### ISSUE TITLE
If SSL for SaaS entitlement is enabled, we should give a better error

### ISSUE THREAD

**Issue by threepointone** [cloudflare/workers-sdk#1013]
(I'll flesh this out with more details later, just logging before I forget) 

Currently we just log the error that the API returns, we should give a better one specifying what should be added to the  configuration. We can also figure out the zone_id for them, that could help. Also internally we should follow up and see if they can default to the zone_id of the given pattern, I think they may not be doing so.

**Comment by ajwootto** [comment]
I just ran into this, from what I could find the workaround is to specify the zone_id along with every route you define:
```
[env.dev]
route = { pattern = "https://dev.my-app.com/*", zone_id="<zone id>" }
```

This is a bit annoying when there's a lot of routes to define and they all have the same zone_id. In `wrangler` 1.x I was able to just define `zone_id` at the top and I guess it applied to every route

**Comment by penalosa** [comment]
Closing in favour of https://github.com/cloudflare/workers-sdk/issues/2953, which tracks the specific issue we have for SSL for SaaS and `zone_id` routes. @threepointone feel free to add more details if this ticket was meant to track more things though!
