### ISSUE TITLE
Refine `wrangler init` package manager detection logic 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/workers-sdk#1014]
We currently look for a package.json/yarn.lock in the cwd to decide which package manager we use to create a project. This isn't particularly useful because: 
- We could be running in a subdirectory of an existing package, and the lockfile wouldn't be there. So we should probably switch to using `findup()` to look for the lockfile 
- More importantly, we're commonly not running in an existing package at all, so we usually end up defaulting to `npm`. The thing to do is to see which package manager is actually calling `wrangler init` and use that (so `npx` or `npm exec` - `npm`, `yarn dlx` - yarn 2+, `pnpm dlx` - `pnpm`)

**Comment by penalosa** [comment]
Fixed by the move to `npm/yarn/pnpm create cloudflare`, since `wrangler init` is now deprecated
