### ISSUE TITLE
feat: rename the routes `custom_domain` option to `origin`

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/workers-sdk#1155]
When specifying a `route` in `wrangler.toml` that should be considered as an origin as part of the [Custom Domain feature](https://blog.cloudflare.com/custom-domains-for-workers/) you currently must use a `custom_domain` flag. E.g.

```toml
routes = [ { pattern = "abc.com", custom_domain = true }]
```

We should consider renaming this to `origin` since that is more aligned with what the route is declaring - i.e. that this Worker should act as the "origin" for request being routed to it. The fact that the product was named "Custom Domains for Workers" is not really accurate here?

```toml
routes = [ { pattern = "abc.com", origin = true }]
```

Since `custom_domain` is now public API, we would continue to support it but mark it deprecated in Wrangler 2.1.0 and then remove it in Wrangler 3.0.0

**Comment by isaac-mcfadyen** [comment]
One possible area of confusion is the product name (Custom Domains for Workers) not matching the origin. This is especially confusing when they're named Custom Domains on the dashboard too.

As long as the documentation is very clear that they mean the same thing though, it might be OK?

**Comment by petebacondarwin** [comment]
Yes, I think if we were to do this then it would probably need to be a product wide change.

**Comment by isaac-mcfadyen** [comment]
In which case I'd very much agree, the Custom Domains name is very confusing and doesn't really make it clear what the difference is between Routes and Custom Domains.

**Comment by petebacondarwin** [comment]
Further indication of the confusing terminology here: https://github.com/cloudflare/wrangler2/issues/1222#issuecomment-1153917580

**Comment by penalosa** [comment]
cc @admah

**Comment by penalosa** [comment]
I'm going to close this for now since the Wrangler option matches the product name. However, I'll raise internally whether Custom Domains is the right name for this feature, and whether it would make sense to rename (at which point Wrangler would change to match that new name)
