### ISSUE TITLE
maintenance: wrangler depends on deprecated npm package `rollup-plugin-inject`

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workers-sdk#1232]
### What version of `Wrangler` are you using?

2.0.9

### What operating system are you using?

mac

### Describe the Bug

```
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
```

Can you please upgrade to the supported package?

**Comment by petebacondarwin** [comment]
This is an upstream issue on the dependency we use for node-compat: https://github.com/ionic-team/rollup-plugin-node-polyfills/pull/32

**Comment by samj** [comment]
This and sourcemap-codec are still WARNing as deprecated as at July 2023.

**Comment by danielkoek** [comment]
Why is this not getting looked at? When I first started using wrangler I thought i installed the wrong SDK because I got all these warnings, seems a bit sloppy to me

**Comment by IgorMinar** [comment]
Updating this version will likely result in a breaking change that might affect unknown (but hopefully only small) number of use-cases. That shouldn't prevent us from updating this. We'll consider this as a change that we'll bundle with a few other minor breaking changes in a future version.

**Comment by mrienstra** [comment]
@IgorMinar, just curious, is https://github.com/cloudflare/workers-sdk/pull/3832 (PR to close this issue) more of a breaking change than https://github.com/cloudflare/workers-sdk/pull/3772 (released in [`wrangler@3.7.0`](https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.7.0)) was?

For convenience: the breaking change in https://github.com/cloudflare/workers-sdk/pull/3772:
> Bump esbuild version to 0.17.19. Breaking changes to esbuild are documented [here](https://github.com/evanw/esbuild/releases/tag/v0.17.0)

(apologies if this isn't a useful question)

**Comment by 1000hz** [comment]
@mrienstra The version of esbuild we bumped to in #3772 was carefully considered so as not to potentially introduce any user-facing breaking changes. Notably, we didn't bump to esbuild@0.18+ since that version includes changes to build output that might affect users in unforeseen ways. We're planning on also making _that_ bump in the next major version of wrangler (#3962)

**Comment by petebacondarwin** [comment]
We've landed the update to esbuild plugins into the v4 branch so closing this as complete.
