### ISSUE TITLE
Pre-filtering to prevent: too much traffic for live tailing

### ISSUE THREAD

**Issue by RaniSputnik** [cloudflare/workers-sdk#1317]
#### Overview and problem statement

We are seeing exceptions in production that we are struggling to diagnose. We have followed all of [the debugging tips]() here, including wrapping our handler in a try/catch and firing off error logs but I still have no visibility into the errors which suggests to me the exceptions are being thrown outside of the handler. Unfortunately, we don't know how to replicate these errors and we're not seeing them in our non-prod environments.

What I would like to do now is pull logs from production, but when trying to use `wrangler tail` I get the following error.

```
$ npx wrangler tail --env master | grep "exception" > exceptions.txt
🦚  Setting up log streaming from Worker script "master". Using ports 8080 and 8081.
⠲   This may take a few seconds...
Error: ⚠️  Code 10057: workers.api.error.too_much_traffic_for_live_tailing
🕵️  See documentation
```

What I'd like to propose is a couple of improvements:

1. Document whether there is _any_ mitigation option available folks who encounter this issue
2. Provide some way to pre-filter logs before they enter the tail pipe

I think many services would seek to provide a sampled tail when traffic is too high, and this might be a great solution, but only if it removed duplicate log entries. If I lost unique (and valuable) exception logs as a result of sampling then that would be equally frustrating.

I understand this request is probably unreasonably difficult, but as it stands today I don't really have any other options.

#### Basic example

Provide a `--sample` flag to indicate that we're happy to only receive a sample of the logs in the given environment.

```
$ npx wrangler tail --sample
```

**Comment by petebacondarwin** [comment]
This is still a problem with Wrangler 2 (since it is actually a problem with our Tail infrastructure and not the Tail Client (e.g. Wrangler). We are working on an internal project to improve this.

**Comment by lrapoport-cf** [comment]
a part of this feature is being addressed in https://github.com/cloudflare/wrangler2/issues/1625

**Comment by petebacondarwin** [comment]
Adding @jspspike to this, as he and I are designing the next phase of the tail improvements that hopefully will allow us to remove the limiter when filters are applied.

**Comment by heathdutton** [comment]
Any updates on this?
I really only care about getting a tal on that one pesky exception out of a million invocations.

If the filters could move forward to the tail infrastructure so that we fit under an acceptable limit that would be swell.

**Comment by jspspike** [comment]
Right now the only way to increase the filtering limit is to use the `--ip self` parameter with tail. This could help debug if you can reproduce the issue yourself.

Removing all limits is planned but no set date yet

**Comment by tiagonbotelho** [comment]
@penalosa I'm still observing this issue on the latest wrangler version 🤔 Could I be doing something wrong perhaps?

```
$ wrangler --version
 ⛅️ wrangler 3.1.0
------------------
$ wrangler tail $MY_WORKER --format=json --sampling-rate=0.01

✘ [ERROR] A request to the Cloudflare API ([REDACTED]) failed.

  This script has too much traffic: 11224 invocations per second, which is over the limit of 200.
  [code: 10057]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

**Comment by petebacondarwin** [comment]
The prefiltering updates are currently being rolled out in stages so we can ensure that we don't suddenly overwhelm the system. Full support should be available by the end of next week. Please try again then.

Perhaps @jspspike, you could give an update when we are close to full rollout?

**Comment by siddhatiwari** [comment]
I'm still getting this issue when trying to tail pages:

```
wrangler pages deployment tail --method "GET"  --project-name $PROJECT_NAME --sampling-rate 0.001
 ⛅️ wrangler 3.23.0
-------------------
No deployment specified. Using latest deployment for production environment.

✘ [ERROR] A request to the Cloudflare API ([REDACTED]) failed.

  This script has too much traffic: 132 invocations per second, which is over the limit of
  100. [code: 8000068]
```

**Comment by petebacondarwin** [comment]
@jspspike - I thought we had rolled out the pre-filtering checks and remove the limiter? But looking at our backend code I still see the limit check being run unless the filters contain `--ip=self`. Can you confirm if this is the case and if so what the plan was to roll out full support?

**Comment by taylorlee** [comment]
@siddhatiwari We fixed an issue that may have been responsible for the error you saw, would you mind trying again and letting me know if you still see the issue? Thanks!

**Comment by siddhatiwari** [comment]
> @siddhatiwari We fixed an issue that may have been responsible for the error you saw, would you mind trying again and letting me know if you still see the issue? Thanks!

I still seem to be getting the issue:
```
wrangler pages deployment tail --method "GET"  --project-name $PROJECT_NAME --sampling-rate 0.001 

 ⛅️ wrangler 3.28.2
-------------------
No deployment specified. Using latest deployment for production environment.

✘ [ERROR] A request to the Cloudflare API ([REDACTED]) failed.

  This script has too much traffic: 102 invocations per second, which is over the
  limit of 100. [code: 8000068]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
  ```

**Comment by taylorlee** [comment]
@siddhatiwari apologies, I read the original issue description and missed the detail that you were specifically using pages tail (as opposed to workers tailing). I took deeper look, and indeed the prior fix I mentioned was applied to Workers but not Pages. It has now been fixes for pages as well though - would you mind trying one more time? :pray:  Your limit should be 10K now.
