### ISSUE TITLE
🚀 Feature Request: Caching previous interactive choices

### ISSUE THREAD

**Issue by geelen** [cloudflare/workers-sdk#1318]
### Describe the solution

Wondering how we might be able to prevent so many interactions when you're using Wrangler a lot across several projects. I think I have an idea for a decent solution, wanted to quickly write it up for discussion before I build it though:

The biggest pain-point right now is remembering which Account you're using, if you have multiple. In the old days, you'd put `account_id` inside your `wrangler.toml`, but that's something we've veered away from now (every time you'd clone a public Worker example—the first thing you'd have to do is go into that config file, delete it, go into the dashboard, find your one, insert it).

For Pages, we threw down something quick (since we wanted the `project_name` as well) into `node_modules/.cache/pages.json`, which works pretty well as long as you _have_ a `node_modules` dir. If you're just deploying a folder full of assets, we accidentally create a `node_modules` dir inside it without asking you, oops...

We already have `.env` for providing `CLOUDFLARE_ACCOUNT_ID` (and others like `CLOUDFLARE_API_TOKEN`), so one approach we could take would be something like:

```
❯ npx wrangler kv:namespace list
Select an account from below:
  Work Account A
  Other Account B
❯ Glenmaddern@gmail.com's Account

Choosing *Glenmaddern@gmail.com's Account*. Run the following command to remember this choice:
echo "CLOUDFLARE_ACCOUNT_ID=dfdd4e8cd3df187b2f25fb7bebad127c" >> .env

...
```

But that feels kinda manual? Imo it'd be great if it just did it for you.

---

### Proposal: use `~/.wrangler/config/caches/<id>.json`

We already maintain the `~/.wrangler/config` directory, why don't we do the following:

* Hash of the current project root dir (i.e. location of nearest `package.json` if present, `pwd` otherwise)
* If any `CLOUDFLARE_` env vars are provided (which might invalidate the info in the cache), hash them separately.
* Read/write to `~/.wrangler/config/caches/project-<pwd-sha1>(.env-<env-sha1>).json`, i.e.
  * if no env overrides are provided, `~/.wrangler/config/caches/project-a1b2c3.json` is used
  * otherwise, use `~/.wrangler/config/caches/project-a1b2c3.env-d4e5b2.json`
* Notify the user which cache file is being used and how to clear it

This has the nice property of not touching the current working directory (no chance of being accidentally committed) but being able to remember arbitrary things. It also means that, say, if a user overrides `CLOUDFLARE_ACCOUNT_ID` in their env, no existing cached values are trusted—the user is prompted for every choice again and those new choices are stored.

A couple of small downsides, though I don't feel like either a dealbreakers

* If they rename/move the project directory, their caches are lost
* If they clone a new project into an old path, they might get a stale cache & have to delete it

This feels like a good tradeoff of convenience with low chances of edge cases, what do you all think?

---

### Addendum `wrangler config`

Rather than tell the user about these oddly-named `project-<hash>.env-<hash>.json` files, we could wrap this in a more generic `wrangler config` command:

* `wrangler config set <key>=<value>`
* `wrangler config delete key`
* `wrangler config clear` (wipes all for project)
* `wrangler config clear --all` (wipes entire cache dir)
* `wrangler config info` (prints out the location of the config file, and maybe all its values)
* Maybe `wrangler config global set NODE_PACKAGE_MANAGER=pnpm` and fuhgeddabout #1202 ?

Imo, then instead of a `Note: we're using config file ...` message on every command, we could instead display a message like:

```
❯ npx wrangler kv:namespace list
Note: reading account_id & 3 other keys from config cache. Run `wrangler config info` to inspect.

...
```

That feels like a fairly neat and tidy warning (it'll be on every command output so anything longer might get irritating). Thoughts?

**Comment by GregBrimble** [comment]
I like it!

Two points:

- > Hash of the current project root dir (i.e. location of nearest `package.json` if present, `pwd` otherwise)

    `package.json` rather than `wrangler.toml`?

- > If they clone a new project into an old path, they might get a stale cache & have to delete it

    Depending on the file system/OS, we could get the stat of the cache and the directory and purge the cache if it's older?

**Comment by petebacondarwin** [comment]
I feel bad filling up the config directory with these cache files without a well defined clearing functionality.
I feel like the `node_modules/.cache` approach is safer, since it will be naturally cleaned up.

**Comment by geelen** [comment]
Rather than using lots of files, then, we could store a single JSON file, with a TTL for each entry (keeping the same semantics of using the hash of the `pwd` and `env` to keep config separate, just as a top-level key now instead). Every time the config is loaded, the TTL of the current project could be extended, and any other entries that have expired can be pruned.

Then a user can nuke their entire cache with a `rm ~/.wrangler/config/cache.json`. But it's a bit harder for them to find and update a single project's values, so might make sense to implement the `wrangler config set|delete|clear|info` commands.

**Comment by penalosa** [comment]
I'm going to close this for now, since a mechanism for caching interactive account choices has been added to Wrangler (which seemed like the primary use case here). There's definitely room for improvement in the caching though, and that might be worth a separate discussion.
