### ISSUE TITLE
Promote unstable_dev() to dev()

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#1420]
This issue will track the issues required to promote `api/unstable_dev()` to `api/dev`

- We should rewrite our local-mode tests to use unstable_dev: 
  - https://github.com/cloudflare/wrangler2/issues/1419
  - this is blocked until we implement a react-free version of `unstable_dev`, as it doesn't currently work in CI:
    - https://github.com/cloudflare/wrangler2/pull/1538
- https://github.com/cloudflare/wrangler2/issues/1756
- The API needs to export its types for consumers, tracked by: 
  - https://github.com/cloudflare/wrangler2/issues/1387
- We need to finalise the types that `dev` uses for the options config: 
  - https://github.com/cloudflare/wrangler2/issues/1418
- Stabilize unstable_dev's options
  - https://github.com/cloudflare/wrangler2/issues/2344

**Comment by caass** [comment]
> FWIW @caass we're months away from promoting any of the `unstable_` APIs, I just wanted a chunky issue to track the effort involved

😬 whoops sorry i came off strong, i understand !! i can remove my comment if you like :)

**Comment by lmcarreiro** [comment]
> * //TODO: add more things to this list

When we import wrangler package, it's sending the wrangler help to the output. To avoid that, I had to do this dirty replacement in the compiled cli.js file:

```bash
sed -i 's|  \(main(hideBin(\)|  /**/import_process.default.argv.some(arg => arg.endsWith("wrangler/wrangler-dist/cli.js")) \&\& \1|' $cliPath
```

```diff
 // src/cli.ts
 if (typeof jest === "undefined" && require.main) {
-  main(hideBin(import_process.default.argv)).catch((e2) => {
+  /**/import_process.default.argv.some(arg => arg.endsWith("wrangler/wrangler-dist/cli.js")) && main(hideBin(import_process.default.argv)).catch((e2) => {
     const exitCode = e2 instanceof FatalError && e2.code || 1;
     import_process.default.exit(exitCode);
   });
 }
```

**Comment by lmcarreiro** [comment]
Also, it would be good to expose the `createTail` too. I'm using the same dirty replacement to use it right now to export it:

```bash
sed -i 's|  \(unstable_dev: () => unstable_dev\)|  /**/\1,createTail: () => createTail|' $cliPath
```
```diff
 // src/cli.ts
 var cli_exports = {};
 __export(cli_exports, {
-  unstable_dev: () => unstable_dev
+  /**/unstable_dev: () => unstable_dev,createTail: () => createTail
 });
 module.exports = __toCommonJS(cli_exports);
 init_import_meta_url();
```

**Comment by rozenmd** [comment]
Hey @lmcarreiro,

regarding:
> When we import wrangler package, it's sending the wrangler help to the output

That's very weird - could you share more details about your setup?

**Comment by lmcarreiro** [comment]
> > When we import wrangler package, it's sending the wrangler help to the output
> 
> That's very weird - could you share more details about your setup?

There is nothing special, if I create a new project I can reproduce that easily:

```bash
npm init
echo "const { unstable_dev } = require('wrangler'); console.log(typeof unstable_dev);" > index.js
npm install wrangler --save
node .
```

![image](https://user-images.githubusercontent.com/13019179/197072873-3c6f33fe-ccd6-4c52-8511-95ca9028ac5d.png)

> We're also looking at exposing an `unstable_tail` API soon - how are you using `createTail`?

I put the details in the comment above https://github.com/cloudflare/wrangler2/issues/1420#issuecomment-1281725738, it's dirty, but it works. This `createTail` function is not exported, so I make changes in the node_modules/wrangler/wrangler-dist/cli.js to expose it.

**Comment by rozenmd** [comment]
Hey @lmcarreiro I've resolved the `help` issue in https://github.com/cloudflare/wrangler2/pull/2052 - if you install `wrangler@2.1.13` it should resolve the issue:

```bash
Wrote to /Users/rozenmd/Testing/test12/package.json:

{
  "name": "test12",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Max Rozen",
  "license": "ISC"
}


npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.

added 102 packages, and audited 103 packages in 870ms

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
function
```

**Comment by lmcarreiro** [comment]
Thank you! Now my only dirty change into the cli.js is to expose the `createTail`. I'll appreciate whenever you expose the `unstable_tail` API.

**Comment by JustinGrote** [comment]
Sorry to necro but as this appears to never have been merged, I assume we are still to use unstable_dev for testing?

**Comment by rozenmd** [comment]
Yep @JustinGrote `unstable_dev` is still the way to integration test your Workers. I moved over to the D1 team, so not sure what the progress is here.

**Comment by penalosa** [comment]
We'll be addressing this as part of the Wrangler as a Library work, and so I'm going to close this issue for now. You can track the status of that work here: https://github.com/cloudflare/workers-sdk/milestone/11
