### ISSUE TITLE
Support local hostnames w/ TLS for `wrangler dev` remote mode

### ISSUE THREAD

**Issue by jed** [cloudflare/workers-sdk#1461]
(submitted by request from [discord](https://discord.com/channels/595317990191398933/799437470004412476/996425965553078422))

Currently, there is no way to get wrangler remote mode to bind to a local hostname. This prevents users from testing wildcard subdomains and workers based on Cloudflare for SaaS, since there is no way to provide a TLS certificate, no way to bind to a hostname other than localhost, and no way to provide a zone not registered with Cloudflare. For example, I have a production worker that responds to subdomain wildcards on zone mydomain.com, allowing `https://some-random-string.mydomain.com` urls, and a development version of the worker that does the same locally, allowing `https://some-random-string.mydomain.com.test` urls.

This use case is well served by wrangler local mode thanks to Miniflare (along with [DNSMasq and mkcert on macOS](https://blog.cdivilly.com/2020/06/15/localhost-wildcard_https)), which allows bindings to arbitrary hostnames provided, backed up by custom certificates provided in `[miniflare.https]` in `wrangler.toml`. It would be nice to see parity with this support for remote mode.

**Comment by threepointone** [comment]
Assigning to @cameron-robey for exploring solutions

**Comment by Wallacy** [comment]
FWIW: For people like me that uses Workers Sites that is also relevant. My Worker Sites uses de subdomain as key to change the entry point of the index and others things.
