### ISSUE TITLE
🚀 Feature Request: Custom path for env files

### ISSUE THREAD

**Issue by hpohlmeyer** [cloudflare/workers-sdk#1468]
### Describe the solution

The undocumented `.dev.vars` file is really handy to populate secrets in local mode, since you do not need to modify the toml file.

Most projects use a `.env` file that is not checked in to read environment variables locally. In order to use the same variables for Wrangler, you would need to copy the variables you need for the worker from the `.env` file to the `.dev.vars` file. It would be nice to use the `.env` instead. This could be solved by supporting a custom path that for `dotenv`.

Miniflare supports [custom env file paths](https://miniflare.dev/core/variables-secrets#env-files) through the `--env` flag or a `env_path` entry in the `wrangler.toml` (nice for different environments). It would be nice to see a similar API in wrangler.

**Comment by andywwright** [comment]
> we wouldn't be able to make this change

This sounds a bit strange to me... A lot of people in at least seven topics vote for using .env at a project level just to be told that it is impossible to implement, but moving wrangler's own settings to something like .wrangler.env does not look that difficult.

I appreciate it is a breaking change and the Team obviously has more important issues to deal with, so it's more like unwillingness, not "wouldn't be able"...

**Comment by upokusaev** [comment]
I have to use a workaround so I don't forget to accidentally duplicate variables. I hope it will help someone:

1. Create a `copy_env.sh` file with the contents:
```bash
#!/bin/bash

# Check if the .env file exists
if [ -f ".env" ]; then
    # Copy the contents of .env to .dev.vars
    # If .dev.vars exists, it will be overwritten
    cp ".env" ".dev.vars"
    echo "File .dev.vars created or updated with contents from .env"
else
    echo "File .env not found"
fi
```

2. Before running the local server, run `sh copy_env.sh && <your command to run server>`.
