### ISSUE TITLE
🚀 Feature Request: Urgently need a way to disable redirects from `foo.html` to `foo` with Pages

### ISSUE THREAD

**Issue by Hexstream** [cloudflare/workers-sdk#1488]
### Describe the solution

When navigating to a URL such as `https://example.com/foo.html`,
Pages for some reason redirects to `https://example.com/foo`.

Unfortunately, this "feature" is simply **_disastrous_** for my use-cases, and I **urgently** need a way to disable it, especially since there does not seem to be any workaround. (This is my only remaining blocker for finishing the long-overdue migration of my 25+ subdomains to Pages.)

First of all, I think it obviously doesn't make sense to **force users to change tons of their URLs _just because they're changing their underlying infrastructure_**. [Cool URLs don't change](https://www.w3.org/Provider/Style/URI), remember? Also, if someone uniformly had as many `foo.html` URLs across all their websites, but only migrated half their websites to Pages, then this would mean that half of their websites would use `foo` and the other would use `foo.html`, leading to gratuitous and confusing inconsistencies.

Second, I realize this may be uncommon, but this "feature" interacts _catastrophically_ with websites that already have different pages for `foo.html` and `foo`. In fact, one of my websites does this extensively. I have this nice naming convention (that I really don't want to abandon) where I have `foo.swf` for a flash file and then I have `foo.swf.html` for the embedding page that uses [Ruffle](https://ruffle.rs/) for playback. Right now, were I to migrate this website to Pages, I would have to either:

1. move all `foo.swf` to new URLs, and `foo.swf` would now incorrectly serve `foo.swf.html`, frustrating users who wanted the flash file.

2. move all `foo.swf.html` to new URLs, and `foo.swf.html` would now incorrectly serve `foo.swf`, frustrating users who wanted the embedding page.

In short, if this "feature" cannot be disabled easily, then this is a no-win situation for anyone who wants to migrate to Pages and has similarly conflicting URLs.

Third, this "feature" effectively requires (for best semantics and performance) changing the canonical URLs of all `foo.html` files (and any links pointing to them) to the equivalent `foo` URL, which is potentially a HUGE burden of work, depending on infrastructure. As it happens, I have been writing all my websites in raw HTML, CSS and JS for more than a decade, and updating all those damn links manually would be quite a hassle. (And I bet there are many people out there for whom the burden would be exponentially heavier.)

Fourth, I already migrated one of my websites with a few `foo.html` files to Pages, meaning I am currently exposing and supporting apparently-canonical `foo` URLs, something I never even wanted to do in the first place. Once I can go back to supporting `foo.html` only, I would either have to break all links pointing to `foo` URLs, or support redirects forever, both of which are obviously undesirable. In short, any `foo` URLs that I am temporarily forced to support are a "ticking time bomb", the longer they are exposed, the more users will suffer when I stop supporting them.

Fifth, I actually noticed just now that `foo.html` supports not only `foo.html` and `foo`, but also `foo/`! This means that any `foo.html` file will conflict with `foo/index.html`. It's just crazy to me that all `foo.html` files are automatically and forcibly accessible under 3 different URLs.

Anyway, I hope my presentation was not too annoying, but this is a really critical and aggravating issue that I urge you to fix ASAP. I don't even think this "feature" should be enabled by default, but I would be satisfied if it was very easy to disable it. Thank you.

**Comment by Hexstream** [comment]
As for the means to disable this feature, one idea would be accepting

strip-html-suffixes=false

as the very first line of the `_redirects` file. This is simple, logical, efficient and extensible. More such special directives could eventually be accepted on separate lines only at the start of the file before normal redirection directives.

**Comment by Hexstream** [comment]
I was able to work around this issue with Workers, not without some pain.

This solves my issue in the short term, but a simple native solution would be strongly preferred.

**Comment by Hexstream** [comment]
Now that [Cloudflare Pages supports `wrangler.toml`](https://developers.cloudflare.com/pages/functions/wrangler-configuration/), this would be easier to implement.

`wrangler.toml` could just accept `strip-html-suffixes = false` to opt-in to this new behavior.

`strip-html-suffixes = true` would be the default so as to retain backwards compatibility.

_Could you please implement this crucial feature soon?_

**Comment by Hexstream** [comment]
This is a widely requested feature in the Cloudflare community,
here are the first 10 topics I found (in descending order of views):

[Pages redirect missing .html extension file name issue](https://community.cloudflare.com/t/pages-redirect-missing-html-extension-file-name-issue/263026)
[Prevent truncating and removal of page name extensions?](https://community.cloudflare.com/t/prevent-truncating-and-removal-of-page-name-extensions/388845)
[Cloudflare Pages Route matching problem](https://community.cloudflare.com/t/cloudflare-pages-route-matching-problem/319869)
[How to enable trailing ‘.html’ from url](https://community.cloudflare.com/t/how-to-enable-trailing-html-from-url/358212)
[Cloudflare Pages Route Matching: Disable extensionless HTML redirect](https://community.cloudflare.com/t/cloudflare-pages-route-matching-disable-extensionless-html-redirect/397505)
[React app deployed to clouldflare, url automatically removes .html](https://community.cloudflare.com/t/react-app-deployed-to-clouldflare-url-automatically-removes-html/389199)
[Any updates on Route matching vs .html?](https://community.cloudflare.com/t/any-updates-on-route-matching-vs-html/559126)
[Automatic redirect pages without .html](https://community.cloudflare.com/t/automatic-redirect-pages-without-html/574596)
[Cloudflare Pages url redirect](https://community.cloudflare.com/t/cloudflare-pages-url-redirect/595311)
[Cloudflare Pages truncates URLs by removing the “.html” extension](https://community.cloudflare.com/t/cloudflare-pages-truncates-urls-by-removing-the-html-extension/609238)

I realize this is on the roadmap, hopefully we can get this crucial feature in 2024?

It's a big blocker for many people, it will be a great day when this is implemented!

**Comment by dc-95** [comment]
@Hexstream , can you share how you worked around it? Having the same issue as well

**Comment by Hexstream** [comment]
Yes, at the time I used **1. a Worker for some easy cases** and **2. `_worker.js` for some more complex cases**.

I am looking to migrate my workarounds to [Pages Functions](https://developers.cloudflare.com/pages/functions/) soon.

I am hoping Birthday Week in September will bring nice improvements to Pages, including fixing this critical issue.

Here is my code for **1. the `nostrip-html-suffixes` Worker:**

`wrangler.toml`:

```
name = "nostrip-html-suffixes"
compatibility_date = "2022-07-22"

main = "./worker.js"
usage_model = "bundled"

workers_dev = false
routes = [
       { pattern = "https://modern.pokehidden.archive.hexstream.net/*", zone_name = "hexstream.net" },
       { pattern = "https://dumping-grounds.hexstream.xyz/archived/ert.hexstream.xyz/FlyHighWithYourDreams*", zone_name = "hexstream.xyz" }]

minify = false
node_compat = false
```

`worker.js`:

```
export default {
  async fetch (request) {
      function passthrough (url) {
          return fetch(new Request(url), {
              method: request.method,
              headers: request.headers
          });
      }
      const url = request.url;
      if (url.endsWith(".html"))
          return passthrough(url.slice(0, -5));
      const urlNoSlash = url.endsWith("/") ? url.slice(0, -1) : url;
      const htmlResponse = await passthrough(urlNoSlash + ".html");
      if (htmlResponse.ok)
          //return passthrough(urlNoSlash + ".404");
          return Response.redirect(urlNoSlash + ".html", 301);
      else
          return fetch(request);
  }
};

/*

Unwanted effects:

/foo.html redirects to /foo
/foo and /foo/ serve /foo.html

Solution:

/foo.html serves former /foo
/foo and /foo/ do not exist if /foo.html exists

*/
```

And here is my code for **2.  `_worker.js`**:

```
export default {
    async fetch(request, env) {
        function passthrough (url) {
            return env.ASSETS.fetch(url.toString(), {
                method: request.method,
                headers: request.headers,
                cf: request.cf
            });
        }
        const url = new URL(request.url);
        const pathname = url.pathname;
        if (pathname.startsWith('/workaround/')) {
            url.pathname = "/workaround/";
            return passthrough(url);
        }
        if (pathname.endsWith('.swf.html')) {
            url.pathname = "/workaround/html" + pathname.slice(0, -5);
            return passthrough(url);
        }
        if (pathname.endsWith('.swf')) {
            url.pathname = "/workaround/swf" + pathname;
            return passthrough(url);
        }
        if (pathname.endsWith(".html")) {
            url.pathname = pathname.slice(0, -5);
            return passthrough(url);
        }
        if (pathname.endsWith("/"))
            url.pathname = pathname.slice(0, -1);
        const urlHtml = new URL(url);
        urlHtml.pathname += ".html";
        const urlNotFound = new URL(url);
        urlNotFound.pathname += ".404";
        const htmlResponse = await passthrough(urlHtml);
        if (htmlResponse.ok)
            return passthrough(urlNotFound);
        else
            return env.ASSETS.fetch(request);
    }
};
```

I hope this helps in any way, but I cannot guarantee the quality of the above soon-to-be-legacy code...

**Comment by Parrot7483** [comment]
Another reason to implement this feature: The redirect causes my pages to load in 250ms instead of 140ms. Hugo can not generate pages that would not be redirected by cloudflare.

**Comment by emily-shen** [comment]
Just to add that with the new [Workers + static assets](https://developers.cloudflare.com/workers/static-assets/) you can set `html_handling = "none"` to disable redirects. Assets is in beta atm but would probably be the recommended solution going forwards.

**Comment by Hexstream** [comment]
Great! I guess I'll wait until that feature makes it to Pages.
I'm looking forward to further Pages/Workers convergence...

**Comment by Hexstream** [comment]
Oh, and by the way I did migrate my workarounds to Pages Functions back in June.
Sorry for not sharing this earlier, I've been quite busy...

So, the workaround is now much simpler, here is an example `assets/_routes.json`:

```
{
    "version": 1,
    "include": ["/images/1.html",
                "/images/1",
                "/images/2.html",
                "/images/2",
                "/images/3.html",
                "/images/3",
                "/images/4.html",
                "/images/4",
                "/images/5.html",
                "/images/5",
                "/images/6.html",
                "/images/6",
                "/images/7.html",
                "/images/7",
                "/images/8.html",
                "/images/8",
                "/images/9.html",
                "/images/9",
                "/images/10.html",
                "/images/10",
                "/images/11.html",
                "/images/11",
                "/images/12.html",
                "/images/12",
                "/images/nsfw/1.html",
                "/images/nsfw/1",
                "/images/nsfw/2.html",
                "/images/nsfw/2",
                "/images/nsfw/3.html",
                "/images/nsfw/3",
                "/images/nsfw/4.html",
                "/images/nsfw/4",
                "/images/nsfw/5.html",
                "/images/nsfw/5",
                "/images/nsfw/6.html",
                "/images/nsfw/6",
                "/images/sfw/1.html",
                "/images/sfw/1",
                "/images/sfw/2.html",
                "/images/sfw/2",
                "/images/sfw/3.html",
                "/images/sfw/3",
                "/images/sfw/4.html",
                "/images/sfw/4",
                "/images/sfw/5.html",
                "/images/sfw/5",
                "/images/sfw/6.html",
                "/images/sfw/6",
                "/fanart/1.html",
                "/fanart/1",
                "/fanart/2.html",
                "/fanart/2",
                "/fanart/3.html",
                "/fanart/3",
                "/fanart/4.html",
                "/fanart/4"],
    "exclude": []
}
```

This tells Pages Functions for which specific pages to execute `functions/_middleware.js`:

```
function passthrough (context, url) {
    const request = context.request;
    return context.next(new Request(url), {
        method: request.method,
        headers: request.headers
    });
}

function serve(context) {
    const request = context.request;
    const url = new URL(request.url);
    url.pathname = url.pathname.slice(0, -5);
    return passthrough(context, url);
}

function suppress(context) {
    const request = context.request;
    const url = new URL(request.url);
    let pathname = url.pathname;
    if (pathname.endsWith("/"))
        pathname = pathname.slice(0, -1);
    url.pathname = pathname + ".404";
    return passthrough(context, url);
}

export async function onRequestGet(context) {
    const url = new URL(context.request.url);
    if (url.pathname.endsWith(".html"))
        return serve(context);
    else
        return suppress(context);
}
```

**Comment by emily-shen** [comment]
@Hexstream I think our Workers + Pages convergence plan is centred around adding Pages features to Workers, rather than the other way around. Would be interested in hearing if there's anything blocking you from moving to Workers + Assets though! https://developers.cloudflare.com/workers/static-assets/compatibility-matrix/

**Comment by Hexstream** [comment]
> I think our Workers + Pages convergence plan is centred around adding Pages features to Workers, rather than the other way around.

Right, that's what I suspected.

> Would be interested in hearing if there's anything blocking you from moving to Workers + Assets though!

Simply put, **I don't think I would have much to gain from migrating from Pages to Workers + Assets _right now_, and I think I have A LOT to gain from waiting at least until the next Birthday Week in September (when it would presumably be out of beta) to do so.** I'm pretty sure by that time we'll be MUCH deeper into the Pages/Workers convergence and I could expect a pretty seamless and painless experience. Right now, _not necessarily,_ perhaps.

Looking at the compatibility matrix, I see that Workers + Assets is missing some Pages features I actively use, these can be worked around but are readily apparent additional points of friction over the ones I would have to dig deeper to find.

- Custom HTTP headers for static assets
- Middleware (Light use only for workarounds now, but heavy use starting in 2025)
- Redirects (btw redirecting to other domains should be just as easy as within the same domain...)
- File-based Routing

Right now, I have [25 subdomains over 4 main websites](https://abc.hexstream.xyz/websites/), all with [one nice unified architecture](https://status-quo.hexstream.expert/services/cloudflare/).

**Whenever I migrate from Pages to Workers + Assets, I want to do it _all in one shot,_ and I don't want to flail around.**
That means I read all the documentation and then migrate everything.

**I'd really much rather read all the GA documentation and then use the GA platform and have a seamless experience than read all the Beta documentation and then use the Beta platform and likely come across some limitations which will be fixed anyway in the GA version**, and I have a LOT of other work to do anyway while "waiting".

I hope this is to your satisfaction. :)

**Comment by emily-shen** [comment]
Thanks for the detailed feedback @Hexstream! Don't at all mean to rush anyone to move before GA, just good to get feedback in case there's any missing pieces for GA, so really appreciate this :) 

(cc @korinne)

**Comment by emily-shen** [comment]
However, closing as not planned for Pages.

**Comment by Hexstream** [comment]
_Alrighty-o!_ :)
