### ISSUE TITLE
assets: CORS support 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/workers-sdk#1556]
For `--assets` / `config.assets`, a couple of features: 

- Let's actually just enable CORS for static assets by default
- Add a configuration `cors: boolean`
- Allow for further customisation via `_headers` (when we implement it)

**Comment by GregBrimble** [comment]
Pages automatically adds the `access-control-allow-origin': '*'` header which is safe to do for static assets. I'd support adding this to `--assets` by default too.

We let people unset headers with `_headers` like so:

```txt
/*
  ! access-control-allow-origin
```

**Comment by penalosa** [comment]
I’m going to close this issue for now. Going forward, we’ll revisit the assets system as part of Pages/Workers convergence, and will inherit the benefits of the Pages assets system.
