### ISSUE TITLE
🐛 BUG: response headers for `assets` break iframes / FEATURE: make asset response headers configurable

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workers-sdk#1698]
### What version of `Wrangler` are you using?

2.0.26

### What operating system are you using?

Mac

### Describe the Bug

I have an application that contains several `.html` files uploaded to a worker using `assets`.

These `.html` files are then loaded into an iframe created by my app.

By default this doesn't work because all assets are served with `X-Frame-Options: DENY` header:

[`response.headers.set("X-Frame-Options", "DENY");`](https://github.com/cloudflare/wrangler2/blob/c0343304b0adaddfed3087298c9634c701fae8b2/packages/wrangler/templates/serve-static-assets.ts#L49
)

This is would a reasonable default if the headers were customizable, which doesn't seem to be the case.

Could we add a way to customize these headers (while offering good defaults)?

**Comment by threepointone** [comment]
tbh, the defaults for the current assets implementation were copy-pasted from an example, so they're totally up for changes to be better defaults. 
https://github.com/cloudflare/wrangler2/blob/eb75413ec35f6d4f6306601f4d5c9d058f794a18/packages/wrangler/templates/serve-static-assets.ts#L47-L51

We also want to implement `_headers` support much like pages has. 

So as as quick fix, I'd be happy to accept a PR/suggestions on what the defaults should be, and we can prioritise work on implementing `_headers`

**Comment by penalosa** [comment]
Going forward, we’ll revisit the assets system as part of Pages/Workers convergence, and will inherit the benefits of the Pages assets system.
