### ISSUE TITLE
🐛 BUG: wrangler dev shows "Script not found"

### ISSUE THREAD

**Issue by bjesus** [cloudflare/workers-sdk#1717]
### What version of `Wrangler` are you using?

2.0.26

### What operating system are you using?

Linux, Mac

### Describe the Bug

We are a Cloudflare team working on Zaraz, recently switched to using `wrangler dev` for local development purposes. Quite often when launching `wrangler dev`, we get a `1104 Script not found` error. This happens to all of our team members, usually at the same time, and it just gets resolved by itself, without any changes to our Worker code.

![screenshot_2022-08-22_11-45-24_494046891](https://user-images.githubusercontent.com/55081/185892347-1bc9785a-c635-492c-abf0-c589e5d0d050.png)

**Comment by JacobMGEvans** [comment]
Contacting @alankemp and will ping internally.

**Comment by rozenmd** [comment]
After chatting about this with @petebacondarwin and @bjesus, we think the issue might be a worker name collision, will make a PR with a fix

**Comment by lrapoport-cf** [comment]
@rozenmd per your last comment, did you make a PR for this?

**Comment by rozenmd** [comment]
Good call out @lrapoport-cf - I've updated my comment.

**Comment by bjesus** [comment]
@rozenmd - are we sure it wasn't? the issue is completely solved for us since we wrapped `wrangler dev` with a shell script that generates random worker names...

**Comment by lrapoport-cf** [comment]
we've created an internal ticket to investigate the issue with the preview session service

**Comment by penalosa** [comment]
Closing in favour of the internal ticket [EW-6904](https://jira.cfdata.org/browse/EW-6904). Of note, Wrangler 3 uses local mode for `dev` by default, which shouldn't exhibit the same issue

**Comment by anthonycorletti** [comment]
is this resolved? im getting 1104s when using `wrangler deploy`. my workflow is: deploy previews with `wrangler versions upload` and deploy to production with `wrangler deploy`. im just using the default preview names that workers gives me.

**Comment by petebacondarwin** [comment]
@anthonycorletti - are you trying to hit the preview URLs before doing any deployment (i.e. only a version upload)? Also does it resolve itself after a bit (i.e. is it just that the Worker upload has not yet propagated)?

**Comment by anthonycorletti** [comment]
@petebacondarwin nope. It was really strange. I could reach previews but not production. My fix was deleting the worker and recreating it.

**Comment by petebacondarwin** [comment]
I've asked internally. The team said if it is still an issue then to create a separate issue that they can look into.
I wonder (from what you say) that this Worker just got into a weird broken state?
