### ISSUE TITLE
Feature: `wrangler init --from-dash` with an environment

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/workers-sdk#1751]
Currently the `wrangler init --from-dash` only grabs the default environment for initializing a project. We eventually would like to be able to choose which environment is initialized in the project. 

i.e. `wrangler init --from-dash my-worker --env staging`

_Originally posted by @petebacondarwin in https://github.com/cloudflare/wrangler2/pull/1729#discussion_r958343133_

**Comment by penalosa** [comment]
Closing since service environments have been deprecated. This can be revisited in the future once Wrangler and the API have a more 1:1 notion of environments
