### ISSUE TITLE
🚀 Feature Request: Remove OAuth authorization from the web dashboard

### ISSUE THREAD

**Issue by caizixian** [cloudflare/workers-sdk#1800]
### Describe the solution

Currently, it seems that there's no way to remove any authorized OAuth application using the web UI, and revoking an OAuth token requires running `wrangler logout` on the machine where the original `wrangler login` was run. This can be a problem, say, if the dev machine is lost.

**Comment by admah** [comment]
This work is in progress with our Dashboard team, but I'm not sure on an ETA. That work will provide a way to revoke tokens via the dashboard UI.

 I'm going to close this out from this repo, as it is not directly related to Wrangler, and there are documented workarounds for developing via Wrangler.

**Comment by letanloc1998** [comment]
Dear fork,

Does Cloudflare support revoke authorization from dashboard now?

Many thanks.
