### ISSUE TITLE
🚀 Feature Request: `worker.scheduled()` in `unstable_dev` for testing

### ISSUE THREAD

**Issue by cameron-robey** [cloudflare/workers-sdk#1804]
### Describe the solution

For testing, it could be useful to be able to call `worker.scheduled()` alongside `worker.fetch()` to be able to write tests for functionality in scheduled events.

**Comment by unibeck** [comment]
Any update on this?

**Comment by RamIdeas** [comment]
Hi @cameron-robey, thanks for this feature request! We are currently working on improvements for unstable_dev and are considering this as part of the API coming in a future release of Wrangler

**Comment by penalosa** [comment]
This has been addressed as part of the start dev worker work. You can now:

```ts
import { startWorker } from "wrangler"

const worker = await startWorker(...)

await worker.scheduled(...)
```
