### ISSUE TITLE
🚀 Feature Request: Auto-Purge Default Cache with `pages dev`

### ISSUE THREAD

**Issue by helloimalastair** [cloudflare/workers-sdk#1919]
### Describe the solution

Currently, when using the `--persist` flag with `wrangler pages dev`, the cache is entirely persisted to disk. While this is handy for emulating/testing cache behavior, it is difficult to use it for development purposes. Conversely, `--persist` is handy for caching Function calls/KV entries, so just not using the flag isn't ideal.

It would be nice if there were a way to have `wrangler` add a key to items stored to the Cache by the Pages Fileserver and then automatically clear assets with said key whenever changes are observed in the *build output directory*. This might also be good to have for Functions Cache too, depending on the setup of the user's Functions.

This could be made as default behavior or as a separate flag.

**Comment by jahands** [comment]
> add a key to items stored
What are some examples of these keys, and the items they contain?

**Comment by helloimalastair** [comment]
@jahands, the format of the key doesn't really matter(at least to the end user/developer), nor does it even need to be accessible to them. It would just be nice for `wrangler` to have a way to recognize cached static files, and clear them when the *build output directory* updates, or when the project is rebuilt, so that static assets are cleared.

**Comment by jrf0110** [comment]
This seems like a `wrangler dev` feature request, since `wrangler pages dev` inherits options from there. @rozenmd  does this seem like a reasonable feature request for wrangler dev?

**Comment by rozenmd** [comment]
@cloudflare/wrangler / @cloudflare/pages  - I wonder if this isn't a feature request for a base `wrangler` command/API for clearing the persistence cache

**Comment by helloimalastair** [comment]
@rozenmd, it might be good to have as an API, but it would also be good to have it as a flag on `wrangler pages dev`, so that a user doesn't have to manually clear the cache every time they reload.

**Comment by CarmenPopoviciu** [comment]
hey @helloimalastair 

is this still an issue for you? I'm trying to reproduce but am not able. If you're still experiencing issues, can you pls provide us with a repro to get a better understanding of what it is your are seeing

<3

**Comment by helloimalastair** [comment]
It appears that this issue no longer occurs. Thanks for the follow up!
