### ISSUE TITLE
🐛 BUG: fetching bound registered workers in local mode fails with timeout

### ISSUE THREAD

**Issue by helloandre** [cloudflare/workers-sdk#1920]
### What version of `Wrangler` are you using?

2.1.6

### What operating system are you using?

M1 Pro macOS 12.6

### Describe the Bug

When running `wrangler pages dev`, after some delay (presumably the timeout mentioned in the error) this error is being output several times per second until the server is stopped.

```
▲ [WARNING] Failed to get worker definitions TypeError: fetch failed

      at Object.processResponse
  (/Users/andre/code/wrangler-bug/node_modules/wrangler/wrangler-dist/cli.js:8846:27)
      at /Users/andre/code/wrangler-bug/node_modules/wrangler/wrangler-dist/cli.js:9178:42
      at node:internal/process/task_queues:140:7
      at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
      at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    cause: ConnectTimeoutError: Connect Timeout Error
        at onConnectTimeout
  (/Users/andre/code/wrangler-bug/node_modules/wrangler/wrangler-dist/cli.js:2870:29)
        at /Users/andre/code/wrangler-bug/node_modules/wrangler/wrangler-dist/cli.js:2828:51
        at Immediate._onImmediate
  (/Users/andre/code/wrangler-bug/node_modules/wrangler/wrangler-dist/cli.js:2859:13)
        at process.processImmediate (node:internal/timers:471:21) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }
```

### steps to reproduce:

 - `npx create-remix@latest` 
     - name
     - Just The Basics
     - Cloudflare Pages
     - Typescript
     - Y
 - `npm run dev` 
 - wait 10-15 seconds.

Note: I do not have wrangler installed globally, and have tried running this same command after running `npx wrangler login` and the error is still output.

**Comment by helloandre** [comment]
The reason this is happening is the same reason of #1864 which fundamentally will never work with the current usage of `child_process.fork`

`startWorkerRegistry()` fails, because `isPortAvailable()` will never be true. `isPortAvailable` even handles this case specifically and calls `resolve(false)` in the case of an `EADDRINUSE` in use.

**Comment by cmoog** [comment]
I'm encountering this error as well on `2.3.2`

**Comment by craigsc** [comment]
Also hitting this while running a Remix app on both 2.2.1 and 2.3.2 wrangler

**Comment by stefandanaita** [comment]
This started happening to me today on 2.4.4 :(

**Comment by tom-sherman** [comment]
Had this on 2.2.1, upgraded to 2.4.4 and still have the issue

**Comment by tom-sherman** [comment]
I fixed this on my machine by finding the port listening on 6284 (the dev registry server) and force quitting this. I'm on macos and performed the following steps:

```
sudo lsof -i -P | grep LISTEN | grep :6284
```

This outputted the process name ("node") and the PID. I then found this process in Activity Monitor and force quit it.

Restarting your machine would probably do a similar job.

**Comment by gkiely** [comment]
I was able to reproduce this by starting wrangler, stopping it, deleting my project, git cloning then starting again.

**Comment by Eusebiotrigo** [comment]
I'm not sure it is the same bug, but I'm getting this:

```
Failed to get worker definitions TypeError: fetch failed

      at fetch10
  (/Users/blah/backend/cloudflare-workers/account/node_modules/wrangler/wrangler-dist/cli.js:13582:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async getRegisteredWorkers
  (/Users/blah/backend/cloudflare-workers/account/node_modules/wrangler/wrangler-dist/cli.js:120431:22)
      at async getBoundRegisteredWorkers
  (/Users/blah/backend/cloudflare-workers/account/node_modules/wrangler/wrangler-dist/cli.js:120449:29)
  {
    cause: ConnectTimeoutError: Connect Timeout Error
        at onConnectTimeout
  (/Users/blah/backend/cloudflare-workers/account/node_modules/wrangler/wrangler-dist/cli.js:6526:29)
        at
  /Users/blah/backend/cloudflare-workers/account/node_modules/wrangler/wrangler-dist/cli.js:6484:51
        at Immediate._onImmediate
  (/Users/blah/backend/cloudflare-workers/account/node_modules/wrangler/wrangler-dist/cli.js:6515:13)
        at process.processImmediate (node:internal/timers:471:21) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }
```
Then I can kill the worker, either via kill -9 <pid> or control+C or pressing `x`, and even then I get this log out:
```
[ERROR] Failed to unregister worker TypeError: fetch failed

      at fetch10
  (/Users/blah/backend/cloudflare-workers/account/node_modules/wrangler/wrangler-dist/cli.js:13582:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async unregisterWorker
  (/Users/blah/backend/cloudflare-workers/account/node_modules/wrangler/wrangler-dist/cli.js:120418:5)
      at async Promise.allSettled (index 0) {
    cause: ConnectTimeoutError: Connect Timeout Error
        at onConnectTimeout
  (/Users/blah/backend/cloudflare-workers/account/node_modules/wrangler/wrangler-dist/cli.js:6526:29)
        at
  /Users/blah/backend/cloudflare-workers/account/node_modules/wrangler/wrangler-dist/cli.js:6484:51
        at Immediate._onImmediate
  (/Users/blah/backend/cloudflare-workers/account/node_modules/wrangler/wrangler-dist/cli.js:6515:13)
        at process.processImmediate (node:internal/timers:471:21) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }
```
It takes a little bit to stop the server. And I'm starting the worker using `wrangler dev --local --persist` and other workers without --persist (as they don't need the d1 db).

**Comment by tom-sherman** [comment]
> Then I can kill the worker

You need to kill more than the worker. There's a seperate background process (dev registry server) that you need to kill - it should be on port 6284.

**Comment by Eusebiotrigo** [comment]
> You need to kill more than the worker. There's a separate background process (dev registry server) that you need to kill - it should be on port 6284

Thank you, @tom-sherman! That did it!

**Comment by MatteoGauthier** [comment]
Having the issue with `wrangler@2.9.1`

**Comment by nextjoshaustin** [comment]
This workaround has saved me several times. 

The cause is other processes running of the worker via node. 

After force quitting these, the warnings will stop.

![image](https://user-images.githubusercontent.com/565760/236633228-70d085bf-905b-4705-aeef-b78637433a0e.png)

**Comment by rosswaycaster** [comment]
This seemed to work for me: `kill -9 $(lsof -ti:6284)`

It is my understanding that this will find and kill the node process of the Worker Registry.

**Comment by paramaggarwal** [comment]
> This seemed to work for me: kill -9 $(lsof -ti:6284)

Was running into this issue today and was able to resolve it using the above command. ↑

**Comment by jfitzsimmons2** [comment]
For anyone who gets here from Google, I'm on Windows using VS Code, and stopping the local server and restarting VS Code resolved the issue.
