### ISSUE TITLE
💡 Refactor: Convert Jest to Vitest

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/workers-sdk#1927]
### Describe the solution

Vitest Docs comparison https://vitest.dev/guide/comparisons.html#jest:
> Vitest is an interesting option as it gives you a faster run for your unit tests and a jump in DX thanks to the default watch mode using Vite instant Hot Module Reload (HMR). Vitest offers compatibility with most of the Jest API and ecosystem libraries, so in most projects, it should be a drop-in replacement for Jest.

**Depends on:**
MSW conversion #1874

**Comment by rozenmd** [comment]
I'd recommend doing this one test suite at a time, and see if we can't run jest next to vitest while we convert things across.

**Comment by JacobMGEvans** [comment]
> Vitest doesn't support `process.chdir()`, which could be a problem for some of our tests that use it

Might be able to find a workaround or I can talk to some of their team.

**Comment by petebacondarwin** [comment]
The workaround is to move all our code to use a virtual filesystem, and then have in-memory mock file-system for tests.
See https://github.com/angular/angular/tree/main/packages/compiler-cli/src/ngtsc/file_system

**Comment by penalosa** [comment]
Looks like https://www.npmjs.com/package/memfs could solve this (and at a single stroke also move us much closer to being able to run the entirety of Wrangler in a non-node environment)

**Comment by petebacondarwin** [comment]
That could work...

**Comment by petebacondarwin** [comment]
Although, a generic virtual filesystem in the production code, would also help with running Wrangler in non-NodeJS environments....

**Comment by penalosa** [comment]
We could run two esbuild builds for Wrangler itself, one with a plugin to resolve any imports of `fs` with `memfs`, and one without, and then expose a `browser` field in the published `package.json` (and then maybe export `memfs`'s `fromJSON` so that users can initialise the filesystem)?

**Comment by penalosa** [comment]
Or wait, this actually gets more difficult since esbuild doesn't use the node fs API. Huh

**Comment by penalosa** [comment]
Closing in favour of https://github.com/cloudflare/workers-sdk/issues/3467, which tracks the current work on this
