### ISSUE TITLE
🔬 Properly test proxy server

### ISSUE THREAD

**Issue by cameron-robey** [cloudflare/workers-sdk#1961]
The proxy server doesn't have a suite of tests surrounding it, meaning that some things never properly got tested.

When we think about integration testing, we should look at writing a comprehensive set of tests for the proxy server.

An example is with web-sockets, where based on our implementation (with no surrounding tests) we ended up with issues:
- https://github.com/cloudflare/wrangler2/issues/1767
- https://github.com/cloudflare/wrangler2/issues/1812
- https://github.com/cloudflare/wrangler2/issues/1813

**Comment by rozenmd** [comment]
Dumb idea: would unstable_dev having remote mode help here?

**Comment by cameron-robey** [comment]
Yes, one option for testing this would be a set of integration tests that run end to end with remote mode

**Comment by RamIdeas** [comment]
Hi @cameron-robey, thanks for pointing this out! We are currently working on improvements for unstable_dev which will include e2e testing of the API in local mode and remote mode

**Comment by rozenmd** [comment]
Can you link the GitHub issues here (or mention this issue in the new issues) to track that work @RamIdeas? Will make it easier to find later on.
