### ISSUE TITLE
🚀 Feature Request: "no linked issue" GitHub Action for reviewing PRs

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#1968]
### Describe the solution

A feature request for this repo:

Basically, I want an action that runs every time a PR is opened (I don't know if this whole thing is possible btw)

- If a PR has linked issues, check if any of them are in [cloudflare-docs](https://github.com/cloudflare/cloudflare-docs)
- If so, the action leaves an encouraging message thanking the developer for thinking about docs 
- If not, the action leaves a message asking if they've considered whether this feature needs documentation
  - (as a stretch goal), block PRs until someone has clicked yes/no on the message? Maybe we could link out to a Worker-powered page that makes the action pass the check once a person has visited the page?

**Comment by JacobMGEvans** [comment]
> I don't know if this whole thing is possible btw

I think it is, we have access to both repos and credentials. If we create a full blown Action app we can use Octokit and access the Docs issues and look for references to the PR

**Comment by caass** [comment]
I've submitted https://github.com/nearform/github-action-check-linked-issues/pull/194, which hopefully gets merged and then we can use that for this.

**Comment by lrapoport-cf** [comment]
this is effectively addressed as part of https://github.com/cloudflare/workers-sdk/pull/6683, so closing this issue 👍
