### ISSUE TITLE
Chore: Improve `wrangler generate` tests

### ISSUE THREAD

**Issue by caass** [cloudflare/workers-sdk#1980]
- [ ] Write mocks for `git clone` to shim `file://` urls for remote urls
   - [See about spying on calls to `git-client`](https://github.com/cloudflare/wrangler2/pull/1957#discussion_r986742801)
- [ ] Investigate if `checkFiles()` from `init.test.ts` can replace `readDirectory`

These might be easier to fix after (if?) the templates get merged into this repo

**Comment by caass** [comment]
Blocked until templates are merged into this repository

**Comment by lrapoport-cf** [comment]
PR for migrating templates into this repo: https://github.com/cloudflare/wrangler2/pull/2498
