### ISSUE TITLE
🐛 BUG: Node inspector fails to start in local mode

### ISSUE THREAD

**Issue by willtemperley** [cloudflare/workers-sdk#2008]
### What version of `Wrangler` are you using?

2.1.11

### What operating system are you using?

Mac Monterey

### Describe the Bug

I'm unable to get the wrangler to run using a custom port,  node inspector to run using e.g. `wrangler dev --local --inspector-port=9997`

Running `lsof -i :9997` confirms nothing is listening on the port prior to launch.

This seems to be limited to --local 

<img width="693" alt="Untitled" src="https://user-images.githubusercontent.com/92311/195144069-313c3ad9-41d9-4a24-91c3-19adffd98da1.png">

**Comment by caass** [comment]
This looks like an issue where we're accidentally opening the inspector twice when using local mode. Adding it to our backlog :)

**Comment by penalosa** [comment]
This is likely solved by Wrangler 3, which changed the internals of the local mode implementation. If you're still running into this issue, feel free to comment with more details and we can re-investigate!

**Comment by ThomasHambach** [comment]
Hi @penalosa , I am actually running into the same issue. The reproduction is quite simple. This is on wrangler 3.4

```   
await unstable_dev('index.ts'), {
        port: 42000,
        local: true,
        inspectorPort: 42001,
        inspect: true,
        compatibilityDate: "2023-03-14",
        logLevel: "debug",
        experimental: {
            disableExperimentalWarning: true,
            watch: false
        }
    });
await server.start();
```

Trying to connect using devtools will not work. Running `netstat -an | findstr :42001` shows no active connections.
