### ISSUE TITLE
🐛 BUG: `wrangler dev` sends request to hostname of custom zone, instead of full domain

### ISSUE THREAD

**Issue by MaximGY** [cloudflare/workers-sdk#2018]
### What version of `Wrangler` are you using?

2.1.11

### What operating system are you using?

Linux

### Describe the Bug

I've got my domain `example.com`, and a Worker deployed at `worker.example.com`. The second-level domain hosts a website, which is totally unrelated to what my Worker does.

I use a grey-clouded DNS record pointing to my server for `example.com`, and an orange-clouded DNS record pointing to `100::` for `worker.example.com`.

When trying to test the Worker using `wrangler dev`, an error message pops up with the content of a typical 404 reply from my `example.com` website. Publishing the Worker works fine and interacting with it once published is also fine. Changing the Workers route to the default `workers.dev` domain also makes the error disappear.

Though not being able to test my Worker this way is annoying, my main concern is that I don't understand why on Earth a request to `example.com` is done in the process.

**Comment by penalosa** [comment]
Could you provide the contents of the error message?

**Comment by MaximGY** [comment]
Sure, here it is. I removed most of the HTML content to make it more brief.

```
 ⛅️ wrangler 2.1.11 
--------------------
Your worker has access to the following bindings:
⬣ Listening at http://0.0.0.0:8787
- http://127.0.0.1:8787
- http://192.168.1.118:8787
- http://192.168.97.1:8787
- http://192.168.143.1:8787
✘ [ERROR] Error while creating remote dev session: ParseError: Unexpected token <

      at parseJSON
  (/home/user/project/node_modules/wrangler/wrangler-dist/cli.js:136608:11)
      at createPreviewSession
  (/home/user/project/node_modules/wrangler/wrangler-dist/cli.js:143712:51)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async start
  (/home/user/project/node_modules/wrangler/wrangler-dist/cli.js:144345:9) {
    text: 'Unexpected token <',
    notes: [],
    location: {
      lineText: '<!DOCTYPE html>',
      line: 1,
      column: -1,
      file: undefined,
      fileText: '<!DOCTYPE html>\n' +
        '<html>\n' +
        '<head>\n' +
        '<meta charset="utf-8">\n'
        
    A whole lot of HTML...
        
    ... 1939 more characters
    },
    kind: 'error'
  }

```

**Comment by caass** [comment]
It seems like the error is coming from [here](https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/create-worker-preview.ts#L119-L128), where we try to communicate with our API to set up a preview session using a custom zone. I think this may be something we have to fix internally, but I'd have to get a reproduction going to troubleshoot further.
