### ISSUE TITLE
🐛 BUG: using wrangler dev --test-scheduled (even without any CRON code in the Worker) causes this error.

### ISSUE THREAD

**Issue by joshmotion** [cloudflare/workers-sdk#2054]
### What version of `Wrangler` are you using?

0.0.0-200c7f22

### What operating system are you using?

Mac

### Describe the Bug

using ``wrangler dev --test-scheduled`` (even without any CORS code in the Worker) causes this error.
![Screen_Shot_2022-10-21_at_2 22 47_AM](https://user-images.githubusercontent.com/91714073/196991134-d9a3778e-d152-4716-a431-cc873ccaaab1.png)

note: ever since I added the d1 NPM package to my wrangler, wrangler has always reported I'm missing an update, even after running ``"npm install -g wrangler"``.
![Screen Shot 2022-10-21 at 4 24 36 AM](https://user-images.githubusercontent.com/91714073/196991025-55e390b9-207f-46a0-86b7-951e07ee1e30.png)

**Comment by rozenmd** [comment]
We resolved the npm install issue by having @joshmotion run `npm install wrangler@latest` in the project repo, main issue still needs investigation

**Comment by NielXu** [comment]
Getting the same error with `wrangler 2.4.4` running `wrangler dev --test-scheduled`

**Comment by penalosa** [comment]
I suspect this is the D1 facade interacting poorly with the middleware—a solution could be to rewrite the D1 facade as middleware?
