### ISSUE TITLE
🐛 BUG: Can't create a worker from a github repository

### ISSUE THREAD

**Issue by ambit741235WHJR** [cloudflare/workers-sdk#2058]
### What version of `Wrangler` are you using?

2.1.13

### What operating system are you using?

Windows

### Describe the Bug

Can't create a worker from a github repository. This error always occurs while creating the worker.
![image](https://user-images.githubusercontent.com/100905193/197170619-53e14d8d-5c02-40c5-9568-39d39b6c0059.png)

**Comment by rozenmd** [comment]
Hi @ambit741235WHJR thanks for reporting this - could you confirm which command you're running?

I just tried the following and it worked:
```bash
wrangler generate projectname2 https://github.com/stripe-samples/stripe-node-cloudflare-worker-template

 ⛅️ wrangler 2.1.13
--------------------
Creating a worker in projectname2 from https://github.com/stripe-samples/stripe-node-cloudflare-worker-template
✨ Success!
```

**Comment by ambit741235WHJR** [comment]
Hi @rozenmd, I used the following command to create the worker but still not working.
`wrangler generate stripe-worker https://github.com/stripe-samples/stripe-node-cloudflare-worker-template`

**Comment by ambit741235WHJR** [comment]
![image](https://user-images.githubusercontent.com/100905193/197220786-c3585648-2bd8-4ba3-ac8a-8614a6e970ce.png)

**Comment by ambit741235WHJR** [comment]
Even when I tried to execute the command you executed, it still throws the same error.

```
❯ wrangler generate projectname2 https://github.com/stripe-samples/stripe-node-cloudflare-worker-template
 ⛅️ wrangler 2.1.13
--------------------
Creating a worker in projectname2 from https://github.com/stripe-samples/stripe-node-cloudflare-worker-template

✘ [ERROR] Failed to find "undefined" in https://github.com/stripe-samples/stripe-node-cloudflare-worker-template.git


If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new/choose
```

**Comment by rozenmd** [comment]
That's strange, how about `git -v`?

**Comment by ambit741235WHJR** [comment]
> That's strange, how about `git -v`?

@rozenmd 
`git version 2.35.1.windows.2`

**Comment by naturecodevoid** [comment]
I’m having the same issue on Mac with wrangler 2.1.13 and git 2.23.0 when trying to use the official `worker-typescript-template` repo.
