### ISSUE TITLE
🚀 Feature Request: Add "package-lock.json" to ".gitignore"

### ISSUE THREAD

**Issue by RainerZufall187** [cloudflare/workers-sdk#2070]
### Describe the solution

When I create a new Wrangler Project with Git, package-lock.json isn't added to .gitignore. There shouldn't be a package-lock.json in a GitHub repository when there isn't a node_modules directory.

**Comment by WalshyDev** [comment]
Committing package-lock.json is correct and recommended.

https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json
> This file is intended to be committed into source repositories
