### ISSUE TITLE
🚀 Feature Request: Command to update wrangler itself

### ISSUE THREAD

**Issue by kwhitley** [cloudflare/workers-sdk#2071]
### Describe the solution

I'd love an easy, built-in path for upgrading wrangler itself, for example something like:

```shell
wrangler update
# or
wrangler upgrade
```

**Comment by kwhitley** [comment]
Thanks Jacob! 👍

**Comment by JacobMGEvans** [comment]
Feel free to check out the PR @kwhitley it should be a decent start for what you asked for 😃

**Comment by JacobMGEvans** [comment]
Looking for use case of the command rather than usage of the package manager. 
In regards to this https://github.com/cloudflare/wrangler2/pull/2469#issuecomment-1372577354

**Comment by penalosa** [comment]
Closing in favour of using the built in package manager update options (`npm update wrangler`, for npm)
