### ISSUE TITLE
🐛 BUG: wrangler pages publish causes cannot route issue

### ISSUE THREAD

**Issue by ghostdevv** [cloudflare/workers-sdk#2126]
### What version of `Wrangler` are you using?

Latest

### What operating system are you using?

linux

### Describe the Bug

I run `npx wrangler@2 pages publish "modules/site/.svelte-kit/cloudflare" --project-name="PROJECT_NAME" --branch=""` and it fails because of the following error:

```
✘ [ERROR] A request to the Cloudflare API (/accounts/44321e1b7fbd29b56b65c1890a3bbee2/pages/projects/PROJECT_NAME/upload-token) failed.

  Could not route to /client/v4/accounts/44321e1b7fbd29b56b65c1890a3bbee2/pages/projects/PROJECT_NAME/upload-token, perhaps your object identifier is invalid? [code: 7003]
  
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new/choose
```

The account id `44321e1b7fbd29b56b65c1890a3bbee2` is valid, and there is a related issue #2100 that solves it by remove `account_id` from `wrangler.toml` but that doesn't help me because I don't have a `wrangler.toml` and when I don't supply one it prompts me in the terminal to select an account

**Comment by jahands** [comment]
Does this happen with all of your projects, or only one of them?

**Comment by ghostdevv** [comment]
This stopped causing issues fortunately, I am assuming an update to wrangler patched this shortly after me making the issue - happy to close this if no one else has any problems with it

**Comment by metagrapher** [comment]
FWIW I am using a .env file to contain environment variables, such as zone ID and token. I moved this to ".oldenv" and it did not change anything, however.

**Comment by metagrapher** [comment]
Hrmmm. .. I should open a new issue probably, looking at the title, methinks. 🤔

**Comment by ghostdevv** [comment]
I think it's safe to close this now, happy to reopen if anyone has issues :pray:
