### ISSUE TITLE
💬 [Discussion]: Should `batch-timeout` be in milliseconds as well?

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/workers-sdk#2128]
I didn't want this discussion to get lost in the merge. If there are any necessary follow-ups they can be had here, then this can either be transferred to a proper GitHub Discussion or closed. 
        
        Should `batch-timeout` be in milliseconds as well, to match behaviour with the API?

_Originally posted by @penalosa in https://github.com/cloudflare/wrangler2/pull/2064#discussion_r1009328488_

**Comment by penalosa** [comment]
I think it should be (in milliseconds), but equally I don't think this is a crucial change, and can probably wait until a bigger re-think of config in general

**Comment by penalosa** [comment]
Closing this for now—we can maybe come back to it at some point in the future
