### ISSUE TITLE
 ESLint rule and have Prettier handle `import type { Type } ` Pattern

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/workers-sdk#2129]
> Is there something wrong with the `import { type ..., ... }` pattern? I think I've used that in various places

@penalosa consistency, we started with the `import type { FetchError } from "../cfetch";` and would like to keep it consistent, we should at it as a ESLint rule and have Prettier handle it if it can.

_Originally posted by @JacobMGEvans in https://github.com/cloudflare/wrangler2/pull/2064#discussion_r1014049480_
Cc: @penalosa

**Comment by mrkldshv** [comment]
Hey! Is this issue free to pick up?

**Comment by JacobMGEvans** [comment]
Sure 😄

**Comment by mrkldshv** [comment]
To give an update here: the change that allows to enforce such pattern [was just merged](https://github.com/typescript-eslint/typescript-eslint/commit/75dcdf164d206c5530ba7cc095c4599ec90abe35). I'll update the configuration in the repository when release with this PR is published.

**Comment by mrkldshv** [comment]
It seems like we also need to [this](https://github.com/import-js/eslint-plugin-import/pull/2473) rule to be released to be able to enforce `import type {}` pattern. Will be tracking new releases of eslint-plugin-import.

**Comment by JacobMGEvans** [comment]
Just following up on this, are you still working on this @mrkldshv ?

**Comment by mrkldshv** [comment]
Sure! From what I understood we'd need release of https://github.com/import-js/eslint-plugin-import to make it work. The old version doesn't have `consistent-type-specifier-style` rule. Let me know if we can do anything meanwhile!

**Comment by penalosa** [comment]
Closing this issue since we've configured Prettier to do this
