### ISSUE TITLE
🐛 BUG: external fetch inside Cloudflare Queues Consumer gives 1003

### ISSUE THREAD

**Issue by agotfredsen82** [cloudflare/workers-sdk#2150]
### What version of `Wrangler` are you using?

wrangler@queues

### What operating system are you using?

Mac, Linux

### Describe the Bug

Any fetch to external results in a 1003 if the fetch is inside a Workers Queue Consumer .

export default {
  fetch: <- any external fetch happening inside here like (https://httpbin.org/html/) worker as expected
  queue: <- any external fetch happening inside here like (https://httpbin.org/html/) don't work gives 1003
};

**Comment by JacobMGEvans** [comment]
Currently an internal conversation. 
Cc: @jbw1991

**Comment by JacobMGEvans** [comment]
This has been determined to be a internal bug and is now being handled.

**Comment by jbw1991** [comment]
Hey @agotfredsen82, thanks for the report. We have released some backend changes that should fix the issue.

Could you please re-publish your consumer script (wrangler publish) and try it again?

**Comment by penalosa** [comment]
We haven't heard from you in a while, so I'm closing out this issue for now. If it's still a problem feel free to comment with more details and we can investigate further!
