### ISSUE TITLE
🐛 BUG: Inconsistency between dev and prod service bindings

### ISSUE THREAD

**Issue by willtemperley** [cloudflare/workers-sdk#2170]
### What version of `Wrangler` are you using?

2.2.1

### What operating system are you using?

Mac

### Describe the Bug

Using the following pattern, copied verbatim from the docs at https://developers.cloudflare.com/workers/platform/bindings/about-service-bindings/:

```
    const authResponse = await env.auth.fetch(request.clone());

    if (authResponse.status !== 200) {
      return authResponse;
    }
```

In _production_ If the request method is POST/PUT/PATCH/DELETE, the cloned request will be cancelled if the response body is not read.  This leads to e.g. browser XHR requests hanging indefinitely with no error message (making it very difficult to debug).

Using `wrangler dev --local` however works without reading the response. I believe it's accessing the live service binding based on '@opencragmap/ocm-boundary:dev: ▲ [WARNING] This worker is bound to live services: auth (ocm-auth)
'

Not sure where the bug is here - maybe the docs just need updating, but there's definitely inconsistency between dev and prod.

**Comment by willtemperley** [comment]
FWIW turns out the response cannot be returned directly if it's been read. If authentication fails and the response has been read, a  TypeError is thrown:  "Body has already been used. It can only be used once. Use tee() first if you need to read it twice."

Final solution working on dev and prod is:

```typescript
    const response = await env.auth.fetch(request.clone())
    const authJson = await response.json() // Response must be read, otherwise non-simple requests (PUT etc) will fail
    if (response.status !== 200) {
      // A new response must be constructed to avoid a "Body has already been used" error
      return Response.json(authJson, {
        ... response
      })
    }
```

**Comment by caass** [comment]
Thanks for bringing this up! @mrbbot looks like a difference in behavior between miniflare and the runtime? Would like to hear your thoughts on this.

**Comment by willtemperley** [comment]
I'm trying to replicate this issue with a toy example on workers.dev at the moment but I can't so far - no difference between request methods found at all.

**Comment by JacobMGEvans** [comment]
@willtemperley can you see if this discrepancy still exists in `wrangler dev --experimental-local`

**Comment by willtemperley** [comment]
I've replicated the issue in a toy example: https://github.com/willtemperley/wrangler-issue-2170

In this example the script fails if the PUT request body is read after it has been cloned (worker0). The logs show the request to mock-auth is being cancelled.

What's strange is this is not exactly the same issue I had in prod. In that case the request to the auth service binding failed with the same error if I didn't read the auth response (for non-GET requests). I wasn't able to replicate that here.

@JacobMGEvans I can't seem to get the service binding to bind in --experimental-local

**Comment by penalosa** [comment]
This should be fixed in `wrangler@3`, which uses the open source `workerd` for local mode emulation.
