### ISSUE TITLE
🐛 BUG: Missing documentation about wrangler.toml  for worker pages

### ISSUE THREAD

**Issue by polRk** [cloudflare/workers-sdk#2206]
### What version of `Wrangler` are you using?

2.3.0

### What operating system are you using?

Mac

### Describe the Bug

No information how to use wrangler pages with wrangler.toml.

Generally no information about wrangler.toml format, fields, values...

**Comment by isaac-mcfadyen** [comment]
Pages doesn't use a Wrangler.toml and using one will have no effect on Functions currently.

I know the team wants to have a similar config-as-code file in the future, but as of right now `wrangler.toml` is for Workers only.

**Comment by GregBrimble** [comment]
Thanks for filing this issue. As @isaac-mcfadyen says, we don't currently support `wrangler.toml`. If you feel there is information missing about how you can configure Pages in our [developer docs](https://developers.cloudflare.com/pages), please file an issue on that [repo](https://github.com/cloudflare/cloudflare-docs).
