### ISSUE TITLE
🐛 BUG: publishing worker with env variables only uploads string variable values

### ISSUE THREAD

**Issue by jsalaber** [cloudflare/workers-sdk#2207]
### What version of `Wrangler` are you using?

2.3.2

### What operating system are you using?

MacOS Monterey 12.6

### Describe the Bug

When publishing the worker from the CLI (`wrangler publish`), the environment variables that are listed in the `wrangler.toml` file under the specific environment will not show up in the settings page of the worker on the dashboard unless it's a string value, as well as the actual variable not being available to be used in the worker.

#### Reproduction Steps

1. List environment variables with differing env values:

```
[env.production.vars]
CONFIG_CACHE_TIMEOUT_SECONDS=30
USE_EVENTS_API=1
COOKIE_DOMAIN='.taplytics.com'
```

2. Publish the worker using `wrangler publish`
3. Check the settings page of the worker and observe the environment variables not enclosed in quotations are not included in the environment variables

#### Expected behavior

I expect without needing to add quotations that publishing the worker will have all my environment variables listed in the worker settings page, available globally in the worker as a string.

**Comment by admah** [comment]
@jsalaber sorry for the delay in response on this. This is a bug, and we will take a look at fixing it. Thanks.

**Comment by penalosa** [comment]
I'm not sure when this was resolved, but this is no longer an issue with the latest version of Wrangler (non-string environment variables are also uploaded)
