### ISSUE TITLE
🐛 BUG: Can't execute D1 SQL

### ISSUE THREAD

**Issue by Keavon** [cloudflare/workers-sdk#2220]
### What version of `Wrangler` are you using?

2.3.2

### What operating system are you using?

Windows with cmd.exe

### Describe the Bug

I'm following the Get Started guide, pretty much verbatim, in the docs and I'm on this step: `wrangler d1 execute <DATABASE_NAME> --local --file=./schema.sql`

But I'm getting this error:

```
Packages @databases/sql, @databases/split-sql-query not available locally. Attempting to use npx to install temporarily.
Installing... (npx --prefer-offline -y -p @databases/sql@3.2.0 -p @databases/split-sql-query@1.0.3)

X [ERROR] npx-import failed for @databases/sql,@databases/split-sql-query with message:

      Failed to find temporary install directory. Looking for paths matching '\npm-cache\_npx\' in:
      [lots of lines printing out my system path]

 You should install @databases/sql, @databases/split-sql-query locally:
      npm install --save-dev @databases/sql@3.2.0 @databases/split-sql-query@1.0.3
```

However, I did run that last line, `npm install --save-dev @databases/sql@3.2.0 @databases/split-sql-query@1.0.3` and they are installed locally (present in both my package.json and node_modules folder). I even restarted my shell after installing them.

Node: v16.13.1
npm: v8.5.5

**Comment by scratchyone** [comment]
Adding "wrangler": "^0.0.0-7c228171" to my dependencies and running wrangler with `npx` fixed this issue for me.

**Comment by icebourg** [comment]
I'm experiencing the same problem. @scratchyone's suggestion didn't work for me. 

```node --version
v19.1.0

npm --version
8.19.3

wrangler --version
 ⛅️ wrangler 2.4.4
-------------------

✘ [ERROR] npx-import failed for @databases/sql,@databases/split-sql-query with message:

      Failed to find temporary install directory. Looking for paths matching '/.npm/_npx/' in: [snip]

  You should install @databases/sql, @databases/split-sql-query locally:
      npm install --save-dev @databases/sql@3.2.0 @databases/split-sql-query@1.0.3```

I already tried that last command and I can see in the current directory that `node_modules` has modules for both of these packages. I only know enough about npm/node to be dangerous so I may be overlooking something dumb. :)

**Comment by ben-xD** [comment]
I've just faced this issue today. The same command was working yesterday. Not sure what happened. 🤔. I'm using the latest version of wrangler, `2.6.2`

**Comment by ben-xD** [comment]
I worked around the problem by uninstalling nvm and Node `18.12.1 LTS` and used the node installer from https://nodejs.org/en/ for the same version, `18.12.1 LTS`. 

This fixed it for me 🤷🏻🤷🏻

**Comment by StoneMoe** [comment]
meet similar issue too
using Node v18.15.0, Windows, installed via Scoop
```
🌀 Mapping SQL input into an array of statements
🌀 Loading DB at .wrangler\state\d1\DB.sqlite3
[NPXI] better-sqlite3 not available locally. Attempting to use npx to install temporarily.
[NPXI] Installing... (npx --prefer-offline -y -p better-sqlite3@8.0.1)

X [ERROR] npx-import failed for better-sqlite3 with message:

      Failed to find temporary install directory. Looking for paths matching '\npm-cache\_npx\'
  in:
```
