### ISSUE TITLE
🐛 BUG: Wrangler logspewing warnings when --local option used

### ISSUE THREAD

**Issue by craigsc** [cloudflare/workers-sdk#2226]
### What version of `Wrangler` are you using?

2.4.0

### What operating system are you using?

Mac OS 12.6

### Describe the Bug

Running `wrangler dev --local` currently logspews whenever the local webserver is actually hit. This makes any kind of console logging almost useless due to the excess amount of warnings.

This seems to be logspewing since 2.0.25, 2.0.24 is the last "good" version that doesn't have logspew that I could find in my own testing.

To repro:

1) Run `npx create-remix@latest` to get a barebones app, select `Just the basics`, then 'Cloudflare Workers' as the deploy environment
2) Run `npx wrangler dev --local` and then open the app on localhost
3) You'll see massive amounts of warning logspew like the below:
![Screen Shot 2022-11-17 at 7 15 54 PM](https://user-images.githubusercontent.com/236858/202609957-9ae4e478-9160-4562-b719-1af6aaaf61d9.png)

**Comment by JacobMGEvans** [comment]
👋 Greetings, 
Thanks for the report, for additional context do you happen to be working on a VPN or WARP? Are you using Durable Objects?

**Comment by craigsc** [comment]
No VPN or WARP. Also not using durable objects, just using the create-remix setup project which doesn't include any of that

**Comment by penalosa** [comment]
This should be solved by https://github.com/cloudflare/workers-sdk/pull/3048
