### ISSUE TITLE
🐛 BUG: Better error logging in wrangler dev proxy logic

### ISSUE THREAD

**Issue by JoshFerge** [cloudflare/workers-sdk#2244]
### What version of `Wrangler` are you using?

2.4.2

### What operating system are you using?

Mac

### Describe the Bug

When using `wrangler pages dev` with the `--proxy=PORT` option, node, due to the resolution of localhost, will attempt to send this request to the ipv6 loopback address on node17+.

If a developer has their proxy frontend only listening on ipv4, the cloudflare worker will simply print `[pages:err] Error: Could not proxy request: TypeError: fetch failed` 

This just cost me a good 2-3 hours thinking something was wrong with my webpack server. For future developers, a more verbose error message / allow us to specify the host of the proxy would be helpful here: https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/miniflare-cli/assets.ts#L42

**Comment by JoshFerge** [comment]
note: this also applies to SSL issues that i'm having.

**Comment by JacobMGEvans** [comment]
Sorry @nevikashah I read it wrong 😅

**Comment by BMorearty** [comment]
> This just cost me a good 2-3 hours ...

You're a faster debugger than I. Man, this just cost me 3-4 DAYS.

Cloudflare gang, please fix this. Even better than a good error message would be to let the developer specify that the name of the host they want to listen to. And document that if you're using Node.js 17+, you should probably specify an IPv6 host.

**Comment by Sammy-T** [comment]
I'm running into this issue trying to run a local pages environment for a Hugo site. 

Would it not be reasonable to have the CLI request `127.0.0.1` instead of `localhost` or to set the dns default result order to `ipv4first`?
