### ISSUE TITLE
🐛 BUG: ✘ [ERROR] fetch failed when publishing a workers-site

### ISSUE THREAD

**Issue by jdddog** [cloudflare/workers-sdk#2245]
### What version of `Wrangler` are you using?

2.4.2

### What operating system are you using?

Ubuntu

### Describe the Bug

I'm unable to publish a workers-site with wrangler2 that was able to be published with wrangler v1. 

wrangler keeps on exiting with the error `✘ [ERROR] fetch failed`.

There are about 7.5K pages (30K files and 2.5GB of data). I have regularly published workers-sites with more files than this with wrangler v1.

It is also hard to tell how far wrangler has progressed through the upload because the progress stats printed by wrangler are incorrect on the first try:
```
Uploaded 0% (0 out of 10,435)
Uploaded 47% (5,000 out of 10,435)
Uploaded 95% (10,000 out of 10,435)
Uploaded 100% (10,435 out of 10,435)
```

And then when I retry the upload after the first failure, no progress stats are printed and the output that shows what files are being uploaded, skipped and deleted are exactly the same as the previous run.

As an aside, I personally think that it would be better to only show summarised upload progress by default and to only print what files are being uploaded, deleted and skipped when the user sets a debug flag. Printing every file change clogs up the CLI when uploading a large amount of files and gets truncated anyway unless you redirect the output to a file.

**Comment by JacobMGEvans** [comment]
Hey 👋🏻 , thanks for reporting the issue!
If possible can you provide a minimal reproduction

**Comment by jdddog** [comment]
Hey @JacobMGEvans, yeah sure.

**Comment by jdddog** [comment]
Now Cloudflare gives a slightly more detailed error message:

```
✘ [ERROR] A request to the Cloudflare API (/accounts/7c4ee2b197dd0fd4cd2cd77dbb3b9519/storage/kv/namespaces/d16d22e7411a49a1b241a293b040e858/bulk) failed.

  Too many bulk operations already in progress. Please wait until one completes before retrying.
  [code: 10046]
```

So I think it might be because [`await Promise.all(bucketsToPut)`](https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/sites.ts#L220) in the `syncAssets` function isn't uploading the buckets in batches, but all at once.

**Comment by jdddog** [comment]
Now Cloudflare gives a slightly more detailed error message:

```
✘ [ERROR] A request to the Cloudflare API (/accounts/***/storage/kv/namespaces/***/bulk) failed.

  Too many bulk operations already in progress. Please wait until one completes before retrying.
  [code: 10046]
```

So I think it might be because [`await Promise.all(bucketsToPut)`](https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/sites.ts#L220) in the `syncAssets` function isn't uploading the buckets in batches, but all at once.

**Comment by JacobMGEvans** [comment]
I appreciate the additional details. If you can provide a repro worker, that would be awesome another way you can give us more insight into the issue is you can run Wrangler in debug mode and give us your `stdout` dump here 😄 
You can set it with `WRANGLER_LOG=debug npx wrangler` 

Docs: https://developers.cloudflare.com/workers/wrangler/system-environment-variables/#supported-environment-variables

**Comment by jdddog** [comment]
I've got the debug logs, however I think they might have sensitive info (account info and cookies etc), so perhaps it is better to email them to you?

**Comment by yurqua** [comment]
I'm experiencing the same issue. I just started with workers yesterday and got a test working this morning. Now when I'm trying to deploy a new version, I see

```
✨ Compiled Worker successfully
POST /pages/assets/upload
failed: ParseError: A request to the Cloudflare API (/pages/assets/upload) failed.
    at throwFetchError (/Users/username/.nvm/versions/node/v16.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:129713:17)
    at fetchResult (/Users/username/.nvm/versions/node/v16.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:129680:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doUpload (/Users/username/.nvm/versions/node/v16.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:148699:21)
    at async run (/Users/username/.nvm/versions/node/v16.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:148336:26) {
  text: 'A request to the Cloudflare API (/pages/assets/upload) failed.',
  notes: [
    {
      text: 'Too many bulk operations already in progress. Please wait until one completes before retrying. [code: 10046]'
    }
  ],
  location: undefined,
  kind: 'error',
  code: 10046
} retrying...
```

Wrangler version is 2.12.0
OS is MacOS Ventura 13.2.1

**Comment by JacobMGEvans** [comment]
> I'm experiencing the same issue. I just started with workers yesterday and got a test working this morning. Now when I'm trying to deploy a new version, I see
> 
> ```
> ✨ Compiled Worker successfully
> POST /pages/assets/upload
> failed: ParseError: A request to the Cloudflare API (/pages/assets/upload) failed.
>     at throwFetchError (/Users/username/.nvm/versions/node/v16.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:129713:17)
>     at fetchResult (/Users/username/.nvm/versions/node/v16.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:129680:5)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async doUpload (/Users/username/.nvm/versions/node/v16.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:148699:21)
>     at async run (/Users/username/.nvm/versions/node/v16.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:148336:26) {
>   text: 'A request to the Cloudflare API (/pages/assets/upload) failed.',
>   notes: [
>     {
>       text: 'Too many bulk operations already in progress. Please wait until one completes before retrying. [code: 10046]'
>     }
>   ],
>   location: undefined,
>   kind: 'error',
>   code: 10046
> } retrying...
> ```
> 
> Wrangler version is 2.12.0 OS is MacOS Ventura 13.2.1
> 
> UPD. Just updated Wrangler version to 2.12.1 and error text is slightly different:
> 
> ```
> notes: [
>     {
>       text: '{"request_id":"7a4bc5de601e2bf0-FRA","message":"An error occurred processing your request. You may contact support with the given request_id to troubleshoot."} [code: 10000]'
>     }
>   ],
> ```
> 
> Seems to be related to an incident: ![image](https://user-images.githubusercontent.com/9869503/223741850-9833cebe-f5c2-4fdb-a756-234c5eedeed3.png)

Yes, thank you for reporting this. This is separate from the original issue and related to the incident 😃 .
