### ISSUE TITLE
🐛 BUG: Unable to `generate` Python template

### ISSUE THREAD

**Issue by trinhpham** [cloudflare/workers-sdk#2247]
### What version of `Wrangler` are you using?

2.4.2

### What operating system are you using?

Mac

### Describe the Bug

Run the command
`npx wrangler generate my-app https://github.com/cloudflare/python-worker-hello-world` which is guided on https://developers.cloudflare.com/workers/get-started/quickstarts/

Result: 
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/9128061/202963954-f1affa7d-ca91-4906-8929-822bedb66ddc.png">

**Comment by trinhpham** [comment]
Added NodeJS info:
```
❯ npm --versions
{
  npm: '8.15.0',
  node: '16.17.0',
  v8: '9.4.146.26-node.22',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.7',
  openssl: '1.1.1q+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022a',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

**Comment by penalosa** [comment]
Could you run `WRANGLER_LOG=debug npx https://prerelease-registry.devprod.cloudflare.dev/workers-sdk/prs/2849/npm-package-wrangler-2849 generate my-app https://github.com/cloudflare/python-worker-hello-world` and post the output? That'll help us investigate further. Thanks!

**Comment by trinhpham** [comment]
<img width="786" alt="image" src="https://user-images.githubusercontent.com/9128061/222893831-67a9cf1d-627c-4646-b9b5-57d69590616c.png">
Here you are.

**Comment by JacobMGEvans** [comment]
Hey thanks for responding, sorry to see our pre-release directory didn't work in this case. However, we do have another issue that seems to be related #2850 which we will use to follow up with a fix. 

Thanks again! 😄
