### ISSUE TITLE
🐛 BUG: ReferenceError when using D1 locally

### ISSUE THREAD

**Issue by cloudelice** [cloudflare/workers-sdk#2253]
### What version of `Wrangler` are you using?

2.4.2

### What operating system are you using?

Mac

### Describe the Bug

I have a Remix app in a worker and D1 binding appears as `undefined` (in local).  
Other bindings are working well (KV, R2, Service).  

wrangler.toml:
```
d1_databases = [
  { binding = "DB", database_id = "<ignored>", database_name = "my_db" }
]
```

Then I run:  
```
wrangler dev --local --persist
```

Result (at runtime):
`ReferenceError: DB is not defined`

Expected result:  
DB as a D1Database

**Comment by penalosa** [comment]
Hi, thanks for reporting this! Could you setup a repo that reproduces the issue?

**Comment by cloudelice** [comment]
Hello, I created a repo here: https://github.com/cloudelice/d1-issue-2253

**Comment by penalosa** [comment]
Unfortunately the D1 alpha doesn't currently support service-worker format Workers, which is what Remix uses. Thanks for raising it though, we'll add it to the backlog!

**Comment by cloudelice** [comment]
@penalosa Hello, same issue with Queues

**Comment by lrapoport-cf** [comment]
hi @cloudelice :) thanks for flagging this and posting your workaround! in an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. If this is still a problem, please feel free to open a new issue referencing this one and include an updated summary and any additional context and we will review. thank you!
