### ISSUE TITLE
🐛 BUG: D1 consistently dropping out and returning D1_ERROR in Wrangler.

### ISSUE THREAD

**Issue by oracularhades** [cloudflare/workers-sdk#2312]
### What version of `Wrangler` are you using?

2.5.0 

### What operating system are you using?

Mac (Ventura 13.0.1)

### Describe the Bug

<img width="751" alt="Screenshot 2022-11-30 at 3 58 39 PM" src="https://user-images.githubusercontent.com/91714073/204697123-db7669ca-79ac-4a46-a944-3d582c4c2d1f.png">

Hello! Either when starting a dev instance, with "wrangler dev", often randomly, or after leaving Wrangler idle for a little while you'll get a D1_ERROR dropout. The dropout won't end until whatever request you're running finally times out and env.DB.prepare returns an error, which can take minutes sometimes. This bug is super annoying when trying to write code.

Thanks.

**Comment by joshmotion** [comment]
Forgot to mention, this happens in prod too. I'll load our main site and you the dropout happens there too...which now remembering that this should probably have been filed as a D1 bug.

**Comment by joshmotion** [comment]
Just tested and it's both prod/dev die at the same time, so it seams to be D1 just going down entirely.

**Comment by rozenmd** [comment]
Hey @joshmotion if this re-occurs, can you log `error.cause` and post a project that reproduces this?

**Comment by rozenmd** [comment]
We shipped a new backend for D1, which should fix this issue - you can read more about it here: https://blog.cloudflare.com/d1-turning-it-up-to-11/
