### ISSUE TITLE
🐛 BUG: Cannot interact with D1 database locally using Remix and Pages

### ISSUE THREAD

**Issue by dantrain** [cloudflare/workers-sdk#2347]
### What version of `Wrangler` are you using?

2.6.1

### What operating system are you using?

macOS 12.2.1

### Describe the Bug

Hello!

- I created a Remix app with `npx create-remix@latest` and deployed it to Cloudflare Pages.
- I created a D1 database and added some example data as per https://blog.cloudflare.com/d1-open-alpha/
- I navigated to **Project > Settings > Functions > D1 database bindings** and bound the variable name `DB` to my database in both "Production" and "Preview" tabs:

![image](https://user-images.githubusercontent.com/1765203/205983952-3b7e281f-8777-4eab-af29-40ae4efc5993.png)

- I wrote a Remix `loader` function to query the database from `context.DB` for `SELECT * FROM Customers`, see https://github.com/dantrain/remix-d1-test/blob/main/app/routes/index.tsx#L12
- I redeployed to Cloudflare Pages and the data loads beautifully, see https://remix-d1-test.pages.dev/

![image](https://user-images.githubusercontent.com/1765203/205984711-a55b4133-71c1-428d-8d97-102f3364f4f9.png)

- To interact with the database during local development, I added `--d1=DB` to the end of the `wrangler pages dev ./public` command, as per https://developers.cloudflare.com/pages/platform/functions/bindings/#interact-with-your-d1-databases-locally, see https://github.com/dantrain/remix-d1-test/blob/main/package.json#L7
- When running the `dev` command however, I see `SqliteError: no such table: Customers`

![image](https://user-images.githubusercontent.com/1765203/205985751-274db726-d61e-4250-8f22-19dc75e5dda9.png)

- If I change the query to `SELECT * FROM sqlite_schema`, I get this:

![image](https://user-images.githubusercontent.com/1765203/205986265-8be90701-46ad-4e50-94cc-c1d7d54fb33f.png)

It would be great if I could interact with the database from local as the docs suggest. Alternatively if there is an easy way to interact with a local sqlite database on disk that would also work, but I haven't been able to figure that out with my Remix/Pages setup.

- GitHub repo: https://github.com/dantrain/remix-d1-test
- Cloudflare Pages deployment: https://remix-d1-test.pages.dev/

I'm very excited to use D1 with Remix, thanks for your efforts!

**Comment by drewschrauf** [comment]
From the error message, it looks like you're interacting with the database but it doesn't have the same tables as your "production" one. Take a look at [D1 migrations](https://developers.cloudflare.com/d1/platform/migrations/). You can apply those to your local DB using `--local`.

**Comment by Skye-31** [comment]
You'll need to do `--persist` as well for wrangler to read from your disk as opposed to an in-memory database

**Comment by gustavopch** [comment]
I was also expecting to be able to interact with the production services locally. I'm a solo developer and worrying about maintaining multiple environments (each with their own quirks) synced during the early development of a project is not important to me, it makes me spend more time.

**Comment by GeorgeTailor** [comment]
yeah, it would be great to have a possibility to connect to remote D1 DB when developing locally. [The docs](https://developers.cloudflare.com/pages/platform/functions/bindings/#interact-with-your-d1-databases-locally) do not mention any restrictions here, even on contrary, they sound like it should be possible.

**Comment by admah** [comment]
You're correct that it's not currently possible to interact with remote resources while developing locally via `wrangler pages dev`. We currently provide a 1:1 match between local and production in Wrangler v3 by using [Miniflare](https://miniflare.dev), and will continue to press in that direction. We want to encourage this to prevent users from accidentally overwriting prod data or other issues that arise when environments are tangled up.

I'm going to close this out as something we do not intend to support. I would encourage anyone that wants to see this command to open up a new feature request, with a good description of why it would be preferred over the current recommendation.

cc: @vy-ton

**Comment by cloudcreatr** [comment]
Hey.. I have this same issue.. when I run migration it's not visible in local db.. like it creates two local db and remix uses the empty one and other db has the migration.. even after using same id.. idk.. also.. it would be great to interact with production db to get real production feel.. i mean there should be atleast sperate copy of production db which i can use for testing against.. for example how to test with production data..

**Comment by treeder** [comment]
I would also like this to use our remote dev D1 database, not a local one. Is this still not possible?
