### ISSUE TITLE
🐛 BUG: contributing guide doesn't specify what operating systems are supported when compiling from source

### ISSUE THREAD

**Issue by jdddog** [cloudflare/workers-sdk#2363]
### What version of `Wrangler` are you using?

main

### What operating system are you using?

Ubuntu 18.04

### Describe the Bug

I'm following the steps in the contributing guide to build wrangler2 locally. 

At the installing dependencies step, after installing `libc++1`, when I run `npm install` I get the following error:

```node
npm ERR! code 1
npm ERR! path /home/user/wrangler2/node_modules/workerd
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! node:internal/errors:841
npm ERR!   const err = new Error(message);
npm ERR!               ^
npm ERR! 
npm ERR! Error: Command failed: /home/user/wrangler2/node_modules/workerd/bin/workerd --version
npm ERR! /home/user/wrangler2/node_modules/workerd/bin/workerd: error while loading shared libraries: libunwind.so.1: cannot open shared object file: No such file or directory
npm ERR! 
npm ERR!     at checkExecSyncError (node:child_process:828:11)
npm ERR!     at Object.execFileSync (node:child_process:863:15)
npm ERR!     at validateBinaryVersion (/home/user/wrangler2/node_modules/workerd/install.js:57:47)
npm ERR!     at /home/user/wrangler2/node_modules/workerd/install.js:215:7 {
npm ERR!   status: 127,
npm ERR!   signal: null,
```

It might just be that my system is misconfigured, however, maybe it isn't possible to compile wrangler2 on Ubuntu 18.04, especially since it is nearing EOL. 

It would be good if the contributing guide stated what operating systems are supported when compiling from source, or if it provided enough information so that we could work that out.

**Comment by caass** [comment]
@jdddog thanks for reporting this! Can you check if installing libunwind-dev fixes this issue for you?

**Comment by penalosa** [comment]
This should be fixed by the new static builds of `workerd`—coming in the next release
