### ISSUE TITLE
🐛 BUG: "statement too long"

### ISSUE THREAD

**Issue by dcposch** [cloudflare/workers-sdk#2367]
### What version of `Wrangler` are you using?

2.6.1

### What operating system are you using?

Mac

### Steps to reproduce

```
npx wrangler d1 execute test --file projects.sql 
```

```
✘ [ERROR] A request to the Cloudflare API (/accounts/09742c49bc8b4f681a71c115327b6e29/d1/database/8bc06ccd-7565-473d-b60b-aafa25d38e1f/query) failed.

  ERROR 9009: SQL prepare error: statement too long [code: 7500]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose
```

Unfortunately, the error message doesn't say *which* statement is too long, or where in the file it appears.

I've attached SQL file to this report so that you can reproduce: 
[projects.sql.zip](https://github.com/cloudflare/wrangler2/files/10189793/projects.sql.zip)

**Comment by rozenmd** [comment]
Hey @dcposch 
We recently released a new D1 backend which fixes this issue, you can read more about it here: https://blog.cloudflare.com/d1-turning-it-up-to-11/

**Comment by robinmetral** [comment]
Hey @rozenmd, how did the new backend solve this issue? Did it amend/remove statement length limits in the API? I'm still running into the same thing: #4510
