### ISSUE TITLE
🐛 BUG: Running `d1` Commands Requires to Select an Account Every Time

### ISSUE THREAD

**Issue by juriadams** [cloudflare/workers-sdk#2378]
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

macOS Ventura 13.0.2

### Describe the Bug

Every time I run a `wrangler d1` command, I get prompted to select which account I would like to use:

```bash
Select an account from below:
  juri@xxx.xx's Account
❯ xxx
```

This can get frustrating really fast, especially when testing and running multiple commands.

**Comment by smcstewart** [comment]
Still an issue with `2.9.1`. This is inconsistent with other `wrangler` commands.

**Comment by elithrar** [comment]
Fixed as of https://github.com/cloudflare/workers-sdk/commit/5f48c405c663de0c6b2bfc27005246f1fdec6987 but not yet in a public release.

Use `npx wrangler@beta` to test from tip.
