### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by gorillacasinosrs** [cloudflare/workers-sdk#2412]
### What version of `Wrangler` are you using?

2

### What operating system are you using?

Windows

### Describe the Bug

16:33:50.781 | Deploying your site to Cloudflare's global network...
-- | --
16:33:52.625 |  
16:33:52.758 | ✘ [ERROR] Error: Pages only supports files up to 26.2 MB in size
16:33:52.758 |  
16:33:52.759 | .next/cache/webpack/client-production/0.pack is 95.3 MB in size
16:33:52.759 |  
16:33:52.759 |  
16:33:52.759 | If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new/choose
16:33:52.770 | Failed: upload process exited with code: 1
16:33:54.416 | Failed: an internal error occurred
16:33:54.416 | Error: Failed to publish assets. For support, join our Discord (https://discord.gg/cloudflaredev) or create a ticket and reference the deployment ID: 124fca10-00aa-473f-9570-d92182c3eb3b

**Comment by JacobMGEvans** [comment]
@dml33t Thanks for reporting your issue, however, we will need additional information on, what the specific Wrangler version is `wrangler --version`, any other output Wrangler is providing (you can also put Wrangler in debug mode with [`WRANGLER_LOG`](https://developers.cloudflare.com/workers/wrangler/system-environment-variables/#supported-environment-variables)) 

Also please provide a title for the issue 😄

**Comment by penalosa** [comment]
I'm closing this for now since we haven't heard from you in a while. If this is still an issue, feel free to comment with more information and we can investigate further!
