### ISSUE TITLE
MSW Fetch API Support [FormData]

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/workers-sdk#2419]
Besides the stopgap in `init.test` for script `FormData` response, there is also possibly older MSW versions that allowed for `request.body` to be parsed into FormData manually (related: https://github.com/mswjs/interceptors/issues/288, https://github.com/mswjs/msw/issues/1327#issuecomment-1249596133) , these stopgaps could handle the FormData situation until MSW-Beta stabilizes or has a codemod that allows for quick refactor.

Additionally to the `request` object on MSW doesn't have `FormData` support, it seems the response can only handle `TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of FormData` the future update to MSW will be fully Fetch compliant and support it. 
Fetch API Work reference : 
https://github.com/mswjs/msw/pull/1436

_Originally posted by @JacobMGEvans in https://github.com/cloudflare/wrangler2/issues/2418#issuecomment-1353585883_

**Comment by JacobMGEvans** [comment]
Cc: @petebacondarwin

**Comment by penalosa** [comment]
This was fixed by #5887
