### ISSUE TITLE
🐛 BUG: got EMFILE error with wrangler pages publish

### ISSUE THREAD

**Issue by DanSnow** [cloudflare/workers-sdk#2443]
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Linux

### Describe the Bug

I'm running `wrangler pages publish` and got the following error

```
FatalError: Failed to upload files. Please try again. Error: {"errno":-24,"code":"EMFILE","syscall":"open","path":"/path/to/file"})
node_modules/wrangler/wrangler-dist/cli.js:160994:13
at async run2 (node_modules/wrangler/wrangler-dist/cli.js:160596:26) {
  code: 'EMFILE'
}
```

I know this can be usually fixed by adjusting the ulimit. But I don't have permission to adjust it. So I'm asking does there have any way to limit the concurrency uploading.

**Comment by HelloAlexPan** [comment]
Bump

**Comment by penalosa** [comment]
Thanks for flagging this. In an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. If this is still a problem, please feel free to open a new issue referencing this one. Please be sure to include an updated summary and any additional context and we will review. Thank you!
