### ISSUE TITLE
🐛 BUG: `wrangler pages dev` crashes on Worker compile error, leaving port occupied

### ISSUE THREAD

**Issue by itsmatteomanf** [cloudflare/workers-sdk#2445]
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Mac

### Describe the Bug

When running the `wrangler pages dev` command, if the Worker fails compilation (due to coding error or partial save), will make the whole process fail, making you restart the command.

The bigger problem is that upon restart `0.0.0.0:8788` is marked as occupied for a variable amount of time, making the restart impossible, unless the port is changed.

**Comment by jrf0110** [comment]
Hey @itsmatteomanf - I'm having a hard time reproducing this locally. Would you mind sending us a link to a repo that reproduces this issue?

**Comment by Skye-31** [comment]
I was able to reproduce this myself @jrf0110, admittedly somewhat unreliably (perhaps a race condition of unstable_dev also rebuilding the worker?)

**Comment by itsmatteomanf** [comment]
Thanks, @Skye-31. I forgot to reply after out conversation before. I am not sure how to do a repro repo, as it's not specific to a configuration specifically.

**Comment by jrf0110** [comment]
Thanks, @Skye-31. I'll consider that validated then :)

I'll spend some time today to see if I can find where this is happening
