### ISSUE TITLE
🐛 BUG: unable to apply migrations on preview_database_id in D1

### ISSUE THREAD

**Issue by verokarhu** [cloudflare/workers-sdk#2446]
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Mac

### Describe the Bug

Trying to apply a migration to the preview database with the command:
`wrangler d1 migrations apply database-dev`
returns the error:
`[ERROR] Can't find a DB with name/binding 'database-dev' in local config. Check info in wrangler.toml...`

The wrangler.toml file has the following configuration:
`d1_databases = [
    { binding = "DATABASE", database_id = "<UUID for database-prod>", database_name = "database-prod", preview_database_id = "<UUID for database-dev>" },
]`

I've worked around the problem by adding the following section to the wrangler.toml file:
`[env.dev]
d1_databases = [
    { binding = "DATABASE", database_id = "<UUID for database-dev>", database_name = "database-dev" },
]`
which allows me to apply the migrations by running:
`wrangler d1 migrations apply -e dev database-dev`

I'm not sure if this is how it's supposed to be done. It would be nice to be able to apply the same migrations first to the preview database.

**Comment by rozenmd** [comment]
Hi @verokarhu - thanks for reporting this. 

At the moment there's no nice way to deal with preview databases. The best workaround so far is as you've done - defining the preview database separately in `wrangler.toml` and manually running migrations on that database first.
