### ISSUE TITLE
🐛 BUG: Cannot Compile Realm-JS But Logs Unclear

### ISSUE THREAD

**Issue by MarcusSorealheis** [cloudflare/workers-sdk#2450]
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Mac

### Describe the Bug

I cannot get the [Realm-JS](https://github.com/realm/realm-js) node module to transpile when I send it up to a worker with Wrangler. The logs do not make it easy to resolve issues with the __filename dependency. I attempted to use a variety of polyfill strategies, but could not get anything to work. Do you know if you could try to deploy Realm-JS and see if it fails and explain why?

**Comment by JacobMGEvans** [comment]
This likely pertains to Node support, are you using `node_compat`?

**Comment by lrapoport-cf** [comment]
hi @MarcusSorealheis, we haven't heard back so we will close the issue for now. however if this is still an issue and you are able to provide additional context, please feel free to re-open it. thanks!
