### ISSUE TITLE
🐛 BUG: Some CF accounts missing from whoami, even after wrangler logout & re-login

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/workers-sdk#2452]
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Mac OS Ventura 13.1

### Describe the Bug

`wrangler whoami` only shows a subset of accounts I'm part of (and have permissions for), even after `wrangler logout` and logging back in:

```
👋 You are logged in with an OAuth Token, associated with the email '<EMAIL>'!
┌──────────────────────────────────────┬──────────────────────────────────┐
│ Account Name                         │ Account ID                       │
├──────────────────────────────────────┼──────────────────────────────────┤
│ Account 1                           │ <ID> │
├──────────────────────────────────────┼──────────────────────────────────┤
│ Account 3      │ <ID> │
```

^ Account 2 is missing from this list.

...but when running other wrangler commands, they are aware of Account 2: 

```
➜  wrangler pages project create 
Using account: "Account 2 - <ID>"
Select an account from below:
  Account 1
❯ Account 2
  Account 3
Enter the name of your new project: project-name 
Enter the production branch name: main 

✘ [ERROR] A request to the Cloudflare API (/accounts/<ID>/pages/projects) failed.

  Authentication error [code: 10000]
```

**Comment by JacobMGEvans** [comment]
Interesting. I will take a look at this asap.

**Comment by irvinebroque** [comment]
Sounds good! Ping me in chat if you need more internal details to reproduce.

**Comment by Miaxos** [comment]
Same issue here

**Comment by JacobMGEvans** [comment]
Ok, so looking at the response back from the repro (thanks @irvinebroque) I can see the missing Account, so this is definitely an issue on how we handle or parse the response. Starting to dig into this now. 

Thanks @Miaxos for the confirmation too

**Comment by irvinebroque** [comment]
Forgot to mention — the account that is missing from `wrangler whoami` is one that I was recently added to, after I'd previously run `wrangler login`. Without digging into wrangler internals, it seems like the list of Cloudflare accounts is cached/persisted and isn't being updated with the API response from running `wrangler whoami`.

**Comment by penalosa** [comment]
Does this reproduce with the latest version of Wrangler (2.7.2)? We changed the way the account list is rendered, so it may have been fixed

**Comment by JacobMGEvans** [comment]
> Does this reproduce with the latest version of Wrangler (2.7.2)? We changed the way the account list is rendered, so it may have been fixed

@penalosa I was going to be testing that. Then see if Irvine could try it out if it seemed like it was working on our end and we had some testing in place for it.

**Comment by JacobMGEvans** [comment]
After further digging, I have discovered there is a difference in the amount of accounts returning in the `/user` endpoint (data point called `organizations`) 6 in this case and only 5 accounts returning from the `/accounts` endpoint. 

Cc: @jspspike

**Comment by jspspike** [comment]
@JacobMGEvans What exactly are the endpoints you're referring to?

**Comment by penalosa** [comment]
@irvinebroque can you still reproduce this? I'm going to close this for now (it sounds like it was a rendering issue, and that would likely have been fixed when we removed Ink), but if this is still an issue we can re-open
