### ISSUE TITLE
🐛 BUG: `wrangle dev --experimental-local` doesn't allow Durable Objects

### ISSUE THREAD

**Issue by kentonv** [cloudflare/workers-sdk#2458]
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Linux

### Describe the Bug

`wrangler dev --experimental-local` fails on projects that define Durable Object namespaces, because it passes `durableObjectsPersist: true` to the Miniflare 3, which errors because it doesn't support persisting Durable Objects yet (indeed, `workerd` itself does not have this ability).

Changing `durableObjectsPersist` to `false`, however, allows Durable Objects to be tested using in-memory storage. Storage will be reset whenever `workerd` is restarted, but this mode can still be useful for testing. It would be nice to permit people to use in-memory mode, perhaps with a flag, until such a time as `workerd` gains support for persistence.

**Comment by JacobMGEvans** [comment]
Thanks for the suggestion, I don't see anything wrong implementing that flag as a stopgap until DO support is available on `worderd` then `miniflare v3`

**Comment by Resonious** [comment]
Regular `--local`'s durable objects are already ephemeral, so I'd actually expect `--experimental-local` to be the same by default :+1:

**Comment by kentonv** [comment]
I went ahead and implemented persistent DO storage in `workerd`. :smiley: 

https://github.com/cloudflare/workerd/pull/302

**Comment by Manouchehri** [comment]
Is `--local` supposed to allow DOs as well? =)
