### ISSUE TITLE
🐛 BUG: Prerelease registry versions of wrangler will still prefer invoking local wrangler versions in `node_modules` if present

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-sdk#2486]
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

All

### Describe the Bug

If you have a project with wrangler installed into `node_modules`, and then try to use a prerelease version, the prerelease version will just invoke the local wrangler version rather than using itself.

We added this before so people could have global/local co-existing, where local is preferred. For prereleases though, it seems reasonable that we'd always want to run that over global or local.

**Comment by penalosa** [comment]
This is fixed in Wrangler 3, which disabled the delegation behaviour
