### ISSUE TITLE
🚀 Feature Request: Add D1 error message "D1_TABLE_NOTFOUND"

### ISSUE THREAD

**Issue by phruse** [cloudflare/workers-sdk#2512]
### Describe the solution

The current "D1_ERROR" error message is too-comprehensive. Therefore, I suggest adding the "D1_TABLE_NOTFOUND" error message. It is also not consistent that "D1_COLUMN_NOTFOUND" exists because "D1_TABLE_NOTFOUND" does not.

`D1_TABLE_NOTFOUND`
This error message can be helpful to automatically create a table if it doesn't exist (ex. first run).

**Comment by rozenmd** [comment]
Hey @phruse thanks for filing this issue - I'm curious about your use case - have you tried `error.cause` to track your errors?

As in:
```
try {
    await db.exec("INSERTZ INTO my_table (name, employees) VALUES ()");
} catch (e: any) {
    console.log({
        message: e.message,
        cause: e.cause.message,
    });
}
```

**Comment by phruse** [comment]
## The point is the automation of table creation.
### Method 1
Of course, I can use the `e.cause.message` to check for table errors like so:
```
 if(e.cause.message.startsWith("Error: ERROR 9009:")){
     make_table();
 }
```

However, the table not found error message appears differently between miniflare and the actual cloudflare workers, so an _additional ENV or build step is needed for local mode_ (or unit testing). Also, the method that relies on error messages is potentially _insecure and unreliable_.

### error message ex)
**miniflares**
```
SqliteError: no such table: <table name>
     <stack trace> {
       code: 'SQLITE_ERROR'
     }
```
**Cloudflare worker**
```
Error: D1_ERROR
     <stack trace> {
   stack: ...,
   cause: Error: Error: ERROR 9009: SQL prepare error: no such table: <table name>
}
```

### Method 2
In addition, I can load an additional .sql file before local mode, as described in [the documentation](https://developers.cloudflare.com/d1/get-started/#5-run-a-query-against-your-d1-database). However, this cannot be applied to tables that need to be _created dynamically_.
```
async function initSchema(database: D1Database) {
     const data = await fs.readFile(<path>, {encoding: "utf8"});
     await database.exec(data);
}

```

### Conclusion
Therefore, I wonder why `D1_TABLE_NOTFOUND` not exists. I think `D1_TABLE_NOTFOUND` will be used often in a typical use case.

To give a slightly contrived example, if you create a table for each company, you can make the table right away when you first add a company. But when adding data to the table, if the `D1_TABLE_NOTFOUND` error occurs and the table is created at that time, slightly more efficient.(lazy initialization) If you try to make the table later without this error, you should always check that the table exists before accessing it.

**Comment by penalosa** [comment]
Thanks for flagging this. In an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. If this is still a problem, please feel free to open a new issue referencing this one. Please be sure to include an updated summary and any additional context and we will review. Thank you!
