### ISSUE TITLE
🐛 BUG: Having an issue running workers locally with D1

### ISSUE THREAD

**Issue by joshuanoronha** [cloudflare/workers-sdk#2513]
### Which Cloudflare product(s) does this pertain to?

D1, Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Linux (PopOS)

### Describe the Bug

I am stuck in a bit of a catch22 situation here, I have not made any changes to my code and am facing this issue, this is when I am running the worker that connects with a local d1 instance:

Issue:
```
✘ [ERROR] In development, you should use a separate D1 database than the one you'd use in production. Please create a new D1 database with "wrangler d1 create <name>" and add its id as preview_database_id to the d1_database "DB" in your wrangler.toml
```

I added preview_database_id to my wrangler.toml file and now I am getting another issue:
```
✘ [ERROR] Build failed with 1 error:
  ../../../../tmp/tmp-7680-9CpvvNjIXsPs/d1-beta-facade.entry.js:5:7: ERROR: No matching export in "src/index.ts" for import "default"
```

I am running the project using `wrangler dev --local --persist`

I have tried:

-  rebuilding my DB
- deleting the folder in /tmp
- stashing my changes and running the application
- replacing the DB with a new DB and adding it to the toml file

Could someone please help me with this issue, any leads are appreciated?

**Comment by rozenmd** [comment]
Hey @joshuanoronha - is your Worker exporting a fetch handler?

For example:

```
export default {
  async fetch(request: Request, env: Env) {
    return new Response(
      "Hello World"
    );
  },
};
```
