### ISSUE TITLE
🚀 Feature Request: `wrangler pages dev` should allow specifying assets directory

### ISSUE THREAD

**Issue by mhujer** [cloudflare/workers-sdk#2535]
Hello,

I'm using Wrangler to locally develop a simple Function as a part of a statically generated "Pages" website and I [couldn't find](https://developers.cloudflare.com/workers/wrangler/commands/#dev-1) any option to specify the assets directory to use. It would be great to have an option similar to [what is possible](https://developers.cloudflare.com/workers/wrangler/commands/#dev) when using Wrangler to develop the Workers with either `--site` or `--assets` options.

I have a top level directories `/functions` (with a working function) and `/build` (with statically generated website).

I can either run `wrangler pages dev .` in which case the function works correctly, but the static website is served from subdirectory (`http://127.0.0.1:8788/build/`). Or I can run `wrangler pages dev build/` which serves the static website correctly but does not load the functions (which is expected).

What I'm trying to do is to mimic the behaviour of the Pages when deployed, where the functions are expected to be in the `<root>/functions` and the build output directory can be configured:
![image](https://user-images.githubusercontent.com/353372/212068007-1458f40c-5419-4b81-9a94-3489b96aadef.png)

**Comment by CarmenPopoviciu** [comment]
hi @mhujer thank you for raising this issue.

Unless I'm misunderstanding your setup, running `wrangler pages dev build` should do exactly what you need, assuming you run that command in your root directory, that contains both top-level `functions` and `build directories. Is that not the case? If not, can you please provide a repro repository that I could have a look at 🙏 ?

<3

**Comment by mhujer** [comment]
Hi, I don't really remember on which project I faced this issue back then so I think I can just close this.
