### ISSUE TITLE
🐛 BUG: 500 Server Error if you try to insert the row with the same primary key

### ISSUE THREAD

**Issue by zigazajc007** [cloudflare/workers-sdk#2536]
### Which Cloudflare product(s) does this pertain to?

D1

### What version of `Wrangler` are you using?

2.7.1

### What operating system are you using?

Linux

### Describe the Bug

If you try to insert the row with the same primary key it should return json with "success": false, so I will know that the username is already registered. So I won't need to perform another database read just to check if username is already registered.

Steps to reproduce:
1. Create a table with column TEXT and Primary key
2. Insert 2 same values
3. Error will appear when you try to insert the same value

![image](https://user-images.githubusercontent.com/44822563/212075332-6e173f13-e195-46e3-abde-16b86f589b1e.png)

**Comment by JacobMGEvans** [comment]
👋🏻 Greetings,
I appreciate the report. This is the repo and issues for Wrangler, Cloudflare Worker CLI, this seems D1 specific.

Feel free to check out the Cloudflare Discord where there is a channel for D1 as well: https://discord.com/invite/cloudflaredev

To report issues related to D1 specifically:
https://community.cloudflare.com/c/developers/d1/85/l/latest

Cc: @nevikashah @rozenmd
