### ISSUE TITLE
🚀 Feature Request: Pages dev watch should pick up new _worker.js files

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/workers-sdk#2553]
### Describe the solution

My understanding is that on start `wrangler pages dev` looks for an `_worker.js` file to watch.
If it can't find one, it'll just serve static assets. If it does find one, it'll watch it for changes.

If the `_worker.js` file is not present when wrangler looks for it then it will just serve static assets and the only way to
get it to pick up the file it to kill the pages process and restart it.

Since there are various frameworks which we can integrate with pages that generate the `_worker.js` file for you, I think it is quite likely that it could not exist at the beginning and show up later on (I had this exact issue with Next.js), so I am wondering if wrangler could be improved to actually pick up when a new `_worker.js` file is added even afterwards so that developers don't need to restart the process multiple time.

**Comment by IDisposable** [comment]
This should be plausible by injecting a `templates/_worker.js`-based file in the bundling process much like is done for the `checked-fetch.js` file. So if there's no _worker.js at startup, create one from the template (possibly blank) and then watch that... see 

https://github.com/cloudflare/wrangler2/blob/b44e1a7525248a4482248695742f3020347e3502/packages/wrangler/src/bundle.ts#L190

**Comment by penalosa** [comment]
This should have been resolved by https://github.com/cloudflare/workers-sdk/pull/6150
