### ISSUE TITLE
🐛 BUG:I'm trying to make API in DART Language with some Dart Package😔

### ISSUE THREAD

**Issue by shbadon** [cloudflare/workers-sdk#2555]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms, Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.8.0

### What operating system are you using?

Windows

### Describe the Bug

-------------------
▲ [WARNING] Processing wrangler.toml configuration:

    - 😶 Ignored: "type":
      Most common features now work out of the box with wrangler, including modules, jsx,
  typescript, etc. If you need anything more, use a custom build.

Total Upload: 88.17 KiB / gzip: 18.06 KiB

X [ERROR] A request to the Cloudflare API (/accounts/*****#####***###***##***###***###**#/workers/scripts/untitled_api) failed.

  Uncaught Error:
    at worker.js:405:13 in a
    at worker.js:1158:17 in bC
    at worker.js:1147:11 in ct
    at worker.js:1087:18 in cx
    at worker.js:2429:20 in cL
    at worker.js:2394:42 in cY
    at worker.js:3537:9
    at worker.js:3516:9
    at worker.js:3531:7 in dartProgram
    at worker.js:3539:5
   [code: 10021]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose

**Comment by penalosa** [comment]
Thanks for reporting this! To help us track down the issue further, would you be able to provide a minimal reproduction as a github repository?

**Comment by Spejik** [comment]
Which optimization level are you using? I found that it works with -O1|3|4, but when I used -O2 I got the same error. I have no idea why, maybe there's an issue with the Dart VM running in Workers? (but then O1 shouldn't work either, so idk)

Here's more info about what the levels do: https://dart.dev/tools/dart-compile#basic-options

**Comment by adrianjagielak** [comment]
The same issue, wrangler fails to publish index.js compiled with optimization level -O2 (-O1|3|4 works just fine)

Wrangler version: 2.9.1
Dart version: 2.18.2
Minimal reproduction repo/branch: https://github.com/cloudflare/dart-worker-hello-world/tree/JacobMGEvans/wrangler2-config-update (the official hello world for wrangler 2)

commands to reproduce:

```bash
wrangler generate projectname https://github.com/cloudflare/dart-worker-hello-world
cd projectname
dart pub get
dart compile js -O2 --server-mode -o index.js index.dart
```

## Logs

<details>
<summary>Logs</summary>

(I replaced my account ID with "\<redacted\>")

```
adrianjagielak@MacBook-Pro-Adrian projectname % wrangler publish                                        
 ⛅️ wrangler 2.9.1 
-------------------
Total Upload: 88.08 KiB / gzip: 18.06 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/<redacted>/workers/scripts/projectname) failed.

  Uncaught Error:
    at worker.js:400:13 in a
    at worker.js:1153:17 in bC
    at worker.js:1142:11 in ct
    at worker.js:1082:18 in cx
    at worker.js:2424:20 in cL
    at worker.js:2389:42 in cY
    at worker.js:3532:9
    at worker.js:3511:9
    at worker.js:3526:7 in dartProgram
    at worker.js:3534:5
   [code: 10021]

  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose

```

</details>

**Comment by JacobMGEvans** [comment]
Thank you for the minimal repro! That is a huge help.

**Comment by RamIdeas** [comment]
Hi @shbadon! It seems this is an issue with the Dart compiler. Wrangler and workers itself does not support Dart. The recommendation is to use a custom build with wrangler. Wrangler will run the javascript output of the custom build
