### ISSUE TITLE
Document `wrangler pages dev --kv`

### ISSUE THREAD

**Issue by aaronadamsCA** [cloudflare/workers-sdk#2564]
### Describe the solution

As #1490 helps make clear, the behaviour of `wrangler pages dev` with `--kv` is non-obvious. How it's currently described:

> `--kv` `string[]`
> KV namespace to bind.

This isn't enough. My best guess based on observation is that it emulates a new empty KV namespace on each run, but I'm really not sure.

**Comment by 4levels** [comment]
I'm seeing something very similar, as if the KV store is ehpemeral, as described in the general `wrangler dev` docs for the `--local` option

https://developers.cloudflare.com/workers/wrangler/commands/#dev

> --local  (default: false)
>
>Run the preview of the Worker directly on your local machine.
>This runs an ephemeral local version of your Worker, and will not be able to access data stored on Cloudflare’s network (for example, this includes your data stored on KV). To persist data locally, using the --persist flag will tell Wrangler to store data in the .wrangler/state subdirectory.

I can access the KV store fine after deployment, but locally it never seems to work, even with correct bindings and validation of the contents of the stores with the wrangler cli

**Comment by 4levels** [comment]
I'm still not sure how to understand this, but since it works after being deployed and is a local issue for me, I kind of settled with the idea that I can use `wrangler pages dev --persist --kv=..` as workaround and sync the actual KV values manually if needed.

**Comment by jefforulez** [comment]
upvoting this issue.   the documentation around KV binding for pages and pages functions is terrible.  i lost a good four or five hours going in circles with it today.   not only is the expected behavior not clearly explained, but terminology and descriptions for "binding id", "variable name", "id", "preview id", "namespace name", and "namespace id" etc are perplexing.

**Comment by aaronadamsCA** [comment]
I can say with near-certainty now that `--kv` creates a new empty namespace on every run of `wrangler pages dev`.

**Comment by JulesBlm** [comment]
This threw me off as well. I looked around the docs and found this on the [doc for Bindings](https://developers.cloudflare.com/pages/platform/functions/bindings/).

> Local development uses local storage. It cannot access data stored on Cloudflare’s servers.
> By default, data in local development is not persisted. This means if you write a value into KV, for example, the next time you start local dev, it will no longer exist. Enable persistence with the --persist flag.

Initially I though `--persist` would persist the values the Cloudflare KV but it only persists locally.

**Comment by penalosa** [comment]
This is documented in https://developers.cloudflare.com/pages/functions/bindings/#interact-with-your-kv-namespaces-locally
