### ISSUE TITLE
🐛 BUG: kv put value is not optional

### ISSUE THREAD

**Issue by tomByrer** [cloudflare/workers-sdk#2580]
### Which Cloudflare product(s) does this pertain to?

KV, Wrangler

### What version of `Wrangler` are you using?

2.8.0

### What operating system are you using?

Win10

### Describe the Bug

Your docs & `--help` say "[value is optional](https://developers.cloudflare.com/workers/wrangler/commands/#put)", yet in actual use it is mandatory.
What I'm trying to do is use put to "[leave the value parameter empty and instead include a property in the metadata object](https://developers.cloudflare.com/workers/runtime-apis/kv/#more-detail)" (again your docs).

```bash
$ wrangler kv:key put  --namespace-id="s0menamespac3" "test03"

X [ERROR] Exactly one of the arguments value and path is required
wrangler kv:key put <key> [value]
....

$ wrangler kv:key put  --namespace-id="s0menamespac3" "test04" ""

X [ERROR] Exactly one of the arguments value and path is required
wrangler kv:key put <key> [value]

#(what I really want to do)
$ wrangler kv:key put  --namespace-id="s0menamespac3" "testmetadata" --metadata="{\"name\": \"test_value\"}"
X [ERROR] Exactly one of the arguments value and path is required
```

TIA

**Comment by tomByrer** [comment]
I'm not too familiar with Yargs, but looking at [your business-logic code](https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/kv/index.ts#L237-L260), I don't see any mention of a null value?

**Comment by penalosa** [comment]
Wrangler doesn't support writing a null value via the command line, but you should be able to write a null value using the [in-worker API ](https://developers.cloudflare.com/kv/api/write-key-value-pairs/).

The reason the docs mention that value is optional is that you can use either value or `--path` to specify the value for a KV entry. This is clarified slighty further up the docs page:
> Exactly one of VALUE or --path is required.
