### ISSUE TITLE
🐛 BUG: [b] open a browser hotkey takes you to wrong host in remote mode + Access

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-sdk#2610]
### Which Cloudflare product(s) does this pertain to?

Workers/Other

### What version of `Wrangler` are you using?

2.8.1

### What operating system are you using?

macOS

### Describe the Bug

When running `wrangler dev` in remote mode for a Worker which runs behind Access, once the dev session is ready, pressing `b` takes you to `subdomain.example.com:8787` rather than `localhost:8787` or whatever host we're using these days (`127.0.0.1`/`0.0.0.0`/etc.)

**Comment by penalosa** [comment]
@GregBrimble It looks like this was a bug introduced in https://github.com/cloudflare/wrangler2/pull/1883, which applies for _all_ remote mode dev, rather than just for workers behind Access. I'm assigning to you since you worked on that PR and probably have more context for what's going on there

**Comment by KianNH** [comment]
Transferring over from #2691 - myself & @threepointone have run into this bug today.

**Comment by threepointone** [comment]
I assume it's broken for everyone with routes btw, I wasn't even using it as a custom domain, just a plain route. This sounds like it should be higher priority.

**Comment by KianNH** [comment]
Can confirm - I was originally under the impression this was for custom domains only but having tested with a route, that is also being opened by the `open a browser` hotkey.

**Comment by KianNH** [comment]
This is also an issue when using `--port 0` - with no routes or custom domains - and that will open `localhost:0` in the browser.
