### ISSUE TITLE
🐛 BUG: Local service bindings require specific worker startup order

### ISSUE THREAD

**Issue by stevenkampen** [cloudflare/workers-sdk#2635]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

 2.8.1

### What operating system are you using?

Mac

### Describe the Bug

If worker B has a service binding for A, I have to start worker B first, wait for it to be ready, then start A.

When I reviewed the changes which implemented the worker registry I saw that the intention was to have them able to startup in any order, and it sounds like it did work like that for a while.

Note: The issue is resolved as soon as worker A does its first refresh (e.g. due to code change).

**Comment by penalosa** [comment]
I can't seem to reproduce this (service bindings work locally with any worker startup order). If you're still running into issues feel free to comment with more details and we can investigate further, but for now I'm going to close this issue
