### ISSUE TITLE
🐛 BUG: Failed to construct 'WebSocket': the constructor is not implemented.

### ISSUE THREAD

**Issue by 7Hazard** [cloudflare/workers-sdk#2640]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler

### What version of `Wrangler` are you using?

2.8.1

### What operating system are you using?

Windows

### Describe the Bug

Running unning `wrangler pages dev`, when trying to do `new WebSocket("ws://127.0.0.1:8000")`, I get the following error:
`[pages:err] Error: Failed to construct 'WebSocket': the constructor is not implemented.`

According to [the Worker documentation about WebSockets](https://developers.cloudflare.com/workers/learning/using-websockets#writing-a-websocket-client):
`Cloudflare Workers supports the new WebSocket(url) constructor.`

**Comment by penalosa** [comment]
Thanks for reporting this! This will be fixed by an upcoming Miniflare 2 release, which implements this (cc @mrbbot). I'll leave this open to track updating the Miniflare version that Wrangler depends on.

**Comment by penalosa** [comment]
This was fixed in a Miniflare release—apologies, it looks like I forgot to update this ticket!
