### ISSUE TITLE
🐛 BUG: `unstable_dev` fetch cannot accept query param

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/workers-sdk#2641]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.8.1

### What operating system are you using?

Mac

### Describe the Bug

Due to the code here:
https://github.com/cloudflare/wrangler2/blob/89d78c0ac444885298ac052b0b3de23b69fb029b/packages/wrangler/src/api/dev.ts#L302-L328

The URL that's passed into `fetch` for `unstable_dev` does not handle query params. This obviously causes any test using these to fail.

Repro:
```js
import { writeFile } from 'fs/promises';
import { expect, test } from 'vitest';
import { unstable_dev } from 'wrangler';

test('unstable_dev fetch repro', async () => {
	const script = `
	export default {
		fetch(req) {
			const url = new URL(req.url);
			const name = url.searchParams.get('name');
			return new Response('Hello, ' + name);
		}
	}
	`;
	await writeFile('script.js', script, { encoding: 'utf8' });

	const worker = await unstable_dev('script.js');

	const res = await worker.fetch('http://worker?name=Walshy');

	expect(res.status).toBe(200);

	const text = await res.text();

	expect(text).toBe('Hello, Walshy');

	await worker.stop();
});

```

Error:
```
 FAIL  test/repro.test.ts > unstable_dev fetch repro
AssertionError: expected 'Hello, null' to be 'Hello, Walshy' // Object.is equality
 ❯ test/repro.test.ts:25:15
     23|  const text = await res.text();
     24|
     25|  expect(text).toBe('Hello, Walshy');
       |               ^
     26|
     27|  await worker.stop();

  - Expected   "Hello, Walshy"
  + Received   "Hello, null"
```

A fix I'd suggest is instead just relying on the URL object, something like:
```js
const url = new URL(input);
url.protocol = `${protocol}:`;
url.hostname = readyAddress;
url.port = readyPort;
input = url.toString();
```
Instead of manually constructing the URL string.

**Comment by bretthoerner** [comment]
Related/additionally, it doesn't unpack a `Request` at all if it's passed in, so even changing the _path_ has no effect if you use the template: https://github.com/cloudflare/workers-sdk/blob/6fd062419c6b66c2c5beb7c45ec84a32dfa89e01/templates/worker-typescript/src/index.test.ts#L17

i.e. If you change that to `new Request('http://falcon/foo', { method: 'GET' });` your app receives `http://ip:port/` as the `request.url`
