### ISSUE TITLE
🐛 BUG: workers.api.error.wrong_plan for publish / dev workers

### ISSUE THREAD

**Issue by crisperit** [cloudflare/workers-sdk#2675]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.9.0

### What operating system are you using?

WSL

### Describe the Bug

I am logged to the wrangler via `wrangler login` on the account : `ACCOUNT_PRIVATE` with an ID let's say `123` and I have free version of workers

I'm also added to the 'ACCOUNT_WORKER' with an ID let's say `456` and with he Enterpraise plan + unbounded workers.

I want to publish a worker to the  `ACCOUNT_WORKER`

Mine wrangler.toml:
```
name = "test"
main = "src/index.ts"
compatibility_date = "2023-02-03"
account_id = "456"
usage_model = "unbound"
workers_dev = true
```

After running the `wrangler publish` I'm getting:

```
wrangler publish
 ⛅️ wrangler 2.9.0 
-------------------
Total Upload: 0.25 KiB / gzip: 0.17 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/xxx/workers/scripts/xxx) failed.

  workers.api.error.wrong_plan [code: 10075]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose
```

I can add new workers through website and also through direct api calls... I think the problem lies somewhere on the calls that Wangler does

**Comment by NicholasEstrada** [comment]
Hi, how did you manage to fix this? I have the same problem, and using the same System "WSL"

**Comment by NicholasEstrada** [comment]
Thanks!!!
