### ISSUE TITLE
🐛 BUG: wrangler dev dies upon saving 'import'ed file, must be killed and restarted

### ISSUE THREAD

**Issue by lorenbrichter** [cloudflare/workers-sdk#2679]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.9.0

### What operating system are you using?

Mac

### Describe the Bug

This seems like a new bug, this behavior used to work fine (last I checked it worked in 2.4.2).

If I have `index.js` and `example.txt`

`index.js`:
```
import example from './example.txt';

export default {
	async fetch(request, env, ctx) {
		return new Response(example);
	},
};
```

`example.txt`:
```
this is a test
```

now I run `wrangler dev` in `local` mode, whenever I modify and save `example.txt` wrangler throws the following error:

```
[mf:err] Error: ENOENT: no such file or directory, open '/private/var/folders/0b/nkcg3qd51sj54_knx9ywmb580000gn/T/tmp-2506-ACQmyPnLTG9D/1ff2b3704aede04eecb51e50ca698efd50a1379b-example.txt'
```

I spelunked briefly in the tmp folders, and it looks like the cached file is not regenerated, but the wrangler dev server is looking for the file under a new hash name and (obviously) not finding it.

Maybe a miniflare regression? This has been a real showstopper recently.

**Comment by JeffBue** [comment]
I'm an outsider, but having the same issue when saving files. Any help here would be appreciated.

**Comment by lorenbrichter** [comment]
I just downgraded all my projects to 2.4.2. I’ll probably just stick with that until the experimental runtime is less… experimental (it still refuses to work on my machine, tried asking the discord for help to no avail).On Apr 26, 2023, at 8:47 PM, Jeff ***@***.***> wrote:﻿
I'm an outsider, but having the same issue when saving files. Any help here would be appreciated.
