### ISSUE TITLE
🚀 Feature Request:

### ISSUE THREAD

**Issue by alihussain575** [cloudflare/workers-sdk#2690]
### Describe the solution

deploing  my nx monorepo next js project on cloudflare pages using `@cloudflare/next-on-pages`

**Comment by alihussain575** [comment]
This is the app that i created [github repo](https://github.com/alihussain575/nx-next-app.git) please check this and tell me if you could add this feature ?

**Comment by penalosa** [comment]
Thanks for flagging this. In an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. If this is still a problem, please feel free to open a new issue referencing this one. Please be sure to include an updated summary and any additional context and we will review. Thank you!
