### ISSUE TITLE
🐛 BUG: `_routes.json` not being detected

### ISSUE THREAD

**Issue by rgraham7503** [cloudflare/workers-sdk#2694]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2

### What operating system are you using?

pages

### Describe the Bug

I have an angular project that deploys just fine on pages. I added the functions folder with a function, and when I deploy I get no routes found. So I added _routes.json and in root(/), dist(/dist/) and functions(/functions/) and still get no routes found.
`<html><body>
<pre class="c_jp c_bq c_ow c_ox c_sn c_so c_da c_ut c_nb c_mz c_na c_fl c_fm c_ue c_bs c_uu">

09:51:58.824 | ✘ [ERROR] No routes found when building Functions directory: /opt/buildhome/repo/functions
-- | --
09:51:58.824 |  
09:51:58.825 |  
09:51:58.825 | If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new/choose
09:51:58.836 | Warning: Wrangler did not find routes when building functions. Skipping.
09:51:58.836 | Validating asset output directory
09:51:59.478 | Deploying your site to Cloudflare's global network...
09:52:01.407 | Uploading... (0/8)
09:52:01.408 |  
09:52:02.994 | AAG Uploading... (3/8)
09:52:02.995 |  
09:52:03.451 | AAG Uploading... (5/8)
09:52:03.452 |  
09:52:03.641 | AAG Uploading... (8/8)
09:52:03.642 |  
09:52:03.645 | ✨ Success! Uploaded 8 files (2.75 sec)

</pre>
</body>
</html>`

_routes.json is this

`{
   "version": 1,
   "include": ["/api"],
   "exclude": []
}`

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to link to a repo that reproduces the issue, and we can investigate further?

**Comment by CarmenPopoviciu** [comment]
`_routes.json` is not mandatory in order for a Pages project with Functions to work. I suspect something goes wrong when your functions are built, but in order to understand exactly what, we'd need to get more info. A repro example would be great, but if that's not possible, it would help to at least know how your app folder structure looks like and what your `/function` directory looks like

**Comment by admah** [comment]
Closing as stale. Please reopen if the issue persists when testing against Wrangler v3.
