### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by FAD-Desarollo** [cloudflare/workers-sdk#2698]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

0.0.0

### What operating system are you using?

Windows

### Describe the Bug

I'm using cloudflare pages to deploy unity app, this app has a file 37.8 MB in size and I can´t  reduce size. There is a way to deploy it?

**Comment by penalosa** [comment]
It's likely that something like [R2](https://www.cloudflare.com/en-gb/products/r2/) would suit your needs better here, I think? cc @cloudflare/pages

**Comment by GregBrimble** [comment]
Yup. Pages has a max file size of 25 MiB. We have no immediate plans to raise that, so you'll need to look into other ways of hosting that file (and R2 is a good shout!)
