### ISSUE TITLE
Features for D1

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#2701]
- [ ] `wrangler d1 migrations list` should have a --json flag for clean output
- [ ] prisma support (https://github.com/prisma/prisma/issues/13310) - what do they need from us?
- [ ] try out a means of quick preview branches for D1 dbs (to enable a workflow like `wrangler d1 clone <old-db> <new-name>` when a PR is opened, followed by `wrangler d1 delete <new-name>` once the PR is closed
  - [ ] also consider: `wrangler d1 create <new-name> --from-existing=<old-db>`
  - [ ] also consider: `wrangler d1 create <new-name> --from-backup=<old-db>:<backup-timestamp>`
- [ ] a means of generating a `types.d.ts` file of the current db state (for prod, local, and preview): `wrangler d1 types <dbname> --local` `wrangler d1 types <dbname> --preview`
  - [ ] look into https://github.com/RobinBlomberg/kysely-codegen
  - [ ] also https://github.com/rmp135/sql-ts

**Comment by penalosa** [comment]
Sorry to be terribly annoying, but would it be possible to split these out into one issue per item? (There are a few chunky issues like this in the backlog, and they're always hard to close out because the scope tends to grow)

**Comment by rozenmd** [comment]
Yeah @penalosa I will, I was just getting pinged from various channels/sources and wanted a single place to see these

**Comment by tsteckenborn** [comment]
Just fyi, in case it wasn't seen: https://community.cloudflare.com/t/how-to-access-environment-variables-from-libraries/480041

**Comment by penalosa** [comment]
@rozenmd what's the status of this?

**Comment by penalosa** [comment]
This is pretty stale, so I'm going to close for now. @rozenmd feel free to open individual issues if it's helpful for tracking work going forward
