### ISSUE TITLE
🐛 BUG: Missing entry-point

### ISSUE THREAD

**Issue by chrismuntean** [cloudflare/workers-sdk#2704]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.9.1

### What operating system are you using?

Fedora Linux

### Describe the Bug

After receiving the email to update to V2 since V1 is being depreciated I get this error after authenticating:

```
✘ [ERROR] Missing entry-point: The entry-point should be specified via the command line (e.g. `wrangler dev path/to/script`) or the `main` config field.
```

**Comment by penalosa** [comment]
The [migration guide](https://developers.cloudflare.com/workers/wrangler-legacy/migration/) should have more details on how to upgrade from v1 to v2. If there are specific things we could make clearer, or issues that you run into that aren't covered by the CLI output or the migration guide, we can definitely look to improve it.

In this specific case, you'll need to add a `main = "src/index.ts"` field to your Wrangler configuration file (replace `src/index.ts` with whatever your main JavaScript module is—the one which exports your event handlers (or registers event handlers if you're using service worker syntax))

**Comment by chrismuntean** [comment]
I see, I understand now. Thank you
