### ISSUE TITLE
🐛 BUG: backticks in strings break d1 sql queries

### ISSUE THREAD

**Issue by sgentle** [cloudflare/workers-sdk#2713]
### Which Cloudflare product(s) does this pertain to?

D1

### What version of `Wrangler` are you using?

2.9.1

### What operating system are you using?

Mac

### Describe the Bug

The following gives an error when using `wrangler d1 execute` against a remote database:
```sql
CREATE TABLE test (value TEXT);

INSERT INTO test VALUES ('`;');
```
```
ERROR 9009: SQL prepare error: unrecognized token: "'`;" in insert into test VALUES('`; at offset
  24 [code: 7500]
```

It works fine in the sqlite3 cli and with `--local`.

**Comment by rozenmd** [comment]
Hey @sgentle thanks for reporting this, I'll have @geelen take a look

**Comment by rozenmd** [comment]
Hi @sgentle - this should be fixed now, do you mind trying again?

**Comment by sgentle** [comment]
Oops, missed the notification. Yep, working fine now!
