### ISSUE TITLE
🐛 BUG: Wrangler R2 GET requires local folder to exist

### ISSUE THREAD

**Issue by serycodes** [cloudflare/workers-sdk#2721]
### Which Cloudflare product(s) does this pertain to?

R2

### What version of `Wrangler` are you using?

2.9.1

### What operating system are you using?

WSL

### Describe the Bug

If downloading a file from R2 that is stored in a prefix, that prefix needs to exist locally as a folder or the download fails.

```
$ wrangler r2 object get bucketname/foldername/filetodownload.zip
 ⛅️ wrangler 2.9.1
-------------------
Downloading "foldername/filetodownload.zip" from "bucketname".

✘ [ERROR] ENOENT: no such file or directory, open 'foldername/filetodownload.zip'
```
```
$ mkdir foldername
$ wrangler r2 object get bucketname/foldername/filetodownload.zip
 ⛅️ wrangler 2.9.1
-------------------
Downloading "foldername/filetodownload.zip" from "bucketname".
Download complete.
```

**Comment by JacobMGEvans** [comment]
I wrote this, I think I know what is going on. Thanks for the issue! 😄

**Comment by eerison** [comment]
I guess it was the reason that get wasn't working for me 😅

**Comment by HudsonGraeme** [comment]
That threw me off too, thanks for the issue @serycodes
