### ISSUE TITLE
🐛 BUG: --experimental-local doesn't log http requests and group console output by request

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workers-sdk#2722]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.9.1

### What operating system are you using?

Mac

### Describe the Bug

If I use `wrangler dev --experimental-local` and follow the logs, I can't tell which logs belong to which request as no information about HTTP requests is present in the log output, and logs are not grouped by request.

This makes it hard to debug apps that make lots of concurrent requests.

The remote mode, wrangler tail, as well as miniflare 2, all add log entries about HTTP requests, and some (e.g. tail) group console logs by request which is very nice and it would be great to have this kind of output for --experimental-local as well.

**Comment by JacobMGEvans** [comment]
I think @mrbbot would have more context for this, looping him in.

**Comment by admah** [comment]
@jspspike can we close this out based on work you did in the miniflare repo?

**Comment by jspspike** [comment]
Yes we can
