### ISSUE TITLE
[Templates] 404 page doesn't render in HTML but plain text

### ISSUE THREAD

**Issue by samhamilton** [cloudflare/workers-sdk#2728]
Hi, 

We are using workers-sites on a few specific subfolders, which works well with the [template](https://github.com/cloudflare/templates/blob/main/worker-sites/index.js) provided. The one thing not working is that the worker will show the uploaded 404.html file as text and not html when serving to a browser. 

The only change we made to the file is `options.mapRequestToAsset = handlePrefix(/^\/en\/glossary/)` so that assets are properly served from a subfolder. I can't figure out why other html pages are fine and only the 404 pages is handled as text? 

example 404: https://www.martide.com/en/glossary/i-am-not-a-page
example working page: https://www.martide.com/en/glossary/a/

thanks
Sam

**Comment by penalosa** [comment]
Hi @samhamilton! Thanks for flagging this. In an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. If this is still a problem, please feel free to open a new issue referencing this one. Please be sure to include an updated summary and any additional context and we will review. Thank you!
