### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Goose0x** [cloudflare/workers-sdk#2736]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

latest

### What operating system are you using?

Windows 11

### Describe the Bug

<html>
<body>
<pre class="c_oh c_bq c_nb c_iu c_yi c_yj c_da c_qr c_kr c_kp c_kq c_ga c_gb c_yk c_bs c_ys" style="box-sizing: border-box; border-radius: 0px; color: rgb(49, 49, 49); display: block; font-size: 12px; margin: 0px; overflow: auto; padding: 16px 32px; width: 1262px; background-color: rgb(242, 242, 242); border-width: 0px 0px 1px; border-style: solid; border-color: rgb(217, 217, 217); border-image: initial; font-family: monaco, courier, monospace; height: 500px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

06:12:57.565 | Finished
-- | --
06:12:57.566 | Note: No functions dir at /functions found. Skipping.
06:12:57.566 | Validating asset output directory
06:12:58.617 | Deploying your site to Cloudflare's global network...
06:13:00.713 |  
06:13:00.854 | ✘ [ERROR] Error: Pages only supports files up to 26.2 MB in size
06:13:00.855 |  
06:13:00.855 | cache/webpack/edge-server-production/0.pack is 386 MB in size
06:13:00.855 |  
06:13:00.855 |  
06:13:00.856 | If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new/choose
06:13:00.868 | Failed: upload process exited with code: 1
06:13:02.021 | Failed: an internal error occurred
06:13:02.021 | Error: Failed to publish assets. For support, join our Discord (https://discord.gg/cloudflaredev) or create a ticket and reference the deployment ID: 2d415151-9756-4016-865f-779c31c05935

</pre>
</body>
</html>

Cannot seem to get this to work at all.   When using next.js
[tsuki-website.2d415151-9756-4016-865f-779c31c05935.log](https://github.com/cloudflare/workers-sdk/files/10747799/tsuki-website.2d415151-9756-4016-865f-779c31c05935.log)

**Comment by Skye-31** [comment]
This isn't a bug - next is producing files in a folder called `cache`, which pages is seeing and trying to upload - you'll need to append ` && rm -rf cache` to your build command

**Comment by penalosa** [comment]
We haven't heard from you in a while, so I'm going to close this issue for now. If you're still running into issues feel free to comment with more details and we can investigate further!

**Comment by Bradleykingz** [comment]
For future visitors, append `&& rm -rf .next/cache`

**Comment by jacksonllk** [comment]
OR, append && rm -rf out/cache if you are using 'out' directory instead of '.next' directory.

So that's npm run build && rm -rf out/cache

**Comment by abodmicheal** [comment]
I ran into this issue but I used cache false in next and when I upload the file the page gives not found
