### ISSUE TITLE
🐛 BUG: API check pages deployments return 400 while previous APIs are fine.

### ISSUE THREAD

**Issue by ltvaran** [cloudflare/workers-sdk#2738]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.10.0

### What operating system are you using?

Linux

### Describe the Bug

API check pages deployments return 400 while previous APIs are fine.
I already checked with abusereport@cloudflare.com and they said no blocks or bans are found with my account. I still can login on the web.

Attached logs from CI-CD [pipelineLogError-{7a1a7ac0-0952-4574-85ed-61a7f514eca8}.txt](https://github.com/cloudflare/workers-sdk/files/10754016/pipelineLogError-.7a1a7ac0-0952-4574-85ed-61a7f514eca8.txt)

-- START CF API REQUEST: POST https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/$PROJECT_NAME/deployments
HEADERS: {
  "User-Agent": "wrangler/2.10.0"
}
INIT: {
  "method": "POST",
  "body": {},
  "headers": {
    "User-Agent": "wrangler/2.10.0"
  }
}
-- END CF API REQUEST
-- START CF API RESPONSE: Bad Request 400
HEADERS: {
  "cf-cache-status": "DYNAMIC",
  "cf-ray": "79a4e8eb3ab304fe-HKG",
  "connection": "keep-alive",
  "content-encoding": "gzip",
  "content-type": "application/json; charset=UTF-8",
  "date": "Thu, 16 Feb 2023 08:28:29 GMT",
  "server": "cloudflare",
  "set-cookie": "__cflb=0H28vgHxwvgAQtjUGUFqYFDiSDreGJnUxV31Mq3cSms; SameSite=Lax; path=/; expires=Thu, 16-Feb-23 10:58:30 GMT; HttpOnly, __cfruid=a7554c2addecff0ca6c6f805539a9406cd58642c-1676536109; path=/; [domain=.api.cloudflare.com](http://domain%3D.api.cloudflare.com/); HttpOnly; Secure; SameSite=None",
  "transfer-encoding": "chunked",
  "vary": "Accept-Encoding",
  "x-envoy-upstream-service-time": "1731"
}
RESPONSE: {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 8000036,
      "message": "Your Cloudflare account has been blocked. Contact [abusereply@cloudflare.com](mailto:abusereply@cloudflare.com)."
    }
  ],
  "messages": []
}
-- END CF API RESPONSE

**Comment by jspspike** [comment]
“Hi @ltvaran! Thanks for flagging this. In an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last few months. If this is still a problem, please feel free to open a new issue referencing this one. Please be sure to include an updated summary and any additional context and we will review. Thank you!”
