### ISSUE TITLE
wordpress_test_cookie

### ISSUE THREAD

**Issue by mtissington** [cloudflare/workers-sdk#2749]
I'm a little confused, cache bypass seems to be set for all requests that have a cookie beginning with "wordpress".

A lot of my pages on my site (activewords.com) have wordpress_test_cookie set. So these pages are never cached.

Surly the code should allow cookie wordpress_test_cookie to be cached?

**Comment by penalosa** [comment]
@mtissington I'm closing this for now since we haven't heard from you in a while, but feel free to re-open if this is still an issue, and we can investigate further
