### ISSUE TITLE
Edge cache example - A few questions about the "stale on revalidate" logic

### ISSUE THREAD

**Issue by daigo75** [cloudflare/workers-sdk#2750]
@pmeenan I stumbled across your example for the edge cache worker, and I would like to ask you a few questions, to better understand the logic behind it. I listed the questions below:
1. Shouldn't the "stale while revalidate" logic check for the expiration date? If I understood correctly, the refresh is performed only when the content doesn't contain the expected headers, but I would have expected it to occur also when the content is actually stale.
2. In method `cacheResponse()`, there's a comment saying "// Move the cache headers out of the way so the response can actually be cached." What does that mean?
3. In method `cacheResponse()`, the `Cache-Control` header is set to `max-age=315360000`. Why such a high value?

Thanks in advance for your answers.

**Comment by penalosa** [comment]
I'm closing this for now, but feel free to comment if this is still an issue for you and we can investigate further.
