### ISSUE TITLE
🐛 BUG: Cannot read properties of undefined (reading 'fetch') 

### ISSUE THREAD

**Issue by logankeenan** [cloudflare/workers-sdk#2751]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.10.0

### What operating system are you using?

Mac Ventura 13.1

### Describe the Bug

I'm following the [Getting Started Guide](https://github.com/cloudflare/workers-rs#getting-started) in workers-rs, but it's failing to run the initial project scaffold. 

Node: v18.14.1
npm :9.5.0
wrangler: 2.10.0 
rustc: 1.66.1

I ran `npx wrangler dev` and receive this error was well as running ` npx wrangler dev --local`.  I uploaded the [repo](https://github.com/logankeenan/worker-test) and attached screenshots of scaffolding out the project.  Let me know what else I can do to help troubleshoot. Thank you!

<img width="991" alt="Screenshot 2023-02-17 at 8 36 21 AM" src="https://user-images.githubusercontent.com/2107635/219685722-08d94eeb-a7d2-4100-9711-9df1b2be4f65.png">
<img width="1310" alt="Screenshot 2023-02-17 at 8 36 44 AM" src="https://user-images.githubusercontent.com/2107635/219685734-62c4622a-036e-47a4-8556-0edf45ae265f.png">
<img width="1792" alt="Screenshot 2023-02-17 at 8 39 54 AM" src="https://user-images.githubusercontent.com/2107635/219685740-ca9b19e4-997d-47d0-92a7-45c6b592df3a.png">

**Comment by KianNH** [comment]
This is a known issue with `workers-rs` that'll be fixed in their next release - take a look at https://github.com/cloudflare/workers-rs/issues/276#issuecomment-1425748586 for a workaround.
