### ISSUE TITLE
Cache not being cleaned on planned article

### ISSUE THREAD

**Issue by solracsf** [cloudflare/workers-sdk#2752]
Using Wordpress, the cache is not being cleaned on a planned article.

Our articles are published also on the homepage so they are published on the category but not in the homepage. only solution, re-save the article after it has been published.

**Comment by lauragift21** [comment]
The templates repo has moved to workers-sdk monorepo, if you are still encountering problems with this, can you leave a comment and let us know.

**Comment by penalosa** [comment]
@mtissington I'm closing this for now since we haven't heard from you in a while, but feel free to re-open if this is still an issue, and we can investigate further
