### ISSUE TITLE
🚀 Feature Request: Change how we detect modules/service-workers

### ISSUE THREAD

**Issue by penalosa** [cloudflare/workers-sdk#2754]
### Describe the solution

We currently use `esbuild` to detect whether a Worker is in service-worker format or module-worker format. This is fairly heavyweight, and can sometimes be wrong. We should shift to something like https://www.npmjs.com/package/es-module-lexer, which is what the Cloudflare dashboard uses.

**Comment by punkeel** [comment]
In the meantime, could you respect the user-configured `build.upload.format`? / cc #2767

**Comment by IgorMinar** [comment]
I think it's reasonable to respect `build.upload.format` if provided by the user, but we should not require it since that would be a big breaking change at this point, and also not aligned with our long term direction.

Once service worker syntax is deprecated, we can safely default to module syntax without heuristics.

**Comment by KianNH** [comment]
When I had a brief look:

1) `--format` is a hidden flag only on `publish`, not `dev` - so it'd need adding to `dev` and potentially unhiding

2) `build.upload.format` is currently deleted during config validation so messaging would need updating in-case users still have it in their config (ignoring the deprecation notices) & suddenly a new Wrangler update breaks their `dev`/`publish` 

3) Wrangler currently sends metrics for various events, would it be worth adding one for when the `hint` supplied by `--format` or `build.upload.format` is different to the 'guessed' format from the heuristics? There may be an uptick at first where users remove `build.upload.format` now that it is considered by Wrangler, but after that I suspect it'll work nicely in showing if changes (i.e `esbuild` upgrade) change trends.

There's already a discussion open from October requesting that this is re-added, albeit with no replies: https://github.com/cloudflare/workers-sdk/discussions/2020

I like that Wrangler is able to automatically figure out what I'm using which makes for a pretty seamless `init` -> `publish` workflow but I'm sure advanced users would love the escape hatch.

**Comment by penalosa** [comment]
In practice, this isn't a huge performace problem, so closing for now. At the time this was opened Wrangler did _many_ esbuild passes per build, but we've since cleaned that up and so the inital esbuild pass when parsing a user's config is negligible.
