### ISSUE TITLE
🐛 BUG: D1 import with transaction is very slow

### ISSUE THREAD

**Issue by bisgardo** [cloudflare/workers-sdk#2761]
### Which Cloudflare product(s) does this pertain to?

D1

### What version of `Wrangler` are you using?

2.10.0

### What operating system are you using?

Linux

### Describe the Bug

I followed the [instructions](https://developers.cloudflare.com/d1/learning/importing-data/#import-an-existing-database) for importing an existing SQLite DB into D1:

```
sqlite3 mydb.sqlite3 .dump > db.sql
```

This results in a file `db.sql` with shape:

```
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE address ( ... );
INSERT INTO address VALUES(...);
<...>
CREATE TABLE IF NOT EXISTS "thing" (...);
INSERT INTO thing VALUES(...);
<...>
COMMIT;
```

The markers `<...>` each cover 10000s of rows.

Looking in `splitSqlIntoStatements` (`packages/wrangler/src/d1/splitter.ts`) we see that because of the `BEGIN` line, `str` is never pruned but instead built as a single huge SQL statement. I left the command running all night but it but the next morning it was still burning 100% CPU.

After removing the `BEGIN TRANSACTION` and `COMMIT` lines, the command ran quickly. The docs don't mention that this should be done.

**Comment by rozenmd** [comment]
Hey @bisgardo, we've now documented this here: https://developers.cloudflare.com/d1/learning/importing-data/#troubleshooting - since D1 runs the SQL batch in a transaction, SQL files that contain transactions don't work.
