### ISSUE TITLE
🐛 BUG: logic values in bind not working

### ISSUE THREAD

**Issue by step135** [cloudflare/workers-sdk#2765]
### Which Cloudflare product(s) does this pertain to?

D1

### What version of `Wrangler` are you using?

latest

### What operating system are you using?

x

### Describe the Bug

Following throws error:
```
let a = true
env.DB.prepare("INSERT INTO tbl (v) VALUES (?)").bind(a).run()
```
but this works:
```
env.DB.prepare("INSERT INTO tbl (v) VALUES (true)").run()
```

**Comment by jspspike** [comment]
@rozenmd Not sure if you have any more context about this issue but we are currently closing out stale issues that haven't had any activity in the last few months. Feel free to open if this bug is still relevant
