### ISSUE TITLE
🐛 BUG: can't upload script with wrangler 2 

### ISSUE THREAD

**Issue by punkeel** [cloudflare/workers-sdk#2767]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.10.0

### What operating system are you using?

Linux

### Describe the Bug

```
 [WARNING] Processing wrangler-def.toml configuration:

         - Deprecation: "build.upload.format":
           The format is inferred automatically from the code.
...
 [ERROR] A request to the Cloudflare API (/accounts/abc/workers/scripts/def) failed.

       The uploaded script has no registered event handlers. [code: 10068]

       If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose
```

wrangler2 does not respect `format = "service-worker"`, and the API doesn't recognize a Worker script using `addEventListener('fetch', (event: FetchEvent) => {...});`?

This worked with Wrangler 1.

**Comment by jspspike** [comment]
Could I see your full `wrangler.toml` and script? Using the following script and `wrangler.toml` I was able to upload a service worker.

```js
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})
/**
 * Respond with hello worker text
 * @param {Request} request
 */
async function handleRequest(request) {
  return new Response('Hello worker!', {
    headers: { 'content-type': 'text/plain' },
  })
}
```

```toml
name = "helloworld"

workers_dev = true
main = "index.js"
compatibility_date = "2022-10-03"
```

**Comment by JacobMGEvans** [comment]
Hi @punkeel 👋🏻, 
Appreciate your reporting an issue you were having, were you able to figure out the problem or come up with a solution?

**Comment by penalosa** [comment]
Thanks for reporting this! If this is still an issue feel free to comment with more details, and we can re-open and investigate further!
