### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Incognito** [cloudflare/workers-sdk#2768]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.10.0

### What operating system are you using?

Mac 12.4

### Describe the Bug

When attempting to tail logs for "Pages" I receive API errors both in the wrangler command line, raw API and web UI.

Here is an example deployment where I am unable to tail logs using the command `npx wrangler pages deployment tail "https://29a19e75.app-waipify-com.pages.dev" --project-name="app-waipify-com"`.

It is not simply only this deployment but all deployments for this "Page".

<img width="1438" alt="Screen Shot 2023-02-20 at 5 44 00 PM" src="https://user-images.githubusercontent.com/379322/220170208-ea0587c8-4525-4021-800e-30c3e6d9491c.png">

When attempting this via web UI I also receive an error:
<img width="1413" alt="Screen Shot 2023-02-20 at 6 33 03 PM" src="https://user-images.githubusercontent.com/379322/220170677-844cb4cc-aa2a-4207-aa84-1c32ede21567.png">

Using Chrome inspector I collected the error message returned from the endpoint `https://dash.cloudflare.com/api/v4/accounts/75461928a2b17b695d1c809221e343ac/pages/projects/app-waipify-com/deployments/6f3c13c3-2ea5-4aef-b1a1-e7c440468540/tails
 `:
```
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 8000068,
      "message": "workers.api.error.script_not_found"
    }
  ],
  "messages": []
}
```

This deployment is a Next.js Edge Runtime following deployment instructions on https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/

Happy to provide any more details!

**Comment by mydracula** [comment]
![image](https://user-images.githubusercontent.com/71320199/222827473-35f91ef4-e8d3-45d2-9618-48c39d326293.png)

I also met

**Comment by Incognito** [comment]
@mydracula as far as I can tell it's because the functions were unable to be run in general. I had this issue with nextjs edge deploys.

**Comment by jspspike** [comment]
“Hi @Incognito! Thanks for flagging this. In an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last few months. If this is still a problem, please feel free to open a new issue referencing this one. Please be sure to include an updated summary and any additional context and we will review. Thank you!”

**Comment by tddschn** [comment]
Has the tail command been fixed? Still encountering the same error with `wrangler 3.22.4`.

**Comment by magick93** [comment]
I'm also running into this issue.

**Comment by cryptic-dev** [comment]
same issue
