### ISSUE TITLE
🐛 BUG: [pages:err] Error: Could not proxy request

### ISSUE THREAD

**Issue by safaalai** [cloudflare/workers-sdk#2774]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler

### What version of `Wrangler` are you using?

2.10.0

### What operating system are you using?

Mac

### Describe the Bug

Running:
`npx wrangler pages dev --kv=USER -- npm start`

Site starts on localhost:33xx        
(NOTE: Port increments by 1 on each run until I reboot.  Starts at 3333)

Code then calls Stytch which redirects to function localhost:8788/some/function.

The function redirects back to localhost:8788/some/page at the end of the call.

Then I get:
[pages:err] Error: Could not proxy request: TypeError: fetch failed
GET /some/page 502 Bad Gateway

This all used to work with the previous version of wrangler and started failing when I upgraded.

The problem I have here, is that for local development I have to specify a stable port number on Stytch, but since wrangler keeps updating the port number on each try I cannot possibly know what the port number will be.

**Comment by safaalai** [comment]
I downgraded wrangler to @0.0.34 and the problem persisted with the same error codes.
One thing I did prior to this is to update my mac to Ventura 13.2.1 (22D68)

**Comment by safaalai** [comment]
This issue is due to an upgrade of Node that is not compatible with my development system.  As such this is not a problem with Wrangler.  Closing the issue.

**Comment by DominicTobias** [comment]
@safaalai could you elaborate? Does it fail if you use Node 18 which has fetch defined?

**Comment by DominicTobias** [comment]
This is indeed a problem with Node 18 and native fetch - https://github.com/node-fetch/node-fetch/issues/1624

If we could configure the host from `localhost` to `127.0.0.1` then it would work fine :(

**Comment by safaalai** [comment]
Yes, the issue was that I went to node 18 and my system was not compatible with that.  Went back down to 16.13.1 and things work fine now.
