### ISSUE TITLE
🐛 BUG: Header Negation is Ignored, Multiple Headers being set

### ISSUE THREAD

**Issue by CxRes** [cloudflare/workers-sdk#2776]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.10.0

### What operating system are you using?

Windows

### Describe the Bug

When deploying a website with Pages, header negation for `_headers` file is not working as expected. If a header specified globally is negated for a specific route and a new value for that header is applied, one actually gets two headers in the HTTP response with both the route specific value and also the global value. 

The HTTP response in such cases should remove the global header and should only return the route-specific value for the header.

Sample: https://test-header-negation.pages.dev/

This does not happen in local development with wrangler.

**Comment by penalosa** [comment]
Thanks for flagging this. In an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. If this is still a problem, please feel free to open a new issue referencing this one. Please be sure to include an updated summary and any additional context and we will review. Thank you!

**Comment by CxRes** [comment]
Yes. This bug was resolved, from what I recall!
