### ISSUE TITLE
🐛 BUG: D1 Data import fails

### ISSUE THREAD

**Issue by PBhadoo** [cloudflare/workers-sdk#2777]
### Which Cloudflare product(s) does this pertain to?

D1

### What version of `Wrangler` are you using?

2.10.0

### What operating system are you using?

Windows 11 x64

### Describe the Bug

````
D:\cloudflare\archived1>wrangler d1 execute archive_tg_db --file=10.sql
Delegating to locally-installed wrangler@2.10.0 over global wrangler@2.9.1...
Run `npx wrangler d1 execute archive_tg_db --file=10.sql` to use the local version directly.

▲ [WARNING] Processing wrangler.toml configuration:

    - D1 Bindings are currently in alpha to allow the API to evolve before general availability.
      Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose
      Note: Run this command with the environment variable NO_D1_WARNING=true to hide this message

      For example: `export NO_D1_WARNING=true && wrangler <YOUR COMMAND HERE>`


--------------------
🌀 D1 is currently in open alpha and is not recommended for production data and traffic
🌀 Please report any bugs to https://github.com/cloudflare/workers-sdk/issues/new/choose
🚧 To request features, visit https://community.cloudflare.com/c/developers/d1
🚧 To give feedback, visit https://discord.gg/cloudflaredev
--------------------

🌀 Mapping SQL input into an array of statements
🌀 Parsing 10000 statements
🚣 Executing on archive_tg_db (5f2568d5-8c19-4004-951e-a475a16b2d9b):

X [ERROR] Received a malformed response from the API

  <!DOCTYPE html>
  <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
  <!--[if I... (length = 6515)

  POST
  /accounts/d7fd792641c0f950e8e4979eac0cfe5a/d1/database/5f2568d5-8c19-4004-951e-a475a16b2d9b/query
  -> 504 Gateway Time-out

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
````

Unable to import data. Have to retry several times then it succeeds. Also there should be a auto retry parameter. like --retry=3

**Comment by rozenmd** [comment]
We shipped a new backend for D1, which should fix this issue - you can read more about it here: https://blog.cloudflare.com/d1-turning-it-up-to-11/

**Comment by PBhadoo** [comment]
> We shipped a new backend for D1, which should fix this issue - you can read more about it here: https://blog.cloudflare.com/d1-turning-it-up-to-11/

Got it. But I've tried several times via email and all but they never provided more storage capacity. And i can't test D1 with 100 MB. Can you help increase it. As without it cannot test it properly and I've to use Mongodb for large datasets. My work doesn't affect any production environment or data loss doesn't affect me either.

Email for CF is admin at hashhackers dot com
