### ISSUE TITLE
🐛 BUG: `r2 object put` Duplex option required

### ISSUE THREAD

**Issue by migueljr** [cloudflare/workers-sdk#2784]
### Which Cloudflare product(s) does this pertain to?

R2

### What version of `Wrangler` are you using?

2.11.0

### What operating system are you using?

MAC

### Describe the Bug

I'm trying to run the command below to upload a file to r2:

`wrangler r2 object put cccc/main.js -f main.js`

and this error is happening:

![image](https://user-images.githubusercontent.com/12215747/220948996-947da099-13b4-4588-b194-6dd65698f396.png)

I've done a lot of research and haven't found a solution for this.

what should I do?

**Comment by JacobMGEvans** [comment]
I wonder if this is being caused by a recent Undici upgrade we did. Could you try to reproduce this with an older version of Wrangler, just a few versions back?

**Comment by migueljr** [comment]
I tested version 2.10.0.. and it worked. so the problem is in version 2.11.0
