### ISSUE TITLE
🐛 BUG: worker-rs: "Could not resolve './index_bg.wasm'" on wrangler dev or publish

### ISSUE THREAD

**Issue by danwritecode** [cloudflare/workers-sdk#2801]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.11.1

### What operating system are you using?

Linux Ubuntu 22.04.2

### Describe the Bug

I had a project a week ago that was running fine with wrangler dev and was publishing fine with wrangler publish. However now, when I run either command, I receive the following error: 

```
[INFO]: Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: :-) Done in 51.42s
[INFO]: :-) Your wasm pkg is ready to publish at /home/dan/documents/apps/image-processing-service/build.
✘ [ERROR] Could not resolve "./index_bg.wasm"

    index_bg.js:1:22:
      1 │ ...t * as wasm from './index_bg.wasm';
        ╵                     ~~~~~~~~~~~~~~~~~

1 error
Error: esbuild exited with status exit status: 1

✘ [ERROR] Command failed with exit code 1: cargo install -q worker-build && worker-build --release
```

The issue seems to be that that index_bg.wasm file is actually named index.wasm:
![image](https://user-images.githubusercontent.com/41842184/221371973-282e2031-255e-4224-8a00-a689dc1ad31c.png)

**Things I've tried:** 
1. deleting build and target folders
2. updating wrangler to latest version
3. running wrangler via npx (same result)
4. re-cloning my repo into a new directory

The source repo can be found here: https://github.com/aiku-ai/image-processing-service

**Comment by KianNH** [comment]
Bump your `worker` crate version to `0.0.13` in `Cargo.toml`

**Comment by danwritecode** [comment]
@KianNH that did it. not sure why I didn't think to do that initially. either way, hopefully this closed issue will serve someone in the future. thanks for the lightning fast reply on a saturday nonetheless.
