### ISSUE TITLE
🐛 BUG: pages deploy "found" /functions directory when no such directory exists

### ISSUE THREAD

**Issue by jefforulez** [cloudflare/workers-sdk#2804]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.0.16

### What operating system are you using?

cloudflare pages deployment

### Describe the Bug

my cloudflare pages deploy is throwing this error:

```
Found Functions directory at /functions. Uploading.
 ✘ [ERROR] No routes found when building Functions directory: /opt/buildhome/repo/functions
```

but there is not a `/functions` directory in my repo.

my project build configuration is:
- Framework preset: `Nuxt.js`
- Build command: `nuxt generate`
- Build output directory: `/dist`
- Root directory: `/`
- Build comments on pull requests: ``

this project previously deployed as configured without problems. 

<img width="688" alt="Screenshot 2023-02-26 at 10 50 57" src="https://user-images.githubusercontent.com/1448616/221421134-d330d3d7-98ee-4641-ad23-d422444e9e0a.png">

**Comment by jefforulez** [comment]
deployment log:  [ruleznewmedia-com.d99637be-a531-49c4-b70b-3c48f0507514.log](https://github.com/cloudflare/workers-sdk/files/10834065/ruleznewmedia-com.d99637be-a531-49c4-b70b-3c48f0507514.log)

**Comment by eduardo-marcolino** [comment]
I got the same error. I had to change the build command to:

`nuxt generate && rm -rf /opt/buildhome/repo/functions`

And the output directory to:

`/output/public`

**Comment by lrapoport-cf** [comment]
hi @jefforulez :) thanks for flagging this and thanks @eduardo-marcolino for posting your solution 👍  in an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and any additional context and we will review. thank you!
