### ISSUE TITLE
wrangler preview --url in wrangler 2

### ISSUE THREAD

**Issue by aivLuk** [cloudflare/workers-sdk#2809]
#### Describe the bug

I'm moving to wrangler 2 and can't seem to find a way how to replicate previous **wrangler preview --url** functionality. I tried using **wrangler dev --host**, **wrangler dev --route** but keep on getting same **Could not find zone for ...** error when trying to run **wrangler dev**

Does anyone know how to replicate this with wrangler 2?

**Comment by aivLuk** [comment]
Yes, but `--local` is a boolean. How can I open a specific url in preview? For example in wrangler 1 it would be something like this:
`wrangler preview --url example.com/test/subtest`

We have some redirect logic in the worker that is depending on the pathname of the url, so it should open this specific pathname locally.

**Comment by penalosa** [comment]
@aivLuk I may be misunderstanding the use case, but can you navigate to `http://localhost:8787/test/subtest` in your browser? Would that work?

**Comment by aivLuk** [comment]
@penalosa yes that works. Is it possible to specify the pathname in cli or config so it would open that up in the browser and I wouldn't need to type it by hand everytime? Basically what that `preview` example was doing?

**Comment by penalosa** [comment]
Not in Wrangler v2+'s config or CLI, I'm afraid. Once you've started a dev session, pressing "b" in your terminal will open a browser to http://localhost:8787 though

**Comment by aivLuk** [comment]
@penalosa okay got it. Issue is if it's `/` then in the worker logic it immediately does a redirect. I guess will have to live with the manual typing the localhost with the pathname. Thanks for your effort.

**Comment by penalosa** [comment]
Closing this for now, but cc @admah to see if this is something we should prioritise as feature work
