### ISSUE TITLE
🚀 Feature Request: customise location of Cloudflare Pages `functions` directory

### ISSUE THREAD

**Issue by balupton** [cloudflare/workers-sdk#2814]
### Describe the solution

Would be nice if I could move my `functions` directory from root into my `src`/`source` directory alongside my other typescript files.

The project repo is at https://github.com/bevry/billing/tree/cfpages and the contrived repo is at https://github.com/balupton/astro-cfpages-esbuild-resolution-bug

**Comment by RamIdeas** [comment]
Hi @balupton! Thanks for flagging this. In an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. Unfortunately this is not a feature we're ready to commit to supporting right now. We may in the future but also cannot guarantee that or commit to any timeline right now. If this is still a problem, please feel free to open a new issue referencing this one. Please be sure to include an updated summary and any additional context and we will review. Thank you!
