### ISSUE TITLE
🚀 Feature Request: Wrangler shouldn't hide SQL errors

### ISSUE THREAD

**Issue by DominicTobias** [cloudflare/workers-sdk#2819]
### Describe the solution

Hi, if executing the following: `npx wrangler d1 execute my-db --local --file=./migrations/01_init.sql`

All I get back if I have an SQL errors is:

✘ [ERROR] D1_ERROR

This makes it very hard to develop. I have to go into the sql CLI (`sqlite3 .wrangler/state/d1/DB.sqlite3`) and paste in the SQL to get a useful error:

```
Parse error: near ")": syntax error
  , 'unixepoch')),     PRIMARY KEY (job_post_id),   );
                                      error here ---^
```

Ah I had a trailing comma. I wish wrangler would have told me that.

**Comment by rozenmd** [comment]
This issue is resolved by https://github.com/cloudflare/workers-sdk/pull/3124 - fix should be available in `wrangler@beta` in a few minutes.
