### ISSUE TITLE
🐛 BUG: Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by aivLuk** [cloudflare/workers-sdk#2827]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.12.0

### What operating system are you using?

Mac

### Describe the Bug

Getting this error when trying to run `wrangler dev --local --live-reload`. Weirdly when I simply run `webpack` app builds successfully, but when it tries to build via wrangler it errors. Read that this might be because of node 17 changes but I'm running on node 16.14.2.

Tried adding `NODE_OPTIONS=--openssl-legacy-provider webpack` to the build command and it works. However after that running simply `webpack` throws `--openssl-legacy-provider is not allowed in NODE_OPTIONS`. Tried running `unset NODE_OPTIONS` before the build but it doesn't work.

Weirdest part that I have another worker with the exact same set up and it works there. What can be the case?

wrangler.toml:

name = "worker"
main = "src/index.ts"
compatibility_date = "2023-02-27"
route = "example.com/*"

[build]
command = "yarn && yarn build"

**Comment by fishcharlie** [comment]
@aivLuk How did you solve this? I'm getting the same error.
