### ISSUE TITLE
🚀 Feature Request Geopoly/R*tree extensions in D1

### ISSUE THREAD

**Issue by lennybr** [cloudflare/workers-sdk#2833]
### Describe the solution

Is it possible to add the [Geopoly Extension](https://www.sqlite.org/geopoly.html#geojson) or [R*tree](https://www.sqlite.org/rtree.html#overview) for D1?

**Comment by rozenmd** [comment]
Hi @lennybr, we don't yet have plans to add those extensions, but we are exploring ways to let you write your own Worker to do the same thing in D1.

**Comment by johnswarbrick** [comment]
Hi @rozenmd, having a GeoSpatial plugin for Cloudflare D1 would fill a quite significant capability gap vs a cloud-hosted PostgreSQL or even SQLite database. Running the geospatial queries within D1 rwill always be more efficient than trying to do it through an external system such as a worker. I understand it's not on your roadmap currently, but I hope you might reconsider! :)

**Comment by ansarizafar** [comment]
Is there any progress on GeoSpatial queries? I badly need this feature.

**Comment by samf3nn** [comment]
Any news about this feature ?

**Comment by amadeuspagel** [comment]
If I upload a database with R*Tree indexes to D1, can I use these indexes in queries? EDIT: [Claude says no.](https://claude.ai/public/artifacts/37e12ff2-3616-4711-8785-1bd4bb584deb)

**Comment by non-bin** [comment]
Yes please?
