### ISSUE TITLE
🐛 BUG: `wrangler generate [name] [template]` doesn't work

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#2837]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

latest

### What operating system are you using?

Mac

### Describe the Bug

Following examples from https://developers.cloudflare.com/workers/get-started/quickstarts/#templates - I can't generate any projects, for example: 

```
rozenmd@cflaptop Testing % npx wrangler@latest generate my-app https://github.com/cloudflare/workers-sdk/tree/main/templates/worker
 ⛅️ wrangler 2.12.0
--------------------
Creating a worker in my-app from https://github.com/cloudflare/workers-sdk/tree/main/templates/worker

✘ [ERROR] Failed to find "tree/main/templates/worker" in https://github.com/cloudflare/workers-sdk.git


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
```

It also doesn't work if you run `npx wrangler generate my-app cloudflare/workers-sdk/tree/main/templates/worker-typescript`

**Comment by lrapoport-cf** [comment]
i believe this is a documentation error and should be fixed by https://github.com/cloudflare/cloudflare-docs/pull/7728

**Comment by Cherry** [comment]
Related: https://github.com/cloudflare/workers-sdk/issues/2799

**Comment by rozenmd** [comment]
What was the fix @penalosa ?

**Comment by Cherry** [comment]
As per https://github.com/cloudflare/workers-sdk/issues/2799#issuecomment-1453675243, this does not appear to be resolved. 🤔

**Comment by penalosa** [comment]
@rozenmd the QuickStart docs have been updated to fix the links
