### ISSUE TITLE
🐛 BUG: better-sqlite3 issue and Cloudflare dashboard D1 GET error

### ISSUE THREAD

**Issue by danboyle8637** [cloudflare/workers-sdk#2842]
### Which Cloudflare product(s) does this pertain to?

D1, Wrangler

### What version of `Wrangler` are you using?

2.12.0

### What operating system are you using?

Mac

### Describe the Bug

I have a bare bones worker that don't do anything else. Fresh init.

I have created a binding to a D1 database created through Wrangler. But when I try to run `wranger dev --local` I get this error: 

```
Error: npx-import failed for better-sqlite3 with message:
    Command failed with exit code 1: npx --prefer-offline -y -p better-sqlite3@8.0.1 printenv PATH
```

And for some reason I can't install better-sqlite3 locally. 

When I try to follow the tutorial in the docs on publishing a Worker with a D1 database... it fails when installing better-sqlite3.

Another strange issue:

When I log into my Cloudflare dashboard and go to my D1 databases... of which I only have the one.

I get this error popup at the bottom...

`API Request Failed: GET /api/v4/accounts/<ACCOUNT ID>/d1/database/<D1 Id>`

Where Account Id is my account id and D1 Id is the id for the D1 database I created.

Any ideas what might be the issue?

**Comment by IcedMonk** [comment]
Did you find the workaround?
Even i am facing the same issue.

**Comment by danboyle8637** [comment]
@IcedMonk I did not. I am also on a timeline so decided to use Planetscale for the next couple projects until D1 is ready for prime time.
