### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Kucharz37** [cloudflare/workers-sdk#2843]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms

### What version of `Wrangler` are you using?

2.12.0

### What operating system are you using?

Windows

### Describe the Bug
{
  "success": true,
  "challenge_ts": "2022-02-28T15:14:30.096Z",
  "hostname": "example.com",
  "error-codes": [],
  "action": "login",
  "cdata": "sessionid-123456789"
}

**Comment by JacobMGEvans** [comment]
👋🏻 Greetings, 

We appreciate issues being created. Could you provide us with more context of what this issue is, how it pertains to Wrangler or the Workers-SDK, and if you can provide a reproduction that would help us in debugging and prioritizing 😃 

Thanks!
