### ISSUE TITLE
🐛 BUG: Version 2.12.1 Wrangler pages publish ENOENT [ERROR] 

### ISSUE THREAD

**Issue by kewei5zhang** [cloudflare/workers-sdk#2871]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.12.1

### What operating system are you using?

Mac & Linux AMD

### Describe the Bug

Wrangler 2.12.1 failed pages publish build with the below error.

Error message:

```
Using API Token authentication
$ Running: wrangler pages publish build --project-name project-name --branch branch --commit-dirty=true
✨ Compiled Worker successfully

✘ [ERROR] ENOENT: no such file or directory, open '/github/workspace/tmp/functionsWorker-0.[24](https://github.com/org/repo/actions/runs/4360322086/jobs/7623108195#step:8:25)53403321635801.js'
```

How to reproduce:

- Upgrade wrangler to 2.12.1
-  Run:  wrangler pages publish build --project-name project-name

**Comment by GregBrimble** [comment]
I'm not able to reproduce this on macOS or using `ubuntu-latest` on GitHub Actions. Can you confirm your setup (ideally providing a link to a project if possible)? Can you also please confirm if you're using `_worker.js` or a folder of `functions/`?

**Comment by kewei5zhang** [comment]
Same issue in 2.12.2
<img width="758" alt="image" src="https://user-images.githubusercontent.com/9304284/224212518-583363b6-289b-4b55-b6a2-03b726837599.png">

**Comment by warren-bank** [comment]
off-topic.. quick question about static sites hosted with Cloudflare Pages:

when using `wrangler pages publish ...`, is there a way to upload new files without removing ones that had previously been pushed?

as an extreme example, if a site consists of 20k files and only 1 file needs to be updated.. is there a way to overwrite only that individual file without needing to reupload all 20k files?

sorry to hijack this issue.. I'll delete as soon as I get a response.
I haven't tried CP yet.. and the answer to this question will determine whether I do or not.
Thanks for the assist.

**Comment by admah** [comment]
@kewei5zhang  in an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. If this is still a problem, please feel free to open a new issue referencing this one. Please be sure to include an updated summary and any additional context and we will review.
