### ISSUE TITLE
🐛 BUG: Wrangler is using localhost instead of 127.0.0.1 to proxy requests

### ISSUE THREAD

**Issue by koyadume** [cloudflare/workers-sdk#2872]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.12.1

### What operating system are you using?

Windows

### Describe the Bug

I am using wrangler to proxy requests to vite dev/preview server which (unfortunately) listens on localhost instead of 127.0.0.1 in spite of passing `--host 0.0.0.0` flag. Due to this issue wrangler is unable to proxy request to vite dev/preview server. I can see that wrangler is using localhost at https://github.com/cloudflare/workers-sdk/blob/763f3f6b1d228ee7d920d1a081e5952f6e2ef80d/packages/wrangler/src/miniflare-cli/assets.ts#L56 line which should be updated to 127.0.0.1 to make it work with a proxy running with localhost or there should be a way to specify proxy host.

**Comment by yw662** [comment]
I don't think there should be any problem with it. localhost means 127.1 and ::1, it should listen to both if it says localhost, otherwise it is a bug of the underlying net library. If vite preview is listening on localhost but not 127.1, it can be a bug of node.

**Comment by koyadume** [comment]
I don't think listening on localhost means both 127.0.0.1 and ::1 on windows 10 with nodejs 17.x. I tried various combincations to make it work -

*   If I run vite dev server using `vite preview --host ::1` , it works. As per [this](https://stackoverflow.com/questions/21673068/dual-ipv4-and-ipv6-support-in-flask-applications) SO thread, we will need to use ::1 in order to make it listen on both ipv4 and ipv6.
*   localhost is resolving to `::1` on my laptop (windows 10) and so if I disable ipv6 or configure windows to prefer ipv4 over ipv6 using [these](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-ipv6-in-windows) instructions then it works as well with vite dev server listening on localhost only. However I would like to avoid changing things in the windows registry as I am not sure what could be the impact on other applications running on my laptop.

**Other things**

*   Starting 17.x, nodejs prefers ipv6 over ipv4 as per [this](https://www.reddit.com/r/ipv6/comments/qbr8jc/nodejs_finally_prefers_ipv6_addresses_over_ipv4/) post.
*   It seems vite dev server is not respecting value of `--host` flag because it is listening on ipv4 always even if I start it with `--host ::` flag.

I will close this defect here as I don't think it is an issue with wrangler.
