### ISSUE TITLE
Unable to Authenticate Wrangler in any Remote Development Environment

### ISSUE THREAD

**Issue by Grunet** [cloudflare/workers-sdk#2874]
[https://developers.cloudflare.com/workers/wrangler/commands/#using-wrangler-login-on-a-remote-machine](https://developers.cloudflare.com/workers/wrangler/commands/#using-wrangler-login-on-a-remote-machine) outlines how to authenticate the Wrangler CLI when using a remote development environment (e.g. Codespaces).

However it doesn't seem to work. The original shell always puts out this error message at the end

```bash
Received query string parameter doesn't match the one sent! Possible malicious activity somewhere.
```

I've seen this on Gitpod, Codespaces, Stackblitz, and Codesandbox so far so I don't think it's specific to any of them.

Is there an alternative form of authentication that could be used in the meantime? I haven't gotten api key-based authentication to work either

**Comment by Grunet** [comment]
My assumption is this has something to do with either Proof of Key Code Exchange (PKCE) and/or state for Cross Site Request Forgery (CSRF) protection, where after I authenticate via the UI, my local browser has something that running curl on the remote machine doesn't

**Comment by Grunet** [comment]
Yeah it's state https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/user/user.ts#L636

**Comment by Grunet** [comment]
Afaict the state is always a query parameter on the redirect URL from the Identity Provider (Cloudflare) and it matches what was sent initially by wrangler (the Referring Provider)

**Comment by Grunet** [comment]
Not sure what I did differently this time but following this code https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/user/auth-variables.ts#L14 I was able to do

```bash
export CLOUDFLARE_API_TOKEN=<API token generated from the Edit Workers template>
npx wrangler whoami
```

And that appears to have worked

Still not clear to me why the OAuth2 flow isn't working

**Comment by penalosa** [comment]
It sounds like you've got this working with API tokens? That's what we'd recommend for environments like Stackblitz and Codespaces. The remote machine authentication flow should work though (or should be removed from the docs), and so I'll leave this open to track investigating that.

**Comment by Grunet** [comment]
> It sounds like you've got this working with API tokens? 

Correct yeah, I think I found a comment on a closed issue that clued me in to trying that, and it's worked so far

**Comment by iamshaynez** [comment]
Seems D1 database is not (yet) supported by API Token.

```
✘ [ERROR] A request to the Cloudflare API (/accounts/xxxxxx/d1/database) failed.

  Authentication error [code: 10000]
```

wrangler login with manual curl on the localhost redirection doesn't work...

```
Received query string parameter doesn't match the one sent! Possible malicious activity somewhere.
```

**Comment by mishra-saksham** [comment]
@Grunet  
Thank you for writing this issues, 
I also was having the same issue until I found a simple way to communicate between the remote development environment and the local in browser account page of cloudflare 

So how it works is basically you are doing the same steps no change in that, 
1. `wrangler login`
2. `https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=<Your-Client-Code>&state=<Your-State-Token>&code_challenge=<Your-Challenge-Token>&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A8976%2Foauth%2Fcallback&scope=account%3Aread+user%3Aread+workers%3Awrite+workers_kv%3Awrite+workers_routes%3Awrite+workers_scripts%3Awrite+workers_tail%3Aread+zone%3Aread+offline_access`
3. You open the secure link in the browser where you have cloudflare account logged in. 
4. *Note* :  Cloudflare Auth after successful authorization will redirect you to the following query string `redirect_uri=http%3A%2F%2Flocalhost%3A8976%2Foauth%2Fcallback&scope=account%3Aread+user%3Aread+workers%3Awrite+workers_kv%3Awrite+workers_routes%3Awrite+workers_scripts%3Awrite+workers_tail%3Aread+zone%3Aread+offline_access` 
6. *After a successful* you will have be redirected to the page `http://localhost:8976/oauth/callback?code=<Your-Auth-Code>&scope=account%3Aread%20user%3Aread%20workers%3Awrite%20workers_kv%3Awrite%20workers_routes%3Awrite%20workers_scripts%3Awrite%20workers_tail%3Aread%20zone%3Aread%20offline_access&state=<Your-State-Token>` 
7. Well, to no surprise this page will not work in your current browser window as the origin is the remote development environment which is not accessible as localhost.
8. What can be done next is pretty the main stream principle of using curl internally for testing APIs in development servers.
9. So change the localhost to `127.0.0.1` or what ever your `*inet*` is there before subnet mask. [To get the details of internal networking use command `ip addr`, usually it is 127.0.0.1 if nothing is changed from defaults] 
10. Now your callback url should look like  `http://127.0.0.1:8976/oauth/callback?code=<Your-Auth-Code>&scope=account%3Aread%20user%3Aread%20workers%3Awrite%20workers_kv%3Awrite%20workers_routes%3Awrite%20workers_scripts%3Awrite%20workers_tail%3Aread%20zone%3Aread%20offline_access&state=<Your-State-Token>` 
11. Now open a new bash terminal or powershell or Terminal(macOS terminal)  and use the command `curl "<your-callback-url>"` #### the callback url is the one we made in the 10th point. 
12. Voila! you are now logged in. 
**Remember to fill in the details in the boilerplate url schema**

**Comment by lrapoport-cf** [comment]
hi @Grunet :) sounds like you've got things working and that @mishra-saksham is able to get the the remote machine authentication flow (https://developers.cloudflare.com/workers/wrangler/commands/#use-wrangler-login-on-a-remote-machine) going (thanks for the write up!). given this, i will close the issue now, thanks both!

**Comment by newsve** [comment]
Thanks for sharing, I tried and curl could connect and send its GET request:

```bash
*   Trying 127.0.0.1:8976...
* connect to 127.0.0.1 port 8976 failed: Connection refused
*   Trying ::1:8976...
* Connected to localhost (::1) port 8976 (#0)
> GET /oauth/callback?code=[redacted]
> Host: localhost:8976
> User-Agent: curl/7.81.0
> Accept: */*
```

but wrangler login replied with:
```bash
/home/[redacted]/node_modules/wrangler/wrangler-dist/cli.js:29573
            throw a;
            ^

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (/home/[redacted]/node_modules/wrangler/wrangler-dist/cli.js:5121:19)
    at successSteps (/home/[redacted]node_modules/wrangler/wrangler-dist/cli.js:5092:27)
    at fullyReadBody (/home/[redacted]/node_modules/wrangler/wrangler-dist/cli.js:3590:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (/home/[redacted]/node_modules/wrangler/wrangler-dist/cli.js:5101:7)
    at async exchangeAuthCodeForAccessToken (/home/[redacted]/node_modules/wrangler/wrangler-dist/cli.js:120821:31)
    at async Server.<anonymous> (/home/[redacted]/node_modules/wrangler/wrangler-dist/cli.js:120983:30)

Node.js v20.12.1
```
wrangler version: `⛅️ wrangler 3.51.2`

**Comment by thewaleed** [comment]
> ```shell
> API token generated from the Edit Workers template
> ```

where did u git "API token generated from the Edit Workers template" from?

**Comment by Grunet** [comment]
> > ```shell
> > API token generated from the Edit Workers template
> > ```
> 
> where did u git "API token generated from the Edit Workers template" from?

@thewaleed Go to My Profile > API Tokens > Create Token > Use Template for "Edit Cloudflare Workers"

**Comment by tkalejaiye** [comment]
Had this same issue and resolved it by forwarding port 8976 to my local machine when ssh-ing to the remote environment.

**Comment by faceslog** [comment]
Still the same issue with 3.78.3 tried: 

- https://developers.cloudflare.com/workers/wrangler/commands/#use-wrangler-login-on-a-remote-machine
- forwarding the port

**Comment by sugoidogo** [comment]
adding on to mishra's explanation, I had to change the host from `localhost` to `[::1]` instead of `127.0.0.1` in order for it to succeed. Using `localhost` gave me an invalid query string error, and using `127.0.0.1` curl failed to connect. It seems wrangler may be listening on ipv6 specifically in some cases and using locahost for that case somehow causes verification to fail, maybe the http host header is involved somehow? I don't know enough to speculate past that.

**Comment by avelops** [comment]
> Not sure what I did differently this time but following this code https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/user/auth-variables.ts#L14 I was able to do
> 
> ```shell
> export CLOUDFLARE_API_TOKEN="API token generated from the Edit Workers template"
> npx wrangler whoami
> ```
> 
> And that appears to have worked
> 
> Still not clear to me why the OAuth2 flow isn't working

that is by far the most straight forward route, thanks! (using .devcontainer)

**Comment by fredxfred** [comment]
Can we please reopen this issue? Headless login still is not directly supported and instead must rely on workarounds (those in this thread and the [official docs), ](https://developers.cloudflare.com/workers/wrangler/commands/#login)the workarounds in the [official documentation](https://developers.cloudflare.com/workers/wrangler/commands/#login) do not work for all the people commenting in this issue (nor for me). And to top it all off, for me none of the following work:

1. Official docs suggest to curl the localhost redirect -> ```Received query string parameter doesn't match the one sent! Possible malicious activity somewhere.```
2. ```export CLOUDFLARE_API_TOKEN="API token generated from the Edit Workers (or equivalent) template"``` -> wrangler in some cases treats me as logged in and in others does not. Did not actually allow me to complete uploading to cf pages
3. ```curl http://127.0.0.1:8976/...``` or equivalent instead of localhost -> ```Failed to connect to 127.0.0.1 port 8976 after 0 ms: Connection refused```
4. ```curl http://[0:0:1]:8976/...``` or equivalent instead of localhost -> ```Received query string parameter doesn't match the one sent! Possible malicious activity somewhere.```

Please can the wrangler team add better support for headless logins so that we don't need to follow these workarounds? I have never had a problem logging into the GCP CLI in a remote machine, and I don't think modifying wrangler to use a similar flow would be too difficult. Right now you essentially do not support headless logins with a stable interface that works across reasonably standard dev environment.

If you wanted to take the approach gcloud took, clientside you can add a login arg ```npx wrangler login --headless``` that generates a clickable link with a url param indicate the user is headless, and then waits for the user to paste in a token. Serverside you can read that headless arg and, when set, redirect to a page displaying the token (and whatever else you need wrangler to know to complete the login) for the user to copy back to wherever they are logging in (instead of a localhost url). That's how gcloud login works and it's perfectly functional, and not a huge change from what you have already.

**Comment by sugoidogo** [comment]
One possible cause could be bash/sh/etc interpreting special characters in the url, causing a modified url to be passed to curl instead of what is shown on the command line. I just signed in using the exact url successfully by putting quotes around it.

**Comment by b1m-dev** [comment]
> One possible cause could be bash/sh/etc interpreting special characters in the url, causing a modified url to be passed to curl instead of what is shown on the command line. I just signed in using the exact url successfully by putting quotes around it.

This worked for me with Codespaces.  Experience is shocking though.

**Comment by juparave** [comment]
> One possible cause could be bash/sh/etc interpreting special characters in the url, causing a modified url to be passed to curl instead of what is shown on the command line. I just signed in using the exact url successfully by putting quotes around it.

This is the way

**Comment by MirilRetry** [comment]
If you're using GitHub Codespaces and none of the three curl methods worked, here's an alternative that did work for me: use Python with the following simple script:
```python
import requests
requests.get("URL")
```
"URL" will be **unmodified** URL that Cloudflare redirected you to.

**Comment by NellowTCS** [comment]
Easy workaround for this, for me, is to just replace the localhost:8976 with https://codespace-8976.app.github.dev/

**Comment by prmichaelsen** [comment]
I would still love this--I use an API token but it's unwieldy having to run `export $(cat .env.cloudflare.local | xargs) && npx wrangler <command>` every time I want to use wrangler. See @NellowTCS's comment. This would be pretty straightforward

**Comment by mikewirth** [comment]
Adding my voice here to plead for reopening this issue and fully supporting headless auth in wrangler. At least an explanation why Cloudflare is reluctant to add this standard feature that many other popular CLIs, like the mentioned gcloud (others I've verified are claude, codex, flyctl) would be appreciated. @fredxfred makes the best 

It seems silly that to login to wrangler with OAuth in a remote environment, port forwarding or copying, editing an curling URLs is necessary.

To add some recency to the debate: With AI agents interacting on their own with cloudflare being more and more officially supported this becomes more pressing, as the default way for many is to run them in a sandboxed environment. Using wrangler in this case means jumping through the above mentioned hoops.

**Comment by Chekote** [comment]
I'd also like to see this decoupled. I understand that in some ways it's convenient, but a CLI shouldn't have a dependency on a GUI. Please support terminal exclusive auth. 🙏🏻

**Comment by csi-lk** [comment]
Just had this issue trying to login on a remote box, `curl` + swapping localhost for `127.0.0.1` + putting the url in quotes finally worked for anyone who stumbles across this (as I did from searching for the error message exactly)
