### ISSUE TITLE
🐛 BUG: Please enable R2 through the Cloudflare Dashboard. [code: 10042]

### ISSUE THREAD

**Issue by ecomba** [cloudflare/workers-sdk#2877]
### Which Cloudflare product(s) does this pertain to?

R2

### What version of `Wrangler` are you using?

2.12.2

### What operating system are you using?

Mac

### Describe the Bug

Running create bucket:

`wrangler r2 bucket create some-bucket`

Returns:

```
[ERROR] A request to the Cloudflare API (/accounts/xxx
Please enable R2 through the Cloudflare Dashboard. [code: 10042]
```

R2 is active (just set it up before running this command (after trying to do it on the cloudflare dashboard without success).

It's probably a bug at the server and not wrangler itself, but I want to keep a record of this here

**Comment by rock217** [comment]
I get this too from the CF console after subscribing.

**Comment by jspspike** [comment]
This looks like an issue in the backend, I will create an internal ticket for this

**Comment by penalosa** [comment]
I think this was resolved, so I'll close it for now. If you're still running into issues feel free to comment with more details and we can investigate further.
