### ISSUE TITLE
🚀 Feature Request: Configure esbuild bundling

### ISSUE THREAD

**Issue by shishkin** [cloudflare/workers-sdk#2882]
### Describe the solution

Currently wrangler pages functions bundling can either be off or on with little flexibility. It would help to have a way to tweak esbuild's configuration that wrangler is using under the hood. One use case for that is esbuild's define and inject options.

**Comment by g-otn** [comment]
Would be nice if the [Custom Builds](https://developers.cloudflare.com/workers/wrangler/custom-builds/) page had an full example using esbuild its easier to understand it.
