### ISSUE TITLE
🚀 Feature Request: access env in module's global scope

### ISSUE THREAD

**Issue by shishkin** [cloudflare/workers-sdk#2883]
### Describe the solution

Currently, pages functions (new syntax) receive the `env` in the `onRequest` method. It would help to get access to the `env` at the top level especially with support for top-level await. This would allow a worker to do init logic once before the request handler is called.

**Comment by CarmenPopoviciu** [comment]
NodeJS compat has been recently added, which enables NodeJS's async local storage https://nodejs.org/api/async_context.html#class-asynclocalstorage. You can use this to pass objects around like in the global scope

**Comment by penalosa** [comment]
This is a limitation/feature of the workers runtime when using module worker syntax (which Pages functions use under the hood). See https://developers.cloudflare.com/workers/learning/migrate-to-module-workers/#advantages-of-migrating, in particular:
> Workers using ES modules format do not rely on any global bindings. This means the Workers runtime does not need to set up fresh execution contexts, making Workers safer and faster to run.
