### ISSUE TITLE
🐛 BUG: Non-descriptive ERR_HTTP2_ERROR when running wrangler dev

### ISSUE THREAD

**Issue by frederik-wolf** [cloudflare/workers-sdk#2885]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.12.2

### What operating system are you using?

Windows

### Describe the Bug

I'm currently facing a non-descriptive ERR_HTTP2_ERROR when trying to run Wrangler for my development environment.

**The command I'm running**: `wrangler dev index.js --env=local`

**The error I'm receiving**:
```
C:\Users\****\AppData\Local\Yarn\Data\global\node_modules\wrangler\wrangler-dist\cli.js:30488
            throw a;
            ^

Error [ERR_HTTP2_ERROR]: Protocol error
    at new NghttpError (node:internal/http2/util:556:5)
    at Http2Session.onSessionInternalError (node:internal/http2/core:786:26)
Emitted 'error' event on ClientHttp2Session instance at:
    at emitClose (node:internal/http2/core:1079:10)
    at Array.<anonymous> (node:internal/http2/core:1118:7)
    at finish (node:internal/streams/writable:753:25)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_HTTP2_ERROR',
  errno: -505
}
```

The script I'm trying to run with Wrangler is a worker script making use of `itty-router` to provide a small api for link shortening. So I'm feeding all worker requests to itty-router and handle various routes from there.

So far the development process has been straightforward, however Zscaler Zero Trust got recently added to our infrastructure. My first problem of needing to make Zscaler's root certificate known to Node has already been solved of Discord. The error above showed up directly after solving that issue.

**Comment by JacobMGEvans** [comment]
Greetings 👋,
If you are able to provide a minimal viable reproduction, that would go a long way in helping us debug this. 

Thanks for reporting the issue.

**Comment by lrapoport-cf** [comment]
hi @fepimentel  :) it doesn't look like there's anything in the reproduction you mentioned, so we will close the issue for now. however, if this is still an issue and you are able to provide additional context, please feel free to re-open it. thanks!
