### ISSUE TITLE
🚀 Feature Request: Configuration via environment variables instead of wrangler.toml 

### ISSUE THREAD

**Issue by McSodbrenner** [cloudflare/workers-sdk#2898]
It would be helpful if the complete configuration (not only the `var`s, which is already possible now) could be set via environment variables instead of wrangler.toml. This would simplify the integration into CI pipelines.

You could then set a prefix via the CLI, for example, so that there is no conflict with existing env vars:
`wrangler publish --env-prefix WRANGLER`.
The `account_id = "..."` in wrangler.toml would then become `WRANGLER_ACCOUNT_ID`. The code would then have to read in all env vars that start with the prefix. Nested constructs could be mapped with "__" in the keys.

**Comment by penalosa** [comment]
Thanks for raising this! We won't be implementing this at this time, but it's definitely something we could potentially consider in the future. If you could add some more details on your use case (specifically why this would be helpful over and above a config file) to https://github.com/cloudflare/workers-sdk/discussions/1951, we'll make sure to take it into account when we come to focus on expanding the config formats Wrangler accepts.
