### ISSUE TITLE
🐛 BUG: `value of stdout.lastframe() is undefined` is returned with some Wrangler commands

### ISSUE THREAD

**Issue by leonlarsson** [cloudflare/workers-sdk#2907]
### Which Cloudflare product(s) does this pertain to?

D1, Wrangler

### What version of `Wrangler` are you using?

2.12.3

### What operating system are you using?

Windows

### Describe the Bug

The following steps both print out `value of stdout.lastframe() is undefined`:

Running `wrangler d1 execute DBNAME --file="./schema.sql` where schema.sql is:

```sql
DROP TABLE IF EXISTS cooltable;
CREATE TABLE cooltable (some_data TEXT NOT NULL, some_other_data TEXT NOT NULL);
```
Result:
```
🌀 Mapping SQL input into an array of statements
🌀 Parsing 2 statements
🌀 Executing on DBNAME (DBID):
🚣 Executed 2 commands in 8.666151999495924ms
value of stdout.lastframe() is undefined
```

---

Running a `wrangler d1 execute DBNAME --command` that returns no data.
For example, running `wrangler d1 execute DBNAME --command "SELECT * FROM cooltable"` or `wrangler d1 execute DBNAME --command "DROP TABLE cooltable"`
Result:
```
🌀 Mapping SQL input into an array of statements
🌀 Parsing 1 statements
🌀 Executing on DBNAME (DBID):
🚣 Executed 1 command in 4.784738999791443ms
value of stdout.lastframe() is undefined
```

It seems to come from here: https://github.com/cloudflare/workers-sdk/blob/6fd062419c6b66c2c5beb7c45ec84a32dfa89e01/packages/wrangler/src/utils/render.ts#L86

**Comment by petebacondarwin** [comment]
The output value comes from https://github.com/cloudflare/workers-sdk/blob/6fd062419c6b66c2c5beb7c45ec84a32dfa89e01/packages/wrangler/src/utils/render.ts#L46

**Comment by petebacondarwin** [comment]
I think the problem is that if there is no rendered output from the Ink.js component then there will be no last frame.

I'll look into this in case tomorrow.

**Comment by Qxxxx** [comment]
I don't know if it stops statements excution. I have three slq commands in `.sql` file but only one statement is excuted.
```
🌀 Mapping SQL input into an array of statements
🌀 Parsing 3 statements
🌀 Executing on DB (b5823f1d-d731-475c-a869-b51d965842cd):
🚣 Executed 1 command in 0.01684001088142395ms
value of stdout.lastframe() is undefined
```
