### ISSUE TITLE
🐛 BUG: Pub/Sub API always producing new client id

### ISSUE THREAD

**Issue by demosjarco** [cloudflare/workers-sdk#2909]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.12.3

### What operating system are you using?

Windows 11 21H1

### Describe the Bug

Using `--client-id ["01GVPB0WE375WAP5QCWSJ6QPJ6"]` on `wrangler pubsub broker issue` is being ignored. It still produces a new token AND client id, instead of same client id but new token. My goal of attempting this is to create short lived credentials but keeping the same client id for identification purposes.

I also attempted the underlying HTTP request in Insomnia (2023.1.0) too `/accounts/<account-id>/pubsub/namespaces/<namespace>/brokers/<broker>/credentials?clientid=%5B%2201GVPB0WE375WAP5QCWSJ6QPJ6%22%5D` but I still got a new client id AND token. Ray id `7a90ab888ae0a6f0` for the manual HTTP request.

**Comment by jspspike** [comment]
I've created an internal ticket for the pub/sub team to look into this

**Comment by lrapoport-cf** [comment]
hi @demosjarco :) thanks for flagging this. in an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. in the case of this particular issue, there is nothing we can do on the wrangler side, but as @jspspike noted, there is an internal ticket tracking this: MQTT-124. as a note, we do not have information regarding timeline on this, and it's not on the immediate roadmap of the relevant team.
