### ISSUE TITLE
Wrangler wants to delete a different worker than the one I wanted it to delete🐛 BUG:

### ISSUE THREAD

**Issue by MartinRoesch2** [cloudflare/workers-sdk#2915]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.12.3

### What operating system are you using?

Windows 11

### Describe the Bug

PS C:\Users\Martin\live1-lab> wrangler delete 2023-03-17--modules
 ⛅️ wrangler 2.12.3 
--------------------
√ Are you sure you want to delete project-2023-03-16? This action cannot be undone. ... yes

X [ERROR] A request to the Cloudflare API (/accounts/43d7ffddb2efb963b98c4c1bf091c2a8/workers/services/project-2023-03-16) failed

As you can see, I asked Wrangler to delete 2023-03-17--modules. But it prompts me for deleting project-2023-03-16.

**Comment by penalosa** [comment]
Thanks for reporting this! `wrangler delete --name 2023-03-17--modules` is how you specify a specific worker to delete (note the `--name` parameter). Hopefully that works for you!
