### ISSUE TITLE
🚀 Feature Request: CLI to add Environment Variables on Pages

### ISSUE THREAD

**Issue by Sagar-Chudamani** [cloudflare/workers-sdk#2938]
### Describe the solution

Need to add/set/update the Environment variables on Cloudflare Pages projects.

**Comment by penalosa** [comment]
Thanks for opening an issue! You can do this via the command line for Pages projects using Wrangler with the `--binding` flag:

```sh
npx wrangler pages dev --binding VAR=VALUE ./folder
```
