### ISSUE TITLE
🐛 BUG: Confusing error message for Durable Objects after drop to free plan

### ISSUE THREAD

**Issue by frankichiro** [cloudflare/workers-sdk#2944]
### Which Cloudflare product(s) does this pertain to?

Workers/Other

### What version of `Wrangler` are you using?

2.13.0

### What operating system are you using?

Mac

### Describe the Bug

I recently published a Worker that uses as Durable Object, and got the error message: `Durable Object namespace binding cannot communicate with other nodes.` For some reason my Durable Object would not work, and that was all the information I got.

In order to investigate this I created a separate Worker and Durable Object with bare minimum functionality just to try and pinpoint the problem. When I tried to publish everything, I was prevented from doing so as Wrangler asked me to first approve of a Paid plan for Workers, which I was under the impression that I already had.

As it turns out, I had an unpaid invoice that I had missed. So here is what I have learned:

- Trying to publish a new Durable Object while on the Free plan results in Wrangler asking to approve of a Paid plan. This is correct behaviour.
- If a Durable Object was created before the account reverted to a Free plan, thus already existing, it can still be updated without any mentions of Paid plan requirements, but it will generate the error mentioned above when being accessed.

So, the error message does not match the actual problem in this situation, which is unclear and could be improved.

**Comment by JacobMGEvans** [comment]
Greetings 👋 , 
Really appreciate taking the time to let us know about this user experience, we will be sure to discuss this and look into improving the messaging.

**Comment by lrapoport-cf** [comment]
hi @frankichiro :) thanks for flagging this. in an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and any additional context and we will review. thank you!
