### ISSUE TITLE
🐛 BUG:  ⛅️ wrangler 2.13.0

### ISSUE THREAD

**Issue by segurode** [cloudflare/workers-sdk#2951]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.13.0

### What operating system are you using?

Windows

### Describe the Bug

Statement from console: "X [ERROR] Missing entry-point: The entry-point should be specified via the command line (e.g. `wrangler dev path/to/script`) or the `main` config field."

Any workaround, please?

**Comment by penalosa** [comment]
Hi! Can you clarify what your issue is? Have you followed the steps given in the error message (specifying your main entrypoint in `wrangler.toml` or via the CLI)?

**Comment by penalosa** [comment]
We haven't heard from you in a while, so I'm going to close this for now. If it's still an issue, feel free to re-open and we can investigate further!
