### ISSUE TITLE
🐛 BUG: Support `*/*` route with `zone_id` routes

### ISSUE THREAD

**Issue by penalosa** [cloudflare/workers-sdk#2953]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.13.0

### What operating system are you using?

Mac

### Describe the Bug

Currently publishing `*/*` routes with a `zone_id` fails with an `Invalid URL` error. It works with `zone-name` routes

**Comment by 1000hz** [comment]
Closing as this issue is no longer present at the time of writing (current latest version of wrangler is 3.22.4).
