### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by kickstarterbuzz** [cloudflare/workers-sdk#2955]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

github vs studio

### What operating system are you using?

mac

### Describe the Bug

 [ERROR] Error: Pages only supports files **up to 26.2 MB in size**
Purged however not able to update, old logs going on and on, while the files is updated below<29mB
website cookie cleaned
Old log:
b/wwwroot.tar.gz is 60.4 MB in size

**Comment by penalosa** [comment]
Unfortunately this is a limitation of the Cloudflare Pages service—files can only be up to [25MB](https://developers.cloudflare.com/pages/platform/limits/#file-size) in size. Consider using [R2](https://developers.cloudflare.com/r2/) for storing large files (which doesn't have this file size limitation).
