### ISSUE TITLE
🎉 Feature Request: Don't run an update check in `unstable_dev`

### ISSUE THREAD

**Issue by Skye-31** [cloudflare/workers-sdk#2956]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.13.0 (but happens in all prior versions too)

### What operating system are you using?

Windows (though this doesn't have any effect)

### Describe the Bug

When running a wrangler command, it'll make a request to https://registry.npmjs.org/wrangler to let you know if there's an update that you can install. 

This behaviour also occurs in unstable_dev, which should not be the case, particularly when being used for things such as testing, as this slows the test down every time wrangler is run

**Comment by RamIdeas** [comment]
This sounds reasonable. There's no need to slow down each `dev` run. It's also quite likely the warning will be seen when running other commands
