### ISSUE TITLE
🐛 BUG: Failed to get worker definitions TypeError: fetch failed

### ISSUE THREAD

**Issue by jasonkuhrt** [cloudflare/workers-sdk#2959]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.13.0

### What operating system are you using?

Mac

### Describe the Bug

When running `wrangler pages dev --compatibility-date=2023-03-29 --compatibility-flag=nodejs_compat --local ./public` I get spammed (hundreds of times) with this error:

```
▲ [WARNING] Failed to get worker definitions TypeError: fetch failed

      at fetch
  (/Users/jasonkuhrt/projects/prisma/pdp-spike-control-plane-v2/node_modules/.pnpm/wrangler@2.13.0/node_modules/wrangler/wrangler-dist/cli.js:16584:17)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async getRegisteredWorkers
  (/Users/jasonkuhrt/projects/prisma/pdp-spike-control-plane-v2/node_modules/.pnpm/wrangler@2.13.0/node_modules/wrangler/wrangler-dist/cli.js:126469:22)
      at async getBoundRegisteredWorkers
  (/Users/jasonkuhrt/projects/prisma/pdp-spike-control-plane-v2/node_modules/.pnpm/wrangler@2.13.0/node_modules/wrangler/wrangler-dist/cli.js:126488:29)
  {
    cause: ConnectTimeoutError: Connect Timeout Error
        at onConnectTimeout
  (/Users/jasonkuhrt/projects/prisma/pdp-spike-control-plane-v2/node_modules/.pnpm/wrangler@2.13.0/node_modules/wrangler/wrangler-dist/cli.js:7185:29)
        at
  /Users/jasonkuhrt/projects/prisma/pdp-spike-control-plane-v2/node_modules/.pnpm/wrangler@2.13.0/node_modules/wrangler/wrangler-dist/cli.js:7141:51
        at Immediate._onImmediate
  (/Users/jasonkuhrt/projects/prisma/pdp-spike-control-plane-v2/node_modules/.pnpm/wrangler@2.13.0/node_modules/wrangler/wrangler-dist/cli.js:7173:13)
        at processImmediate (node:internal/timers:466:21) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }

```

**Comment by jamesmfinney93** [comment]
Currently, experiencing the same issue.
Have you managed to find a solution?

**Comment by dctanner** [comment]
Just started happening to me, making it hard to debug things!

**Comment by fullthom** [comment]
I'm also experiencing this at the moment - has anyone found a workaround?

**Comment by Soulusions** [comment]
I've been having this same issue overflowing my terminal, hiding actual caught errors, this only seems to happen when you leave the server be for a second then it doesn't stop sending this error.

**Comment by yw662** [comment]
I am having the same issue and I have to `wrangler pages dev ./dist --log-level error`. It is not a cure but a nice painkiller.

**Comment by nextjoshaustin** [comment]
Happening for me as well.

**Comment by penalosa** [comment]
Fixed by https://github.com/cloudflare/workers-sdk/pull/3048

**Comment by Cali93** [comment]
I'm also getting this error on 3.1.0 and 3.1.1.

**Comment by bryanlatten** [comment]
+1 seems to have regressed, same problem on 3.1.1

**Comment by paulgb** [comment]
Same, also on 3.1.1.

**Comment by lane711** [comment]
Rebooting my machine fixed this for me

**Comment by broofa** [comment]
Breadcrumb:  I was seeing this same issue.  I tried clearing the `node_modules` and `.wrangler/tmp` dirs, and restarting `wrangler` without success.

Ultimately @lane711 's solution (reboot host) fixed the problem.  Weird... 🤷 .
