### ISSUE TITLE
🐛 BUG: Getting 502 for large headers with wrangler dev

### ISSUE THREAD

**Issue by macebalp** [cloudflare/workers-sdk#2965]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.13.0

### What operating system are you using?

Windows

### Describe the Bug

I get a 502 with no logs if the Set-Cookies pass a a certain threshold when running a worker in my PC with wrangler.

Script to repro:
```js
export interface Env {}

const generateString = (length: number) => new Array(length + 1).join("s")

export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext
  ): Promise<Response> {
    try {
      const res = new Response(`Hello World!`);
      for(let i = 0;i < 5; i++){
        res.headers.append('set-cookie', `s${i}=` + generateString(670))
      }
      return res;
    } catch (error) {
      console.error(error);
      return new Response(`Error world`, { status: 500 });
    }
  },
};
```

It is a hello world Module worker written in Typescript, it generates 5 strings to set them as cookies. When i run this script with `wrangler dev` and using bare minimum toml file i get the expected 5 set-cookie headers. If i change it to generate 680 chars string (or more) it fails with 502 and no error logs trying both in regular and incognito in Chrome.

I have tried running wrangler with both Node 16 and 18

The limit seems too low as Cloudflare claims to support 32KB total header size and Node has a 16KB according the research i have done.

**Comment by macebalp** [comment]
One additional peace of information: I have tested with a single header to more accurately estimate the limit i'm hitting, and it is around 3500 chars.

**Comment by penalosa** [comment]
This is fixed as of Wrangler v3, which uses the open-source [`workerd`](https://github.com/cloudflare/workerd) to power local mode dev
