### ISSUE TITLE
🐛 BUG: can't deploy when using octokit (github api library)

### ISSUE THREAD

**Issue by javaboy-github** [cloudflare/workers-sdk#2975]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

 2.13.0 

### What operating system are you using?

Mac

### Describe the Bug

I'm trying to access github api with octokit and deploy it on cloudflare worker but deploying failed.

wrangler.toml

```toml
name = "github-api-demo"
main = "src/index.ts"
compatibility_date = "2023-04-01"
usage_model = "bundled"
env = { }

node_compat = true

[triggers]
crons = [ ]
```
error message:
```sh

> github-api-demo@0.0.0 deploy
> wrangler publish

 ⛅️ wrangler 2.13.0 
--------------------
▲ [WARNING] Enabling Node.js compatibility mode for built-ins and globals. This is experimental and has serious tradeoffs. Please see https://github.com/ionic-team/rollup-plugin-node-polyfills/ for more details.


Total Upload: 467.92 KiB / gzip: 87.89 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/66a2ce95fb1df2b9c81d22c3ff6cd6d8/workers/scripts/yetly-remote-edit) failed.

  Uncaught Error: Some functionality, such as asynchronous I/O, timeouts, and generating random
  values, can only be performed while handling a request.
    at index.js:3914:51 in _startAutoCleanup
    at index.js:3841:18 in Group2
    at index.js:13332:19 in createGroups
    at index.js:13369:5 in throttling
    at index.js:2956:31
    at index.js:2955:34 in Octokit2
    at index.js:2967:13 in OctokitWithDefaults
    at index.js:13468:15
   [code: 10021]

  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

**Comment by jspspike** [comment]
@javaboy-github Would you be able to share your worker code? As the error states certain things can only happen during the handling of a request. Meaning if you try to set a global variable to the result of a function that wouldn't be possible, instead you would have to make the variable set to a function which would then be called as you need it.
Based on your stack trace I suspect that the octokit library does something like this and is the cause of your error.

[Here](https://dev.to/kleeut/cloudflare-workers-some-functionality-can-only-be-performed-while-handling-a-request-3bne) is a blog post from someone who ran into a similar issue which might better explain this error

**Comment by javaboy-github** [comment]
src/index.ts
```typescript
import { Hono } from "hono";
import { Octokit } from "octokit";

const app = new Hono();
const octokit = new Octokit({auth:"My github api's token"})

app.get("/", async c => {
  return c.text("hello, world", 200)
})

export default app;
```
it's all.

**Comment by Ehesp** [comment]
@javaboy-github You need to create the Octokit instance inside of a request handler, not on the top level scope.

**Comment by javaboy-github** [comment]
@Ehesp  Thanks! It succeeded.
