### ISSUE TITLE
🐛 BUG: Failed to Parse URL

### ISSUE THREAD

**Issue by safaalai** [cloudflare/workers-sdk#2984]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler

### What version of `Wrangler` are you using?

2.14.0

### What operating system are you using?

macOS 13.2.1

### Describe the Bug

I installed wrangler 2.14.0 and ran wrangler pages dev. 

In my Front End HTML I have a button that calls out to an external service at some https://someexternaldomain.com/someurl.  This external service does some work then redirects back to a function.  I have configure it so that for my testing scenario it calls back to http://localhost:8788/somefunction.  The redirect has two query parameters.

When miniflare attempts to call the function, I get a crash with the following error:

`GET /somefunction?withqueryparams: TypeError: Failed to parse URL from [object Object]  
  at new Request (/project-directory/node_modules/undici/lib/fetch/request.js:85:15)`

I put a few console.log's in this code and found that baseURL is undefined but the input url is intact --i.e. http://localhost/somefunction?queryparams.

**Comment by safaalai** [comment]
FYI.  This same code functioned properly in 2.12.2

**Comment by safaalai** [comment]
Ok .. some more investigation.  The first new URL call on my plain http string works just fine.  However, for some reason this is immediately followed by another URL which is an object.  The error stack trace is as follows:

`TypeError: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:641:5)
    at new Request (/project-directory/node_modules/undici/lib/fetch/request.js:81:21)
    at new Request (/project-directory/node_modules/miniflare/node_modules/@miniflare/core/src/standards/http.ts:466:13)
    at EventTarget.dispatchFetch (/project-directory/node_modules/miniflare/node_modules/@miniflare/core/src/index.ts:1077:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Server.<anonymous> (/project-directory/node_modules/@miniflare/http-server/src/index.ts:291:20) {
  input: '[object Object]',
  code: 'ERR_INVALID_URL'
`

**Comment by safaalai** [comment]
The only way I can think of reproducing this is to call to some worker on a URL which then calls back to a function.

So the setup is this:
1.  Have a basic HTML page in a pages project that has a button that links to a worker.  This worker should be sitting on cloudflare --i.e. not local.
2. Have the worker call "http://localhost:8788/somefunction"
3. Have "somefunction.ts" under the pages functions directory
4. Call wrangler pages dev to run the pages project
5. Click on the button
6. See the result

**Comment by safaalai** [comment]
I've pinned down the exact npm version that this bug occurs:
Referring to [Wrangler version history on npmjs](https://www.npmjs.com/package/wrangler?activeTab=versions)
The system works on version [0.0.0-9af1a640](https://www.npmjs.com/package/wrangler/v/0.0.0-9af1a640)
But we get the bug on the next version [0.0.0-dc1465ea](https://www.npmjs.com/package/wrangler/v/0.0.0-dc1465ea)

**Comment by penalosa** [comment]
Looks like this is fixed!
