### ISSUE TITLE
🐛 BUG: --experimental-local requires zone lookup when route is present in wrangler.toml

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/workers-sdk#2987]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.14.0

### What operating system are you using?

Mac

### Describe the Bug

When using `--experimental-local` with a Worker where a route is configured in `wrangler.toml`, a network request to validate the zone is made, even though it's not necessary.

In cases where the zone for the specified route can't be found in the user's Cloudflare account, Wrangler spits back the following error:

```
✘ [ERROR] Could not find zone for foo.dev
```

In cases where you're offline, Wrangler gives you back:

```
✘ [ERROR] fetch failed
```

Local mode should support offline development. This issue is only present when using `--experimental-local`. Seems like the zone lookup should never happen when running in local dev?

### Steps to reproduce

1. `wrangler init`
2. Add a route to `wrangler.toml`, ex: `route = "https://foo.dev"`
3. `wrangler dev --experimental-local`
4. Observe the `✘ [ERROR] Could not find zone for foo.dev` error
5. `wrangler dev --local`
6. Observe that no such error is present

**Comment by admah** [comment]
Thanks for submitting this @irvinebroque. I can confirm this as well.

**Comment by irvinebroque** [comment]
🔥 thank you @penalosa!
