### ISSUE TITLE
🐛 BUG: workers.api.error.unauthorized [code: 10023]

### ISSUE THREAD

**Issue by barabo** [cloudflare/workers-sdk#2991]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.14.0

### What operating system are you using?

Mac

### Describe the Bug

I'm trying to publish a new worker from the CLI using `wrangler`.  I am able to deploy new workers in the Cloudflare UI using my account, but when I try from the command line I get a permission error `workers.api.error.unauthorized [code:10023]`

I've confirmed that I'm logged-in from the CLI via `wrangler whoami`.

<details><summary>See `whoami` output</summary>

```
(base) canderson@hostname % wrangler whoami
 ⛅️ wrangler 2.14.0 
--------------------
Getting User settings...
👋 You are logged in with an OAuth Token, associated with the email canderson@anaconda.com!
┌──────────────────────────────────┬──────────────────────────────────┐
│ Account Name                     │ Account ID                       │
├──────────────────────────────────┼──────────────────────────────────┤
│ Anaconda, Inc                    │ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX │
├──────────────────────────────────┼──────────────────────────────────┤
│ Canderson@anaconda.com's Account │ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX │
└──────────────────────────────────┴──────────────────────────────────┘
🔓 Token Permissions: If scopes are missing, you may need to logout and re-login.
Scope (Access)
- account (read)
- user (read)
- workers (write)
- workers_kv (write)
- workers_routes (write)
- workers_scripts (write)
- workers_tail (read)
- d1 (write)
- pages (write)
- zone (read)
- offline_access 
```

</details>

I've tried `wrangler logout` and `wrangler login`.  I've been sure to select `Anaconda, Inc` when I log in via wrangler CLI.

I've confirmed that my KV namespace ID is correct, and that all the environment variables and secrets that are referenced in the worker exist in the deployment via the UI.

I think it's odd that I'm able to create deployments in the UI, but unable to in the CLI.

<details><summary>Click to see my `wrangler.toml`</summary>

```
name = "virtual-staging-channel-prod"
main = "src/index.js"
compatibility_date = "2023-03-13"
send_metrics = true

routes = ["staging.continuum.io/*"]
usage_model = "unbound"
logpush = true

kv_namespaces = [
  { binding = "REPODATA", id = "XXXXXXXXXXXXXXXXXXXXXXXXXX" }
]

[vars]
AWS_REGION = "us-east-1"
AWS_S3_BUCKET = "ci-staging-test"

# Use `wrangler secret put` to set these for the AWS bucket account:
# AWS_ACCESS_KEY_ID = "*************"
# AWS_SECRET_ACCESS_KEY = "******************************"
```

</details>

I tried again another way by generating an API token with full `worker` permissions selected.  I ended up with the same result.

I did find that if I remove the `logpush` option from my `wrangler.toml` the worker *is* deployed, but I still end up with an `Authentication error [code: 10000]` with it tries to update the worker routes.

<details><summary>Click to see the wrangler warning emitted</summary>

```
Uploaded virtual-staging-channel-prod (0.87 sec)
▲ [WARNING] The current authentication token does not have 'All Zones' permissions.

  Falling back to using the zone-based API endpoint to update each route individually.
  Note that there is no access to routes associated with zones that the API token does not have
  permission for.
  Existing routes for this Worker in such zones will not be deleted.
```

</details>

I eventually discovered that if I `unset CLOUDFLARE_API_TOKEN` and resort to using the OAuth authentication - it finally works.  So, `logpush` was my culprit.  Sharing for posterity.

**Comment by JacobMGEvans** [comment]
Amazing issue, love the use of <details> and thank you for sharing your problem and solution!

**Comment by codeoholic** [comment]
Facing the same issue. Even tried v2.9.0 but still getting 10023. Had to ultimately remove logpush as recommended by @barabo. Carl, thank you for sharing this.

**Comment by jackmcpickle** [comment]
Removing `logpush` from the `wrangler.toml` worked for me too.

**Comment by cristianmadularu** [comment]
Isn't there an additional scope that could be added to the CLOUDFLARE_API_TOKEN in order to be able to deploy even when logpush is set?
