### ISSUE TITLE
Variables from .env are undefined

### ISSUE THREAD

**Issue by aivLuk** [cloudflare/workers-sdk#2992]
Not sure if it's a bug or I simply don't understand how environment variables work with workers, but I have a .env file with variables defined in it. When I try to console.log `process.env.SOME_VAR` and run `wrangler dev --local` I get undefined in the console.

I'm using `service-worker` syntax. A barebone example of worker showcases this. Try init a worker, create `.env` file, console.log it with `process.env` and run `wrangler dev --local`.

Adding these vars to `.dev.vars` file and using module syntax works, however I have a much bigger worker project and really dislike the idea of prop drilling `env` from the `fetch` function.

Reading docs seems like .env should work but it doesn't --> https://developers.cloudflare.com/workers/wrangler/system-environment-variables/

Using wrangler 2.14.0

What are my options here? Can I use newest wrangler with service worker syntax and have my env variables defined in `.env` and working?

**Comment by KianNH** [comment]
`process.env` is a Node thing, it doesn't exist in Workers. Similarly, `.env` isn't respected by Workers and `.dev.vars` is only for local development.

When using Service Workers (`addEventListener`), all of your bindings are just globals.

**Comment by aivLuk** [comment]
But it worked before with wrangler 1 and `wrangler preview`. Also in the docs it says:

Create an .env file in your project directory. Set the values of your environment variables in your [.env](https://developers.cloudflare.com/workers/wrangler/system-environment-variables/#example-env-file) file. This is the recommended way to set these variables, as it persists the values between Wrangler sessions.

Another thing, `process.env` exists, it's just an empty object.

**Comment by KianNH** [comment]
> Create an .env file in your project directory. Set the values of your environment variables in your [.env](https://developers.cloudflare.com/workers/wrangler/system-environment-variables/#example-env-file) file. This is the recommended way to set these variables, as it persists the values between Wrangler sessions.

This is for Wrangler, not your Worker.

> Another thing, `process.env` exists, it's just an empty object.

Your variables, secrets and bindings in Workers will never be under `process.env`.

**Comment by admah** [comment]
The docs on using environment variables in Workers can be found [here](https://developers.cloudflare.com/workers/platform/environment-variables/).  I'm going to close this issue out. If there is a bug please reopen.

As a side note, unless you need service-worker syntax for some reason, we recommend that you start new Workers with module syntax.
