### ISSUE TITLE
🐛 BUG: tail.developers.workers.dev cert altname is api.twitter.com

### ISSUE THREAD

**Issue by pureliumy** [cloudflare/workers-sdk#2996]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.14.0

### What operating system are you using?

Mac

### Describe the Bug

When running `wrangler tail [worker name]`, there will be an error related to SSL cert.

```
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: tail.developers.workers.dev. is not in the cert's altnames: DNS:api.twitter.com
```

Btw, I can't established a Websocket connection in Cloudflare dashboard too.

**Comment by Erisa** [comment]
It works for me.

Most likely this is an issue with your network connection. What happens if you visit https://tail.developers.workers.dev/ and then click the padlock in the top left  and "View certificate" (or equivalent for non-chrome)? Does it show a Cloudflare certificate or something else?
