### ISSUE TITLE
🐛 BUG: Error: Script startup exceeded CPU time limit. [code:   1002]

### ISSUE THREAD

**Issue by theleaks** [cloudflare/workers-sdk#3002]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.14.0

### What operating system are you using?

Mac

### Describe the Bug

```
import { JsonRpcProvider } from "ethers";  /v4 ~ v6.2 tested.

const provider = new JsonRpcProvider("<RPC_URL>");
```

Script startup exceeded CPU time limit.

I am using the Paid plan - Unbound package.

**Comment by zer0stars** [comment]
Having the same issue.

**Comment by kampfmodz** [comment]
me aswell, any updates?

**Comment by odyslam** [comment]
I am encountering this myself

**Comment by odyslam** [comment]
@ricmoo I know you spent some time making ethers compatible with Cloudflare workers in the past. Perhaps you have some insight on how Cloudflare or the community can fix this? Thanks!

**Comment by odyslam** [comment]
So, I figured out the solution from the Cloudflare dev Discord server. Because `ethers` is a big library, you must await the import. 
```Typescript
    const ethers = await import('ethers');
```
cc @ricmoo for visibility
