### ISSUE TITLE
🐛 BUG: Time stops passing according to Date.now with wrangler dev --local

### ISSUE THREAD

**Issue by Code6226** [cloudflare/workers-sdk#3008]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.14.0 

### What operating system are you using?

Windows 10

### Describe the Bug

I have a worker using a Durable Object. There, I use `Date.now()` (or `new Date()`, which has the same bug).

Expected:
- Receive the current time each time it's called

Actual:
- Receive the correct time the first time it's called, but further calls always return the original time.

For example, here is a Durable Object constructor:
```
  constructor(state, env) {
    setInterval(() => {
      // Time freezes???
      let nowTS = Date.now()
      console.log('EVERY SEC TICK', new Date(), this.testTS, nowTS, nowTS === this.testTS ? 'TIME HAS STOPPED' : 'ok')
      this.testTS = nowTS
    }, 1000)
  }
```

This produces the following output when running `wrangler dev --local`:

```
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798340 1680966798352 ok
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
EVERY SEC TICK 2023-04-08T15:13:18.352Z 1680966798352 1680966798352 TIME HAS STOPPED
```

This bug only occurs when running locally.

**Comment by penalosa** [comment]
This is expected behaviour for the Workers runtime, in order to mitigate against Spectre attacks. See https://developers.cloudflare.com/workers/learning/security-model/#step-1-disallow-timers-and-multi-threading for more details.

**Comment by Code6226** [comment]
Thanks for the info, but I don't think that's what's happening in my scenario.

1) I am able to get the correct time in production. Time only freezes for me when using `wrangler dev --local`. Without `--local`, time does not freeze. So I don't think this is Spectre protection kicking in.
2) Time is freezing in a long running Durable Object (locally only). I'm basically following the web socket chat example. So this Durable Object could well be running for an hour straight. If I want to get a timestamp when a web socket message arrives, I think that's a valid scenario that should be supported. And it does work just fine in production. I have found a work around locally, but I'd rather not have to use a workaround locally, since it already works fine in production

**Comment by emilioastarita** [comment]
@Code6226 can you share what workaround did you find? 

Probably worth to add some kind of warning in console. I've been debugging my Durable Object and I was really confused because this.

**Comment by penalosa** [comment]
@Code6226 Can you provide a self contained reproduction repo?

Does this reproduce with `wrangler dev --experimental-local`?

**Comment by emilioastarita** [comment]
It's just adding a `setInterval` task during object construction and logging the value of the call:
 
https://github.com/emilioastarita/durable-object-with-date
