### ISSUE TITLE
🐛 BUG: `d1 execute` command fails reading sql file which ends with comment line

### ISSUE THREAD

**Issue by reta-ygs** [cloudflare/workers-sdk#3012]
### Which Cloudflare product(s) does this pertain to?

D1

### What version of `Wrangler` are you using?

2.14.0

### What operating system are you using?

Mac

### Describe the Bug

SQL file:
```schema.sql
DROP TABLE IF EXISTS comments;
-- Optionally, uncomment the below query to create data
```

command:
```bash
wrangler d1 execute db --local --file schema.sql
```

**Comment by JacobMGEvans** [comment]
👋🏻 Greetings,
I appreciate the report. This is the repo and issues for Wrangler (Cloudflare Worker CLI) Pages, & Other SDK tooling, this seems D1 specific.

Feel free to check out the Cloudflare Discord where there is a channel for D1 as well: https://discord.com/invite/cloudflaredev

To report issues related to D1 specifically:
https://community.cloudflare.com/c/developers/d1/85/l/latest

Cc: @nevikashah @rozenmd

**Comment by rozenmd** [comment]
Thanks for reporting this @reta-ygs, we'll take a look

**Comment by rozenmd** [comment]
Wrangler now handles this correctly.

Consider upgrading to either `wrangler@beta` or `wrangler@3.0.1`
