### ISSUE TITLE
🐛 BUG: No routes found when building Functions directory: /opt/buildhome/repo/functions

### ISSUE THREAD

**Issue by CallumWatkins** [cloudflare/workers-sdk#3015]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

unknown

### What operating system are you using?

n/a

### Describe the Bug

See the functions directory here:
https://github.com/CallumWatkins/website/tree/master/functions

<details>
<summary>CF Pages Deploy Log</summary>

23:53:14.775 | Cloning repository...
:-- | :--
23:53:17.292 | From https://github.com/CallumWatkins/website
23:53:17.293 | * branch            56544c3ef4a50ad7e1a5f2a4edd60f41acc160ad -> FETCH_HEAD
23:53:17.293 |  
23:53:17.590 | HEAD is now at 56544c3 Merge pull request #47 from CallumWatkins/feature/content-2023-02
23:53:17.590 |  
23:53:17.749 |  
23:53:17.783 | Success: Finished cloning repository files
23:53:18.449 | Installing dependencies
23:53:18.459 | Python version set to 2.7
23:53:20.970 | Attempting node version '18.12' from .nvmrc
23:53:22.280 | Downloading and installing node v18.12.1...
23:53:22.635 | Downloading https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.xz...
23:53:23.013 | Computing checksum with sha256sum
23:53:23.153 | Checksums matched!
23:53:28.258 | Now using node v18.12.1 (npm v8.19.2)
23:53:28.683 | Started restoring cached build plugins
23:53:28.697 | Finished restoring cached build plugins
23:53:29.229 | Attempting ruby version 2.7.1, read from environment
23:53:31.250 | Using /opt/buildhome/.rvm/gems/ruby-2.7.1
23:53:32.266 | Using PHP version 5.6
23:53:32.411 | 5.2.5 is already installed.
23:53:32.439 | Using Swift version 5.2.5
23:53:32.439 | Started restoring cached node modules
23:53:32.456 | Finished restoring cached node modules
23:53:32.980 | Installing NPM modules using NPM version 8.19.2
23:53:34.241 | npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
23:53:34.241 | npm WARN config location in the cache, and they are managed by
23:53:34.241 | npm WARN config     [`cacache`](http://npm.im/cacache).
23:53:34.654 | npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
23:53:34.654 | npm WARN config location in the cache, and they are managed by
23:53:34.654 | npm WARN config     [`cacache`](http://npm.im/cacache).
23:53:38.650 | npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
23:53:38.792 | npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
23:53:47.013 |  
23:53:47.013 | > postinstall
23:53:47.014 | > nuxt prepare
23:53:47.014 |  
23:53:47.150 | Nuxi 3.2.2
23:53:49.107 | ✔ Types generated in .nuxt
23:53:49.156 |  
23:53:49.157 | added 857 packages, and audited 858 packages in 15s
23:53:49.157 |  
23:53:49.157 | 191 packages are looking for funding
23:53:49.157 | run `npm fund` for details
23:53:49.159 |  
23:53:49.159 | found 0 vulnerabilities
23:53:49.176 | NPM modules installed
23:53:49.249 | Installing Hugo 0.54.0
23:53:49.944 | Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
23:53:49.948 | Started restoring cached go cache
23:53:49.970 | Finished restoring cached go cache
23:53:50.120 | go version go1.14.4 linux/amd64
23:53:50.138 | go version go1.14.4 linux/amd64
23:53:50.142 | Installing missing commands
23:53:50.143 | Verify run directory
23:53:50.143 | Executing user command: nuxt generate
23:53:50.254 | Nuxi 3.2.2
23:53:50.273 | Nuxt 3.2.2 with Nitro 2.2.2
23:53:51.293 |  
23:53:51.293 | WARN  Using experimental payload extraction for full-static output. You can opt-out by setting experimental.payloadExtraction to false.
23:53:51.293 |  
23:53:53.213 | ℹ Building client...
... | ...
23:54:02.769 | Finished
23:54:02.770 | Found Functions directory at /functions. Uploading.
23:54:03.411 |  
23:54:03.517 | ✘ [ERROR] No routes found when building Functions directory: /opt/buildhome/repo/functions
23:54:03.518 |  
23:54:03.518 |  
23:54:03.518 | If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
23:54:03.530 | Warning: Wrangler did not find routes when building functions. Skipping.
23:54:03.531 | Validating asset output directory
23:54:04.282 | Deploying your site to Cloudflare's global network...
... | ...
23:54:07.993 |  
23:54:07.995 | ✨ Success! Uploaded 131 files (2.25 sec)
23:54:07.996 |  
23:54:08.364 | ✨ Upload complete!
23:54:10.055 | Success: Assets published!
23:54:10.841 | Success: Your site was deployed!

</details>

**Comment by rmouser** [comment]
I see this bug too. Running hugo static site, want to add a function. Tried creating _routes.json, no difference.

[build.log](https://github.com/cloudflare/workers-sdk/files/11436620/build.log)

**Comment by rmouser** [comment]
Update: For my JavaScript worker, removing "default" from the export statement got me past this issue.

**Comment by GregBrimble** [comment]
Looks like you've figured it out. Yeah, the exports should look like `export const onRequest = () => {}` for Pages Functions (not default-exported).
