### ISSUE TITLE
🐛 BUG: Uncaught TypeError: Object prototype may only be an Object or null: undefined at worker.js

### ISSUE THREAD

**Issue by digitdash** [cloudflare/workers-sdk#3016]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.15.0

### What operating system are you using?

Linux

### Describe the Bug

Randomly, whenever I try to deploy to CF worker, it outputs the following error at the very end of the deployment:

`  Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at worker.js:10823:45 in oa.exports
    at worker.js:11435:10 in require_stream_readable
    at worker.js:11744:275
    at worker.js:11758:6
    at worker.js:19905:4
    at worker.js:19906:3
   [code: 10021]`

This appears after wrangler is finished syncing assets, and due to it im not able to deploy at all to my CF worker.

**Comment by digitdash** [comment]
Any update on this

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to provide a reproduction repository for this issue?

**Comment by penalosa** [comment]
We haven't heard from you in a while, so I'm going to close this issue for now. If you're still running into issues feel free to comment with more details and we can investigate further
