### ISSUE TITLE
Update prerelease registry allow list format to include team name

### ISSUE THREAD

**Issue by lrapoport-cf** [cloudflare/workers-sdk#3017]
Update the prerelease registry allow list (https://github.com/cloudflare/workers-sdk/blob/main/packages/prerelease-registry/functions/utils/repoAllowlist.ts) format to include a team name. This is to track which internal teams are adding which repos to the allow list, in the case that teams need to be contacted.

**Comment by penalosa** [comment]
A year later, I think we can close this. At the time, I think we were concerned that we'd end up with a lot of users of the pre-release registry, which would lock us down from making changes. However, this didn't end up being a problem, and so this is no longer relevant.
