### ISSUE TITLE
🐛 BUG: `wrangler init --from-dash <name>` does not create package.json

### ISSUE THREAD

**Issue by mattdeboard** [cloudflare/workers-sdk#3029]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.15.0

### What operating system are you using?

Ubuntu Linux

### Describe the Bug

When I run `wrangler init --from-dash <name>`, the UI asks if I want to use git, then it asks if I want to use TypeScript, and those are the only prompts I get. Below is a screenshot showing the whole UI flow for this command:

![image](https://user-images.githubusercontent.com/306571/231540013-c52a5804-d67c-4c7a-8391-a50db47e38b5.png)

This is different than `wrangler init <name>`, where the UI does ask if I want to include a package.json.

**Comment by mxschumacher** [comment]
I tried to reproduce this bug, but could not, there a few differences between our two systems even though we are both on Linux (Manjaro in my case) and both using wrangler 2.15.0, I get the prompt for package json and it gets created after. Please see my output below

```
[I] λ wrangler init --from-dash steep-boat-01af                                                      (noPackageJson) 23:14:18
 ⛅️ wrangler 2.15.0
--------------------
Using npm as package manager.
✔ Select an account › max_personal
✨ Created steep-boat-01af/wrangler.toml
✔ Would you like to use git to manage this Worker? … yes
✨ Initialized git repository
✔ No package.json found. Would you like to create one? … yes
✨ Created steep-boat-01af/package.json
✔ Would you like to use TypeScript? … yes
✨ Created steep-boat-01af/tsconfig.json
▲ [WARNING] After running `wrangler init --from-dash`, modifying your worker via the Cloudflare dashboard is discouraged.

  Edits made via the Dashboard will not be synchronized locally and will be overridden by your local
  code and config when you publish.


npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

added 103 packages, and audited 104 packages in 15s

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
✨ Installed @cloudflare/workers-types and typescript into devDependencies

To start developing your Worker, run `cd steep-boat-01af && npm start`
To publish your Worker to the Internet, run `npm run deploy`
[I] λ cd steep-boat-01af/                                                                            (noPackageJson) 23:15:13
[I] (main) λ ls                                                                                    (steep-boat-01af) 23:15:18
 node_modules   package-lock.json   package.json   src   tsconfig.json   wrangler.toml
```

The "Delegating to locally-installed wrangler@2.15.0 over global wrangler@2.15.0" is strange, this message should only show if the versions are different, but in your case they are not.

Is there anything specific about the wrangler you have created in your dash? I just used the default template without any further modifications for my test.

Just for completeness, could you please let me know which version of node is installed on your machine?

**Comment by mxschumacher** [comment]
Relevant logic is here: https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/init.ts#L254 

Are you running the command within a completely empty folder or is it possible that there's already a package.json present? 

Maybe you could try one more time with:
```
ls -a 
wrangler init --from-dash <name of your worker>
ls -a
```

**Comment by mattdeboard** [comment]
Interesting, yes there is a random `package.json` in this folder I ran the command in. The folder is not actually a package, it just happened to have that file in there.

**Comment by mattdeboard** [comment]
Still, is this the desired behavior? I'd think you would still want to prompt for creating a package.json, no?

**Comment by penalosa** [comment]
The `wrangler init` command has been deprecated in `wrangler@3` in favour of `npm create cloudflare`, and so I'll close this issue for now. If you're still running into issues feel free to comment with more details and we can investigate further!
