### ISSUE TITLE
🐛 BUG: Middleware should support an env-wrapping construct to wrap the env of both durable objects and workers

### ISSUE THREAD

**Issue by nikitapilgrim** [cloudflare/workers-sdk#3044]
### Which Cloudflare product(s) does this pertain to?

Workers/Other

### What version of `Wrangler` are you using?

2.15.1

### What operating system are you using?

Mac

### Describe the Bug

in local development mode, access to service binding within DO is lost
https://github.com/nikitapilgrim/bugworkerlocalenv

**Comment by penalosa** [comment]
Thanks for reporting this! Is it reproducible with `wrangler dev --experimental-local`?

**Comment by nikitapilgrim** [comment]
> Thanks for reporting this! Could you provide the exact commands you're running in your project?

cd random
wrangler dev --locel

cd ..
wrangler dev --local 

post http://127.0.0.1:8787

{
	"worker": {
		"Test": {},
		"random": {}
	},
	"DO": {
		"Test": {}
	}
}

there is no access to random service inside the DO

**Comment by penalosa** [comment]
We've confirmed this is a bug in the internal middleware system—we'll get this fixed!

**Comment by penalosa** [comment]
This should be fixed in the next release of Wrangler
