### ISSUE TITLE
🐛 BUG: unstableDev is exposed in default project scaffold/boilerplate

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workers-sdk#3045]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.15.1

### What operating system are you using?

Mac

### Describe the Bug

When I scaffold a new project via `wrangler init`, the following prompt defaults to "Y":

> ? Would you like us to write your first test with Vitest? › (Y/n)

and results in the `index.test.ts` being created with the following content:

```ts
import { unstable_dev } from "wrangler";
import type { UnstableDevWorker } from "wrangler";
import { describe, expect, it, beforeAll, afterAll } from "vitest";

describe("Worker", () => {
  let worker: UnstableDevWorker;

  beforeAll(async () => {
    worker = await unstable_dev("src/index.ts", {
      experimental: { disableExperimentalWarning: true },
    });
  });

  afterAll(async () => {
    await worker.stop();
  });

  it("should return Hello World", async () => {
    const resp = await worker.fetch();
    if (resp) {
      const text = await resp.text();
      expect(text).toMatchInlineSnapshot(`"Hello World!"`);
    }
  });
});
```

Note that the test file depends on `unstableDev` which as the name suggests is an unstable API.

We won't be maturing this API any time soon, and exposing it in all newly created projects only creates a liability for us and sets wrong expectations with developers.

I recommend that we change the default to N as part of v3.

**Comment by 1000hz** [comment]
Closing since `wrangler init` has been deprecated in wrangler v3 and project scaffolding has been deferred to `create-cloudflare`
