### ISSUE TITLE
🐛 BUG: Account ID is not respected when applying migrations

### ISSUE THREAD

**Issue by imconnorngl** [cloudflare/workers-sdk#3046]
### Which Cloudflare product(s) does this pertain to?

D1

### What version of `Wrangler` are you using?

2.15.1

### What operating system are you using?

Linux

### Describe the Bug

When using the wrangler CLI to apply migrations on a D1 database, I am prompted with the  `More than one account available but unable to select one in non-interactive mode.`.

This does not occur when using wrangler publish from the same `wrangler.toml` and the worker is published correctly, however, running `wrangler d1 migrations apply github-webhook` results in the above prompt. 

This is my `wrangler.toml` file:

```
name = "github-webhook"
main = "./src/index.ts"
compatibility_date = "2023-04-09"
node_compat = true
account_id = "<account id>"

[[ d1_databases ]]
binding = "DB"
database_name = "github-webhook"
database_id = "<database id>"
migrations_dir = "migrations"

[vars]

```

**Comment by rozenmd** [comment]
Hey @imconnorngl,

Sorry about this - you should be able to access a fix if you install `wrangler@beta`, otherwise it'll be available in the next wrangler release.
