### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by danfernand** [cloudflare/workers-sdk#3051]
### Which Cloudflare product(s) does this pertain to?

Workers/Other

### What version of `Wrangler` are you using?

2.14.0

### What operating system are you using?

Mac

### Describe the Bug

Testing a worker out and `resp.url` does not return full url

In the worker
```
return new Response(null, {
      status: 301,
      headers: {
        location: 'http://someurl.com#somehash=thehash',
        "Cache-Control": "no-cache",
      },
});
```

In the test
```
 describe("Worker", () => {
  let worker: UnstableDevWorker;

  beforeAll(async () => {
    worker = await unstable_dev("src/index.ts", {
      experimental: {
        disableExperimentalWarning: true,
      },
      local: true,
      vars: {
        JWT_PRIVATE_KEY: "somekey",
      },
    });
  });

  afterAll(async () => {
    await worker.stop();
  });

  it("resp.url should be http://someurl.com#somehash=thehash", async () => {
    const resp = await worker.fetch();
    expect(resp.redirected).toEqual(true);
    expect(resp.url).toEqual("http://someurl.com#somehash=thehash");
  })
})
```

Test result
```
  - Expected   "http://ww12.someurl.com#somehash=thehash"
  + Received   "http://ww12.someurl.com/"
```

**Comment by JacobMGEvans** [comment]
Thanks for the bug report! We have a potential fix for this in [2.15.0 ](https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%402.15.0) in PR #2957 

If you still have issues after upgrading please feel free to reopen the issue 😄

**Comment by danfernand** [comment]
Thank you!

**Comment by danfernand** [comment]
I upgraded and im still not seeing the hash come in tests

https://cloudflareworkers.com/?_ga=2.255294668.55185524.1682455680-1282279078.1679676857#e74480c019427872f200b219447e7cb1:about:blank

This is what we are doing and works correctly, but in testing the worker we are not seeing the hash

**Comment by danfernand** [comment]
@JacobMGEvans ^
