### ISSUE TITLE
🐛 BUG: `--service` options missing in `wrangler pages dev`

### ISSUE THREAD

**Issue by stenet** [cloudflare/workers-sdk#3053]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.15.1

### What operating system are you using?

Mac

### Describe the Bug

The documentation https://developers.cloudflare.com/pages/platform/functions/bindings/#interact-with-your-service-binding-locally tells to interact with a service you have to use the `--service` option in `wrangler pages dev`:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/1838511/232326515-6e115308-d698-4a14-acbb-cc0a4ffe2b52.png">

This option does not exist:

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/1838511/232326544-478a8fec-31aa-4ccf-9f0a-0a9a00daf637.png">

**Comment by CarmenPopoviciu** [comment]
we have a WIP PR that addresses this issue. You can follow the progress over here: https://github.com/cloudflare/workers-sdk/pull/2162
