### ISSUE TITLE
🐛 BUG: Pages publish suggests wrangler.toml when ran headless with no account ID

### ISSUE THREAD

**Issue by Erisa** [cloudflare/workers-sdk#3061]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.16.0

### What operating system are you using?

Mac

### Describe the Bug

When `wrangler pages publish` is run in a non-interactive environment without a `CLOUDFLARE_ACCOUNT_ID` and multiple accounts scoped to the token, it returns the following error

```sh
$ npx wrangler pages publish dist --project-name erisatest | cat

✘ [ERROR] More than one account available but unable to select one in non-interactive mode.

  Please set the appropriate `account_id` in your `wrangler.toml` file.
  Available accounts are (`<name>`: `<account_id>`):
    `Erisa A - Employee`: `2d0d216f0f48937d2a261c5af101afd7`
    `Erisa A`: `ece1d09b06af2ced51407c97505ea0cc`


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
```

In the example, `| cat` is used to make the environment non-interactive.

Since Pages does not support `wrangler.toml`, adding one does nothing.
If one gets confused and tries to force use of one with `--config wrangler.toml`, they receive the following:

```sh
$ npx wrangler pages publish dist --project-name erisatest --config wrangler.toml | cat

✘ [ERROR] Pages does not support wrangler.toml


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
```

Ideally the first error would recognise Pages is being used and say to use `CLOUDFLARE_ACCOUNT_ID` instead.

**Comment by ItsWendell** [comment]
@Erisa Are there any workarounds for this?

**Comment by Erisa** [comment]
@ItsWendell, setting `CLOUDFLARE_ACCOUNT_ID ` as an environment variable containing your intended account ID makes it go away.
For example in the above if I wanted to use my employee account I would do `export CLOUDFLARE_ACCOUNT_ID=2d0d216f0f48937d2a261c5af101afd7`

**Comment by ItsWendell** [comment]
@Erisa  Thanks for your quick response! I thought this was part of the issue but indeed, I made a small mistake in my Github Action trying to access secrets instead of variables, got it working now, thanks!

**Comment by dave-swift** [comment]
Additionally, the documentation suggests you can use toml file for Pages at https://developers.cloudflare.com/workers/wrangler/commands/#:~:text=Flags%3A-,%2D%2Dconfig,-string

> The following global flags work on every command.
> 
> Flags:
> 
> `--config` string
> Path to `.toml` configuration file.

**Comment by Erisa** [comment]
Hey @CarmenPopoviciu, it's fine now that Pages has wrangler.toml. Thanks!

**Comment by CarmenPopoviciu** [comment]
much awesomeness!
