### ISSUE TITLE
Error trying to run workers with KV locally

### ISSUE THREAD

**Issue by faizanbashir** [cloudflare/workers-sdk#3062]
I am getting an error when I am trying to run a worker locally.

My `wrangler.toml`:

```toml
name = "darthheck"
account_id = ""

# Configure the Workers KV binding
kv_namespaces = [
  { binding = "test_subscription", preview_id = "<kv_preview_id>" }
]

# Configure the workers.dev deployment
workers_dev = true

compatibility_date = "2023-04-18"
```

I am getting the following error when I try to run the `wrangler dev index.js --experimental-local`:

```shell
 ⛅️ wrangler 2.16.0
--------------------

✘ [ERROR] Processing wrangler.toml configuration:

    - "kv_namespaces[0]" bindings should have a string "id" field but got
  {"binding":"test_subscription","preview_id":"ad82640fad0d4dea8f9464d35e3eb681"}.


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
```

Initially I was using the KV ID of the one created on cloudflare dashboard:

```shell
{"binding":"test_subscription","id":"ad82640fad0d4dea8f9464d35e3eb681"}
```

When I tried to run it using the same command dev command I got the below error:

```shell
 ⛅️ wrangler 2.16.0
--------------------

✘ [ERROR] In development, you should use a separate kv namespace than the one you'd use in production. Please create a new kv namespace with "wrangler kv:namespace create <name> --preview" and add its id as preview_id to the kv_namespace "test_subscription" in your wrangler.toml


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
```

**Comment by faizanbashir** [comment]
Can anyone help with this?

**Comment by faizanbashir** [comment]
Does anyone from @cloudflare care to answer this?

**Comment by admah** [comment]
@faizanbashir sorry for the delayed response on this. Your code is missing an `ID` for the prod KV namespace, and that is required. 

It should look like: 

`kv_namespaces = [
  { binding = "test_subscription", id = "<kv_prod_id>", preview_id = "<kv_preview_id>" }
]`

Let me know if that works, and I can close this issue out. Thanks.

**Comment by faizanbashir** [comment]
This certainly helps. Thank you!
