### ISSUE TITLE
🚀 Feature Request: configurable functions directory for `wrangler pages dev`

### ISSUE THREAD

**Issue by yw662** [cloudflare/workers-sdk#3064]
### Describe the solution

Currently `wrangler pages dev` would hard code functions directory as `./functions`:
https://github.com/cloudflare/workers-sdk/blob/89d78c0ac444885298ac052b0b3de23b69fb029b/packages/wrangler/src/pages/dev.ts#L268

It could be made configurable like `wrangler pages dev --functions=./path/to/functions` or in a config file if there would be one. It can be helpful for a monorepo with more than one functions directory.

It should be mentioned that "**we shouldn't do this until Pages allows this to be configured via Dash as well, because otherwise the Pages CI/CD flow would not support projects with custom functions directory.**"

**Comment by CarmenPopoviciu** [comment]
hi @yw662, thank you for requesting this feature.

I am not entirely sure this is something we would like to support in the near future, but I will bring it up with the team, and update here once we have reached a decision

<3

**Comment by petebacondarwin** [comment]
Hi @yw662 - while this would add some flexibility to the `wrangler dev` command, it requires a lot of extra configuration support across the CI build pipeline and the dashboard. So we do not intend to add this functionality.
