### ISSUE TITLE
🐛 BUG: Not enough arguments following: compatibility-flags (Pages/Functions)

### ISSUE THREAD

**Issue by v0l** [cloudflare/workers-sdk#3066]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

?

### What operating system are you using?

Mac

### Describe the Bug

CF Pages build all failing since 1hr ago with the following error:

```
22:40:00.304 | Found Functions directory at /functions. Uploading.
22:40:01.051 | ✘ [ERROR] Not enough arguments following: compatibility-flags
```

I do not use any `wrangler.toml` and have just 2 functions in my Pages app.

Env:
`NODE_VERSION=16`

**Comment by WalshyDev** [comment]
Hey,

This was an issue our side which we rolled back last night. Apologies for the issue!
