### ISSUE TITLE
🐛 BUG: Unable to delete Wrangler secrets with "@" in the key name

### ISSUE THREAD

**Issue by robotson** [cloudflare/workers-sdk#3069]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.15.1

### What operating system are you using?

macOS 13.3.1

### Unable to delete Wrangler secrets with certain characters, specifically "@" in the name.

(I accidentally used wrangler to put a secret with an "@" character in the key name)

Steps to Reproduce:

1. Create a Wrangler secret with a name containing the '@' symbol
2. Attempt to delete the secret using the wrangler secret delete command or the web interface
3. Observe that the command fails with an error message

When attempting to delete a secret with a name containing the '@' symbol in wrangler CLI, the command fails and generates the error message "Cannot read properties of undefined (reading 'map')".

Additionally, attempting to remove the binding for the secret from the web interface also generates an error, with the message "workers.api.error.binding_not_found (Code: 10056)".

**Comment by lrapoport-cf** [comment]
hi @robotson  :) thanks for flagging this. in an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and any additional context and we will review. thank you!
