### ISSUE TITLE
🐛 BUG: D1 prepared statement can't bind boolean

### ISSUE THREAD

**Issue by andrewmd5** [cloudflare/workers-sdk#3070]
### Which Cloudflare product(s) does this pertain to?

D1

### What version of `Wrangler` are you using?

 2.16.0

### What operating system are you using?

Mac

### Describe the Bug

I have a simple table:
```sql
CREATE TABLE users (
    id CHAR(32) PRIMARY KEY,
    username VARCHAR(32) NOT NULL,
    discriminator CHAR(4) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password CHAR(72) NOT NULL,
    verified BOOLEAN,
    flags TINYINT,
    created_at DATETIME,
    UNIQUE (email),
    CONSTRAINT user_discriminator UNIQUE (username, discriminator)
);
```

When I attempt bind a prepared statement using the following object:
```typescript
const data = {
            id: crypto.randomUUID().replaceAll('-', ''),
            password: data.passwordHash,
            username: data.username,
            discriminator: data.discriminator,
            email: data.email,
            verified: false,
            flags: 0,
            created_at: 'CURRENT_TIMESTAMP'
   };
```

I receive an error that:
```
message: Type 'boolean' not supported for value 'false'
```

I can fix this by by modifying the beta facade to break on boolean types just as it does for strings and numbers and the data inserts successfully.
```javascript
	bind(...values) {
		for (var r in values) {
			switch (typeof values[r]) {
				case "boolean":
				case "number":
				case "string":
```

**Comment by Mecanik** [comment]
So what is the solution for this?

**Comment by FlareLine** [comment]
Hey @andrewmd5 - just checking in with this one, have you submitted a PR for review for this bug yet? 😁

**Comment by geelen** [comment]
My apologies, small fixes like this were a bit difficult for us to ship easily in the past, but I'm pleased to say we've resolved a lot of that friction. So, this should be fixed when this PR is merged & released: https://github.com/cloudflare/workerd/pull/1677
