### ISSUE TITLE
🐛 BUG: `wrangler dev` not working at high traffic time

### ISSUE THREAD

**Issue by chientrm** [cloudflare/workers-sdk#3071]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.16.0

### What operating system are you using?

Linux

### Describe the Bug

Only happens at high traffic time.

<img width="609" alt="Screen Shot 2023-04-19 at 12 50 35 PM" src="https://user-images.githubusercontent.com/70304839/232978811-c1ce76f5-fd2a-463e-9104-ece32584e865.png">

**Comment by penalosa** [comment]
Thanks for reporting this! Could you provide some more reproduction information (the level of traffic you were receiving, primarily)

**Comment by penalosa** [comment]
We haven't heard from you in a while, so I'm going to close this issue for now. If you're still running into issues feel free to comment with more details and we can investigate further
