### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by sreekotay** [cloudflare/workers-sdk#3077]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.16.0

### What operating system are you using?

Windows

### Describe the Bug

Unable to user wrangler publish or npm start:

publish:
X [ERROR] A request to the Cloudflare API (/accounts/9129abde1bf290f32a4d3164182baa4a/workers/scripts/flareproxy) failed.

  workers.api.error.internal_server [code: 10002]
  
 start:
X [ERROR] Error on remote worker: ParseError: A request to the Cloudflare API (/accounts/9129abde1bf290f32a4d3164182baa4a/workers/scripts/flareproxy/edge-preview) failed.

      at throwFetchError (C:\code\flareproxy\node_modules\wrangler\wrangler-dist\cli.js:129668:17)
      at fetchResult (C:\code\flareproxy\node_modules\wrangler\wrangler-dist\cli.js:129635:5)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async createPreviewToken
  (C:\code\flareproxy\node_modules\wrangler\wrangler-dist\cli.js:131756:29)
      at async createWorkerPreview
  (C:\code\flareproxy\node_modules\wrangler\wrangler-dist\cli.js:131777:17)
      at async start (C:\code\flareproxy\node_modules\wrangler\wrangler-dist\cli.js:134349:34) {
    text: 'A request to the Cloudflare API
  (/accounts/9129abde1bf290f32a4d3164182baa4a/workers/scripts/flareproxy/edge-preview) failed.',
    notes: [ { text: 'workers.api.error.internal_server [code: 10002]' } ],
    location: undefined,
    kind: 'error',
    code: 10002
  }

**Comment by zbauman3** [comment]
Bumping this as I'm seeing the same issue

**Comment by dotysan** [comment]
Does `wrangler dev --local` work where `wrangler dev` doesn't? If so, prolly same as #3097.

**Comment by zbauman3** [comment]
Update: It ended up being duplicate entries in my `wrangler.toml`.
