### ISSUE TITLE
🐛 BUG: Wrangler does not find files in symlinked folders

### ISSUE THREAD

**Issue by calebmer** [cloudflare/workers-sdk#3094]
### Which Cloudflare product(s) does this pertain to?

Pages, Workers/Other

### What version of `Wrangler` are you using?

2.17.0

### What operating system are you using?

Mac

### Describe the Bug

Cloudflare sites does not upload files within a symlinked directory. Instead it crashes since it tries to interpret the directory as a file. The code even has a TODO comment where this bug needs to be fixed:

https://github.com/cloudflare/workers-sdk/blob/6f5259f73e7a93258524786f817ca1186ae06bd4/packages/wrangler/src/sites.ts#L24-L42

I wrote a patch for this I’ve been upgrading with wrangler since 2.4.4. It would be nice if it were incorporated upstream!

My wrangler 2.4.4 patch I’m currently upgrading to 2.17.0:

```patch
diff --git a/src/sites.tsx b/src/sites.tsx
index b690e7d10911f594ae0ed9785972ebe3e2bdfa6a..823db9e76615016675ee90753ed976649a924032 100644
--- a/src/sites.tsx
+++ b/src/sites.tsx
@@ -32,11 +32,12 @@ async function* getFilesInFolder(dirPath: string): AsyncIterable<string> {
 		if (file.name.startsWith(".") && !HIDDEN_FILES_TO_INCLUDE.has(file.name)) {
 			continue;
 		}
-		// TODO: follow symlinks??
-		if (file.isDirectory()) {
-			yield* await getFilesInFolder(path.join(dirPath, file.name));
+		// NOTE(calebmer): Support directory symlinks.
+		const filePath = path.join(dirPath, file.name);
+		if (file.isDirectory() || (file.isSymbolicLink() && (await stat(filePath)).isDirectory())) {
+			yield* await getFilesInFolder(filePath);
 		} else {
-			yield path.join(dirPath, file.name);
+			yield filePath;
 		}
 	}
 }
diff --git a/wrangler-dist/cli.js b/wrangler-dist/cli.js
index f5bba9b37756b24e5de7810daf2e860beac3ae9a..c63203f23925475e8b07f2987c3b576f3cafd155 100644
--- a/wrangler-dist/cli.js
+++ b/wrangler-dist/cli.js
@@ -145211,10 +145211,12 @@ async function* getFilesInFolder(dirPath) {
     if (file.name.startsWith(".") && !HIDDEN_FILES_TO_INCLUDE.has(file.name)) {
       continue;
     }
-    if (file.isDirectory()) {
-      yield* await getFilesInFolder(path16.join(dirPath, file.name));
+    // NOTE(calebmer): Support directory symlinks.
+    const filePath = path16.join(dirPath, file.name);
+    if (file.isDirectory() || (file.isSymbolicLink() && (await (0, import_promises4.stat)(filePath)).isDirectory())) {
+      yield* await getFilesInFolder(filePath);
     } else {
-      yield path16.join(dirPath, file.name);
+      yield filePath;
     }
   }
 }
```

**Comment by jspspike** [comment]
Hello @calebmer! Would you be able to add your changes as a PR? That way we can review and merge your changes in directly

**Comment by lrapoport-cf** [comment]
hi @calebmer :) thanks for flagging this. in an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. if this is still a problem, please feel free to open a new issue referencing this one. or if you're able to put up a PR we'll be happy to review! thanks!
