### ISSUE TITLE
🐛 BUG: Could not resolve node "http2" while running wrangler dev in node_compat = true mode

### ISSUE THREAD

**Issue by noahmcgillmr** [cloudflare/workers-sdk#3101]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.17.0

### What operating system are you using?

Mac

### Describe the Bug

The application running on my worker is using the [googleapis](https://www.npmjs.com/package/googleapis) library to interact with the Google Sheets API. This library uses the build-in node package **http2**. 

In wrangler.toml, I have `node_compat = true` set. This seems to be polyfilling most node libraries as expected, except for http2. When I run `wrangler dev`, I get the following error:

```
✘ [ERROR] Could not resolve "http2"

    node_modules/googleapis-common/build/src/http2.js:16:22:
      16 │ const http2 = require("http2");
         │                       ~~~~~~~
         ╵                       "./http2"

  The package "http2" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.


✘ [ERROR] Build failed with 1 error:

  node_modules/googleapis-common/build/src/http2.js:16:22: ERROR: Could not resolve "http2"
```

I'm running on MacOS arm with node v20.0.0 installed.

**Comment by KianNH** [comment]
`node_compat = true` is just some best-effort polyfills which doesn't include `http2` - https://github.com/ionic-team/rollup-plugin-node-polyfills/

You'd need to find another polyfill, or swap out the library for one that leverages the Fetch Web API used by browsers/serverless runtimes.

**Comment by noahmcgillmr** [comment]
@KianNH I see. Closing this issue. Thank you!
