### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by maclainjohnson** [cloudflare/workers-sdk#3102]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.17.0

### What operating system are you using?

Mac

### Describe the Bug

I am trying to use a Cloudflare Worker to build a function that makes API calls to OpenAI.

I followed the instructions here to set up my Worker: https://developers.cloudflare.com/workers/get-started/guide/

and I have my function wrapped in a handler in my index.js file.

When I run `wrangler publish` it gives me this error:

`Uncaught ReferenceError: process is not defined
    at index.js:2625:11
   [code: 10021]`

How can I fix this?

**Comment by penalosa** [comment]
Thanks for reporting this! Unlike in NodeJS, the `process` global is not defined in the Cloudflare Workers runtime, which is based on [web standards](https://developers.cloudflare.com/workers/runtime-apis/web-standards/). The [Cloudflare Developers Discord](https://discord.cloudflare.com) is a great place to ask questions around general Workers development, and they should be able to point you in the right direction (in this case, it's likely that one of your dependencies isn't supported in the Cloudflare Workers runtime environment)
