### ISSUE TITLE
🐛 BUG:  WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

### ISSUE THREAD

**Issue by delivrjs** [cloudflare/workers-sdk#3103]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.17.0

### What operating system are you using?

Mac

### Describe the Bug

WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

**Comment by penalosa** [comment]
I'm not sure what the issue being reported is here, so I'm going to close it for now. If you're still running into issues feel free to comment with more details and we can investigate further!
