### ISSUE TITLE
🐛 BUG: error for running --experimental-local-remote-kv without --persist is confusing

### ISSUE THREAD

**Issue by obfuscatedgenerated** [cloudflare/workers-sdk#3112]
### Which Cloudflare product(s) does this pertain to?

KV, Wrangler

### What version of `Wrangler` are you using?

2.17.0

### What operating system are you using?

Windows 10

### Describe the Bug

When running a development server locally with experimental and remote KV, the server errors and doesn't listen for requests. This problem seems to happen just after installing @miniflare/tre but is not resolved by installing it manually.

I'm using nodejs_compat.

## Command
`wrangler dev --experimental-local --experimental-local-remote-kv`

## Log
```
⛅️ wrangler 2.17.0 
--------------------
Using vars defined in .dev.vars
Your worker has access to the following bindings:
- KV Namespaces:
  - FORMS: *****
  - TIMEOUTS: *****
  - LINKS: *****
- Vars:
  - FROM_ADDRESS: "(hidden)"
  - MAILGUN_API_KEY: "(hidden)"
  - MAILGUN_API_BASE_URL: "(hidden)"
  - SECRET_SIGNATURE: "(hidden)"
  - STORAGE_IMPLEMENTATION: "(hidden)"
X [ERROR] local worker: AssertionError [ERR_ASSERTION]: false == true

      at transformMf2OptionsToMf3Options
  (***\node_modules\wrangler\wrangler-dist\cli.js:132242:37)
      at async startLocalWorker
  (***\node_modules\wrangler\wrangler-dist\cli.js:131757:28)
  {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: false,
    expected: true,
    operator: '=='
  }
```

**Comment by obfuscatedgenerated** [comment]
This is solved by passing `--persist` at the same time. Looking at the assertion that is failing, this is intentional behaviour. This isn't documented anywhere I could find and there is no indication in the command help screen. This error message could be more explanatory than `false == true`. I'm renaming this issue accordingly.

**Comment by penalosa** [comment]
The `--experimental-local-remote-kv` flag was [removed in Wrangler `v3`](https://github.com/cloudflare/workers-sdk/pull/3224), so I'm going to close this issue for now.
