### ISSUE TITLE
🐛 BUG: wrangler publish will error out if using pdf.js

### ISSUE THREAD

**Issue by ivarec** [cloudflare/workers-sdk#3113]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.17.0

### What operating system are you using?

Windows

### Describe the Bug

If I try to use `pdf.js` in a Cloudflare Worker, `wrangler publish` fails with the following stack trace:

```
⛅️ wrangler 2.17.0 
--------------------
Your worker has access to the following bindings:
- R2 Buckets:
  - FOO_FILES: foo_files
Total Upload: 679.03 KiB / gzip: 107.38 KiB

X [ERROR] A request to the Cloudflare API (/accounts/***/workers/scripts/foobar) failed.

  Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at index.js:628:45 in get platform
    at index.js:3337:40 in KeyboardManager
    at index.js:3441:41 in <static_initializer>
    at index.js:3410:35 in Object.defineProperty.value
    at index.js:15532:40 in __w_pdfjs_require__
    at index.js:2903:26 in Object.defineProperty.value
    at index.js:15532:40 in __w_pdfjs_require__
    at index.js:2770:27 in Object.defineProperty.value
    at index.js:15532:40 in __w_pdfjs_require__
    at index.js:882:39 in Object.defineProperty.value
   [code: 10021]


  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

I can easily reproduce it with the following minimal code (after installing `pdf-dist` from npm):

```js
import * as pdfjsLib from 'pdfjs-dist'

export default {
  async fetch (request, env, ctx) {
    return new Response()
  }
}
```

**Comment by gdoteof** [comment]
also running into this, and see one here: https://community.cloudflare.com/t/pdfjs-dist-npm-package-not-working/483435

**Comment by penalosa** [comment]
Thanks for reporting this! It doesn't look like the `pdf.js` library is supported in the [Cloudflare Workers environment.](https://developers.cloudflare.com/workers/runtime-apis/web-standards/) Going forward, the Workers runtime is working on adding support for [more Node.JS builtins](https://developers.cloudflare.com/workers/runtime-apis/nodejs/), which should improve library compatibility.

**Comment by wuservices** [comment]
There's now https://github.com/unjs/unpdf, which should work with Workers (with a few limitations)

**Comment by Soviut** [comment]
For posterity, I was able to get this wrapped version of pdfjs to work. https://github.com/johannschopplich/pdfjs-serverless
