### ISSUE TITLE
🐛 BUG: testing a worker's url does not return hash in the url

### ISSUE THREAD

**Issue by danfernand** [cloudflare/workers-sdk#3115]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.17.0

### What operating system are you using?

Mac, Linux (CI)

### Describe the Bug

Testing a worker out and `resp.url` does not return full url

In the worker
```
return new Response(null, {
      status: 301,
      headers: {
        location: 'http://someurl.com#somehash=thehash',
        "Cache-Control": "no-cache",
      },
});
```

In the test
```
 describe("Worker", () => {
  let worker: UnstableDevWorker;

  beforeAll(async () => {
    worker = await unstable_dev("src/index.ts", {
      experimental: {
        disableExperimentalWarning: true,
      },
      local: true,
      vars: {
        JWT_PRIVATE_KEY: "somekey",
      },
    });
  });

  afterAll(async () => {
    await worker.stop();
  });

  it("resp.url should be http://someurl.com#somehash=thehash", async () => {
    const resp = await worker.fetch();
    expect(resp.redirected).toEqual(true);
    expect(resp.url).toEqual("http://someurl.com#somehash=thehash");
  })
})
```

Test result
```
  - Expected   "http://ww12.someurl.com#somehash=thehash"
  + Received   "http://ww12.someurl.com/"
```

The original issue is closed without a resolution - https://github.com/cloudflare/workers-sdk/issues/3051

**Comment by 1000hz** [comment]
This behavior is in line with the Fetch Standard. [`Response.url` doesn't include include hash fragments.](https://fetch.spec.whatwg.org/#dom-response-url:~:text=URL%2C%20serialized-,with%20exclude%20fragment%20set%20to%20true,-.)

You can, however, write your test such that the request is made in manual-redirect mode and assert against the resulting `Location` header:

```tsx
it("response location header should be http://someurl.com#somehash=thehash", async () => {
  const resp = await worker.fetch('/', {redirect: 'manual'});
  expect(resp.status).toEqual(301);
  expect(resp.headers.get('location')).toEqual("http://someurl.com#somehash=thehash");
})
```

**Comment by nosovk** [comment]
ok, is there some workaround to get url hash in cloudlfare worker?
