### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by zzeee** [cloudflare/workers-sdk#3129]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.12.2

### What operating system are you using?

Mac

### Describe the Bug

After 3 months of successful publishing, today 
when I am doing wrangler publish
I see 
✘ [ERROR] TypeError: fetch failed

      at fetch
  (/Users/andrey/.config/yarn/global/node_modules/wrangler/wrangler-dist/cli.js:16584:17)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at runNextTicks (node:internal/process/task_queues:64:3)
      at process.processImmediate (node:internal/timers:442:9)
      at async performApiFetch
  (/Users/andrey/.config/yarn/global/node_modules/wrangler/wrangler-dist/cli.js:130525:10)
      at async fetchInternal
  (/Users/andrey/.config/yarn/global/node_modules/wrangler/wrangler-dist/cli.js:130535:20)
      at async fetchResult
  (/Users/andrey/.config/yarn/global/node_modules/wrangler/wrangler-dist/cli.js:129671:16)
      at async publish
  (/Users/andrey/.config/yarn/global/node_modules/wrangler/wrangler-dist/cli.js:133650:31)
      at async Object.publishHandler [as handler]
  (/Users/andrey/.config/yarn/global/node_modules/wrangler/wrangler-dist/cli.js:149610:3) {
    cause: ConnectTimeoutError: Connect Timeout Error
        at onConnectTimeout
  (/Users/andrey/.config/yarn/global/node_modules/wrangler/wrangler-dist/cli.js:7185:29)
        at /Users/andrey/.config/yarn/global/node_modules/wrangler/wrangler-dist/cli.js:7141:51
        at Immediate._onImmediate
  (/Users/andrey/.config/yarn/global/node_modules/wrangler/wrangler-dist/cli.js:7173:13)
        at process.processImmediate (node:internal/timers:471:21) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }

When I do wrangler tail (of of my workers name)
I see ✘ [ERROR] fetch failed

**Comment by rozenmd** [comment]
@JacobMGEvans this sounds related to https://github.com/cloudflare/workers-sdk/issues/3121 ?

**Comment by penalosa** [comment]
We haven't heard from you in a while, so I'm going to close this issue for now. If you're still running into issues feel free to comment with more details and we can investigate further!
