### ISSUE TITLE
🐛 BUG: Worker Type Detection Malfunction

### ISSUE THREAD

**Issue by helloimalastair** [cloudflare/workers-sdk#3145]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.19.0

### What operating system are you using?

MacOS Ventura 13.3.1 (a) (22E772610a)

### Describe the Bug

Creating a new project that only exports a DO class causes `wrangler` to assume the project is *Service Worker Syntax*:
> ▲ [WARNING] The entrypoint `src/index.ts` has exports like an ES Module, but hasn't defined a default export like a module worker normally would. Building the worker using "service-worker" format...

This causes the upload to fail, since a *Service Worker* cannot declare a Durable Object. This error can be bypassed by providing an
```ts
export default {};
```

The `export default` was omitted in an effort to reduce friction in deploying DOs for use with Pages Functions, but having to deploy code for the Worker itself, even if minuscule, may present extra difficulty to those who do not wish to actually use Workers.

**Comment by penalosa** [comment]
Thanks for reporting this! Unfortunately there's currently no way to deploy a Durable Object without also deploying a Worker alongside it, and so I'm going to close this for now. In the future, the convergence of Pages and Workers should make defining durable objects for use in Pages Functions easier.
