### ISSUE TITLE
🐛 BUG: `wrangler pages dev` doesn't provide a user-friendly error message on node imports

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/workers-sdk#3147]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.19.0

### What operating system are you using?

Mac

### Describe the Bug

Run `wrangler pages dev` on a pages project which imports from a standard nodejs module without specifying the `nodejs_compat` flag generates a non user friendly error:
![Screenshot 2023-05-04 at 23 26 29](https://user-images.githubusercontent.com/61631103/236348749-450af599-e001-4737-9a05-0de70378ed22.png)

Compared to what we get for example with `wrangler pages functions build` or `wrangler pages publish`:
![Screenshot 2023-05-04 at 23 32 51](https://user-images.githubusercontent.com/61631103/236349137-0e2ac9d3-6f45-40b0-8f69-79268235b0f2.png)

This error message should be aligned and made user friendly like the other ones.

___

> **Note**: I've tested which with `wrangler pages dev` I am not sure `wrangler dev` might have the same issue

___

([original discussion](https://github.com/cloudflare/workers-sdk/pull/3133#issuecomment-1535507484))

**Comment by CarmenPopoviciu** [comment]
hi @dario-piotrowicz ,

I have tested this in latest wrangler `v 3.52.0` and this is what I'm seeing:

<img width="829" alt="Screenshot 2024-04-25 at 15 09 47" src="https://github.com/cloudflare/workers-sdk/assets/4638332/fcdd6c98-92bd-4162-8ef0-f3f187adc599">

<img width="1111" alt="Screenshot 2024-04-25 at 15 12 50" src="https://github.com/cloudflare/workers-sdk/assets/4638332/5ea247df-1794-4e02-bb71-f17b9532f115">

Are the above warning/error messages what you'd expect? Or what is the expected messaging you were hoping to see/find useful?

**Comment by dario-piotrowicz** [comment]
@CarmenPopoviciu yeah that looks much better, you get that with `wrangler pages dev` right?

**Comment by CarmenPopoviciu** [comment]
@dario-piotrowicz yes, that is correct. If you are happy with that error message, are we good to close this out?

**Comment by dario-piotrowicz** [comment]
Yes, let's close the issue then 🙂 

Thanks a bunch 🙏
