### ISSUE TITLE
🚀 Improvement: create an esbuild plugin that can differentiate between pages and workers

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/workers-sdk#3155]
### Describe the solution

An esbuild pluging should be added that differentiates between Pages and workers.

Such plugin should be injected and used in the worker building process without it having to be aware of the source.

So that we can avoid the use of flags such as:
https://github.com/cloudflare/workers-sdk/blob/d078800804899c3c8e083260f8cfdfc0397d6110/packages/wrangler/src/pages/functions/buildWorker.ts#L156

___

([original discussion](https://github.com/cloudflare/workers-sdk/pull/3133#pullrequestreview-1414972261))

**Comment by penalosa** [comment]
This was done at some point—we no longer use `forPages`
