### ISSUE TITLE
Bug: `wrangler d1 execute` returns D1_ERROR

### ISSUE THREAD

**Issue by penguingl** [cloudflare/workers-sdk#3159]
### Which Cloudflare product(s) does this pertain to?

D1, Wrangler

### What version of `Wrangler` are you using?

2.19.0

### What operating system are you using?

Mac

### Describe the Bug

Hello, when I run `wrangler d1 execute database --local --file=./schema.sql` I get an error:
```
🌀 Mapping SQL input into an array of statements
🌀 Loading DB at .wrangler/state/d1/DB.sqlite3
[NPXI] better-sqlite3 not available locally. Attempting to use npx to install temporarily.
[NPXI] Installing... (npx --prefer-offline -y -p better-sqlite3@8.0.1)
[NPXI] Installed into /Users/user/.npm/_npx/7d0049dadb8d11c4/node_modules.
[NPXI] To skip this step in future, run: npm install --save-dev better-sqlite3@8.0.1

✘ [ERROR] D1_ERROR


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
```
There is no additional information. Do you have any idea what the problem could be?

**Comment by JacobMGEvans** [comment]
👋🏻 Greetings,
I appreciate the report. This is the repo and issues for Wrangler (Cloudflare Worker CLI) Pages, & Other SDK tooling, this seems D1 specific.

Feel free to check out the Cloudflare Discord where there is a channel for D1 as well: https://discord.com/invite/cloudflaredev

To report issues related to D1 specifically:
https://community.cloudflare.com/c/developers/d1/85/l/latest

Cc: @nevikashah @rozenmd

**Comment by rozenmd** [comment]
Hey @penguingl, are you able to share the schema to help debug?

**Comment by penguingl** [comment]
Hello, I figured out what the problem was, I used double quotes instead of single quotes
```
DROP TABLE IF EXISTS Users;
CREATE TABLE Users (UserID INT, Username TEXT, PRIMARY KEY (`UserID`));
INSERT INTO Users (UserID, Username) VALUES (1, "test_user");
```
The error occurs only if you use the --local option if I'm not using a local database then command is executed without errors.

Also this error occurs when I use a comment in the schema file after queries
```
DROP TABLE IF EXISTS Users;
CREATE TABLE Users (UserID INT, Username TEXT, PRIMARY KEY (`UserID`));
INSERT INTO Users (UserID, Username) VALUES (1, 'test_user');

-- some comment
```
The error also occurs only when using the --local option.

I'm not very good at SQL, but if it works with a remote database, should it also work with a local database? Or it can give more detailed information in the error instead of [ERROR] D1_ERROR.

**Comment by rozenmd** [comment]
Wrangler now outputs the full error message:
```
 NO_D1_WARNING=true && npx wrangler d1 execute d1_init --file ./migrations/0000_test.sql

🌀 Mapping SQL input into an array of statements
🌀 Parsing 1 statements
🌀 Executing on d1_init (fe780a68-xxxx-xxxx-xxxx-406cf5b72a30):

✘ [ERROR] A request to the Cloudflare API (/accounts/xxxxx/d1/database/fe780a68-xxxx-xxxx-xxxx-406cf5b72a30/query) failed.

  ERROR 9009: SQL prepare error: no such table: doesnt_exist [code: 7500]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

Consider upgrading to either `wrangler@beta` or `wrangler@3.0.1`

**Comment by fl4viooliveira** [comment]
In my case, It started work after I removed all comments.

``` SQL
DROP TABLE IF EXISTS Users;
CREATE TABLE IF NOT EXISTS Users (
    UserId INTEGER PRIMARY KEY AUTOINCREMENT,
    UserName TEXT,
    AuthToken TEXT
);

DROP TABLE IF EXISTS GHApps;
CREATE TABLE IF NOT EXISTS GHApps(
    InstallId INTEGER PRIMARY KEY AUTOINCREMENT,
    GHInstallId INTEGER,
    GHInstallCode TEXT,
    UserId INTEGER,
    FOREIGN KEY (UserId) REFERENCES Users(UserId)
);
```
