### ISSUE TITLE
🐛 BUG: Multiple account selection when running in dev mode

### ISSUE THREAD

**Issue by akshaybabloo** [cloudflare/workers-sdk#3161]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.19.0

### What operating system are you using?

Windows

### Describe the Bug

I have multiple accounts linked to my Cloudflare account. Whenever I try to run `wrangler dev --env development`, The URL comes up first and then it waits, but hidden below that there is an account selection that doesn't show up. Example:

First it shows like this

```
$ wrangler dev --env development
 ⛅️ wrangler 2.19.0 
--------------------
Your worker has access to the following bindings:
- KV Namespaces:
  - GOLLAHALLI_KV: <id>
- Vars:
  - ENVIRONMENT: "development"
⬣ Listening at http://0.0.0.0:8787
- http://192.168.75.1:8787
- http://192.168.66.1:8787
- http://172.28.67.214:8787
- http://127.0.0.1:8787
```

Then nothing shows up after this. When I do <kbd>CTRL</kbd>+<kbd>C</kbd>, then this shows up:

```
Select an account from below:
> Akshay Raj Gollahalli
  Kedri.aut@gmail.com's Account
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn on local mode, [c] clear console, [x] to exit                                                                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Done in 1079.23s.
```

I think the account selection and the other selection should be shown first and then the URLs.

**Comment by JacobMGEvans** [comment]
Thank you for reporting this!

**Comment by penalosa** [comment]
This should be resolved by Wrangler 3, which uses local mode by default for `wrangler dev`. I'm going to close this for now, but if you're still running into issues with `wrangler dev --remote` feel free to comment with more details and we can investigate further!
