### ISSUE TITLE
🐛 BUG: `wrangler d1 execute` exception caught in D1 core

### ISSUE THREAD

**Issue by sun816** [cloudflare/workers-sdk#3162]
### Which Cloudflare product(s) does this pertain to?

D1, Wrangler

### What version of `Wrangler` are you using?

2.19.0

### What operating system are you using?

windows 

### Describe the Bug

when import much sql data ,it said will  use multi batchs , and  it works ok at first then errors result is :

🚣 Executed 1 command in 0.04067100025713444ms
🚣 Executed 1 command in 0.0579309999011457ms
🚣 Executed 1 command in 0.047861000057309866ms
🚣 Executed 1 command in 0.04106000019237399ms
🚣 Executed 1 command in 0.0435500000603497ms
🚣 Executed 1 command in 211.47155799996108ms
  INSERT INTO
X [ERROR] A request to the Cloudflare API (/accounts/????) failed.

  Error 9000: exception caught in D1 core. unreachable RuntimeError: unreachable
      at wasm://wasm/00f5753e:wasm-function[4783]:0x31be54
      at wasm://wasm/00f5753e:wasm-function[4836]:0x322be4
      at wasm://wasm/00f5753e:wasm-function[4877]:0x32c7d6
      at wasm://wasm/00f5753e:wasm-function[237]:0x29575
      at wasm://wasm/00f5753e:wasm-function[4973]:0x34351d
      at Object.s2 [as query] (index.js:2418:157)
      at async Sqlite.query (index.js:3205:23)
      at async sqliteQuery (index.js:9409:29)
      at async index.js:9167:22 [code: 7500]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

**Comment by JacobMGEvans** [comment]
👋🏻 Greetings,
I appreciate the report. This is the repo and issues for Wrangler (Cloudflare Worker CLI) Pages, & Other SDK tooling, this seems D1 specific.

Feel free to check out the Cloudflare Discord where there is a channel for D1 as well: https://discord.com/invite/cloudflaredev

To report issues related to D1 specifically:
https://community.cloudflare.com/c/developers/d1/85/l/latest

Cc: @nevikashah @rozenmd

**Comment by rozenmd** [comment]
We shipped a new backend for D1, which should fix this issue - you can read more about it here: https://blog.cloudflare.com/d1-turning-it-up-to-11/
