### ISSUE TITLE
🚀 Feature Request: Allow set KVNamespace id and previewId from env

### ISSUE THREAD

**Issue by anarkrypto** [cloudflare/workers-sdk#3165]
### Describe the solution

Currently we use wrangler.toml or dashboard to bind the kv namespace id and preview_id

```
[[kv_namespaces]]
  binding = "MY_KV"
  preview_id = "xxxxx"
  id = "xxxxx"
```

However, It's not good practice to use private ids in settings files that won't always be private.

For example, in my case I have a public project on Github where all wrangler settings must be public. Devs should just add the secret to their project environment or edit the .dev.vars

I don't think it's feasible to ask them to also edit the wrangler.toml

So I would like a solution to load the kv namespace id and preview id directly from the env.

I didn't find anything similar in the documentation.

**Comment by penalosa** [comment]
In general, we don't consider KV (or D1 etc...) namespace IDs to be private, and so it should be safe to include them in a public GitHub project
