### ISSUE TITLE
🐛 BUG: Can't opt in to Durable Objects

### ISSUE THREAD

**Issue by AAorris** [cloudflare/workers-sdk#3185]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.20.0

### What operating system are you using?

Mac

### Describe the Bug

Repro state:
- Created an account
- Set up "Pay as you go" plan "including monthly usage for durable objects"

Impact:
- There is no tab for durable objects
- The opt-in URL from wrangler takes me to the Workers overview with no durable objects context: https://dash.cloudflare.com/:accountId/workers/overview?enable-durable-objects
- The dashboard has no way of navigating to Durable objects
- The documentation points to "Go to the pricing tab under Workers"
- Setting up a pay as you go plan and running `wrangler login` again doesn't allow me to use Durable Objects

Outcome:
- I can't deploy my first desired project, the workers-chat-demo
- I can't see or use Durable Objects on the dashboard
- I cannot use `wrangler publish` to create scripts using Durable Objects

Discord: https://discord.com/channels/595317990191398933/1106225268873510983

**Comment by admah** [comment]
@AAorris thank you for filing this issue. We are working on a resolution and should have a fix out shortly. I'll be sure to update this thread when that goes out.

**Comment by petebacondarwin** [comment]
An internal fix for this should be rolling out later today once USA is online.

**Comment by admah** [comment]
This fix has been released. Please reopen if you continue to experience this issue.
