### ISSUE TITLE
🐛 BUG: wrangler pages dev shows an error when the proxy is just emitting empty lines

### ISSUE THREAD

**Issue by 205g0** [cloudflare/workers-sdk#3223]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.20

### What operating system are you using?

WSL

### Describe the Bug

When you run, e.g., vite inside wrangler pages dev and vite starts, vite emits a couple of empty lines before anything else (probably just too look good) which leads to: 
![image](https://github.com/cloudflare/workers-sdk/assets/74575852/2125024e-c78d-4104-a0c0-6d808099c677)

if you disable logging in vite (with loglevel silent), this error disappears

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to open a new issue with more details and we can investigate further.
