### ISSUE TITLE
🐛 BUG: The specified bucket name is not valid.(SOLVED)

### ISSUE THREAD

**Issue by RevoltPW** [cloudflare/workers-sdk#3227]
### Which Cloudflare product(s) does this pertain to?

Workers/Other

### What version of `Wrangler` are you using?

2.20.0

### What operating system are you using?

Linux Mint 21.1 x86_64 

### Describe the Bug

when i try to create a bucket using the command `wrangler r2 bucket create preview_bucket_coimages`
get the error: 

  _**The specified bucket name is not valid. [code: 10005]**_

so only names without _ can be used to create a bucket but if i want to use then in the worker i get this new error:

`✘ [ERROR] In development, you should use a separate r2 bucket than the one you'd use in production. Please create a new r2 bucket with "wrangler r2 bucket create <name>" and add its name as preview_bucket_name to the r2_buckets "MY_BUCKET_TEST" in your wrangler.toml`

also in the web interface i cant neither use names that have "_" like preview_bucket_name 

so i cant use the buckets with this issues :(

**Comment by lrapoport-cf** [comment]
@jonesphillip can your team please take a look at this?

**Comment by miguelvictor** [comment]
im having the same error. I tried creating a "separate r2 bucket than the one I would use in production" by running `wrangler r2 bucket create preview_bucket_name` but it still gives me errors.

**Comment by RevoltPW** [comment]
ok that problem was about the wrangler config, 
now i added the r2 to my wrangler.toml like this:
`r2_buckets  = [
  { binding = "MY_BUCKET", bucket_name = "coimages", preview_bucket_name = "previewbucketcoimages"}
]`

and it works, before i was following this tutorial from the [documentation](https://developers.cloudflare.com/r2/api/workers/workers-api-usage/) but the right way to doit is in this part of the [documentation](https://developers.cloudflare.com/workers/wrangler/configuration/#r2-buckets)

**Comment by lrapoport-cf** [comment]
@RevoltPW sounds like the issue is resolved for you :) but there is a discrepancy in documentation that needs to be fixed, is that correct?

@miguelvictor does @RevoltPW 's fix work for you, or are you still experiencing issues?

**Comment by penalosa** [comment]
We haven't heard from you in a while, so I'm going to close this issue for now. If you're still running into issues feel free to comment with more details and we can investigate further

**Comment by pipeu** [comment]
When executing the command:
`wrangler r2 bucket create previewKontato`

I was getting the error: The specified bucket name is not valid. [code: 10005]

After trying some possibilities i discovered that it doesn't work with capital letters or special characters like -.

The same command with lower case letters `wrangler r2 bucket create previewkontato` works fine!
I hope it helps someone else.
