### ISSUE TITLE
🐛 BUG: C3 compatibility date issue

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/workers-sdk#3240]
### Which Cloudflare product(s) does this pertain to?

C3

### What version of `Wrangler` are you using?

2.0.1

### What operating system are you using?

Mac

### Describe the Bug

The generated compatibility-date is invalid. Currently formatted as month-date-year whereas it should be year-month-date (with 0 left padding).

**Comment by engineeringstuff** [comment]
I also get this when running `npm create cloudflare my-first-app` (mentioned in [todays blog](https://blog.cloudflare.com/making-cloudflare-for-web/#the-best-place-for-your-web-applications)) followed by `npm run pages:dev`
