### ISSUE TITLE
🚀 Feature Request: `npm create cloudflare@latest -- --version`

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-sdk#3241]
### Describe the solution

Please add a `--version` flag to output the version of the c3 CLI :)

**Comment by admah** [comment]
This exists now so I'm going to close this out.

![Screenshot 2023-05-19 at 2 47 47 PM](https://github.com/cloudflare/workers-sdk/assets/2184114/8b56890f-7a21-408a-976a-4e1e1c2cb5ac)
