### ISSUE TITLE
🐛 BUG: A request to the Cloudflare API failed while using Wrangler

### ISSUE THREAD

**Issue by heypratik** [cloudflare/workers-sdk#3256]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.20.0

### What operating system are you using?

win32

### Describe the Bug

So I have this very small code - 
```
var shell = require('shelljs');

process.env.CLOUDFLARE_ACCOUNT_ID = '123456';
process.env.CLOUDFLARE_API_TOKEN = 'xxxxxx-xxxxxxxx';

shell.echo('hello world');
shell.exec('npx wrangler pages publish ./cf --project-name=test');

```

Here's the response - 
```
hello world

X [ERROR] A request to the Cloudflare API (/accounts/123456 /pages/projects) failed.

  Could not route to /accounts/123456 /pages/projects, perhaps your object identifier is invalid? [code: 7003]
  No route for that URI [code: 7000]

  If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose

```

As you can see from the response wrangler adds a space after the account id when calling API. I tried different libraries & Nodejs child-process but no help. 

I just want to call my API & have wrangler deploy the files to CF pages. How do I fix this?

**Comment by admah** [comment]
@heypratik thanks for filing an issue. In your example above, you have a space at the end of the env var:

`process.env.CLOUDFLARE_ACCOUNT_ID = '123456 ';`

Can you remove that and try again?

**Comment by heypratik** [comment]
Sorry @admah I added that space when adding the issue here. The space is not in my code & it gives me this issue. I edited the bug above as well.

**Comment by heypratik** [comment]
Can you give me your code? Did you use Sheljs or any other library? Let me know!

**Comment by penalosa** [comment]
@heypratik would you be able to provide a reproduction repo for this issue? I'm also unable to reproduce the space-adding behaviour

**Comment by penalosa** [comment]
We haven't heard from you in a while, so I'm going to close this issue for now. If you're still running into issues feel free to comment with more details and we can investigate further!
