### ISSUE TITLE
🐛 BUG: wrangler d1 execute require a wrangler.toml when ran locally 

### ISSUE THREAD

**Issue by PaganMuffin** [cloudflare/workers-sdk#3316]
### Which Cloudflare product(s) does this pertain to?

D1

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

WSL2 Ubuntu 22.04

### Describe the Bug

Using command ``wrangler d1 execute DB_NAME --local`` require a wrangler.toml file to be present at root level and it results in throwing error ``Can't find a DB with name/binding 'DB' in local config. Check info in wrangler.toml...`` on Pages projects where all binding is done through command eq. ``--d1 DB_NAME`` which will create ``.wrangler/state/v3/d1/DB_NAME/db.sqlite`` after first failed query from binding.

Proposition:
Use DB_NAME from command argument as database id if config not present instead throwing error.

**Comment by ma11hew28** [comment]
### Workaround

To workaround this issue, until it's fixed, you can run your Pages app locally and open a browser to a Pages Function that queries your database, which will create the local database, as @PaganMuffin mentions above. Then you can use the `sqlite3` command to execute SQL statements against the local database.

#### Example

1. Create a Pages project.
2. Create a D1 database.
3. Bind the D1 database to your Pages project with the variable name `DB`.
4. Add this Functions file at `functions/users.js`:

    ```javascript
    export async function onRequest(context) {
      const ps = context.env.DB.prepare('SELECT * from users')
      const data = await ps.first()
      return Response.json(data)
    }
    ```

5. Run the Pages app locally:

    ```shell
    wrangler pages dev public --d1=DB
    ```

6. Go to http://127.0.0.1:8788/users in your browser.
7. Confirm that you get "Error: SqliteError: no such table: users".
8. Add this file at `schema.sql`:

    ```sql
    DROP TABLE IF EXISTS users;
    CREATE TABLE users (id bigserial PRIMARY KEY);
    INSERT INTO users VALUES (1), (2), (3);
    ```

9. Initialize the local database:

    ```shell
    cat schema.sql | sqlite3 .wrangler/state/v3/d1/DB/db.sqlite
    ```

10. Repeat steps 5 and 6 above.

### Related issues

- #3620

**Comment by CarmenPopoviciu** [comment]
hi @PaganMuffin, we recently added `wrangler.toml` [support](https://developers.cloudflare.com/pages/functions/wrangler-configuration/) for Pages projects. Can you please try using a configuration file in your project and let us know if that solved the issue for you 🙏 ?

**Comment by PaganMuffin** [comment]
Hi, I can confirm that this fixed the issue for me.

**Comment by CarmenPopoviciu** [comment]
fantastic! thank you so much for following up!. I'll go ahead and close, but pls feel free to re-open if you experience any more issues <3
