### ISSUE TITLE
🐛 BUG: CTRL +C sometimes doesn't cancel operations with C3

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#3318]
### Which Cloudflare product(s) does this pertain to?

C3

### What version of `Wrangler` are you using?

c3 2.0.7

### What operating system are you using?

Windows 10

### Describe the Bug

- `npm create cloudflare`
- select chatgpt plugin
- when asked to deploy application, hit CTRL + C.

It will deploy anyway.

This also happens when being asked about TypeScript when doing a hello world - hitting CTRL + C just proceeds and doesn't cancel.

**Comment by jculvey** [comment]
This was fixed by https://github.com/cloudflare/workers-sdk/pull/3525 and will be included in `2.0.12`.

The root cause here was that the `confirm` and `select` inputs weren't correctly handling the `cancel` state of clack prompts.
