### ISSUE TITLE
🐛 BUG: Service binding not available in queue export

### ISSUE THREAD

**Issue by cleytoncarvalho** [cloudflare/workers-sdk#3320]
### Which Cloudflare product(s) does this pertain to?

Queues, Workers/Other

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

Mac

### Describe the Bug

I have a service binding to communicate to another worker, it's available in the env fetch export but not in the queue env export. Not sure if this is a bug or a feature that still needs to be created.

`async fetch(request: Request, env: Env): Promise<Response>` - env.MY_BINDING is defined

`async queue(batch: QueueEvent, env: Env): Promise<Response>` - env.MY_BINDING is **not** defined

**Comment by cpauwels** [comment]
Same issue here, and it also seems to be broken in wrangler 2
