### ISSUE TITLE
🐛 BUG: Ship and fork with the WARP cert

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-sdk#3328]
### Which Cloudflare product(s) does this pertain to?

C3

### What version of `Wrangler` are you using?

n/a

### What operating system are you using?

macOS

### Describe the Bug

If I've got WARP on, NPM/Yarn/Volta etc. all fail because they don't rely on the system cert chain.

Wrangler ships with [it's own copy of the Cloudflare CA cert](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/Cloudflare_CA.pem) and [forks itself to use it](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/bin/wrangler.js#L68). C3 should probably consider doing the same!

**Comment by jculvey** [comment]
Closing because this was fixed via DNS resolution improvements. Certs should be provided via the NODE_EXTRA_CA_CERTS environment variable.
