### ISSUE TITLE
🚀 Feature Request: [C3] Handle duplicate pages project names gracefully

### ISSUE THREAD

**Issue by jculvey** [cloudflare/workers-sdk#3331]
### Describe the solution

If you already have an existing pages project that's the same name as the one you've given to c3, it will fail late in the deployment process with a raw wrangler error. A better experience would be to fail in a mode similar to a disallowed wrangler login attempt -- show a partial success and give the user some next steps on how to continue the process.

**Comment by jculvey** [comment]
Potential solution: validate that the name is unique across pages & workers before creating.

**Comment by dario-piotrowicz** [comment]
I'm closing this as we've discussed this internally and it seems like the current implementation is correct

The check it performs is done a bit late which is not optimal but that's actually the earlier possible moment in which we can actually perform such check

Besides users should not hit this issue too often so hopefully it's not really a problem
