### ISSUE TITLE
🐛 BUG: Smart Placement

### ISSUE THREAD

**Issue by deleteDB** [cloudflare/workers-sdk#3342]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms, Workers/Other, Wrangler

### What version of `Wrangler` are you using?

 wrangler 3.0.1

### What operating system are you using?

Windows

### Describe the Bug

I think I should know what the problem is because I was eligible to use "Smart Placement" even before it was publicly tested. After "Smart Placement" entered beta, a new statement was added: "Smart Placement is intended for latency-sensitive Workers and as such, does not currently work with Cron Triggers." This prevented me from using "wrangler publish" to deploy updates and even from deleting scheduled tasks in the workers console, as well as switching back to the "Default" state from "Smart Placement." I tried commenting out the triggers environment variable and removing "[unsafe.metadata.placement]
mode = "smart"," but none of these actions worked. I performed all these operations in the console but couldn't modify or publish the workers.

Here is the error message:

```shell
workers.api.error.unknown [code: 10013]

If you think this is a bug, please open an issue at:
https://github.com/cloudflare/workers-sdk/issues/new/choose
```

**Comment by deleteDB** [comment]
https://github.com/cloudflare/workers-sdk/assets/91873635/9cd9cf5a-20c5-4620-a7ab-842cd2fd3e44


https://github.com/cloudflare/workers-sdk/assets/91873635/9d6eb957-b257-4275-93df-e53f897e8350

The above is the screen recording operation of the console.

**Comment by deleteDB** [comment]
![eroor-2](https://github.com/cloudflare/workers-sdk/assets/91873635/e6ea35d3-2769-41df-b449-e1fbbbc9d1c9)
![eroor](https://github.com/cloudflare/workers-sdk/assets/91873635/8db31250-19bf-4767-8655-035bb0ae1f13)
console wrong picture

**Comment by tanushreesharma-cf** [comment]
Hi @deleteDB! Yeah, this like you're stuck in an odd state because of the precaution we added for Cron Triggers. Can you email me your Cloudflare account ID and worker name - tanushree[at]cloudflare[dot]com

**Comment by deleteDB** [comment]
Hi @tanushreesharma-cf ，thank you very much, I have sent the corresponding information to the email address you specified.

**Comment by penalosa** [comment]
Sounds like this has been resolved—if you're still running into issues let me know!
