### ISSUE TITLE
🐛 BUG: Old `init` commands no longer functional

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#3348]
### Which Cloudflare product(s) does this pertain to?

C3

### Describe the Bug

Many of the templates in the `templates` repo here have READMEs that suggest init commands that don't work anymore.

For example:
- https://github.com/cloudflare/workers-sdk/tree/main/templates/experimental/worker-rust
- https://github.com/cloudflare/workers-sdk/tree/main/templates/worker-r2

Running these commands such as `npm init cloudflare project_name worker-rust` result in an interactive C3 prompt, and don't then deploy the template you wanted even if you follow the prompts.

https://github.com/cloudflare/workers-rs also suggests this in its README.

**Comment by admah** [comment]
@Cherry we've got some changes to `init` coming soon via #3359. Once those land, I'll get the template docs updates in.

**Comment by Cherry** [comment]
Thanks Adam. In addition, once this lands, I'd recommend searching the docs repo in general for things like `npm init`, `wrangler init`, etc. and verifying all of the suggested commands there still function as expected.

**Comment by admah** [comment]
I've updated all of the template examples in this repo removing `init`. I've also put a PR in to update the `workers-rs` repo. Closing this issue as complete.
