### ISSUE TITLE
ERROR: Could not resolve http, https, fs even after NPM install (node_compat = false)

### ISSUE THREAD

**Issue by MrAshFar** [cloudflare/workers-sdk#3351]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

win64

### Describe the Bug

```
ERROR: Could not resolve "http"
ERROR: Could not resolve "https"
ERROR: Could not resolve "stream"
ERROR: Could not resolve "fs"
ERROR: Could not resolve "path
```

Only **stream** and **path** are resolved after NPM installation other three ones still cause build errors. If I use node_compat = true again builds fails in **globals**.

**Comment by MrAshFar** [comment]
```
  Uncaught TypeError: globalThis.XMLHttpRequest is not a constructor
    at index.js:2851:11 in checkTypeSupport
    at index.js:2872:38 in
  ../../../../AppData/Roaming/npm/node_modules/wrangler/node_modules/rollup-plugin-node-polyfills/polyfills/http-lib/capability.js
```

This error is thrown when node_compat = true

**Comment by Cherry** [comment]
`http`, `https`, `fs`, `XMLHttpRequest `, etc. are not supported or polyfilled APIs unfortunately, even in the newer and more native [Node.js compat efforts](https://developers.cloudflare.com/workers/runtime-apis/nodejs/) . You will likely need to use another library more designed for a non-node environment.

**Comment by penalosa** [comment]
Thanks for reporting this! The answer by @Cherry covers why this isn't working (these APIs are not currently supported in Workers), and so I'll close this issue for now. 

The way to make network requests in the Workers environment is to use the web standard [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) API.
