### ISSUE TITLE
🚀 [Wrangler] Feature Request: Flag to seed local KV / D1 for new projects from existing KV / D1 stores

### ISSUE THREAD

**Issue by code-poel** [cloudflare/workers-sdk#3356]
### Describe the solution

It would be really helpful to have wrangler commands/flags to allow for easier seeding of a new local project's KV and D1 data from an existing KV or D1 data store.

Use Case:
I have an existing CF Worker that runs on a schedule and writes to D1 and KV storage.

I would like to create a new Pages or Worker project that can utilize the KV values or D1 data.

To get this working locally, I need to write a script to pull all KV values from a namespace and then write them to the local KV storage or download a D1 backup and import it locally.  While totally possible, it can be pretty confusing when getting started to figure out how to do this.  Having a wrangler command or flag that could read from the remote stores and then write them to the local filesystem would be exceedingly useful.

**Comment by admah** [comment]
Thanks for submitting this @code-poel. I can see this as a very useful command. I'm wondering how would you envision it as a flag?

**Comment by code-poel** [comment]
Use of "flag" was the wrong choice.

Something like:

wrangler d1 import <source_database_id> <local_binding>

✅ Successfully imported DB '<database_name_from_source>'

[[d1_databases]]
binding = "DB"
database_name = "<database_name_from_source>"
database_id = "<source_database_id>"

**Comment by zhiqingchen** [comment]
Thanks for submitting this @code-poel. I can see this as a very useful command. I'm wondering how would you envision it as a flag?

**Comment by admah** [comment]
@code-poel I think this functionality may exist now in Wrangler. Would this command do what you're looking for?

`wrangler d1 migrations apply your-database --local`

Based on [the docs](https://developers.cloudflare.com/d1/learning/local-development/#test-programmatically), this should setup your local DB using data from the existing `your-database`.

cc: @elithrar

**Comment by penalosa** [comment]
It looks like this is existing functionality in Wrangler, so I'm going to close this for now. If the existing commands don't fully cover your use-case feel free to comment and we can re-open

**Comment by ImLunaHey** [comment]
Seems like there's been a bit of confusion here. Seeding and migrations are two different things.

Can this please be reopened?
