### ISSUE TITLE
🐛 BUG: "Unknown Error: undefined" from missing flag in `unstable_dev`

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/workers-sdk#3362]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.20.0

### What operating system are you using?

Mac 13.3.1

### Describe the Bug

This was not a fun one to find 😓 

Take the following code:
```js
import { Buffer } from 'node:buffer';

export default {
	async fetch(request: Request): Promise<Response> {
		const encoded = Buffer.from(request.url).toString('base64');
		return new Response(encoded);
	},
};
```

and the test:
```js
import { unstable_dev } from "wrangler";
import type { UnstableDevWorker } from "wrangler";
import { describe, expect, it, beforeAll, afterAll } from "vitest";

describe("Worker", () => {
	let worker: UnstableDevWorker;

	beforeAll(async () => {
		worker = await unstable_dev("src/index.ts", {
			experimental: { disableExperimentalWarning: true },
		});
	});

	afterAll(async () => {
		await worker.stop();
	});

	it("should return Hello World", async () => {
		const resp = await worker.fetch('https://example.com/');
		if (resp) {
			const text = await resp.text();
			expect(text).toBe(btoa(`http://${worker.address}:${worker.port}/`));
		}
	});
});
```

This is gonna fail, there's no `nodejs_compat` flag right? Well, it does fail... however:
```
➜  unstable-dev git:(main) npm run test

> unstable-dev@0.0.0 test
> vitest


 DEV  v0.31.1 /Users/walshy/workspace/workers/unstable-dev

 ❯ src/index.test.ts (1)
   ❯ Worker (1)
     ⠼ [ beforeAll ]
     · should return Hello World

 Test Files   (1)
      Tests   (1)
   Start at  17:57:29
   Duration  430ms (transform 36ms, setup 0ms, collect 227ms, tests 0ms, environment 0ms, prepare 41ms)

⎯⎯⎯ Unhandled Error ⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯ Unhandled Error ⎯⎯⎯
Unknown Error: undefined


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
```

This failure is insanely unhelpful, I'm not sure how it's getting to this error without any stacktrace but yeah. In a large project, it's extremely difficult to find this issue.

In my case, this worked in CI but not locally, if `unstable_dev` just can't find the flag through options or wrangler.toml for xyz reason it fails this badly.

Simple fix but with a very non-verbose error, which makes finding the cause extremely difficult.

**Comment by admah** [comment]
@WalshyDev thanks for filing this issue. We are currently doing work around `unstable_dev` and will add a fix for this to that body of work. We should provide better messaging for users when there is missing config.
