### ISSUE TITLE
🐛 BUG: Failed to delete a worker previously binding to a queue

### ISSUE THREAD

**Issue by prprnya** [cloudflare/workers-sdk#3370]
### Which Cloudflare product(s) does this pertain to?

Queues, Workers for Platforms, Workers/Other

### What version of `Wrangler` are you using?

3.0.0

### What operating system are you using?

Unrelated to OS, it also happens on web dashboard

### Describe the Bug

When I try to run `wrangler delete --name=wildebeest-consumer-prprnya` to delete a worker previous binding to a queue, the output is like below:

```txt
 ⛅️ wrangler 3.0.0 (update available 3.0.1)
-----------------------------------------------------
√ Are you sure you want to delete wildebeest-consumer-prprnya? This action cannot be undone. ... yes

✘ [ERROR] A request to the Cloudflare API (/accounts/<account>/workers/services/wildebeest-consumer-prprnya) failed.

  script still in use as a consumer for a queue [code: 10064]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

I have already deleted all of my queues in the dashboard, cleared all routes and variables, renamed the worker, and replaced the codes by example in the documentation, even canceled the workers paid subscription. After so many attempts, the same error still occurs on the wrangler cli and web dashboard.

**Comment by admah** [comment]
@prprnya thanks for filing this issue. To do this, you'll need to log into the Cloudflare Dashboard, and:

- find the queue
- click on "Settings"
- under "Consumer Details" disconnect the consumer

Once it has been disconnected, you can delete the Worker via Wrangler (or the dashboard) as expected. 

I'm going to close this, but feel free to reopen if this doesn't address your issue.

**Comment by filipfalcon** [comment]
For anyone wondering whether this is achievable using the CLI, yes it is:

```bash
wrangler queues consumer remove <queue-name> <script-name>
```

Find out more information [here](https://developers.cloudflare.com/workers/wrangler/commands/#consumer-remove).
