### ISSUE TITLE
Improve messaging around `wrangler rollback` not being able to find a worker

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#3372]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

Mac

### Describe the Bug

```
npx wrangler@beta rollback
 ⛅️ wrangler 0.0.0-2956c31d
---------------------------
🚧`wrangler rollback` is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose


✘ [ERROR] A request to the Cloudflare API (/accounts/xxxx/workers/services/undefined) failed.

  workers.api.error.service_not_found [code: 10090]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

If a worker name is required, the command should be `rollback <deployment-id>`, not `rollback [deployment-id]`

**Comment by admah** [comment]
You should be able to run `rollback` without an ID. That should rollback the current Worker to the last deployment as described in [the docs](https://developers.cloudflare.com/workers/wrangler/commands/#rollback). I do think this is a bug.

**Comment by rozenmd** [comment]
Wait does the command need to be run within a project that contains a wrangler.toml?

**Comment by rozenmd** [comment]
@JacobMGEvans:
```
rozenmd@xxxxx asddf % cd ~
rozenmd@xxxxxxxxx ~ % npx wrangler@latest rollback
 ⛅️ wrangler 3.1.0
------------------
✔ Select an account › xxxxx@gmail.com's Account
🚧`wrangler rollback` is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose


✘ [ERROR] A request to the Cloudflare API (/accounts/xxxx/workers/services/undefined) failed.

  workers.api.error.service_not_found [code: 10090]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

**Comment by penalosa** [comment]
We should probably provide better logging here, and allow specifying a worker name

**Comment by admah** [comment]
That's a good idea @penalosa. This was originally designed in the context of running it in a project folder. Adding a `--name`  option like `wrangler deploy` could work here.
