### ISSUE TITLE
🐛 BUG: create-cloudflare worker-rs stopped working

### ISSUE THREAD

**Issue by paul-asvb** [cloudflare/workers-sdk#3376]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.0.8

### What operating system are you using?

linux

### Describe the Bug

# Expectation
`npm init cloudflare project_name worker-rust `
should create a rust directory with a compiling worker. 

# Reality
The command creates js worker

**Comment by admah** [comment]
@paul-asvb can you try running this command `npm init cloudflare@1 my-project worker-rust`? I think that will create the project as expected.

**Comment by JacobMGEvans** [comment]
Thanks for the response Adam, Paul if you have further issues or the suggestion from Adam doesn't work please feel free to reopen the issue.
