### ISSUE TITLE
🐛 BUG: Pages Function Compilation Error Crashes Servers, Leaves Ports Listening

### ISSUE THREAD

**Issue by arimgibson** [cloudflare/workers-sdk#3378]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

Linux -- Fedora 37 & 38

### Describe the Bug

Exact replica of #94, which is strange as that issue was patched 1.5 years ago.

When using Wrangler (local development, so Miniflare included) and editing a Page function, the server crashes on compilation errors instead of showing an error message as @GregBrimble configured. The server's listener on port 8788 is left running and has to be manually killed before restarting the server. This behavior is not apparently in Wrangler when developer a Worker.

Reproduction Steps -- and [minimal reproducible example](https://github.com/arimgibson/pages-functions-repro):
1. Use `pnpm create cloudflare` to create a new Pages application (used Astro, framework shouldn't matter)
2. Add a functions directory with `helloworld.js`, which has working onRequest function
3. Start server with `pnpm pages:dev`, visit http://127.0.0.0:8788/helloworld
4. Change helloworld.js to throw compliation error, such as removing an ending parenthesis

![Screenshot from 2023-05-30 14-27-57](https://github.com/cloudflare/workers-sdk/assets/43756494/e7d27b04-10e9-46d4-ad8a-05025bdb88da)

![Screenshot from 2023-05-30 14-29-14](https://github.com/cloudflare/workers-sdk/assets/43756494/c81b146b-a7ce-457d-adfd-1ff89b4d5f7c)

**Comment by baer** [comment]
I've been experiencing the same. Adding a few additional details here:

- I'm running macOS 13.4 (Ventura) with Node v20.2.0
- The process that gets left behind is `workerd`
- When running a dev server (e.g. `wrangler pages dev -- npm run dev-next`) several Node processes are also left behind which cause issues with the proxy or spin the CPU at 100%.

**Comment by arimgibson** [comment]
Mmm thanks for the additional context @baer, forgot to add that it's the `workerd` process which doesn't close!

As Node v20 isn't LTS quite yet, I'll add that I'm on Node v18.16.0, so it impacts both versions

**Comment by baer** [comment]
Actually, I have a bit more detail. The command above almost always leaves node processes around, even if wrangler exists properly.

**Comment by baer** [comment]
Update:

1. On the node side, it looks like Wrangler is orphaning a single process (the `npm run dev-next` command), but that Next's dev server has three child processes.
2. Wrangler will orphan these node processes every time, even if it is terminated properly using the `x` keyboard input

I wrote a script to help manage the issue while this is being fixed. 

**⚠️  To anybody who runs scripts from the Internet without reading/understanding them ⚠️**
This script kills **ALL** `node` and `workerd` processes, not just the ones that are orphaned. That means that if you're running other processes/servers for other projects at the same time, it'll nuke those too.

<img width="502" alt="Screenshot 2023-06-08 at 10 45 34 AM" src="https://github.com/cloudflare/workers-sdk/assets/940667/b1669a52-60ac-4141-abcb-3adccbd425a1">

```bash
#!/bin/bash

# ANSI color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m' # No color

# Time in seconds given for processes to gracefully exit
sleep_time=5

# Function to kill process with graceful fallback
kill_process() {
    process_name=$1

    # Find the PID of matching processes
    pids=($(pgrep "$process_name"))

    # Count the number of found processes
    num_processes=${#pids[@]}

    # Exit if there are no processes found
    if [ $num_processes -eq 0 ]; then
        echo -e "${GREEN}🔍 No processes found for $process_name${NC}"
        return
    fi

    # Try to terminate processes gracefully
    echo -e "${GREEN}🔍 Found $num_processes $process_name processes${NC}"
    for pid in "${pids[@]}"; do
        echo -e "\t${YELLOW}✋ Sending SIGTERM to $process_name process with PID: $pid${NC}"
        kill -15 $pid
    done

    # Wait a bit to allow processes to terminate
    echo -e "${GREEN}⏳ Waiting $sleep_time seconds for $process_name processes to terminate...${NC}"
    sleep $sleep_time

    # Forcefully kill if still running
    for pid in "${pids[@]}"; do
        if kill -0 $pid 2>/dev/null; then
            echo -e "\t${RED}💥 $process_name process with PID $pid did not terminate, sending SIGKILL${NC}"
            kill -9 $pid
        fi
    done
}

# =============================================================================
# =============================================================================

echo -e "\n${BLUE}🧟 Starting the Zombie Slayer! 🧟${NC}\n"

kill_process "workerd"
kill_process "node"

echo -e "\n${BLUE}🧹 Zombies have been eliminated! Keeping it clean. Keep it classy. 🧹${NC}"
```
