### ISSUE TITLE
🚀 Feature Request: Add wrangler support for ARM 32/64

### ISSUE THREAD

**Issue by rhaksw** [cloudflare/workers-sdk#3379]
### Describe the solution

I run wrangler on a Raspberry Pi to collect logs, though I had some trouble figuring out which version I needed. Someone in the community forum [helped me](https://community.cloudflare.com/t/does-wrangler-3-support-arm32/515900/4) discover that I needed wrangler version _2_, not 1 or 3.

I was advised to open an issue here and request that wrangler 3 support ~~ARM 32/64 devices~~ the Pi's OS. Mine says "Raspbian GNU/Linux 9.13 (stretch)". I'm sure that's outdated but I also understand wrangler 3 currently only supports a limited set of the latest operating systems, and it doesn't look like the Pi's OS is in that set.

**Comment by penalosa** [comment]
Closing in favour of https://github.com/cloudflare/workers-sdk/issues/3457

**Comment by karneaud** [comment]
Can we reopen this issue @penalosa ?? I'm using a Docker container on a RPI4 running arm6v8 Linux raspberrypi 6.6.62+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux
