### ISSUE TITLE
🐛 BUG: Shared CTX between Requests when running `wrangler dev`

### ISSUE THREAD

**Issue by amiller68** [cloudflare/workers-sdk#3380]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

Mac

### Describe the Bug

I have a worker implementation with middleware that takes a value from a header in requests, and saves it within `ctx`
In local E2E testing, I've noticed the following behavior:
- `test A` will make `request A` to `route A` with a known `value A` as the header
- `test B` will make `request B` to  `route B` with a random `value B` as the header
In logs generated by the handler at `route B`, on some concurrent tests I observe `value A` being listed as the value within the header, instead of `value B`. Furthermore, when I run tests in sequence, this problem goes away, and all my tests pass.
This demonstrates that on interleaved requests, the `ctx` from  `request A` has replaced that of `request B` some time before the log from the handler at `route B` occurs.

**Comment by penalosa** [comment]
Thanks for reporting this! Could you link a reproduction repo so we can investigate further?

**Comment by penalosa** [comment]
We haven't heard from you in a while, so I'm going to close this issue for now. If you're still running into issues feel free to comment with more details and we can investigate further
