### ISSUE TITLE
🐛 BUG: static assets are deleted before deploying new worker succeeds

### ISSUE THREAD

**Issue by jdiamond** [cloudflare/workers-sdk#3382]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.13.0

### What operating system are you using?

Linux

### Describe the Bug

I occasionally get the error about our workers taking too long to start up. When this happens, running the exact same command to re-deploy almost always works. I would like to figure out what to do to avoid this but have not yet discovered what makes it randomly fail. We are not doing anything explicitly in our workers to make it take long other than importing lots of other modules.

During our deploy, Wrangler is also uploading static assets. After uploading the new assets, Wrangler deletes the old ones. This wouldn't be a problem if the worker didn't take too long to start. In the cases where that happens, our users have reported seeing errors about not being able to find the old assets in KV. After I re-deploy and the new worker is running, they are able to press refresh which loads the new assets, but I would prefer if our users were never exposed to this problem.

I think this situation could be improved by deleting the old assets _after_ validating the new worker can start.

The current sequence appears to be this:

- upload new assets
- delete old assets
- upload new worker
- validate it started quickly enough

What I would like it be:

- upload new assets
- upload new worker
- validate it started quickly enough
- delete old assets

Is this possible? Thanks.

**Comment by RamIdeas** [comment]
We're going to be re-addressing assets as part of the [Workers/Pages convergence](https://blog.cloudflare.com/pages-and-workers-are-converging-into-one-experience/). Closing this for now
