### ISSUE TITLE
🐛 BUG: C3 ungracefully quits when not logged in on an old version of Wrangler

### ISSUE THREAD

**Issue by jmadruga-cf** [cloudflare/workers-sdk#3388]
### Which Cloudflare product(s) does this pertain to?

C3

### What version of `Wrangler` are you using?

2.x

### What operating system are you using?

Mac

### Describe the Bug

We should check if you you have an old version of Wrangler during C3 create workflow.  When I run "npm create cloudflare" and create a Next project, I'm helpfully guided through all the options.  However, at the end it asks me if I want to deploy and if I'm not already logged into wrangler I'm dumped into an ugly error message:

 
<img width="1014" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/37448704/c3c802ee-6f45-466a-8259-6cc7f45089ce">

```✘ [ERROR] Not logged in.


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose

1
npm notice
npm notice New patch version of npm available! 9.6.4 -> 9.6.7
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.7
npm notice Run npm install -g npm@9.6.7 to update!
npm notice
npm ERR! code 1````

We could easily avoid this by checking a user's version of wrangler at the beginning of the workflow.  When I upgraded to Wrangler 3, the tool worked great.  It prompted me to login.

**Comment by penalosa** [comment]
This has been fixed in newer versions of C3
