### ISSUE TITLE
🐛 Bug: templates are failing

### ISSUE THREAD

**Issue by wighawag** [cloudflare/workers-sdk#3389]
### Which Cloudflare product(s) does this pertain to?

Workers/Other

### What version of `Wrangler` are you using?

templates

### What operating system are you using?

templates

### Describe the Bug

the example / template on stackblitz fails:

https://stackblitz.com/edit/cloudflare-templates-rna8ho?file=wrangler.toml&terminal=start-stackblitz&title=Workers%20TypeScript

This example also fails when downloaded on local machine :

https://stackblitz.com/edit/cloudflare-templates-ravnmm?file=.editorconfig&terminal=start-stackblitz&title=Workers%20Router

**Comment by JacobMGEvans** [comment]
This might be a StackBlitz issue, we may need to reach out. 

@admah

**Comment by penalosa** [comment]
Thanks for reporting this! This looks like a StackBlitz issue, where the wrong port is being detected (it's wrongly detected as 6284). Changing the port to 8787 in the StackBlitz UI should fix the issue. Feel free to comment with more details if you're still running into the issue!

**Comment by admah** [comment]
I have filed an issue with Stackblitz [here](https://github.com/stackblitz/webcontainer-core/issues/1101).
