### ISSUE TITLE
🐛 BUG: `wrangler deploy` uses "production" as a default environment, however doesn't use env.production section in wrangler.toml

### ISSUE THREAD

**Issue by jancespivo** [cloudflare/workers-sdk#3392]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

Linux

### Describe the Bug

`wrangler deploy` deploys to production environment by default but it doesn't use [env.production] section in wrangler.toml 

It leads to hardly noticeable errors in production environment, when new code is deployed but for example routes differ from ones defined in wrangler.toml, just because developer forgot to use `wrangler deploy --env production` and used just `wrangler deploy` instead.

**Comment by Cherry** [comment]
As far as I know, `wrangler deploy` doesn't default to any specific environment, but you're probably seeing `production` as from the Cloudflare dashboard.

The terminology around this all is a little confusing, sorry. Let me see if I can summarise.

Originally, Cloudflare introduced [Service Environments](https://developers.cloudflare.com/workers/learning/using-services/#service-environments). These allowed users to create environments in the dash, and split config between them. This had issues and was "temporarily" disabled. This is what you see in the dash today with the "production" environment dropdowns and things.

All the time during this, Wrangler offered its own version of [Environments](https://developers.cloudflare.com/workers/platform/environments/). These are controlled and managed by Wrangler itself, and will result in multiple workers being created per env, such as `your-project-prod`, `your-project-dev` - this is the `env.production` config and such that you see in `wrangler.toml`. This works really well, and lets you split absolutely everything per environment, but isn't the most ergonomic with multiple workers.

And then [Deployments](https://developers.cloudflare.com/workers/platform/deployments/) was introduced recently. The [blog post](https://blog.cloudflare.com/deployments-for-workers/) describes a lot of things that are planned in future for Deployments, but today they're essentially just a historic report of when/how you deployed your worker.

cc @admah

**Comment by penalosa** [comment]
Thanks for the detailed summary @Cherry. To confirm, `wrangler deploy` shouldn't default to any specific environment. To use a `production` environment defined in your `wrangler.toml`, you'll need to use `wrangler deploy -e production`. This should show up in the dashboard as a `-production` suffix to your worker name.

**Comment by jancespivo** [comment]
Thanks @Cherry and @penalosa Now I understand :)

The reason it worked like I described was we have had `name=some_name` in wrangler.toml on top-level and also in [env.production]. It seems when name is defined in environment section, it is used as is and no suffix is added. So both "environments" were deployed as the same worker name - so overrode.
