### ISSUE TITLE
🚀 Feature Request: Support custom plugins when bundling worker/pages function

### ISSUE THREAD

**Issue by mariusGundersen** [cloudflare/workers-sdk#3393]
### Describe the solution

I work on a page which uses server side rendered react to generate html (which is then hydrated client side, similar to what next, gatsby, etc do). As part of this I use css modules with the less precompiler. This is all bundled using webpack, which I can configure with custom plugins. This bundled js file is then passed on to wrangler which further bundles it using esbuild. It seems a bit silly to me to bundle the js twice, and in dev mode I need to have both webpack and esbuild (through wrangler) in watch mode. This is inefficient. If I could supply my own plugins to the esbuild instance used in wrangler I could skip the webpack step.

There could be a `wrangler.config.mjs` file which wrangler would load and use to configure esbuild. This file could export a variety of things, for example

```js
export function esbuildOptions(){
  return {
    plugins: [

    ],
    loader: {}
  };
}
```

This would then merge these objects with the built in values.

**Comment by penalosa** [comment]
Thanks for reporting this! We're unlikely to expose Wrangler's `esbuild` options in the near future, but you can use Wrangler's `--no-bundle` flag if you'd like to skip Wrangler's `esbuild` step. https://developers.cloudflare.com/workers/wrangler/custom-builds/

**Comment by mariusGundersen** [comment]
I need this for pages, which does things slightly differently, and always runs the bundle step, no matter what. I therefore end up with my first bundle run and then the esbuild run afterwards, every time.
