### ISSUE TITLE
🚀 Feature Request: [C3] Can we rephrase "Where do you want to create your application"?

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#3394]
### Describe the solution

When you run `npx create cloudflare@latest` you're immediately prompted with:
```
╰ Where do you want to create your application? also used as application name
--black-thunder-97ee
```

I think i'm finding it confusing because the CLI's default value + the prompt looks like a flag?

Compare that to something like:

```
? Where would you like to create your app? (./my-worker-app)
```
Where the terminal's cursor is at the end of the line, and it's immediately clear that it wants a relative directory path

**Comment by admah** [comment]
@rozenmd we'll take a look and see what we can do. Thanks!
