### ISSUE TITLE
🐛 BUG: [wrangler v3] - Workers that only have a `scheduled` handler report an error when invoked locally

### ISSUE THREAD

**Issue by code-poel** [cloudflare/workers-sdk#3395]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

WSL

### Describe the Bug

If you have a worker that only should be invoked through a `scheduledEvent` and thus only has a `scheduled` method, when you test it locally with the `--test-scheduled` flag and hit the `/__scheduled` route, wrangler will display an error.  The code still executes but it's confusing to have that error display.

Sample worker code:
```js
export default {
  async scheduled(event, env, ctx) {
    try {
      console.log('incoming markup scheduled event')
    }
    catch (error) {
      console.log(error)
    }
  },
}
```

Output of hitting the `/__scheduled` route...

![image](https://github.com/cloudflare/workers-sdk/assets/525901/8ad63284-d2d3-4d66-a35b-a7b749a7ee59)

**Comment by JacobMGEvans** [comment]
👋🏻 Greetings, 

It seems like its working as expected, however, we will look into 404'ing a favicon request. 

Additionally adding a fetch handler to your setup with drastically reduce the error logging out.

**Comment by RamIdeas** [comment]
It looks like this isn't a bug. If you have any more information please feel free to follow up. Closing for now
