### ISSUE TITLE
🐛 BUG: Unable to upload assets to pages using wrangler

### ISSUE THREAD

**Issue by mohamine18** [cloudflare/workers-sdk#3398]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

Windows

### Trying to upload assets to my page created using wrangler
NodeJS 18.14.2
Wrangler 3.0.1
windows OS
Assets: index.html, 2 CSS files, few images, few JS files

### This is the command and what the CLI communicate 
No project selected. Would you like to create one or use an existing
project?
  Create a new project
> Use an existing project
Select a project:
> coming-soon
�  Uploading... (0/27)

### This is the CLI error response
FatalError: Failed to upload files. Please try again. Error: {"text":"Received a malformed response from the API","notes":[{"text":"<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1*>502 Bad Gateway</h1*></cente... (length = 155)"},{"text":"POST /pages/assets/upload -> 502 Bad Gateway"}],"kind":"error","name":"ParseError"})
    at C:\Users\Amine-HP\AppData\Roaming\nvm\v18.14.2\node_modules\wrangler\wrangler-dist\cli.js:141131:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (C:\Users\Amine-HP\AppData\Roaming\nvm\v18.14.2\node_modules\wrangler\wrangler-dist\cli.js:140737:26) {
  code: 1
}

**Comment by mohamine18** [comment]
### This is the Error from dashboard drag and drop feature
![drag drop](https://github.com/cloudflare/workers-sdk/assets/5670526/59cef035-80f3-4847-b4a4-4a7ca47cf838)

**Comment by admah** [comment]
@mohamine18 in an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last few months. If this is still a problem, please feel free to open a new issue referencing this one. Please be sure to include an updated summary and any additional context and we will review.
