### ISSUE TITLE
🐛 BUG: Code 7403 accessing constellation models

### ISSUE THREAD

**Issue by rawsh** [cloudflare/workers-sdk#3402]
### Which Cloudflare product(s) does this pertain to?

Workers/Other

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

Mac

### Describe the Bug

Steps

1. `npx wrangler login`
2. `npx wrangler constellation catalog list`

```
✘ [ERROR] A request to the Cloudflare API (/accounts/05d8805cc6b6454c6e6dcd571f2be57a/constellation/catalog) failed.

  The given account is not valid or is not authorized to access this service [code:
  7403]
```

**Comment by JacobMGEvans** [comment]
Do you have access to Constellation? It is a closed beta 

https://dash.cloudflare.com/?to=/:account/workers/constellation

<img width="795" alt="Screenshot 2023-06-07 at 1 23 09 PM" src="https://github.com/cloudflare/workers-sdk/assets/27247160/2623a3dc-6813-4899-8f91-a39b534d615c">

**Comment by penalosa** [comment]
We haven't heard from you in a while, so I'm going to close this issue for now. If you're still running into issues feel free to comment with more details and we can investigate further!
