### ISSUE TITLE
🐛 BUG: Pages Example Forum App documentation lacking

### ISSUE THREAD

**Issue by ghost** [cloudflare/workers-sdk#3405]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

3

### What operating system are you using?

macOS

### Describe the Bug

Documentation for the [pages-example-forum-app](https://github.com/cloudflare/workers-sdk/tree/main/templates/pages-example-forum-app) lacks adequate information regarding the configuration of `REACT_APP_` environment variables.
```
REACT_APP_CLIENT_ID=
REACT_APP_CLIENT_SECRET=
REACT_APP_REDIRECT_URL=
REACT_APP_AUTHORIZATION_ENDPOINT=
REACT_APP_TOKEN_ENDPOINT=
REACT_APP_RESOURCE_ENDPOINT=
REACT_APP_SECRET_KEY=
```
First three were relatively easy as they are part of the GitHub OAuth app setup. The next four I'm afraid I have no idea where I am meant to get these from.

Can someone expand on what is currently available *(below)* so the slightly more inept of us have some semblance of an idea what is going on.
> Create a .env file and copy to contents of .env.example into the file. Then replace the credentials accordingly.

**Comment by RamIdeas** [comment]
Hi @jasiqli. Thanks for flagging this. The templates directory at the root of this repo has been deprecated in favour of the templates for C3 (create-cloudflare). We plan to migrate/rewrite/remove the existing templates. I've created [this issue](https://github.com/cloudflare/workers-sdk/issues/3514) to ensure we don't end up in the same position again.

**Comment by RamIdeas** [comment]
We're in an internal discussion regarding the direction of existing workers templates. For context, there are new templates being added to C3 (create-cloudflare).

In the meantime, we'll keep this issue open to document the env vars as is.

If you're interested in hearing about / giving input on the direction of Workers templates, please feel free to reach out on Discord! https://discord.gg/cloudflaredev

**Comment by jasiqli** [comment]
Thanks @RamIdeas.

Can't say I've taken to using C3. Haven't seen a need.

Have not had an issue *(at least an I couldn't solve myself)* with any of the other current templates.

I don't use Discord.

**Comment by penalosa** [comment]
We no longer recommend users use these templates to get started with projects, as they're generally very out of date. For up to date project templates, you can refer to https://developers.cloudflare.com/workers/get-started/quickstarts/ & for tutorials you can refer to https://developers.cloudflare.com/workers/tutorials/
