### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by rz3pehr** [cloudflare/workers-sdk#3412]
### Which Cloudflare product(s) does this pertain to?

C3, D1, KV, Pages, Pub/Sub, Queues, R2, Workers for Platforms, Workers/Other, Wrangler

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

linux ubuntu

### Describe the Bug

wrangler init --from-dash hello-world-small-hat-021d

**Comment by JacobMGEvans** [comment]
Greetings, 

Seems like you are having an issue, however, without a title, a detailed description and a reproduction of the problem I am afraid there is nothing we can do to help. 

Please follow up with those 3 things so we can help out 😃
