### ISSUE TITLE
🐛 BUG: Can open devtools using wrangler pages

### ISSUE THREAD

**Issue by donferi** [cloudflare/workers-sdk#3417]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

Mac

### Describe the Bug

Context: I have wrangler installed locally in my project as a `devDependency`.

I run my app locally with this command: `wrangler pages dev --compatibility-date=2023-01-01 ./pages`

Everything works fine but I can't open the devtools when I get this menu:

```
 [b] open a browser, [d] open Devtools, [c] clear console, [x] to exit  
```

`b` does open my browser (Brave) but `d` doesn't do anything. How do I get devtools to run? I tried going to `brave://inspect` but I don't see anything related with workerd.

What am I missing? 🤔

**Comment by petebacondarwin** [comment]
Closing due to a lack of response.
