### ISSUE TITLE
🐛 BUG: Most commands are failing with error:  workers.api.error.script_not_found

### ISSUE THREAD

**Issue by RonenEizen** [cloudflare/workers-sdk#3422]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler

### What version of `Wrangler` are you using?

3.1.0

### What operating system are you using?

Mac

### Describe the Bug

Most wrangler commands are failing for all pages projects on my account with the following error: 

`workers.api.error.script_not_found [code: xxxxxxxx]`

![Screenshot 2023-06-08 at 5 29 12 PM](https://github.com/cloudflare/workers-sdk/assets/1503653/94092cab-3403-444b-8b7b-fa5d1af01289)
![Screenshot 2023-06-08 at 5 28 42 PM](https://github.com/cloudflare/workers-sdk/assets/1503653/3e8fcbce-c2f8-4b33-8983-7abd023c9e17)

**Comment by atjeff** [comment]
This looks to happen in wrangler@^2 also

**Comment by penalosa** [comment]
This is quite an old issue, and so I'm going to close it for now. I suspect the root cause was a transient issue with our API, that has hopefully long since been resolved? If you're still running into this feel free to open a new issue and we can investigate further
