### ISSUE TITLE
🐛 BUG: --compatibility-flags="nodejs_compat" --experimental-local doesn't change anything

### ISSUE THREAD

**Issue by ninsiu-com** [cloudflare/workers-sdk#3430]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

3.1.0

### What operating system are you using?

Windows

### Describe the Bug

Hi:

I'm new to pages and I just want the index page to be: `index.htm` instead of `index.html` , so i'm tring to use a simple demo like this to solve this:

    -  index.htm    
    + /functions/
               - index.js
               - require-text.js

index.js :

```JAVASCRIPT
var requireText = require('./require-text');
var html = requireText('./index.htm', require);

export async function onRequest() {
	return new Response( html, {
			headers: { "Content-Type": "text/html" }
	});
}

```

require-text.js:
```JAVASCRIPT
var fs = require('fs');

module.exports = function(name, require) {
    return fs.readFileSync(require.resolve(name)).toString();
};

```

But when i use  command:  `wrangler pages dev ./` to run , it said:

```
X [ERROR] Could not resolve "fs"

    require-text.js:1:17:
      1 │ var fs = require('fs');
        ╵                  ~~~~

  The package "fs" wasn't found on the file system but is built into node.
  Add the "nodejs_compat" compatibility flag to your Pages project to enable Node.js compatibility.


X [ERROR] Build failed with 1 error:

  require-text.js:1:17: ERROR: Could not resolve "fs"
```

So I turned to the document in: https://developers.cloudflare.com/workers/runtime-apis/nodejs/

in Section **Enable Node.js with Pages Functions** It Said:
`
To enable nodejs_compat in local development, pass the [--compatibility-flags](https://developers.cloudflare.com/workers/wrangler/commands/#dev-1) argument with the nodejs_compat flag to wrangler pages dev:
`

```
wrangler pages dev [<DIRECTORY>] --compatibility-flags="nodejs_compat" --experimental-local
```

So I change to the root directory and use command: `wrangler pages dev ./ --compatibility-flags="nodejs_compat" --experimental-local` 

But **NOTHING CHANGED**, still the same error:
```
X [ERROR] Could not resolve "fs"

    require-text.js:1:17:
      1 │ var fs = require('fs');
        ╵                  ~~~~

  The package "fs" wasn't found on the file system but is built into node.
  Add the "nodejs_compat" compatibility flag to your Pages project to enable Node.js compatibility.


X [ERROR] Build failed with 1 error:

  require-text.js:1:17: ERROR: Could not resolve "fs"
```

**Comment by kamsheffield** [comment]
Near the top of the docs it also mentions this:
```
Node.js APIs are available under the node: prefix, and this prefix 
must be used when importing modules, both in your code and the npm packages you depend on.

// Do this:
import { Buffer } from 'node:buffer';

// Do not do this:
import { Buffer } from 'buffer';
```
You can try rewriting your require to `var fs = require('node:fs');` and see if that fixes the issue.

**Comment by ninsiu-com** [comment]
> Near the top of the docs it also mentions this:
> 
> ```
> Node.js APIs are available under the node: prefix, and this prefix 
> must be used when importing modules, both in your code and the npm packages you depend on.
> 
> // Do this:
> import { Buffer } from 'node:buffer';
> 
> // Do not do this:
> import { Buffer } from 'buffer';
> ```
> 
> You can try rewriting your require to `var fs = require('node:fs');` and see if that fixes the issue.

Thanks, and I've tried this, but it said: `Dynamic require of "node:fs" is not supported`

```
service core:user:worker: Uncaught Error: Dynamic require of "node:fs" is not supported
  at functionsWorker-0.6046772983412287.js:6:9
  at functionsWorker-0.6046772983412287.js:78:14 in require-text.js
  at functionsWorker-0.6046772983412287.js:44:50 in __require22
  at functionsWorker-0.6046772983412287.js:95:19 in test.js
  at functionsWorker-0.6046772983412287.js:41:56 in __init
  at functionsWorker-0.6046772983412287.js:116:5 in C:/Users/******/AppData/Local/Temp/functionsRoutes-0.2793327856386669.mjs
  at functionsWorker-0.6046772983412287.js:41:56 in __init
  at functionsWorker-0.6046772983412287.js:150:1
```

Is that because the wrangler does not allow the fs module ? Only the moudule in https://developers.cloudflare.com/workers/runtime-apis/nodejs/ are supported ?

assert
AsyncLocalStorage
Buffer
EventEmitter
path
Streams
StringDecoder
util

**Comment by penalosa** [comment]
Thanks for reporting this! Unfortunately the `node:fs` module isn't available yet—only the specific modules listed out in https://developers.cloudflare.com/workers/runtime-apis/nodejs/ can be used.

**Comment by ninsiu-com** [comment]
> Thanks for reporting this! Unfortunately the `node:fs` module isn't available yet—only the specific modules listed out in https://developers.cloudflare.com/workers/runtime-apis/nodejs/ can be used.
> 
> In terms of solving your initial issue, does just uploading a file called `index.htm` work?


Thank you for your reply, I've solved this problem using the `context` param:

```JAVASCRIPT
// index.js
export async function onRequest( context ) {
	if( context.functionPath == '/' )
	{
		return await context.next( "/index.htm" )
	}
	return await context.next()
}
```


But still had questions:

1. I upload the index.htm file , but when i visit https://example.com/ , cloudflare searches the file: `index.html` , not `index.htm`. **Is there anyway to change the search index file name or file name list ?**

2.  **Is there anyway we can read file content ?**

**Comment by penalosa** [comment]
1. I don't believe so, I think customising via Pages Functions is the intended solution here.
2. In your code, `await context.next( "/index.htm" )` should resolve to a `Response` with a body containing your file content. 

I'm going to close this issue for now, but feel free to comment with more details if you're still running into the issue!
