### ISSUE TITLE
🐛 BUG: preview_bucket_name just doesn't work

### ISSUE THREAD

**Issue by moritz-mm** [cloudflare/workers-sdk#3437]
### Which Cloudflare product(s) does this pertain to?

R2, Workers/Other, Wrangler

### What version of `Wrangler` are you using?

3.1.0

### What operating system are you using?

Windows

### Describe the Bug

I created two buckets "production-builder-assets" and "development-builder-assets".

When i add the r2_buckets binding to my wrangler.toml like this:

```
r2_buckets = [
    { binding = "ASSET_BUCKET", bucket_name = "production-builder-assets", preview_bucket_name = "development-builder-assets" }
]
```

`wrangler dev` i get in the console:

```
Your worker has access to the following bindings:
- R2 Buckets:
  - ASSET_BUCKET: development-builder-assets
```

but when i start a put request like this:

`await context.env.ELEMENT_BUCKET.put("test", "hello world");`

and go to the cloudflare dashboard into my `development-builder-assets` bucket there is no file at all.

The JSON returned from the `put`-call:

```
{
   "customMetadata":{
      
   },
   "httpMetadata":{
      
   },
   "uploaded":"2023-06-12T16:42:18.551Z",
   "checksums":{
      "md5":"5eb63bbbe01eeed093cb22bb8f5acdc3"
   },
   "httpEtag":"\"5eb63bbbe01eeed093cb22bb8f5acdc3\"",
   "etag":"5eb63bbbe01eeed093cb22bb8f5acdc3",
   "size":11,
   "version":"581eddd9e5ba94f9187bbe3f1eaaab24",
   "key":"test"
}
```

i have no idea anymore... can please someone help?

**Comment by Cherry** [comment]
Local `wrangler dev` never interfaces with remote products like R2 - they're all simulated locally.

If you want to use real R2 via `preview_bucket_name`, you need to use remote dev with `wrangler dev --remote`.

**Comment by moritz-mm** [comment]
Gotchua, it works with --remote thanks! Would be nice if that is written down in the docs at the `preview_bucket_name` prop or something!
