### ISSUE TITLE
Implement Turborepo Codegen for Template-able Architecture

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/workers-sdk#3439]
Create a code generation feature in Turborepo that allows easy creation and configuration of new packages or other template-able elements. Refer to the [documentation](https://turbo.build/repo/docs/core-concepts/monorepos/code-generation) for more information.

This also forces consistency and standards for Workers-SDK Monorepo additions/setups like packages, fixtures, templates, etc...

Follow up work to https://github.com/cloudflare/workers-sdk/pull/3261

**Comment by penalosa** [comment]
See https://github.com/cloudflare/workers-sdk/pull/4038#issuecomment-2089907176

**Comment by JacobMGEvans** [comment]
Yep still agree 😄
