### ISSUE TITLE
Implement TypeScript Composition & Project Setup for Monorepo's

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/workers-sdk#3442]
Enable the composite mode for TypeScript projects within the monorepo. The composite mode enforces constraints that allow build tools, including TypeScript itself under the `--build` mode, to quickly determine if a project has been built. 

This mode requires specifying the root directory, including all implementation files, and setting the declaration option to `true`. Refer to the [TypeScript handbook](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#composite) for further documentation on TypeScript projects.

Follow up work to https://github.com/cloudflare/workers-sdk/pull/3261

**Comment by penalosa** [comment]
We're not seeing many issues with how TypeScript is set up right now, and it's not super clear to me what benefit composite mode would bring. We can potentially re-evaluate this in the future if build times become painfully slow.

**Comment by JacobMGEvans** [comment]
Mainly it was the explicit includes it enforced (helps with managing TS monorepos), defaults the rootDir for that tsconfig file, and a few other niceties & perfs as the repo grows, but yeah nothing critical for sure.
