### ISSUE TITLE
🐛 BUG: sh: 1: wrangler: Text file busy

### ISSUE THREAD

**Issue by SimonyanG** [cloudflare/workers-sdk#3443]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.0

### What operating system are you using?

Linux

### Describe the Bug

command 
`npx wrangler pages deploy` returned  `sh: 1: wrangler: Text file busy`

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to provide a reproduction repo that demonstrates the issue?

**Comment by penalosa** [comment]
We haven't heard from you in a while, so I'm going to close this issue for now. If you're still running into issues feel free to comment with more details and we can investigate further!
