### ISSUE TITLE
🐛 BUG:  `wrangler pages dev`  so confusing...

### ISSUE THREAD

**Issue by ninsiu-com** [cloudflare/workers-sdk#3460]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

3.1.0

### What operating system are you using?

Windows

### Describe the Bug

Hi:

**1. Expected to run Locally , but AUTH online.**

I'm using `wrangler pages dev` to test my site locally. As the command document said , the `dev` command is 

> Develop your full stack Pages application locally.

And some days ago , I can use this command to test locally without AUTH online. 

But today when I tried to use  `wrangler pages dev`  to test my site locally, it start oauth online ? 

is this a BUG or?

**2.  Command has different running logical ?**

I have a test site in folder: `cloudflare.pages/` , And i had two ways to debug it:

> a) change to `cloudflare.pages/` and use command: `wrangler pages dev ./` , this command first `compiling worker` and do other things like oauth, as the following output:

```

🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose
▲ [WARNING] No compatibility_date was specified. Using today's date: 2023-06-14.

  Pass it in your terminal:
  `
  --compatibility-date=2023-06-14
  `
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more information.


Compiling worker to "C:\Users\*****\AppData\Local\Temp\functionsWorker-0.7449586076122148.mjs"...
✨ Compiled Worker successfully

```

> b) use command: `wrangler pages cloudflare.pages/` , **it has no `Compiling worker` step** as the following output:
```
wrangler pages dev cloudflare.pages/
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose
▲ [WARNING] No compatibility_date was specified. Using today's date: 2023-06-14.

  Pass it in your terminal:
  `
  --compatibility-date=2023-06-14
  `
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more information.


No functions. Shimming...
 ⛅️ wrangler 3.1.0
------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote
⎔ Starting local server...
[mf:wrn] Unable to fetch the `Request.cf` object! Falling back to a default placeholder...
Error: getaddrinfo ENOTFOUND workers.cloudflare.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
[mf:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2023-05-18",
X [ERROR] Timed out waiting for authorization code, please try again.
```

I can run the server using `wrangler pages cloudflare.pages/`, but it only serves STATIC Pages, no functions.

Why the two ways so different ?

**Comment by penalosa** [comment]
Thanks for raising this, and apologies for the delay in getting back to you!
1. This should now be fixed, and was a brief regression when we released Wrangler v3
2. This is intended behaviour. `wrangler pages dev` must be run within your project, and can optionally be provided a folder of static assets as the first positional argument. See https://developers.cloudflare.com/workers/wrangler/commands/#dev-1 for more details
