### ISSUE TITLE
Convert Wrangler to Vitest

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/workers-sdk#3467]
Refactor Wrangler tests to use Vitest for a consistent and standardized test environment

The team has made the decision to adopt Vitest for several reasons:

- Improved performance: Vitest offers significantly faster testing speeds compared to Jest, particularly for larger projects.
- Enhanced developer experience: Vitest provides a better DX than Jest by offering features such as hot module reloading and automatic test discovery, making testing more efficient and enjoyable.
- Increased flexibility: Vitest offers greater flexibility compared to Jest, allowing for customization of the test runner to cater to specific project requirements.
- Simplified learning curve: Vitest has a simpler API compared to Jest, making it easier to learn and use for developers new to the testing ecosystem.
- Future-proofing: Vitest is built on the Vite framework, which is newer and more modern than Jest. By adopting Vitest, we ensure our testing infrastructure remains up to date and aligned with current industry practices.

To maintain consistency and establish a standardized test environment within the monorepo, I am in the process of converting Wrangler tests to utilize Vitest. This change will streamline our testing processes and ensure a cohesive approach across the codebase.

**Comment by spd-asia** [comment]
Vitest also has in-source tests just like Rust.. loving the new experience..

https://vitest.dev/guide/in-source.html

```js
// src/index.ts

// the implementation
export function add(...args: number[]) {
  return args.reduce((a, b) => a + b, 0)
}

// in-source test suites
if (import.meta.vitest) {
  const { it, expect } = import.meta.vitest
  it('add', () => {
    expect(add()).toBe(0)
    expect(add(1)).toBe(1)
    expect(add(1, 2, 3)).toBe(6)
  })
}
```

**Comment by JacobMGEvans** [comment]
There have been some serious setbacks with this, mainly due to the Jest mocking the migration to Vitest is pretty non-trivial. 

@penalosa @admah
