### ISSUE TITLE
🚀 Feature Request: Have the option to output Wrangler execution result to JSON

### ISSUE THREAD

**Issue by ofrogon** [cloudflare/workers-sdk#3470]
### Describe the solution

Hi,

When using Wrangler from CI it could be useful to have the output in a JSON format to simplify the command result interpretation.

For example, when calling `wrangler pages deploy`, having the option to output to JSON and be able to get the URL to the freshly deploy pages (versus having to extract the URL with a regex from all the command output) can be a nice to have.

**Comment by admah** [comment]
@ofrogon thanks for this suggestion. I think this is a good option to have for any sort of `deploy` command that Wrangler has.

**Comment by penalosa** [comment]
Closing in favour of https://github.com/cloudflare/workers-sdk/issues/2012
