### ISSUE TITLE
c3 doesn't tell people to change directory

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#3476]
### Which Cloudflare product(s) does this pertain to?

C3

### What version of `Wrangler` are you using?

C3 2.0.9

### What operating system are you using?

Windows

### Describe the Bug

After create an app with C3, you get output like this:

```
├  APPLICATION CREATED  Deploy your application with npm run deploy
│
│ Run the development server npm run dev
│ Deploy your application npm run deploy
│ Read the documentation https://developers.cloudflare.com/workers
│ Stuck? Join us at https://discord.gg/cloudflaredev
│
╰ See you again soon!
```

But you can't actually run any of those commands until you change directory, such as via `cd autumn-violet-70e6`.

Perhaps c3 should auto-change directory? Or tell people to change dir?

**Comment by admah** [comment]
Thanks @Cherry! Yes, this is something we should add to the messaging.
