### ISSUE TITLE
🚀 Feature Request:  Maybe it should allow user to choise other auth methods like token auth

### ISSUE THREAD

**Issue by ninsiu-com** [cloudflare/workers-sdk#3481]
### Describe the solution

Hi:

> Now wrangler deploy use OAuth , but the process is not stable. It usually fail in exchangeAuthCodeForAccessToken() process.  I think it should allow user to choise other auth methods like token auth. It's much stable than OAuth.

**Comment by penalosa** [comment]
You should be able to use the environment variable `CLOUDFLARE_API_TOKEN` to use an API token with Wrangler, rather than relying on OAuth. See https://developers.cloudflare.com/workers/wrangler/system-environment-variables/ for more details

**Comment by ninsiu-com** [comment]
> You should be able to use the environment variable `CLOUDFLARE_API_TOKEN` to use an API token with Wrangler, rather than relying on OAuth. See https://developers.cloudflare.com/workers/wrangler/system-environment-variables/ for more details

Thanks, But i've tried the .env file already, it still use OAuth:
```
E:\var\www\cloudflare.pages>ls -al
total 2
drwxrwxrwx   1 user     group           0 Jun 17 09:26 .
drwxrwxrwx   1 user     group           0 Jun 16 17:09 ..
-rw-rw-rw-   1 user     group         263 Jun 17 09:27 .env
-rw-rw-rw-   1 user     group         188 Jun 16 21:23 _routes.json
drwxrwxrwx   1 user     group           0 Jun 16 21:07 functions
drwxrwxrwx   1 user     group           0 Jun 16 15:45 node_modules
```

My .env file looks like:
```
E:\var\www\cloudflare.pages>cat .env
CLOUDFLARE_ACCOUNT_ID=3076b21e93a05b*****
CLOUDFLARE_API_TOKEN=pO479UmXrxEX6kxdy*****
CLOUDFLARE_EMAIL=*****
WRANGLER_SEND_METRICS=true
CLOUDFLARE_API_BASE_URL=https://api.cloudflare.com/client/v4
WRANGLER_LOG=debug
```

Then when I try to use  `wrangler login` or `wrangler pages deploy ./`, it still open the OAuth window:

```
E:\var\www\cloudflare.pages>wrangler login
 ⛅️ wrangler 3.1.0
------------------
Attempting to login via OAuth...
Opening a link in your default browser: https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=54d*****
```

How can I show the debug info of wrangler command to see if it really tries to load the .env file or just ignore it ?

**Comment by ninsiu-com** [comment]
Hi:

I've see the problem. **The key in .env file does not change anything. But the enviroment key changes.**

I've add console.info to cli.js, and see wrangler load the .env file. But it seems .env file does not change anything to wrangler:

```
E:\var\www\cloudflare.pages>wrangler pages deploy ./
loadDotEnv() .env undefined
{
  path: '.env',
  parsed: {
    CLOUDFLARE_ACCOUNT_ID: '3076b21e93a05ba*********',
    CLOUDFLARE_API_TOKEN: 'pO479UmXrxEX6kxdy9jb*********',
    CLOUDFLARE_EMAIL: 'z*********',
    WRANGLER_SEND_METRICS: 'true',
    CLOUDFLARE_API_BASE_URL: 'https://api.cloudflare.com/client/v4',
    WRANGLER_LOG: 'debug'
  }
}
Checking if domain has Access enabled: dash.cloudflare.com
Access switch not cached for: dash.cloudflare.com
```


> 1. WRANGLER_LOG=debug in .env file does not work

As you can see, .env file has WRANGLER_LOG set to debug, but it does not output the debug info. Thoes debug is displayed when I use `set WRANGLER_LOG=debug` in command line.

> 2. Tokens loaded, but not actived.

Token in .env file does not change the auth method, it still use OAuth.


> 3. `CLOUDFLARE_API_TOKEN` enviroment works

As mentioned in 2, If i use command line to set CLOUDFLARE_API_TOKEN variable, It WORKS! That's the problem.
