### ISSUE TITLE
🐛 BUG: wrangler 3.1.0 returns "No fetch handler" if the default export isn't a POJO

### ISSUE THREAD

**Issue by ItalyPaleAle** [cloudflare/workers-sdk#3487]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.0

### What operating system are you using?

Linux

### Describe the Bug

My worker's main entrypoint, which was working just fine with wrangler@2 and in the live site, is something like:

```js
const server = new Server({
    manifest,
    router,
})
export default server
```

Where the `Server` class contains an `async fetch(req, env, ctx)` method.

However, when running the code above using `wrangler dev` with Wrangler 3.1.0, it doesn't work and all pages show a "No fetch handler" error.

If I change `loader_module.ts` to add at the beginning:

```js
console.log("WORKER", worker, Object.keys(worker).join(" "))
```

I see in the console something like:

```
WORKER Object manifest router middleware
```

Essentially, it seems that it tried to get the properties I passed to the `Server` constructor, rather than using the `server` object itself.

Surprisingly, just changing the entrypoint to the below works just fine.

```js
const server = new Server({
  foo: 'bar'
})
export default {async fetch(request, env, ctx) {return server.fetch(request, env, ctx)}};
```

**Comment by KianNH** [comment]
This is a known issue - https://github.com/cloudflare/workerd/issues/699#issuecomment-1561335461

**Comment by penalosa** [comment]
To clarify, did this work in wrangler v2? Could you link a reproduction repo? Thanks!

**Comment by ItalyPaleAle** [comment]
@penalosa I can't share a repo yet, but at the high level this is the Server class:

```ts
export default class Server {
    private manifest: Record<string, string>
    private router: Router<Handler<any>>
    private init?: ServerInitFunction

    /**
     * Constructor
     */
    constructor({
        manifest,
        router,
        init,
    }: {
        manifest: Record<string, string>
        router: Router<Handler<any>>
        init?: ServerInitFunction
    }) {
        this.manifest = manifest
        this.router = router
        this.init = init
    }

    /** Fetch handler */
    async fetch(
        req: Request,
        env: AppEnv,
        parentContext: ExecutionContext
    ): Promise<Response> {
        // Handle here
    }
}
```

Then the server is instantiated with:

```ts
const server = new Server({
    manifest, router, init,
})
export default server
```

It works with Wrangler v2. I thought I remembered this working in CF Workers (the service), but I may be wrong - the app is still in development.

I found this issue while updating the project to Wrangler v3.

**Comment by penalosa** [comment]
Thanks for clarifying. This style of registering handlers isn't supported by the Workers runtime (see https://github.com/cloudflare/workerd/issues/699#issuecomment-1561335461 for more details). The workaround is to use something like the following:

```js
const server = new Server({
  foo: 'bar'
})
export default {
  async fetch(request, env, ctx) {
    return server.fetch(request, env, ctx)
  }
};
```
