### ISSUE TITLE
🐛 BUG: TRACE requests cause wrangler dev server to crash

### ISSUE THREAD

**Issue by smjcrane** [cloudflare/workers-sdk#3506]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.1

### What operating system are you using?

Windows

### Describe the Bug

When running `wrangler pages dev <dir>`, sending a TRACE request crashes the dev server. Instead, it should return an error such as 405 Method Not Allowed.

**Comment by CarmenPopoviciu** [comment]
hi @smjcrane , thank you for reporting this issue. Lot's has changed since you first reported this problem, so can you please confirm if this is still an issue you're experiencing?

**Comment by petebacondarwin** [comment]
Closing due to lack of response.
