### ISSUE TITLE
🐛 BUG: wrangler init (create cloudflare) `"Hello World" Worker` installs TS dependencies for JS

### ISSUE THREAD

**Issue by m-dre** [cloudflare/workers-sdk#3507]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.1

### What operating system are you using?

MacOS 13.4 (22F66)

### Describe the Bug

Running `wrangler init abcd`, or `npm create cloudflare abcd` selecting the Hello World Worker template, and choosing JavaScript ends up installing TypeScript dependencies.

This is that the package.json contains:
`{
  "name": "abcd",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "deploy": "wrangler publish",
    "start": "wrangler dev"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20230419.0",
    "typescript": "^5.0.4",
    "wrangler": "^3.0.0"
  }
}`

**Comment by s0urfruit** [comment]
I see you did some more investigative work than me, but the issues are practically identical - dunno if anyone wants to close mine: 

https://github.com/cloudflare/workers-sdk/issues/3548

**Comment by RamIdeas** [comment]
It seems this was fixed in #3609 which closed #3548 and, as you mentioned, this seems like a duplicate issue
