### ISSUE TITLE
🐛 BUG: `wrangler dev` doesn't change the headers in the same way as workers do

### ISSUE THREAD

**Issue by ValeriyMaslenikov** [cloudflare/workers-sdk#3513]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

3.1.1

### What operating system are you using?

Mac

### Describe the Bug

Here it's the code of the worker:
```ts
// Export a default object containing event handlers
export default {
	// The fetch handler is invoked when this worker receives a HTTP(S) request
	// and should return a Response (optionally wrapped in a Promise)
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const body = request.body ? await request.text() : '{}';

		const response =  await fetch('http://localhost:8089/some-route', {
			method: 'POST',
			headers: new Headers(request.headers),
			body,
			redirect: 'follow',
		});

		console.log(await response.json());

		return new Response('Hello world!');
	},
};
```

According to the [documentation](https://developers.cloudflare.com/fundamentals/get-started/reference/http-request-headers/#accept-encoding) workers overwrite the accept encoding in the request, where the `wrangler dev` doesn't.

WIth the following code, when worker is triggered from Postman in the `request.headers` we can see the `Accept-Encoding` header with original header (not overwritten). When you send this request from Postman it will be `gzip, deflate, br`.

And looks like `fetch` doesn't support other encodings except `gzip`, meaning that in case of origin server using something else (e.g. Brotli) – then in the console we can see the following error:
```
error SyntaxError: Unexpected token '
                                     ', "
                                         F������"... is not valid JSON
    at async Object.fetch (worker.js:65:24)
    at async jsonError (worker.js:87:12) {
  stack: SyntaxError: Unexpected token '
                                        ', "
                                            F������"...…s:65:24)
    at async jsonError (worker.js:87:12),
  message: Unexpected token '
                             ', "
                                 F������"... is not valid JSON
}
```

**Comment by penalosa** [comment]
In Wrangler v3, `wrangler dev` runs your Worker in a local simulator of the workers environment—https://github.com/cloudflare/miniflare. Unfortunately that means that you won't see all of the behaviour of the rest of the (non-workers) Cloudflare environment locally (small differences in headers is one aspect of that). To test your Worker against the rest of the Cloudflare environment, you can start a remote preview with `wrangler dev --remote`.

**Comment by xdivby0** [comment]
I know this is closed, but I spent several hours debugging why my code isn't working when upgrading from wrangler 2 to 3. It should be marked in the migration guide that the fetch function doesn't work exactly the same. Something  like "when you are seeing unprintable ��� characters after migrating, it's most likely due to you having specified an  `Accept-Encoding` header that is not supported by the workerd or something.

**Comment by xdivby0** [comment]
I have reworded your very helpful message here and added it to where it would have helped me, @penalosa. I never made a PR to the docs, do you think this is a helpful addition: https://github.com/cloudflare/cloudflare-docs/pull/11966?

**Comment by fhanau** [comment]
Added a comment on the linked pull request – brotli support is currently enabled by default in local development.
