### ISSUE TITLE
🐛 BUG: Default 'npm create cloudflare' workflow for next.js leads to nodejs_compat error page

### ISSUE THREAD

**Issue by jmadruga-cf** [cloudflare/workers-sdk#3528]
### Which Cloudflare product(s) does this pertain to?

C3

### What version of `Wrangler` are you using?

3.1.1

### What operating system are you using?

Mac

### Describe the Bug

If I create a next.js app using C3 and deploy it on pages, I get an error about not having the nodejs_compat flag set when I visit the site.  It looks like I've deployed it successfully and it's unclear how to fix the issue.  It's a bad first experience for someone trying to deploy.

The solution is outlined in https://developers.cloudflare.com/workers/platform/nodejs-compatibility/, but even then it's unclear what I should do.  There is no wrangler.toml, so the easiest method to fix it is by navigating to the dashboard.  We should be able to detect if the flag is not set when working through the C3 workflow and guide them to setting the flag, or just set it for them since we know it's a new project (they did a create) and it won't work without it.

**Comment by petebacondarwin** [comment]
We need to fix up the docs to use `@latest` - see https://developers.cloudflare.com/pages/get-started/c3/
cc @admah

**Comment by jmadruga-cf** [comment]
Latest did fix the issue.  Thanks @petebacondarwin .

**Comment by petebacondarwin** [comment]
Cool. Closing this for now.
