### ISSUE TITLE
🐛 BUG: quick edit doesn't show my code?

### ISSUE THREAD

**Issue by punkeel** [cloudflare/workers-sdk#3532]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

latest

### What operating system are you using?

N/A

### Describe the Bug

Using Quick Edit (dashboard) on a script that was deployed with wrangler ... doesn't show the original worker script?

Step 1: deploy with wrangler:
```
// File name is src/worker.js
export default {
	async fetch(request, env, ctx) {
                const url = new URL(request.url);
		return await fetch('http://abc.xyz/');
	},
};
```

Step 2. edit with quick edit. The script is now:
```
// src/worker.js
var worker_default = {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    return await fetch("http://abc.xyz/");
  }
};
export {
  worker_default as default
};
//# sourceMappingURL=worker.js.map
```

As a user, I expect Quick Edit to show me my script, not a minified/prettified version?

**Comment by penalosa** [comment]
Thanks for reporting this! Wrangler will bundle your code with esbuild before uploading, which will mean that the code visible in Quick Edit will reflect the output of that bundling process. 

To ensure Wrangler doesn't bundle your code, you can pass the `--no-bundle` argument to `wrangler dev` or `wrangler publish`. This will mean that the Quick Edit exactly reflects your original source.

However, this has a number of trade-offs, including the inability to import npm packages (unless you also have a custom build set up to pre-bundle those) or use some features like D1 or assets.
