### ISSUE TITLE
🐛 BUG: The `constellation` variable is not been recognised by worker.ts

### ISSUE THREAD

**Issue by navaneeth-automatad** [cloudflare/workers-sdk#3535]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.1

### What operating system are you using?

Mac

### Describe the Bug

The constellation variable is not been recognised by env even if the variables are present. Also, there it would be helpful if it has typescript support (this is not a bug)

Thanks

(This issue is for `constellation`  not for `wrangler` but It had no options)

**Comment by jspspike** [comment]
Could you provide your `wrangler.toml` or minimal reproducible example?

**Comment by navaneeth-automatad** [comment]
wrangler.toml
`constellation = [
    {binding = 'REG', project_id = 'PROJECT_ID'},
]`

env defination
(since the latest version of constellation has no typescript support.
```ts
interface Env {
	REG: <NoT_SURE_WHAT_TO_GIVE>
}
```

worker.ts
```ts
import { Tensor, run } from "@cloudflare/constellation";
export default {
		const url = new URL(request.url);
		if (url.pathname.startsWith('/13model')){
			const content = await request.json();

			let input = content.data.split(',')
			const tensorInput = new Tensor("float32", [1, 8], input);
			const output = await run(
				env.REG,
				"MODEL_ID",
				tensorInput
			);
			return new Response(JSON.stringify(output));
              }
	},
};
```

the env.reg is undefined if I give `any`.


Hope it helps to debug. thanks

**Comment by jspspike** [comment]
I'm not too familiar with the constellation product but it looks like you haven't defined a fetch handler. As shown in [the constellation docs](https://developers.cloudflare.com/constellation/get-started/first-constellation-worker/) you should have your logic in a function `async fetch(request: Request, env: Env): Promise<Response> {}` where `env` is defined as a parameter

**Comment by navaneeth-automatad** [comment]
ok, btw the similar code works for d1 , kv, etc but not for `constellation`.
Have a question, when can we expect the next release for  `constellation` npm package?

**Comment by jspspike** [comment]
I'm not sure myself, but you might be able to get in touch with some constellation developers [on discord](https://discord.com/invite/cloudflaredev)
