### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by jbasdf** [cloudflare/workers-sdk#3538]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.1

### What operating system are you using?

Mac

### Describe the Bug

When I attempt to tail the logs I get the following error:

∫ wrangler tail --format=pretty
 ⛅️ wrangler 3.1.1
------------------

✘ [ERROR] A request to the Cloudflare API (/accounts/c992a4373fcc82472ad0645d87fdc502/workers/scripts/atomic-lti-worker/bindings) failed.

  workers.api.error.script_not_found [code: 10007]

**Comment by penalosa** [comment]
Have you deployed your worker to Cloudflare? `wrangler tail` will only work after a deploy. During development, `wrangler dev` should print out your worker logs.
I'm going to close this for now, but feel free to comment with more details and we can investigate further.

**Comment by jbasdf** [comment]
I have multiple accounts and wrangler was confused about which one I was using. I had deployed the worker to the wrong account. I then logged into the other account and tried to run tail. When that didn't work I tried to deploy the worker which failed. I went into the original account and deleted the worker. Then I did a new deploy in the correct account and it seems to work.
