### ISSUE TITLE
🐛 BUG: req.url relative to `routes` in wrangler config, even when developing locally

### ISSUE THREAD

**Issue by jbmanning** [cloudflare/workers-sdk#3563]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.2

### What operating system are you using?

Mac

### Describe the Bug

I noticed today that req.url seems to be defined to be relative to the routes in your wrangler config, even when you are developing locally. 

This has issues when developing locally with libraries like next-auth, since they use the req.url to generate the callback urls. 

![image](https://github.com/cloudflare/workers-sdk/assets/11013297/10e5c8c3-be26-498d-9ebb-b07160d4d28d)

## Workaround
I have currently bypassed the issue with the following code, but a correct solution would be nice:
```typescript
export default {
    async fetch(_req) {
        const _url = new URL(_req.url)
        _url.host = _req.headers.get('host')
        const req = new Request(_url, _req)

        // ...
    }
}

**Comment by 1000hz** [comment]
You can override the host that gets set in `req.url` by adding the following to your `wrangler.toml`:
```
[dev]
host = "127.0.0.1:8787"
```
(https://developers.cloudflare.com/workers/wrangler/configuration/#local-development-settings)

It's worth us reconsidering whether we should automatically default `req.url` to your route host by default when running in local mode.
