### ISSUE TITLE
🐛 BUG: Email workers no longer being deployed

### ISSUE THREAD

**Issue by carlos-alberto** [cloudflare/workers-sdk#3568]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

3.1.2

### What operating system are you using?

Mac

### Describe the Bug

The `email` handler is no longer being exported when deploying a worker using wrangler in both 3.1.1 and 3.1.2.

[This commit](https://github.com/cloudflare/workers-sdk/commit/b34956aa038e240bb49b71aa5d18cc96d740b148) seems to be the culprit:

![image](https://github.com/cloudflare/workers-sdk/assets/1853495/c88a2df4-a83b-43a4-a46f-b6858c9cd7e4)

**Comment by Yihao-G** [comment]
It seems 3.1.0 was the last working version. 3.1.1 start to have this issue
