### ISSUE TITLE
🐛 BUG: `migrations` is neither inheritable nor non-inheritable

### ISSUE THREAD

**Issue by QiroNT** [cloudflare/workers-sdk#3571]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.2

### What operating system are you using?

Mac

### Describe the Bug

I'll assign this as a bug since it's likely an oversight.

As the doc stated, `migrations` in `wrangler.toml` is neither inheritable nor non-inheritable.
This creates a situation where I can define a new durable object in an environment, but can't upload it because I have no way to define new migrations.

Defining it on the top level works, `--new-class` should also work but it's not supported any more.

**Comment by petebacondarwin** [comment]
Related to #729

**Comment by petebacondarwin** [comment]
Closing as a duplicate of #729, where we will track the implementation.
