### ISSUE TITLE
🐛 BUG: missleeding documentation?

### ISSUE THREAD

**Issue by peernohell** [cloudflare/workers-sdk#3572]
### Which Cloudflare product(s) does this pertain to?

Workers/Other

### What version of `Wrangler` are you using?

0.0.0

### What operating system are you using?

MacOS

### Describe the Bug

Documentation instruct us to du `npx create cloudflare@1 ...`
But when I run it I have the following error `could not determine executable to run`.

After reading issues I found in #3540 that they use `npm` and not `npx`. 

When I run the commande with `npm` it works.
It would be create to update the documentation.

**Comment by 1000hz** [comment]
Can you link to the documentation you're referring to?

**Comment by peernohell** [comment]
Sorry for mithing this.
It's on the readme page of template page.

https://github.com/cloudflare/workers-sdk/tree/main/templates
