### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Laurry-gee** [cloudflare/workers-sdk#3584]
### Which Cloudflare product(s) does this pertain to?

C3, D1, KV, Pages, Pub/Sub, Queues, R2, Workers for Platforms, Workers/Other, Wrangler

### What version of `Wrangler` are you using?

0.0.0

### What operating system are you using?

Mac

### Describe the Bug

/ #

**Comment by penalosa** [comment]
I'm going to close this for now, but feel free to add more details and we can investigate your issue
