### ISSUE TITLE
Provide standalone binary download

### ISSUE THREAD

**Issue by datapolitical** [cloudflare/workers-sdk#36]
Is it possible to install this with cargo?

**Comment by threepointone** [comment]
Perhaps not cargo, but we have been thinking of having a plain binary download. Could you explain your usecase?

**Comment by datapolitical** [comment]
I don’t like using node. It’s complicated, I don’t fully understand it, and this is the only reason I have to use it on my project.

**Comment by Kronifer** [comment]
Hi there, would this be up for grabs?

**Comment by penalosa** [comment]
I'm going to close this for now—we're not likely to do it anytime soon, and it's at odds with the current development focus of Wrangler. Additionally, with the recent inclusion of the open source `workerd` in the Wrangler package, the download size of a standalone binary would likely be prohibitive
