### ISSUE TITLE
🐛 BUG: Spurious fetch failures with unstable_dev worker with an async test

### ISSUE THREAD

**Issue by ravi-signal** [cloudflare/workers-sdk#3607]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.2.0

### What operating system are you using?

Mac

### Describe the Bug

I have some tests written with `unstable_dev`. When I upgraded from wrangler2 to wrangler3, I started seeing some flaky failures where a fetch would fail with some communication failure, usually:

```
Serialized Error: {
  "code": "EPIPE",
  "errno": -32,
  "syscall": "write",
}
```

or 

```
Serialized Error: {
  "code": "ECONNRESET",
  "errno": -54,
  "syscall": "read",
}
```

With workerd logging at `debug` level I don't see anything to indicate why this happens.

I minimized the test case down to reproduce with a worker that just immediately returns a response and does nothing else. 

The worker:
```javascript
export default {
    async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
        try {
            return new Response('not found', {status: 404});
        } catch (e) {
            console.error(`worker error: ${e}`);
            throw e;
        }
    }
};
```

The test makes a request with a body (otherwise I don't see this). If I `await` an async sleep (or seemingly any `await`ed operations, originally was hitting this with an async webcrypto call in my test), the fetch fails sometimes. Without the `await`ed op the fetch never fails:

```javascript
describe('test', async () => {
    let worker: UnstableDevWorker;

    beforeAll(async () => {
        worker = await unstable_dev('src/index.ts', {
            experimental: {disableExperimentalWarning: true},
            // logLevel: 'debug'
        });
    });

    afterAll(async () => {
        await worker.stop();
    });

    it('test', async () => {
        await new Promise<void>(resolve => setTimeout(() => resolve(), 1)) // comment this out and the test always passes
        const resp = await worker.fetch('', {
            method: 'PUT',
            body: 'bar'
        });
        expect(resp.status).toBe(404);
    }, {repeats: 1000});
});
```

I've included the full code to reproduce here: https://github.com/ravi-signal/workerd-test-issue

On my machine it can sometimes takes a couple runs (each with 1K iterations) to hit the error, but not much more than that. I am running an M1 mac, but the same code reproduces the issue on a linux machine I tried.

Thanks!

**Comment by admah** [comment]
@ravi-signal thank you for filing this issue. Are you still running into this? We are working to stabilize this API currently, and will also take a look at what could be causing this.

**Comment by ravi-signal** [comment]
Thanks for checking, I am indeed still running into this. I can confirm that https://github.com/ravi-signal/workerd-test-issue still reproduces the issue with the latest version of wrangler (3.10.1)

**Comment by admah** [comment]
Ok. Thank you for letting us know!

**Comment by penalosa** [comment]
This should be addressed by the stabilisation of the dev server we've recently done. I'm going to close this for now, since I've tested this case using the `unstable_startWorker()` API and the issue no longer seems to exhibit:

```ts
import {it, expect, beforeAll, afterAll, describe} from 'vitest';
import {unstable_startWorker} from 'wrangler';

describe('test', async () => {
    let worker: any;

    beforeAll(async () => {
        worker = await unstable_startWorker({ entrypoint: 'src/index.ts' });
    });

    afterAll(async () => {
        await worker.dispose();
    });

    it('test', async () => {
        await new Promise<void>(resolve => setTimeout(() => resolve(), 1)) // comment this out and the test always passes
        const resp = await worker.fetch('http://example.com/', {
            method: 'PUT',
            body: 'bar'
        });
        expect(resp.status).toBe(404);
    }, {repeats: 1000});
});
```

@ravi-signal feel free to open a new issue if you're still running into problems
