### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Boffice** [cloudflare/workers-sdk#3618]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

wrangler2

### What version of Node are you using?

v18.16.0

### What operating system are you using?

Fedora 38

### Describe the Bug

Installed Wrangler via `yarn global add wrangler`

```
yarn global v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "wrangler@3.2.0" with binaries:
      - wrangler
      - wrangler2
```

`wrangler --version` returns error:

bash: wrangler: command not found...

**Comment by JacobMGEvans** [comment]
Let's see if this helps:
This will output the path to the Wrangler binary.

Open your .bashrc or .zshrc file. This file is located in your home directory.

Add the following line to your .bashrc or .zshrc file:

```
export PATH=$PATH:`which wrangler`
Save your .bashrc or .zshrc file.
```

Reload your .bashrc or .zshrc file by running the following command:
`source ~/.bashrc`

Save your file and run `source ~/.bashrc` to reload it. Now you should be able to run wrangler without any errors.

To test that the wrangler command is working, run wrangler --version.

**Comment by lrapoport-cf** [comment]
hi @Boffice :) did @JacobMGEvans 's recommendation above solve your issue?

**Comment by admah** [comment]
Closing this. If it continues to be an issue, please reopen.
