### ISSUE TITLE
🐛 BUG: wrangler pages dev doesn't close database on exit

### ISSUE THREAD

**Issue by ma11hew28** [cloudflare/workers-sdk#3620]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3.2.0 [Wrangler]

### What version of Node are you using?

18.16.1

### What operating system are you using?

macOS

#### Summary

The local Pages server doesn't properly close the local D1 database before shutting down.

#### Steps to reproduce

1. Create a Pages project.
2. Create a D1 database.
3. Bind the D1 database to your Pages project with the variable name `DB`.
4. Add this Functions file at `functions/users.js`:

    ```javascript
    export async function onRequest(context) {
      const ps = context.env.DB.prepare('SELECT * FROM users')
      const data = await ps.first()
      return Response.json(data)
    }
    ```

5. Run the Pages app locally:

    ```shell
    wrangler pages dev public --d1=DB
    ```

6. Go to http://127.0.0.1:8788/users in your browser.
7. Confirm that you get "Error: SqliteError: no such table: users".
8. Open and properly close the local database:

    ```bash
    sqlite3 .wrangler/state/v3/d1/DB/db.sqlite .tables
    ```

9. Add this file at `schema.sql`:

    ```sql
    DROP TABLE IF EXISTS users;
    CREATE TABLE users (id bigserial PRIMARY KEY);
    INSERT INTO users VALUES (1), (2), (3);
    ```

10. Initialize the local database:

    ```shell
    sqlite3 .wrangler/state/v3/d1/DB/db.sqlite < schema.sql
    ```

11. Repeat steps 5 and 6 above.
12. Confirm that you get `{"id":1}`.
13. Shut down the Pages app from the Terminal by pressing "x".

#### Observed behavior

After steps 7 and 13 above, I see these files in `.wrangler/state/v3/d1/DB`:

- `db.sqlite`
- `db.sqlite-shm`
- `db.sqlite-wal`

#### Expected behavior

After steps 7 and 13 above, `.wrangler/state/v3/d1/DB` should only contain this file:

- `db.sqlite`

### Related issues

- #3316

**Comment by CarmenPopoviciu** [comment]
Hi @ma11hew28, thank you for reporting this issue and providing such a detailed repro <3. Since the issue was reported quite a while back, I wanted to first check if this is still relevant with the latest wrangler version of today

**Comment by ma11hew28** [comment]
Hi @CarmenPopoviciu, sorry for the delayed reply. You're welcome. I just tried out these steps with Wrangler 3.52.0 and didn't notice this issue anymore. It looks like now the local database gets created in *.wrangler/state/v3/d1/miniflare-D1DatabaseObject* and the files in that folder that end in *.sqlite-shm* and *.sqlite-wal* are removed after shutting down the Pages app from the Terminal by pressing "x".

**Comment by CarmenPopoviciu** [comment]
I'm so happy to hear! Thank you so much for getting back to us on this. I'll go ahead and close this then, but pls feel free to re-open if you run into the issue again <3
