### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Frederik-Baetens** [cloudflare/workers-sdk#3624]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

Wrangler 3.1.1

### What version of Node are you using?

v18.16.0

### What operating system are you using?

Debian Linux

### Describe the Bug

The following route is not valid in wrangler.toml, while it is valid to configure it in the dashboard

```
[[routes]]
zone_id = "xxxxxxxxxxxx"
pattern = "*/*"
```

Gives an error: `✘ [ERROR] Invalid URL`

![Screenshot from 2023-07-14 21-16-56](https://github.com/cloudflare/workers-sdk/assets/18269095/b1f5cae3-3c87-41ca-9be2-546590b8c2a2)

This working is important to me since it's required by certain SSL4SAAS configurations: https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/start/advanced-settings/worker-as-origin

### Please provide a link to a minimal reproduction

Just wrangler init, and putting that route in the wrangler.toml should do it.

**Comment by penalosa** [comment]
Closing in favour of https://github.com/cloudflare/workers-sdk/issues/2953
