### ISSUE TITLE
🐛 BUG: creating project from template fails with EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by mxschumacher** [cloudflare/workers-sdk#3642]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

3.3.0

### What version of Node are you using?

18.16.1

### What operating system are you using?

Linux (Fedora 38)

### Describe the Bug

Going through the documentation located [here](https://github.com/cloudflare/workers-sdk/tree/main/templates#usage) I executed the following command:

> npm create cloudflare@1 test worker-d1-api

which triggered: **Error: EXDEV: cross-device link not permitted**

You can find a test case triggering this error message here: https://github.com/cloudflare/workers-sdk/blob/f7ae0ead2a48453845fcdbe3366b2db63d93b008/packages/wrangler/src/__tests__/generate.test.ts#L229

### Please provide any relevant error logs

npm create cloudflare@1 cf-d1-api worker-d1-api                                                             (code) 01:12:01

Error: EXDEV: cross-device link not permitted, rename '/tmp/880f3e5237c9b-3d1e918115827/worker-d1-api' -> '/home/mxschumacher/code/cf-d1-api'

npm ERR! code 1
npm ERR! path /home/mxschumacher/code
npm ERR! command failed
npm ERR! command sh -c create-cloudflare cf-d1-api worker-d1-api

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mxschumacher/.npm/_logs/2023-07-19T23_12_25_510Z-debug-0.log

**Comment by admah** [comment]
Hello @mxschumacher 👋  Thank you for filing this issue. I'm not able to replicate this on my machine so I assume it may be a Linux/create-cloudflare v1 issue. While the latest C3 does not support arbitrary templates like v1, you can perform the same action with `npx wrangler generate cf-d1-api worker-d1-api`. I'm going to close this as we do not currently support create-cloudflare v1 and will not fix issues related to it.
