### ISSUE TITLE
🚀 Feature Request: Wrangler CLI, make R2 bucket public

### ISSUE THREAD

**Issue by Swimburger** [cloudflare/workers-sdk#3656]
### Describe the solution

AFAIK, you can only make R2 buckets public via the CF app, but I'd like to use the CLI for as much as possible.
How can I do this using the CLI, or can we add that capability?

**Comment by lrapoport-cf** [comment]
hey @jonesphillip , can your team please take a look at this?

**Comment by RamIdeas** [comment]
hey @jonesphillip, just a reminder about this ticket

**Comment by jonesphillip** [comment]
@Swimburger sorry for the late reply. This is not currently possible in Wrangler, but we're planning to get API documented and get functionality in Wrangler in the near future. Will update this issue when it's done.

**Comment by jonesphillip** [comment]
This is possible by using the [`r2 bucket domain`](https://developers.cloudflare.com/workers/wrangler/commands/#domain-add) or [`r2 bucket dev-url`](https://developers.cloudflare.com/workers/wrangler/commands/#dev-url-enable) commands. Closing this feature request out.
