### ISSUE TITLE
🐛 BUG: Wrangler routes don't work with Cloudflare for SaaS Custom Hostnames

### ISSUE THREAD

**Issue by kleinmp** [cloudflare/workers-sdk#3662]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.3.0

### What version of Node are you using?

18.12.1

### What operating system are you using?

Mac

### Describe the Bug

When adding a route on a domain that is setup as a [custom hostname](https://developers.cloudflare.com/ssl/reference/migration-guides/digicert-update/custom-hostname-certificates/#custom-hostnames), I get the following error:

`✘ [ERROR] Could not find zone for [www.example-dev.com]`

The custom hostname in question is setup on the zone noted in the wrangler.toml. The route can still be added in the Cloudflare interface, but wrangler won't allow it.

Note that it does work if there is a zone in the same account that matches the top level domain of the route trying to be added. (e.g. A route can be added for test.example.com on any zone if there is an example.com zone).

```
name = "test-worker"
main = "src/worker.ts"
compatibility_date = "2023-07-02"
usage_model = "bundled"
env = { }

# This will throw error if www.example-dev.com is setup as a custom hostname unless there is a zone called www.example-dev.com or example-dev.com on the same account.
[[routes]]
pattern = "www.example-dev.com/some-path"
zone_name = "dev.example.com"
```

**Comment by romeupalos** [comment]
We are also interested in this fix for this issue.
Today we had a disruption in production since the custom hostname cannot be left as a route in the `wrangler.toml` file.
A known work-around is to use `*/*`, however it cannot be used by all implementations, e.g. maybe different domains are handled by different workers?
