### ISSUE TITLE
🐛 BUG: Wrangler crashes when running `pages dev` if functions contain invalid syntax

### ISSUE THREAD

**Issue by davwheat** [cloudflare/workers-sdk#3663]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler core

### What version(s) of the tool(s) are you using?

Wrangler 3.3.0

### What version of Node are you using?

18.17.0

### What operating system are you using?

WSL (Ubuntu 22.04)

### Describe the Bug

When running `wrangler pages dev [...]`, Typescript functions get auto-transpiled as part of the dev watcher process.

If the TS file contains invalid syntax, the build errors as expected.

When this happens, however, the dev server itself appears to crash and require a restart. I would not expect this. Furthermore, the dev server doesn't shut down cleanly from this crash, instead leaving the old HTTP server live on `:8788` (and proxy/proxy port if appropriate), requiring the process to be manually killed to restart the dev server.

### Please provide any relevant error logs

![image](https://github.com/cloudflare/workers-sdk/assets/7406822/9b69329a-a7ba-4a24-acfb-0c3969b67e80)
![image](https://github.com/cloudflare/workers-sdk/assets/7406822/598bf7f2-1675-46df-88b2-00f7772a2cb6)

**Comment by JacksonKearl** [comment]
This has been driving me batty for months now... made a PR to fix it.
