### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by shellsperCloud1** [cloudflare/workers-sdk#3666]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms

### What version(s) of the tool(s) are you using?

wrangler 2.0 

### What version of Node are you using?

3.1.0

### What operating system are you using?

windows

### Describe the Bug

[influxdb-client-js-1.33.2.zip 12.zip](https://github.com/cloudflare/workers-sdk/files/12146959/influxdb-client-js-1.33.2.zip.12.zip)

### Please provide any relevant error logs

[drive1 (1).txt](https://github.com/cloudflare/workers-sdk/files/12146953/drive1.1.txt)

**Comment by penalosa** [comment]
Hi @shellsperCloud1 👋 Could you clarify what specific issue with Wrangler you're running into?

**Comment by RamIdeas** [comment]
We're going to close this issue as we haven't heard back from you. Please feel free to reopen if you're still experiencing the bug and can clarify the specific issue with Wrangler you're running into
