### ISSUE TITLE
🐛 BUG: `wrangler deploy` looks up library module tsconfig instead of package.json

### ISSUE THREAD

**Issue by tsteckenborn** [cloudflare/workers-sdk#3673]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.3.0 [Wrangler]

### What version of Node are you using?

18.16.1

### What operating system are you using?

Mac

### Describe the Bug

Deployment with `wrangler deploy` leads to the issue:

![image](https://github.com/cloudflare/workers-sdk/assets/50519619/45b01b9b-72a8-42a3-93bc-3e0baa5b4de7)

1. Const Parameters should be valid since TypeScript 5.0 (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters)
2. That is lib code, deploying and compiling app code should not ingest the TS files from lib it should ingest the compiled esm modules

Removing the tsconfig files from the libraries node module folder enables deployment.

### Please provide any relevant error logs

```
 ➜ wrangler deploy
 ⛅️ wrangler 3.3.0
------------------

✘ [ERROR] Expected identifier but found "const"

    ../../node_modules/.pnpm/@effect+data@0.16.1/node_modules/@effect/data/src/Option.ts:769:19:
      769 │ export const all: <const I extends Iterable<Option<any>> | Record...
          ╵                    ~~~~~


✘ [ERROR] Build failed with 1 error:

  ../../node_modules/.pnpm/@effect+data@0.16.1/node_modules/@effect/data/src/Option.ts:769:19:
  ERROR: Expected identifier but found "const"
```

**Comment by penalosa** [comment]
Thanks for reporting this! Wrangler uses esbuild `0.17.19` to build your worker, which doesn't yet support const parameters. Upgrading esbuild is tracked in https://github.com/cloudflare/workers-sdk/issues/3962, but in the meantime the best solution for using TS 5 syntax is to run `tsc` in a [Custom Build](https://developers.cloudflare.com/workers/wrangler/custom-builds/)
