### ISSUE TITLE
🐛 BUG: Local R2 .put() hangs while the put operation seems to succeed

### ISSUE THREAD

**Issue by DominikBB** [cloudflare/workers-sdk#3688]
### Which Cloudflare product(s) does this pertain to?

R2

### What version(s) of the tool(s) are you using?

3.3.0 [wrangler]

### What version of Node are you using?

20.4.0

### What operating system are you using?

WSL Ubuntu 20.04.02 LTS

### Describe the Bug

The Bucket is successfully bound to the worker as evident in the CLI upon running `npx wrangler@3 dev`.

When a fetch handler comes to the line:
`await env.MAPPER_BUCKET.put("test", "test");`

The execution hangs, and subsequently the request times out.

I can see that the file is actually successfully put into a .wrangler/r2... local file.

No error logs are reported in the CLI or anywhere evident.

**Comment by robbertvanginkel** [comment]
This seems to be the same as https://github.com/cloudflare/workers-sdk/issues/3626, which seems to be caused by a node issue.

**Comment by Zerebokep** [comment]
I can confirm that, downgrading to node:20.2 fixes the issue.
