### ISSUE TITLE
🐛 BUG: `--var` should accept non-string values

### ISSUE THREAD

**Issue by huw** [cloudflare/workers-sdk#3689]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.4.0 [Wrangler]

### What version of Node are you using?

20.4.0

### What operating system are you using?

Ubuntu 22.04 (GitHub Codespaces)

### Describe the Bug

Sometimes I want to override behaviour on my Worker when developing locally. For this purpose, I will pass `wrangler dev --var FEATURE_FLAG:false` (for example). Although `wrangler.toml` and the Dashboard both support non-string variables, [`--var` parses everything as a string](https://developers.cloudflare.com/workers/wrangler/commands/#dev), meaning that I can’t override these variables locally. The workaround is either to create a new environment for every combination of variables I might want (infeasible) or to only use string variables (brittle).

It does seem like the behaviour around `wrangler.toml` has changed, since I found cloudflare/wrangler-legacy#1259 from a while ago, and in my own code I was writing `FEATURE_FLAG === “true”` to convert the string values to booleans. If this is intentional, then we should also update `--var` to match this. Otherwise I am unable to update my variables on a per-run basis.

I haven’t checked with `--define`, but I assume the behaviour is currently the same and should probably also be amended for consistency.

**Comment by penalosa** [comment]
Thanks for raising this! Unfortunately this is probably not something we can support when calling Wrangler from the command line (although as you mention this is supported from with `wrangler.toml`). When Wrangler receives the flags that are passed on the command line, there's no way to distinguish between the string `"false"` and the boolean value `false`. Using string-valued vars is probably the best approach going forward.
