### ISSUE TITLE
🐛 BUG: yoga-layout dependency causing cleanup scripts to never run and ports be retained unwantedly

### ISSUE THREAD

**Issue by JacksonKearl** [cloudflare/workers-sdk#3697]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.4.0

### What version of Node are you using?

v18.14.2

### What operating system are you using?

MacOS

### Describe the Bug

Many issues document ports being left open on crashes (#2445, #3378, #3640, #3663, #3696). Some of these are fixed by not crashing in the specific circumstances documented (#3695), but really the ports shouldn't be left open even when a crash does occur. Investigating this, I see that attempts are made in https://github.com/cloudflare/workers-sdk/blob/11d0c0905562573bc92aee9bfee6b3c16a125016/packages/wrangler/src/pages/dev.ts#L639-L646 to clean up on exit, however these are never actually invoked during crashes because the yoga-layout dependency installs its own handlers that terminate the process immediately on all unhandled rejections and uncaught exceptions:

```
      process.on("uncaughtException", function (a) {
        throw a
      })
      process.on("unhandledRejection", function (a) {
        throw a
      })
```

I do not know why yoga-layout would do this, as it prevents any graceful error handling from running. I see you vendor your own version of it, would you consider removing those handlers? 

### Please provide a link to a minimal reproduction

Observe here how the `uncaughtException` and `unhandledRejection` handlers prevent CLEANUP from running:
```ts
import http from "http"

const CLEANUP = (reason) => () => {
  console.log(`cleaning up... (${reason})`)
  process.exit(0)
}

process.on("exit", CLEANUP("exit"))
process.on("SIGINT", CLEANUP("sigint"))
process.on("SIGTERM", CLEANUP("sigterm"))

process.on("uncaughtException", function (a) {
  console.log("uncaughtException") 
  throw a
})
process.on("unhandledRejection", function (a) {
  console.log("unhandledRejection")
  throw a
})

http
  .createServer((req, res) => {
    console.log("URL:", req.url)
    if (req.url === "/error") {
      throw Error()
    }
    if (req.url === "/reject") {
      new Promise((c, e) => e())
    }
    res.end()
  })
  .listen(8080)

```

**Comment by JacksonKearl** [comment]
Well this is odd. I really have no clue what those handlers are doing in `yoga`. When I download the package from NPM they are present (only in the compiled output), but when I build from scratch they're gone. I haven't seen anything in the issues regarding them being removed.

**Comment by JacksonKearl** [comment]
Looks like the handler are actually added by emscripten, targeting old versions of Node where rejected promises did not cause the process to exit. Building yoga with a newer emscripten/Node will not include there handlers, and there's some more info about other workarounds here: https://github.com/emscripten-core/emscripten/issues?q=is%3Aissue+uncaughtException+

**Comment by petebacondarwin** [comment]
Hi @JacksonKearl - thanks for reporting this and then digging into it further. I see, as you say, that emscripten is only adding these handlers for node < 15. Wrangler requires node v16+ so this should not be an issue any further.
