### ISSUE TITLE
🐛 BUG: Possible new dependancies not documented

### ISSUE THREAD

**Issue by mrbm** [cloudflare/workers-sdk#3708]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

2.4

### What version of Node are you using?

tested v18 and v20

### What operating system are you using?

OSX Mac M1 - 13.5 (22G74)

### Describe the Bug

In previous iteration updates of V2 I had no problem updating wrangler running the standard command:
npm install -g wrangler
or
install -g wrangler

However since wrangler went to v3 I have been unable to update. I have not added any new packages or libraries. I have tried node 18, node 20, but still a failure. I do not have Xtools installed on this computer and have no issues with v2 installations.

### Please provide any relevant error logs

mrjonze@Midnight-Blue-Air food-portal % sudo npm install -g wrangler
Password:
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm ERR! code 1
npm ERR! path /Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/wrangler/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild --release
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.17.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.17.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.8.2 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.17.0/node-v18.17.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.17.0/node-v18.17.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v18.17.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.17.0/SHASUMS256.txt
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/wrangler/node_modules/better-sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mrjonze/Library/Caches/node-gyp/18.17.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/mrjonze/Library/Caches/node-gyp/18.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/mrjonze/Library/Caches/node-gyp/18.17.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/wrangler/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1502, in XcodeVersion
npm ERR!     version_list = GetStdoutQuiet(["xcodebuild", "-version"]).splitlines()
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1563, in GetStdoutQuiet
npm ERR!     raise GypError("Error %d running %s" % (job.returncode, cmdlist[0]))
npm ERR! gyp.common.GypError: Error 1 running xcodebuild
npm ERR! 
npm ERR! During handling of the above exception, another exception occurred:
npm ERR! 
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 686, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 678, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 663, in gyp_main
npm ERR!     generator.GenerateOutput(flat_list, targets, data, params)
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2654, in GenerateOutput
npm ERR!     writer.Write(
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 883, in Write
npm ERR!     self.WriteActions(
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1017, in WriteActions
npm ERR!     env = self.GetSortedXcodeEnv()
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2272, in GetSortedXcodeEnv
npm ERR!     return gyp.xcode_emulation.GetSortedXcodeEnv(
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1888, in GetSortedXcodeEnv
npm ERR!     env = _GetXcodeEnv(
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1743, in _GetXcodeEnv
npm ERR!     "XCODE_VERSION_ACTUAL": XcodeVersion()[0],
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1513, in XcodeVersion
npm ERR!     version = CLTVersion()  # macOS Catalina returns 11.0.0.0.1.1567737322
npm ERR!   File "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1551, in CLTVersion
npm ERR!     return re.search(regex, output).groupdict()["version"]
npm ERR! AttributeError: 'NoneType' object has no attribute 'groupdict'
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 22.6.0
npm ERR! gyp ERR! command "/Users/mrjonze/.nvm/versions/node/v18.17.0/bin/node" "/Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/mrjonze/.nvm/versions/node/v18.17.0/lib/node_modules/wrangler/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v18.17.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /Users/mrjonze/.npm/_logs/2023-08-06T06_50_22_740Z-debug-0.log

**Comment by toinbis** [comment]
Same here, +1.

**Comment by jonnie-clouds** [comment]
seeing this, too:

```bash
~/dev took 2s 
❯ node -v                         
v18.13.0

~/dev 
❯ npx wrangler                    
Need to install the following packages:
  wrangler@3.4.0
Ok to proceed? (y) y
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```

**Comment by mrbm** [comment]
I went into batman mode and have made this new bug report that summarizes problem in documentation because of the new dependency along with the specific scenario that requires the x-code to be reinstalled in order to proceed: https://github.com/cloudflare/cloudflare-docs/issues/10230 Cloudflare has now re-opened my bug report to address the issue.
