### ISSUE TITLE
🐛 BUG: kv - local list output different schema than typical listing

### ISSUE THREAD

**Issue by JacksonKearl** [cloudflare/workers-sdk#3715]
### Which Cloudflare product(s) does this pertain to?

KV, Wrangler core

### What version(s) of the tool(s) are you using?

building off `main`

### What operating system are you using?

Mac

### Describe the Bug

The recent addition of the `--local` flag is lovely and I am a big fan. However the format it outputs `list` operations in is different from that which the non-`--local` `list` operation uses. Specifically a `--local` `list` looks like:
```ts
{ 
    keys: {
        name: string,
        metadata?: string, // note the raw JSON, not parsed value
        expiration?: number
    }[], 
    list_complete: true
 }
```

whereas a standard list looks like:

```ts
{
    name: string,
    metadata?: any, // parsed JSON
    expiration?: number
}[]
```

It'd be nice if they had the same output format so tools building on wrangler don't have to have a special case for parsing local commands.

cc @jspspike

**Comment by jspspike** [comment]
I see, I'll try to put up a PR sometime this week

**Comment by JacksonKearl** [comment]
cool, I can do it if you'd prefer
