### ISSUE TITLE
🐛 BUG: webSocketAutoResponse fails on local development

### ISSUE THREAD

**Issue by safaalai** [cloudflare/workers-sdk#3734]
### Which Cloudflare product(s) does this pertain to?

Pages, Workers for Platforms, Other

### What version(s) of the tool(s) are you using?

3.5.0 Wrangler

### What version of Node are you using?

18.16.1

### What operating system are you using?

Mac OS 13.2.1

### Describe the Bug

I'm experiencing failure on Hibernate Auto messages for Durable objects on local development.

Definitions
normal message = message processed by webSocketMessage handler which sends back an ack.
ping message = message processed by auto handler which sends back a pong

1. Single normal message ==> goes through and gets a response from the DO
2. Normal messages on intervals ==> every message gets a response from the DO
3. 'ping' auto messages on an interval by themselves ==> get no response
4. single normal message followed by 'pings' on intervals  ==> normal message gets response, 1st ping gets response, subsequent pings get no response
5. normal & ping messages on intervals ==> normal & ping messages get a single response, all subsequent normal & ping messages get no response

Using pages: npx wrangler pages dev -- npm start
   (npm start kicks off another server that is proxied by wrangler)

Looking at the DO logs, any time auto messages are involved, i.e. 'ping' message cases #3, #4 & #5, I get:
```workerd/jsg/util.c++:275:` error: e = kj/compat/http.c++:3421: failed: expected !currentlySending; another message send is already in progress
stack: 10b9e595f 10b9e3338 10b9f7ccd 10b9f07fe 10b9fb371 10b9f7ccd 10b9f07fe 10b9fb371 10b9f7ccd 10b9f07fe 10b9fb371 10b0ce270; sentryErrorContext = jsgInternalError
Client error Error: internal error {
  stack: Error: internal error,
  message: internal error
}```

### Please provide any relevant error logs

```workerd/jsg/util.c++:275:` error: e = kj/compat/http.c++:3421: failed: expected !currentlySending; another message send is already in progress
stack: 10b9e595f 10b9e3338 10b9f7ccd 10b9f07fe 10b9fb371 10b9f7ccd 10b9f07fe 10b9fb371 10b9f7ccd 10b9f07fe 10b9fb371 10b0ce270; sentryErrorContext = jsgInternalError
Client error Error: internal error {
  stack: Error: internal error,
  message: internal error
}```

**Comment by MellowYarker** [comment]
Thanks for the report! We're looking into it, in the meantime could you also open an issue in the Workerd repo?

**Comment by safaalai** [comment]
Reopening under workerd
