### ISSUE TITLE
Resizing window causes visual glitches with dev

### ISSUE THREAD

**Issue by Electroid** [cloudflare/workers-sdk#374]
### What version of `Wrangler` are you using?

0.0.0-b8e3b01 (alpha)

### What operating system are you using?

Mac

### Describe the Bug

When you resize your terminal window using `wrangler dev`, it causes visual glitches.

https://user-images.githubusercontent.com/3238291/152248743-78003dbd-4fb0-4c9c-a019-37aa52c3f6cd.mov

**Comment by threepointone** [comment]
![giphy](https://user-images.githubusercontent.com/18808/152251917-793cfca1-4f67-46d9-9add-06c6db86d1bb.gif)

**Comment by penalosa** [comment]
Closing in favour of #2714
