### ISSUE TITLE
🐛 BUG: Workerd errors swallowed in 3.5.0

### ISSUE THREAD

**Issue by vineelsai26** [cloudflare/workers-sdk#3743]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.5.0

### What version of Node are you using?

20.4.0

### What operating system are you using?

Mac

### Describe the Bug

Wrangler is not logging an error message if the previous instance of it is running in version 3.5.0 but however, it is in 3.4.0 and 3.3.0

Version 3.5.0
<img width="1365" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/52851879/51e34e6f-e131-41c4-9927-8bf211904825">

Version 3.4.0
<img width="1367" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/52851879/a5a79d73-59c6-4d4e-9a70-740e0cd318b1">

Version 3.3.0
<img width="1367" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/52851879/bd8223ea-b637-45fa-ae03-1a240b6ee5a4">

**Comment by Cherry** [comment]
This was reported by another user in the Discord today too: https://discord.com/channels/595317990191398933/799437470004412476/1140359620620202085

It seems like wrangler 3.5.0 is swallowing some of these workerd errors that it didn't previously.

**Comment by penalosa** [comment]
This should be resolved now. Feel free to re-open if this is still causing issues
