### ISSUE TITLE
🐛 BUG: tail workers not work and break the dashboard

### ISSUE THREAD

**Issue by madawei2699** [cloudflare/workers-sdk#3745]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms

### What version(s) of the tool(s) are you using?

3.1.2 [wrangler]

### What version of Node are you using?

v18.15.0

### What operating system are you using?

Mac

### Describe the Bug

I tried to set up a consumer worker as described in the docs, however, that will crash the Cloudflare Dashboard UI after I deploy the worker :NotLikeThis:  Also the tailing does not work, the tail worker does not receive any events.

**Comment by 1000hz** [comment]
Sorry you're running into this. Since this issue isn't directly related to wrangler or any projects contained in this repo, I'll close those and open an internal ticket to track this elsewhere. If you could provide more detail about the specific error you received in the Dashboard, the URL you were visiting when you saw the error page, and how you deployed the worker it would help us a lot in fixing the issue. Thanks!

**Comment by madawei2699** [comment]
Hi, @1000hz Sorry for that, but the tail worker broke the other worker's dashboard and did not work.

The context is, I create a tail worker, the code is very simple:
```ts
export interface Env {
  NEWRELIC_API_ENDPOINT: string
  NEWRELIC_API_KEY: string
}

export default {
  async tail(events: TailEvent, env: Env, ctx: any) {
		const { NEWRELIC_API_ENDPOINT, NEWRELIC_API_KEY } = env
		console.log('NEWRELIC_API_KEY', NEWRELIC_API_KEY)
		console.log('tail', events)
		// TODO: send log one by one, newrelic can parse json array
    const res = await fetch(NEWRELIC_API_ENDPOINT, {
      method: "POST",
			headers: {
				"Content-Type": "application/json",
				"Api-Key": NEWRELIC_API_KEY,
			},
      body: JSON.stringify({}),
    })
		const json = await res.json()
		console.log('res', json)
  }
}
```
But when I deploy the production, I need to connect it to other workers like:
<img width="1031" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/2446612/66e1e60d-9dec-4996-b50c-66f2ac68911a">

After I click the button `Save and deploy` in the dashboard and the dashboard is broken like:
<img width="1011" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/2446612/613c65b7-f729-4f54-8876-46108dd9b7ab">

And if I need the dashboard back, I need to use the wrangler in CLI to redeploy the worker without the tail worker.

And most important, the tail worker can not receive any logs from other workers bound to it.

So could you help to report this issue to the internal team? Because it stop me to use the tail worker to collect the logs and it is important to me.

Thanks.

**Comment by 1000hz** [comment]
Hi @madawei2699, thanks for adding that information! This should now be fixed.
