### ISSUE TITLE
🐛 BUG: Workers site doesn't serve static assets if `--route` is specified

### ISSUE THREAD

**Issue by kotx** [cloudflare/workers-sdk#3749]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

3.5.0

### What version of Node are you using?

18.17.1

### What operating system are you using?

Mac

### Describe the Bug

Add
```toml
[sites]
bucket = "..."
```
in `wrangler.toml`

Then run `wrangler dev --route ...`
Static assets aren't served and return 404.

**Comment by lrapoport-cf** [comment]
hi @kotx ! thanks for flagging this. in an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and any additional context and we will review. thank you!

**Comment by lrapoport-cf** [comment]
hi @kotx :) we've re-opened the issue. can you please provide a reproduction so we can look into this? thanks!

**Comment by petebacondarwin** [comment]
Workers Sites is not recommended. The recommended approach is to use Pages.
Closing as there is no reproduction.
