### ISSUE TITLE
🐛 BUG: Wranger install fails with error (Error: Expected "2023-08-14" but got "workerd 2023-08-01")

### ISSUE THREAD

**Issue by AkashRajpurohit** [cloudflare/workers-sdk#3761]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

latest

### What version of Node are you using?

18.16.0

### What operating system are you using?

Mac

### Describe the Bug

Installing latest wrangler is failing on the post install script for workerd.

[Reported on discord](https://discord.com/channels/595317990191398933/799437470004412476/1140761734827745390) as well by another user

### Please provide any relevant error logs

```
node_modules/.pnpm/workerd@1.20230814.0/node_modules/workerd: Running postinstall script, failed in 1s
.../node_modules/workerd postinstall$ node install.js
│ /Users/akash/Documents/project/node_modules/.pnpm/workerd@1.202308
│     throw new Error(
│           ^
│ Error: Expected "2023-08-14" but got "workerd 2023-08-01"
│     at validateBinaryVersion (/Users/akash/Documents/project/node_
│     at /Users/akash/Documents/project/node_modules/.pnpm/workerd@1
│ Node.js v18.16.0
```

**Comment by admah** [comment]
This was an issue in `workerd` that has now been resolved ([see this comment](https://github.com/cloudflare/workerd/issues/1016)). Could you try the install again?

**Comment by AkashRajpurohit** [comment]
Yep, seems to be working fine now.
This can be closed. Thank you.
