### ISSUE TITLE
🚀 Feature Request: allow c3 to leverage external templates

### ISSUE THREAD

**Issue by admah** [cloudflare/workers-sdk#3771]
### Describe the solution

Currently, c3 users are limited to a set of hard-coded Worker templates and a set of frameworks. We should extend c3 to allow users the ability to specify a template both interactively and non-interactively.  Templates should be accessible via a GitHub URL. 

Users should be able to:
- use a custom template via the C3 interactive flow
- use a custom template via a cli flag (ie. `--template <org>/<repo>`

**Comment by bndkt** [comment]
This would be great. A param to pass in a GitHub repo url to use as the template would be great.
