### ISSUE TITLE
request: remove the message about miniflare falling back to an older version of the runtime 

### ISSUE THREAD

**Issue by threepointone** [cloudflare/workers-sdk#3784]
### Describe the solution

Folks use the compatibility date not as a direct version number, but as an indicator of "give me all the features before this time". I think it's fine to not show the fallback message "The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2023-08-14", but you've requested "2023-08-17". Falling back to "2023-08-14"..." It's just visual noise. 

More importantly, folks who make a new project will almost ALWAYS see it, which can be confusing for folks starting off. It's not useful, so please remove it?

**Comment by Cherry** [comment]
Related: https://github.com/cloudflare/workers-sdk/issues/3363

Agreed, this is very weird and confusing when advice for years has been to just "use today's date" on new projects.
