### ISSUE TITLE
🐛 BUG: [Wrangler] `deployments view` 

### ISSUE THREAD

**Issue by alexgorb2016** [cloudflare/workers-sdk#3791]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms, Workers Runtime

### What version(s) of the tool(s) are you using?

 wrangler 3.5.1

### What version of Node are you using?

v16.20.1

### What operating system are you using?

Mac

### Describe the Bug

Hi,
I am trying to get detailed information about deployments.
So, first I run _node wrangler.js deployments list --name worker_
and I get list of last deployments without any errors, after that I use one of "Deployment ID" to get more details
_node wrangler.js deployments view "Deployment ID GUID"_ and I got following error

 ⛅️ wrangler 3.5.1
------------------
🚧`wrangler deployments` is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose

✘ [ERROR] A request to the Cloudflare API (/accounts/cd024f95850044940f272df88f976a86/workers/services/undefined) failed.

  workers.api.error.service_not_found [code: 10090]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

Please help me with that problem.

### Please provide any relevant error logs

This is my token permission list
🔓 Token Permissions: If scopes are missing, you may need to logout and re-login.
Scope (Access)
- account (read)
- user (read)
- workers (write)
- workers_kv (write)
- workers_routes (write)
- workers_scripts (write)
- workers_tail (read)
- d1 (write)
- pages (write)
- zone (read)
- ssl_certs (write)
- constellation (write)
- offline_access

**Comment by JacobMGEvans** [comment]
Thanks for reporting this!

**Comment by jspspike** [comment]
@alexgorb2016 I'm having issue recreating this issue. Looks like the worker name is somehow `undefined` when trying to make the request. Could you post your `wrangler.toml`? There might be something special about your configuration that's causing this issue. I saw you mentioned workers for platforms. Are you drying to view a deployment for a user worker or dispatch worker?

**Comment by lrapoport-cf** [comment]
hi @alexgorb2016 :) we haven't heard from you in a while, so we're going to close this issue for now. if you're still running into issues feel free to comment with more details and we can re-open and investigate further! thanks!
