### ISSUE TITLE
🚀 Feature Request: [C3] Prompt to use latest version if one is available

### ISSUE THREAD

**Issue by jculvey** [cloudflare/workers-sdk#3793]
### Describe the solution

If you `npm create cloudflare` today, it will use a cached version if you've used the command before. Ideally we'd like users to use `npm create cloudflare@latest`, but if they don't, and a newer version is available, we should confirm if they'd like to, and then spawn off a new invocation of the command `@latest`.

This check should only run if a specific version hasn't been specified, and it should default to false in non-interactive contexts.

**Comment by IgorMinar** [comment]
I propose that this behavior is the default (with a prompt defaulting to Y) and in non-interactive setting also default to yes, just like with `-y`. The only time we should stick with the version the user specified is when the user called c3 with @<version_specifier>.

This way we always use the latest unless the user is requesting a particular tag or version. WDYT?
