### ISSUE TITLE
🐛 BUG: C3 should more strictly validate arguments and pass args after `--` to the fw cli

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workers-sdk#3798]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

2.1.1

### What version of Node are you using?

18

### What operating system are you using?

Mac

### Describe the Bug

If c3 receives any unrecognized / invalid arguments before `--` separator it should fail and display `--help` output.

Any contents after `--` (or second `--` in the case of `npm create`) should be passed into the underlying fw CLI. (please note that npx and npm differ in that `npm create` itself requires `--` to pass args into c3, so in that case we end up with two `--` in argv which is a bit untraditional, but ok).

**Comment by dario-piotrowicz** [comment]
The argument passing should have been successfully addressed by https://github.com/cloudflare/workers-sdk/pull/3807

But the unrecognized / invalid arguments before `--` handling still needs to be implemented

**Comment by dario-piotrowicz** [comment]
This should have been fixed by #3841
