### ISSUE TITLE
🐛 BUG: A request to the Cloudflare API (/accounts/XXXXXXXXXXXX/workers/scripts/my-repo) failed

### ISSUE THREAD

**Issue by ja1984** [cloudflare/workers-sdk#3824]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

cloudflare/wrangler-action@v3

### What version of Node are you using?

16

### What operating system are you using?

Github actions

### Describe the Bug

I have a Nuxt3 project that have been running fine, push commits go github builds and deploys it to CF Workers (using this guide https://nitro.unjs.io/deploy/providers/cloudflare#d1-usage ).

I haven't made a commit for about 2 months until yesterday, but now it just fails. I tried to run "wrangler deploy" locally but got the same issue, all the files seems to be synced just fine but after the synced files message in the logs there is a 2 - 3 second lag and I get the following error:

```
✘ [ERROR] A request to the Cloudflare API (/accounts/XXXXXXXXXXXX/workers/scripts/my-repo) failed.

  Uncaught TypeError: d2 is not a function
    at worker.js:20001:16
    at worker.js:20003:6
    at worker.js:30283:4
    at worker.js:30284:3
   [code: 10021]

  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

**Comment by RamIdeas** [comment]
Hi @ja1984 👋  are you still experiencing this issue on the latest wrangler? If so, can you provide a minimal reproduction of your setup for us to help debug the issue please?
