### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by eklausme** [cloudflare/workers-sdk#3862]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

wrangler 2.20.1

### What version of Node are you using?

20.5.1

### What operating system are you using?

Linux

### Describe the Bug

wrangler pages publish .

✘ [ERROR] A request to the Cloudflare API (/accounts/Elmar.Klausmeier@gmail.com/pages/projects) failed.

  Could not route to /client/v4/accounts/Elmar.Klausmeier@gmail.com/pages/projects, perhaps your
  object identifier is invalid? [code: 7003]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

**Comment by helloimalastair** [comment]
Are you setting `CLOUDFLARE_ACCOUNT_ID` to your email address? Your account ID should be a 32-character Hex, like so: `d4ba2e3c15c942c374380afd7fb7f441`

**Comment by eklausme** [comment]
Thanks!

That was the problem.
