### ISSUE TITLE
🐛 BUG: openning devtools via `wrangler dev` doesn't honor the local default browser setting

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workers-sdk#3866]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.6.0

### What version of Node are you using?

18

### What operating system are you using?

Mac

### Describe the Bug

starting a `wrangler dev` or `wrangler pages dev` dev server and hitting `d` to open devtools results in Chrome being launched and devtools opening in Chrome in spite of Chrome Beta or Brave being my default browsers (separate computers).

Both are be able to display devtools without any problems so it would be great if we could honor the default browser setting and opened devtools.

Interestingly opening up a browser via `b` does honor the default browser setting, so we already do it for some but not all browser invocations.

**Comment by penalosa** [comment]
It was before my time, but I believe this was intentional in order to ensure that a browser capable of opening DevTools was used (I think primarily to guard against Safari, which can't display DevTools currently).

**Comment by RamIdeas** [comment]
Chrome still renders the devtools better than other browsers so we will keep this behaviour and close this issue as not planned

**Comment by ivanfgm** [comment]
I got here from a google search cause i don't have chrome installed, it seems now firefox and brave are also supported but i'm using Arc.

In case anyone find themselves not having chrome, brave or firefox you can open the devtools yourself opening this url in your browser:

`https://devtools.devprod.cloudflare.dev/js_app?theme=systemPreferred&ws=127.0.0.1:9229/ws`

Note you can [customize the inspector port](https://developers.cloudflare.com/workers/wrangler/commands/#dev) with `--inspector-port` option of `wrangler`.
