### ISSUE TITLE
🚀 Feature Request: support exporting D1 databases

### ISSUE THREAD

**Issue by caizixian** [cloudflare/workers-sdk#3891]
### Describe the solution

Support exporting D1 databases either as plain-text `.sql` file or `.sqlite` database file.

**Comment by arjunsajeev** [comment]
Any progress on this? CSV exports would also be nice.

**Comment by Boscop** [comment]
@arjunsajeev Can't you do it with wrangler?

**Comment by rozenmd** [comment]
Not for databases created in beta @Boscop

**Comment by flexchar** [comment]
Hey Max (@rozenmd), I wanted to give you (and everyone else considering using D1 for production) heads up that the community project has an issue exporting a bit bigger databases.

https://github.com/nora-soderlund/cloudflare-d1-backups/issues/8

I'm hoping that CF would find a way to enable exports/imports like Turso does (I'm currently exploring them as an alternative).

**Comment by nora-soderlund** [comment]
I have already fixed the issue with my package in 1.2.0.

**Comment by rozenmd** [comment]
@flexchar a native export is being worked on, we just don't have an ETA yet.

**Comment by rozenmd** [comment]
Closing this issue as we've added support for it.

**Comment by flexchar** [comment]
Huge thanks for this Max! @rozenmd

**Comment by rozenmd** [comment]
It was all @geelen !
