### ISSUE TITLE
🚀 Feature Request: Expose `readConfig` as API for programmatically use

### ISSUE THREAD

**Issue by alexanderniebuhr** [cloudflare/workers-sdk#3897]
### Describe the solution

When using Wrangler in combination with other development servers like Astro, it becomes necessary to read the Wrangler configuration programmatically. Currently, there's no straightforward way to do this, which makes integration cumbersome and less efficient.

I propose exposing the `readConfig` function as a programmatic API. This would allow developers to easily read the Wrangler configuration when using Wrangler programmatically in combination with other tools.

1. Manually reading and parsing the `wrangler.toml` file: This is error-prone and doesn't account for any internal logic that Wrangler might use to read its configuration, or any added options.
2. Using child processes to run Wrangler commands and parse the output: This is inefficient and can lead to various issues related to process management.

This feature would be particularly useful for developers who are using Wrangler in a more complex setup, where multiple development servers or build tools are involved. For example, when using Wrangler with Astro, one could read the Wrangler config to programmatically set up proxying, environment variables, etc.

**Comment by sdarnell** [comment]
Also note that it appears there is a move to switch from .toml to .json (Yay! 🥳 ) but when that happens it'll be more complicated and error prone (to support both).

**Comment by alexanderniebuhr** [comment]
Sure, would love to see exposed APIs for json also. :)

**Comment by penalosa** [comment]
This will be addressed by https://github.com/cloudflare/workers-sdk/pull/6816, which is part of the internally tracked https://jira.cfdata.org/browse/RM-19440 which we'll be working on over the next few months. I'm going to close this issue for now so that we don't duplicate the tracking, but for internal reference this specific item is tracked by https://jira.cfdata.org/browse/DEVX-1423.
