### ISSUE TITLE
🐛 BUG: wrangler init tells you to use cloudflare@2 (instead of cloudflare@latest)

### ISSUE THREAD

**Issue by jmadruga-cf** [cloudflare/workers-sdk#3900]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

Wrangler 3.7.0

### What operating system are you using?

Mac

### Describe the Bug

mockassignment git:(main) ✗ wrangler init
 ⛅️ wrangler 3.7.0
------------------
Using npm as package manager.
▲ [WARNING] The `init` command is no longer supported. Please use `npm create cloudflare@2` instead.

  The `init` command will be removed in a future version.

Running `npm create cloudflare@2`...

**Comment by jspspike** [comment]
After discussing with the team we decided that we don't want to pull the latest version of create cloudflare to keep major versions in sync. However we do want to pull the latest minor version. Based on @jculvey's comment [here](https://github.com/cloudflare/workers-sdk/pull/3903#issuecomment-1755756792) this functionality should exist once the associated PR has been merged.
