### ISSUE TITLE
🐛 BUG: Workers tail events turn `undefined` into `null`

### ISSUE THREAD

**Issue by KianNH** [cloudflare/workers-sdk#3905]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

n/a

### What version of Node are you using?

n/a

### What operating system are you using?

n/a

### Describe the Bug

Workers tail events will turn `undefined` into `null`, which confuses users as these types don't overlap & issues such as `if (undefined === null)` are [not picked up by TypeScript.](https://github.com/microsoft/TypeScript/issues/11920)

This isn't an issue with Wrangler specifically, the same behaviour is observed in the tail events shown in the dashboard.

Discord link: https://discord.com/channels/595317990191398933/779390076219686943/1149351316112539718

![firefox_1VOxFF5hP3](https://github.com/cloudflare/workers-sdk/assets/94662631/4c903278-10b7-42ca-935d-61e928307747)

**Comment by Cherry** [comment]
I just hit this and spent far longer than I care to admit trying to debug it. It's especially problematic on nested object properties. As a simple repro:

```js
export default {
	async fetch(request, env, ctx) {
		const response = await fetch('https://api.api-ninjas.com/v1/randomuser');
		const json = await response.json();
		console.log(json.test);
		return new Response('Hello World');
	},
};
```

```
  (log) null
```

`json.test` is absolutely not `null`, which has a _very_ different meaning in JavaScript than `undefined`.

**Comment by lrapoport-cf** [comment]
hi @KianNH and @Cherry , thanks for reporting this. i've raised this with the relevant internal team and they will look into this (internal ticket WP-850). as this is not a wrangler issue i'm going to close this issue, but i've linked it to the internal ticket and asked that any updates be reported back here as well :)

**Comment by markjmiller** [comment]
This is a tricky one. json can't represent javascript values such as `undefined` and `NaN`, so they have to be serialized to `null`. This trade-off was intentionally decided in the workers runtime. This could be solvable with a new TailRequest method to convert serialized `null` values back to their original js value.

**Comment by Cherry** [comment]
Thanks @markjmiller.

Unfortunately, `tail` logs today without this distinction are at best, extremely difficult to use, and at worst, effectively useless. There is a a very strong difference in JavaScript between `null` and `undefined`, so this makes debugging extremely difficult, as per my trivial example above.
