### ISSUE TITLE
🐛 BUG: wrangler dev --remote does not work if a custom domain doesn't already exist

### ISSUE THREAD

**Issue by KianNH** [cloudflare/workers-sdk#3906]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.7.0

### What version of Node are you using?

18.17.0

### What operating system are you using?

Windows

### Describe the Bug

`wrangler dev --remote` with a custom domain that doesn't yet exist throws an unhelpful `ENOTFOUND` error.

![image](https://github.com/cloudflare/workers-sdk/assets/94662631/e58100e0-0f56-4675-abdd-f151ec6d55d6)

**Comment by penalosa** [comment]
This now shows a more helpful error message as of #5107 ![Screenshot 2024-08-27 at 20 08 14](https://github.com/user-attachments/assets/a8bcee99-3e06-454f-bc84-aec20d894377)
