### ISSUE TITLE
🐛 BUG: Wildcard patterns used by SSL for SaaS do not work with a zone_id

### ISSUE THREAD

**Issue by KianNH** [cloudflare/workers-sdk#3909]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.7.0

### What version of Node are you using?

18.17.0

### What operating system are you using?

Windows

### Describe the Bug

Routes such as `*/*` are used by SSL for SaaS, and must be attributed to a zone - this works fine with `zone_name`, but instead throws an `Invalid URL` error when using `zone_id`.

https://github.com/cloudflare/workers-sdk/blob/a986f19f2d7989639524f9fd73761ea69aef4f6b/packages/wrangler/src/zones.ts#L12-L45

**Comment by penalosa** [comment]
I'm not sure when we fixed this, but I can no longer reproduce, so closing this for now. Feel free to open a new issue if it still persists.
