### ISSUE TITLE
🐛 BUG: Development proxy has different behaviour on local vs remote

### ISSUE THREAD

**Issue by KianNH** [cloudflare/workers-sdk#3911]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.7.0

### What version of Node are you using?

18.17.0

### What operating system are you using?

Windows, macOS

### Describe the Bug

Workers that have a route that covers a specific path, i.e `kian.org.uk/a-single-path`, the local proxy will behave differently depending on if `--remote` is used or not.

When using `wrangler dev --remote`:

* `open a browser` opens `/`, showing me the origin.
* My Worker is only available on `/a-single-path`

When using `wrangler dev`:

* My Worker is available on all paths.

As to which behaviour is the desired one, I will defer that to yourselves - but the behaviour difference is definitely very confusing, and the `open a browser` functionality has a lot of rough edges.

**Comment by penalosa** [comment]
Closing in favour of https://github.com/cloudflare/workers-sdk/issues/5125, which tracks our intended solution here
