### ISSUE TITLE
🐛 BUG: SSLV3_ALERT_CERTIFICATE_UNKNOWN

### ISSUE THREAD

**Issue by anasfanani** [cloudflare/workers-sdk#3915]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

0.0.0-a986f19f [Wrangler]

### What version of Node are you using?

19.5.0

### What operating system are you using?

WSL

### Describe the Bug

Error when use https after clear cache

### Please provide any relevant error logs

```
ubuntu@Optiplex:/mnt/d/code$ sudo wrangler dev --local-protocol https -l sc.js --port 443
Delegating to locally-installed wrangler@0.0.0-a986f19f over global wrangler@0.0.0-04d8a312...
Run `npx wrangler dev --local-protocol https -l src/v3.1.js --port 443` to use the local version directly.

 ⛅️ wrangler 0.0.0-a986f19f
---------------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote
▲ [WARNING] --local is no longer required and will be removed in a future version.

  `wrangler dev` now uses the local Cloudflare Workers runtime by default. 🎉


⎔ Starting local server...
[mf:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2023-09-04",
but you've requested "2023-09-08". Falling back to "2023-09-04"...
[mf:inf] Ready on https://0.0.0.0:443
[mf:inf] - https://127.0.0.1:443                                                                                                                   
[mf:inf] - https://172.17.56.232:443                                                                                                               
workerd/util/symbolizer.c++:98: warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set. To symbolize stack traces, set $LLVM_SYMBOLIZER to the location of the llvm-symbolizer binary. When running tests under bazel, use `--test_env=LLVM_SYMBOLIZER=<path>`.
kj/compat/tls.c++:500: error: error accepting tls connection; kj::mv(e) = kj/compat/tls.c++:72: failed: OpenSSL error; message = error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN                                                                                         
stack: /mnt/d/code/node_modules/@cloudflare/workerd-linux-64/bin/workerd@20b7830 /mnt/d/code/node_modules/@cloudflare/workerd-linux-64/bin/workerd@20c0cf0 /mnt/d/code/node_modules/@cloudflare/workerd-linux-64/bin/workerd@20c2250                           
kj/compat/tls.c++:500: error: error accepting tls connection; kj::mv(e) = kj/compat/tls.c++:72: failed: OpenSSL error; message = error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN                                                                                         
stack: /mnt/d/code/node_modules/@cloudflare/workerd-linux-64/bin/workerd@20b7830 /mnt/d/code/node_modules/@cloudflare/workerd-linux-64/bin/workerd@20c0cf0 /mnt/d/code/node_modules/@cloudflare/workerd-linux-64/bin/workerd@20c2250                           
GET : https://localhost.dev/
```

**Comment by petebacondarwin** [comment]
Hi @anasfanani - sorry we didn't get to look at this issue earlier. Is it still a problem for you?
It is difficult to work out what might be the problem. Are you trying to use your own certificates for the local HTTPS server?
Could you please provide a reproduction that we could debug?

**Comment by lrapoport-cf** [comment]
Hi @anasfanani :) we haven't heard from you in a while, so we’re going to close this issue for now. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and any additional details and a repro and we will revisit and investigate further. thanks!

**Comment by quisido** [comment]
@petebacondarwin 

I'm not the OP, but I'm having this same problem. I'm on Windows (not WSL), and I get this error any time I `wrangler dev`:

```
X [ERROR] kj/compat/tls.c++:500: error: error accepting tls connection; kj::mv(e) = kj/compat/tls.c++:72: failed: OpenSSL error; message = error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN
```

It's probably the `local_protocol = "https"` configuration in `wrangler.toml`.

**Comment by petebacondarwin** [comment]
@quisido - could you check a few things:

- does turning off `local_protocol = "https"` stop the error?
- what version of Wrangler and Node are you using?

**Comment by quisido** [comment]
Great question. Removing `local_protocol` did not stop the error.

Wrangler is 3.17.1, I believe.
Node is v21.1.0.

**Comment by petebacondarwin** [comment]
Hmm... OK. So I think we will need a bit more help with a reproduction that we can dig into. Any chance you could create a minimal Worker project that has this problem that I can try out locally?

**Comment by lrapoport-cf** [comment]
@quisido we haven't heard from you so we’re going to close this issue for now, but if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and a reproduction and we'll revisit and investigate further. thanks!
