### ISSUE TITLE
🐛 BUG: Cannot read properties of undefined (reading 'fetch')

### ISSUE THREAD

**Issue by thejackshelton** [cloudflare/workers-sdk#3918]
### Which Cloudflare product(s) does this pertain to?

Pages, Workers Runtime

### What version(s) of the tool(s) are you using?

3.6.0

### What version of Node are you using?

18.16.1

### What operating system are you using?

WSL2

### Describe the Bug

I'm trying to use SSR with cloudflare workers on a small-medium size site that is a blog with some extra marketing pages. I need to use SSR for the preview environment of the CMS.

How to reproduce:
Create wrangler toml file with the following:

```tsx
name = "sis-ssr-worker"
main = "dist/_worker.js"
compatibility_date = "2023-08-14"
```

Follow the get started guide here with an existing Astro project
https://developers.cloudflare.com/workers/get-started/guide/

deploy the worker. 

I get several 

### Please provide a link to a minimal reproduction

https://sis-ssr-worker.bianca-15d.workers.dev/

### Please provide any relevant error logs

Log error. There's more in the logs, but it shares some sensitive information. Let me know if there's anything else I need to provide!

```tsx
  "outcome": "exception",
  "scriptName": "sis-ssr-worker",
  "diagnosticsChannelEvents": [],
  "exceptions": [
    {
      "name": "TypeError",
      "message": "Cannot read properties of undefined (reading 'fetch')",
      "timestamp": 1694222726946
    }
  ],
```

[mf:inf] GET /_astro/hoisted.2302b26c.js 500 Internal Server Error (267ms)
[mf:inf] GET /_astro/page.9f2ff80f.js 500 Internal Server Error (270ms)
[mf:inf] GET /_astro/hoisted.fe6862c6.css 500 Internal Server Error (270ms)
[mf:inf] GET /_astro/index.8cb5bef9.css 500 Internal Server Error (273ms)
[mf:inf] GET /_astro/_...slug_.c642a811.css 500 Internal Server Error (276ms)

**Comment by yharaskrik** [comment]
I am receiving this as well. 

It works when deployed but not when using `wrangler dev` (with custom builds)

**Comment by admah** [comment]
@thejackshelton thanks for filing this issue, and sorry for the delayed response. I'm not sure if you're still having issues with your Astro site, but if you are we currently recommend using the create-cloudflare (C3) tool to start new projects since it will use Astro's scaffolding tool and then install Cloudflare-specific adapters and config. The docs you need are here: https://developers.cloudflare.com/pages/framework-guides/deploy-an-astro-site/

**Comment by lrapoport-cf** [comment]
@thejackshelton  please let us know if using create-cloudflare (C3) per @admah 's recommendation above addresses the issue, or if you still run into the same issue when using C3. thanks!

**Comment by lrapoport-cf** [comment]
hi @thejackshelton :) we haven't heard from you in a while, so we’re going to close this issue for now, but if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and any additional requested details, followup, or context and we will revisit and investigate further. thanks!
