### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by LQTseng** [cloudflare/workers-sdk#3929]
### Which Cloudflare product(s) does this pertain to?

D1, Wrangler core

### What version(s) of the tool(s) are you using?

3.7.0[Wrangler]

### What version of Node are you using?

16.14.0

### What operating system are you using?

Windows

### Describe the Bug

![image](https://github.com/cloudflare/workers-sdk/assets/109683666/89486fa1-d81c-44fd-b375-70ef5731b8a3)
I got this error when executing this command according to the [documentation](https://developers.cloudflare.com/d1/learning/local-development/#start-a-local-development-session)
>  To access your production (remote) database, pass the --remote flag when calling wrangler dev.

### Please provide any relevant error logs

X [ERROR] Unknown argument: remote

**Comment by rozenmd** [comment]
Hi @LQTseng, you're seeing this error because you are running `wrangler pages dev`, and not `wrangler dev`

I believe `--remote` isn't an option for pages (yet? @WalshyDev @GregBrimble)
