### ISSUE TITLE
🐛 BUG: Content Length bug for ARM Mac in debug

### ISSUE THREAD

**Issue by CaptainYarb** [cloudflare/workers-sdk#3934]
### Which Cloudflare product(s) does this pertain to?

Wrangler core, Miniflare

### What version(s) of the tool(s) are you using?

3.7.0

### What version of Node are you using?

18.13.0

### What operating system are you using?

Mac (Arm M1)

### Describe the Bug

The web server is serving roughly 1MB of content and stopping, no matter what the content size of the file is. I don't have insight if this is a race condition relative to the speed of serving the content or a content size limit. Text based content such as JS is signficnatly more failure prone as it doesn't retry in the browser.

This test will only fail on Mac ARM based processors. It has been replicated on a M1 Air and M2 Pro, but is not replicatable on a Windows machine.

Depending on the content type the browser can retry, but in the repo I show how it takes 5 minutes to retry and send a 24MB file, when most other times (escically for text-based content like CSS/JS) it fail with a content length mismatch error.

### Please provide a link to a minimal reproduction

https://github.com/CaptainYarb/wrangler-mac-bug

### Please provide any relevant error logs

n/a The wrangler web server doesn't produce any specific errors to show that it's aware of the failure.

**Comment by CaptainYarb** [comment]
Additional information: This bug is a regression from Wrangler v2.x

Example: https://github.com/CaptainYarb/wrangler-mac-bug/tree/wrangler-v2

**Comment by petebacondarwin** [comment]
I just tried this and while I can reproduce it with Wrangler 3.7.0 (as in the reproduction), updating to the latest Wrangler 3.22.4 does not reproduce the issue. So I believe this has been resolved.

**Comment by petebacondarwin** [comment]
In fact it appears to have been resolved as of 3.9.0
