### ISSUE TITLE
🚀 Feature Request: Bun Support

### ISSUE THREAD

**Issue by gunta** [cloudflare/workers-sdk#3941]
### Describe the solution

Currently, `wrangler init` doesn't supports Bun.

**Comment by timothymiller** [comment]
I'll add this comment here, since it is related.

It would be nice for miniflare to support `bun:sqlite` in addition to `better-sqlite3`.

When I use bun as a package manager, I find it does not install the bindings correctly for `better-sqlite3`, and D1 queries throw an error as a result.

**Comment by timothymiller** [comment]
> @timothymiller
> 
> > It would be nice for miniflare to support bun:sqlite in addition to better-sqlite3.
> > When I use bun as a package manager, I find it does not install the bindings correctly for better-sqlite3, and D1 queries throw an error as a result.
> 
> `workerd` has a native SQL interface and will no longer need the `better-sqlite3` (and thus `bun:sqlite`) dependency in the future.

Thank you for providing clarify. Upon further inspection, it seems the opportunity for improvement lies with Drizzle. Their driver for D1 requires better-sqlite3 today. I will get in contact with them.

**Comment by admah** [comment]
Thanks for submitting this. I've added a C3 label to this since ultimately this support will need to go there 👍

**Comment by timothymiller** [comment]
> @timothymiller
> 
> > It would be nice for miniflare to support bun:sqlite in addition to better-sqlite3.
> > When I use bun as a package manager, I find it does not install the bindings correctly for better-sqlite3, and D1 queries throw an error as a result.
> 
> `workerd` has a native SQL interface and will no longer need the `better-sqlite3` (and thus `bun:sqlite`) dependency in the future.

Is this updated workerd package generally available?

**Comment by FutureExcited** [comment]
with the addition of bun:s3, +1

**Comment by Dawsson** [comment]
Bump on the bun:s3, would pair amazing with R2.

**Comment by dr-diffie** [comment]
We need Bun on Cloudflare workers. This will also be a big benefit for free users as bun is mostly faster, which results in reduced cpu times.

**Comment by Dawsson** [comment]
And, will benefit cloudflare as more users will be willing to switch to workers, thus making CF more money
