### ISSUE TITLE
🐛 BUG: Fails to start dev pages if .d.ts generated by wasmpack is included

### ISSUE THREAD

**Issue by lucasavila00** [cloudflare/workers-sdk#3953]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.8.0 [wrangler]

### What version of Node are you using?

v18.16.0

### What operating system are you using?

Linux

### Describe the Bug

I'm building a pages project and using functions.

If I include this d.ts generated by wasmpack, wrangler dev does not start:

```
/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function compare_schemas(a: number, b: number, c: number, d: number, e: number): void;
export function init(a: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
```

```
Compiling worker to "/tmp/functionsWorker-0.030211841906682135.mjs"...
✘ [ERROR] The constant "memory" must be initialized

    functions/pkg/index_bg.wasm.d.ts:3:13:
      3 │ export const memory: WebAssembly.Memory;
        ╵              ~~~~~~


✘ [ERROR] The constant "memory" must be initialized

    functions/pkg/index_bg.wasm.d.ts:3:13:
      3 │ export const memory: WebAssembly.Memory;
        ╵              ~~~~~~


✘ [ERROR] Build failed with 1 error:

  functions/pkg/index_bg.wasm.d.ts:3:13: ERROR: The constant "memory" must be initialized
```

deleting this file makes everything work, including the wasm file execution etc.

**Comment by lrapoport-cf** [comment]
hi @lucasavila00  ! thanks for flagging this. in an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and any additional context and we will review. thank you!
