### ISSUE TITLE
🐛 BUG: Cant communicate with KV locally unless using --remote flag

### ISSUE THREAD

**Issue by oligirling** [cloudflare/workers-sdk#3959]
### Which Cloudflare product(s) does this pertain to?

KV, Wrangler core

### What version(s) of the tool(s) are you using?

3.8.0 [Wrangler]

### What version of Node are you using?

18.17.1

### What operating system are you using?

Mac

### Describe the Bug

When using:
```
wrangler dev --port 7000
```
I can no longer communicate with KV unless i use the `--remote` flag.

**index.js**
```
addEventListener('fetch', event => {
    event.respondWith(handleRequest(event))
})
async function handleRequest(event) {

    const kv = await OLI_TEST.get("hello")
    if (kv === null) {
        throw new Error('Its null')
    } else {
        throw new Error('Its not null, the value is ' + kv)
    }
}
```

**wrangler.toml**
```
name = "test"
main = "index.js"
account_id = "x"
workers_dev = true
send_metrics = true
compatibility_date = "2023-06-28"
node_compat = true
logpush = true

kv_namespaces = [
    { binding = "OLI_TEST", id = "xxxxxxx...f18", preview_id = "xxxxxxx...f86" }
]
```

**OLI_TEST Kv namespace**
<img width="600" alt="Screenshot 2023-09-15 at 18 52 55" src="https://github.com/cloudflare/workers-sdk/assets/42932986/c9974578-a652-4cdb-8ba7-d28954d693fa">

**OLI_TEST_preview Kv namespace**
<img width="577" alt="Screenshot 2023-09-15 at 18 51 13" src="https://github.com/cloudflare/workers-sdk/assets/42932986/4f1550e7-92e7-4509-9f7b-35a5cfbd65e7">

**Confirming with CLI**

```
$ wrangler kv:key get "hello" --binding OLI_TEST
OLI_TEST
$ wrangler kv:key get "hello" --binding OLI_TEST --preview
OLI_TEST_preview
```

When starting up it picks up the preview namespace:
```
- KV Namespaces:
  - OLI_TEST: xxxxxxx...f86
⎔ Starting local server...
```

But this returns `NULL`. It does not find the key inside KV.
<img width="1263" alt="Screenshot 2023-09-15 at 19 16 27" src="https://github.com/cloudflare/workers-sdk/assets/42932986/4205d3f0-813e-44d8-9e3b-86573e822bb0">

Now lets try with remote flag
```
wrangler dev --remote --port 7000
```

Starts up, its still using the preview_id version
```
- KV Namespaces:
  - OLI_TEST: xxxxxxx...f86
 ```
Its not `NULL`
<img width="955" alt="Screenshot 2023-09-15 at 19 09 59" src="https://github.com/cloudflare/workers-sdk/assets/42932986/38d4f880-95ca-4cf9-a930-6126224e88f5">

Two questions:
- Am I missing something?
- Isnt `--remote` meant to be loading the none preview_id version?

**Comment by jspspike** [comment]
I think we should have better documentation on this, but when you are running `wrangler dev` by default it will communicate with a local kv store using the `preview_id`. This local store is on your machine and not the same as one you may have configured in the dashboard.
If you run using the `--remote` flag, this will communicate with a live kv store using the `preview_id`.

**Comment by oligirling** [comment]
> I think we should have better documentation on this, but when you are running `wrangler dev` by default it will communicate with a local kv store using the `preview_id`. This local store is on your machine and not the same as one you may have configured in the dashboard. If you run using the `--remote` flag, this will communicate with a live kv store using the `preview_id`.

Interesting, i didnt know this and did not find much in the docs about this. How can you add to your local kv store using the CLI?

**Comment by oligirling** [comment]
If any one else runs into this issue
```
wrangler kv:key put "12345" "hello" --binding="NAMESPACE_NAME" --local --persist-to="./data/"
```
The `--local` and `--persist-to` are required. Then same for when you run `wrangler dev`:
```
wrangler dev --persist-to="./data/"
```
