### ISSUE TITLE
🐛 BUG: wrangler logs success for pages deploy even with Functions failures

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#3966]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.8.0

### What version of Node are you using?

18.17.1

### What operating system are you using?

Windows 10

### Describe the Bug

When publishing a Pages project with Functions, wrangler will seemingly always report a success, even if the Functions upload fails.

Example:

`index.html`: 
```
<html>
<body>
	<h1>Hello World</h1>
</body>
</html>
```

`functions/_middleware.js`:
```javascript
const a = true;
a();
export function onRequest(context){
	return context.next()
}
```

Result via wrangler (`npx wrangler@3.8.0 pages deploy .`):
```
✨ Successfully created the 'test-functions-errors' project.
✨ Compiled Worker successfully
🌏  Uploading... (1/1)

✨ Success! Uploaded 1 files (1.56 sec)

✨ Uploading Functions bundle
✨ Deployment complete! Take a peek over at https://3f676375.test-functions-errors.pages.dev
```

But the Cloudflare Pages dashboard shows an error:
![](https://up.jross.me/mv9n9ifp)

And the project isn't actually available. There's no way to get logs about what happened here, so folks are left confused.

This happens periodically in Discord, requiring a Pages team member to pull logs for a deployment ID, as well as on the forum such as at https://community.cloudflare.com/t/wrangler-pages-publish-always-fails-tried-both-with-nextjs-and-with-astro-templates/554749?u=cherryjimbo.

**Comment by superjose** [comment]
Oh this is currently happening to me 
<img width="1072" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/8230270/db38d0ca-a216-4ace-8d26-5a870953864b">

<img width="1067" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/8230270/f73e4d95-356e-4508-bc3d-909048c9dba5">

**Comment by rishi-raj-jain** [comment]
Happening with me as well. The CLI fails to return a warning.

**Comment by CarmenPopoviciu** [comment]
hey folks,

Thank you so much for raising this issue 🫶 . Really appreciate all the details provided 💖 

I'm happy to report there's an [open PR](https://github.com/cloudflare/workers-sdk/pull/5819) that addresses this bug. Really excited to be fixing this, as I think it'll be incredibly for our users moving forward 🤗 

Feel free to have a look and make your voice heard wrt the proposed solution. Particularly interested in knowing if the logging we put in place there provides you with sufficient information. Feedback is always much appreciated 

<3

**Comment by superjose** [comment]
OMG IT Worked now!!! hahahah, My script is over the 1 MiB size limit!!
