### ISSUE TITLE
🐛 BUG:  Authentication error [code: 10000]

### ISSUE THREAD

**Issue by willin** [cloudflare/workers-sdk#3977]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

 ⛅️ wrangler 3.8.0

### What version of Node are you using?

20

### What operating system are you using?

Mac

### Describe the Bug

```bash
❯ npx wrangler d1 create demo
--------------------
🚧 D1 is currently in open alpha and is not recommended for production data and traffic
🚧 Please report any bugs to https://github.com/cloudflare/workers-sdk/issues/new/choose
🚧 To request features, visit https://community.cloudflare.com/c/developers/d1
🚧 To give feedback, visit https://discord.gg/cloudflaredev
--------------------


✘ [ERROR] A request to the Cloudflare API (/accounts/96f10109ea482311a0fe5e42d6ea35f7/d1/database) failed.

  Authentication error [code: 10000]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose


❯ npx wrangler -v
 ⛅️ wrangler 3.8.0
------------------
```

### Please provide a link to a minimal reproduction

https://github.com/willin/remix-cloudflare-pages-demo

### Please provide any relevant error logs

Account Id: 96f10109ea482311a0fe5e42d6ea35f7
API Token: Global API Token starts with `cfbxxxx`

**Comment by rozenmd** [comment]
Hey @willin, do other wrangler commands work? `wrangler dev`, `wrangler deploy`, etc?

**Comment by willin** [comment]
`wrangler dev` works.

**Comment by rozenmd** [comment]
and @willin, what's the output of `wrangler whoami`?

**Comment by willin** [comment]
```bash
❯ npx wrangler whoami
 ⛅️ wrangler 3.8.0
------------------
Getting User settings...

✘ [ERROR] A request to the Cloudflare API (/user) failed.

  Invalid request headers [code: 6003]
  - Invalid format for Authorization header [code: 6111]

  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```


but i have already used `npx wrangler login`

**Comment by petebacondarwin** [comment]
This looks like your stored authentication token is invalid or corrupt.
Do you have CLOUDFLARE_API_TOKEN or CF_API_TOKEN environment variable set?
Can you try `npx wrangler logout` and then `npx wrangler whoami` again?

**Comment by willin** [comment]
no idea about that...

i bought a new mac recently...

**Comment by petebacondarwin** [comment]
Does that mean that you still have this problem with the new Mac?
