### ISSUE TITLE
🐛 BUG: c3 install fails with certain versions of yarn

### ISSUE THREAD

**Issue by admah** [cloudflare/workers-sdk#3998]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

2.3.0

### What operating system are you using?

Mac

### Describe the Bug

Running `yarn create-cloudflare@latest` produces an install errors in some versions of yarn. We need to investigate which versions work, why this is happening, and document version compatibility - if some versions are not supported.

**Comment by yusukebe** [comment]
Hi @admah 

This may not be related to this issue, but I always run the following command without `@latest`.

```plain
yarn create cloudflare
```

According to the following documentation it always seems to use the latest version.

https://classic.yarnpkg.com/lang/en/docs/cli/create/

And Vite also introduces it without `@latest`.

https://vitejs.dev/guide/#scaffolding-your-first-vite-project

Hope this helps. Thanks!
