### ISSUE TITLE
🐛 BUG: ERR_IPC_CHANNEL_CLOSED when reload Remix app

### ISSUE THREAD

**Issue by KazuyaHara** [cloudflare/workers-sdk#4008]
### Which Cloudflare product(s) does this pertain to?

C3, Pages, Wrangler core

### What version(s) of the tool(s) are you using?

3.9.0 [wrangler]

### What version of Node are you using?

20.6.1

### What operating system are you using?

Mac

### Describe the Bug

After running remix dev with Wrangler v3.9.0, when I tried to reload the Remix app, the server was terminated with the error message: "Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed." However, Wrangler v3.8.0 seems to work without any issues.

Steps to reproduce:
1. Setting up a new project (`npm create cloudflare@latest my-remix-app -- --framework=remix`)
2. move to remix dir (`cd my-remix-app`)
3. run remix (`npm run dev`)
4. edit files to live-reload

### Please provide any relevant error logs

```
/Users/[path-to-remix]/node_modules/wrangler/wrangler-dist/cli.js:30947
            throw a;
            ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at new NodeError (node:internal/errors:405:5)
    at target.send (node:internal/child_process:754:16)
    at Object.announceAndOnReady [as onReady] (/Users/[path-to-remix]/node_modules/wrangler/wrangler-dist/cli.js:150032:15)
    at MiniflareServer.<anonymous> (/Users/[path-to-remix]/node_modules/wrangler/wrangler-dist/cli.js:128172:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on process instance at:
    at process.processEmit [as emit] (/Users/[path-to-remix]/node_modules/wrangler/wrangler-dist/cli.js:25324:38)
    at node:internal/child_process:758:35
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
```

**Comment by ryan0x44** [comment]
Can confirm same issue per this and remix-run/remix#7510 and downgrading from wrangler 3.9.0 to 3.8.0 resolved it for me

**Comment by IanVS** [comment]
I am also getting `ERR_IPC_CHANNEL_CLOSED` on each change to my functions files when using vite, and not remix.

**Comment by Phoenixmatrix** [comment]
I caught that too in Remix, but it happens whenever the content of the functions directory is updated, no matter the tooling.

**Comment by ekojsalim** [comment]
Seems that this is due to this [code change](https://github.com/cloudflare/workers-sdk/pull/3951/files#diff-f64ec8fc0f101cfe619c859a32a565dbedacc3b95f1e3a1483cb832710dbbfb2R766-R772). @mrbbot

**Comment by OnurGvnc** [comment]
> Seems that this is due to this [code change](https://github.com/cloudflare/workers-sdk/pull/3951/files#diff-f64ec8fc0f101cfe619c859a32a565dbedacc3b95f1e3a1483cb832710dbbfb2R766-R772). @mrbbot

I had the same issue and removing [that line](https://github.com/cloudflare/workers-sdk/blob/5221a2ce87e85d7c1b66b4f7badd599b3a780031/packages/wrangler/src/index.ts#L772) fixed it for me.
As a temporary workaround, I've created a patch using [patch-package](https://github.com/ds300/patch-package).

`./patches/wrangler+3.9.1.patch`
```patch
diff --git a/node_modules/wrangler/wrangler-dist/cli.js b/node_modules/wrangler/wrangler-dist/cli.js
index 183663e..ebfe39f 100644
--- a/node_modules/wrangler/wrangler-dist/cli.js
+++ b/node_modules/wrangler/wrangler-dist/cli.js
@@ -147318,8 +147318,6 @@ ${tryRunningItIn}${oneOfThese}`
     }
     throw e2;
   } finally {
-    if (typeof jest === "undefined")
-      process.disconnect?.();
   }
 }
 __name(main, "main");

```

**Comment by OnurGvnc** [comment]
for a temporary workaround: https://github.com/cloudflare/workers-sdk/issues/4008#issuecomment-1735824275
