### ISSUE TITLE
🐛 BUG: ERR_IPC_CHANNEL_CLOSED when saving Pages Function with local D1 binding

### ISSUE THREAD

**Issue by scruffymongrel** [cloudflare/workers-sdk#4017]
### Which Cloudflare product(s) does this pertain to?

D1, Pages, Wrangler core

### What version(s) of the tool(s) are you using?

3.9.0 [Wrangler]

### What version of Node are you using?

20.7.0

### What operating system are you using?

Mac

### Describe the Bug

When running `pnpm wrangler pages dev ./public` via wrangler 3.9.0, changes to a Pages Function work fine if there is no local D1 binding.

Once a local D1 binding is created via `pnpm wrangler pages dev ./public --d1=DB` (as per <https://developers.cloudflare.com/pages/platform/functions/bindings/#d1-databases>), changes to the Pages Function cause wrangler to crash.

Before restarting wrangler, I need to `lsof -I :8788` and `kill -9` the process, otherwise I get `✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.`

### Please provide a link to a minimal reproduction

https://github.com/Hinte-land/repro-wrangler-3.9.0-pages-d1-local

### Please provide any relevant error logs

```
/Users/andy/§/github.com/hinte-land/repro-wrangler-3.9.0-pages-d1-local/node_modules/.pnpm/wrangler@3.9.0/node_modules/wrangler/wrangler-dist/cli.js:30947
            throw a;
            ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at new NodeError (node:internal/errors:405:5)
    at target.send (node:internal/child_process:754:16)
    at Object.announceAndOnReady [as onReady] (/Users/andy/§/github.com/hinte-land/repro-wrangler-3.9.0-pages-d1-local/node_modules/.pnpm/wrangler@3.9.0/node_modules/wrangler/wrangler-dist/cli.js:150032:15)
    at MiniflareServer.<anonymous> (/Users/andy/§/github.com/hinte-land/repro-wrangler-3.9.0-pages-d1-local/node_modules/.pnpm/wrangler@3.9.0/node_modules/wrangler/wrangler-dist/cli.js:128172:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on process instance at:
    at process.processEmit [as emit] (/Users/andy/§/github.com/hinte-land/repro-wrangler-3.9.0-pages-d1-local/node_modules/.pnpm/wrangler@3.9.0/node_modules/wrangler/wrangler-dist/cli.js:25324:38)
    at node:internal/child_process:758:35
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v20.7.0
```

**Comment by Sylphritz** [comment]
I'm getting the same error as soon as I set D1 binding via the following command:
```
wrangler pages dev --compatibility-date=2023-09-19 --d1=DB --proxy 3000 -- pnpm dev
```

**Comment by Phoenixmatrix** [comment]
even without the d1 binding I get the issue in wrangler 3.9. I have a Remix app and if I make any change that affects the server (so update the pages function), it will cause the error. That's with a brand new app, no binding, nothing.

Reverting to 3.7 fixes the issue (I think 3.8 was fine too, but didn't double check). If I upgrade back to 3.9, issue returns.

**Comment by aaronadamsCA** [comment]
+1 to having this issue with no bindings. Our command is

```
wrangler pages dev public/ --compatibility-date=2023-08-01 --local-protocol=https --port=8002
```

and we get a crash upon saving any file.

Reverting to Wrangler v3.8.0 works.

**Comment by Sylphritz** [comment]
I updated `wrangler` to `3.10.0` and the problem is gone.

**Comment by scruffymongrel** [comment]
Can confirm same behaviour under 3.10.0.

From what I've seen, reverting back to 3.8.0 seems to need something like `cf-bindings-proxy` to enable local D1 with Pages. I've managed to get a workable solution with 3.8.0 and `cf-bindings-proxy` but am keen to remove the extra dependency if possible.

**Comment by kreas** [comment]
Can confirm. Same issue for me as well

```bash
➜  ai-cf git:(main) ✗ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
➜  ai-cf git:(main) ✗ node -v
v20.6.1
```

**Comment by TEMHITHORPHE** [comment]
seems related to this issue here #4008 ... there's a workaround mentioned there, but the straightforward thing seems to downgrade back down to Wrangler 3.8.
