### ISSUE TITLE
🐛 BUG: [ERROR] near "INSERT": syntax error [code: 7500]

### ISSUE THREAD

**Issue by BaffinLee** [cloudflare/workers-sdk#4020]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3

### What version of Node are you using?

20

### What operating system are you using?

Windows

### Describe the Bug

Here is my sql, there is no `INSERT` in it ! What's going on ?

```sql
CREATE TABLE IF NOT EXISTS orders (
    order_id INTEGER PRIMARY KEY,
    customer_id STRING NOT NULL, -- for example, a unique ID aba0e360-1e04-41b3-91a0-1f2263e1e0fb
    order_date STRING NOT NULL,
    status INTEGER NOT NULL,
    last_updated_date STRING NOT NULL
)
```

And this sql is copied from your official page, https://developers.cloudflare.com/d1/learning/using-indexes/#create-an-index
![image](https://github.com/cloudflare/workers-sdk/assets/17738556/007be477-5d38-4f9a-a329-1fdee7e3db23)

### Please provide any relevant error logs

Your database may not be available to serve requests during the migration, continue? ... yes
🌀 Mapping SQL input into an array of statements
🌀 Parsing 1 statements
🌀 Executing on test (22b98bc9-da38-49e8-8f18-e20bbbea78e7):
┌───────────────┬────────┐
│ name          │ status │
├───────────────┼────────┤
│ 0001_init.sql │ ❌       │
└───────────────┴────────┘

❌ Migration 0001_init.sql failed with the following errors:

X [ERROR] near "INSERT": syntax error [code: 7500]

**Comment by LuckyWraptor** [comment]
Did you forget a semicolon perhaps?
Cloudflare D1 (or sqlite) is picky about that.

Looking at the error, I'm not sure it's the Cloudflare example code that's wrong... something else is.
