### ISSUE TITLE
🚀 Feature Request: allow build step for wrangler dev

### ISSUE THREAD

**Issue by jadbox** [cloudflare/workers-sdk#4021]
### Describe the solution

For frameworks like Astro, the project first needs to be built prior to `wrangler dev` being able to mount the project and provide its wrapper services (like D1). There's some work with Astro happening now to manually replicate parts of wrangler inside of `astro dev` so that wrangler isn't needed (https://github.com/withastro/astro/pull/8654). However I worry this might be a fragile solution as the CF services and wrappers are bound to change over time. 

One possible solution to allow wrangler to auto rebuild from a host framework on changes:
`wrangler dev --watch --exec astro build`

Alternatively, would it be possible for `astro dev` to use `wrangler` as a JS API for injecting the services and environment info?

I'm not involved in any of this active development, but I wanted to raise this up as a framework interoperability challenge.

**Comment by alexanderniebuhr** [comment]
I'm the maintainer for Astro, working on the integration of the mentioned support. I'd like to provide some clarity on our approach.

To begin with, we aren't manually replicating `wrangler`. Instead, we leverage `workerd` and `miniflare`, that are also utilized by `wrangler`. While we currently extract certain logic to implement config file parsing, our preference would be to fully utilize an API. We've opened a [request](https://github.com/cloudflare/workers-sdk/issues/3897) to discuss this further.

> A potential solution to enable wrangler's automatic rebuild when the host framework detects changes: 
`wrangler dev --watch --exec astro build`

While a similar functionality is achievable today, our goal is to seamlessly integrate it with the `vite` dev server. This would eliminate the need for a complete project rebuild every time there's a change.

> Alternatively, would it be possible for astro dev to use wrangler as a JS API for injecting the services and environment info?

As previously highlighted, we're already leveraging APIs for integration. @jadbox, could you clarify your suggestion and how it might differ from our current approach?

**Comment by jadbox** [comment]
Thank you @alexanderniebuhr, you have far more context than on so perhaps I have only stirred up dust by opening this. I'll go ahead and close this issue.
