### ISSUE TITLE
🐛 BUG:A request to the Cloudflare API  backup failed

### ISSUE THREAD

**Issue by abdolrhman** [cloudflare/workers-sdk#4022]
### Which Cloudflare product(s) does this pertain to?

D1, R2

### What version(s) of the tool(s) are you using?

3.9.0[wrangler]

### What version of Node are you using?

v18.7.0

### What operating system are you using?

mac

### Describe the Bug

i am trying to work locally with d1, as described here :
https://github.com/cloudflare/workers-sdk/tree/main/templates/worker-d1
so when i try to create a backup with R2 i am getting 
  The request is malformed: Experimental DBs do not support backups yet:
please advice

**Comment by overiit** [comment]
Had this issue aswell while migrating with d1, updating to 3.10.0 fixed it for me.

**Comment by penalosa** [comment]
@abdolrhman Could you clarify the exact Wrangler command you're running that causes this error? Does upgrading to v3.10 fix the issue for you?

**Comment by colinmcdonald22** [comment]
Not the issue creator, but I was stuck on this issue for a bit too

 I kept running `wrangler --version` and getting 3.10.1, without realizing that my shell was using globally-installed Wrangler (3.10.1), but my `package.json` scripts were using my `devDependencies`-installed Wrangler.

After updating Wrangler in `devDependencies`, this is fixed after 3.10.

**Comment by RamIdeas** [comment]
For future reference, using `npx wrangler` will use your local project wrangler first and then the globally installed version before getting the latest from npm and using that

Sounds like this is fixed in v3.10.0, so I will close this issue now.

@abdolrhman thanks for reporting the issue, if the problem still exists on the latest version please feel free to open

**Comment by uniform641** [comment]
I met the same problem with wrangler 3.13.2. 

Here is the relevant log.
```bash
╭─ ~/Documents/code/test ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  at 11:10:17 
╰─ npx wrangler d1 backup create test-db
Proxy environment variables detected. We'll use your proxy for fetch requests.

✘ [ERROR] A request to the Cloudflare API (api address) failed.

  The request is malformed: Experimental DBs do not support backups yet:
  [my-database-id] (v3) [code: 7400]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

My system info:
- wrangler: 3.13.2
- node: 18.16.0
- os: ubuntu 22.04

**Comment by xokaido** [comment]
I am having the same issue:
![image](https://github.com/cloudflare/workers-sdk/assets/6562281/552409b1-8e55-4fd6-b001-e776b88fa7e9)
