### ISSUE TITLE
🐛 Bug Report — Pages Functions - workerd crashes on syntax errors

### ISSUE THREAD

**Issue by treeder** [cloudflare/workers-sdk#4031]
refs https://github.com/cloudflare/workers-sdk/issues/3663

When working with pages functions in dev mode, ie:

```sh
wrangler pages dev public
```

When you edit a file and get a syntax error, wrangler crashes. And worse than just crashing, it leaves the workerd process running so you can't just start it up again. You have to find the process ID, then `kill` the process before you can start it up again.

The error can be as simple as having an extra bracket, eg:

![image](https://github.com/cloudflare/workerd/assets/75826/5c7b5683-345a-4c12-a3fe-0cab7ca3a5c1)

**Comment by irvinebroque** [comment]
@treeder — can you try this pre-release version of Wrangler from https://github.com/cloudflare/workers-sdk/pull/3695#issuecomment-1661746419 that _should_ fix this? 

```
npx https://prerelease-registry.devprod.cloudflare.dev/workers-sdk/runs/6115478290/npm-package-wrangler-3695 dev path/to/script.js
```

**Comment by treeder** [comment]
Yep, that fixes it. 👍
