### ISSUE TITLE
🐛 BUG: Failed wrangler vectorize create because vectorize.not_entitled [code: 1005]

### ISSUE THREAD

**Issue by teramotodaiki** [cloudflare/workers-sdk#4042]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.10.0 [Wrangler]

### What version of Node are you using?

18.14.0

### What operating system are you using?

Mac

### Describe the Bug

I tried to `vectorize create` according to the document ( https://developers.cloudflare.com/vectorize/get-started/intro/ ), then I got the following error.

```sh
$ npx wrangler vectorize create tutorial-index --dimensions=3 --metric=cosine
🚧 Creating index: 'tutorial-index'

✘ [ERROR] A request to the Cloudflare API (/accounts/**my id**/vectorize/indexes) failed.

  vectorize.not_entitled [code: 1005]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

The worker is just created now with `npm create cloudflare@latest` and deployed successfully.
It seems to be an API error, so I will try again tomorrow.
I am very excited the vectorize. :)
****

**Comment by admah** [comment]
@teramotodaiki are you on a Workers Paid plan? The [docs](https://developers.cloudflare.com/vectorize/) say: " Vectorize is currently in public beta and is enabled for all developers on Workers paid plans." The error you're seeing looks related to that.

**Comment by teramotodaiki** [comment]
@admah I had missed it, will try it with Paid plan. Thank you very much! 😄

**Comment by teramotodaiki** [comment]
Close this issue because I upgraded to a Paid plan then the problem was resolved.
