### ISSUE TITLE
🐛 BUG: kv:key put hangs with `--local`

### ISSUE THREAD

**Issue by christianklotz** [cloudflare/workers-sdk#4044]
### Which Cloudflare product(s) does this pertain to?

KV, Wrangler core

### What version(s) of the tool(s) are you using?

3.10.0 [Wrangler]

### What version of Node are you using?

20.5.1 

### What operating system are you using?

Mac

### Describe the Bug

Trying to set a KV value locally makes wrangler hang.

```
wrangler kv:key put foo bar --binding=MY_BINDING --local
 ⛅️ wrangler 3.10.0
-------------------
Writing the value "bar" to key "foo" on namespace xyz.
```

Removing `--local` will succeed and write the value to production without hanging.

Not sure if relevant: The Mac is an Apple Silicon (M2) MacBook Air

**Comment by admah** [comment]
@christianklotz thanks for filing this. Can you add `WRANGLER_LOG="debug"` before the command you're running? That should provide a little more info. 

I tried to replicate this with Node 20.7.0 / Wrangler 3.10.0 / M1 , and was not able to. The command worked as expected.

**Comment by christianklotz** [comment]
Of course, this

```
◆ WRANGLER_LOG="debug" npx wrangler kv:key put foo bar --binding=MY_BINDING --local
Failed to load .env file ".env": Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (node:fs:602:3)
    at Object.readFileSync (node:fs:470:35)
    at tryLoadDotEnv (/Users/ck/Developer/my-repo/node_modules/wrangler/wrangler-dist/cli.js:124088:72)
    at loadDotEnv (/Users/ck/Developer/my-repo/node_modules/wrangler/wrangler-dist/cli.js:124097:12)
    at /Users/ck/Developer/my-repo/node_modules/wrangler/wrangler-dist/cli.js:147712:20
    at /Users/ck/Developer/my-repo/node_modules/wrangler/wrangler-dist/cli.js:131378:16
    at maybeAsyncResult (/Users/ck/Developer/my-repo/node_modules/wrangler/wrangler-dist/cli.js:129600:44)
    at /Users/ck/Developer/my-repo/node_modules/wrangler/wrangler-dist/cli.js:131377:14
    at /Users/ck/Developer/my-repo/node_modules/wrangler/wrangler-dist/cli.js:129587:22
    at Array.reduce (<anonymous>) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '.env'
}
 ⛅️ wrangler 3.10.0
-------------------
Writing the value "bar" to key "foo" on namespace xyz.
```

Adding an empty `.env` file does not make a difference but silences the log

```
◆ WRANGLER_LOG="debug" npx wrangler kv:key put foo bar --binding=STATE_MACHINE --local
 ⛅️ wrangler 3.10.0
-------------------
Writing the value "bar" to key "foo" on namespace 8387aaabec97483d81f33d41fc0993a5.
```

Something worth adding, wrangler is run from a NPM workspace inside a repo but wrangler is added as a dependency at repo level.

**Comment by christianklotz** [comment]
Interestingly, after you mentioned it works with Node 20.7.0, I upgraded Node for this repo and low and behold, it works

```
◆ WRANGLER_LOG=debug npx wrangler kv:key put foo bar --binding=MY_BINDING --local
 ⛅️ wrangler 3.10.0
-------------------
Writing the value "bar" to key "foo" on namespace xyz.
Retrieving cached values for userId from node_modules/.cache/wrangler
Metrics dispatcher: Posting data {"type":"event","name":"write kv key-value (local)","properties":{}}
```

**Comment by penalosa** [comment]
Sounds like this is no longer an issue, so I'm closing this for now
