### ISSUE TITLE
🚀 Feature Request: Hyperdrive should have default ports for schemes (i.e 5432 for postgres)

### ISSUE THREAD

**Issue by KianNH** [cloudflare/workers-sdk#4059]
### Describe the solution

> Good catch, yes. We should fix to avoid needing to specify it for Postgres and just default to 5432 in those cases.

_Originally posted by @elithrar in https://github.com/cloudflare/cloudflare-docs/pull/10980#discussion_r1340579722_

**Comment by lrapoport-cf** [comment]
hi @elithrar , can your team take a look at this?

**Comment by KianNH** [comment]
It looks like this was solved today by @a-robinson in https://github.com/cloudflare/workers-sdk/pull/4069
