### ISSUE TITLE
🐛 BUG: Unable to start wranglers with D1 config

### ISSUE THREAD

**Issue by ian** [cloudflare/workers-sdk#4077]
### Which Cloudflare product(s) does this pertain to?

D1, Wrangler core

### What version(s) of the tool(s) are you using?

3.10.1

### What version of Node are you using?

18.12.1

### What operating system are you using?

Mac

### Describe the Bug

Getting C++ stack trace when trying to run `wranger dev`:

```
⎔ Starting local server...
workerd/server/workerd-api.c++:615: error: wrapped binding module can't be resolved (internal modules only); moduleName = cloudflare-internal:d1-api
workerd/util/symbolizer.c++:98: warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set. To symbolize stack traces, set $LLVM_SYMBOLIZER to the location of the llvm-symbolizer binary. When running tests under bazel, use `--test_env=LLVM_SYMBOLIZER=<path>`.
workerd/jsg/util.c++:275: error: e = workerd/server/workerd-api.c++:635: failed: expected !value.IsEmpty(); global did not produce v8::Value
stack: 10409b8cf 1043710b3 10405a4b7 10405f49b 1040627df 10406120f 104054543 1040542db 10405414f 104054137 105e896f3 105e89a3b 105e8819b 105e87f6b 1040481af 108a0d08b; sentryErrorContext = jsgInternalError
service core:user:cantoscan: Uncaught Error: internal error
✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

Using wrangler.toml:
```
name = "project"
main = "src/db/index.ts"
compatibility_date = "2023-02-03"

[[ d1_databases ]]
binding = "DB"
database_name = "db"
database_id = "..."
preview_database_id = "..."
```

**Comment by rozenmd** [comment]
Hi @ian, thanks for reporting this.

Could you please post a repo with a minimal reproduction of the issue? 

Using the latest wrangler (3.10.1) and a `wrangler.toml` with both a db and a preview db, I couldn't reproduce the issue:

```
 ⛅️ wrangler 3.10.1
-------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote
Your worker has access to the following bindings:
- D1 Databases:
  - DB: 20231002 (xxxx), Preview: (xxxx)
⎔ Starting local server...
[mf:inf] Ready on http://0.0.0.0:8787 
...
```

**Comment by joebailey26** [comment]
I'm getting this issue too. Running Wrangler 3.11.0

**Comment by admah** [comment]
I believe the first warning you're seeing is unrelated to D1, and is what users are reporting in #3631. With the second issue, a repo or way to reproduce would be helpful so we can troubleshoot.

**Comment by lrapoport-cf** [comment]
hey @joebailey26  :) we haven't heard from you in a while, so we’re going to close this issue for now. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and reproduction, and any additional requested details, followup, or context and we will revisit and investigate further. thanks!
