### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by serbyxyz** [cloudflare/workers-sdk#4121]
### Which Cloudflare product(s) does this pertain to?

Pages, Other

### What version(s) of the tool(s) are you using?

    "wrangler": "^3.11.0",  "@builder.io/qwik": "^1.2.12", "@builder.io/qwik-city": "^1.2.12",

### What version of Node are you using?

v20.8.0

### What operating system are you using?

Windows

### Describe the Bug

No loader is configured for ".ttf"

**Comment by penalosa** [comment]
Thanks for reporting this! It looks like you're trying to import a `.ttf` file within your Worker, which isn't supported out of the box. [Wrangler's bundling documentation](https://developers.cloudflare.com/workers/wrangler/configuration/#bundling) has details on how to configure imports—in your case adding the following to your `wrangler.toml` file should allow you to import `.ttf` files as text:

```toml
rules = [
  { type = "Text", globs = ["**/*.ttf"], fallthrough = true }
]
```
