### ISSUE TITLE
🐛 BUG: KV null first value after add new id which start with number at local persist

### ISSUE THREAD

**Issue by katopz** [cloudflare/workers-sdk#4122]
### Which Cloudflare product(s) does this pertain to?

KV

### What version(s) of the tool(s) are you using?

3.10.1

### What version of Node are you using?

18.16.0

### What operating system are you using?

Mac intel

### Describe the Bug

I will describe in comment below
```bash
wrangler dev --persist-to=.wrangler/state
```

```ts
// just helper
export const get_kv_values = async <T>(kv: KVNamespace) => {
  const keys = (await kv.list()).keys
  if (!keys || keys.length < 0) throw new Error('Expect keys')

  console.log('k:', keys.map(e => e.name))

  const values = (await Promise.all(keys.map(key => kv.get<T>(key.name, { type: "json" }))))
  if (!values || values.length < 0) throw new Error('Expect values from KV')

  console.log('v:', values)
  console.log('--------------')

  return values
}

export const test_user = async (USER:KVNamespace) => {
  // Dispose
  await USER.delete('64646261-3434-5534-b837-363833386132')
  await USER.delete('foo')
  await USER.delete('bar')

  // Add foo
  await USER.put('foo', JSON.stringify({ id: 'foo' })).catch(console.error)
  await get_kv_values(USER)

  // Add bar
  await USER.put('bar', JSON.stringify({ id: 'bar' })).catch(console.error)
  await get_kv_values(USER)

  // Add bug id that start with number
  await USER.put('64646261-3434-5534-b837-363833386132', JSON.stringify({ id: '64646261-3434-5534-b837-363833386132' })).catch(console.error)

  // BUG: foo value is gone! 😱
  await get_kv_values(USER)
}
```

### Please provide any relevant error logs

```
k: Array(1) [ foo ]
v: Array(1) [ Object ]
--------------
k: Array(2) [ bar, foo ]
v: Array(2) [ Object, Object ]
--------------
k: Array(3) [ 64646261-3434-5534-b837-363833386132, bar, foo ]
v: Array(3) [ Object, Object, null ]
--------------
```

**Comment by kudlav** [comment]
I'm using the following shell script to fill the KV store:
```sh
npx wrangler kv:key put "3BQ3fnTjRLQems8b7VZb" --local --namespace-id keys --path test_key.json
npx wrangler kv:key put "o4nLVpnacflo9oZFmr1a" --local --namespace-id keys --path test_key_origin.json
npx wrangler kv:key put "tZ4QghPh2M3zzLsar1C3" --local --namespace-id keys --path test_key_ua.json
npx wrangler kv:key put "25B31rNR1A169Lkv7iaf" --local --namespace-id keys --path test_key_others.json
```
The first key (`test_key`) is missing in the local KV store, after running this script.

Node v18.18.0
Ubuntu
Last working version: 3.8.0
Broken in 3.9.0

**Comment by kudlav** [comment]
I'm using the following shell script to fill the KV store:
```sh
npx wrangler kv:key put "3B" --local --namespace-id keys --path test_key.json
npx wrangler kv:key put "o4" --local --namespace-id keys --path test_key_origin.json
npx wrangler kv:key put "tZ" --local --namespace-id keys --path test_key_ua.json
npx wrangler kv:key put "25" --local --namespace-id keys --path test_key_others.json
```
The first key (`test_key`) is missing in the local KV store, after running this script.
The `.wrangler/state/v3/kv/keys/blobs` folder contains only three entries.

Node v18.18.0
Ubuntu
Last working version: 3.8.0
Broken in 3.9.0

**Comment by aplunk** [comment]
@katopz I can't replicate your results when testing against the production KV service. Can you verify that you can only replicate the results when running `wrangler dev` in local mode?

**Comment by katopz** [comment]
> @katopz I can't replicate your results when testing against the production KV service. Can you verify that you can only replicate the results when running `wrangler dev` in local mode?

This happen only in local atm, seem fine in prod (i hope) but to make sure please consider put this in prod test case. (Don't trust me, verify!)

**Comment by dalbitresb12** [comment]
I think I've found this bug as well. I was saving two records at the same time in KV with the following formats:

- `uuid:uuid`
- `####-####-##`

I found that the first record (the one with UUIDs) was not saving the blob to `.wrangler/state/kv`, but when I checked the `.sqlite` file both records were saved there, with the first one having a reference to a non-existent blob.

I just tested in remote mode and it does not happen when deployed in the Cloudflare servers (which, btw, I hope the Cloudflare team finishes recovering from the [incident](https://www.cloudflarestatus.com/incidents/hm7491k53ppg) and they get a good rest).

**Comment by hi-ogawa** [comment]
The PR was not linked to here but I think this is expected to be fixed by
- https://github.com/cloudflare/workers-sdk/pull/4466

**Comment by kaytwo** [comment]
I am still seeing this bug as of wrangler 3.26.0

**Comment by admah** [comment]
Closing this as fixed by the PR linked above. If this continues to be an issue, please reopen. Thanks!
