### ISSUE TITLE
🐛 BUG: live-reload feature in Remix not working after upgrading to Wrangler 3.11.0

### ISSUE THREAD

**Issue by KazuyaHara** [cloudflare/workers-sdk#4124]
### Which Cloudflare product(s) does this pertain to?

C3, Pages

### What version(s) of the tool(s) are you using?

3.11.0 [wrangler]

### What version of Node are you using?

20.8.0

### What operating system are you using?

Mac

### Describe the Bug

After upgrading to Wrangler 3.11.0, the live reload feature of Remix stopped working. It was working around the time of 3.10.1.

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to provide a reproduction repo that demonstrates the issue?

**Comment by petebacondarwin** [comment]
Closing due to lack of response.
