### ISSUE TITLE
🐛 BUG: Unable to use `HYPERDRIVE.connectionString` with Prisma on the edge

### ISSUE THREAD

**Issue by drewdecarme** [cloudflare/workers-sdk#4145]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.11.0 [Wrangler]

### What version of Node are you using?

18.14.0

### What operating system are you using?

Mac

### Describe the Bug

I was getting really excited to use Hyperdrive instead of the Prisma Accelerate product (formerly known as the Prisma Data Proxy) since some of the guidance around Hyperdrive that it could be used with any ORM / DB Utility.

However, it seems that Prisma is forcing users on the `@prisma/client/edge` package (which is required for Cloudflare Workers) to prepend the DB URL with the `prisma://` protocol. Seems a little annoying that the library is throwing an error while validating the syntax of the connection string rather than kind of letting us plug and play.

Here's the error that is happening when I'm trying to do a `FindOrCreate` while using Prisma. Here's the actual known error code that is being generated: https://www.prisma.io/docs/reference/api-reference/error-reference#p5002

```
PrismaClientKnownRequestError: \nInvalid `prisma.user.upsert()` invocation:\n\n\nError validating datasource `db`: the URL must start with the protocol `prisma://`
```

Here's what the `HYPERDRIVE.connectionString` binding looks like for me
```
postgresql://__REDACTED__@__REDACTED__.hyperdrive.local:5432/__REDACTED__?sslmode=disable
```

Is this something that is on Cloudflare's radar and if so, is there any guidance that is in process on how we can continue using our existing tooling with Hyperdrive?

### Please provide any relevant error logs

```
PrismaClientKnownRequestError: \nInvalid `prisma.user.upsert()` invocation:\n\n\nError validating datasource `db`: the URL must start with the protocol `prisma://`
```

**Comment by jharrell** [comment]
Hi @drewdecarme! Jon from Prisma here. This is actually an issue on the Prisma side. We currently only support edge deployments if you are using Accelerate or Data Proxy. We're working on full edge support and support for CF workers in particular can be found here: https://github.com/prisma/prisma/issues/19488

Please let me know if you have any questions!

**Comment by drewdecarme** [comment]
Sounds like you guys are well on your way then to support the exact scenario that I was proposing above. I did sign up for the beta when you guys are ready so I'm happy to keep this open and report back if that's what you would expect.

Thanks for posting that!

**Comment by janpio** [comment]
.... and it should work now actually: https://github.com/prisma/prisma/issues/21394#issuecomment-1992311887
Or directly our blog post: https://www.prisma.io/blog/prisma-orm-support-for-edge-functions-is-now-in-preview
