### ISSUE TITLE
🐛 BUG: Hyperdrive issues when trying to disable cache

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#4151]
### Which Cloudflare product(s) does this pertain to?

Other

### What version(s) of the tool(s) are you using?

Latest

### What version of Node are you using?

18

### What operating system are you using?

Mac

### Describe the Bug

Noticed a few odd things from playing around with it, figured one issue was better than several:

- [ ] the [docs](https://developers.cloudflare.com/hyperdrive/learning/query-caching/#disable-caching) say to run `wrangler hyperdrive update my-hyperdrive --disable-caching` while the flag in wrangler is `--caching-disabled`
- [ ] the use of `my-hyperdrive` in the example above makes it sound like wrangler is expecting the `name`, rather than the `id` - (surprised that wrangler couldn't handle both tbh)
- [ ] the docs also mention that you can update hyperdrive cache settings in the dashboard, but there's just a set of instructions in the dashboard, no UI
- [ ] when actually running `wrangler hyperdrive update my-hyperdrive --disable-caching`, I'm prompted for my origin password, which is weird?

**Comment by ankur-arch** [comment]
Posting this here as the docs haven't been updated yet for users who run into this issue. Here's what worked for me:

```bash
npx wrangler $HEXADECIMAL_ID \
  --origin-host $ORIGIN_HOST \
  --origin-port $ORIGIN_PORT \
  --origin-password $ORIGIN_PASSWORD \
  --origin-user $ORIGIN_USER \
  --origin-scheme $ORIGIN_SCHEME \
  --database $DATABASE \
  --caching-disabled true
```

**Comment by OilyLime** [comment]
We should close this issue. The Hyperdrive command now supports setting or updating the caching settings:
- Caching Disabled
- Max Age
- SWR
https://developers.cloudflare.com/workers/wrangler/commands/#update

**Comment by petebacondarwin** [comment]
Closing as this appears to be resolved. @rozenmd if there is something still missing please can you reopen.
