### ISSUE TITLE
🐛 BUG: fetch fails with option cors

### ISSUE THREAD

**Issue by dreitzner** [cloudflare/workers-sdk#4159]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.12.0

### What version of Node are you using?

18.17.1

### What operating system are you using?

cloudflare pages

### Describe the Bug

After lates release our fetch calls with the option `mode: cors` fail on clouflare pages with the error message:

`The 'mode' field on 'RequestInitializerDict' is not implemented.`

I just removed the fetch option, but I don't think this is a desired behavior.

**Comment by dreitzner** [comment]
I did remove it, but should a fetch request really fail, because of a key in a config object?

**Comment by admah** [comment]
Closing this as fixed by the PR listed above. If this continues to be an issues, please reopen. Thanks!
