### ISSUE TITLE
Support dynamic lazy imports

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/workers-sdk#417]
Cloudflare workers support imports natively, including runtime `import()` expressions.

So potentially we could lazy load files by uploading such modules as "external" alongside the entry-point file.

Currently, our build process will bundle all static imports (and statically analysable dynamic imports) into the main entry-point bundle: import()-ed modules are wrapped in a function, actually executing the import() executes the inlined code.

One thing this approach doesn't currently support is imports where the module specifier is not known at build time. For example:

**a.js**
```js
export const foo = 'A';
```
**b.js**
```js
export const foo = 'B';
```
**index.js**
```js
async function main() {
  const p = Math.random() > 0.5 ? 'a' : 'b';
  const foo = (await import(`./${p}.js`)).foo;
}
main();
```

This issues tracks the support for being able to do this via Wrangler 2.

**Comment by petebacondarwin** [comment]
Closing as a duplicate of #637, which is a superset of this really.

**Comment by threepointone** [comment]
Actually, it's different. That's about lazy imports (`await import(<string literal>)`), while this is about dynamic imports `(await import(variable)`)

**Comment by penalosa** [comment]
Closing for now, since `--no-bundle` supports this use case. If there isn't an issue already open for tracking the new module work that's in-progress, we should make one.

**Comment by irvinebroque** [comment]
Should the docs for `--no-bundle` be updated to reflect that using `--no-bundle` supports dynamic imports? 

https://developers.cloudflare.com/workers/wrangler/commands/

**Comment by penalosa** [comment]
@irvinebroque Yes, they probably should

**Comment by threepointone** [comment]
Maybe we should reopen this, and make it work even with the bundling usecase
ref: https://github.com/cloudflare/workerd/issues/2372

**Comment by michielkikkert** [comment]
This seems to work, even without --no-bundle combined with a TS worker. I thought I mention it because this issue is still open. If anyone is interested on how to get this to work - please comment and I'll provide some code.

**Comment by j4w8n** [comment]
@michielkikkert I'd love to see some example code for this. I can't figure it out.
