### ISSUE TITLE
🐛 BUG: unit testing mocked KV interactions with vitest

### ISSUE THREAD

**Issue by danfernand** [cloudflare/workers-sdk#4188]
### Which Cloudflare product(s) does this pertain to?

KV

### What version(s) of the tool(s) are you using?

2.17.0

### What version of Node are you using?

18.17.0

### What operating system are you using?

Mac

### Describe the Bug

trying to figure out the best way to mock a KV store locally (make sure the worked fetched from it and attempted a put)

Below is my test in vitest

```
describe("Worker", () => {
  let worker: UnstableDevWorker;

  beforeAll(async () => {
    worker = await unstable_dev("src/index.ts", {
      experimental: {
        disableExperimentalWarning: true,
      },
      local: true,
      vars: {
        MAIN_STORE: {
          get: async (val: string) => {
            if (val === "somekeyinthekv") {
              return Promise.resolve("https://somestoredpage");
            }
            return Promise.resolve();
          },
          put: vi.fn(),
        },
      },
    });
  });
 ...
```

In the worker its trying to get and put in various flows but cannot seem to mock without

```
let value = await env.MAIN_STORE.get(key);
                                           ^
Unhandled Promise Rejection: GET /somekey: TypeError: env.MAIN_STORE.get is not a function
```

### Please provide any relevant error logs

Error provided above

**Comment by petebacondarwin** [comment]
Closing as there is an example of how to do this linked above; moreover we also now support running Vitest tests directly in workerd that gives a high fidelity approach to this sort of testing.
