### ISSUE TITLE
🐛 BUG: `wrangler pages dev` misleading logs WARNING --local is no longer required and will be removed in a future version.

### ISSUE THREAD

**Issue by aroman** [cloudflare/workers-sdk#4210]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler core

### What version(s) of the tool(s) are you using?

3.13.2

### What version of Node are you using?

20

### What operating system are you using?

mac

### Describe the Bug

1) I have a pages project with a single function (worker).

2) run:

`wrangler pages dev  --compatibility-date=2023-10-16 .`

```
Compiling worker to "/private/var/folders/j2/fnbkcp_n5cg4myh9cv5q1xbh0000gn/T/functionsWorker-0.890461344708837.mjs"...
✨ Compiled Worker successfully
 ⛅️ wrangler 3.13.2
-------------------
▲ [WARNING] --local is no longer required and will be removed in a future version.

  `wrangler dev` now uses the local Cloudflare Workers runtime by default. 🎉


⎔ Starting local server...
[mf:inf] Ready on http://0.0.0.0:8788
[mf:inf] - http://127.0.0.1:8788
[mf:inf] - http://192.168.1.14:8788
```

note that meaningless/confusing warning. should be removed.

**Comment by kevinmarrec** [comment]
Having the same issue, (also using `3.13.2`), the warning seems to always show, either you're using `--local` or not.

**Comment by jaswrks** [comment]
➕

**Comment by wasmithee** [comment]
⛅️ wrangler 3.21.0
+1

**Comment by ivanafanasyeu** [comment]
+1 		"wrangler": "^3.22.1"

**Comment by ivanafanasyeu** [comment]
<img width="779" alt="Screenshot 2023-12-25 at 12 40 43" src="https://github.com/cloudflare/workers-sdk/assets/25664253/5184476a-59bf-43e4-9970-ee97d0846d3e">
