### ISSUE TITLE
🐛 BUG: Wrangler v2 does not detect entry point

### ISSUE THREAD

**Issue by ZebraFlesh** [cloudflare/workers-sdk#4250]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

2.20.1 [Wrangler]

### What version of Node are you using?

18.18.2

### What operating system are you using?

macOS 13.5.2 (Ventura)

### Describe the Bug

I am attempting to upgrade from wrangler v1 to v2 and have been following the [upgrade guide](https://developers.cloudflare.com/workers/wrangler/migration/v1-to-v2/update-v1-to-v2/) for my service worker format Workers script. After installing wrangler v2, I made the following modifications to my `wrangler.toml` file:

1. removed `type = "wepback"` field; no other `webpack` configuration was provided (migration use case 2, "I use type = webpack, but do not provide my own configuration and let Wrangler take care of it.)
2. removed the multiple `zone_id` fields
3. added `main = "src/index.js"` to all workers

I tried to execute `wrangler dev` but received the following output:

```
% npx wrangler dev
▲ [WARNING] It looks like you have used Wrangler v1's `config` command to login with an API token.

  This is no longer supported in the current version of Wrangler.
  If you wish to authenticate via an API token then please set the `CLOUDFLARE_API_TOKEN`
  environment variable.


 ⛅️ wrangler 2.20.1 (update available 3.14.0)
-------------------------------------------------------

✘ [ERROR] Missing entry-point: The entry-point should be specified via the command line (e.g. `wrangler dev path/to/script`) or the `main` config field.


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
```

I'm not sure what's going on with the warning, but wrangler definitely cannot find my entry point. My entry point is a standard service worker format:

```
addEventListener('fetch', event => {
  event.passThroughOnException();
  event.respondWith(handleRequest(event));  // handleRequest function defined in same file
});
```

**Comment by Cherry** [comment]
Can you share your `wrangler.toml`? You may also want to consider upgrading to wrangler 3. Upgrading from 2 -> 3 doesn't come with anywhere near the same number of breaking changes and is generally very stable these days.

**Comment by ZebraFlesh** [comment]
Here's a redacted version of my `wrangler.toml` file:

```
account_id = <redacted>
compatibility_date = "2021-10-01"

# DEV
[env.dev]
name = "dev-worker"
main = "src/index.js"
routes = [
<redacted>
]
workers_dev = false

kv-namespaces = [
  <redacted>
]

# DEV VARS
[env.dev.vars]
STAGE = "dev"
# various other env vars <redacted>
```

(All other lines are commented out, but I'm still getting the same 1 warning + 1 error output)

**Comment by Cherry** [comment]
You're currently only defining `main` in your `env.dev` section. Move `main = "src/index.js"` to the top-most section under `compatibility_date `.

You could also pass `wrangler dev --env dev` as another option.

**Comment by ZebraFlesh** [comment]
That fixed it, thanks! Is there a syntax reference for the `wrangler.toml` file anywhere? That would really help. Here's what I consider an excellent version of that and is something I use all the time in other projects: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml

**Comment by Cherry** [comment]
Glad to hear it! https://developers.cloudflare.com/workers/wrangler/configuration/ is going to be your best reference.

**Comment by ZebraFlesh** [comment]
Ah I see what's going on now: my original configuration worked if I ran `wrangler dev --env dev`. Thanks, this clarifies (but doesn't solve) other problems.
