### ISSUE TITLE
🐛 BUG: bundle problem when using googleapis

### ISSUE THREAD

**Issue by mujeebkalwar** [cloudflare/workers-sdk#4253]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.14.0

### What version of Node are you using?

20.6.1

### What operating system are you using?

Mac

### Describe the Bug

Getting http2 not resolved error when using `googleapis` npm package

### Please provide any relevant error logs

```
✘ [ERROR] Could not resolve "http2"

    ../../node_modules/.pnpm/googleapis-common@7.0.0/node_modules/googleapis-common/build/src/http2.js:16:22:
      16 │ const http2 = require("http2");
         │                       ~~~~~~~
         ╵                       "./http2"

  The package "http2" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
````

**Comment by saiorama** [comment]
I'm getting stuck on this issue as well. I'm on wrangler 3.17.1. Using `--node-compat=true` with `nom wrangler dev`

**Comment by MujeebullahKalwar** [comment]
@saiorama
I utilized direct fetch calls to the Google API instead of utilizing the `googleapis` SDK.

**Comment by saiorama** [comment]
In my case, I didn't even need to import `googleapis`. Guess the real upshot is that worker poly fills don't have certain modules that googleapis needs. Therefore, if you want to use googleapis, they should be used your way through `fetch`, not as imports.

**Comment by penalosa** [comment]
I’m going to close this issue for now, since this is a limitation of the `node_compat` system. Going forward, the Workers runtime is working on adding support for more Node.JS builtins. However, it's unlikely we'll add support for `http2` in the near future, and so I'd recommend making direct fetch calls to the relevant Google APIs for now.
