### ISSUE TITLE
🐛 BUG: globalThis.XMLHttpRequest is not a constructor

### ISSUE THREAD

**Issue by MrDiamondDog** [cloudflare/workers-sdk#4254]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

3.14.0 [Wrangler]

### What version of Node are you using?

v18.16.1

### What operating system are you using?

Windows

### Describe the Bug

When using `wrangler deploy`, it will not deploy properly because an error: `Uncaught TypeError: globalThis.XMLHttpRequest is not a constructor`. I have looked at the other issues on this topic, but none of them seem to have a good solution for me. But from looking at them, it looks like I need to polyfill XMLHttpRequest myself, is there a package to do that?

Dependencies:
```
"devDependencies": {
    "@types/express": "^4.17.20",
    "@types/node": "^20.8.7",
    "nodemon": "^3.0.1",
    "tsx": "^3.14.0",
    "typescript": "^5.2.2",
    "wrangler": "^3.14.0"
},
"dependencies": {
    "canvas": "^2.11.2",
    "define-data-property": "^1.1.1",
    "discord-interactions": "^3.4.0",
    "dotenv": "^16.3.1",
    "express": "^4.18.2"
}
```

wrangler.toml
```
name = "discord-bot"
main = "./dist/index.js"
compatibility_date = "2023-10-21"
node_compat = true
```

### Please provide any relevant error logs

```
  Uncaught TypeError: globalThis.XMLHttpRequest is not a constructor
    at worker.js:31375:13 in checkTypeSupport
    at worker.js:31397:40 in
  node_modules/rollup-plugin-node-polyfills/polyfills/http-lib/capability.js
    at worker.js:15:58 in __init
    at worker.js:31662:7 in node_modules/rollup-plugin-node-polyfills/polyfills/http-lib/request.js
    at worker.js:15:58 in __init
    at worker.js:31880:7 in node-modules-polyfills:http
    at worker.js:15:58 in __init
    at worker.js:32000:23 in node-modules-polyfills-commonjs:http
    at worker.js:18:52 in __require2
    at worker.js:32019:18 in node_modules/methods/index.js
   [code: 10021]
```

**Comment by tom-voliyo** [comment]
@MrDiamondDog - I see you've marked this issue as `completed`, though I'm also facing the same issue. Can you confirm whether this has been fixed & deployed, and if not, waht hte work around should be?

**Comment by MrDiamondDog** [comment]
I was using the axios library, which uses XHR under the hood, so I switched to one compatible with workers

**Comment by johnstew** [comment]
I'm experiencing this issue as well. Would be good to document the solution here from Cloudflare's perspective since whenever you enable `node_compat = true` for a worker someone will likely run into this because it's baked into the `rollup-plugin-node-polyfills` which is built into the bundler for all workers by default. Only way I see to fix this right now is to create my own custom build which is possible but I don't think that should be the recommended solution here.

**Comment by johnstew** [comment]
@MrDiamondDog Would you mind reopening the issue?

**Comment by MrDiamondDog** [comment]
@johnstew Ive reopened it, I have since solved this problem myself but I can help you if you need

**Comment by MrDiamondDog** [comment]
@johnstew do you still need this issue open?

**Comment by 772778995** [comment]
I also encountered this problem when I used the `nodemailer`.
Is there a solution now?

**Comment by mephmanx** [comment]
I am running into this issue also trying to use google cloud-storage libraries in a webpack 5 bundled worker

**Comment by MrDiamondDog** [comment]
The solution to this issue is to use a library compatible with workers. If a library is giving this error, it is not compatible with workers.

**Comment by adex-codez** [comment]
I am also facing this issue with a package i am using which uses axios how can i resulve the issue

**Comment by CMCDragonkai** [comment]
Seems to be solved if you update your node compatibility flags. https://developers.cloudflare.com/workers/runtime-apis/nodejs/

**Comment by wesbos** [comment]
I also have an upstream package that uses axios unfortunately. Even with the Node.js compat, http.request and xmlhttprequest are both missing 

Apparently you can just the axios-fetch-adapter package, but that needs to be passed into the dependency somehow

**Comment by penalosa** [comment]
@wesbos you should be able to use the [`alias` property](https://developers.cloudflare.com/workers/wrangler/configuration/#module-aliasing) in Wrangler config to alias specific modules—I wonder if you could alias the `axios` package to a re-export of `axios` that always used the fetch adapter?
