### ISSUE TITLE
🐛 BUG: global is not defined after migrating to v2

### ISSUE THREAD

**Issue by ZebraFlesh** [cloudflare/workers-sdk#4256]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

2.20.1 [Wrangler]

### What version of Node are you using?

18.18.2

### What operating system are you using?

mac

### Describe the Bug

I'm trying to migrate a service worker format of Worker from wrangler v1 to v2. After following the migration guide and running `wrangler dev --env dev`, I'm getting the following output:

```
% % npx wrangler dev --env dev
 ⛅️ wrangler 2.20.1 (update available 3.14.0)
-------------------------------------------------------
▲ [WARNING] Processing wrangler.toml configuration:

  
    - "env.dev" environment configuration
      - Deprecation: "kv-namespaces":
        The "kv-namespaces" field is no longer supported, please rename to "kv_namespaces"


Your worker has access to the following bindings:
- Vars:
  - STAGE: "dev"
⬣ Listening at http://0.0.0.0:8787
- http://127.0.0.1:8787
- http://192.168.4.129:8787
- http://192.168.4.127:8787
Total Upload: 510.52 KiB / gzip: 106.09 KiB
✘ [ERROR] Error on remote worker: ParseError: A request to the Cloudflare API (/accounts/<redacted>/workers/scripts/<redacted>/edge-preview) failed.

      at throwFetchError
  (/Users/<redacted>/cloudflare-workers/node_modules/wrangler/wrangler-dist/cli.js:130780:17)
      at fetchResult
  (/Users/<redacted>/cloudflare-workers/node_modules/wrangler/wrangler-dist/cli.js:130747:5)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async createPreviewToken
  (/Users/<redacted>/cloudflare-workers/node_modules/wrangler/wrangler-dist/cli.js:132729:29)
      at async createWorkerPreview
  (/Users/<redacted>/cloudflare-workers/node_modules/wrangler/wrangler-dist/cli.js:132750:17)
      at async start
  (/Users/<redacted>/cloudflare-workers/node_modules/wrangler/wrangler-dist/cli.js:151903:34) {
    text: 'A request to the Cloudflare API
  (/accounts/<redacted>/workers/scripts/<redacted>/edge-preview)
  failed.',
    notes: [
      {
        text: 'Uncaught ReferenceError: global is not defined\n' +
          '  at worker.js:7031:20\n' +
          '  at worker.js:12211:3\n' +
          ' [code: 10021]'
      }
    ],
    location: undefined,
    kind: 'error',
    code: 10021
  }
```

It's a generally unhelpful error message since it doesn't tell me the source of the error. I'm _guessing_ this is due to various pieces of code that are trying to access environment variables via lines such as:
```
const stage = global.STAGE;
```

I expected this code to "just work" since it worked under wrangler 1. (I did RTM to see if there's a suggested way of accessing environment variables, but [the docs](https://developers.cloudflare.com/workers/configuration/environment-variables/) talk in terms of Typescript, which I'm not using.)

**Comment by ZebraFlesh** [comment]
Updated to clarify that the environment variables are all defined ... or at least, they seem to be: I'm not seeing a report of any encrypted secrets. I guess I would have expected output like `XYZ: <encrypted>` to indicated that `XYZ` was known to the script?

**Comment by Cherry** [comment]
How were you building your worker in wrangler v1? Using webpack? No bundling at all? Do you have an example of what your `wrangler.toml` looked like in v1 and in v2, and some minimal code to reproduce this?

**Comment by Cherry** [comment]
If you're still using service worker format though, you should be able to access your environment variables simply as globals. So `STAGE`, rather than `global.STAGE`.

I would definitely recommend you consider migrating to Modules format when you can though: https://developers.cloudflare.com/workers/learning/migrate-to-module-workers/

**Comment by Cherry** [comment]
Were you previously using webpack, via a `webpack.config.js` with wrangler 1? It seems webpack polyfills the node.js `global` by default as per https://webpack.js.org/api/module-variables/#global-nodejs.

esbuild doesn't do this, but if you follow my previous comment, you should be able to get this working by simply removing `global.` from your env vars.

**Comment by ZebraFlesh** [comment]
The only webpack config we used in v1 was:

```
type = "webpack"
```

No other options or custom webpack config.

> you should be able to access your environment variables simply as globals
Sure, but we made this change so we could easily exclude various values from linting (e.g., env variables, KV namespaces, etc). I'm trying to find the backwards compatible path forward that doesn't require me to touch (and then validate) 400 lines of code.

> I would definitely recommend you consider migrating to Modules format
Given that this is about 20K lines of code, that will take some doing. I think it's reasonable to finish the v1 -> v2 migration before contemplating this change.

**Comment by Cherry** [comment]
Using `type=webpack` alone would have been enough to get the `global` polyfill as this is default with webpack, but not in esbuild.

Outside of a custom build or migrating, your quickest course of action here would likely be to enable `node_compat` mode within wrangler:
https://developers.cloudflare.com/workers/wrangler/configuration/#add-polyfills-using-wrangler. 

You'll need to add `node_compat` to your `wrangler.toml` (likely every env), and this should hopefully provide you with the `global` you're looking for again.

**Comment by ZebraFlesh** [comment]
> You could possibly find and replace `global.` with `globalThis.`

Thanks, this seems to work reasonably well. (At least for now -- I still have jest issues to wrestle with, and things may go sideways there.)
