### ISSUE TITLE
🐛 BUG: Analytics Engine `writeDataPoint` not available locally

### ISSUE THREAD

**Issue by cezarsmpio** [cloudflare/workers-sdk#4258]
### Which Cloudflare product(s) does this pertain to?

Other

### What version(s) of the tool(s) are you using?

3.14.0 [Wrangler]

### What version of Node are you using?

18.18.2

### What operating system are you using?

Mac

### Describe the Bug

Trying to use Analytics Engine locally via `wrangler dev` (v3.14.0) but I get the following error:

```
TypeError
Cannot read properties of undefined (reading 'writeDataPoint') 
```

My `wrangler.toml` file:
```
[[analytics_engine_datasets]]
binding = "analyticsEngineDataset"
```

My code:
```
env.analyticsEngineDataset.writeDataPoint({
        blobs: [user.city, user.country],
        doubles: [order.amount],
	indexes: [user.id],
});
```

### Please provide any relevant error logs

![image](https://github.com/cloudflare/workers-sdk/assets/954889/5193b096-0dc7-4911-9f0b-37bbd4584637)

**Comment by penalosa** [comment]
Thanks for reporting this! Unfortunately Analytics Engine isn't currently supported in `wrangler dev`—you can follow https://github.com/cloudflare/miniflare/issues/278 to see progress on it's implementation
