### ISSUE TITLE
🐛 BUG: ✘ [ERROR] This command cannot be run in a non-interactive context

### ISSUE THREAD

**Issue by bigxalx** [cloudflare/workers-sdk#4263]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

^3.0.0

### What version of Node are you using?

v18.18.2

### What operating system are you using?

Mac

### Describe the Bug

I tried following the Getting Started Tutorial: https://developers.cloudflare.com/workers/get-started/guide/

When i run `npm create cloudflare@latest` I choose a directory, choose "Hello World" Worker, and choose Typescript "yes". 
The script fails with 

✘ [ERROR] This command cannot be run in a non-interactive context
 ⛅️ wrangler 3.14.0
-------------------
Total Upload: 0.19 KiB / gzip: 0.16 KiB
▲ [WARNING] You need to register a workers.dev subdomain before publishing to workers.dev

? Would you like to register a workers.dev subdomain now?
🤖 Using default value in non-interactive context: yes

✘ [ERROR] This command cannot be run in a non-interactive context

If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose

**Comment by dario-piotrowicz** [comment]
@bigxalx thanks for the issue 🙂

This is something we've already noticed and know what we need to fix (it does need changes both in wrangler and C3 unfortunately) sorry for the inconvenience 🙇 

In the meantime to get C3 to work for you, you'll need to set up your workers.dev subdomain, you can do that by manually deploying your worker via wrangler (by running `npx wrangler deploy` inside the worker's directory), that should have the proper interactive prompt and let you create the subdomain.

Alternatively you can just deploy a worker via the [Cloudflare dashboard](https://dash.cloudflare.com/) and that should set up your subdomain automatically for you.

___

Related to: https://github.com/cloudflare/workers-sdk/issues/4187

**Comment by dario-piotrowicz** [comment]
Note to self: check if this issue has already been addressed, if not, understand what work needs to be done and on which side (wrangler or c3)

**Comment by michaelparkadze** [comment]
@dario-piotrowicz as of today this issue is still happening.
