### ISSUE TITLE
🐛 BUG: Wrangler is injecting development code in production builds

### ISSUE THREAD

**Issue by Skye-31** [cloudflare/workers-sdk#4269]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.14.0

### What version of Node are you using?

v18.17.0

### What operating system are you using?

Mac

### Describe the Bug

Wrangler has started injecting some sort of "modules watch" code into production builds, when it shouldn't be. These functions are getting called for every import that is made in your worker script, which has an increase in both script size of ~5kb, and script startup time.

```
// wrangler-modules-watch:wrangler:modules-watch
var init_wrangler_modules_watch = __esm({
  "wrangler-modules-watch:wrangler:modules-watch"() {
    init_modules_watch_stub();
  }
});

// node_modules/.pnpm/wrangler@3.14.0/node_modules/wrangler/templates/modules-watch-stub.js
var init_modules_watch_stub = __esm({
  "node_modules/.pnpm/wrangler@3.14.0/node_modules/wrangler/templates/modules-watch-stub.js"() {
    init_wrangler_modules_watch();
  }
});
```

This behaviour started occurring in 3.11.0, and didn't occur in 3.10.0, so I'm almost certain it's the result of https://github.com/cloudflare/workers-sdk/pull/3726, cc @petebacondarwin 

### Please provide a link to a minimal reproduction

Any worker that imports anything -> `npx wrangler deploy --outdir dist`, look at the outputted code to see these files which shouldn't be present

**Comment by petebacondarwin** [comment]
It appears this code is only added if esbuild is having to deal with a Common JS import. If all the code in a Worker is ESM then this virtual module gets stripped from the output.
