### ISSUE TITLE
🐛 BUG: npm create cloudflare@latest throwing error ENOENT: no such file or directory, open 'D:\@cloudflare\workers-types\package.json'

### ISSUE THREAD

**Issue by naveedahmed1** [cloudflare/workers-sdk#4282]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

C3

### What version of Node are you using?

v18.18.2

### What operating system are you using?

Windows

### Describe the Bug

I just tried creating an Angular project using the command `npm create cloudflare@latest` but its throwing below error:

```
├ Installing adapter dependencies
│ npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\@cloudflare\workers-types/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\@cloudflare\workers-types\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\abc\AppData\Local\npm-cache\_logs\2023-10-25T17_06_45_80
0Z-debug-0.log

```

I was creating the project in `D:\dir1\dir2\myproject` .

### Please provide any relevant error logs

```
├ Installing adapter dependencies
│ npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\@cloudflare\workers-types/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\@cloudflare\workers-types\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\abc\AppData\Local\npm-cache\_logs\2023-10-25T17_06_45_80
0Z-debug-0.log

```

**Comment by naveedahmed1** [comment]
The issue still persists with `create-cloudflare version 2.6.2`

**Comment by gusdleon** [comment]
I can confirm running C3 on windows 10 

- Type of app: `Website or web app`
- Framework: `Next`
- Template used: `default-tw`
-  use the next-on-pages eslint-plugin: `Yes`

The error happens after selecting yes in that last step
Logfile:
[C3-nextapp-bug.log](https://github.com/cloudflare/workers-sdk/files/13234407/C3-nextapp-bug.log)

**Comment by mavsoares** [comment]
Same here. Can't create the project in Windows by running `npm create cloudflare@latest my-angular-app -- --framework=angular`

```
Error: npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\@cloudflare\workers-types/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\@cloudflare\workers-types\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by naveedahmed1** [comment]
Are there any docs which guide on how to setup and deploy it manually without relying on cli?

**Comment by petebacondarwin** [comment]
I can reproduce this on my own Windows machine. Will work on diagnosing the bug today.

**Comment by taylorgibb** [comment]
Is there any workaround for this ?

**Comment by mavsoares** [comment]
You can create your project using Angular CLI.

**Comment by naveedahmed1** [comment]
> You can create your project using Angular CLI.

Can you please guide? We cant deploy a normal Angular cli project with SSR to workers/pages directly, right?

**Comment by mavsoares** [comment]
I created a project using Angular CLI, deployed to cloudflare, and it
worked fine on Pages. Didn't test with workers.

Basic command:  ng new project-name

Atenciosamente,
Marcos

**Comment by naveedahmed1** [comment]
How about SSR?

And how did you deploy it to pages? If you could please share the exact steps/commands?

**Comment by mavsoares** [comment]
I didnt use SSR. And just deployed by pushing code to github, where it was
hosted.

Atenciosamente,
Marcos
