### ISSUE TITLE
🐛 BUG: ENOENT: no such file or directory error after version bump

### ISSUE THREAD

**Issue by drdreo** [cloudflare/workers-sdk#4286]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.14.0

### What version of Node are you using?

18.18.2

### What operating system are you using?

Linux

### Describe the Bug

Running wrangler deploy in the Azure pipeline fails after dependabot updates wrangler to `3.14.0`. Previous version that works is `"wrangler": "2.4.2"`

deploy script:
```
npx wrangler pages publish dist/apps/project--project-name=project-preview --commit-dirty=false --branch=dependabot/npm_and_yarn/wrangler-and-undici-and-wrangler-2.20.1
```

### Please provide any relevant error logs

```
node:internal/fs/utils:350
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/vsts/work/1/s/node_modules/Cloudflare_CA.pem'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at runWrangler (/home/vsts/work/1/s/node_modules/.bin/wrangler:49:8)
    at Object.<anonymous> (/home/vsts/work/1/s/node_modules/.bin/wrangler:115:20)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/vsts/work/1/s/node_modules/Cloudflare_CA.pem'
}

Node.js v18.18.2
##[error]Bash exited with code '1'.
Finishing: Deploy to Cloudflare Pages
```

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to provide a reproduction repo that demonstrates the issue?

**Comment by drdreo** [comment]
Unfortunately we have since migrated away from Azure Pipelines and utilize GitHub Actions. This has not been an issue on the new CI system with version `"wrangler": "3.33.0"`
I have no longer access to the old pipelines to re-create a repository with the exact conditions.

I hope I have not caused too much troubles and appreciate you looking into it. Can be closed from my side.

**Comment by petebacondarwin** [comment]
Thanks for the update. Closing for now.
