### ISSUE TITLE
🐛 BUG: workers.api.error.no_access_to_vectorize [code: 100158]

### ISSUE THREAD

**Issue by midshipman** [cloudflare/workers-sdk#4295]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

wrangler 3.15.0, 

### What version of Node are you using?

Node.js v20.0.0

### What operating system are you using?

mac

### Describe the Bug

I followed this guide

https://developers.cloudflare.com/workers-ai/tutorials/build-a-retrieval-augmented-generation-ai/

but got the error in step 7, no clue about error code 100158

**Comment by penalosa** [comment]
From the Vectorize docs (https://developers.cloudflare.com/vectorize/get-started/intro/) it looks like Vectorize is currently only enabled for Workers Paid plans:
> Vectorize is in public beta
> Vectorize is currently in public beta and is enabled for all developers on Workers Paid plans. During the beta, you may run into bugs and instability which may make it unsuitable for production-facing workloads.
