### ISSUE TITLE
🐛 BUG: Could not resolve "@cloudflare/ai"

### ISSUE THREAD

**Issue by midshipman** [cloudflare/workers-sdk#4297]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

wrangler 3.15.0, 

### What operating system are you using?

mac

### Describe the Bug

I tried work AI for pages via bindings and got the error when deploying from github.

It seems 'npm install @cloudflare/ai' does not work, I run this under /functions in the project folder, then push to github. Is it a bug or I missed anything?

thanks

https://developers.cloudflare.com/pages/platform/functions/bindings/

### Please provide any relevant error logs

21:20:46.889 | Found Functions directory at /functions. Uploading.
-- | --
21:20:48.570 | ✘ [ERROR] 1 error(s) and 0 warning(s) when compiling Worker.
21:20:48.571 |  
21:20:48.571 |  
21:20:48.573 |  
21:20:48.575 | ✘ [ERROR] Could not resolve "@cloudflare/ai"
21:20:48.575 |  
21:20:48.576 | hello.js:1:19:
21:20:48.576 | 1 │ import { Ai } from '@cloudflare/ai'
21:20:48.576 | ╵                    ~~~~~~~~~~~~~~~~
21:20:48.576 |  
21:20:48.576 | You can mark the path "@cloudflare/ai" as external to exclude it from the bundle, which will remove this error.
21:20:48.576 |  
21:20:48.576 |  
21:20:48.578 | ✘ [ERROR] Build failed with 1 error:
21:20:48.578 |  
21:20:48.579 | hello.js:1:19: ERROR: Could not resolve "@cloudflare/ai"
21:20:48.579 |  
21:20:48.579 |  
21:20:48.592 | Failed building Pages Functions.
21:20:49.525 | Failed: an internal error occurred. If this continues, contact support: https://cfl.re/3WgEyrH

**Comment by penalosa** [comment]
@midshipman Could you provide a link to your repo/a minimal reproduction? Workers AI should work with Pages. One thing you could try is running `npm install @cloudflare/ai` at the root of your repo, rather than within the `functions` folder?

**Comment by lrapoport-cf** [comment]
hi @midshipman :) we haven't heard from you in a while, so we’re going to close this issue for now. If this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary, repro, and any additional requested details and we will revisit and investigate further. thanks!
