### ISSUE TITLE
🐛 BUG: unable to create temp view or temp table

### ISSUE THREAD

**Issue by luxint** [cloudflare/workers-sdk#4298]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

2.6.2

### What version of Node are you using?

v16.18.1

### What operating system are you using?

Linux

### Describe the Bug

I get 'not authorized [code: 7500]' when trying to create a temp view in a newly created database. This is possible in the older databases i created.

**Comment by andyjessop** [comment]
@rozenmd do you have a view on whether or not D1 should support temp tables?

**Comment by andyjessop** [comment]
@rozenmd just a ping as this issue has been added to your project as "selected for development".

**Comment by rozenmd** [comment]
@andyjessop unfortunately the repo's automation incorrectly moves issues into "selected for development" when issues are tagged with `d1`, an "untriaged" status would be helpful here

temp tables are explicitly unauthorised in workerd: https://github.com/cloudflare/workerd/blob/c5ebbe29e3b3bcc5b2009b399074fdaca703e865/src/workerd/util/sqlite.c%2B%2B#L704

For future readers: If your use case requires temp tables, I'd recommend opening an issue in the workerd repo: https://github.com/cloudflare/workerd/issues
