### ISSUE TITLE
🐛 BUG: Logpoints don’t resolve variable names from source maps (VS Code & Chrome)

### ISSUE THREAD

**Issue by huw** [cloudflare/workers-sdk#4301]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.15.0 [Wrangler]

### What version of Node are you using?

20.8.1

### What operating system are you using?

Linux (Ubuntu 20.04)

### Describe the Bug

Start by creating a rudimentary worker __with `minify = true` in your `wrangler.toml`__:

```ts
export default {
  fetch: async () => {
    const text = "OK";
    return new Response(text);
  },
};
```

Add a logpoint on the `return` line that logs `text` (in Chrome, just add a plain logpoint with `text`; in VS Code, add `{text}`). Start `wrangler dev`, attach a debugger (Chrome or VS Code), and run the code.

In VS Code, it will output:
```
'ReferenceError: text is not defined\n' +
  '    at eval (logpoint-c9ec1b7.cdp:3:5)\n' +
  '    at eval (logpoint-c9ec1b7.cdp:7:3)\n' +
  '    at Object.fetch (file:///workspaces/test/package/debugging/.wrangler/tmp/dev-4ny7aX/index.js:3:338)\n' +
  '    at g (file:///workspaces/test/package/debugging/.wrangler/tmp/dev-4ny7aX/index.js:3:1055)\n' +
  '    at _ (file:///workspaces/test/package/debugging/.wrangler/tmp/dev-4ny7aX/index.js:3:202)\n' +
  '    at Object.next (file:///workspaces/test/package/debugging/.wrangler/tmp/dev-4ny7aX/index.js:3:239)\n' +
  '    at b (file:///workspaces/test/package/debugging/.wrangler/tmp/dev-4ny7aX/index.js:3:531)\n' +
  '    at _ (file:///workspaces/test/package/debugging/.wrangler/tmp/dev-4ny7aX/index.js:3:202)\n' +
  '    at m (file:///workspaces/test/package/debugging/.wrangler/tmp/dev-4ny7aX/index.js:3:284)\n' +
  '    at Object.fetch (file:///workspaces/test/package/debugging/.wrangler/tmp/dev-4ny7aX/index.js:3:1493)'
```

In Chrome, it will output:
```
 ReferenceError: text is not defined
    at eval (VM11 logpoint:1:38)
    at Object.fetch (index.ts:4:5)
    at g (middleware-loader.entry.ts:46:16)
    at _ (common.ts:53:9)
    at Object.next (common.ts:50:11)
    at b (middleware-miniflare??json-error.ts:22:30)
    at _ (common.ts:53:9)
    at m (common.ts:63:9)
    at Object.fetch (middleware-loader.entry.ts:114:11)
```

Disabling `minify` fixes this behaviour. Alternatively, it is possible to inspect the compiled `.wrangler/tmp/dev-4ny7aX/index.js` file and look for the variable. In my case it was being transpiled to `e`. Changing the logpoint to log `{e}` succeeds in both cases, which indicates that the logpoints aren’t following the source maps.

I think `minify = false` in dev mode is a reasonable workaround. I am not sure if this is a `workerd` issue or not.

**Comment by huw** [comment]
I am also seeing a related error with `minify = true` where clicking ‘next’ in either debugger often skips lines. Turning `minify` off also resolves this. I’m assuming that it’s trying to move to the next symbol in the minified file and is struggling with that; resolving the above would probably resolve the same thing so I won’t split it out into a separate issue but worth noting.

**Comment by penalosa** [comment]
Unfortunately I think this is an issue with the upstream VSCode debugger and Chrome DevTools debugger. Chrome now has an experimental option called "Resolve variable names in expressions using source maps" which fixes this behaviour—hopefully VSCode will add similar support soon.
