### ISSUE TITLE
🐛 BUG:Received a malformed response from the API    

### ISSUE THREAD

**Issue by bbright-lokesh** [cloudflare/workers-sdk#4332]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms

### What version(s) of the tool(s) are you using?

3.15.0

### What version of Node are you using?

20.6.1

### What operating system are you using?

windows

### Describe the Bug

im trying to connect the hyperdrive to the postgres database but it gives error messages and some bugs

**Comment by penalosa** [comment]
This is likely a consequence of https://www.cloudflarestatus.com/incidents/hm7491k53ppg—could you try again?

If it's not resolved, feel free to comment with more details (error logs etc...) and we can investigate further
