### ISSUE TITLE
🚀 Feature Request: add Queue Produces support for Pages Dev

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/workers-sdk#4336]
### Describe the solution

Queue Producers can't currently be interacted with locally when using `wrangler pages dev`, as mentioned in our docs:
https://developers.cloudflare.com/pages/platform/functions/bindings/#interact-with-your-queue-producer-binding-locally

However Miniflare does provide support for them: https://github.com/cloudflare/workers-sdk/tree/main/packages/miniflare#queues

So supporting them in `wrangler pages dev` should be possible.

**Comment by admah** [comment]
@dario-piotrowicz is this still valid? We do now support [Queue Producers](https://developers.cloudflare.com/pages/functions/bindings/#queue-producers) locally via Pages, but not consumers.

**Comment by dario-piotrowicz** [comment]
@admah no I guess this is no longer valid then, thanks for pinging me, I'm happy to close the issue 🙂👍

**Comment by treeder** [comment]
What's the flag for binding queues locally?  It's not in the `--help` or in the docs. eg: for d1 it's `--d1`
