### ISSUE TITLE
🐛 BUG: Hyperdrive config is giving timeout during the deploy

### ISSUE THREAD

**Issue by bbright-dinesh** [cloudflare/workers-sdk#4338]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms, Workers Runtime

### What version(s) of the tool(s) are you using?

3.15.0

### What operating system are you using?

Windows

### Describe the Bug

I created a hyperdrive config to the PG instance which is TLS enabled.
It was working fine.

Today we tried to deploy the API again but we are getting below error.

X [ERROR] A request to the Cloudflare API (/accounts/xxxx/workers/scripts/wispy-voice-5006) failed.

  binding HYPERDRIVE of type hyperdrive failed to generate: Failed to perform request against
  sqc-config: Get
  "https://sqc-config-production.sd.cfplat.com/apiv4/internal/databases/xxxx/binding-user":
  context deadline exceeded (Client.Timeout exceeded while awaiting headers). [code: 10021]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

**Comment by ambrt** [comment]
It might be related to ongoing issue at cloudflare https://www.cloudflarestatus.com/incidents/hm7491k53ppg

**Comment by bbright-dinesh** [comment]
Thanks, its resolved
