### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by adshrink** [cloudflare/workers-sdk#4340]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

wrangler 3.15

### What version of Node are you using?

8.19.2

### What operating system are you using?

Mac

### Describe the Bug

A request to the Cloudflare API (/accounts/{ID}/workers/scripts/{Worker-NAME) failed.

  binding DB of type d1 failed to generate. Please try again later or contact support.
  [code: 10021]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

### Please provide any relevant error logs

In local works fine, also in production, now wrangler tell me that isn't valid, but, there are also some Scheduled maintenance today 3 nov

**Comment by adshrink** [comment]
wrangler d1 execute networkloop --command='SELECT * FROM Customers'

🌀 Mapping SQL input into an array of statements
🌀 Parsing 1 statements
🌀 Executing on networkloop (d38dc410-ab11-42f2-ad97-fd8bc6dfb56e):

✘ [ERROR] Received a malformed response from the API

  <!DOCTYPE html>
  
  <!--[if I... (length = 6433)

  POST
  /accounts/55261eacfb61dc9497adf0dbf499a695/d1/database/d38dc410-ab11-42f2-ad97-fd8bc6dfb56e/query
  -> 504 Gateway Time-out
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

**Comment by penalosa** [comment]
This is likely a consequence of [https://www.cloudflarestatus.com/incidents/hm7491k53ppg](https://www.cloudflarestatus.com/incidents/hm7491k53ppg)—could you try again?

If it's not resolved, feel free to comment with more details (error logs etc...) and we can investigate further
