### ISSUE TITLE
🐛 BUG: Wrangler Init Error During Adding the Cloudflare Pages adapter

### ISSUE THREAD

**Issue by Dqgs** [cloudflare/workers-sdk#4342]
### Which Cloudflare product(s) does this pertain to?

Other

### What version(s) of the tool(s) are you using?

3.15.0

### What version of Node are you using?

v20.9.0

### What operating system are you using?

Windows

### Describe the Bug

when trying to create a new project with the template of svelte or any other template such as nextjs it will error at the adding cloudflare page adapters

### Please provide any relevant error logs

`wrangler init
 ⛅️ wrangler 3.15.0
-------------------
Using npm as package manager.
▲ [WARNING] The `init` command is no longer supported. Please use `npm create cloudflare\@2` instead.

  The `init` command will be removed in a future version.

Running `npm create cloudflare\@2`...

using create-cloudflare version 2.6.2

╭ Create an application with Cloudflare Step 1 of 3
│
├ In which directory do you want to create your application?
│ dir ./nameless-dust-67aa
│
├ What type of application do you want to create?
│ type Website or web app
│
├ Which development framework do you want to use?
│ framework Next
│

√ Would you like to use TypeScript? ... No / Yes
√ Would you like to use ESLint? ... No / Yes
√ Would you like to use Tailwind CSS? ... No / Yes
√ Would you like to use `src/` directory? ... No / Yes
√ Would you like to use App Router? (recommended) ... No / Yes
√ Would you like to customize the default import alias? ... No / Yes
Creating a new Next.js app in C:\Users\name\OneDrive\Desktop\asdasasddasdasasdasdasdasdasd\nameless-dust-67aa.

Using npm.

Initializing project with template: app-tw

Installing dependencies:
- react
- react-dom
- next
- typescript
- @types/react
- @types/node
- @types/react-dom
- tailwindcss
- postcss
- autoprefixer
- eslint
- eslint-config-next

added 330 packages, and audited 331 packages in 11s

116 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
Initialized a git repository.

A new version of `create-next-app` is available!
You can update by running: npm i -g create-next-app

╭ Configuring your application for Cloudflare Step 2 of 3
│
├ Created an example API route handler
│
├ Do you want to use the next-on-pages eslint-plugin?
│ yes eslint-plugin
│
├ Adding the Cloudflare Pages adapter
│ npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\@cloudflare\next-on-pages\@1/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\@cloudflare\next-on-pages\@1\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\name\AppData\Local\npm-cache\_logs\2023-11-03T20_57_47_020Z-debug-0.log

│
Error: npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\@cloudflare\next-on-pages\@1/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\@cloudflare\next-on-pages\@1\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\name\AppData\Local\npm-cache\_logs\2023-11-03T20_57_47_020Z-debug-0.log

npm ERR! code 1
npm ERR! path C:\Users\name\OneDrive\Desktop\asdasasddasdasasdasdasdasdasd
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-cloudflare

npm ERR! A complete log of this run can be found in: C:\Users\name\AppData\Local\npm-cache\_logs\2023-11-03T20_57_16_170Z-debug-0.log

✘ [ERROR] Command failed with exit code 1: npm create cloudflare@2

If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose

C:\Users\name\OneDrive\Desktop\asdasasddasdasasdasdasdasdasd>wrangler version
 ⛅️ wrangler 3.15.0
-------------------

C:\Users\name\OneDrive\Desktop\asdasasddasdasasdasdasdasdasd>node -v
v20.9.0`

**Comment by 1000hz** [comment]
Thanks for the report! This has been reported a few times, so I'm gonna consolidate some issues and close this ticket as a duplicate of https://github.com/cloudflare/workers-sdk/issues/4425, to be fixed by #4445.
