### ISSUE TITLE
🐛 BUG: `[ERROR] near "(": syntax error`

### ISSUE THREAD

**Issue by dr-vortex** [cloudflare/workers-sdk#4343]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3.15.0

### What version of Node are you using?

18.18.0

### What operating system are you using?

Window (Git Bash)

### Describe the Bug

```
wrangler d1 execute linden --local --command='CREATE TABLE `accounts` (
  `id` tinytext NOT NULL,
  `username` varchar(32) NOT NULL,
  `disabled` tinyint(1) NOT NULL DEFAULT 0,
  `email` varchar(255) NOT NULL,
  `password` tinytext NOT NULL,
  `oplvl` tinyint(4) NOT NULL DEFAULT 0,
  `created` timestamp NOT NULL DEFAULT current_timestamp(),
  `lastchange` timestamp NOT NULL DEFAULT current_timestamp(),
  `token` tinytext NOT NULL DEFAULT '',
  `session` tinytext NOT NULL DEFAULT ''
);'
🌀 Mapping SQL input into an array of statements
🌀 Executing on local database linden (2a651900-b5fd-457b-b366-c3d44fed20ec) from .wrangler\state\v3\d1:

X [ERROR] near "(": syntax error
```

This also fails if the backticks are removed:

```
wrangler d1 execute linden --local --command='CREATE TABLE accounts (
  id tinytext NOT NULL,
  username varchar(32) NOT NULL,
  disabled tinyint(1) NOT NULL DEFAULT 0,
  email varchar(255) NOT NULL,
  password tinytext NOT NULL,
  oplvl tinyint(4) NOT NULL DEFAULT 0,
  created timestamp NOT NULL DEFAULT current_timestamp(),
  lastchange timestamp NOT NULL DEFAULT current_timestamp(),
  token tinytext NOT NULL DEFAULT '',
  session tinytext NOT NULL DEFAULT ''
);'
🌀 Mapping SQL input into an array of statements
🌀 Executing on local database linden (2a651900-b5fd-457b-b366-c3d44fed20ec) from .wrangler\state\v3\d1:

X [ERROR] near "(": syntax error
```

### Please provide any relevant error logs

env WRANGLER_LOG=debug, export WRANGLER_LOG=debug, set WRANGLER_LOG=debug, etc. Do not change the output.

**Comment by admah** [comment]
Thanks for filing this issue. It looks like this is because of the use of `current_timestamp()`. When I remove that command and run this it is successful:

`wrangler d1 execute linden --local --command "CREATE TABLE IF NOT EXISTS accounts (
  id tinytext NOT NULL,
  username varchar(32) NOT NULL,
  disabled tinyint(1) NOT NULL DEFAULT 0,
  email varchar(255) NOT NULL,
  password tinytext NOT NULL,
  oplvl tinyint(4) NOT NULL DEFAULT 0,
  created timestamp NOT NULL,
  lastchange timestamp NOT NULL,
  token tinytext NOT NULL DEFAULT '',
  session tinytext NOT NULL DEFAULT ''
);"`

cc: @rozenmd

**Comment by dr-vortex** [comment]
@admah I found that as well after over an hour of scratching my head on it.

More verbose error messages would be useful. Perhaps those could get added?

Also, will `functions()` be supported as default values?

**Comment by rozenmd** [comment]
D1 uses SQLite under the hood, you'll want to use `CURRENT_TIMESTAMP` instead of MySQL's `current_timestamp()`

**Comment by dr-vortex** [comment]
Thanks!

**Comment by dr-vortex** [comment]
Can the error messages be more descriptive? Doing so would be helpful for debugging.

**Comment by rozenmd** [comment]
It does seem like we're trimming errors coming from sqlite prematurely, will investigate

**Comment by dr-vortex** [comment]
Closing this as complete as since the original issue has been resolved.
