### ISSUE TITLE
Improve experience with multiple accounts

### ISSUE THREAD

**Issue by Electroid** [cloudflare/workers-sdk#435]
If your credentials have access to multiple accounts, it becomes annoying to use the account selector on each run. Ideally, we should only ask for an account ID, once per project. Here's what that might look like:

* If an `account_id` is specified in the `wrangler.toml`, that is always used.
   * Give a friendly error if the credentials don't have access to that `account_id`.
* If no `account_id` is specified:
  * If credentials have access to 1 account, continue with that account, but don't append the `account_id`.
  * If credentials have access to multiple accounts, prompt for an account, then append `account_id` to the `wrangler.toml`.

**Comment by petebacondarwin** [comment]
Everything except for the following has been done here.

>  then append account_id to the wrangler.toml.

This is because we are not currently in a position to automatically update the wrangler.toml, which is being tracked in #74
