### ISSUE TITLE
Queue configuration incorrectly read

### ISSUE THREAD

**Issue by jasonkuhrt** [cloudflare/workers-sdk#4351]
### Which Cloudflare product(s) does this pertain to?

Queues

### What version(s) of the tool(s) are you using?

3.15.0

### What version of Node are you using?

18.14.0

### What operating system are you using?

14

### Describe the Bug

![CleanShot 2023-11-06 at 14 40 48@2x](https://github.com/cloudflare/workers-sdk/assets/284476/1526db67-0532-44c9-b6ad-44e1d9fc54a4)

**Comment by KianNH** [comment]
This is an unfortunate scenario where you have Wrangler's environments with their own inheritance rules, and TOML's own inheritance rules.

TOML tables, which is indicated by the square brackets (`[table]` or `[[arrayOfTables]]`), inherit anything below them up until *another table* or end of file. That's to say, if you had a file like this...

```toml
[env.dev]

[vars]
foo = "bar"
```

You haven't defined `env.dev.vars`, you've defined `env.dev` and a top-level `vars`. It might be easier to visualise if I convert it to JSON.

```json
{
  "env": {
    "dev": {}
  },
  "vars": {
    "foo": "bar"
  }
}
```

As such, you have two options for having your `vars` correctly under `env.dev`.

A) Use inline tables.

```toml
[env.dev]
vars = { foo = "bar" }
```

B) Add the environment into the name of the table.

```toml
[env.dev.vars]
foo = "bar"
```

**Comment by jasonkuhrt** [comment]
Thanks @KianNH!
