### ISSUE TITLE
🐛 BUG: Improper wrangler behavior when using --from-dash

### ISSUE THREAD

**Issue by celestialemily** [cloudflare/workers-sdk#4352]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

Wrangler 3.15.0

### What version of Node are you using?

20.9.0

### What operating system are you using?

Windows 11

### Describe the Bug

When initializing a local folder based on an already published worker using `--from-dash`, the following behaviors occur:
1. After selecting "no" regarding whether the user would like to use Typescript, Wrangler sets the file extension of the main file to `.ts`, instead of `.js`. Wrangler should correctly recognize that the user does not want to use Typescript, and change the file extension accordingly, both in the folder hierarchy and in `wrangler.toml`.

2. If the user has migrated their Workers usage model to "standard", Wrangler places `usage_model = "standard"` within `wrangler.toml`. This is incorrect behavior, because `usage_model` is now legacy, and should simply be omitted from `wrangler.toml` when the given worker is on the "standard" usage model.

**Comment by admah** [comment]
@celestialemily thanks for filing this issue. We'll take a look and update accordingly.

**Comment by celestialemily** [comment]
Fixed in #4470 , thank you so much!
