### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by jamidwyer** [cloudflare/workers-sdk#4353]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

3.15.0 [Wrangler]

### What version of Node are you using?

16.13.0

### What operating system are you using?

Mac

### Describe the Bug

**What we want:**

Save routes for a worker in wrangler.toml (for version control).

**What we tried:**

1. Add the routes to wrangler.toml like:

```
routes = [
  { pattern = "www.example.com/ko/lists/*", zone_name = "example.com"},
...
  { pattern = "www.example.com/lists/*", zone_name = "example.com"}
]
```
2. Run `wrangler deploy`

**What we see:**

```
Uploaded example-page-worker (1.65 sec)

✘ [ERROR] A request to the Cloudflare API (/accounts/hash/workers/scripts/example-page-worker/routes) failed.

workers.api.error.route_not_allowed_on_subdomain [code: 10038]
```

And new routes we've added to wrangler.toml are not in the Cloudflare UI. 

The same routes do work when we manually add them to the worker in the UI. Am I doing something wrong? I don't see any sign of that error message on the entire Internet. :)

**Comment by penalosa** [comment]
This error happens when you try to use a `workers.dev` zone for a Worker route. If you want your worker to run on your `*.workers.dev` subdomain, you can set `workers_dev = true` in your `wrangler.toml`.

If your `zone_name` doesn't look like `*.workers.dev`, feel free to comment with more details and we can investigate further.

**Comment by jamidwyer** [comment]
Thank you. The `zone_name` does look like example.com. I'm not a networking expert, but I'm happy to get any additional details that would be helpful.

**Comment by jamidwyer** [comment]
I think this error was because I was had an unnecessary workers.dev zone_name on one line. I removed it, and the error went away. Thank you for your help!
