### ISSUE TITLE
[Miniflare] Cloudflare Pages Support for unit testing

### ISSUE THREAD

**Issue by uhthomas** [cloudflare/workers-sdk#4365]
I saw https://github.com/cloudflare/miniflare/issues/113, but I am interested in using [miniflare with Jest](https://miniflare.dev/testing/jest) to test [Cloudflare Pages Functions](https://developers.cloudflare.com/pages/platform/functions/).

It doesn't seem possible to create a mock `EventContext` with Miniflare at current.

**Comment by penalosa** [comment]
Since this issue was opened, we've released the revamped Vitest work for Miniflare 3, which should work with Pages Functions: https://developers.cloudflare.com/workers/testing/unit-testing/

**Comment by buckett** [comment]
The example for pages and Vitest is: https://github.com/cloudflare/workers-sdk/tree/main/fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self
