### ISSUE TITLE
🐛 BUG: Error while creating remote dev session: TypeError: fetch failed

### ISSUE THREAD

**Issue by zzzh** [cloudflare/workers-sdk#4395]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.13.1

### What version of Node are you using?

18.17.1

### What operating system are you using?

wsl2

### Describe the Bug

Got it when I tried to run "wrangler dev --remote", 

### Please provide any relevant error logs

✘ [ERROR] Error while creating remote dev session: TypeError: fetch failed

      at fetch
  (/home/zhu/.nvm/versions/node/v18.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:16838:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async createPreviewSession
  (/home/zhu/.nvm/versions/node/v18.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:150580:28)
      at async start
  (/home/zhu/.nvm/versions/node/v18.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:150781:9) {
    cause: ConnectTimeoutError: Connect Timeout Error
        at onConnectTimeout
  (/home/zhu/.nvm/versions/node/v18.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:7208:29)
        at
  /home/zhu/.nvm/versions/node/v18.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:7164:51
        at Immediate._onImmediate
  (/home/zhu/.nvm/versions/node/v18.17.1/lib/node_modules/wrangler/wrangler-dist/cli.js:7196:13)
        at process.processImmediate (node:internal/timers:476:21) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }

**Comment by zzzh** [comment]
Forgot to mention, I need to use proxy to work, and it works well for other programs.
So this looks to me probably a proxy compatibility issue of "wrangler dev --remote".

**Comment by JohnTheCoolingFan** [comment]
Same problem. I'm not using a proxy. Worked fine while I was booted into other system on 3.19.0, currently both don't work

**Comment by penalosa** [comment]
`wrangler dev --remote` doesn't currently support proxies—see https://github.com/cloudflare/workers-sdk/issues/5162 for the issue tracking support for this.
