### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by sobakieko** [cloudflare/workers-sdk#4410]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler core

### What version(s) of the tool(s) are you using?

3.15.0

### What version of Node are you using?

18.14.2

### What operating system are you using?

Windows

### Describe the Bug

when generating new anggular project

### Please provide any relevant error logs

```
npm ERR! syscall open
npm ERR! path C:\@cloudflare\workers-types/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\@cloudflare\workers-types\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by 1000hz** [comment]
closing as duplicate of #4425. will be fixed by #4445.
