### ISSUE TITLE
🐛 BUG: `wrangler pages dev` cannot detect `compatibility_date` from `wrangler.toml`

### ISSUE THREAD

**Issue by rschristian** [cloudflare/workers-sdk#4411]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.15.0

### What version of Node are you using?

18.18.0

### What operating system are you using?

Linux

### Describe the Bug

Upon running my dev command (`wrangler pages dev src`), every single time, I'm met with the same "No compatibility_date was specified", despite having it listed in my `wrangler.toml` as the docs link to. Setting the flag (`--compatability-date=...`) does silence that pesky warning but it's quite verbose and should be unnecessary.

### Please provide a link to a minimal reproduction

https://github.com/rschristian/bug__wrangler-compatibility-date

### Please provide any relevant error logs

```
$  yarn start

yarn run v1.22.19
$ wrangler pages dev src
▲ [WARNING] No compatibility_date was specified. Using today's date: 2023-11-09.

  Pass it in your terminal:
  .```
  --compatibility-date=2023-11-09
  .```
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more
  information.


Compiling worker to "/home/ryun/Projects/tmp/.wrangler/tmp/pages-Jxzdeo/functionsWorker-0.007770138516417946.mjs"...
✨ Compiled Worker successfully
 ⛅️ wrangler 3.15.0
-------------------
▲ [WARNING] --local is no longer required and will be removed in a future version.

  `wrangler dev` now uses the local Cloudflare Workers runtime by default. 🎉


⎔ Starting local server...
[mf:inf] Ready on http://0.0.0.0:8788
[mf:inf] - http://127.0.0.1:8788
[mf:inf] - http://192.168.100.128:8788
```

**Comment by Binero** [comment]
For what it is worth, I was able to reproduce this.

**Comment by xdivby0** [comment]
I have similar issues and I think in wrangler 2 this wasn't the case, just happened when I upgraded to 3

**Comment by penalosa** [comment]
`pages dev` doesn't currently fully support `wrangler.toml`, although we're currently working on it (see https://github.com/cloudflare/workers-sdk/pull/5284).
