### ISSUE TITLE
🐛 BUG: Error reloading local server: Error: write EOF at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)

### ISSUE THREAD

**Issue by RiseVerse** [cloudflare/workers-sdk#4412]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

Wrangler 3.15.0

### What version of Node are you using?

v20.9.0

### What operating system are you using?

Windows 11 Pro

### Describe the Bug

Hello everyone,

Hope you're all good.

I installed Node.js and VS Code on my machine to implement a Reverse Proxy.

So here is what I typed in my terminal:

"PS C:\Users\Max\Downloads\RiseVerse Reverse Proxy> npx wranngler
PS C:\Users\Max\Downloads\RiseVerse Reverse Proxy> npx wrangler
wrangler

Commands:
  wrangler docs [command..]            📚 Open wrangler's docs in your browser
  wrangler init [name]                 📥 Initialize a basic Worker project, including a wrangler.toml file
  wrangler generate [name] [template]  ✨ Generate a new Worker project from an existing Worker template. See https://github.com/cloudflare/templates
  wrangler dev [script]                👂 Start a local server for developing your worker
  wrangler deploy [script]             🆙 Deploy your Worker to Cloudflare.  [aliases: publish]
  wrangler delete [script]             🗑  Delete your Worker from Cloudflare.
  wrangler tail [worker]               🦚 Starts a log tailing session for a published Worker.   
  wrangler secret                      🤫 Generate a secret that can be referenced in a Worker   
  wrangler secret:bulk [json]          🗄️  Bulk upload secrets for a Worker
  wrangler kv:namespace                🗂️  Interact with your Workers KV Namespaces
  wrangler kv:key                      🔑 Individually manage Workers KV key-value pairs
  wrangler kv:bulk                     💪 Interact with multiple Workers KV key-value pairs at once
  wrangler pages                       ⚡️ Configure Cloudflare Pages
  wrangler queues                      🇶 Configure Workers Queues
  wrangler r2                          📦 Interact with an R2 store
  wrangler dispatch-namespace          📦 Interact with a dispatch namespace
  wrangler d1                          🗄  Interact with a D1 database
  wrangler hyperdrive                  🚀 Configure Hyperdrive databases
  wrangler ai                          🤖 Interact with AI models
  wrangler constellation               🤖 Interact with Constellation models
  wrangler vectorize                   🧮 Interact with Vectorize indexes
  wrangler pubsub                      📮 Interact and manage Pub/Sub Brokers
  wrangler mtls-certificate            🪪 Manage certificates used for mTLS connections
  wrangler login                       🔓 Login to Cloudflare
  wrangler logout                      🚪 Logout from Cloudflare
  wrangler whoami                      🕵️  Retrieve your user info and test your auth config     
  wrangler types                       📝 Generate types from bindings & module rules in config  
  wrangler deployments                 🚢 List and view details for deployments
  wrangler rollback [deployment-id]    🔙 Rollback a deployment

Flags:
  -j, --experimental-json-config  Experimental: Support wrangler.json  [boolean]
  -c, --config                    Path to .toml configuration file  [string]
  -e, --env                       Environment to use for operations and .env files  [string]     
  -h, --help                      Show help  [boolean]
  -v, --version                   Show version number  [boolean]
PS C:\Users\Max\Downloads\RiseVerse Reverse Proxy> npx wrangler init -y
 ⛅️ wrangler 3.12.0 (update available 3.15.0)
-------------------------------------------------------
Using npm as package manager.
▲ [WARNING] The `init` command is no longer supported. Please use `npm create cloudflare@2 -y -- --wrangler-defaults` instead.

  The `init` command will be removed in a future version.

Running `npm create cloudflare@2 -y -- --wrangler-defaults`...

using create-cloudflare version 2.6.2

╭ Create an application with Cloudflare Step 1 of 3
│
├ In which directory do you want to create your application?
│ dir ./reverse-proxy-setup
│
├ What type of application do you want to create?
│ type "Hello World" Worker
│
├ Do you want to use TypeScript?
│ yes typescript
│
├ Copying files from "hello-world" template
│
├ Retrieving current workerd compatibility date
│ compatibility date 2023-10-30
│
├ Couldn't find `git` installed on your machine. Continuing without git.
│
╰ Application created

╭ Installing dependencies Step 2 of 3
│
├ Installing dependencies
│ installed via `npm install`
│
╰ Dependencies Installed 

╭ Deploy with Cloudflare Step 3 of 3
│
├ Do you want to deploy your application?
│ no deploy via `npm run deploy`
│
├  APPLICATION CREATED  Deploy your application with npm run deploy
│
│ Navigate to the new directory cd reverse-proxy-setup
│ Run the development server npm run start
│ Deploy your application npm run deploy
│ Read the documentation https://developers.cloudflare.com/workers
│ Stuck? Join us at https://discord.gg/cloudflaredev
│
╰ See you again soon!

PS C:\Users\Max\Downloads\RiseVerse Reverse Proxy> cd reverse-proxy-setup
PS C:\Users\Max\Downloads\RiseVerse Reverse Proxy\reverse-proxy-setup> npm run start

> reverse-proxy-setup@0.0.0 start
> wrangler dev

 ⛅️ wrangler 3.15.0
-------------------
⎔ Starting local server...
X [ERROR] Error reloading local server: Error: write EOF

      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {   
    errno: -4095,
    code: 'EOF',
    syscall: 'write'
  }

╭───────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit │
│                                                                                               │
╰───────────────────────────────────────────────────────────────────────────────────────────────╯"

Do you have any solution?

PS: I tried using wrangler version 3.12.0 (perhaps more stable?), but it's always wrangler 3.15.0 that runs.

Have a great day,
Maxime

### Please provide any relevant error logs

PS C:\Users\Max\Downloads\RiseVerse Reverse Proxy\reverse-proxy-setup> npm run start

> reverse-proxy-setup@0.0.0 start
> wrangler dev

 ⛅️ wrangler 3.15.0
-------------------
⎔ Starting local server...
X [ERROR] Error reloading local server: Error: write EOF

      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {   
    errno: -4095,
    code: 'EOF',
    syscall: 'write'
  }

**Comment by RiseVerse** [comment]
It fixed.

I uninstalled everything:
- NodeJS
- VSCode
- Microsoft Visual Distribution

Just after, I reinstall all of them with the last version, for Node.js the last version (non-stable). 

I also:
- Run System File Checker 
- Run a DISM
- Updated Windows

I'm pretty sure it was Node.js that solved the problem because at every stage I tried to run the server.

When I installed the latest version of Node.js, I checked downloading all the necessary tools for compatibility (it seems that more things were installed this time).

Have a great day everyone,
Maxime

**Comment by ygweric** [comment]
Reinstall node.js with **Automatically install the necessary tools** works for me  👍 
It download some windows framework, chocolate, python, etc.

This bug has **nothing** to do with node version, pnpm\yarn version, or wrangler version !!

![企业微信截图_17127200062030](https://github.com/cloudflare/workers-sdk/assets/2714474/49fbecc2-c882-4425-a0e6-0cb6e529fa7f)

![企业微信截图_17127243971695](https://github.com/cloudflare/workers-sdk/assets/2714474/6d21144b-9748-4536-bba7-2e3673f5447f)


> It fixed.
> 
> I uninstalled everything:
> 
> * NodeJS
> * VSCode
> * Microsoft Visual Distribution
> 
> Just after, I reinstall all of them with the last version, for Node.js the last version (non-stable). 
> 
> I also:
> 
> * Run System File Checker
> * Run a DISM
> * Updated Windows
> 
> I'm pretty sure it was Node.js that solved the problem because at every stage I tried to run the server.
> 
> When I installed the latest version of Node.js, I checked downloading all the necessary tools for compatibility (it seems that more things were installed this time).
> 
> Have a great day everyone, Maxime
