### ISSUE TITLE
🐛 BUG: `--old-asset-ttl` expires each individual asset synchronously

### ISSUE THREAD

**Issue by shahyar** [cloudflare/workers-sdk#4414]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.7.0 [Wrangler]

### What version of Node are you using?

20.0.0

### What operating system are you using?

Linux

### Describe the Bug

The `--old-asset-ttl` feature described in #3384 and introduced in #3385 performs the asset expiration synchronously. This makes deployments take many minutes, as it can take as long as 10s (average is 6s for me) to expire each asset, which means over dozens or even hundreds of chunks, it can balloon the deployment.

**Comment by penalosa** [comment]
This is a very old issue so I'm going to close it for now. If you're still running into problems feel free to comment with more details and we can investigate further (and potentially revisit the linked PR)
