### ISSUE TITLE
🐛 BUG: fresh generation of worker-emscripten template doesn't work

### ISSUE THREAD

**Issue by marhyn** [cloudflare/workers-sdk#4417]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms

### What version(s) of the tool(s) are you using?

Wrangler[3.15.0]

### What operating system are you using?

MAC

### Describe the Bug

https://github.com/cloudflare/workers-sdk/tree/main/templates/experimental/worker-emscripten

there are no stb headers. Even if I manually put them in the repo, it still doesn't work.

### Please provide a link to a minimal reproduction

https://github.com/cloudflare/workers-sdk/tree/main/templates/experimental/worker-emscripten

### Please provide any relevant error logs

Error: Cannot find module 'XXX/build.js'

**Comment by penalosa** [comment]
We no longer recommend users use these templates to get started with projects, as they're generally very out of date. For up to date project templates, you can refer to https://developers.cloudflare.com/workers/get-started/quickstarts/ & for tutorials you can refer to https://developers.cloudflare.com/workers/tutorials/
