### ISSUE TITLE
🚀 Feature Request: Assign custom domains to R2 buckets directly from the command line

### ISSUE THREAD

**Issue by nestarz** [cloudflare/workers-sdk#4424]
### Feature Request

**Summary:**
As a developer who frequently interacts with Cloudflare R2 buckets, I am looking for a way to assign custom domains to R2 buckets directly from the command line, using the `wrangler` CLI tool or via a script. This feature would streamline my workflow as it would eliminate the need to use the web dashboard for this purpose.

**Motivation:**
The ability to assign custom domains to storage buckets via the command line is a common feature in other cloud services, and its absence in Cloudflare Workers impacts productivity, especially when managing multiple environments or automating deployments.

Having this feature would allow developers and DevOps teams to maintain a fully automated CI/CD pipeline without having to switch contexts to the web dashboard, thus preserving efficiency and reducing the potential for human error.

**Proposed Solution:**
Introduce a new subcommand in `wrangler`, for example, `wrangler r2 domain assign`, which would take the necessary parameters to bind a custom domain to an R2 bucket.

Additionally, offering API support for this action would allow users to write scripts that can handle domain assignments.

**Example Usage:**
```shell
wrangler r2 domain assign --bucket my-awesome-bucket --domain my.customdomain.com
```

By providing the appropriate flags and parameters, such as `--bucket` for the bucket name and `--domain` for the custom domain, users can easily and programmatically assign custom domains to their R2 buckets.

**Additional Context:**
While the current process of using the web dashboard is functional, it doesn't cater well to automation or to scenarios where developers need to manage resources through code. This feature would be particularly useful for those who operate in a code-as-infrastructure paradigm and those who have already adopted automation in other facets of their cloud resource management.

**Comment by baspenny** [comment]
@frammaa suggestion works like a charm. Is it possible to just make this official part of the API and document this?

**Comment by Ases** [comment]
> Then update the permissions of said domain, in this case open access via that domain:
> 
> ```ts
> await fetch(
>     `https://api.cloudflare.com/client/v4/accounts/${cloudflareAccountId}/r2/buckets/${bucket}/policy?cname=${domain}&access=CnamesOnly`,
>     {
>       method: 'PUT',
>       headers: {
>         'Content-Type': 'application/json',
>         Authorization: `Bearer your-token`,
>       },
>     }
>   )
> ```
:warning: 
Be careful with this PUT as it replaces the entire bucket policy, and if you already had other domains enabled in the same bucket, they will be deactivated.

I suggest you use this other method to activate the domain (which appends the domain to the actual policy).

```sh
curl "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/r2/buckets/$BUCKET_NAME/domains/custom/$DOMAIN" \
-X PUT \
-H "Content-Type: application/json" \
-H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
-H "X-Auth-Key: $CLOUDFLARE_API_KEY" \
--data '{"enabled": true }'
```

**Comment by jonesphillip** [comment]
This is now possible using [`wrangler r2 bucket domain` commands](https://developers.cloudflare.com/workers/wrangler/commands/#domain-add). The API for interacting with custom domains is also documented [here](https://developers.cloudflare.com/api-next/resources/r2/subresources/buckets/subresources/domains/subresources/custom/).

Closing this feature request out, let us know if you have questions.
