### ISSUE TITLE
🐛 BUG: miniflare TlsOptions_Version Typescript type issue

### ISSUE THREAD

**Issue by spinx** [cloudflare/workers-sdk#4451]
### Which Cloudflare product(s) does this pertain to?

Miniflare

### What version(s) of the tool(s) are you using?

latest

### What version of Node are you using?

18.18.2

### What operating system are you using?

Mac

### Describe the Bug

When trying to `tsc` a Typescript project using Miniflare, I get a few type errors including the following error:

```
TlsOptions_Version' does not satisfy the constraint 'EnumLike'.
4793 z.ZodNativeEnum<TlsOptions_Version>
```

### Please provide a link to a minimal reproduction

https://github.com/spinx/miniflare-types

**Comment by penalosa** [comment]
Setting the `tsconfig.json` option `skipLibCheck: true` should solve this in your project
