### ISSUE TITLE
C3: Improve `@cloudflare/workers-types` types used for Workers

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/workers-sdk#4514]
### Describe the solution

In C3 when creating a new worker we get the latest compatibility date and apply it to the worker's toml file ([source](https://github.com/cloudflare/workers-sdk/blob/04a2d0ed6fca1c366cd891b54026c34e1c1a5701/packages/create-cloudflare/src/workers.ts#L187)) the `@cloudflare/workers-types` types used do not however match such compatibility date (see [comment](https://github.com/cloudflare/workers-sdk/issues/3742#issuecomment-1827092751)) causing a confusing and frustrating experience for developers.

So we should also:
 - make sure that the `@cloudflare/workers-types` is updated to its latest version ~~(instead of having the [version hardcoded](https://github.com/search?q=repo%3Acloudflare%2Fworkers-sdk+%2F%22%40cloudflare%5C%2Fworkers-types%22%3A+%22.*%3F%22%2F+path%3A%2F%5Epackages%5C%2Fcreate-cloudflare%5C%2Ftemplates%5C%2F%2F&type=code))~~ (probably not an issue since the versions do have `^`)
 - update the [tsconfig.json workers-types entries](https://github.com/search?q=repo%3Acloudflare%2Fworkers-sdk+%2F%22types%22%3A+%5C%5B%22%40cloudflare%5C%2Fworkers-types%22%5D%2F+path%3A%2F%5Epackages%5C%2Fcreate-cloudflare%5C%2Ftemplates%5C%2F%2F&type=code) to use the [most recent non-experimental entrypoint](https://github.com/cloudflare/workerd/tree/main/npm/workers-types#compatibility-dates)
 
 This should provide a valid setup for developers and allow them to proceed with their work without type issues.
 
 > [!NOTE]
 > it is still confusing that there is a compatibility date and a (most likely) different workers-types entrpoint date, that is however an issue that needs to be solved separately and not something that we can address in C3, hopefully this will be addressed in the future making the use of types more straightforward for developers

**Comment by Cherry** [comment]
This sounds like a great improvement, thanks Dario! Excited to see this land.
