### ISSUE TITLE
🐛 BUG: `upstream_protocol` is ignored in the codebase

### ISSUE THREAD

**Issue by peter-leonov-hellofresh** [cloudflare/workers-sdk#4539]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.18.0

### What version of Node are you using?

18.17.1

### What operating system are you using?

Mac

### Describe the Bug

As visible from [the code search](https://github.com/search?q=repo%3Acloudflare%2Fworkers-sdk%20upstreamProtocol&type=code) the `upstream_protocol` option gets parsed and verified but never used.

Steps to reproduce
* define `upstream_protocol = "https"`
* make a request to the `wrangler dev` server
* see the outgoing requests being `http`
* also, see the upstream server redirecting to `https` as it should in 2024 :)

Expected
* outgoing requests use `https`

Thanks for the great work on the tool, awesome stuff!

### Please provide any relevant error logs

No errors.

**Comment by samaritanau** [comment]
This is hurting us at the moment, can't test locally
