### ISSUE TITLE
🐛 BUG: EBADF: bad file descriptor, write

### ISSUE THREAD

**Issue by shirshak55** [cloudflare/workers-sdk#4540]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

3.18

### What version of Node are you using?

21.3.0

### What operating system are you using?

Mac

### Describe the Bug

Whenever I try to deploy cloudflare worker, I get this message

Attempting to login via OAuth...

And, it opens a link in browser. And, when I allow it in browser i get this error.
```
/Users/macbook/Desktop/projects/mike/tm_spinner_config/node_modules/wrangler/wrangler-dist/cli.js:29374
            throw a;
            ^

Error: EBADF: bad file descriptor, write
    at writeFileSync (node:fs:2352:20)
    at writeAuthConfigFile (/Users/macbook/Desktop/projects/mike/tm_spinner_config/node_modules/wrangler/wrangler-dist/cli.js:119084:37)
    at Server.<anonymous> (/Users/macbook/Desktop/projects/mike/tm_spinner_config/node_modules/wrangler/wrangler-dist/cli.js:119173:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'write'
}

Node.js v21.3.



```

**Comment by mxschumacher** [comment]
Hello, I have the exact same issue. When downgrading the node version to 20.10.0 (latest LTS at the time of writing) and re-rerunning the same commands, the login is successful. 

Running
> man 2 write | grep "EBADF"

We are told “EBADF  fd is not a valid file descriptor or is not open for writing.”

I assume that within the major version (from 20 to 21), something changes in **fs.writeFileSync** https://nodejs.org/api/fs.html#fswritefilesyncfile-data-options, I see that it is invoked in https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/user/user.ts#L869 from https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/user/user.ts#L978C28-L978C28

System context: I am using wrangler version 3.18.0 and node version 21.3.0 on Fedora Linux with kernel 6.5.12

As the developer docs for wrangler don’t specify an upper bounds for the node version to be installed, this is an easy trap to fall into. I think users should be encouraged to stay on the node LTS until further notice.

**Comment by shirshak55** [comment]
I think if it is node issue, so this repo isn't responsible for this?

I have tried 21.4.0, and it doesn't seem to be fixed.

<img width="1236" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/8097377/17ebe4e4-eff7-43ec-a91f-cd9dd0735ed9">

**Comment by mxschumacher** [comment]
Hello @shirshak55 , I don't think this issue should be closed. The docs define a lower bound of node version that is supported, but don't indicate an upper bound. Instead of letting users run into strange error messages due to problems with downstream dependencies, wrangler should give useful feedback and define the most recent node release that all tests have been passed on.

While this particular bug might have been resolved, the problem in general still stands. Node will keep changing and the package.json does not limit the upper bound of the version number.
