### ISSUE TITLE
🐛 BUG: Cannot wrangler login

### ISSUE THREAD

**Issue by ajsb85** [cloudflare/workers-sdk#4549]
### Which Cloudflare product(s) does this pertain to?

Other

### What version(s) of the tool(s) are you using?

3.18.0 wrangler 

### What version of Node are you using?

21.3.0

### What operating system are you using?

Windows 10

### Describe the Bug

This site can’t be reached localhost refused to connect.

![image](https://github.com/cloudflare/workers-sdk/assets/663460/17bae5cf-76a2-40d2-a582-b082f824c326)

### Please provide any relevant error logs

```console
Error: ENOENT: no such file or directory, open 'C:\Users\ajsb8\AppData\Roaming\xdg.config\.wrangler\config\default.toml'
    at writeFileSync (node:fs:2352:20)
    at writeAuthConfigFile (C:\Users\ajsb8\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:119084:37)
    at Server.<anonymous> (C:\Users\ajsb8\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:119173:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\ajsb8\\AppData\\Roaming\\xdg.config\\.wrangler\\config\\default.toml'
}
```

[wrangler-2023-12-04_21-11-42_161.log](https://github.com/cloudflare/workers-sdk/files/13551362/wrangler-2023-12-04_21-11-42_161.log)

**Comment by penalosa** [comment]
@ajsb85 can you still reproduce this?

**Comment by ajsb85** [comment]
> @ajsb85 can you still reproduce this?

No. But I was able to use it recently.
Don't worry.
Thank you.
