### ISSUE TITLE
🚀 Feature Request: Can Workers generated by wrangler include tests again?

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#4552]
### Describe the solution

Currently if you want a Worker with Vitest preconfigured, you have to run:
```
npx wrangler@2 init my-tested-worker -y
```

It would be cool if wrangler v3 could generate Workers with tests too.

**Comment by admah** [comment]
#5189 closes this by adding `@cloudflare/vitest-pool-workers` to "Hello World" templates with an example test.
