### ISSUE TITLE
🐛 BUG: C3 2.8.2 always initialises JavaScript, even when TypeScript is selected

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#4599]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

C3 2.8.2

### What version of Node are you using?

20.10.0

### What operating system are you using?

Windows 11

## c3 2.8.1

- `npm create cloudflare@2.8.1 -- --no-auto-update`
- use all defaults - ensure you say "yes" to TypeScript
- you'll get a TypeScript project, with `src/index.ts`

## c3 2.8.2

- `npm create cloudflare@2.8.2 -- --no-auto-update`
- use all defaults - ensure you say "yes" to TypeScript
- you'll get a JavaScript project, no types, `src/index.js`

---

It seems this regression was introduced in https://github.com/cloudflare/workers-sdk/pull/4470 and unfortunately wasn't caught in any automated testing. It also took longer than I care to admit to find that PR, without a changeset 😅

**Comment by samaritanau** [comment]
I can confirm!

**Comment by rita3ko** [comment]
I also ran into this issue
