### ISSUE TITLE
🐛 BUG: secret revert to previous value after update

### ISSUE THREAD

**Issue by danbars** [cloudflare/workers-sdk#4601]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.19.0

### What version of Node are you using?

18.12.1

### What operating system are you using?

Mac

### Describe the Bug

* I have a worker that has both `fetch` and `queue` handlers.
* I've created a secret using `wrangler secret put API_KEY` with value `1`
* In the code I'm using `env.API_KEY` *only from `queue` handler*
* After that I've updated the secret using the same command to value `2`
* Redeploy the worker using `wrangler publish` (not sure if it's needed)
* The `API_KEY` remains with value `1` !
* Weird trick: In the `fetch` handler, in the first line add `console.log(env.API_KEY)`. The console prints `2` and now also the `queue` handler is using `2`. If I remove the log, the value reverts again to `1` when used in `queue`

### Please provide a link to a minimal reproduction

NA

### Please provide any relevant error logs

There's nothing in the logs that discloses this.

**Comment by petebacondarwin** [comment]
@danbars - does this also happen with non-secret vars?

**Comment by admah** [comment]
I'm not able to reproduce this in a basic example. I did create a repo to demo what I'm seeing: https://github.com/admah/cloudflare-queues-demo

**Comment by danbars** [comment]
@petebacondarwin I don't have any non-secret var, so I don't know.
@admah the above description is from my production worker. 
I'll try to recreate on a minimal setup.

**Comment by danbars** [comment]
I wasn't able to reproduce in an isolated environment. 
I now tried removing the log line from my production environment, and everything seems to be working properly. i.e. the secret is not reverted. 
I can't reproduce anymore, but know that when I originally opened the ticket I double checked myself by removing and re-adding the console line and making sure that the behavior is reproduced. 

I will leave this ticket open for another day or 2 just in case you have more questions or comments, and then close it.
