### ISSUE TITLE
Live-reload doesn't seem to work on all files, only the __worker.js file

### ISSUE THREAD

**Issue by treeder** [cloudflare/workers-sdk#4607]
### Describe the solution

I have a `_worker.js` that imports from another file in the same directory. If I edit `__worker.js`, it reloads. If I edit the imported js file, nothing happens requiring me to do a full restart.

**Comment by DylanRJohnston** [comment]
This is super annoying when working with wasm, and doesn't match the behaviour of `wrangler dev` which properly reloads everything. My current work around is to use something like `entr` to touch the `_worker.js` file when something else changes.

```
find site | /entr touch site/_worker.js &
```

**Comment by penalosa** [comment]
This was addressed by https://github.com/cloudflare/workers-sdk/pull/6150. If you're still running into issues feel free to open a new issue and we can investigate further.
