### ISSUE TITLE
🐛 BUG: workers.api.error.bucket_not_found when choosing EU jurisdiction

### ISSUE THREAD

**Issue by Mecanik** [cloudflare/workers-sdk#4613]
### Which Cloudflare product(s) does this pertain to?

R2

### What version(s) of the tool(s) are you using?

3.21.0 [Wrangler]

### What operating system are you using?

Windows

### Describe the Bug

As the title says, the API returns `workers.api.error.bucket_not_found` when you try to bind a bucket that was created in the EU jurisdiction via the Cloudflare dashboard.

**Comment by Mecanik** [comment]
After navigating to really unrelated docs, I found that if you add `jurisdiction = "eu"` to the specified bucket wrangler will deploy the worker without issues. The documentation needs to be updated.

**Comment by flexchar** [comment]
I've just encountered the same. I was surprised to see the error even though the bucket works on the deployed worker and most certainly exists. 

@Mecanik could you link to the docs where you found it? I'd like to document the change for myself. :)

**Comment by lapppius** [comment]
For more: https://developers.cloudflare.com/r2/reference/data-location/#using-jurisdictions-from-workers

**Comment by penalosa** [comment]
I'm going to close this issue, since it's documented at https://developers.cloudflare.com/r2/reference/data-location/#using-jurisdictions-from-workers

**Comment by flexchar** [comment]
Hey @penalosa, is it possible to scope the workers to only process requests in certain regions too? Or rather disable certain countries? 

I am having some issues where China is a problematic source and sometimes I get requests from Chinese workers. I would like to disable it.
