### ISSUE TITLE
🐛 BUG: Why does `wrangler pages dev` allow node commands, e..g. Buffer?

### ISSUE THREAD

**Issue by 205g0** [cloudflare/workers-sdk#4615]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

latest

### What version of Node are you using?

latest

### What operating system are you using?

latest

### Describe the Bug

I always assumed that wrangler "simulates" my production env as far as possible. But it allows node commands in wrangles pages dev and then you get errors in production with cryptic, unrelated error messages and you don't know why. I didn't enable the `node_compat` flag.

Good that I had the CF dashboard open and saw that a build broke but often I don't and have fun going back finding that bug. This would be still easy with something like git bisect but it isn't since you have to deploy every time to see if it is running on prod.

Maybe this is intended or we need node for whatever reason but then, a warning in dev that node commands have been used would be quite helpful.

Once you know all good but most of the times, you have ten other things in your mind.

### Please provide a link to a minimal reproduction

just sprinkle node commands here and there

### Please provide any relevant error logs

n.a.

**Comment by CarmenPopoviciu** [comment]
hi @205g0 , thank you for reporting this issue. 

Lots has changed since Dec 2023 when this was first reported. Are you still experiencing any of these issues?

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to comment with more details and we can investigate further.
