### ISSUE TITLE
🐛 BUG: --host flag not respected

### ISSUE THREAD

**Issue by admah** [cloudflare/workers-sdk#4643]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.17.1+

### What operating system are you using?

---

### Describe the Bug

User reports that “host” flag seems to be ignored. 

If I set --host to "testing.com", the request host header is set to 127.0.0.1:8787, even if I do a: curl --head http://127.0.0.1:8787/ -H “Host: testing.com”. Was working previously.

**Comment by petebacondarwin** [comment]
This is fixed by https://github.com/cloudflare/workers-sdk/pull/4630
