### ISSUE TITLE
🐛 BUG: D1 tutorial, request to the cloudflare API is malformed, failed to decode id

### ISSUE THREAD

**Issue by BlakeBrown** [cloudflare/workers-sdk#4649]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

Everything is up to date

### What operating system are you using?

Mac

### Describe the Bug

Tried to follow the tutorial here https://developers.cloudflare.com/d1/get-started/

When deploying the production by running the following command, I get an error

` npx wrangler d1 execute test-db --file=./schema.sql`

  The request is malformed: failed to decode id [code: 7400]
  
  I have the following in wranger.toml

```
[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "test-db"
database_id = "2"
```

**Comment by BlakeBrown** [comment]
Closing. I followed the tutorial wrong.

Pay careful attention to the output after `npx wrangler d1 create <your-db-name>`, or you won't be able to use your DB in prod

**Comment by jessewriter** [comment]
i'm following the tutorial exactly pasting the terminal text and got this error also.  pay careful attention to what?

**Comment by jessewriter** [comment]
ah `database_id` is auto generated, from the tutorial I thought we can put any id there, but you have to put in the response from step 2 literally from the wrangler terminal response.  replace string ending in 'foot' with your terminal response.

![Image](https://github.com/user-attachments/assets/9326aa9e-9b05-465f-a205-6d241ed70175)
