### ISSUE TITLE
🐛 BUG: Worker named `accounts` fails to have its routes updated

### ISSUE THREAD

**Issue by atomicalbt** [cloudflare/workers-sdk#4660]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms

### What version(s) of the tool(s) are you using?

3.22.1

### What version of Node are you using?

v20.9.0

### What operating system are you using?

macOS 13.0

### Describe the Bug

A Cloudflare Worker called `accounts` fails to have its routes updated due to its naming. Instead of `PUT /client/v4/accounts/{account_id}/workers/scripts/accounts/routes` returning an authentication error (having the Wrangler use the fallback), it returns:

```
{
  "code": 7003,
  "message": "Could not route to /client/v4/accounts/{acc_id}/workers/scripts/accounts/routes, perhaps your object identifier is invalid?"
}
```

This is not a Wrangler-specific bug, but I wonder if having some form of hard-coded validation on the CLI would help users diagnose errors like this faster. I also couldn't find any documentation with forbidden Worker names. 

Apologies in advance if this is not the right channel to report this.

### Please provide any relevant error logs

```
curl --location --request PUT 'https://api.cloudflare.com/client/v4/accounts/{acc_id}/workers/scripts/accounts/routes' \
--header 'Authorization: Bearer {api_token}' \
--header 'Content-Type: application/json' \
--data '[
    {
        "pattern": "api.example.com/accounts/*",
        "zone_name": "api.example.com"
    }
]'
```

```
{
    "result": null,
    "success": false,
    "errors": [
        {
            "code": 7003,
            "message": "Could not route to /client/v4/accounts/{acc_id}/workers/scripts/accounts/routes, perhaps your object identifier is invalid?"
        }
    ],
    "messages": []
}
```

**Comment by tnoor-co** [comment]
Ran into the same issue as well with a worker pages project named `accounts` as well.

```
✘ [ERROR] A request to the Cloudflare API (/accounts/<redacted>/pages/projects/accounts/upload-token) failed.

  Could not route to
  /client/v4/accounts/<redacted>/pages/projects/accounts/upload-token,
  perhaps your object identifier is invalid? [code: 7003]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

 Renamed the project to `auth-accounts` and it worked fine.

```
🌍  Uploading... (55/55)

✨ Success! Uploaded 55 files (2.33 sec)

✨ Uploading _headers
✨ Uploading Functions bundle
✨ Uploading _routes.json
✨ Deployment complete! Take a peek over at https://<redacted>.<redacted>.pages.dev
```

Thanks for creating the issue, @atomicalbt !

**Comment by penalosa** [comment]
This should have been fixed at the API layer—feel free to open a new issue if you're still seeing unexpected behvaiour
