### ISSUE TITLE
🐛 BUG: `D1 bindings require module-format [object Object]`

### ISSUE THREAD

**Issue by rista404** [cloudflare/workers-sdk#4714]
### Which Cloudflare product(s) does this pertain to?

D1, Wrangler core

### What version(s) of the tool(s) are you using?

3.22.3 [Wrangler]

### What version of Node are you using?

21.5.0

### What operating system are you using?

Mac

### Describe the Bug

I tried to follow the [Comments API with D1 Tutorial](https://developers.cloudflare.com/d1/tutorials/build-a-comments-api/) and can't get it to work. The errors are as follows:

In local:
```
> wrangler dev

 ⛅️ wrangler 3.22.3
-------------------
Your worker has access to the following bindings:
- D1 Databases:
  - DB: test-db-api (...)
⎔ Starting local server...
✘ [ERROR] workerd/server/workerd-api.c++:609: error: wrapped binding module can't be resolved (internal modules only); moduleName = cloudflare-internal:d1-api
```

And when trying to develop:

```
Total Upload: 55.24 KiB / gzip: 12.47 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/{id}/workers/scripts/cf-workers-db-api) failed.

  D1 bindings require module-format [object Object]
  ```
  
  I can create a reproduction repo but it's exactly how it is in the tutorial.

**Comment by KianNH** [comment]
I can't reproduce this error with the code from the tutorial - are you able to create the reproduction repository?

**Comment by rista404** [comment]
@KianNH sure, here it is: https://github.com/rista404/cf-d1-test/

Don't forget to create a new db (`npx wrangler d1 create test-db-api`) and change the id in the `wrangler.toml`.

**Comment by KianNH** [comment]
You're missing `export default app` at the bottom.

https://developers.cloudflare.com/d1/tutorials/build-a-comments-api/#2-initialize-your-hono-application

**Comment by rista404** [comment]
🤦🏻‍♂️ 

Sorry for the trouble, @KianNH. I was so puzzled by the error message mentioning D1 that it must've slipped through. Thanks for the help.

**Comment by KianNH** [comment]
It's because the presence of a default export is how Wrangler knows you're using a Module Worker rather than a Service Worker.

Since there wasn't one, it uploaded your Worker as a Service Worker which are a legacy format which you can't use D1 with.

**Comment by rista404** [comment]
Yeah all clear now, thanks again!

I'll close the issue however I do suggest maybe looking into error messages — mostly for the local `wrangler dev` process.
