### ISSUE TITLE
🐛 BUG: onResolve error from bundling module resultion when importing wasm modules from npm packages

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workers-sdk#4726]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.22.3

### What version of Node are you using?

20.10.0

### What operating system are you using?

Mac

### Describe the Bug

If I try to import a wasm module from an npm package in my worker using the node module resolution, for example:

```
import JPEG_DEC_WASM from '@jsquash/jpeg/codec/dec/mozjpeg_dec.wasm';
```

I get the following error when running `wrangler dev`:
```
✘ [ERROR] ENOENT: no such file or directory, open '/Users/foo/bar/src/@jsquash/jpeg/codec/dec/mozjpeg_dec.wasm' [plugin wrangler-module-collector]

    src/jsquash-transform.ts:3:26:
      3 │ import JPEG_DEC_WASM from '@jsquash/jpeg/codec/dec/mozjpeg_dec.wasm';
        ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/wrangler@3.22.3_patch_hash=whuv2ih5kundyyu7rtaqweiv2a/node_modules/wrangler/wrangler-dist/cli.js:123256:19:
      123256 │             build5.onResolve(
             ╵                    ~~~~~~~~~

    at /Users/foo/bar/node_modules/.pnpm/wrangler@3.22.3_patch_hash=whuv2ih5kundyyu7rtaqweiv2a/node_modules/wrangler/wrangler-dist/cli.js:123256:20
    at Array.forEach (<anonymous>)
    at /Users/foo/bar/node_modules/.pnpm/wrangler@3.22.3_patch_hash=whuv2ih5kundyyu7rtaqweiv2a/node_modules/wrangler/wrangler-dist/cli.js:123255:22
    at Array.forEach (<anonymous>)
```

The only way I was able to get this to work was by using a relative path to the module rather than node module resolution:
```
import JPEG_DEC_WASM from '../node_modules/@jsquash/jpeg/codec/dec/mozjpeg_dec.wasm';
```

The module resolution should work the same for both js/ts and wasm files.

**Comment by Cherry** [comment]
I [fixed this is a while back](https://jross.me/improving-wasm-imports-with-wrangler-and-cloudflare-workers/) for modern packages that are using `exports` in `package.json`: https://github.com/cloudflare/workers-sdk/pull/4135

For example with `@resvg/resvg-wasm`, they have an [exports map](https://github.com/yisibl/resvg-js/blob/06dd2c01ea0e83ba97e28ff793eae3a9c38bea6f/wasm/package.json#L9) for `./index_bg.wasm` so you just import `@resvg/resvg-wasm/index_bg.wasm`. 

It doesn't seem like `jSquash` does this though: https://github.com/jamsinclair/jSquash/blob/main/packages/jpeg/package.json, so you're stuck with the `../node_modules/....` paths for now.

It would probably be a good idea to try the "node" resolution algorithm on paths like this around [here](https://github.com/Cherry/workers-sdk/blob/44cbd66ff2283384569756ef578b08ec1556cdb8/packages/wrangler/src/deployment-bundle/module-collection.ts#L273) to better support more of the ecosystem.
