### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by mayanksmarty** [cloudflare/workers-sdk#4735]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

latest

### What operating system are you using?

window

### Describe the Bug

I have a project which contain react, nodejs and tsx file inside the src folder when i run with npm run dev it works fine but when i run with wrnagler it gives me loader error like this X [ERROR] No loader is configured for ".ttf" files: src/assets/fonts/NeueHaasDisplay-Roman.ttf

    src/shared/styles/GlobalStyles.ts:3:22:
      3 │ import NeueRoman from "../../assets/fonts/NeueHaasDisplay-Roman.ttf";        
what im missing do i need to anythhing extra and one more thing wrangler deploy uses js script but my project start with html file do i need to do changes or there is support for html also

**Comment by penalosa** [comment]
Thanks for opening this issue! It looks like you're trying to import font files into a typescript file. This won't work by default, but using [Wrangler's module rules](https://developers.cloudflare.com/workers/wrangler/configuration/#bundling), you can control how font files are imported. 

However, depending on your existing bundler setup this may not be all that's required. Wrangler's bundler is specific to writing a Worker, and can't handle arbitrary front end codebases. If you're writing a React app you'll likely have better luck with Cloudflare Pages, which can take the output of your existing build setup. See https://developers.cloudflare.com/pages/framework-guides/deploy-a-react-site/ for more details.
