### ISSUE TITLE
🚀 Feature Request: preserveFileNames option

### ISSUE THREAD

**Issue by benycodes** [cloudflare/workers-sdk#4741]
### Describe the solution

Could you implement `preserveFileNames` for bundled assets into the wrangler.toml or CLI?
This should prevent bundled assets name changing to be prefixed with the SHA1 hash of the file, and means we can import files on the fly.

Seems like it's implemented in `createModuleCollector` but no corresponding config option was implemented (should be a quick fix!)

- https://github.com/cloudflare/workers-sdk/blob/96a27f3d8a250c995907773d1aa695f80d43d9d0/packages/wrangler/src/deployment-bundle/module-collection.ts#L97C2-L97C19
- https://github.com/cloudflare/workers-sdk/blob/96a27f3d8a250c995907773d1aa695f80d43d9d0/packages/wrangler/src/deploy/deploy.ts#L473C27-L473C48

**Comment by petebacondarwin** [comment]
@admah - can you decide if this is a feature we want to support? If so, there is a PR that is mostly ready to go to implement it, which we can clean up and land.

**Comment by admah** [comment]
@benycodes thanks for submitting this - and the PR. We are good to move this forward and get the PR landed. 

We will need the new flag added to our docs on [this page](https://developers.cloudflare.com/workers/wrangler/commands/#deploy).

**Comment by benycodes** [comment]
@petebacondarwin @admah - tests have been added & formatting issue fixed. Let me know if anything else needs doing.

This allows for us to do this at runtime:
```js
const fileName = 'text.file';
const dynamicFileImport = await import(`./${fileName}`)
```
which currently needs to be done as `await import('1151a76c857b5849bf592248ec41fa369707d93f-text.file')`, and annoyingly the file name changes if we modify the file content.

For my specific use case it was to serve static files:
```js
// this
.get('/robots.txt', (c) => serveStaticFile('7a54e2d580b1ccecb62fe3fbb7b98fe569630744-robots.txt', c))
// can now become this
.get('/robots.txt', (c) => serveStaticFile('robots.txt', c))
```
