### ISSUE TITLE
🐛 BUG:  PS C:\Users\CCL\Desktop\flr\sola\ade> npx wrangler vectorize create vector-index --dimensions=768 --metric=cosine 🚧 Creating index: 'vector-index'  X [ERROR] A request to the Cloudflare API (/accounts/03ca965e895ced6f7d7f1ec8e27c8cba/vectorize/indexes) failed.    vectorize.not_entitled [code: 1005]

### ISSUE THREAD

**Issue by surfiniaburger** [cloudflare/workers-sdk#4746]
### Which Cloudflare product(s) does this pertain to?

Other

### What version(s) of the tool(s) are you using?

wrangler ^3.0.0

### What version of Node are you using?

20

### What operating system are you using?

windows

### Describe the Bug

PS C:\Users\CCL\Desktop\flr\sola\ade> npx wrangler vectorize create vector-index --dimensions=768 --metric=cosine
🚧 Creating index: 'vector-index'

X [ERROR] A request to the Cloudflare API (/accounts/03ca965e895ced6f7d7f1ec8e27c8cba/vectorize/indexes) failed.

  vectorize.not_entitled [code: 1005]

**Comment by penalosa** [comment]
It's likely that there will be a free tier for Vectorize after it comes out of public beta, but it's currently only available on the [Workers Paid](https://developers.cloudflare.com/workers/platform/pricing/#workers) plan—see https://developers.cloudflare.com/vectorize/platform/pricing/ for more details.

**Comment by surfiniaburger** [comment]
Thank you Somhairle, I'm using cloudfare for MLH hackathon, vectorizer would have been next level for me. Albeit I've decided to stick with all the free tiers can offer. Working with workers is cool, It's like having everything all in one place.

Regards,
Adedoyinsola
________________________________
