### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by strawbs1989** [cloudflare/workers-sdk#4750]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

C3

### What operating system are you using?

windows

### Describe the Bug

<html>
<body>

21:41:41.505 | Deploying your site to Cloudflare's global network...
-- | --
21:41:44.199 |  
21:41:44.313 | ✘ [ERROR] Error: Pages only supports files up to 26.2 MB in size

</body>
</html>

### Please provide a link to a minimal reproduction

https://github.com/strawbs1989/coolvibes-reloaded

**Comment by penalosa** [comment]
This is expected for sites deployed to Cloudflare Pages. As the error message says:

> Pages only supports files up to 26.2 MB in size

See https://developers.cloudflare.com/pages/platform/limits/#file-size for more details
