### ISSUE TITLE
🚀 Feature Request:

### ISSUE THREAD

**Issue by moskalyk** [cloudflare/workers-sdk#4752]
### Describe the solution

Hey, 

It seems like when using the wrangler cli, if you `wrangler login` and `wrangler init` and get to the 5th step of project creation, it asks to deploy the application. But, deploying would only work if you're in the randomly generated project directory post `wrangler init` step. It'd be really nice for users if this could just be all possible by in a single flow with the cli, and the only thing the dashboard is useful for is account login.

Thanks,
Morgan

**Comment by penalosa** [comment]
Choosing to deploy an application from `wrangler init` _should_ work within the initialisation flow. Are you running into errors when deploying?

**Comment by lrapoport-cf** [comment]
hey @moskalyk :) we haven't heard from you in a while, so we’re going to close this issue for now. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and any additional requested details, followup, or context and we will revisit and investigate further. thanks!
