### ISSUE TITLE
🐛 BUG: Cannot access `wrangler dev --ip 0.0.0.0` from device on same network

### ISSUE THREAD

**Issue by s3mj3n** [cloudflare/workers-sdk#4763]
### Which Cloudflare product(s) does this pertain to?

Wrangler core, Miniflare

### What version(s) of the tool(s) are you using?

3.22.5, 3.22.3, 3.19.0, 3.18.0

### What version of Node are you using?

18

### What operating system are you using?

MacOS

### Describe the Bug

Run `wrangler dev --ip 0.0.0.0` and try accessing http://<local_ip>:8787 on a device on the same network.

### Please provide any relevant error logs

Hi!

With `wrangler dev --ip 0.0.0.0` I can access the worker through http://192.168.1.26:8787 (local IP) on computer on which I started the process, but not from my phone on the same wifi network... (i can access other ports (http://192.168.1.26:5000), if I run a simple web server for example).

I tried different wrangler versions, nothing changed. Actually, it worked with 3.18.0 and `--remote` but remote development breaks my workflow...

If I forward a port to 8787 (with `socat TCP-LISTEN:8282,fork TCP:localhost:8787`) I can access the dev worker from my phone through http://192.168.1.26:8282. 

Is this a bug or am I missing something?

**Comment by Lekensteyn** [comment]
I cannot reproduce the problem on Linux with wrangler 3.24.0 and `wrangler dev --ip 0.0.0.0`. On macOS, you can also check which address and ports a service is listening using:
```
lsof -nPiTCP -sTCP:LISTEN
```

Can you confirm that no firewall rule is denying external access to the `node` process?

**Comment by s3mj3n** [comment]
@Lekensteyn Yes I can confirm that there is no firewall denying external access to the node process. I can access other node servers from my phone but not workerd... Even though it's open when running `lsof -nPiTCP -sTCP:LISTEN`.

So far, I tried:
- All rencent wrangler versions (3.14 to 3.26)
- Connect from another phone
- Connect from another browser
- Other wifi networks
- Launching wrangler on different ports (3000, 8282, 8787, 8888…)
- Fresh new Cloudflare Worker project  
- Fresh new Cloudflare Worker project after creating on a new user on the Mac
- All of the above while disabling firewall completely (and anti-virus)

Also I ran `sudo tcpdump -i en0 port ${PORT}` to listen to incoming connections: it does not go beyond the initial handshake when trying to access wrangler from the phone on the same device (works with other node servers as I said, and works when I forward a port to the wrangler on).

It looks like the workerd process is listening on the chosen port but refuses the connection from another device ip.

**Comment by s3mj3n** [comment]
I just managed to get back to a "working" state by downgrading to wrangler 3.18 and using `--remote` (still not working on local).

It looks like it has to do with the changes brought by 3.19 (https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.19.0): the workerd IP loopback.
