### ISSUE TITLE
🐛 BUG: Unable to View Real-time Logs from Cloudflare Pages via Wrangler

### ISSUE THREAD

**Issue by okamototomoyuki** [cloudflare/workers-sdk#4785]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler core

### What version(s) of the tool(s) are you using?

3.23.0

### What version of Node are you using?

v20.10.0

### What operating system are you using?

Windows 11

### Describe the Bug

1. I attempted to view the Real-time Logs for my SvelteKit page deployed on Cloudflare Pages by executing the following command on my PC:
> wrangler pages deployment tail 1927c4ba-d66c-4a71-8343-4a7c8045d265   

2. Then, I selected the target project:
> kit-ecsite

3. Until last week, the console.log outputs from within the project were displayed here, but now nothing appears.

5. After about 30 seconds, it results in the error stated in Please provide any relevant error logs.

### Please provide any relevant error logs
```text
PS C:\repository\kit-ecsite> wrangler pages deployment tail 1927c4ba-d66c-4a71-8343-4a7c8045d265 
Debugger attached.
Debugger attached.
 ⛅️ wrangler 3.23.0
-------------------
Select a project:
> kit-ecsite
  test
  task-schedule
  cloudflare-memo
  kit-d1-proxy
  cloudflare-test

X [ERROR] A request to the Cloudflare API (/accounts/1f60a750acc192ddfcb4077542357b40/pages/projects/kit-ecsite/deployments/1927c4ba-d66c-4a71-8343-4a7c8045d265/tails) failed.

  An unknown error occured. Contact your account team or Cloudflare support: https://cfl.re/3WgEyrH.
  [code: 8000000]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose


Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

**Comment by AsyncBanana** [comment]
This is happening for me as well. Both the wrangler and dashboard log streaming fail to work.

**Comment by juanpmarin** [comment]
Same issue here

**Comment by Cherry** [comment]
I believe this was due to https://www.cloudflarestatus.com/incidents/dr8pkxg4qztl and should now be fixed.

**Comment by penalosa** [comment]
Thanks @Cherry! I'll close this out for now, but @okamototomoyuki feel free to open a new issue if the problem persists
