### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by charlesetc** [cloudflare/workers-sdk#4835]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Other

### What version(s) of the tool(s) are you using?

3.24.0

### What version of Node are you using?

v20.7.0

### What operating system are you using?

Mac

### Describe the Bug

I'm hoping to use Astro and access durable objects. I have a src/dobject.js file with a hello world durable object. Then I have the following in wrangler.toml:

```
[durable_objects]
bindings = [
  { name = "DOBJECT", class_name = "DObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["DOBject"]
```

and this adapter configuration in astro.config.mjs:

```
  adapter: cloudflare({
    runtime: {
      "DO": { 
        type: "durable-object",
        className: "DObject",
      },
    }
  }),
```

When I run wrangler deploy I get the following error:

```
[...]
Uploaded 100% [1 out of 1]
Removing 1 stale asset...
↗️  Done syncing assets
Your worker has access to the following bindings:
- Durable Objects:
  - DOBJECT: DObject
Total Upload: 190.99 KiB / gzip: 55.43 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/771075126a31746d5e4a9b10b7357afd/workers/scripts/lionsmane) failed.

  Uncaught TypeError: Class extends value undefined is not a constructor or null
    at null.<anonymous>
  (file:///Users/charles/code/lionsmane/.wrangler/tmp/bundle-CEf6Rr/middleware-insertion-facade.js:15:6)
  in maskDurableObjectDefinition
    at null.<anonymous>
  (file:///Users/charles/code/lionsmane/.wrangler/tmp/bundle-CEf6Rr/middleware-insertion-facade.js:24:28)
   [code: 10021]


  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

Any idea what is going on? Happy to provide any more information.

### Please provide a link to a minimal reproduction

The error happens with this code: https://github.com/charlesetc/lionsmane/

**Comment by penalosa** [comment]
Thanks for reporting this! Unfortunately, I think this may be an issue on the Astro side rather than with Wrangler directly. I'd recommend opening an issue at https://github.com/withastro/adapters. I'm going to close this for now, but feel free to open a new issue if Astro confirms that this is an issue on the Wrangler side. cc @dario-piotrowicz for reference

**Comment by dario-piotrowicz** [comment]
@penalosa thanks for pinging me 🙂 

@charlesetc This is something that we've already discussed with the Astro team, they should support your use case soon (as soon as they can use the `getBindingsProxy` utility), right @alexanderniebuhr?

**Comment by alexanderniebuhr** [comment]
Correct we should be able to support that very soon. 

**However,** it would be great if someone could contribute this use-case to the tests of the Cloudfare adapter in this repository (https://github.com/withastro/adapters) as a PR. So we can make sure the update provides the expected outcome.

**Comment by charlesetc** [comment]
So are durable objects not supported with Astro right now? The docs made it seem like they were. Maybe I'm missing some way in which my use case is different from the normal one or I've made some mistake alone the way. Thanks for the help, all!

**Comment by charlesetc** [comment]
Gotcha!
