### ISSUE TITLE
🐛 BUG:✘ [ERROR] A request to the Cloudflare API failed.

### ISSUE THREAD

**Issue by makoto** [cloudflare/workers-sdk#4837]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

"@cloudflare/workers-types": "^4.20240117.0"

### What version of Node are you using?

v18.18.0

### What operating system are you using?

Mac (but the error is from the API)

### Describe the Bug

When I deploy https://github.com/ensdomains/evmgateway/blob/cloudflare-worker-bug-test-case/arb-gateway/  with `npx wrangler deploy --env sepolia` then I get `'✘ [ERROR] A request to the Cloudflare API (/accounts/15dcc9085cb794bb4f29d3e8177ac880/workers/scripts/arb-sepolia-gateway-worker) failed.
'` error

### Please provide a link to a minimal reproduction

https://github.com/ensdomains/evmgateway/blob/cloudflare-worker-bug-test-case/arb-gateway/

### Please provide any relevant error logs

```
warning @ensdomains/arb-gateway@0.1.0: The engine "bun" appears to be invalid.
$ echo 'building arb-gateway...' && bun run clean && bun run build:cjs && bun run build:esm && bun run build:types
building arb-gateway...
$ rm -fr _cjs _esm _types
$ tsc --project tsconfig.build.json --module commonjs --outDir ./_cjs --removeComments --verbatimModuleSyntax false && echo > ./_cjs/package.json '{"type":"commonjs"}'
$ tsc --project tsconfig.build.json --module es2022 --outDir ./_esm && echo > ./_esm/package.json '{"type":"module","sideEffects":false}'
$ tsc --project ./tsconfig.build.json --module esnext --declarationDir ./_types --emitDeclarationOnly --declaration --declarationMap
✨  Done in 2.96s.
▲ [WARNING] Enabling Node.js compatibility mode for built-ins and globals. This is experimental and has serious tradeoffs. Please see https://github.com/ionic-team/rollup-plugin-node-polyfills/ for more details.


Total Upload: 3733.65 KiB / gzip: 869.20 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/15dcc9085cb794bb4f29d3e8177ac880/workers/scripts/arb-sepolia-gateway-worker) failed.

  Uncaught TypeError: globalThis.XMLHttpRequest is not a constructor
    at worker.js:87600:11 in checkTypeSupport
    at worker.js:87622:38 in
  ../../../../.nvm/versions/node/v18.18.0/lib/node_modules/wrangler/node_modules/rollup-plugin-node-polyfills/polyfills/http-lib/capability.js
    at worker.js:16:56 in __init
    at worker.js:87887:5 in
  ../../../../.nvm/versions/node/v18.18.0/lib/node_modules/wrangler/node_modules/rollup-plugin-node-polyfills/polyfills/http-lib/request.js
    at worker.js:16:56 in __init
    at worker.js:88105:5 in node-modules-polyfills:http
    at worker.js:16:56 in __init
    at worker.js:88225:21 in node-modules-polyfills-commonjs:http
    at worker.js:19:51 in __require2
    at worker.js:88244:16 in ../node_modules/methods/index.js
   [code: 10021]
```

**Comment by penalosa** [comment]
It looks like you're trying to use the `node:http` module within workers, which isn't currently supported. I’m going to close this issue for now, since this is a limitation of the `node_compat` system. Going forward, the Workers runtime is working on [adding support for more Node.JS builtins](https://developers.cloudflare.com/workers/runtime-apis/nodejs/), including possibly the `node:http` module. 

In the meantime, the best solution for now is to include your own polyfills of Node.JS builtins like `http`.
