### ISSUE TITLE
🐛 BUG: Miniflare logs CRON warning on every reload

### ISSUE THREAD

**Issue by DaniFoldi** [cloudflare/workers-sdk#4859]
### Which Cloudflare product(s) does this pertain to?

Miniflare

### What version(s) of the tool(s) are you using?

3.20231218.4

### What version of Node are you using?

20.8.0

### What operating system are you using?

macOS

### Describe the Bug

Hi :wave:,

When creating a worker with cron trigger, wrangler dev/miniflare logs a warning every time the script is reloaded.

Note that when I first ran into this, I found the exact message confusing as well (what is being ignored?), since miniflare _does_ support cron triggers, just doesn't fire them automatically.

Screenshot of current warning (copied from Discord, originally uploaded by `@bachmacintosh`):
![image](https://github.com/cloudflare/workers-sdk/assets/6977583/80849f02-8549-4a84-bc74-cbe21cd4d9d9)

In my opinion, a warning message similar to this would be more appropriate, especially if only logged once when the process is started:
```
[WARNING] Miniflare 3 doesn't currently trigger scheduled workers automatically.
Use --test-scheduled to forward fetch triggers.
```

**Comment by admah** [comment]
Thanks for filing this @DaniFoldi! It would be great if:
- we just showed this once when the user starts a new dev session
- we categorized this as `info` instead of a `warning`? Warning feels a little heavy here.

cc: @mrbbot
