### ISSUE TITLE
🐛 BUG: --json flag in `wrangler d1 execute` swallows debug information on error

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#4871]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

latest

### What operating system and version are you using?

.

### Describe the Bug

.

**Comment by rozenmd** [comment]
@lrapoport-cf just FYI it looks like there's a bug in the `workers-sdk` automation, it keeps assigning this d1 issue to workers-sdk

**Comment by lrapoport-cf** [comment]
> @lrapoport-cf just FYI it looks like there's a bug in the `workers-sdk` automation, it keeps assigning this d1 issue to workers-sdk

@rozenmd  hmm have you noticed the same problem on any other D1 issues?
