### ISSUE TITLE
🚀 Feature Request [getBindingsProxy]: `getBindingsProxy` should expose a `cf` object

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/workers-sdk#4875]
In the `getBindingsProxy` return object we should include a [`cf` object](https://developers.cloudflare.com/workers/runtime-apis/request/#incomingrequestcfproperties) that developers can use to mock the real production thing.

It should reuse the same functionality Miniflare already implements: https://github.com/cloudflare/workers-sdk/blob/6a4cb8c6456f1dba95cae2b8bbe658f7227349f8/packages/miniflare/src/cf.ts

For that we either:
- need to expose the `setupCf` function: https://github.com/cloudflare/workers-sdk/blob/6a4cb8c6456f1dba95cae2b8bbe658f7227349f8/packages/miniflare/src/cf.ts#L70
So that we can all it from wrangler/`getBindingsProxy`
- or add a `cf` or `getCf` to the Miniflare class

I did think that the former could be better (since it doesn't force the caller to be tied to the Miniflare instance), but I changed my mind and actually think that the latter could be better (since we already do have a Miniflare instance and get the `cf` from it... also other Miniflare users could make use of such additional field/method)

(In any case either should do)

**Comment by houmark** [comment]
Hey guys! Any timeline on this one?

**Comment by dario-piotrowicz** [comment]
Hi @houmark, this should make it into one of the stable releases next week (I would be very very surprised if it doesn't) 🙂

For it we just need to merge: https://github.com/cloudflare/workers-sdk/pull/4905 and then simply expose the `cf` in `getBindingsProxy` 🙂

**Comment by houmark** [comment]
Brilliant! Thanks so much!

**Comment by dario-piotrowicz** [comment]
No problem 🙂👍
