### ISSUE TITLE
🐛 BUG: `account_id` is not passed to the `/zones` endpoint

### ISSUE THREAD

**Issue by ichernetsky-cf** [cloudflare/workers-sdk#4944]
### Which Cloudflare product(s) does this pertain to?

Other

### What version(s) of the tool(s) are you using?

Latest Wrangler

### What operating system and version are you using?

Linux

### Observed behavior

Wrangler gets the error below when deploying a Worker.

```
Listing zones across more than 500 accounts is currently not allowed, please apply the 'account.id' filter
```

### Expected behavior

As the error message suggests, [gertZoneIdFromHost](https://github.com/cloudflare/workers-sdk/blob/2b71e22f86be35068eac3713b7e6eefbf04a0970/packages/wrangler/src/zones.ts#L89) should pass `account_id` to the `/zones` endpoint.

**Comment by taylorlee** [comment]
The issue is [here](https://github.com/cloudflare/workers-sdk/blob/2b71e22f86be35068eac3713b7e6eefbf04a0970/packages/wrangler/src/zones.ts#L89). We need to add 'account.id' to URLSearchParams, which presumably means passing the account down through all the calls above getZoneIdFromHost.
