### ISSUE TITLE
🐛 BUG: wrangler pages project create does not respect CLOUDFLARE_ACCOUNT_ID

### ISSUE THREAD

**Issue by matthewjosephtaylor** [cloudflare/workers-sdk#4947]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.27.0

### What version of Node are you using?

20.9.0

### What operating system and version are you using?

Mac Darwin Kernel Version 23.0.0

### Observed behavior
```
CLOUDFLARE_ACCOUNT_ID=<account id> npx wrangler pages project create 
```
uses the account that I originally created/deployed to NOT the account specified.

I also tried CF_ACCOUNT_ID as some documentation refers to that but no joy.

### Expected behavior
I expect to be able to create and deploy a codebase to multiple accounts

In general I'm quite frustrated by the lack of transparency in how Pages behaves to how things like workers behave. 

I really would hope and expect a standard wrangler.toml file configuration would be how this would work.

At the very least I expect environment variables to work as the documentation suggests it should.

### Steps to reproduce

1. create a pages project with an account A
2. try to create a new project to deploy the existing codebase to account B
3. note that there is no way to switch accounts.

**Comment by matthewjosephtaylor** [comment]
Work-around:
- Remove node_modules/.cache/wrangler/pages.json, wrangler-account.json

Once removed then the environment variable appears to work as expected and creates new JSON objects in the cache folder, and creates the page in the correct account.

Once again I will state that this is very magic-y and not an expected way to deal with configuration. Using the `.cache` folder inside node_modules is way less obvious/expected. There is already a .wrangler folder at the top level of the project created by wrangler dev, would expect wrangler to be _consistent_. IMHO consistency in a tool like wrangler is a MUST. 

I get it that these are 'hidden' folders but hopefully you understand that for developers using the tool these an essential part of the tool as it is _vital_ to know how things work so that problems and issues like this can be resolved quickly.

So my further suggestions if anyone cares is to:
- have pages store its configuration information in the project top level .wrangler folder
- document and don't be ashamed that you have to store information like this. I as a developer _expect_ a tool like this to need somewhere to store state information, it just needs to be consistent. It makes my job easier to work with your tool if I can trust and know where it stores it state, and can inspect it.

**Comment by admah** [comment]
@matthewjosephtaylor thank you for taking the time to file this and to write out your thoughts on improving. This is definitely something we are taking a look at. I'm going to move this into our backlog so we can address it.

**Comment by nativedone** [comment]
Hi @admah do you have any news about this one? Asking because it says effort is small and priority is High - this would unlock the use of pages inside monorepos linked to a user with multiple accounts. Think about agencies dealing with clients accounts.

**Comment by oliy** [comment]
We just hit this as well.  Please prioritize!
