### ISSUE TITLE
🐛 BUG: Wrangler live-reload breaks node_compat imports

### ISSUE THREAD

**Issue by lepinsk** [cloudflare/workers-sdk#4960]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

wrangler 3.28.0

### What version of Node are you using?

v20.10.0

### What operating system and version are you using?

Linux (GitHub Codespace Dev Container)

### Observed behavior

When importing a nodejs module (for example `node:crypto`), `wrangler` will run the code initially, but if any changes are made to the code (causing `wrangler` to do a live-reload), it will complain that the module is not found.

### Expected behavior

Imported modules will continue to work through live reloads.

### Steps to reproduce

Worker code (`src/bugtest.js`):

```js
import { createHmac } from 'node:crypto';

export default {
  async fetch(request, env) {
    return new Response('Object Not Found', { status: 404 });
  }
}
```

Wrangler config (`wrangler.toml`):

```toml
name = "bug-reproduction"
main = "src/bugtest.js"
compatibility_date = "2023-12-14"
env = { }

account_id = "XXXXXXXXXXXXXXXXXX"
workers_dev = true

compatibility_flags = ["nodejs_compat"]
```

Reproduction Steps:

* run `wrangler dev` on a project containing the above worker source and wrangler config files
* note that `wrangler` will start up and the code will properly execute and respond to web requests
* make *any change to the code whatsoever* (for example, add a `console.log` line before the `Response`), and save the file
* `wrangler` will live reload, and throw the following error:

> ```
> ✘ [ERROR] Could not resolve "node:crypto"
> 
>     src/bugtest.js:1:27:
>       1 │ import { createHmac } from 'node:crypto';
>         ╵                            ~~~~~~~~~~~~~
> 
>   The package "node:crypto" wasn't found on the file system but is built into node.
>   Add "node_compat = true" to your wrangler.toml file and make sure to prefix the module name with "node:" to enable Node.js compatibility.
> ```

### Please provide any relevant error logs

```
✘ [ERROR] Could not resolve "node:crypto"

    src/bugtest.js:1:27:
      1 │ import { createHmac } from 'node:crypto';
        ╵                            ~~~~~~~~~~~~~

  The package "node:crypto" wasn't found on the file system but is built into node.
  Add "node_compat = true" to your wrangler.toml file and make sure to prefix the module name with "node:" to enable Node.js compatibility.
```

**Comment by Cherry** [comment]
I think this might be a duplicate of https://github.com/cloudflare/workers-sdk/issues/4959

**Comment by lepinsk** [comment]
@Cherry — hah, beat me by 3 minutes! Looks like I missed it because it didn't exist when I started writing my bug report 🙂 

I'l close mine off.
