### ISSUE TITLE
Cannot find module '__STATIC_CONTENT_MANIFEST'

### ISSUE THREAD

**Issue by whoabuddy** [cloudflare/workers-sdk#4968]
While trying to migrate an API that's working on Service Workers to the new Module Workers format we're seeing some issues while following the [documentation in the README](https://github.com/cloudflare/kv-asset-handler#es-modules).

The main goal here is to create an API that will also upload a folder of static assets, primarily used for a landing page and openAPI documentation. Any pattern that does not match a static asset is redirected to the itty-router.

## What's working

The [older working implementation is here](https://github.com/citycoins/api) and you can see an example of the content below:

- static file that matches pattern: https://api.citycoins.co/openapi.yml
- static (using file above as src): https://api.citycoins.co/docs
- API route handled by itty-router: https://api.citycoins.co/mia/tools/get-full-city-configuration

The [wrangler.toml configuration](https://github.com/citycoins/api/blob/387a0a39f273a3b411e9d332c5c6e26491b11f8d/wrangler.toml) handles the upload of the assets to KV, and the [main index file](https://github.com/citycoins/api/blob/387a0a39f273a3b411e9d332c5c6e26491b11f8d/src/index.ts#L108-L132) handles matching the download or sending the request to the router.

## What's not working

There were a few roadblocks when trying to set this up from scratch again, and the [newer implementation is located here](https://github.com/citycoins/protocol-api/).

### What's been done so far:

- set up new project with `wrangler generate` from `⛅️ wrangler 2.7.1`
- migrated workers code from services workers to module format
- installed all necessary dependencies and copied folder for static assets
- tested both locally and by publishing with a few errors along the way
- tested various approaches to the problem, more details below

Before getting into the nitty-gritty, this does feel *very close to an answer*, however documentation varies both on accuracy and relevancy depending on the source. Any help is greatly appreciated and hopefully this will serve as a good source of info for others as well.

### Problems encountered

This line from the README results in an error - no module found!

```
import manifestJSON from "__STATIC_CONTENT_MANIFEST";
Cannot find module '__STATIC_CONTENT_MANIFEST' or its corresponding type declarations.ts(2307)
```

Using the variable later it shows undefined (as expected): `SyntaxError: "undefined" is not valid JSON` and returns HTTP 500 as a result.

To work around this we've tried:

- adding a KV binding to the worker and using it instead of the default
- adding definitions to `Env` in `src/index.ts` for the STATIC references
- various configuration tweaks based on other issues described online

There was one point where we were seeing 404s because no KV binding was present in wrangler.toml, but the main issue we keep coming back to is no way to list out the static files stored in KV to match the request. 

Generating a manual manifest feels messy and given the limited documentation (or accurate documentation, given recent changes) we can find, this already feels like a gray area in the first place.

The assets get uploaded and those uploads are detected on subsequent runs, e.g. below by adding a new file:

```
Reading ms-icon-70x70.png...
Skipping - already uploaded.
Reading openapi-test.yml...
Uploading as openapi-test.1e6889318c.yml...
Reading openapi.yml...
Skipping - already uploaded.
↗️  Done syncing assets
```

## Other Issues

Based on what was reported in cloudflare/workers-sdk#4969 and comments about others running this way, it feels like the configuration above should work?

**Comment by penalosa** [comment]
It sounds like this has been resolved by moving to Pages. If anyone runs it similar issues in the future, feel free to open a new issue and we can take a look.
