### ISSUE TITLE
Spaces in file names results in `NotFoundError`

### ISSUE THREAD

**Issue by CMCDragonkai** [cloudflare/workers-sdk#4970]
I have some files that have spaces in their names. Like `Polykey Logo.svg`.

When requested from the browser, it looks like `https://polykey.io/docs/images/Polykey%20Logo.svg`.

When using `getAssetFromKV`, this ends up not working and throws a `NotFoundError`.

When I changed the file name to `polykey-logo.svg`, it all worked fine.

I saw this is an old issue cloudflare/kv-asset-handler#75 that said it was fixed, but this is definitely not the case.

I'm using:

```
    "@cloudflare/kv-asset-handler": "^0.2.0",
    "wrangler": "^2.0.23"
```

And my compatibility date:

```
    "wrangler": "^2.0.23"
```

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to comment with more details and we can investigate further.

**Comment by CMCDragonkai** [comment]
> [@CMCDragonkai](https://github.com/CMCDragonkai) Note that if you have a custom `mapRequestToAsset` function, you may also need to specify the `pathIsEncoded` option (based on reading the code at https://github.com/cloudflare/kv-asset-handler/blob/264c0b1dd2e9124b7328961594f33cbe66dc8145/src/index.ts#L125-L146).

Awesome that did the trick. It was necessary cause I do have a custom function. Should really be in the docs.
