### ISSUE TITLE
Newly uploaded images return 404

### ISSUE THREAD

**Issue by patibugaj** [cloudflare/workers-sdk#4972]
For almost a month we are struggling with an issue that newly uploaded images return 404. And usually start to appear after a few days.
We are using Gatsby as a build platform and Cloudflare for hosting and for workers. To optimize the assets we are using `@cloudflare/kv-asset-handler` inside the worker implementation. We have contacted Gatsby for a while, but Gatsby previews for the same build work properly.

For example, please take a look at the hero image responses on those previews:
Gatsby preview that works
![image](https://user-images.githubusercontent.com/37595963/165060601-2f9018c6-9aac-4fe7-8c13-3b4b4e351c62.png)
![image](https://user-images.githubusercontent.com/37595963/165061423-9d87a9ef-dbb6-4f51-aa30-0b10f7b22a9f.png)

Cloudlare preview that doesn't work
![image](https://user-images.githubusercontent.com/37595963/165060741-aeb52a04-3d07-48d2-a9b0-d617f2434d96.png)
![image](https://user-images.githubusercontent.com/37595963/165061257-8e9f6e5c-6bb3-4dd1-bc09-2f8d7972b45b.png)

When we fetch gatsby images directly without `@cloudflare/kv-asset-handler` and when we publish content with `workers.dev` everything works properly. The issue started happening without any code changes on our side.

This is our event, that, among other things, is responsible for getting assets with KV:
```
async function handleEvent(event) {
  const url = new URL(event.request.url);

  const options = {};

  try {
    if (DEBUG)
      // customize caching
      options.cacheControl = {
        bypassCache: true,
      };

    const page = await getAssetFromKV(event, options);

    // allow headers to be altered
    let response = new Response(page.body, page);

    response.headers.set('X-XSS-Protection', '1; mode=block');
    response.headers.set('X-Content-Type-Options', 'nosniff');
    response.headers.set('X-Frame-Options', 'DENY');
    response.headers.set('Referrer-Policy', 'unsafe-url');
    response.headers.set('Feature-Policy', 'none');

    const cacheControlHeaders = getCacheControl(url);
    if (cacheControlHeaders.length > 0) response.headers.set('Cache-Control', cacheControlHeaders);

    return response;
  } catch (e) {
    // if an error is thrown try to serve the asset at 404.html
    if (!DEBUG)
      try {
        const notFoundResponse = await getAssetFromKV(event, {
          mapRequestToAsset: req => new Request(`${new URL(req.url).origin}/404.html`, req),
        });

        return new Response(notFoundResponse.body, {
          ...notFoundResponse,
          status: 404,
        });
        // eslint-disable-next-line no-empty
      } catch (e) {}

    return new Response(e.message || e.toString(), { status: 500 });
  }
}
```

**Comment by penalosa** [comment]
I’m going to close this issue for now. Going forward, we’ll revisit the assets system as part of Pages/Workers convergence, and will inherit the benefits of the Pages assets system.

In the meantime, [Pages](https://developers.cloudflare.com/pages/) is the best choice for deploying sites with static assets.
