### ISSUE TITLE
Resolve Unnecessary Event (`Evt`) for Requests

### ISSUE THREAD

**Issue by HelloFillip** [cloudflare/workers-sdk#4973]
Currently when constructing requests for assets with `getAssetFromKV` an `Evt` is needed. The `Event` holds the `Request` object and a `waitUntil` object (as a `Promise`). 

When using the package it was easier to omit the event and use `await` outside of the `getAssetFromKV` function so I omitted it and replaced the `Evt` parameter with a `Request` parameter, adding `await` in the cache persist:

```typescript
await cache.put(cacheKey, response.clone())
```

Noting that this does not result in exactly the same behavior but simplified the function calls. 

Looking back at this the `Evt` allows for additional control in the process but the lack of a simplified API could be resolved with either an alternative function that creates the `Evt` object implicitly, or exporting the `Evt` object and an `Evt` factory function to make the API more intuitive. Both approaches could be used, with the former suitable for cases when a resolvable `Promise` isn't needed, however the latter (an `Evt` factory function) would at least improve the API.

I've made these changes in a local fork already for my own project, so this issue is more about starting a discussion to put it into an acceptable PR, if possible.

**Comment by penalosa** [comment]
I’m going to close this issue for now. Going forward, we’ll revisit the assets system as part of Pages/Workers convergence, and will inherit the benefits of the Pages assets system.

In the meantime, [Pages](https://developers.cloudflare.com/pages/) is the best choice for deploying sites with static assets.
