### ISSUE TITLE
304 `REVALIDATED` `CF-Cache-Status` cache header

### ISSUE THREAD

**Issue by g45t345rt** [cloudflare/workers-sdk#4974]
I'm using this code

```js
const data = await getAssetFromKV(event)
return new Response(data.body, data)
```

and I'm unable to use the cache. I keep getting `MISS` by checking the request in devtools
![image](https://user-images.githubusercontent.com/49697006/135182901-404f86df-544c-424d-aaf9-efb64f247a2f.png)

I can see that it's set to `false` by default
https://github.com/cloudflare/kv-asset-handler/blob/f9bb072da86ec91ae8bb3b0cd06b219e26d638c2/src/index.ts#L159
and only set to `true` if we use ASSET_MANIFEST
https://github.com/cloudflare/kv-asset-handler/blob/f9bb072da86ec91ae8bb3b0cd06b219e26d638c2/src/index.ts#L160-L167

Is this intended or I'm missing something?

**Comment by penalosa** [comment]
It seems like this has been resolved, so I'm going to close this for now. If you're still running into issues feel free to open a new issue with a reproduction.
