### ISSUE TITLE
Cache behavior for 206 responses that includes etags needs investigation

### ISSUE THREAD

**Issue by shagamemnon** [cloudflare/workers-sdk#4975]
cloudflare/kv-asset-handler#133, which enables etag support for all resource types hasn't been merged. When a strong `etag` is presented, partial responses to byte range requests are cached. However when weak `etags` are served, partial responses to range requests are not cached.

The resource types that will gain etag support when cloudflare/kv-asset-handler#133 is merged, and cache behavior on CF, Chromium and Safari, need to be investigated before cloudflare/kv-asset-handler#165 can be merged

_Originally posted by @shagamemnon in https://github.com/cloudflare/kv-asset-handler/issues/165#issuecomment-774694695_

**Comment by penalosa** [comment]
This is a very old issue so I'm going to close it for now. If you're still running into problems feel free to comment with more details and we can investigate further.
