### ISSUE TITLE
Add support for per-KV entry content-type 

### ISSUE THREAD

**Issue by normanr** [cloudflare/workers-sdk#4977]
As mentioned at https://blog.cloudflare.com/catching-up-with-workers-kv/, it should be possible to use getWithMetadata to get key metadata (including the content-type).

I'm not sure if wrangler is populating the KV entry metadata yet. I thought I remember seeing a PR for it, but can't find it to see if it was merged yet or not.

**Comment by penalosa** [comment]
This is a very old issue so I'm going to close it for now. If you're still running into problems feel free to comment with more details and we can investigate further.
