### ISSUE TITLE
Add CORS header to responses

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-sdk#4979]
[GitHub Pages adds `access-control-allow-origin: *` to all pages](https://twitter.com/annevk/status/574261459712143361), so for static content hosted by Cloudflare Workers Sites, I'm guessing it should be safe to do the same.

**Comment by louwers** [comment]
There is also `Cross-Origin-Opener-Policy: same-origin` and `Cross-Origin-Embedder-Policy: require-corp`.

**Comment by penalosa** [comment]
I’m going to close this issue for now. Going forward, we’ll revisit the assets system as part of Pages/Workers convergence, and will inherit the benefits of the Pages assets system.

In the meantime, [Pages](https://developers.cloudflare.com/pages/) is the best choice for deploying sites with static assets.
