### ISSUE TITLE
serveSinglePageApp mime type detection is too aggressive

### ISSUE THREAD

**Issue by osdiab** [cloudflare/workers-sdk#4981]
My app, every.org, is using Cloudflare Workers to host our static bundle. We have URLs for nonprofits, looking like `every.org/<nonprofit slug>`, and slugs can currently have periods in them. so for instance, the url for the popular nonprofit Vote.org is `every.org/vote.org`.

However we found out that because cloudflare tries to read mime types to determine if it should tack on `index.html` or not, and because the `mime` package decides that a `.org` extension ought to be a MIME type of `application/vnd.lotus-organizer`, it decides that this isn't actually supposed to be a page, searches for an asset with that name, can't find it and then hard crashes our website.

We're working around this by not using the `serveSinglePageApp` helper since it's so simple to implement ourselves, but would be nice if the default either didn't presume so much or was clearer that you could bork your site based on your URL scheme. Thanks!

**Comment by penalosa** [comment]
I’m going to close this issue for now. Going forward, we’ll revisit the assets system as part of Pages/Workers convergence, and will inherit the benefits of the Pages assets system.

In the meantime, [Pages](https://developers.cloudflare.com/pages/) is the best choice for deploying sites with static assets.
