### ISSUE TITLE
Investigate cf-cache-status behavior

### ISSUE THREAD

**Issue by shagamemnon** [cloudflare/workers-sdk#4983]
`kv-asset-handler` interacts with cache in some unusual ways. This affects the `cf-cache-status` response header which may or may not be served by Cloudflare cache directly.

To Do:
- Determine if Cloudfare cache is returning a cf-cache-status on all requests
- If `cf-cache-status` is being set redundantly in `kv-asset-handler`, does the cache status value accurately describe the state of the object in cache?
- Are there benefits to setting it anyways? One benefit is that there is no obvious way to write tests without providing the header value

_Originally posted by @shagamemnon in https://github.com/cloudflare/kv-asset-handler/pull/133_

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to comment with more details and we can investigate further.
