### ISSUE TITLE
Cache doesn't clear up when using bypassCache option

### ISSUE THREAD

**Issue by gnuwilliam** [cloudflare/workers-sdk#4984]
#### Environment

* operating system: `macOS`
* output of `rustc -V`:`rustc 1.33.0 (2aa4c46cf 2019-02-28)`
* output of `node -v`: `v12.16.1`
* output of `wrangler -V`: `👷 ✨  wrangler 1.9.2`
* contents of `wrangler.toml`: `type: webpack` - using a standard Gatsby template

#### Steps to reproduce

- Run `wrangler publish` with `bypassCache: true` or set the `edgeTTL` to a specific value and send a new build
- Access the build

#### What did you expect to see?

- The new version of the build being served

#### What did you see instead?

- The older version of the build (have to manually empty the browser cache, on both desktop and mobile - Chrome latest version, to see the new version)

---

Basically, what's happening is that when I send a new build using the cache options available, instead of getting a fresh version of the build (it's a Gatsby static website), I see the older version, and have to keep cleaning the cache on the client side to see the new content. What I'd expect is that when I send a new version of the static content, it'll serve that new version, and cache it (say for 24h or 1 week).

I'd like to ask if there's any additional step that I didn't take, or any extra documentation on caching that would help me solve this issue, maybe a manual purge on the worker or something? I'd be glad to share more information if needed.

Thank you!

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to comment with more details and we can investigate further.
