### ISSUE TITLE
Mocks response.body and request.body aren't readable streams

### ISSUE THREAD

**Issue by shagamemnon** [cloudflare/workers-sdk#4986]
- This is a bug in the `service-worker-mock` package and is tracked here: https://github.com/zackargyle/service-workers/issues/135
- This bug only affects `kv-asset-handler` when invoking `response.body.cancel()`

**Comment by penalosa** [comment]
This is a very old issue so I'm going to close it for now. If you're still running into problems feel free to comment with more details and we can investigate further.
