### ISSUE TITLE
Improving SPA index.html detection

### ISSUE THREAD

**Issue by EatonZ** [cloudflare/workers-sdk#4988]
I have an Angular app. A standard Angular app consists of an index.html and several js bundle files.
In my Workers Sites app, the general `Cache-Control` setting I want to use for all assets is `max-age=86400`. There is 1 exception to this - the index.html. I want to use `no-cache` for that. However, differentiating the index.html from other assets has proven rather tricky.

Here is my code:

```js
let isIndex = false;
response = await getAssetFromKV(event, { mapRequestToAsset: request =>
{
    //KV is case-sensitive. We will only publish files with names in lower-case, so force the request URL path to be lower-case.
    //https://community.cloudflare.com/t/workers-sites-missing-images/121633/9
    const defaultAssetKey = serveSinglePageApp(request);
    const defaultAssetKeyUrl = new URL(defaultAssetKey.url);
    defaultAssetKeyUrl.pathname = defaultAssetKeyUrl.pathname.toLowerCase();

    isIndex = defaultAssetKeyUrl.pathname.endsWith("index.html");

    return new Request(defaultAssetKeyUrl.toString(), defaultAssetKey);
}, cacheControl : { edgeTTL: 31536000 } }); //We cannot set browserTTL in here at this time because we don't know at this point if the requested asset will end up being index.html or something else.

if (isIndex) response.headers.set("Cache-Control", "no-cache");
else response.headers.set("Cache-Control", "max-age=86400");
```

As-is, that works and does what I need, but I feel it could be better.

Here's what I mean. I am aware that `options` has `browserTTL`. However, at the point where options need to be specified, I cannot determine whether the asset being processed is going to end up being index.html or something else. That's the job of the `serveSinglePageApp` function. As you can see in my code, I came up with a workaround.

Ultimately, I would like to be able to set `options.browserTTL` to make things look clean, but I'm not sure how that is possible given the way this is currently designed.

Thoughts?

**Comment by andyjessop** [comment]
I'm going to close this because it's been a few years since we've had any action and the issue is ultimately solved.
