### ISSUE TITLE
better handle paths without extensions

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/workers-sdk#4989]
Reported in https://github.com/cloudflare/wrangler/issues/980

if a path does not have a recognized extension, we currently assume that it is pointing to an html file, so `hostname.ext/foo` is automatically converted to `hostname.ext/foo/index.html`. This is rather specific to the expectations of a few select static site generators (esp hugo), however, it messes with files that have no extension (in the above issue, files under `**/.well-known/*`), and with other static site generators such as jekyll, who assume that `hostname.ext/foo` should be evaluated as `hostname.ext/foo.html`.

we need to update the default fetch from kv logic to:

* try the original path first before trying other variations
* try using `Accept` headers to evaluate mimetypes that cannot be evaluated based on extension

Depending on implementation these could be breaking changes; however if implemented properly they should be backwards compatible.

**Comment by penalosa** [comment]
I’m going to close this issue for now. Going forward, we’ll revisit the assets system as part of Pages/Workers convergence, and will inherit the benefits of the Pages assets system.

In the meantime, [Pages](https://developers.cloudflare.com/pages/) is the best choice for deploying sites with static assets.
