### ISSUE TITLE
🚀 Feature Request: can specify certificate and key with `wrangler pages dev  --local-protocol=https`

### ISSUE THREAD

**Issue by eltorio** [cloudflare/workers-sdk#4992]
### Describe the solution

We cannot choose a specific certificate for use with --local-protocol=https .  
It is very important in the local test process. 
Having a certificate is needed for setting a trusted communication.
Currently the certificate change after each restart. It makes the tests more complicated.

**Comment by admah** [comment]
@eltorio thank you for submitting this. I believe this should be taken care of by https://github.com/cloudflare/workers-sdk/pull/4475

**Comment by briacl** [comment]
@admah sure

**Comment by petebacondarwin** [comment]
Resolved by #4475
