### ISSUE TITLE
🚀 Feature Request: wrangler secrets:bulk from .dev.vars file (or splitting dev secrets)

### ISSUE THREAD

**Issue by nulltrope** [cloudflare/workers-sdk#4994]
### Describe the solution

I'm not new to workers, but am new to using wrangler (we typically use our own in-house uploader to manually bundle and upload workers via the API directly). 

Something I quickly noticed is that I imagine in most dev's workflows, they will be iterating locally and adding any secret values (and other values) needed by their worker into `.dev.vars` file. 

However, when it comes time to deploy, at least for secrets, you now need to one-by-one run `wrangler secret put <name>` and copy/paste them in. This surprised me, as I expected some way to simply bulk-add all secrets in my local `.dev.vars` file. 

Now, I understand not all vars in the `.dev.vars` file might be secret, and since it's a simple key=value syntax, it would be tricky to indicate a particular value as being secret. 

As such, I think it might make sense to introduce a second file named something like `.dev.secrets` that, for all intents and purposes, behaves the same as the existing `.dev.vars` file (and would most likely be merged, with one taking priority). However, the new "secrets" file would be able to be passed in as a flag to one of the wrangler secrets* commands, and simply upload them all in one go to "bootstrap" your worker's secrets. 

If this seems useful to folks, I would be happy to take a try at implementing something.

**Comment by admah** [comment]
@nulltrope thanks for writing out this idea. I'd love to leave it open for others to comment on and upvote. 

In the meantime, we do have a `secrets:bulk` command ([docs](https://developers.cloudflare.com/workers/wrangler/commands/#secretbulk)) you can use. It takes all secrets from a `json` file and uploads them at the same time. While not used in local development, it does provide a way to quickly populate all secrets for your project.

**Comment by penalosa** [comment]
Closing as duplicate of https://github.com/cloudflare/workers-sdk/issues/6388, which is probably the approach we'll take to address this (support the `.dev.vars` format in `secrets:bulk`)

**Comment by MattieTK** [comment]
Heads up for future viewers that we now support this feature for .dev.vars and .env formats https://developers.cloudflare.com/workers/wrangler/commands/#secret-bulk
