### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by AMIRSOHAIL1998** [cloudflare/workers-sdk#5003]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

wrangler 3.13.2 

### What version of Node are you using?

20.

### What operating system and version are you using?

mac somana

### Observed behavior
Please describe.

### Expected behavior
Please describe.

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suit on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

  ✘ [ERROR] A request to the Cloudflare API (/accounts/f2c26572962ef04907367459df7786bb/workers/scripts/platform) failed.
    workers.api.error.unauthorized [code: 10023]
    
    If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose
  error Command failed with exit code 1.
  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: The process '/usr/local/bin/yarn' failed with exit code 1
Error: 🚨 Action failed

**Comment by admah** [comment]
Hello @AMIRSOHAIL1998 the error you have looks like an authentication error. Could you provide more info on how you got that error? What command were you running? Can you also try to run `wrangler whoami` to make sure you are logged in and that you have correct permissions?

**Comment by petebacondarwin** [comment]
Closing as this looks like the user was not authenticated correctly and there is no obvious action we can take.
