### ISSUE TITLE
🐛 BUG: C3 fails to create a new project from workers-rust template

### ISSUE THREAD

**Issue by admah** [cloudflare/workers-sdk#5008]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

2.11.3

### What operating system and version are you using?

Mac OS

### Observed behavior

Running this command `npx create-cloudflare@latest --template cloudflare/workers-sdk/tree/main/templates/experimental/worker-rust` produces an error about a missing `wrangler.toml` file. The project has a valid `wrangler.toml` as well as `package.json` and `src` directory.

![Screenshot 2024-02-13 at 3 34 26 PM](https://github.com/cloudflare/workers-sdk/assets/2184114/11af9e2c-fe5e-4d4c-ae1d-296642cd97e2)

### Expected behavior

This should create a new project folder and go through the C3 workflow.

### Steps to reproduce
 
 - run `npx create-cloudflare@latest --template cloudflare/workers-sdk/tree/main/templates/experimental/worker-rust`
 - see error message

**Comment by penalosa** [comment]
Closing for now, since this refers to an experimental template
