### ISSUE TITLE
🚀 Feature Request: Teach `wrangler d1 insights` about more timePeriods

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#5048]
### Describe the solution

Currently, `wrangler d1 insights --timePeriod` supports `1d`, `7d` and `31d` as timePeriod options.

We should support `min[s]`, `hr[s]` and any `d` up to `31d`.

This means we'd need to block queries above 31d in equivalent hours/minutes too (there isn't more than 31 days of data retention, but may as well save an API call by parsing input args instead).

**Comment by achanda** [comment]
I took a stab at implementing this in the linked PR. I can add tests and docs once I make sure the implementation looks good.
