### ISSUE TITLE
🚀 Feature Request: Add flag to hide wrangler CLI UI box

### ISSUE THREAD

**Issue by mcunningham** [cloudflare/workers-sdk#5063]
### Describe the solution

I'd like to request a cli flag or non-interactive option to be added that hides the CLI UI box that is created by wrangler that gives the following options

> [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit

 I get this when running `wrangler dev` but this would be applicable to any other wrangler command that spawns that box.

<img width="962" alt="Screenshot 2024-02-20 at 3 07 00 PM" src="https://github.com/cloudflare/workers-sdk/assets/56338479/4666acc4-0e85-4a1c-bfda-bc7839e23fdc">

My use case for this is I'm using the wrangler CLI in the context of a monorepo ([turborepo](https://turbo.build/)) which has it's own CLI UI to combine multiple process logs one view and it seems to be pretty incompatible with the wrangler UI as it repeats that box outline for each line logged. I still would like to see the logs that are produced by application just not the "UI" that surrounds it as It's quite hard to view logs this way for me.

<img width="803" alt="Screenshot 2024-02-20 at 3 25 13 PM" src="https://github.com/cloudflare/workers-sdk/assets/56338479/d6d0b6fa-3f4b-451f-a69f-d27e104ce70c">

I could see how this could also be useful in other non-interative CLI environments as well.

**Comment by mimukit** [comment]
I'm facing same issue with [Nx](https://nx.dev/) monorepo tool. A feature to hide or disable the UI box will be appreciated.
