### ISSUE TITLE
🐛 BUG: production-branch is required on wrangler project create (but optional in docs)

### ISSUE THREAD

**Issue by adeherysh** [cloudflare/workers-sdk#5065]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.13.2

### What version of Node are you using?

20.9.0

### What operating system and version are you using?

Linux

### Observed behavior
Please describe.

### Expected behavior
Please describe.

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suit on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

**Comment by admah** [comment]
@adeherysh could you provide more context on this issue? Do you have a link to the docs in question? How do those docs differ from the experience you're seeing in Wrangler?

**Comment by lrapoport-cf** [comment]
hi @adeherysh  :) we haven't heard from you in a while, so we’re going to close this issue for now, but if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and any additional requested details, followup, or context and we will revisit and investigate further. thanks!
