### ISSUE TITLE
🐛 Bug Report — Playground: Multiple `Set-Cookie` headers not shown in raw HTTP response

### ISSUE THREAD

**Issue by tien** [cloudflare/workers-sdk#5073]
Setting multiple cookie via headers will only have the final set cookie sent

[reproduction](https://workers.cloudflare.com/playground#LYVwNgLglgDghgJwgegGYHsHALQBM4RwDcABAEbogB2+CAngLzbMutvvsDMADAJy8B2AZwCMAVgBMnXpJGiAHABZeikQDZ5fNRpEAuDgcNse-IaMnTZC5ao1adAWABQAYXRUIAUw-YAIlABnGHQAqGh3XRIMLDwCYhIqOGBPBgAiKBpPAA8AOgArANTSVCgwbySU9MzcgtTnNw9vCGwAFToYT0i4GBgwKABjAih3ZDy4ADc4AP6EWAgAamB0XHBPZ2ds4KQSXE9UOHAIEgBvJwBIKboqfqjPCH6ACwAKBE8ARxBPAIgAGhJvcZ-foQLIAShO5zO-Xc3xID08cF2CACJAYCU8AHcSAAJBFIgJPUFEJyQ+GIzzInLdDo0J6pADKd2wbnQAGsoJ5Un9Uhh0AwRKkiaS8RSAlSet5cHTGc0WezOdyyIgGBJBcTIchkCQWg9AiQMv0wCBdiiKBAHiQeeh0KkSAAyS1KhCpSHQqgBdBlHJgdAAcyeZPxOV9dxlco5hKFGq1ADl3CRoWyOXCRQgSBjMKyUVN-lkOsDPLhheTKdTJXSqJhgHAwNhE-KuZaBUKzmdA6LxTSpalK1ga3XrQ3uaqo63NSQAEIgI7mzxRDI1kivIIwuevfqeKDjQvkOgkWfkBDoDEBCnp0pgEjuMB7g1Gk2OxAu1uvCAgBBUdFYgBKX2C7s8J5qF2EoqELP5TlbNtUwCSJ22RH5IQAXxbJDEKQ4lnCMbCDBMQRhHEKQZAkOQRCUFR1E0XhtHkER6ncLwfH8FdQnCKhImiHB8EIUhEmSNJkkIbi4CKecyj4yoyB9Mg6lcBimladpOhIak+kGNjRg9Kh1icY5UmrDIAH0lhWMpUl0KpdhqQokKwnD7JYPCzEIywSOsCi7GonRmGcIA)

**Comment by tien** [comment]
@mrbbot thanks for looking into this. I'm also getting this issue when running worker locally via `wrangler dev`, haven't tested this in a deployed environment yet.

**Comment by tien** [comment]
@mrbbot I've just tested this on a deployed worker & the behaviour remains the same, only the final set cookie is sent to the client.

**Comment by penalosa** [comment]
@tien I can reproduce this in the Playground, but I can't seem to repro this with a deployed worker or with `wrangler dev`. I deployed your reproduction code at https://workers-playground-sparkling-field-1b7b.s.workers.dev, and that seems to correctly set both `foo` and `bar` cookies in the response. Could you link a reproduction of the issue with a deployed Worker?

**Comment by tien** [comment]
@penalosa okay so did some digging, and you are right cloudflare worker behave correctly once deployed.

I'm using `trpc` and this appears to be an issue with the library that was never fixed trpc/trpc#2312

It just so happen that Cloudflare Worker playground have the exact same issue, sorry if I've sent you on a wild goose hunt 😅
