### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Larrychi101** [cloudflare/workers-sdk#5084]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

3.5.1

### What version of Node are you using?

20.5.1

### What operating system and version are you using?

Mac OS Big Sur

### Describe the Bug

✘ [ERROR] The expected output file at "dist/react-scripts build" was not found after running custom build: npm run build.

  The `main` property in wrangler.toml should point to the file generated by the
  custom build.

name = "agriculture"
type = "webpack"
account_id = "************************"

[build]
command = "npm run build"
[build.upload]
format = "modules"
main = "react-scripts build"

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to comment with more details and we can investigate further.
