### ISSUE TITLE
🐛 BUG: Dynamic require of "node:crypto" is not supported

### ISSUE THREAD

**Issue by dmotz** [cloudflare/workers-sdk#5088]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.29.0 [Wrangler]

### What version of Node are you using?

20.10.0

### What operating system and version are you using?

macOS 14.3

### Observed behavior
I am trying to use an npm package which internally uses Node's crypto module. The module imports it like this:

```js
const crypto = require("node:crypto");
```

I receive this error when running the worker locally:

```
Uncaught Error: Dynamic require of "node:crypto" is not supported
```

I've tried adding this flag to my toml config, but it still fails:
```
compatibility_flags = [ "nodejs_compat" ]
```

### Expected behavior
Workers should support modules that require `node:crypto`.

### Steps to reproduce
Import a module that requires `node:crypto`.

**Comment by tfp-thefinalproject** [comment]
Any update on this issue? I am using Google oAuth for my project with the Sveltekit application, and this is causing an issue since Google oAuth internally uses that library.

**Comment by penalosa** [comment]
We're working on a new way of getting Node.js compatibility which uses a combination of compile-time polyfills and runtime built-ins. With the latest Wrangler you could try this out by adding the `experimental:nodejs_compat_v2` and leave feedback for us to stabilize this. I'll close this issue in favour of #4489.

With that flag enabled, `require("node:crypto")` should work as expected.
