### ISSUE TITLE
🐛 BUG: Could not proxy request error when running wrangler pages dev in HTTPS

### ISSUE THREAD

**Issue by zacwebb** [cloudflare/workers-sdk#5094]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler core

### What version(s) of the tool(s) are you using?

3.29.0 [Wrangler]

### What version of Node are you using?

v20.10.0

### What operating system and version are you using?

MacOS Sanoma 14.3

### Observed behavior
Running a Nuxt server with `wrangler pages dev` and setting `local-protocol` to `https` should work, but instead I'm running into the error:

```
[wrangler] Could not proxy request: TypeError: fetch failed
```

### Expected behavior
HTTPS should work fine 🥲

### Steps to reproduce
See repro readme

### Please provide a link to a minimal reproduction

https://github.com/zacwebb/nuxt-wrangler-pages

### Please provide any relevant error logs

From wrangler logs:

```
[wrangler:inf] GET / 502 Bad Gateway (20ms)
✘ [ERROR] Error: Could not proxy request: TypeError: fetch failed

      at
  /path/to/nuxt-wrangler-pages/node_modules/.pnpm/wrangler@3.29.0/node_modules/wrangler/wrangler-dist/cli.js:105890:29
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async #handleLoopbackCustomService
  (/path/to/nuxt-wrangler-pages/node_modules/.pnpm/miniflare@3.20240208.0/node_modules/miniflare/dist/src/index.js:8296:24)
      at async #handleLoopback
  (/path/to/nuxt-wrangler-pages/node_modules/.pnpm/miniflare@3.20240208.0/node_modules/miniflare/dist/src/index.js:8338:20)
```

**Comment by zacwebb** [comment]
[NuxtHub](https://hub.nuxt.com/) is now released (which uses Wrangler under the hood), and that's working fine with HTTPS 🎉

**Comment by CarmenPopoviciu** [comment]
@zacwebb in that case, is this issue still relevant?

**Comment by petebacondarwin** [comment]
Closing due to lack of response.
