### ISSUE TITLE
🚀 Feature Request: next-on-pages --remote D1

### ISSUE THREAD

**Issue by jonathangreensted** [cloudflare/workers-sdk#5096]
### Describe the solution

Could --remote flag be supported for next-on-pages projects using D1 please?

I'd like this to work:

npm run pages:build && wrangler pages dev .vercel/output/static --compatibility-date=2024-01-17 --compatibility-flag=nodejs_compat --d1 DB=[db-id] --remote

Maybe I'm missing something but it seems tricky to clone the remote db back to my local dev environment.  Happy to be shown a better way!

**Comment by ctarmor** [comment]
This would be nice!

Here is my issue:

https://github.com/cloudflare/workers-sdk/issues/3505#issuecomment-1975219478

**Comment by penalosa** [comment]
Closing as duplicate of https://github.com/cloudflare/workers-sdk/issues/4929
