### ISSUE TITLE
🐛 BUG:  npm create cloudflare@latest -- --template cloudflare/workers-sdk/templates/worker-typescript fails

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/workers-sdk#5120]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

2.13.0

### What version of Node are you using?

21.2.0

### What operating system and version are you using?

MacOS 14.3.1

### Describe the Bug

According to [docs](https://github.com/cloudflare/cloudflare-docs/pull/12684/files#diff-2b2a14b95369fcdd2c0124db5d889e755f66ec047cc682281717849e3a29602dR108) and my understanding of https://github.com/cloudflare/workers-sdk/pull/4754, it should be possible to point the `--template` command to a template that lives within a subdirectory of a repo on GitHub, ex:

```
npm create cloudflare@latest -- --template cloudflare/workers-sdk/templates/worker-typescript
```

In practice, when I run this, I consistently see an error where cloning from a template fails. I get the following output regardless of the degrit field option that I choose (`git@github.com:` prefix, `https://github.com` prefixed, and what is shown below):

```
npm create cloudflare@latest -- --template cloudflare/workers-sdk/templates/worker-typescript

using create-cloudflare version 2.13.0

╭ Create an application with Cloudflare Step 1 of 3
│ 
├ In which directory do you want to create your application?
│ dir ./test
│
├ What type of application do you want to create?
│ type Worker built from a template hosted in a git repository
│
├ What's the url of git repo containing the template you'd like to use?
│ repository cloudflare/workers-sdk/templates/worker-typescript
│
├ Cloning template from: cloudflare/workers-sdk/templates/worker-typescript 
│ template failed
│ 
╰  ERROR  Failed to clone remote template: cloudflare/workers-sdk/templates/worker-typescript
npm ERR! code 1
npm ERR! path /Users/username/src
npm ERR! command failed
npm ERR! command sh -c create-cloudflare --template cloudflare/workers-sdk/templates/worker-typescript

npm ERR! A complete log of this run can be found in: /Users/username/.npm/_logs/2024-02-29T05_40_21_128Z-debug-0.log

```

### Please provide any relevant error logs

```
39 verbose stack     at ChildProcess.<anonymous> (/Users/birvine-broque/.volta/tools/image/npm/10.1.0/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
39 verbose stack     at ChildProcess.emit (node:events:519:28)
39 verbose stack     at maybeClose (node:internal/child_process:1105:16)
39 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

**Comment by admah** [comment]
@irvinebroque I can't seem to reproduce this. 

Have you tried it with Warp off? I'm able to clone it with it on just fine, but feel like I have seen issues like this before with Warp.

**Comment by irvinebroque** [comment]
Yep think that's it 🤦

**Comment by freemedom** [comment]
i have the same problem. " ERROR  Failed to clone remote template: conzorkingkong/cloud-storage"
i have this error when i use powershell. but when i change to cmd, it becomes working normally.

**Comment by freemedom** [comment]
maybe there are some problems about my windows proxy setting.

**Comment by player-roblox** [comment]
my friend is trying to do this with a GitHub link and is getting the same error, can someone guide me through disabling Warp? I looked up how to do it and he didn't have any apps in settings called Cloudflare Warp: https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/remove-warp/
