### ISSUE TITLE
🐛 BUG: Request entity is too large [code: 7011]

### ISSUE THREAD

**Issue by HMilbradt** [cloudflare/workers-sdk#5144]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.30.1

### What version of Node are you using?

18.17.1

### What operating system and version are you using?

14.2.1 (23C71)

### Observed behavior

Running `wrangler pages deploy .vercel/output/static --project-name app` on a "next on pages" app, I'm seeing this error returned from the API.  Everything is as up to date as possible, 

I'm not sure if this is an issue with the workers SDK, or with [next on pages](https://github.com/cloudflare/next-on-pages), so I've decided to open here as there seem to be other issues related to this, though not the same.  Please let me know if I should open the issue over on that repo instead.

According to Finder, folder / file sizes produced are as follows:
- entire folder: ~1GB
- functions folder: ~866MB
- static folder: ~156MB
- _worker.js file: ~182KB

I also have another project that's deployed exactly the same way, which comes in around ~550MB total size, and that deploys successfully.  The two apps are quite similar, one just has many more pages.

I'm assuming I'm hitting some internal limit, as inspecting the build artifacts the two projects are very similar.  I don't see any gigantic files, the only thing that seems to differ is the fact that one bundle is twice as large.

### Please provide any relevant error logs

✘ [ERROR] A request to the Cloudflare API (/accounts/myaccountidhere/pages/projects/app/deployments) failed.

  Request entity is too large [code: 7011]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

**Comment by penalosa** [comment]
I suspect this is hitting either the Pages file size or file number limit—would you be able to provide a reproduction repo that demonstrates the issue?

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to comment with more details and we can investigate further. Pages has a ~25MB file-size limit, and Workers have a ~1-10MB file size limit depending on your plan, and so I suspect you're running into one of those. See https://developers.cloudflare.com/pages/platform/limits/#file-size & https://developers.cloudflare.com/workers/platform/limits/#worker-size for more details.
