### ISSUE TITLE
🐛 BUG: "[ERROR] Cannot infer host from first route: undefined." with Wrangler 3.30.1

### ISSUE THREAD

**Issue by Razzmatazzz** [cloudflare/workers-sdk#5146]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.30.1 [Wrangler]

### What version of Node are you using?

20.11.0

### What operating system and version are you using?

Windows 11

### Observed behavior
When using Wrangler 3.30.1 and attempting to start the worker with `wrangler dev`, I get the following error:
```
X [ERROR] Cannot infer host from first route: undefined.

  You can explicitly set the `dev.host` configuration in your wrangler.toml file, for example:

        
        [dev]
        host = "example.com"

```

This error does not occur if I'm using Wrangler 3.30.0 or lower.

### Expected behavior
Since the changelog does not indicate any kind of breaking change, I would expect future versions to continue working.

### Steps to reproduce
The error is occurring in this repo: https://github.com/the-hideout/tarkov-api

### Please provide a link to a minimal reproduction

https://github.com/the-hideout/tarkov-api

**Comment by andyjessop** [comment]
@Razzmatazzz I'm just looking at this now, but I can't reproduce it with the example you provided. Would it be possible to get a minimal reproduction, so that we can isolate the issue?

**Comment by Razzmatazzz** [comment]
I'm not sure how it got resolved, but at some point I stopped getting this error. Closing this issue now, thanks.
