### ISSUE TITLE
We should delineate internal API errors, wrangler errors, and user errors

### ISSUE THREAD

**Issue by caass** [cloudflare/workers-sdk#515]
There should be a clear difference in how we handle internal API errors, errors that occur within wrangler, and errors that result from the user (e.g. an esbuild failure due to a problem with the worker code).

**Comment by Electroid** [comment]
It would be nice to also delineate between expected API errors and unexpected API errors.

**Comment by penalosa** [comment]
Addressed in https://github.com/cloudflare/workers-sdk/pull/4707, with a distinction between `UserError`s and other `Error`s
