### ISSUE TITLE
🐛 BUG: Worker is always minified, even when using minify = false

### ISSUE THREAD

**Issue by mitya33** [cloudflare/workers-sdk#5150]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

3.22.3

### What version of Node are you using?

20.11.0

### What operating system and version are you using?

Windows 11

### Observed behavior
Error messages are still reported in the context of minified files, making them almost impossible to debug. An example would be:
```
TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at file:///C:/Users/termi/Sync/dev/projects/hlp/v2/apps/back-serverless/.wrangler/tmp/dev-dnY30i/index.js:2179:19
```
That's not the name of one of my files, and certainly the guilty file doesn't have ~2,000 lines in it.

The docs say you can use `minify` in both the Wrangler command (see below) and in the TOML as an inheritable key (also below) but neither seems to affect this behaviour.

### Expected behavior
Files should not be minified, and error reports should reference the original, not derived/minified, files, with accurate line numbers.

### Steps to reproduce

- A minimal working subset of your worker code
Any worker; just cause a JS error to be thrown e.g. call `forEach` on a non-array

- A minimal working subset of your `wrangler.toml`
```
name = "my-app"
main = "src/index.js"
compatibility_date = "2023-11-21"
node_compat = true
minify = false

[env.stage]
hyperdrive = [
	...
]
vars = { ENV = "stage", DB = "stage" }

[env.prod]
hyperdrive = [
	...
]
vars = { ENV = "prod" }
```
- Commands used to start your local dev server, including custom env and cli args
```
wrangler dev --config \"dev.toml\" --remote --port 1933 --minify false
```
(Note, I have to work using `--remote`, for reasons that are unrelated to this issue.)

- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)
Just run the worker using the above command then cause an error as described above.

**Comment by penalosa** [comment]
Wrangler doesn't minify without the `minify` flag set, but it does _bundle_ by default, which is what you're seeing here. See https://developers.cloudflare.com/workers/wrangler/bundling/ for docs on Wrangler's bundling, including how to enable `no-bundle` mode.

**Comment by mitya33** [comment]
Ahh so it's bundling not minifying that I'm seeing, then. That makes sense. Thank you!
