### ISSUE TITLE
🐛 BUG: fetch throws error when run locally (Issue #4823)

### ISSUE THREAD

**Issue by step135** [cloudflare/workers-sdk#5153]
### Which Cloudflare product(s) does this pertain to?

Other

### What version(s) of the tool(s) are you using?

xxxx

### What operating system and version are you using?

xxxx

### Describe the Bug

The issue was closed without any try to fix the bug on your side.

https://github.com/cloudflare/workers-sdk/issues/4823

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to provide a reproduction repo that demonstrates the issue?

**Comment by dairoot** [comment]
You try to download `ca-certificates`，It works for me
```bash
apt-get install -y ca-certificates
```

**Comment by petebacondarwin** [comment]
Closing as there is no reproduction and is likely to be a certificate configuration issue.
