### ISSUE TITLE
🐛 BUG: Attempting to deploy a DO without a Worker gives service-worker related error

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/workers-sdk#5156]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.30.1

### What version of Node are you using?

21.2

### What operating system and version are you using?

Mac latest

### Observed behavior
When trying to deploy a Durable Object, but omitting to include the Worker that interacts with the DO, Wrangler gives back the following error

https://github.com/cloudflare/workers-sdk/blob/23074c7d2124ff19b01aa6f9d6482395bbf0659e/packages/wrangler/src/deployment-bundle/entry.ts#L91C6-L93

```
▲ [WARNING] The entrypoint index.js has exports like an ES Module, but hasn't defined a default export like a module worker normally would. Building the worker using "service-worker" format...

✘ [ERROR] You seem to be trying to use Durable Objects in a Worker written as a service-worker.

  You can use Durable Objects defined in other Workers by specifying a `script_name` in your
  wrangler.toml, where `script_name` is the name of the Worker that implements that Durable Object.
  For example:
  { name = COUNTER, class_name = Counter } ==> { name = COUNTER, class_name = Counter, script_name =
  counter-worker }
  Alternatively, migrate your worker to ES Module syntax to implement a Durable Object in this
  Worker:
  https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/
```

### Expected behavior
I'd expect that Wrangler gave me back an error that told me that I needed to include a Worker when deploying a Durable Object, and didn't assume that the absence of a default export inherently meant I was using the Service Worker format.

### Steps to reproduce

1. Clone [https://github.com/cloudflare/workers-sdk/tree/main/templates/worker-durable-objects](https://github.com/cloudflare/workers-sdk/tree/main/templates/worker-durable-objects)
2. Remove the Worker, leave the DO as is
3. Try to deploy, observe error

**Comment by irvinebroque** [comment]
@vy-ton — re: getting started with DO

**Comment by penalosa** [comment]
I don't believe deploying a DO without a worker is intended to work—would the API not cause issues here?

**Comment by penalosa** [comment]
The messaging here should have been improved by https://github.com/cloudflare/workers-sdk/pull/6872
