### ISSUE TITLE
🚀 Add new `SvelteKit`+ DO (with local dev support) example

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/workers-sdk#5164]
### Describe the solution

> [!NOTE]
> This is a follow up from this issue in our docs repo: https://github.com/cloudflare/cloudflare-docs/issues/13062#issuecomment-1963100362

In our [Template & Examples directory](https://github.com/cloudflare/workers-sdk/tree/main/templates) let's add a new example for a project using SvelteKit with a DurableObject binding and showcase how that can work both locally and in production.

As mentioned in the docs issue I've already created the example here: https://github.com/dario-piotrowicz/sveltekit-durable-object-local-usage-example this could just be copied to our examples but ideally before doing so I think that we should:
 - add a script there to also do the deployment of both the worker and the SvelteKit app (for now it only has a `dev` script)
 - generally polishing the code
 - adding a proper README
 - the example now uses the [handle hook hack](https://github.com/dario-piotrowicz/sveltekit-durable-object-local-usage-example/blob/main/sveltekit-app/src/hooks.server.ts), ideally we should wait for the [proper SvelteKit local dev support](https://github.com/sveltejs/kit/pull/11732) and use that in the example instead
 
Additionally there are a couple of questions that I'd love to hear people thoughts about:
 - could/should we somehow generalize the example to use a generic full stack framework (instead of specifically target SvelteKit)?
 - are our examples discoverable enough? is anyone every going to find this? if not, could we make them more discoverable? (by for example adding a link (or multiple links) in our docs)?

**Comment by admah** [comment]
>> could/should we somehow generalize the example to use a generic full stack framework (instead of specifically target SvelteKit)?

It seems like frameworks are all different (and opinionated) enough to make that a hard task. Generalizing the template might make less sense to developers familiar with the way a framework does things, which would mean it's usage would probably be less. Just some initial thoughts.

>> are our examples discoverable enough? is anyone every going to find this? if not, could we make them more discoverable? (by for example adding a link (or multiple links) in our docs)?

I think we could add links within our own docs, as well as links within the framework's docs (ie. https://kit.svelte.dev/docs/adapter-cloudflare). I'm sure there are other places as well?

I've also wondered  if we should move `workers-sdk` back to the `cloudflare/templates` repo for visibility?

**Comment by penalosa** [comment]
We no longer recommend users use these templates to get started with projects, as they're generally very out of date. For up to date project templates, you can refer to https://developers.cloudflare.com/workers/get-started/quickstarts/ & for tutorials you can refer to https://developers.cloudflare.com/workers/tutorials/
