### ISSUE TITLE
Remove deprecated `wrangler version` command

### ISSUE THREAD

**Issue by RamIdeas** [cloudflare/workers-sdk#5165]
https://github.com/cloudflare/workers-sdk/pull/5069 marked the `wrangler version` command as deprecated since `wrangler --version` is the recommended approach and having this command may cause confusions with the upcoming `wrangler versions ...` commands

**Comment by cometkim** [comment]
Can it add an option to print only the version? It has too much unnecessary format around, making it difficult to use it with some scripts.

**Comment by penalosa** [comment]
Closed by #7352
