### ISSUE TITLE
Invalid format for Authorization header [code: 6111]

### ISSUE THREAD

**Issue by a224327780** [cloudflare/workers-sdk#5175]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.30.1

### What operating system and version are you using?

Linux

### Describe the Bug

![image](https://github.com/cloudflare/workers-sdk/assets/78008038/7e51e533-e51a-4726-90df-8ae55d25488a)

```
root@kr1:~# wrangler whoami
 ⛅️ wrangler 3.30.1 (update available 3.31.0)
-------------------------------------------------------
Getting User settings...

✘ [ERROR] A request to the Cloudflare API (/user) failed.

  Invalid request headers [code: 6003]
  - Invalid format for Authorization header [code: 6111]

  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

**Comment by admah** [comment]
@a224327780 can you try to logout (wrangler logout) and then login again to get a new code? It looks like there may have been an issue during the auth flow. I've tested with a couple users myself and can't seem to reproduce this.

**Comment by lrapoport-cf** [comment]
hi @a224327780 we haven't heard from you in a while, so we’re going to close this issue for now. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and any additional details, followup, or context (particularly in response to @admah 's question above) and we will revisit and investigate further. thanks!
