### ISSUE TITLE
🚀 Feature Request: Wrangler secret for pages

### ISSUE THREAD

**Issue by skyf0l** [cloudflare/workers-sdk#5180]
I want to add secrets to my Cloudflare Page through wrangler (in CI), but I figured out that it's only possible to set secrets for workers (https://developers.cloudflare.com/workers/wrangler/commands/#secret) and not for pages. Any workaround ?

**Comment by admah** [comment]
@skyf0l thanks for filing this feature request. There are no workarounds at the moment. Pages secrets need to be created via the Cloudflare dashboard.

**Comment by iamvishnusankar** [comment]
Setting secrets through dashboard is not an ideal solution for large projects. I have a project which shares secrets between multiple workers and now in need of using the same secrets for pages.

This should be on higher priority, IMHO!
