### ISSUE TITLE
[OUTDATED] Wrangler JSON schema

### ISSUE THREAD

**Issue by angel-luis** [cloudflare/workers-sdk#5181]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.31

### What operating system and version are you using?

Mac Sonoma 14.2.1

### Observed behavior
Using the VSCode extension **Even Better TOML** I can't use the *limits* key (as documented [here](https://developers.cloudflare.com/workers/wrangler/configuration/#limits)).

### Reason
The `wrangler.schema.json` is outdated. This is what is fetching: https://github.com/cloudflare/workers-sdk/files/12887590/wrangler.schema.json

The key `limits` doesn't exist.

**Comment by penalosa** [comment]
Closing as duplicate of https://github.com/cloudflare/workers-sdk/issues/5055, which will make sure we consistently update the JSON schema.
