### ISSUE TITLE
🐛 BUG: wrangler pages dev shouldn't auth

### ISSUE THREAD

**Issue by penalosa** [cloudflare/workers-sdk#5198]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

0.0.0

### What version of Node are you using?

0.0.0

### What operating system and version are you using?

0.0

### Observed behavior
Please describe.🐛 BUG: wrangler pages dev shouldn't auth

### Expected behavior
Please describe.

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suit on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.
### Please provide a link to a minimal reproduction

🐛 BUG: wrangler pages dev shouldn't auth

### Please provide any relevant error logs

🐛 BUG: wrangler pages dev shouldn't auth

**Comment by CarmenPopoviciu** [comment]
@penalosa is this still relevant, and if so, can you pls add some details to the ticket so I can bettr asses if this is something we need to consider addressing as part of the `pages dev` improvements [milestone](https://github.com/cloudflare/workers-sdk/milestone/10)
