### ISSUE TITLE
Deprecate `wrangler pages dev -- <PROXY_COMMAND>`

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-sdk#5211]
And the supporting `--script-path` arg.

It's unfortunately not fit for purpose and causes users more harm than benefit.

**Comment by penalosa** [comment]
@nevikashah @admah could you weigh in here from a product perspective?

**Comment by petebacondarwin** [comment]
The majority of the work here would actually be going through the docs and ensuring that all our guides avoid this usage.
It might also be worth checking how many Pages projects are currently relying upon this in their build command configured in the Pages dashbaord. cc @nevikashah

**Comment by GregBrimble** [comment]
Given its use, I was thinking we'd want to consider deprecating in v3, letting it sit through v4 and then remove in v5.

**Comment by petebacondarwin** [comment]
Yes. Exactly!

**Comment by GregBrimble** [comment]
Right, so I'm advocating on deprecating before we cut v4 which is why I added it to this milestone :)

**Comment by petebacondarwin** [comment]
OK. That wasn't clear from the issue. 😄 
I'll add it to our next week's sprint.

**Comment by malobre** [comment]
User POV:

I rely on this feature when working on project that use vitejs + pages functions, e.g:
`wrangler pages dev --proxy=5173 -- vite --port=5173 --strictPort`.

If this is deprecated what would the alternative be? A miniflare vite plugin?

**Comment by petebacondarwin** [comment]
If I understand it correctly, the alternative is simply to run the vite server and wranger pages dev server side by side in separate terminals. For example, in one terminal:

```bash
vite --port=5173 --strictPort
```

And then in another terminal
``` bash
wrangler pages dev --proxy=5173
```

**Comment by petebacondarwin** [comment]
Although we would need to make a small fix in wrangler to ensure that we make use of the `--proxy` argument even if there is no proxy command.

**Comment by petebacondarwin** [comment]
But actually, I think @GregBrimble's preferred approach would be to configure vite to watch and build to a directory that we then pass to Wrangler:

```
vite build --watch
```
and
```
wrangler pages dev dist
```

**Comment by GregBrimble** [comment]
Yes, that's correct. Building to a directory is currently the only way to accurately emulate production's static asset serving behavior.

**Comment by malobre** [comment]
@petebacondarwin thanks for the quick response, this mostly cover my use case, except for HMR (which I can live without) and live reload (with `wrangler pages dev --live-reload dist`) which does not work at all (maybe related to #4607 ?)

**Comment by kurdin** [comment]
> User POV:
> 
> I rely on this feature when working on project that use vitejs + pages functions, e.g: `wrangler pages dev --proxy=5173 -- vite --port=5173 --strictPort`.
> 
> If this is deprecated what would the alternative be? A miniflare vite plugin?
`wrangler pages dev --proxy=5173 -- vite --port=5173 --strictPort`
or just 
`wrangler pages dev -- npm run vite`

This was very convenient to start `vite` along with `wrangler pages dev` in development. It's strange that this proxy feature is set to be removed. 🤷

Currently, I encounter this error when I start Wrangler with Vite as a proxy:

`[ERROR] Specify either a directory OR a proxy command, not both.`

Yes, I have `pages_build_output_dir = "pages"` set for deployment, and if I remove it from the config, I see a deployment error telling me I have to add `pages_build_output_dir` to the config or the whole config will be ignored 🤷.

```
We detected a configuration file at
wrangler.toml but it is missing the
"pages_build_output_dir" field, required by Pages.
If you would like to use this configuration file to deploy your project, please use
"pages_build_output_dir" to specify the directory of static files to upload.
Ignoring configuration file for now, and proceeding with project deploy.
```

Can anyone please help with how to deal with this? Sure, I can run vite and wrangler pages dev alongside each other, but it's not as convenient as using a proxy.
 
Is there any way to add `pages_build_output_dir` via `wrangler deploy` cli command and keep/use other all settings from `wrangler.toml` ?

**Comment by anri-asaturov** [comment]
Just wanted to share a configuration that's working for me so far and keeps vite's HMR.

Add this to vite.config.js

```
 server: {
    port: 3000,
    proxy: {
      '/api': {
        target: 'http://127.0.0.1:3001',
        changeOrigin: true,
        rewrite: path => path.replace(/^\/api/, '')
      }
    }
```

Now run your vite app in dev mode as usual (`vite` command), it will run on port 3000 and proxy all `localhost:3000/api/*` calls to `localhost:3001/*` avoiding CORS issues.

Then run

```
wrangler pages dev --port 3001 --live-reload
```
it will serve functions along with static assets which we will ignore.

**Comment by anri-asaturov** [comment]
> > ```
> > wrangler pages dev --port 3001 --live-reload
> > ```
> 
> Having /api as path to proxy adds an additional flag to keep eyes on, which is easy to forget about. All calls to api must be made now with double /api/api paths, in my case. Do you think vite will forward all request params to proxy calls?
> 
> Without further debugging after removing api replace, wrangler throws 500's on every api call. I'll try if this is a reliable solution, however having it served by vite would make it possible to have dev mode on.

Here I've made a copy of my current template for you. It's opinionated, but you will see the basic idea and it works. I've spent quite a lot of time experimenting and researching and this solution makes me happy.

https://github.com/anri-asaturov/cloudflare-pages-spa-template

**Comment by vmuthal** [comment]
My views and solution for this issue:
https://github.com/cloudflare/workers-sdk/issues/5315#issuecomment-2558021347
