### ISSUE TITLE
🐛 BUG: `wrangler login` continues to fail

### ISSUE THREAD

**Issue by jsparkdev** [cloudflare/workers-sdk#5260]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.34.2 [Wrangler]

### What version of Node are you using?

21.7.1

### What operating system and version are you using?

Mac Sonoma 14.4

### Observed behavior

I am using `pnpm` as a package manager, and until recently I was able to log in successfully using the command below.

```bash
pnpm wrangler login
```

However, since some time ago, logging in using this command continues to fail with the message below.

```
Successfully logged in.
Expired! Auth code or refresh token needs to be renewed.
```

I didn't know how to solve this problem, so I asked a question on [Discord](https://discord.com/channels/595317990191398933/1217827337790558250), but there was no answer.

### Expected behavior

I hope I can log in successfully as before.

### Steps to reproduce

This problem occurred with Workers templates created only through `pnpm create cloudflare@latest` without any additional configuration.

1. Create a Workers template using the `pnpm create cloudflare@latest` command.
2. Move to the project folder and run the `pnpm wrangler login` command to log in.
3. A new browser window will open containing the title `Allow Wrangler to make changes to your Cloudflare account?
` and the `Allow` and `Deny` buttons.
4. When I click the `Allow` button for authentication, authentication fails with the following error.

## Browser

`ERR_CONNECTION_REFUSED`

## Console

```
Attempting to login via OAuth...
Opening a link in your default browser: https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=...
Successfully logged in.
Expired! Auth code or refresh token needs to be renewed.
/Users/jspark/code/jolly-base-86e1/node_modules/.pnpm/wrangler@3.34.2_@cloudflare+workers-types@4.20240314.0/node_modules/wrangler/wrangler-dist/cli.js:29573
            throw a;
            ^

ErrorInvalidGrant
    at toErrorClass (/Users/jspark/code/jolly-base-86e1/node_modules/.pnpm/wrangler@3.34.2_@cloudflare+workers-types@4.20240314.0/node_modules/wrangler/wrangler-dist/cli.js:120484:10)
    at exchangeAuthCodeForAccessToken (/Users/jspark/code/jolly-base-86e1/node_modules/.pnpm/wrangler@3.34.2_@cloudflare+workers-types@4.20240314.0/node_modules/wrangler/wrangler-dist/cli.js:120615:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.<anonymous> (/Users/jspark/code/jolly-base-86e1/node_modules/.pnpm/wrangler@3.34.2_@cloudflare+workers-types@4.20240314.0/node_modules/wrangler/wrangler-dist/cli.js:120771:30)

Node.js v21.7.1
```

**Comment by jsparkdev** [comment]
If this is not a bug in wrangler, please let me know how I can fix this!

**Comment by ocia-mandi** [comment]
I am also having this issue.

**Comment by Jazee6** [comment]
I am also having this issue.

**Comment by x8BitRain** [comment]
Getting the exact same problem, downgrading doesn't seem to help. I can work around this with a custom API key `export CLOUDFLARE_API_TOKEN=<token> && wrangler`

**Comment by macdar** [comment]
same issue

**Comment by renzholy** [comment]
same issue

**Comment by inspectorrex** [comment]
same here

**Comment by jsparkdev** [comment]
I don't know the exact reason, but it was resolved today...

**Comment by Andriy-Kulak** [comment]
same issue :-(

**Comment by Andriy-Kulak** [comment]
this can be fixed by updating the `wrangler` npm library to the latest. there is a chrome bug apparently that is fixed with update.

**Comment by jsparkdev** [comment]
This problem occurred not only in Chrome, but also in Safari and Firefox.

After updating to wrangler 3.36.0, this issue appears to have been resolved, so it appears that this issue has been resolved in that version.

**Comment by PacifiK2460** [comment]
Changing version to 3.36.0 doesn't work:

```
G:\...> npx wrangler login --browser false    
 ⛅️ wrangler 2.21.1 (update available 3.53.1)
-------------------------------------------------------
Attempting to login via OAuth...
Visit this link to authenticate: https://dash.cloudflare.com/oauth2/auth?...
G:\...\node_modules\wrangler\wrangler-dist\cli.js:30601
            throw a;
            ^

Error: ENOENT: no such file or directory, open 'C:\Users\me\AppData\Roaming\xdg.config\.wrangler\config\default.toml'
    at writeFileSync (node:fs:2352:20)
    at writeAuthConfigFile (G:\...\node_modules\wrangler\wrangler-dist\cli.js:131445:37)
    at Server.<anonymous> (G:\...\node_modules\wrangler\wrangler-dist\cli.js:131536:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\me\\AppData\\Roaming\\xdg.config\\.wrangler\\config\\default.toml'
}

Node.js v21.3.0
```
Making the file, and providing a sample configuration doesn't help

**Comment by freemedom** [comment]
i run `npx wrangler dev` , then it always can't logged in after i click button in chrome.
then i run `npx wrangler login`, it works.

**Comment by Somye55** [comment]
@

> Changing version to 3.36.0 doesn't work:
> 
> ```
> G:\...> npx wrangler login --browser false    
>  ⛅️ wrangler 2.21.1 (update available 3.53.1)
> -------------------------------------------------------
> Attempting to login via OAuth...
> Visit this link to authenticate: https://dash.cloudflare.com/oauth2/auth?...
> G:\...\node_modules\wrangler\wrangler-dist\cli.js:30601
>             throw a;
>             ^
> 
> Error: ENOENT: no such file or directory, open 'C:\Users\me\AppData\Roaming\xdg.config\.wrangler\config\default.toml'
>     at writeFileSync (node:fs:2352:20)
>     at writeAuthConfigFile (G:\...\node_modules\wrangler\wrangler-dist\cli.js:131445:37)
>     at Server.<anonymous> (G:\...\node_modules\wrangler\wrangler-dist\cli.js:131536:13)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   errno: -4058,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'C:\\Users\\me\\AppData\\Roaming\\xdg.config\\.wrangler\\config\\default.toml'
> }
> 
> Node.js v21.3.0
> ```
> 
> Making the file, and providing a sample configuration doesn't help

Hey, did you find any solution for this?

**Comment by Zhumatic** [comment]
exact same problem : ENOENT: no such file or directory, open '/Users/fumiaki/Library/Preferences/.wrangler/config/default.toml', browser: chrome, node version: 20

**Comment by lucasmengel** [comment]
same issue
