### ISSUE TITLE
Getting mime error [''] 

### ISSUE THREAD

**Issue by DH-555** [cloudflare/workers-sdk#5278]
When deploying a flutter app, I get mime error for the main.dart.js file.

It happens with both the wrangler and manual deployment, in different browsers.

I tried disabling cache, redeploying... Nothing seems to work.

This looks like to happen with flutter web projects in such file.

**Comment by DH-555** [comment]
@petebacondarwin So magically it works now, from both the CLI and direct upload. 
I think a recent update fixed the bug or similar?
From my side i didn't have upgraded or modified anything...

Closing this as solved

**Comment by petebacondarwin** [comment]
Very strange. I haven't heard anything about this from the Pages team. But I see that this appears to have occurred occasionally in the past for various reasons. Please do reach out if it happens again.

**Comment by DH-555** [comment]
I got something similar again.

Example:
https://xdonde.dh-sw.net/virgendeaguassantas/

**Comment by DH-555** [comment]
@petebacondarwin

**Comment by WalshyDev** [comment]
Are you using Firefox and the Dashboard Drag & Drop? If so, there's a known bug there that causes this.

If you're using Wrangler then ideally we get logs with `WRANGLER_LOG=debug wrangler pages deploy ...`

**Comment by DH-555** [comment]
Yes, I am

**Comment by DH-555** [comment]
Okay, tried with chrome. Same is happening

**Comment by DH-555** [comment]
Going to try with wragler

**Comment by DH-555** [comment]
Tried with wrangler, also mime error. I'm getting the plain text HTML instead of the actual website

**Comment by WalshyDev** [comment]
have you got a repro you can share?

**Comment by DH-555** [comment]
Unfortunately not, but here you have a ZIP with it:

**Comment by DH-555** [comment]
[xdonde.zip](https://github.com/user-attachments/files/16841604/xdonde.zip)

**Comment by DH-555** [comment]
@WalshyDev 
Is that enough? Were you able to reproduce the issue?

**Comment by lrapoport-cf** [comment]
@DH-555 it doesn't appear that you attached anything. can you please provide a repro?

**Comment by DH-555** [comment]
Looks like this issue is specific to the deployed page.
I created a new page and it works fine.

I'm closing this consequently, but I don't understand why it happens only with that project/page deployment.
