### ISSUE TITLE
🐛 BUG: Pages deploy does not detect shared project

### ISSUE THREAD

**Issue by rmkerr** [cloudflare/workers-sdk#5280]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.35.2

### What version of Node are you using?

v20.10.0

### What operating system and version are you using?

Sonoma 14.3.1

### Observed behavior
I have a pages project configured on my account. I shared admin access to the entire site with my cofounder. When he tries to deploy using `wrangler pages deploy dist`, he does not see the prompt to select an existing project. Here's the output he sees:

```bash
pnpm wrangler pages deploy dist
:heavy_check_mark: Select an account › Matt@talc.ai's Account
:heavy_check_mark: Enter the name of your new project: … 
```

I've confirmed he has access to the site and the pages project in dash.

### Expected behavior
He should be getting the project selection prompt here, not the create a project prompt.

**Comment by rmkerr** [comment]
@GregBrimble is this something you can help diagnose? I saw you created the initial version of this prompt in #891.

**Comment by penalosa** [comment]
@rmkerr it looks like your cofounder is trying to deploy to the "Matt@talc.ai's Account" account. Is that the correct shared account containing this Pages project?

**Comment by penalosa** [comment]
I'm going to close this for now, but feel free to open a new issue if you're still running into problems
