### ISSUE TITLE
🐛 BUG: `d1 execute` only runs on local database

### ISSUE THREAD

**Issue by cryptiddddd** [cloudflare/workers-sdk#5287]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

wrangler 3.34.2

### What version of Node are you using?

20.11.0

### What operating system and version are you using?

Windows 10

### Describe the Bug

i do not believe i saw this error discussed in the current open issues, i apologize if this is already being discussed. i found a solution, and after checking the open issues, decided it was best i point it out.

### Observed behavior

just this evening, i attempted to update a d1 cloud database with the command `wrangler d1 execute <database_name> --file update.sql`, and it returned an error message. shortened story: the issue was that despite not using the `--local` flag, it was only acting on the local development database. see the second galaxy-emoji bullet point:

```
 ⛅️ wrangler 3.34.2
-------------------
🌀 Mapping SQL input into an array of statements
🌀 Executing on local database <database_name> (<preview_name>) from .wrangler\state\v3\d1:
🌀 To execute on your remote database, add a --remote flag to your wrangler command.
```

this is different from the remote database, i am certain upon reviewing the d1 documentation.

### Expected behavior

this morning, i updated the very same d1 cloud database using very same command. this worked just fine, no issues. i noticed that a new wrangler version was available, so i updated.

#### Solution

i downgraded to wrangler v3.32.0 -- i am unsure if this is the very same i was using this morning -- and it worked just fine. it did _not_ work at v3.34.0 or v3.33.0, i should note.

### Steps to reproduce
1. `wrangler.toml` configured with a d1 binding:
  ```toml
  [[d1_databases]]
  binding = "db"
  database_name = "<name>"
  database_id = "<id>"
  preview_database_id = "<preview_id>"
  ```
2. an initialized database with or without data in it.
3. `update.sql` containing `SELECT`, `INSERT`, `UPDATE`, or `DELETE` statements.
4. run the command `npx wrangler d1 execute --file ./update.sql`. check the d1 cloud database on dash.cloudflare.com.
5. how i discovered it: run the command again, and if you are inserting a duplicate value for a primary key property on a table, a `UNIQUE CONSTRAINT` error should raise.
  - alternatively, expected data may not be found.
  - or redundancies may be found.
  - or unexpected data may be found after an intended deletion statement. the point is, it doesn't interact with the cloud database as expected.

---

i hope that i was thorough in reporting the issue. i'm fairly confident in my own assessment, but it may not be an issue everyone faces.

has anyone else faced this issue?

**Comment by RamIdeas** [comment]
Hi @cryptiddddd. To execute against the remote db, you need to use the `--remote` flag on your command.

**Comment by petebacondarwin** [comment]
The default for d1 commands switched from remote to local in 3.33.0 - see https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/CHANGELOG.md#3330
Since D1 was in beta, this was not deemed a breaking change so did not trigger a major release of Wrangler.

Please use `--remote` as described by @RamIdeas above to get the desired behaviour.

**Comment by gamliela** [comment]
@petebacondarwin good to know - please consider updating the documentation:

> The preceding command would execute queries the local only version of your D1 database. Without the `--local` flag, the commands are executed against the remote version of your D1 database running on Cloudflare’s network.

https://developers.cloudflare.com/d1/build-with-d1/local-development/
