### ISSUE TITLE
🐛 BUG: CLI command failed to generate cloudflare/remix site "failure to extract template"

### ISSUE THREAD

**Issue by pkarl** [cloudflare/workers-sdk#5343]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

3.36.0 [wrangler], 2.8.1 [create-remix], 2.15.1 [create-cloudflare]

### What version of Node are you using?

v18.18.2

### What operating system and version are you using?

Mac Sonoma 14.4 (23E214)

### Observed behavior
1. Failure to generate remix site via CLI using [documented](https://developers.cloudflare.com/pages/framework-guides/deploy-a-remix-site/) create-cloudflare command `npm create cloudflare@latest my-remix-app -- --framework=remix`
2. Failure to generate remix site via CLI using create-cloudflare command + wizard

### Expected behavior
Expected cloudflare-pages-compatible remix site to be generated successfully

### Steps to reproduce

1. `npm create cloudflare@latest my-remix-app -- --framework=remix`

### Please provide any relevant error logs

wrangler debug log for this event:

[2024-03-21T13_54_39_998Z-debug-0.log](https://github.com/cloudflare/workers-sdk/files/14696180/2024-03-21T13_54_39_998Z-debug-0.log)

CLI output:
```bash
➜  npm create cloudflare@latest my-remix-app -- --framework=remix

using create-cloudflare version 2.15.1

╭ Create an application with Cloudflare Step 1 of 3
│
├ In which directory do you want to create your application?
│ dir ./my-remix-app
│
├ What type of application do you want to create?
│ type Website or web app
│
├ Which development framework do you want to use?
│ framework Remix
│
├ Continue with Remix via `npx create-remix@2.8.1 my-remix-app --template https://github.com/remix-run/remix/tree/main/templates/cloudflare`
│


 remix   v2.8.1 💿 Let's build a better website...
      ◼  Directory: Using my-remix-app as project directory

      ◼  Template: Using https://github.com/remix-run/remix/tree/main/templates/cloudflare...
 ██████  Template copying...

      ▲  Oh no! There was a problem extracting the file from the provided template.  Template URL: `https://codeload.github.com/remix-run/remix/tar.gz/main`  Destination directory: `/private/var/folders/_8/x8g2st9s04d8ccxn3csjwlhc0000gn/T/create-remix--g5jk73r1`
╰  ERROR  Error
npm ERR! code 1
npm ERR! path /Users/pk2/Sandbox
npm ERR! command failed
npm ERR! command sh -c create-cloudflare my-remix-app --framework=remix

npm ERR! A complete log of this run can be found in: /Users/pk2/.npm/_logs/2024-03-21T13_49_37_641Z-debug-0.log
```

**Comment by admah** [comment]
@pkarl can you retry with create-cloudflare `2.15.2`? I just ran the command you did and was able to get a new Remix site scaffolded without issue.

**Comment by pkarl** [comment]
@admah success!
