### ISSUE TITLE
🐛 BUG: Error when deploying Queue consumer & producer worker 

### ISSUE THREAD

**Issue by dfodeker** [cloudflare/workers-sdk#5347]
### Which Cloudflare product(s) does this pertain to?

Queues, Workers Runtime

### What version(s) of the tool(s) are you using?

3.26.0

### What operating system and version are you using?

Windows 11

### Observed behavior
running `wrangler deploy`  on a queue consumer and producer worker does not successfully deploy the worker even when trying with the template provided from the CLI.
it initially displays 
```
Total Upload: 0.85 KiB / gzip: 0.47 KiB
Uploaded flat-glade-c7a4 (1.60 sec)
```
and then displays
```
 X [ERROR] A request to the Cloudflare API  with minimal description of the issue causing failure workers.api.error.consumer_exists [code: 11004]
```

### Expected behavior
Deploy the template without issue

### Steps to reproduce
Please provide the following:
- init worker through cli
- select ` Queue consumer & producer Worker` for the question `What type of application do you want to create?`
- use TS
- run `wrangler deploy` in the project folder

A git repo we can clone and run a test suit on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.
- https://github.com/dfodeker/flat-glade

### Please provide a link to a minimal reproduction

https://github.com/dfodeker/flat-glade

### Please provide any relevant error logs

Your worker has access to the following bindings:
- Queues:
  - MY_QUEUE: my-queue
Total Upload: 0.85 KiB / gzip: 0.47 KiB
Uploaded flat-glade-c7a4 (1.60 sec)

X [ERROR] A request to the Cloudflare API (/accounts/{account-id}/workers/queues/my-queue/consumers/flat-glade-c7a4) failed.

  workers.api.error.consumer_exists [code: 11004]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

**Comment by KeKs0r** [comment]
Running into the same issue, how was this resolved?

**Comment by irvinebroque** [comment]
Can you try latest version of Wrangler?
