### ISSUE TITLE
🐛 BUG: unclear docs & experience with `wrangler init` vs 'npm create cloudflare'

### ISSUE THREAD

**Issue by techieshark** [cloudflare/workers-sdk#5352]
### Which Cloudflare product(s) does this pertain to?

C3, Wrangler core

### What version(s) of the tool(s) are you using?

3.36.0 [wrangler], 2.15.1 [c3]

### What version of Node are you using?

20.11.1

### What operating system and version are you using?

Mac Sonoma 14.3.1

### Observed behavior

1. The wrangler [readme](https://github.com/cloudflare/workers-sdk/tree/main/packages/wrangler#create-a-project) (which is also pushed to [npm](https://www.npmjs.com/package/wrangler)) says to run `npx wrangler init my-worker --no-delegate-c3`, but then

![image](https://github.com/cloudflare/workers-sdk/assets/1072292/071e2e5f-09e1-4acb-a557-8774877769a4)

2. when running `wrangler init  --no-delegate-c3` shows a "WARNING" that the `init` subcommand is out dated ("no longer supported) and to use something else, but the something else (create-cloudflare version 2.15.1) seems to install *older* dependencies than `wrangler init` 

![image](https://github.com/cloudflare/workers-sdk/assets/1072292/626bc643-c2f7-4109-a75d-ea39c59b5dd5)

So this is a quite confusing experience and it's not clear what the best way to create a new project actually is.

### Expected behavior

1) Either the README or the output of the `wrangler init` should be updated to be in sync, and 2) ideally if `npm create cloudflare` is the way to go, its output would be on par with wrangler init.

### Steps to reproduce

1. Run `npx wrangler init my-worker-from-wrangler --no-delegate-c3`
2. Observe the warning, then compare it to the wrangler npm page docs.
3. Run `npm create cloudflare@latest -- my-worker-from-c3`
4. Run `diff my-worker-from-wrangler/package.json my-worker-from-c3/package.json` and observe that the c3 typescript package is older (and also doesn't have vitetest, so generally feels not as up to date as from 'wrangler init')

**Comment by jculvey** [comment]
I think the easiest resolution here given the bug description would be to update the `wrangler init` deprecation command to suggest users run `npm create cloudflare@latest` instead of `npm create cloudflare@2.5.0`.

**Comment by penalosa** [comment]
Closing in favour of https://github.com/cloudflare/workers-sdk/issues/5701
