### ISSUE TITLE
🐛 BUG: wrangler@2.21.1 is smaller than 3.36.0

### ISSUE THREAD

**Issue by kpcyrd** [cloudflare/workers-sdk#5357]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.36.0

### What operating system and version are you using?

Arch Linux

### Describe the Bug

`wrangler@2.21.1` was released but the previous latest version of wrangler was `3.36.0`, was this tagged by accident? (e.g. a version of a different component but with the `wrangler@` prefix)

Thanks! :)

**Comment by harryzcy** [comment]
They are for different major versions

**Comment by kpcyrd** [comment]
I see, thanks for clarifying :)
