### ISSUE TITLE
🐛 BUG: Response.redirect() marks headers as immutable

### ISSUE THREAD

**Issue by techieshark** [cloudflare/workers-sdk#5378]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

3.0.0 [wrangler]

### What version of Node are you using?

20.11.1

### What operating system and version are you using?

Mac Sonoma 14.3.1

### Observed behavior

I was hoping I could add some header on a redirect response, but it seems the headers are marked as immutable.

### Expected behavior

Ideally I could write something like this:

```
	const response = Response.redirect(url);
	response.headers.append('via', 'my-worker');
	
	return response;
```

or even better (shorter):

```
      return Response.redirect(url, { via: 'my-worker' });
```

### Steps to reproduce

Not sure if anything beyond what's above is needed to reproduce this, but we can also just read the code:

```
> Unfortunately ... `redirect()` set[s] the internal header guard to "immutable".
```

https://github.com/cloudflare/workers-sdk/blob/3be826f8411ef8d517d572f25a6be38cb8c12cc1/packages/miniflare/src/http/response.ts#L23C3-L24C20

I'm _assuming_ that the "Unfortunately" in the comment indicates an actual "fault" in the code which could be improved, and that this isn't just how the system must be designed. 

Even if a Response from a fetch needed to be somewhat immutable, one would think a freshly constructed Response could have whatever headers one needs -- especially if it's possible to just set those headers via a workaround like this below:

```
const response = Response.redirect(url);
const response2 = new Response(response.body, response);
return response2;
```

**Comment by penalosa** [comment]
While unfortunate, this matches the specified behaviour for the web platform (https://fetch.spec.whatwg.org/#dom-response-redirect), and so is not something we're likely to change. As you note in your issue, it's fairly easy to work around by constructing a new `Response` object.
