### ISSUE TITLE
🐛 BUG: workers.api.error.unknown [code: 10013]

### ISSUE THREAD

**Issue by wighawag** [cloudflare/workers-sdk#5402]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

wrangler 3.38.0

### What version of Node are you using?

v18.19.1

### What operating system and version are you using?

Linux

### Observed behavior
```
wrangler tail fuzd-worker-production
```

```
✘ [ERROR] A request to the Cloudflare API (/accounts/def03fa18e0fd4ec8de6d4558528abca/workers/scripts/fuzd-worker-production/tails) failed.

  workers.api.error.unknown [code: 10013]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

```

### Expected behavior
see the logs

### Steps to reproduce

```
wrangler tail fuzd-worker-production
```

### Please provide any relevant error logs

```
✘ [ERROR] A request to the Cloudflare API (/accounts/def03fa18e0fd4ec8de6d4558528abca/workers/scripts/fuzd-worker-production/tails) failed.

  workers.api.error.unknown [code: 10013]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

```

**Comment by mrbm** [comment]
seeing this issue as well. Saw it 5 min ago with wrangler 3.34.2, then updated to latest version 3.38.0 and still seeing it. Can't perform tail command, identical error

**Comment by penalosa** [comment]
This is related to an ongoing Cloudflare incident—see https://www.cloudflarestatus.com/incidents/b31dxdz60366 for more details and to keep track of progress. I'll leave this issue open until the incident is resolved.

**Comment by penalosa** [comment]
`wrangler tail` functionality should now be restored. Feel free to open a new issue if the problem persists
