### ISSUE TITLE
🚀 Feature Request: `--output` option for `wrangler versions list/view`

### ISSUE THREAD

**Issue by sayantank** [cloudflare/workers-sdk#5408]
### Describe the solution

Currently, there's no way to get just the `version_id` as output from the `wrangler version list/view` commands. Which means if I were to extract the `version_id` for my CI pipelines, I would need to parse the whole output which comes as, 
```
 ⛅️ wrangler 3.38.0
-------------------
Version ID:  0154fc52-5bd8-4538-af68-a4ac54443b05
Created:     2024-03-27T07:47:52.692Z
Author:      sayantan@ironforge.cloud
Source:      Unknown (version_upload)
Tag:         deploy/1
Message:     -
```

Maybe we could have a `--output json` sorta flag which I can then easily parse for the `version_id`, `tag`, etc.

**Comment by penalosa** [comment]
For consistency, this should probably be a `--json` flag, but this sounds like a good thing for us to add! cc @RamIdeas
