### ISSUE TITLE
Add tests for wrangler login

### ISSUE THREAD

**Issue by lrapoport-cf** [cloudflare/workers-sdk#5431]
Add tests for the following:

- https://github.com/cloudflare/workers-sdk/pull/5324
- https://github.com/cloudflare/workers-sdk/pull/5337

**Comment by penalosa** [comment]
Because of the complexity of writing these tests (and the difficulty of writing them in a manner that would actually give us much confidence that the user flow into the browser and back would work), we've instead added a manual testing step for `wrangler login` to our process.
