### ISSUE TITLE
🐛 BUG: workerd runtime can crash in some cases where WebSockets and promises are involved

### ISSUE THREAD

**Issue by nvie** [cloudflare/workers-sdk#5439]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Workers Vitest Integration

### What version(s) of the tool(s) are you using?

@cloudflare/vitest-pool-workers@0.1.7, miniflare@3.20240320.0, vitest@1.3.0, wrangler@3.39.0

### What version of Node are you using?

v18.19.1

### What operating system and version are you using?

Mac Sonoma 14.4.1

### Observed behavior
Related to Durable Objects that use WebSockets, sometimes using promises in tests can crash the workerd runtime (and thus the Vite test runner). Here is a screencast of this behavior in a minimal replication of the bug:

[![](https://brief.cleanshot.cloud/media/1679/oCOxCcl2bpQaJ9GwMRrceZzrrKQl4p0YanNfWLIe.mp4?width=1200&height=630&scaling=fit&play=1)](https://share.cleanshot.com/d914hhK8RFYpDP5N9Ldg)

I've aleady talked about this [on Discord](https://discord.com/channels/595317990191398933/1218150105777963101/1223204435757498420) with @mrbbot, and thus far the most likely theory is that `abortAllDurableObjects()` isn't cleaning up Durable Objects properly (i.e. it doesn't stop all in-progress WebSocket messages).

### Expected behavior
The workerd runtime (and Vitest) never crashes.

### Steps to reproduce
Check out this repo locally:
- https://github.com/nvie/cloudflare-repros
- Run `npm run test`, notice it works
- Duplicate [this line](https://github.com/nvie/cloudflare-repros/blob/main/durable-objects/test/illustrate-bug.test.ts#L28)
- Run `npm run test`, **it now crashes** 😱

### Relevant links
- Discord discussion: https://discord.com/channels/595317990191398933/1218150105777963101/1223204435757498420

### Please provide a link to a minimal reproduction

https://github.com/nvie/cloudflare-repros

### Please provide any relevant error logs

```
$ npm run test

> test
> vitest --config vitest.workers.config.ts --reporter basic


 DEV  v1.3.0 /Users/nvie/Projects/cloudflare-repros

[vpw:inf] Starting single runtime for durable-objects/vitest.config.ts...
*** Fatal uncaught kj::Exception: kj/async.c++:2164: failed: expected !firing; Promise callback destroyed itself.
stack: 103252003 10325b1e3 103251423 1032512e3 10140c7bf 10140ca97 101477667 101477547 10146f097 101452893 1014529f3 10147bf83 10144814f 101440f9b 10325b26f 10325ae93 10325dccf 1032550db 100ecf1df 100ed3883 100ed376b 100ed3753 1032b61a7 1032b64ef 1032b4c4f 1032b4a1f 100ec41af 18105a0df

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: fetch failed
 ❯ fetch node_modules/undici/index.js:112:15
 ❯ process.processTicksAndRejections node:internal/process/task_queues:95:5
 ❯ MessagePort.<anonymous> [worker eval]:28:22

Caused by: Error: connect ECONNREFUSED 127.0.0.1:50356
 ❯ TCPConnectWrap.afterConnect [as oncomplete] node:net:1555:16

/Users/nvie/Projects/cloudflare-repros/node_modules/wrangler/wrangler-dist/cli.js:29573
            throw a;
            ^

TypeError: fetch failed
    at fetch (/Users/nvie/Projects/cloudflare-repros/node_modules/undici/index.js:112:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MessagePort.<anonymous> ([worker eval]:28:22) {
  stacks: [
    {
      method: 'fetch',
      file: '/Users/nvie/Projects/cloudflare-repros/node_modules/undici/index.js',
      line: 112,
      column: 15
    },
    {
      method: 'process.processTicksAndRejections',
      file: '/Users/nvie/Projects/cloudflare-repros/node:internal/process/task_queues',
      line: 95,
      column: 5
    },
    {
      method: 'MessagePort.<anonymous>',
      file: '/Users/nvie/Projects/cloudflare-repros/[worker eval]',
      line: 28,
      column: 22
    }
  ],
  [cause]: Error: connect ECONNREFUSED 127.0.0.1:50356
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    name: 'Caused by: Error',
    stacks: [
      {
        method: 'TCPConnectWrap.afterConnect [as oncomplete]',
        file: '/Users/nvie/Projects/cloudflare-repros/node:net',
        line: 1555,
        column: 16
      }
    ]
  }
}

Node.js v18.19.1
```

**Comment by nvie** [comment]
Looks like this is no longer a bug on the latest versions:

- `@cloudflare/vitest-pool-workers` >= 0.1.18
- `miniflare` >= 3.20240405.0
- `wrangler` >= 3.49.0

Thanks for fixing this! 🙏

**Comment by samuelcolvin** [comment]
Anyone else having similar issues on github actions, you need

```ts
    worker = await unstable_dev('src/index.ts', {
      ip: '127.0.0.1',
      experimental: { disableExperimentalWarning: true },
    })
```

Since whatever `unstable_dev` is using internally doesn't like ipv6.
