### ISSUE TITLE
🐛 BUG: Can't set compatibility date in the future: 2024-03-31

### ISSUE THREAD

**Issue by PastaGringo** [cloudflare/workers-sdk#5453]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

3.41.0

### What version of Node are you using?

v18.19.1

### What operating system and version are you using?

Ubuntu 22.04.3 LTS

### Observed behavior

I'm pushing a deployment with `wrangler deploy` based on a wrangler.toml file with my current date (French time GMT+1).
Passed midnight we are now the 2024-03-31 and the wrangler deploy failed with the error  `Can't set compatibility date in the future: 2024-03-31` Everything was functionning before passing midnight.
I set into my wrangler.toml file the current day date before each wrangler deployment.

### Expected behavior
Successful deployment 

### Steps to reproduce
compatibility_date = "2024-03-31"

I suppose the Cloudflare servers are working on a different timezone where I'm currently in the future for them.

### Please provide any relevant error logs

```
 ⛅️ wrangler 3.41.0
-------------------
Your worker has access to the following bindings:
- KV Namespaces:
  - XXX: XXX
Total Upload: 78.23 KiB / gzip: 21.57 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/XXX/workers/scripts/XXX) failed.

  Can't set compatibility date in the future: 2024-03-31
   [code: 10021]
```

**Comment by penalosa** [comment]
This is expected behaviour: compatibility dates are based on the UTC date rather than the date in your local timezone.
