### ISSUE TITLE
🐛 BUG: deployment failed

### ISSUE THREAD

**Issue by ErNader** [cloudflare/workers-sdk#5492]
### Which Cloudflare product(s) does this pertain to?

Other

### What version(s) of the tool(s) are you using?

8.15.0

### What version of Node are you using?

16.7

### What operating system and version are you using?

Windows 11, android 13

### Describe the Bug

![Screenshot_2024-04-03-15-23-46-182_ir ilmili telegraph](https://github.com/cloudflare/workers-sdk/assets/115494736/4ec662f4-6c60-4cdd-8564-67eeecdd93a9)
![Screenshot_2024-04-03-15-26-15-931_com sec android app sbrowser beta-edit](https://github.com/cloudflare/workers-sdk/assets/115494736/63ceb8c4-ddfc-4164-9ffd-eba2fb21a6ec)
Hi I try a lot of time with different name, aubdomain and....
I make different bots with different account and tokens
Can you help me with this erorr

**Comment by admah** [comment]
@ErNader it looks like the API route you're using might be incorrect. Can you check that it's what you want there?

**Comment by petebacondarwin** [comment]
Hi @ErNader - we haven't heard from you for a while and so there is nothing we can do here right now. I am going to close this for the time being. If you can provide us with a reproduction of the problem, please post here or create a new issue.
