### ISSUE TITLE
🐛 BUG: `d1 create` doesn't know about Australia

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#5505]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

.

### What version of Node are you using?

.

### What operating system and version are you using?

.

### Describe the Bug

```
      --location  A hint for the primary location of the new DB. Options:
                  weur: Western Europe
                  eeur: Eastern Europe
                  apac: Asia Pacific
                  wnam: Western North America
                  enam: Eastern North America
```

**Comment by aperture147** [comment]
This issue makes me remind of "Australia" is not real meme
