### ISSUE TITLE
🐛 BUG (Pages): R2 Jurisdiction in `wrangler.toml` produces failed deployments

### ISSUE THREAD

**Issue by hrueger** [cloudflare/workers-sdk#5513]
### Which Cloudflare product(s) does this pertain to?

Pages, R2

### What version(s) of the tool(s) are you using?

3.47.0 [Wrangler]

### What version of Node are you using?

20.12.1

### What operating system and version are you using?

macOS Sonoma 14.4.1 

### Describe the Bug

Hi @petebacondarwin,
following up to #5377, I tested it and now the bindings, compatibility flags and the compatibility date is set correctly 🎉 However, one little thing is missing:

### Observed behavior
When adding a R2 binding to a Pages `wrangler.toml` specifying an R2 bucket with a jurisdiction and deploying that using `npx wrangler pages deploy`, I get `This deployment failed` in the dashboard:
![grafik](https://github.com/cloudflare/workers-sdk/assets/18656830/1a0a7643-22ad-4135-818f-b71ef99b192e)

When using a bucket without jurisdiction, the deployment works. Nowhere in the docs can I find that buckets with Jurisdicion cannot be used from Pages.

### Expected behavior
It works in Pages like in workers ;-)

### Steps to reproduce
`wrangler.toml`:
```
name = "my-app"
compatibility_date = "2024-03-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[env.preview]
r2_buckets = [
    { binding = "R2_ATTACHMENTS", bucket_name = "attachments", jurisdiction = "eu" },
]
```

Interestingly, the UI too has a bug there: When editing the settings of projects which are not configured using `wrangler.toml`, buckets with jurisdiction don't appear in the dropdown:
![grafik](https://github.com/cloudflare/workers-sdk/assets/18656830/729bcfa8-6307-433d-b5ed-69d2b4b1abed)
I'd expect to see my other buckets there, too. This has already been reported on discord, but I had hoped that the recent changes had fixed that ;-)

This is the only thing which is blocking me from migrating a couple of apps to Cloudflare Pages ;-)
Thanks for looking into this.

If you need anything else for testing, just let me know - happy to help.

**Comment by RamIdeas** [comment]
This is a known issue with the Pages backend service, tracked with internal tickets WC-2034 and WC-2101

Tagging with "pages" label but since one of those tickets has been marked as done cc @GregBrimble @WalshyDev – can you confirm if this issue is still outstanding?
