### ISSUE TITLE
🐛 BUG: Enable event notifications does not work for EU buckets

### ISSUE THREAD

**Issue by cmvrag** [cloudflare/workers-sdk#5514]
### Which Cloudflare product(s) does this pertain to?

Queues

### What version(s) of the tool(s) are you using?

3.47.0 Wrangler

### What version of Node are you using?

20.11

### What operating system and version are you using?

Windows 10

### Observed behavior
workers.api.error.bucket_not_found [code: 10085] when trying to enable event notifications on an EU based R2 bucket 

### Expected behavior
Configuration created successfully!

### Steps to reproduce
followed:  https://developers.cloudflare.com/r2/examples/upload-logs-event-notifications/#6-write-event-notification-messages-to-r2

Everything worked perfectly until step to enable event notifications.  Would not find my EU bucket.  Tried creating a new bucket that was NOT EU based and it worked.  

### Please provide any relevant error logs

workers.api.error.bucket_not_found [code: 10085]

**Comment by jonesphillip** [comment]
This should work now. Closing out.
