### ISSUE TITLE
🐛 BUG: `warning(s) when compiling Worker` can't be read anywhere

### ISSUE THREAD

**Issue by hrueger** [cloudflare/workers-sdk#5518]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.47.0 [wrangler]

### What version of Node are you using?

20.12.1

### What operating system and version are you using?

macOS Sonoma 14.4.1

### Observed behavior
When I'm building a complex pages application and then deploying it using `npx wrangler pages deploy`, I get the following output:
```
npx wrangler pages deploy
▲ [WARNING] Warning: Your working directory is a git repo and has uncommitted changes

  To silence this warning, pass in --commit-dirty=true


🌍  Uploading... (194/194)

✨ Success! Uploaded 0 files (194 already uploaded) (0.23 sec)

✨ Uploading _headers
▲ [WARNING] 3 warning(s) when compiling Worker.


✨ Uploading Worker bundle
✨ Uploading _routes.json
✨ Deployment complete! Take a peek over at https://abcdefg.myapp.pages.dev
```

It says `▲ [WARNING] 3 warning(s) when compiling Worker.`. However, there seems to be no way to actually see those warnings... They're not written to the wrangler log file, there's no --verbose or --debug option and setting the `DEBUG` env variable also does not help. I couldn't find anything in the docs either...

### Expected behavior
Instructions on how to view those warnings are provided or (even better) the warnings are logged to stderr directly.

### Steps to reproduce
Since I don't know what is causing the warnings, I unfortunately cannot prepare a minimal reproduction... :-|

**Comment by CarmenPopoviciu** [comment]
hi @hrueger ,

This was addressed in https://github.com/cloudflare/workers-sdk/pull/6022/files#diff-febd394561824779f39839b2383215615828dc954b274ee9b3d2464e83fc08b7. Can you please check again with the latest warngler version and let us know if it is still an issue for you? 🙏

**Comment by hrueger** [comment]
Hi, thanks for fixing this. Unfortunately, I cannot test this in the near future, as we don't use Workers anymore for our primary application and I currently don't have the capabilities to test production-unrelated issues.

**Comment by CarmenPopoviciu** [comment]
no problem at all. thank you for letting us know.

I'll go ahead and close this as the issue was fixed in the commit I mentioned in my previous comment. If you or anyone else experiences a similar issue please feel free to re-open <3
