### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by alankemp** [cloudflare/workers-sdk#5519]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.45.0

### What operating system and version are you using?

Linux

### Observed behavior
There are warnings shown when installing wrangler:

> $ npm install -g wrangler@latest
> npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
> npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.

### Expected behavior
No warnings!

### Steps to reproduce
`$ npm install -g wrangler@latest`

**Comment by rozenmd** [comment]
@alankemp is the bug here that you expect no warnings from npm when installing wrangler, or is there something else?

**Comment by threepointone** [comment]
Closing this, feel free to comment if you have more info.
