### ISSUE TITLE
🐛 BUG: Unable to deploy Pages when using a `worker.toml` with Hyperdrive binding

### ISSUE THREAD

**Issue by benank** [cloudflare/workers-sdk#5525]
### Which Cloudflare product(s) does this pertain to?

Pages, Other

### What version(s) of the tool(s) are you using?

Latest everything

### What version of Node are you using?

18.18.2

### What operating system and version are you using?

macOS 14.4.1

### Observed behavior
I am using the Cloudflare Pages Github application to automatically deploy my app. Today, I added the new `wrangler.toml` file since support was just added to Pages. I have a Hyperdrive binding in it. When I push my code to automatically deploy, I get this opaque error message:
```
20:47:19.442	wrangler.toml config file detected
20:47:20.465	Failed: an internal error occurred. If this continues, contact support: https://cfl.re/3WgEyrH
```

### Expected behavior
Because I have seen this issue in development, I assume that the problem is due to this error:
```
Error: When developing locally, you should use a local Postgres connection string to emulate Hyperdrive functionality. Please setup Postgres locally and set the value of the 'WRANGLER_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE' variable or "HYPERDRIVE"'s "localConnectionString" to the Postgres connection string.
```

When the Cloudflare Pages application builds my Pages site (built with SvelteKit) that has a `wrangler.toml` with a Hyperdrive binding, it needs a Hyperdrive local connection string. How can I provide a local connection string to the Cloudflare Pages application while building? Setting one in the Pages console environment variables and secrets doesn't work.

### Steps to reproduce
1. Create a new SvelteKit project with Cloudflare.
2. Add automatic deployments with the Cloudflare Pages Github Application.
3. Add a `wrangler.toml` file with a Hyperdrive binding.
4. Push your code.
5. Observe that the deployment will fail with a vague error message.

Note that deploying directly using `npx wrangler pages deploy` works because it builds my site locally, which uses my local environment variables that have local connection strings for Hyperdrive. However, I would prefer not to use this method and have my deployments managed by Github.

**Comment by WalshyDev** [comment]
Hey, what's the deployment ID for that?

The Pages deployment ID is a unique build identifier.
It's the UUID in the browser bar (for example, a URL would be dash.cloudflare.com/ACCOUNT_ID/pages/view/PROJECT/DEPLOYMENT_ID where the deployment ID looks something like a398d794-7322-4c97-96d9-40b5140a8d9b).

**Comment by benank** [comment]
Awesome, thank you!

**Comment by petebacondarwin** [comment]
Reopening until the required infrastructure changes have been released.
