### ISSUE TITLE
🐛 BUG: regression/breaking change in default port with `pages dev`

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#5534]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.47.1

### What version of Node are you using?

20.12.1

### What operating system and version are you using?

Windows 11

### Observed behavior

In wrangler <3.38.0, `wrangler pages dev public` would spawn a server on port `8788` by default.
`[wrangler:inf] Ready on http://127.0.0.1:8788`

In wrangler 3.38.0 and above, the same command spawns the server on port `8787` by default:
`[wrangler:inf] Ready on http://127.0.0.1:8787`

This has broken some workflows for people that rely on it in testing or other workflows.

### Expected behavior
The default port should remain 8788 to avoid issues with documentation, testing, and other things that rely on this, otherwise it's a breaking change.

### Notes

This was introduced in this commit: https://github.com/cloudflare/workers-sdk/commit/f5e2367288e7f57365ef8a1373bbc404bb50a662#diff-c90ff1ca6d929baaafb7d67d6d6ccd573593762adf4e7a9b6917343ceeceb68bL116

The default was seemingly removed: 
![image](https://github.com/cloudflare/workers-sdk/assets/856748/c1c09348-141d-4395-891d-f63bb7f1370f)

**Comment by admah** [comment]
Thanks for flagging this, James, and for the PR. We're going to take a look at this first thing next week.
