### ISSUE TITLE
🐛 BUG: Wrangler deploy stopped working with `workers.api.error.malformed_param` error

### ISSUE THREAD

**Issue by sammdec** [cloudflare/workers-sdk#5541]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

3.48.0 [Wrangler] 

### What version of Node are you using?

Bun 1.1.0

### What operating system and version are you using?

OSX Sonoma 14.4.1

### Observed behavior
When running `wrangler deploy` after many weeks of working behaviour, suddenly wrangler started rejecting with the following error.
`workers.api.error.malformed_param: must specify either 'script' or 'service' [code: 10004]`

### Expected behavior
Worker should deploy successfully

### Steps to reproduce
Please provide the following:
- A minimal working subset of your `wrangler.toml`
```
name = "my-worker"
compatibility_date = "2024-04-06"
main = "src/index.ts"
route = { pattern = "sub.domain.com", custom_domain = true }

[durable_objects]
bindings = [{name = "SUBSCRIPTION", class_name = "Subscription"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Subscription"]
```
- Commands used to start your local dev server, including custom env and cli args
`wrangler dev src/index.ts`

### Please provide any relevant error logs

`workers.api.error.malformed_param: must specify either 'script' or 'service' [code: 10004]`

**Comment by penalosa** [comment]
@tanushree-sharma could you take a look at this? Last time this came up (https://github.com/cloudflare/workers-sdk/issues/3350) it seems to be an API issue with a particular worker

**Comment by sammdec** [comment]
I spoke with Greg Brimble on DM's and from his investigation it sounds like because I had a tail worker that I removed something is hanging around in a backend that is stopping it from deploying

**Comment by tanushree-sharma** [comment]
Thanks for reporting @sammdec. We've picked this up and we're aiming to have a fix out tomorrow.

**Comment by sammdec** [comment]
@tanushree-sharma hey there, any update about when a fix might be going live?

**Comment by tanushree-sharma** [comment]
@sammdec We had an unexpected limited deployment window as a result of an [incident late yesterday](https://www.cloudflarestatus.com/incidents/w5c2r6mqjshl). We're getting this in tomorrow!

**Comment by sammdec** [comment]
Cool, no worries thanks for letting me know 👍🏻

**Comment by sammdec** [comment]
@tanushree-sharma hey there any update on a fix?

**Comment by sammdec** [comment]
@tanushree-sharma any update I could really do with deploying soon.

**Comment by tanushree-sharma** [comment]
Hey @sammdec, apologies for not following up here. We had a fix merged 04/11. Is this resolved for you? cc: @matthewdavidrodgers

**Comment by sammdec** [comment]
Yep can confirm all working now. Thanks for the fix!

**Comment by petebacondarwin** [comment]
Glad to see your issue is resolved. Thanks for reporting @sammdec  and thanks @tanushree-sharma for shepherding through the fix.
