### ISSUE TITLE
🐛 BUG: OAUTH bug, redirects the user to localhost:8976

### ISSUE THREAD

**Issue by ranjancse26** [cloudflare/workers-sdk#5542]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

Wrangler 3.48.0

### What version of Node are you using?

v20.11.1

### What operating system and version are you using?

Windows 11

### Observed behavior
Wrangler login or publish is not working. It's taking the user to https://localhost:8976/oauth/callback

### Expected behavior
Wrangler should login
Wrangler should be able to publish from local machine

### Steps to reproduce
Please provide the following:
- Select any worker repo
- Perform the wrangler login using npx wrangler login
- The consent form is show
- Once the user approves the content, it's taking the user to https://localhost:8976/oauth/callback

### Please provide a link to a minimal reproduction

https://github.com/cloudflare/python-worker-hello-world

### Please provide any relevant error logs

No error logs displayed on screen.

**Comment by penalosa** [comment]
@ranjancse26 This is expected behaviour. What happens when you are redirected to `localhost:8976`? What do the Wrangler output logs say?

**Comment by ranjancse26** [comment]
@penalosa I don't think redirecting to localost 8976 is the expected behavior. Now I not seeing a different error. The localhost redirect is not happening. 

User consent screen is not showing up. Instead, I am seeing the console error.

![image](https://github.com/cloudflare/workers-sdk/assets/2565797/74ef9ea5-b33f-4d61-8ccf-49f6ad4f22e4)

![image](https://github.com/cloudflare/workers-sdk/assets/2565797/8ee0464e-6103-4767-a649-6d04b56a458b)

Could you please spend some time in recreating this issue by yourself. Follow the steps which I have mentioned above. See for yourself if you are able to just log in using wrangler and then do the deployment using the "deploy" command. Check if you are able to successfully deploy the worker using wrangler.

**Comment by petebacondarwin** [comment]
I have tried to reproduce this using the steps given above. I cloned the python repository you linked.

Within this repository I ran:

```sh
 npx wrangler@3.48.0 login
 ⛅️ wrangler 3.48.0 (update available 3.51.0)
-------------------------------------------------------
Attempting to login via OAuth...
Opening a link in your default browser: https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=54d11594-84e4-41aa-b438-e81b8fa78ee7&redirect_uri=http%3A%2F%2Flocalhost%3A8976%2Foauth%2Fcallback&scope=account%3Aread%20user%3Aread%20workers%3Awrite%20workers_kv%3Awrite%20workers_routes%3Awrite%20workers_scripts%3Awrite%20workers_tail%3Aread%20d1%3Awrite%20pages%3Awrite%20zone%3Aread%20ssl_certs%3Awrite%20constellation%3Awrite%20ai%3Awrite%20offline_access&state=XXXXXXX&code_challenge=XXXXXXX&code_challenge_method=S256
```

I have XXXXXed out the sensitive details, but you can see that the redirect_url is `http://localhost:8976/oauth/callback`.

The brower opens and the website displays the consent page. When I click the consent button, the website redirects to that localhost:8976 URL, which is a server being hosted by Wrangler that then receives the OAuth tokens and stores them for future use. Once the handshake is complete Wrangler will tear down that server.

I also see the errors you show in your screen shot above but these are not relevant and do not affect the OAuth flow.

**Comment by ranjancse26** [comment]
@petebacondarwin Ok, the problem which I was facing in one of the Windows 11 laptop is, I wasn't able to login and even use the deploy command. The wrangler was basically failing with the localhost redirect. After that, nothing happened on the command prompt. No errors as such. I wasn't able to login/deploy. 

Sorry, it doesn't matter whether it's a OAuth flow error or not, However the users need to be able to properly authenticate and deploy any apps which were created with "Wrangler". 

Apologize if there were confusion.

**Comment by petebacondarwin** [comment]
Thanks for the additional context. So I guess we need to understand why the redirect was failing on your Windows 11 laptop. I assume it is working on other machines for you? What browser is being used? Are you definitely using Wrangler 3.48.0. 

There was a bug prior to 3.36.0 (https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/CHANGELOG.md#3360) where the latest Chrome broke the OAuth flow because we didn't handle the OPTION preflight request from the browser.

I wonder if there is another process on that laptop that is already holding port 8976, which might be why the redirect is failing? Could you check to see?

Other than that I am not sure what else we can do to diagnose this problem. This login flow is the standard OAuth handshake for device login - we are not doing anything particularly unusual here.

**Comment by beswarm** [comment]
seems the same problem: 

/Users/xxx/.nvm/versions/node/v18.16.0/bin/npm run deploy

> xxx@0.0.0 deploy
> wrangler deploy

 ⛅️ wrangler 3.28.1 (update available 3.51.2)
-------------------------------------------------------
Attempting to login via OAuth...
Opening a link in your default browser: https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=54d11594-84e4-41aa-b438-e81b8fa78ee7&redirect_uri=http%3A%2F%2Flocalhost%3A8976%2Foauth%2Fcallback&scope=account%3Aread%20user%3Aread%20workers%3Awrite%20workers_kv%3Awrite%20workers_routes%3Awrite%20workers_scripts%3Awrite%20workers_tail%3Aread%20d1%3Awrite%20pages%3Awrite%20zone%3Aread%20ssl_certs%3Awrite%20constellation%3Awrite%20ai%3Aread%20offline_access&state=~PBIPYqdRr8mn6d-xOGhzfw5bxyeoph4&code_challenge=-ISaTEqMsIXQ20EKnMPL3F9Kr6PS2rPgFDuTPkZ0WOg&code_challenge_method=S256
/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:29572
            throw a;
            ^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:5121:19)
    at successSteps (/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:5092:27)
    at fullyReadBody (/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:3590:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:5101:7)
    at async exchangeAuthCodeForAccessToken (/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:120587:31)
    at async Server.<anonymous> (/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:120747:30)

Node.js v18.16.0

Process finished with exit code 7

**Comment by petebacondarwin** [comment]
@beswarm - I think you are seeing the different issue that affects Wrangler before 3.36.0 - see https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/CHANGELOG.md#3360. Please update to a more recent version of Wrangler and try again

**Comment by petebacondarwin** [comment]
@ranjancse26 - please can you confirm what browser make and version you are using to complete the login? 
Can you also open the network tab before you complete the login on the browser and record exactly what the request back to port 8967 looks like.

**Comment by ranjancse26** [comment]
@petebacondarwin Here is the info which you have requested. I tried again, however I am still not be able to log in and deploy on Windows 11 machine.

**Microsoft Edge - Latest up to date.
Version 124.0.2478.51 (Official build) (64-bit)**



![WranglerLoginConsole](https://github.com/cloudflare/workers-sdk/assets/2565797/b0f7a475-12bd-4500-9cac-11109116fe76)

![WranglerLogin](https://github.com/cloudflare/workers-sdk/assets/2565797/09f0f554-44e3-4d25-bcec-3bda17b1556e)

**Comment by petebacondarwin** [comment]
Hi - thanks for the additional screenshots. What I would really like to see is the network requests coming from the browser by looking at the "network tab" in the inspector. The console logs you show in the screenshot do not indicate what is going on with the request that is being made to Wrangler to complete the login.

Also, could you try copying the link given by Wrangler into a different browser (e.g. Chrome) and doing the login via that browser, rather than the one that automatically opens up (MS Edge).

**Comment by beswarm** [comment]
> @beswarm - I think you are seeing the different issue that affects Wrangler before 3.36.0 - see https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/CHANGELOG.md#3360. Please update to a more recent version of Wrangler and try again

upgrade and restart do not help. I see the same error and using MS Edge too. manully cope the link into chrome and  do not success neither. 
here is my network tab console snapshot, hope it will help.
![Uploading 109494D8-02BF-48AB-846C-5DE6D4E40B30_1_201_a.jpeg…]()

**Comment by beswarm** [comment]
> @beswarm - I think you are seeing the different issue that affects Wrangler before 3.36.0 - see https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/CHANGELOG.md#3360. Please update to a more recent version of Wrangler and try again

Thank you for your support. Despite attempting both an upgrade and a restart, the problem with port 8976 persists. I've am using Microsoft Edge also. I also  manually copying the link into Chrome, but without success. Below is a snapshot from my network tab console which might offer more insight.

There are occasional logs in the Wrangler console indicating that port 8976 is in use, but these logs disappear and subsequent checks with netstat don’t show the port as being active. Here’s the command I used for verification:
netstat -an | grep 8976 | grep LISTEN

![109494D8-02BF-48AB-846C-5DE6D4E40B30_1_201_a](https://github.com/cloudflare/workers-sdk/assets/7619685/b963fe31-9e15-4bfd-9821-04ba2c723ef0)

**Comment by beswarm** [comment]
![image](https://github.com/cloudflare/workers-sdk/assets/7619685/42f2d332-e0a6-446a-8940-91a841b558ce)

It seems the port is associated with  IPv6

**Comment by petebacondarwin** [comment]
Thanks @beswarm - could you also show what the response is from that request? Is it a 404? A 500? Is there any information in that response that could help us?

That last netstat... is that showing the Wrangler process listening on `::1:8976` or is that some other process that is holding that port?

So in Node (after v16), listening on `localhost` (which is what Wrangler is doing) will default to listening on the IPv6 address (::1), rather than the IPv4 address (127.0.0.1).  But equally Window should also be trying to make the request to the IPv6 version of `localhost`. I wonder if your machine is configure to only use IPv4?

One other idea comes from here: https://github.com/cloudflare/workers-sdk/issues/2433#issuecomment-1833945618

> First, I worked on WSL and thus localhost indicates my local Windows machine instead of WSL where Wrangler is actually running and listening since the browser is running on the local machine, so I simply changed localhost to my WSL's IP address.
> 
> Second, I have my browser enabled "Always use secure connections" which will automatically upgrade navigations to HTTPS, but I guess Wrangler doesn't (and have no need to) use HTTPS on local, so I explicitly added http:// at the beginning of the url.

Are either of these cases relevant to your setup? In particular the second one about upgrading to secure connections?

**Comment by petebacondarwin** [comment]
On my Windows machine (Windows 10 Pro - not 11!!) with Edge (Version 124.0.2478.51 (Official build) (64-bit)) I see this:

![image](https://github.com/cloudflare/workers-sdk/assets/15655/4b3276b4-a153-4b61-b192-daa44b311d53)

The redirect is expected, when Wrangler responds to the request it tells the browser to redirect back to the Cloudflare website to display the confirmation page.
I note that the "Remote Address" in this case is `127.0.0.1:8976`. Can you check what it is for you?

**Comment by petebacondarwin** [comment]
Using Node.js 20 I can see that the Remote address is now `::1:8976` but the handshake still works...

<img width="573" alt="Screenshot 2024-04-24 at 10 47 10" src="https://github.com/cloudflare/workers-sdk/assets/15655/61324aa4-5355-4d4b-9d4b-c8f7fc4ddd07">

**Comment by beswarm** [comment]
Apologies for the delayed response. Occasionally, I am automatically logged in after some failed tries. below is some log details.
 
 ————1. the terminal part —————
beswarm@macbook workers-getting-started % wrangler login
 ⛅️ wrangler 3.52.0
-------------------
Attempting to login via OAuth...
Opening a link in your default browser: https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=54d11594-84e4-41aa-b438-e81b8fa78ee7&redirect_uri=http%3A%2F%2Flocalhost%3A8976%2Foauth%2Fcallback&scope=account%3Aread%20user%3Aread%20workers%3Awrite%20workers_kv%3Awrite%20workers_routes%3Awrite%20workers_scripts%3Awrite%20workers_tail%3Aread%20d1%3Awrite%20pages%3Awrite%20zone%3Aread%20ssl_certs%3Awrite%20constellation%3Awrite%20ai%3Awrite%20queues%3Awrite%20offline_access&state=GbHoVIJ.XlxpgM0FLpiZCGyEwWrkoL6Q&code_challenge=B4mIXFnWzoueWagF6eMw_NoY3bfP6UcFZCd790b9qMM&code_challenge_method=S256
/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:29573
            throw a;
            ^

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:5121:19)
    at successSteps (/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:5092:27)
    at fullyReadBody (/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:3590:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:5101:7)
    at async exchangeAuthCodeForAccessToken (/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:120821:31)
    at async Server.<anonymous> (/Users/beswarm/WebstormProjects/workers-getting-started/node_modules/wrangler/wrangler-dist/cli.js:120983:30)

Node.js v20.12.2

———— 2. the  brower callback part ————  (there is no response body and status code for it, seems the request trigger the the above "not valid json error") 

curl 'http://localhost:8976/oauth/callback?code=VFLVNe21UJFtI4lPndw1V3G1whd8_efXpBnHyGOfqWg.SNU1H6PPQW7c7ca11XQLGXydf9qZwhAvF2A1bS3u_9o&scope=account%3Aread%20user%3Aread%20workers%3Awrite%20workers_kv%3Awrite%20workers_routes%3Awrite%20workers_scripts%3Awrite%20workers_tail%3Aread%20d1%3Awrite%20pages%3Awrite%20zone%3Aread%20ssl_certs%3Awrite%20constellation%3Awrite%20ai%3Awrite%20queues%3Awrite%20offline_access&state=GbHoVIJ.XlxpgM0FLpiZCGyEwWrkoL6Q' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'Accept-Language: en,zh-CN;q=0.9,zh-TW;q=0.8,zh;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: _ga=GA1.1.124774658.1709736126; _ga_J9VQK5NQXR=GS1.1.1709986232.2.0.1709986232.0.0.0' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0' \
  -H 'sec-ch-ua: "Chromium";v="124", "Microsoft Edge";v="124", "Not-A.Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"'

![image](https://github.com/cloudflare/workers-sdk/assets/7619685/aeb48ef6-7a28-4d80-9892-f817ffd372ec)

**Comment by beswarm** [comment]
After a bit of debugging, it appears that the issue lies in cli.js  below snippets.  The response returned is not in JSON format, which causes the error.  although, I do not know why this happen.

Please see the response file posted below for further details."

  const response = await fetchAuthToken(params);
  if (!response.ok) {
    const { error: error2 } = await response.json(); ---- error
    if (error2 === "invalid_grant") {
      logger.log("Expired! Auth code or refresh token needs to be renewed.");
    }
    throw toErrorClass(error2);
  }
  
  
 the response request are origin from:
 
![370010E6-861A-4C08-810E-8716011A8EF5_1_201_a](https://github.com/cloudflare/workers-sdk/assets/7619685/16474994-8969-4caa-9186-d86c7c76fa86)

![3906DDF2-72AB-4D94-8A2F-7F5A2BBB4611_4_5005_c](https://github.com/cloudflare/workers-sdk/assets/7619685/436b91ea-fe88-4c2d-9f2a-4de6a5c4bc26)


does not support html suffix, rename it to txt on purpose.
[response_html.txt](https://github.com/cloudflare/workers-sdk/files/15107049/response_html.txt)

**Comment by beswarm** [comment]
maybe it is related to security thing. after I changed my ip, it works fine now. I am using tailscale

**Comment by petebacondarwin** [comment]
@beswarm - I think the Cloudflare network in front of https://dash.cloudflare.com/oauth2/auth was thinking that your tailscale fronted IP address was potentially malicious and was redirecting you to a challenge page (e.g. a "prove you are not a robot" kind of thing)? This is quite likely as probably lots of actors using tailscale get associated with the same outbound IP address...?

It is notable that the HTML you provided included this:

```html
<noscript><div id="challenge-error-title"><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript>
```

And the embedded JS script in that HTML doc is trying to run code from this URL:

```
/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=879d193799832366
```

This code is part of the Cloudflare's Challenge Platform that tries to identify bots and other malicious actors.

I'm glad is working for you again now. If this re-occurs then please get in touch because it may be that the challenge platform needs some tweaking for the IP address that is being used.

**Comment by JBloss1517** [comment]
I also had the same problem, but I am running it from my personal computer. I am using:
* wrangler 3.61.0
* Windows 11
* Firefox browser

I was able to fix it by simply using `npx wrangler login` first before running the publish command. But had basically identical issues listed above.

**Comment by joldeski** [comment]
I am currently facing this issue. 
wrangler 3.61.0
macOS 14.1.1
Firefox.

**Comment by BruceLuos** [comment]
i also have the problem , and i just put the proxy in my terminal like
`export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890`
then the problem disappear...

- wrangler 3.61.0
- macos 14.2
- chrome

**Comment by petebacondarwin** [comment]
Same issue: https://github.com/cloudflare/workers-sdk/issues/3672
