### ISSUE TITLE
🐛 BUG:"Hello World" Worker Not Responding

### ISSUE THREAD

**Issue by ngocnha** [cloudflare/workers-sdk#5545]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.48

### What version of Node are you using?

21 latest LTS

### What operating system and version are you using?

Linux Debian Bookworm

### Describe the Bug

I followed the guide at https://developers.cloudflare.com/workers/get-started/guide/ to create a simple "Hello World" Cloudflare Worker application.
When I run the command "npx wrangler dev," the Worker starts successfully and listens on port 8787.
However, when I try to access it in a web browser, the page loads indefinitely without displaying any content.

There are no error log in the terminal, but the application is not functioning as expected.

**Comment by penalosa** [comment]
@ngocnha thanks for reporting this! Would you be able to upload the Wrangler logs from your dev session?
