### ISSUE TITLE
🐛 BUG: Fetching a domain that doesn't exist triggers an "internal error"

### ISSUE THREAD

**Issue by johtso** [cloudflare/workers-sdk#5571]
### Which Cloudflare product(s) does this pertain to?

Miniflare

### What version(s) of the tool(s) are you using?

3.48.0 [wrangler]

### What version of Node are you using?

21.7.1

### What operating system and version are you using?

MacOS Sonoma 14.4.1

### Observed behavior
When you make a `fetch` to a non existent domain while running locally in wrangler, an `internal error` is triggered.

### Expected behavior
Should not produce an error

Just to add a little more context, we do this intentionally as a way to increment the current time for the purposes of accurate tracing as it is considerably faster than fetching a domain that exists.

### Steps to reproduce
`wrangler dev`
hit a url that triggers a fetch of a domain that doesn't exist.
example project attached.

### Please provide a link to a minimal reproduction

https://github.com/johtso/wrangler-bug-repro

### Please provide any relevant error logs

```
[wrangler:err] Error: internal error
    at async Object.fetch (file:///Users/xxxxx/repro/src/index.ts:30:3)
    at async jsonError (file:///xxxxx/.nvm/versions/node/v21.7.1/lib/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:10)
    at async drainBody (file:///xxxxx/.nvm/versions/node/v21.7.1/lib/node_modules/wrangler/templates/middleware/middleware-ensure-req-body-drained.ts:5:10)
```

**Comment by johtso** [comment]
Just to add a little more context, we do this intentionally as a way to increment the current time for the purposes of accurate tracing as it is considerably faster than fetching a domain that exists.

**Comment by mootari** [comment]
The spelling of "internal error" suggests that it might be OpenSSL related, e.g. https://github.com/nodejs/node/blob/2cd3073e0f19d8e28c2412c9208f6ffed60ae33b/deps/openssl/openssl/ssl/ssl_stat.c#L366

**Comment by johtso** [comment]
Still an issue with wrangler 3.64.0

**Comment by petebacondarwin** [comment]
It is expected that `fetch()` throws an error if the domain does not exist. It should not return an error response, it should actually throw.
The error message is not so helpful, but as @mootari suggests it is likely that openssl is failing since the domain would have no SSL certificate. What happens if you use `http` rather than `https`?

Closing as this is working as expected.

**Comment by johtso** [comment]
@petebacondarwin thanks for the reply.

The behaviour is the same with or without SSL, same error message.

Putting aside the unhelpful error that gets thrown, the root of the confusion I think is from the fact that Cloudflare returns a 530 response when a Worker makes a request to a domain that can't be resolved, rather than the request causing an error.

This is quite a significant difference in behaviour, but I don't know whether Wrangler tries to emulate these kinds of Cloudflare quirks when running locally?

**Comment by penalosa** [comment]
In Wrangler v3, `wrangler dev` runs your Worker in a local simulator of the workers environment—https://github.com/cloudflare/miniflare. Unfortunately that means that you won't see all of the behaviour of the rest of the (non-workers) Cloudflare environment locally (small differences in error response codes is one aspect of that). To test your Worker against the rest of the Cloudflare environment, you can start a remote preview with wrangler dev --remote. That will provide the most accurate simulation of network quirks like this while testing.

If you want to test this locally, then the best option is probably to extract this out into a shared function that handles both local and remote behaviour:

```ts
async function advanceCurrentTime() {
  try {
    await fetch("https://0348567349828821555790263456.com")
  } catch {}
}

**Comment by Bobrokus** [comment]
> In Wrangler v3, `wrangler dev` runs your Worker in a local simulator of the workers environment—[cloudflare/miniflare](https://github.com/cloudflare/miniflare). Unfortunately that means that you won't see all of the behaviour of the rest of the (non-workers) Cloudflare environment locally (small differences in error response codes is one aspect of that). To test your Worker against the rest of the Cloudflare environment, you can start a remote preview with wrangler dev --remote. That will provide the most accurate simulation of network quirks like this while testing.
> 
> If you want to test this locally, then the best option is probably to extract this out into a shared function that handles both local and remote behaviour:
> 
> ```ts
> async function advanceCurrentTime() {
>   try {
>     await fetch("https://0348567349828821555790263456.com")
>   } catch {}
> }
> ```

Thanks so much! `wrangler dev --remote` fixed this issue for me. I was digging through rabbit holes and am so thankful I found this!
