### ISSUE TITLE
🐛 BUG: `getPlatformProxy` doesn't provide an AI binding when it should

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/workers-sdk#5575]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

`wrangler@3.48.0`

(the issue has been introduced in `3.42.0`, earlier versions don't present this issue)

### What version of Node are you using?

20

### What operating system and version are you using?

Mac

### Observed behavior

`getPlatformProxy` with a `wrangler.toml` file containing an AI binding declaration:
```toml
[ai]
binding = "AI"
```
does not produce a proxy to the AI binding

### Expected behavior

It should produce an AI binding, meaning that with:
```js
import { getPlatformProxy } from 'wrangler';

const { env } = await getPlatformProxy();
```
`env.AI` should contain a valid proxy object

### Please provide a link to a minimal reproduction

https://github.com/dario-piotrowicz/getPlatformProxy-ai-undefined-repro

**Comment by ErickLuis00** [comment]
UP
