### ISSUE TITLE
🐛 BUG: Miniflare's `getBindings` does not properly expose RPC entrypoints

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/workers-sdk#5577]
### Which Cloudflare product(s) does this pertain to?

Miniflare

### What version(s) of the tool(s) are you using?

miniflare@3.20240404.0

### What version of Node are you using?

20

### What operating system and version are you using?

Mac

### Observed behavior
[RPC entrypoints](https://blog.cloudflare.com/javascript-native-rpc) can be defined and used within Miniflare (meaning that they do work for scripts running in miniflare itself).

The issue is that they don't seem available from `Miniflare#getBindings`, the method does return valid proxies for such bindings but trying to access the RPC methods does not work and generates the following [workerd warning](https://github.com/cloudflare/workerd/blob/f77cdc6f08be2a29ef1e35118f86fbd4fdc008b7/src/workerd/api/http.c%2B%2B#L2117-L2122) (regardless on the compat date and flags used):
![Screenshot 2024-04-10 at 18 09 53](https://github.com/cloudflare/workers-sdk/assets/61631103/d2b22101-f364-40de-9224-8ac9e52db6fc)

### Expected behavior

`Miniflare#getBindings` should return bindings with RPC that can be used in the same manner as they can inside Miniflare itself.

### Please provide a link to a minimal reproduction

https://github.com/dario-piotrowicz/miniflare-no-rpc-binding-repro/tree/main

**Comment by dario-piotrowicz** [comment]
the following change fixes the issue compat date/flag issue:
![Screenshot 2024-04-10 at 19 23 22](https://github.com/cloudflare/workers-sdk/assets/61631103/70fa52f9-0bf2-46ab-9bce-22d00983d324)

that does not however seem enough to get the RPC calls working 😓

**Comment by penalosa** [comment]
@dario-piotrowicz does adding the `rpc` flag change the error message at all?

**Comment by dario-piotrowicz** [comment]
@penalosa Yes, adding the `rpc` flag removes that warning/error completely and makes the binding proxy almost work

The problem is that then there are some serialization issues as it seems like RPC is making miniflare try to serialize the RPC functions, I started looking into it but I didn't get far yet, I can provide some more details tomorrow :slightly_smiling_face: 

I hope it's not going to be too problematic, but I worry that this can be quite tricky, since the workerd RPC implementation allows the use of any _structured clonable_ data and I think that the Miniflare proxy implementation instead simply stringifies things.
