### ISSUE TITLE
🚀 Feature Request: specify worker env for getPlatformProxy()

### ISSUE THREAD

**Issue by hrueger** [cloudflare/workers-sdk#5583]
### Describe the solution

Hi,
It would be very useful if the `options` object of `getPlatformProxy()` would accept an `env` property which would be used to get bindings from the `wrangler.toml` file of that specific environment. Currently, only top-level bindings are used (at least for workers, not sure about pages).

**Comment by dario-piotrowicz** [comment]
Hi @hrueger 👋 🙂 

Thanks for the issue

It should be pretty simple to add support for specifying an `env`

It should be just a matter of extending the API and pass the value here:
https://github.com/cloudflare/workers-sdk/blob/fbe1c9c816f2b5774060d721ff830e70d9b7d29f/packages/wrangler/src/api/integrations/platform/index.ts#L89-L90

I'll have a look into it soon 🙂👍

**Comment by dario-piotrowicz** [comment]
@hrueger PR opened 🙂👍 

(If you want please give the [PR's prerelease](https://github.com/cloudflare/workers-sdk/pull/5604#issuecomment-2051689614) a shot and let me know if it works for you 😄)

**Comment by hrueger** [comment]
Wow, that was fast. Works perfectly for me 🎉👍
