### ISSUE TITLE
🐛 BUG: vitest cannot import "fs"

### ISSUE THREAD

**Issue by SharzyL** [cloudflare/workers-sdk#5590]
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

3.49.0 [wrangler], 0.1.0 [@cloudflare/vitest-pool-workers], 1.3.0 [vitest]

### What version of Node are you using?

20.11.1

### What operating system and version are you using?

NixOS

### Observed behavior
When trying to import "fs" module (to read test resources) in a vitest file, vitest complains that `Error: No such module "/path/to/project/root/node_modules/vite-node/dist/fs".`

### Expected behavior
vitest should import "fs" successfully, or there is an alternative way to read a test resource file.

### Steps to reproduce
Clone the repository `https://github.com/mrbbot/vitest-pool-workers-prerelease-getting-started`, make the following modification
```diff
diff --git a/test/index.spec.ts b/test/index.spec.ts
index babcbe4..3dbd6eb 100644
--- a/test/index.spec.ts
+++ b/test/index.spec.ts
@@ -3,6 +3,8 @@ import { describe, it, expect } from "vitest";
 // Could import any other source file/function here
 import worker from "../src";
 
+import "node:fs"
+
 // We're going to improve this in the next major version of workers types,
 // but for now, you'll need to do something like this to get a correctly-typed
 // `Request` to pass to `worker.fetch()`.
```

Run the test
```console
$ ./node_modules/.bin/vitest

 DEV  v1.3.0 /home/sharzy/ws/dev/contrib/vitest-pool-workers-prerelease-getting-started

[vpw:inf] Starting isolated runtimes for vitest.config.ts...
workerd/server/server.c++:2676: error: Fallback service failed to fetch module; payload = ; spec = /?specifier=%2Fhome%2Fsharzy%2Fws%2Fdev%2Fcontrib%2Fvitest-pool-workers-prerelease-getting-started%2Fnode_modules%2Fvite-node%2Fdist%2Ffs&referrer=%2Fhome%2Fsharzy%2Fws%2Fdev%2Fcontrib%2Fvitest-pool-workers-prerelease-getting-started%2Fnode_modules%2Fvite-node%2Fdist%2Fclient.mjs
 ❯ test/index.spec.ts (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/index.spec.ts [ test/index.spec.ts ]
Error: No such module "home/sharzy/ws/dev/contrib/vitest-pool-workers-prerelease-getting-started/node_modules/vite-node/dist/fs".
 ❯ test/index.spec.ts:4:31
      2| import { describe, it, expect } from "vitest";
      3| // Could import any other source file/function here
      4| import worker from "../src";
       |                               ^
      5| 
      6| import "node:fs"

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  22:59:58
   Duration  873ms (transform 24ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 183ms)


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
```

### Please provide a link to a minimal reproduction

https://github.com/mrbbot/vitest-pool-workers-prerelease-getting-started

**Comment by penalosa** [comment]
This is expected, since the Vitest integration runs your test files in the Cloudflare Workers runtime `workerd`, rather than Node.js. If you need to access the filesystem to read test data etc... you can use [Vitest's `globalSetup` file](https://vitest.dev/config/#globalsetup), which will run in a Node.js context (and can provide data to your tests using `provide()`)
