### ISSUE TITLE
🐛 BUG: Weird crash when logging from the console object 

### ISSUE THREAD

**Issue by gourgouris** [cloudflare/workers-sdk#5591]
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

wrangler: ^3.48.0, vitest: 1.3.0, @cloudflare/vitest-pool-workers: ^0.1.17

### What version of Node are you using?

v18.18.2

### What operating system and version are you using?

Win 11

### Observed behavior
crashes when logging using the [diary ](https://github.com/maraisr/diary/blob/main/src/index.ts) default_reporter

### Expected behavior
No crash

### Steps to reproduce
Go to the [official SELF recipe ](https://github.com/cloudflare/workers-sdk/blob/d95450f0b00fa32d4c827fc8ad25d8fc929a654d/fixtures/vitest-pool-workers-examples/basics-unit-integration-self/test/fetch-integration-self.test.ts#L4)
In linked line add the following code (even inside a test, no difference):

```
const fn = console["debug"];
console.debug("works");
fn("crashes");
```

The first loging "works" the second "crashes".
I believe it has to do with the [constructor here](https://github.com/cloudflare/workers-sdk/blob/d95450f0b00fa32d4c827fc8ad25d8fc929a654d/packages/vitest-pool-workers/src/worker/lib/node/console.ts#L29C23-L29C29) not expecting undefined `opts`

This code is ofc deep in my worker code, but can be replicated without even calling the worker.

### Please provide any relevant error logs

```
 TypeError: Cannot read properties of undefined (reading '#stdout')
 ❯ test/index.spec.ts:10:1
      8| console.debug("works")
      9| fn("crashes");
     10|
       | ^
```

![image](https://github.com/cloudflare/workers-sdk/assets/98039905/d723541f-0cc5-420d-a81a-513ebc3c9d6f)

**Comment by penalosa** [comment]
I think this is because `console.debug()` is becoming detached from it's `this` context. Could you try:

```js
const fn = console["debug"].bind(console);
console.debug("works");
fn("crashes");
```

**Comment by gourgouris** [comment]
yes, it does work. 

could this be offered automatically somehow though?
because, to implement this change, the diary library would need to be changed [here](https://github.com/maraisr/diary/blob/8fa3fdf5ca1e62885ba15d9e09b61a778aa4461e/src/index.ts#L38), which I am not sure how it could be justified to the author.

(I dont think I can apply this fix outside of the library - or without forking `default_reporter` function)

**Comment by petebacondarwin** [comment]
Looks like you are right that the Vitest Console does not correctly bind these properties to the Console instance as is normal in v8.
