### ISSUE TITLE
🐛 BUG:workers.api.error.no_access_to_vectorize [code: 100158]

### ISSUE THREAD

**Issue by MPranav1** [cloudflare/workers-sdk#5601]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms

### What version(s) of the tool(s) are you using?

wrangler 3.0.0,

### What operating system and version are you using?

windows 10

### Describe the Bug

command :- npm run deploy   

> rag-oncopanion@0.0.0 deploy
> wrangler deploy

 ⛅️ wrangler 3.49.0 (update available 3.50.0)
-------------------------------------------------------
Your worker has access to the following bindings:
- Vectorize Indexes:
  - VECTORIZE_INDEX: vector-db
- AI:
  - Name: AI
Total Upload: 429.25 KiB / gzip: 78.31 KiB

X [ERROR] A request to the Cloudflare API (/accounts/255dab2a23e265656e7d09e8ef1f5a0b/workers/scripts/rag-oncopanion) failed.

  workers.api.error.no_access_to_vectorize [code: 100158]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

**Comment by penalosa** [comment]
Vectorize is currently only available on the Workers Paid plan: https://developers.cloudflare.com/vectorize/
