### ISSUE TITLE
🐛 BUG: default typing for scheduled workers causes type mismatch when mocking with createScheduledController

### ISSUE THREAD

**Issue by onnimonni** [cloudflare/workers-sdk#5613]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Workers Vitest Integration

### What version(s) of the tool(s) are you using?

3.50.0

### What version of Node are you using?

v21.7.2

### What operating system and version are you using?

Mac Sonoma 14.4.1 (23E224)

### Observed behavior
Default typing for scheduled functions uses `ScheduledEvent` type for the first event parameter:
```ts
export default {
	async scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext): Promise<void> {
		console.log('This is a scheduled event');
	}
}
```

And If one tries to use the `createScheduledController` from the cloudflare vitest test helpers like this the typing returned by `createScheduledController` is `ScheduledController` instead of `ScheduledEvent` 
https://github.com/cloudflare/workers-sdk/blob/ad1d056cb2710b790ff5d4532e9f694e099c27e2/fixtures/vitest-pool-workers-examples/basics-unit-integration-self/test/scheduled-unit.test.ts#L10-L18

As a hack I can just add `ScheduledController` type into the function and it works just fine since they share most of the properties:
```ts
export default {
	async scheduled(event: ScheduledEvent | ScheduledController, env: Env, ctx: ExecutionContext): Promise<void> {
		console.log('This is a scheduled event');
	}
}
```

### Expected behavior
Cloudflare vitest integration should have a way to mock the `ScheduledEvent` and this should be used in the default template which generates scheduled workers. Am I just using this in a wrong way? If so what would be the correct way to mock the first parameter for scheduled workers?

### Please provide any relevant error logs

```
Argument of type 'ScheduledController' is not assignable to parameter of type 'ScheduledEvent'.
  Type 'ScheduledController' is missing the following properties from type 'ScheduledEvent': waitUntil, type, eventPhase, composed, and 13 more.ts(2345)
```

**Comment by RamIdeas** [comment]
Hi @onnimonni! ScheduledController is the correct type for the 1st parameter of the `scheduled` handler.

You can see this test which is practically identical to your code snippet https://github.com/cloudflare/workers-sdk/blob/main/fixtures/vitest-pool-workers-examples/basics-unit-integration-self/test/scheduled-unit.test.ts#L10

There, the worker is typed with `satisfies ExportedHandler` https://github.com/cloudflare/workers-sdk/blob/main/fixtures/vitest-pool-workers-examples/basics-unit-integration-self/src/index.ts#L12

We recommend you type the entire default export this way saving you from typing individual parameters yourself

**Comment by onnimonni** [comment]
Hey @RamIdeas the problem is that create cloudflare cli C3 does not use these types:
```bash
$ npm create cloudflare@latest
using create-cloudflare version 2.18.1

╭ Create an application with Cloudflare Step 1 of 3
│
├ In which directory do you want to create your application?
│ dir ./calm-pine-03e2
│
├ What type of application do you want to create?
│ type Scheduled Worker (Cron Trigger)
│
├ Do you want to use TypeScript?
│ yes typescript
│
├ Copying template files
│ files copied to project directory
│
├ Updating name in `package.json`
│ updated `package.json`
│
├ Installing dependencies
│ installed via `npm install`
│
╰ Application created

╭ Configuring your application for Cloudflare Step 2 of 3
│
├ Installing @cloudflare/workers-types
│ installed via npm
│
├ Adding latest types to `tsconfig.json`
│ added @cloudflare/workers-types/2023-07-01
│
├ Retrieving current workerd compatibility date
│ compatibility date 2024-04-05
│
╰ Application configured

╭ Deploy with Cloudflare Step 3 of 3
│
├ Do you want to deploy your application?
│ no deploy via `npm run deploy`
│
├  APPLICATION CREATED  Deploy your application with npm run deploy
│
│ Navigate to the new directory cd calm-pine-03e2
│ Run the development server npm run start
│ Deploy your application npm run deploy
│ Read the documentation https://developers.cloudflare.com/workers
│ Stuck? Join us at https://discord.gg/cloudflaredev
│
╰ See you again soon!
$ cd ./calm-pine-03e2
$ cat src/index.ts | grep ScheduledEvent
	async scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext): Promise<void> {
```

Should it?

**Comment by RamIdeas** [comment]
I'd agree it should. I think maybe the lack of `satisfies` syntax may have prevented us in the past

We'd welcome a PR to update the template or please feel free to open an issue for it
