### ISSUE TITLE
🚀 Feature Request: Update vitest dependency to 1.5 to support running and debugging tests directly from VSCode

### ISSUE THREAD

**Issue by onnimonni** [cloudflare/workers-sdk#5615]
### Describe the solution

When I try to run my vitest tests directly from Visual Studio Code with `@cloudflare/vitest-pool-workers` version `0.1.19` I get following error:
<img width="688" alt="Screenshot 2024-04-14 at 13 37 06" src="https://github.com/cloudflare/workers-sdk/assets/5691777/e064b26d-0719-4000-b497-60309bb28646">

If you would update the vitest dependency to at least 1.4 it would allow running tests directly with the vitest VSCode integration.

**Comment by onnimonni** [comment]
When trying to update to the new vitest version I get this:
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: You're running `vitest@1.5.0`, but this version of `@cloudflare/vitest-pool-workers` only supports `vitest@1.3.0`.
`@cloudflare/vitest-pool-workers` currently depends on internal Vitest APIs that are not protected by semantic-versioning guarantees.
Please install `vitest@1.3.0` to continue using `@cloudflare/vitest-pool-workers`.
```

**Comment by onnimonni** [comment]
According to the [VSCode vitest plugin](https://marketplace.visualstudio.com/items?itemName=vitest.explorer) version 1.5 is needed to run the debugger directly from VSCode.

**Comment by RamIdeas** [comment]
Hi @onnimonni! [This PR](https://github.com/cloudflare/workers-sdk/pull/5458), when landed, will loosen the version restriction to a warning.

**Comment by onnimonni** [comment]
> Hi @onnimonni! https://github.com/cloudflare/workers-sdk/pull/5458, when landed, will loosen the version restriction to a warning.

Thanks. I learned the same thing already yesterday in the [#vitest-integration-beta channel in Discord](https://discord.com/channels/595317990191398933/1218150105777963101/1229044006252445726).
