### ISSUE TITLE
🐛 BUG: `getPlatformProxy` DO proxy "undefined" is not a valid JSON

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/workers-sdk#5620]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

wrangler@3.50.0

### What version of Node are you using?

20

### What operating system and version are you using?

Mac

### Observed behavior
When using `getPlatformProxy` with recent version of wrangler (v>=3.46.0) it seems like DurableObject proxies don't properly work and when trying to fetch from them an response saying that `undefined` is not a valid JSON value is presented:
![ko](https://github.com/cloudflare/workers-sdk/assets/61631103/d53c8372-217a-4cd2-82ef-4473e665e48c)

### Expected behavior
Fetching from a DurableObject proxy should work as expected (as it worked with wrangler versions <= 3.45.0):
![ok](https://github.com/cloudflare/workers-sdk/assets/61631103/8df6e5b9-67c2-4b8a-a2be-fa69dad29716)

### Minimal reproduction

https://github.com/dario-piotrowicz/getPlatformProxy-DO-JSON-issue-repro

**Comment by dario-piotrowicz** [comment]
Ok, this issue explains this 🥲: https://github.com/cloudflare/workers-sdk/pull/5599#discussion_r1564315387
(and that's also why we were unable to prevent this regression from happening)

**Comment by clibequilibrium** [comment]
> Ok, this issue explains this 🥲: [#5599 (comment)](https://github.com/cloudflare/workers-sdk/pull/5599#discussion_r1564315387) (and that's also why we were unable to prevent this regression from happening)

Thank you for this ! Same issue here on latest wrangler, we are forced to use downgraded version for now

**Comment by dario-piotrowicz** [comment]
@clibequilibrium the fix is on it's way in #5669 🙂
