### ISSUE TITLE
🐛 BUG: `net::ERR_CONTENT_DECODING_FAILED` on Miniflare fetch

### ISSUE THREAD

**Issue by bruceharrison1984** [cloudflare/workers-sdk#5630]
### Which Cloudflare product(s) does this pertain to?

Wrangler core, Miniflare

### What version(s) of the tool(s) are you using?

3.50.0

### What version of Node are you using?

18.18.0

### What operating system and version are you using?

Windows 11

### Observed behavior
Making a request to Miniflare via the `UnstableDevServer` fetch method fails

### Expected behavior
The fetch should succeed

### Steps to reproduce
Please provide the following:
- Simply make a fetch request to Miniflare

Rolling back to v3.49.0 resolves the issue.

### Please provide a link to a minimal reproduction

https://github.com/bruceharrison1984/vite-wrangler-spa

Specifically:
https://github.com/bruceharrison1984/vite-wrangler-spa/blob/bb7df47ceb20b2afddeaedd1cafee0c46f5aa3ff/src/utils.ts#L10-L35

### Please provide any relevant error logs

![image](https://github.com/cloudflare/workers-sdk/assets/17836372/b9e0c10c-6288-409d-af99-4d6e5c069806)

**Comment by penalosa** [comment]
Could you check if this was fixed by https://github.com/cloudflare/workers-sdk/pull/5798?

**Comment by bruceharrison1984** [comment]
This has been fixed
