### ISSUE TITLE
🐛 BUG: `wrangler deploy` does not bind to configured KV namespaces

### ISSUE THREAD

**Issue by an-nguyen-codeleap** [cloudflare/workers-sdk#5634]
### Which Cloudflare product(s) does this pertain to?

KV, Wrangler core

### What version(s) of the tool(s) are you using?

3.51.0 [Wrangler]

### What version of Node are you using?

20.11.1

### What operating system and version are you using?

Mac Sonoma 14.2.1

### Observed behavior
When I run `wrangler deploy` in my worker project, the worker will be deployed and show all the bindings in console but the KV binding. All the bindings are specified in `wrangler.toml` file, a KV namespace is included.
```toml
kv_namespaces = [
  { binding = "MyKV", id = "xxx" }
]
```

### Expected behavior
My worker should connect to `MyKV` and appear in console log.

**Comment by an-nguyen-codeleap** [comment]
I found the root cause of the issue. The settings for KV bindings will no longer working if I use the syntax:
```
kv_namespaces = [
  { binding = "<BINDING_NAME1>", id = "<NAMESPACE_ID1>" },
  { binding = "<BINDING_NAME2>", id = "<NAMESPACE_ID2>" }
]
```

It works normally after I change to the syntax:
```
[[kv_namespaces]]
binding = "<BINDING_NAME1>"
id = "<NAMESPACE_ID1>"

[[kv_namespaces]]
binding = "<BINDING_NAME2>"
id = "<NAMESPACE_ID2>"
```

**Comment by marc-lassiter** [comment]
I also ran into the same issue. `npx wrangler deploy` would not push the `kv_namespace` binding up.

The formatting change posted by @an-nguyen-codeleap solved the issue.

> I found the root cause of the issue. The settings for KV bindings will no longer working if I use the syntax:
> 
> ```
> kv_namespaces = [
>   { binding = "<BINDING_NAME1>", id = "<NAMESPACE_ID1>" },
>   { binding = "<BINDING_NAME2>", id = "<NAMESPACE_ID2>" }
> ]
> ```
> 
> It works normally after I change to the syntax:
> 
> ```
> [[kv_namespaces]]
> binding = "<BINDING_NAME1>"
> id = "<NAMESPACE_ID1>"
> 
> [[kv_namespaces]]
> binding = "<BINDING_NAME2>"
> id = "<NAMESPACE_ID2>"
> ```

**Comment by robclancy** [comment]
so many docs, websites and asking ai shows the old syntax, I had a feeling it was wrong because of the `[ai]` binding but this is the only fucking place that I find the new syntax... waste of time.

**Comment by jameswoodley** [comment]
Yeah - this needs the docs updating, wasted hours on this
