### ISSUE TITLE
🚀 Feature Request: `mf.waitOnExecutionContext`, have `mf.dispose` wait on all `waitUntil`s, or bring back `Response#waitUntil()`

### ISSUE THREAD

**Issue by hansottowirtz** [cloudflare/workers-sdk#5643]
### Describe the solution

We have some old tests we want to migrate to Miniflare 3. However, `Response#waitUntil()` was removed. The following test fails, because there is no way to wait for `waitUntil`.
```ts
import { Miniflare } from "miniflare";
import { expect, it } from "vitest";

const getMf = () =>
  new Miniflare({
    script: `
  const delay = (n) => new Promise((res) => setTimeout(res, n)) ;
  export default {
    async fetch(req, env, ctx) {
      ctx.waitUntil(delay(2000))
      return new Response("ok", { status: 200 })
    }
  }`,
    modules: true,
    compatibilityDate: "2023-03-30",
  });

it("should wait for waitUntil correctly", async () => {
  const mf = getMf();
  const t1 = Date.now();
  const res = await mf.dispatchFetch("http://test");
  await mf.dispose();
  const t2 = Date.now();
  expect(res.status).toBe(200);
  expect(t2 - t1).toBeGreaterThan(2000);
});
```

**Comment by penalosa** [comment]
If possible, we'd recommend using the new Vitest integration to test your Workers: https://developers.cloudflare.com/workers/testing/vitest-integration. In particular, it [exposes a `waitOnExecutionContext()` API](https://developers.cloudflare.com/workers/testing/vitest-integration/test-apis/#events) that sounds like it's what you want here.

Would that work for your use case?

**Comment by hansottowirtz** [comment]
We have by now migrated all our tests to Vitest.
