### ISSUE TITLE
🐛 BUG: "Module cannot be synchronously required" when using @cloudflare/vitest-pool-workers

### ISSUE THREAD

**Issue by JordanFaust** [cloudflare/workers-sdk#5646]
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

0.2.0

### What version of Node are you using?

20.11.1

### What operating system and version are you using?

Nixos

### Observed behavior

Use of CJS dependencies fails within vitest-pool-workers. The example I am running into is using the launchdarkly cloudflare sdk. It has a dependency on semver which is failing to run any tests

### Expected behavior

Test to successfully run.

### Steps to reproduce

1. Check out [this branch](https://github.com/JordanFaust/clean-project/tree/vitest-launchdarkly)
2. npm install
3. npm run test

![image](https://github.com/cloudflare/workers-sdk/assets/1653499/a17652aa-c43c-430c-92fe-2798534f4164)

### Please provide a link to a minimal reproduction

https://github.com/JordanFaust/clean-project/tree/vitest-launchdarkly

### Please provide any relevant error logs

FAIL  test/bug.test.ts [ test/bug.test.ts ]
Error: Module cannot be synchronously required while it is being instantiated or evaluated. This error typically means that a CommonJS or NodeJS-Compat type module has a circular dependency on itself, and that a synchronous require() is being called while the module is being loaded.
 ❯ media/procore/clean-project/node_modules/semver/classes/range.js?mf_vitest_no_cjs_esm_shim:205:20
 ❯ media/procore/clean-project/node_modules/semver/classes/comparator.js?mf_vitest_no_cjs_esm_shim:141:15
 ❯ media/procore/clean-project/node_modules/semver/index.js?mf_vitest_no_cjs_esm_shim:29:20

**Comment by JordanFaust** [comment]
This is a reproduction of this issue on the latest release: https://github.com/cloudflare/workers-sdk/issues/5367

**Comment by penalosa** [comment]
Closing in favour https://github.com/cloudflare/workers-sdk/issues/5367
