### ISSUE TITLE
🐛 DURABLE OBJECTS BUG: NOSENTRY Invalid alarm timeout value.

### ISSUE THREAD

**Issue by jaovitubr** [cloudflare/workers-sdk#5657]
### Which Cloudflare product(s) does this pertain to?

Durable Objects

### What version(s) of the tool(s) are you using?

Wrangler 3.51.2

### What version of Node are you using?

20.11.0

### What operating system and version are you using?

Windows 11

### Observed behavior
Every time an alarm is triggered, a warning appears:

``▲ [WARNING] workerd/io/worker-entrypoint.c++:561: warning: NOSENTRY Invalid alarm timeout value. Using 15 minutes; timeout = 0ns``

### Expected behavior
It just went off without warning.

### Steps to reproduce
- ``git clone git@github.com:jaovitubr/cf-alarm-warning.git``
- ``npm install``
- ``npm start``
- go to ``http://127.0.0.1:8787``
- see console

### Please provide a link to a minimal reproduction

https://github.com/jaovitubr/cf-alarm-warning

**Comment by mhart** [comment]
This should be fixed once https://github.com/cloudflare/workerd/pull/2052 rolls out and into the next wrangler version
