### ISSUE TITLE
🐛 BUG: hacky modules detection doesn't work remarkably well in practice (pure Durable Objects project)

### ISSUE THREAD

**Issue by punkeel** [cloudflare/workers-sdk#5663]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.51.2

### What operating system and version are you using?

MacOS

### Observed behavior
wrangler thinks a pure-DO project uses Service Worker syntax, even when it clearly uses `import`/`export`. This breaks during the upload, especially when trying to use features that require Module Workers.

```console
npx wrangler@latest versions upload --experimental-gradual-rollouts
 ⛅️ wrangler 3.51.2
-------------------
▲ [WARNING] The entrypoint index.ts has exports like an ES Module, but hasn't defined a default export like a module worker normally would. Building the worker using "service-worker" format...


▲ [WARNING] The `usage_model` defined in wrangler.toml is deprecated and no longer used. Visit our developer docs for details: https://developers.cloudflare.com/workers/wrangler/configuration/#usage-model


Total Upload: 0.64 KiB / gzip: 0.37 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/b03830d9ae163ab8ac4a868e4ddd0e84/workers/scripts/lala/versions) failed.

  Version upload failed. You attempted to upload a Service Worker syntax script to the version
  upload API, which only supports ES Modules. See
  https://developers.cloudflare.com/workers/reference/migrate-to-module-workers/ for migration
  instructions. [code: 10216]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

```

### Expected behavior
```js
/**
 * A function to "guess" the type of worker.
 * We do this by running a lightweight build of the actual script,
 * and looking at the meta-file generated by esbuild. If it has a default
 * export (or really, any exports), that means it's a "modules" worker.
 * Else, it's a "service-worker" worker. This seems hacky, but works remarkably
 * well in practice.
 */
```

Side note: this is the second time I encounter a bug with this logic (#2754/#2767) - reading "but works remarkably well in practice" when it doesn't is still as infuriating as it was the first time! :-)

This still can't be overridden by the user (who so happens to know their own worker, without having to guess):

```console
$ npx wrangler@latest versions upload --experimental-gradual-rollouts --format modules
 ⛅️ wrangler 3.51.2
-------------------
▲ [WARNING] The entrypoint index.ts has exports like an ES Module, but hasn't defined a default export like a module worker normally would. Building the worker using "service-worker" format...



✘ [ERROR] You configured this worker to be 'modules', but the file you are trying to build doesn't export a handler. Please pass `--format service-worker`, or simply remove the configuration.


🪵  Logs were written to "/Users/maxime/.wrangler/logs/wrangler-2024-04-19_10-42-32_425.log"
```

### Steps to reproduce
1. Create project, with a Durable Object (no Workers, no `fetch`)
2. Try to upload it with wrangler, eg with `npx wrangler@latest versions upload --experimental-gradual-rollouts`

### Please provide a link to a minimal reproduction

https://github.com/punkeel/repro-5629/blob/maxime/wrangler/index.ts

**Comment by penalosa** [comment]
We can definitely explore improvements to the messaging here, but in this case I think it's roughly correct. It's not possible to have a pure-DO project—you also need to export a worker handler.

**Comment by punkeel** [comment]
From what I can tell, having a pure Durable Object project works reliably well in practice


> you also need to export a worker handler
Looks like a `export default {}` does the trick - is that what you mean here? #5487 may be related then. If so, that code is really dumb-looking and counter intuitive...

**Comment by penalosa** [comment]
Ah—my understanding may be outdated here then. @GregBrimble @Frederik-Baetens could you confirm whether uploading a DurableObject without an attached worker is expected to work now?

**Comment by GregBrimble** [comment]
We still require a Worker (default export) piece, but are considering removing this check at some point in the future to support uploading only named entrypoint(s). This _may_ mean we also support uploading only a Durable Object, but that's not yet been discussed. What's the use-case? For a Pages project?

**Comment by KianNH** [comment]
I've also encountered this issue when using JS RPC named entrypoints.

The example in the documentation (https://developers.cloudflare.com/workers/runtime-apis/rpc/#class-instances) has an exported fetch handler which seems to exist just to satisfy this bug.

```ts
// worker.ts
import { WorkerEntrypoint } from "cloudflare:workers";

export class Worker extends WorkerEntrypoint {
  async fetch() { return new Response("Hello from Worker B"); }

  add(a: number, b: number) { return a + b; }
}

// index.ts
export { Worker } from "./worker"
// add `export default {}` here to fix the bug
```

This code will fail, since the lack of a default export makes Wrangler think this is a Service Worker. It's easy to miss the warning log that would guide the user towards the issue:

```
 ⛅️ wrangler 3.52.0
-------------------
▲ [WARNING] The entrypoint src/index.ts has exports like an ES Module, but hasn't defined a default export like a module worker normally would. Building the worker using "service-worker" format...


⎔ Starting local server...
✘ [ERROR] service core:user:test-a: Uncaught Error: Dynamic require of "cloudflare:workers" is not supported

    at null.<anonymous> (core:user:test-a:8:11)
    at null.<anonymous> (core:user:test-a:274:35)
    at null.<anonymous> (core:user:test-a:283:3)


✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.


[wrangler:inf] Ready on http://localhost:8787
```

This is mainly an issue for Workers that will contain multiple named entrypoints, which is likely to become more popular if/when Service Bindings stop charging for requests and a microservice model becomes more feasible for users.

This was originally pointed out by a user in the community Discord: https://discord.com/channels/595317990191398933/779390076219686943/1233803440631578644

**Comment by penalosa** [comment]
I'm going to close this in favour of https://github.com/cloudflare/workers-sdk/issues/5487, which tracks improving the messaging here.

While Wrangler is incorrect to assume your Worker is in the service-worker format in this case, adding a default export is required for this to work when uploaded to the API. Without a default export, the API call will fail with `The uploaded script has no registered event handlers. [code: 10068]` (having said that, this is arguably a pretty confusing error message). So while Wrangler is making this confusing, the user-facing behaviour is correct to some extent (in that the upload will fail anyway, even if Wrangler didn't have this detection bug).

It seems like we have several cases where it would be helpful to loosen up the RPC upload validation, which we'd then have to account for in Wrangler:
- Uploading a `WorkerEntrypoint` _without_ a `fetch()` (or other) handler
- Uploading a Worker with no default export—only a named handler

 @GregBrimble do you know if those are planned?

**Comment by GregBrimble** [comment]
Both planned, but no timeline as of yet.

**Comment by JustFly1984** [comment]
Hope it will help to somebody:

I was burned by omitting fetch method on RPC worker class extended from WorkerEntrypoint. An error is "The uploaded script has no registered event handlers".
wrangler.toml "format" setting is not supported anymore, class is exported with export default.
I'm using the typescript, and while addding fetch method, it complains that I have to use overrides keyword, cos fetch is already defined on parent WorkerEntrypoint class.
Is it intentional or a bug?
