### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by SnowyThinker** [cloudflare/workers-sdk#5707]
### Which Cloudflare product(s) does this pertain to?

KV

### What version(s) of the tool(s) are you using?

wrangler 3.8.0 (update available 3.52.0)

### What version of Node are you using?

v18.16.0

### What operating system and version are you using?

Mac

### Observed behavior
Error while publish

### Expected behavior
Please describe.

### Steps to reproduce
Skipped uploading 34,727 existing assets.
↗️  Done syncing assets
Total Upload: 5446.84 KiB / gzip: 1281.43 KiB
▲ [WARNING] We recommend keeping your script less than 1MiB (1024 KiB) after gzip. Exceeding past this can affect cold start time

▲ [WARNING] Here are the 5 largest dependencies included in your script:

  - node_modules/mime/types/other.js - 26.82 KiB
  - node_modules/@cloudflare/kv-asset-handler/dist/index.js - 10.16 KiB
  - node_modules/mime/types/standard.js - 10.12 KiB
  - node_modules/mime/Mime.js - 2.06 KiB
  - node_modules/@cloudflare/kv-asset-handler/dist/types.js - 1.27 KiB
  If these are unnecessary, consider removing them

✘ [ERROR] A request to the Cloudflare API (/accounts/xxxxx/workers/scripts/xx) failed.

  workers.api.error.script_too_large [code: 10027]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

**Comment by penalosa** [comment]
This error means that your Worker bundle is too large. You can refer to https://developers.cloudflare.com/workers/platform/limits/#worker-size for more details on the size limit.
