### ISSUE TITLE
🐛 BUG: Unable to deploy existing project with wrangler or C3

### ISSUE THREAD

**Issue by evolgs** [cloudflare/workers-sdk#5708]
### Which Cloudflare product(s) does this pertain to?

C3, Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

3.52.0 [Wrangler], 2.21.0 [C3]

### What version of Node are you using?

20.4.0

### What operating system and version are you using?

Windows 11, WSL

### Observed behavior
I have an existing folder which I need to automate in deploy to cloudflare workers. `CLOUDFLARE_ACCOUNT_ID` and `CLOUDFLARE_API_TOKEN` are specified in the CLI. Unfortunately it is impossible to deploy the project. 

When using `wrangler`, it will complain that an existing wrangler.toml exist and this error is produced:

```
set CLOUDFLARE_ACCOUNT_ID="..." && set CLOUDFLARE_API_TOKEN="..." && npx wrangler init -y
 ⛅️ wrangler 3.52.0
-------------------
Using npm as package manager, as there is already a package-lock.json file.
▲ [WARNING] wrangler.toml already exists!


× Do you want to continue initializing this project?
```

The extra question is breaking the automation. There should be no questions, I already supplied `-y`.

Or when trying to deploy it will return this:

```
set CLOUDFLARE_ACCOUNT_ID="..." && set CLOUDFLARE_API_TOKEN="..." && npx wrangler deploy
 ⛅️ wrangler 3.52.0
-------------------

X [ERROR] A request to the Cloudflare API (/accounts/.../workers/services/...) failed.

  Could not route to /accounts/.../workers/services/..., perhaps your object identifier is invalid? [code: 7003]
  No route for that URI [code: 7000]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

```

Also tried:

```
set CLOUDFLARE_ACCOUNT_ID="..." && set CLOUDFLARE_API_TOKEN="..." && npx wrangler init --yes
 ⛅️ wrangler 3.52.0
-------------------
Using npm as package manager, as there is already a package-lock.json file.
▲ [WARNING] The `init` command is no longer supported. Please use `npm create cloudflare\@2.5.0 -y -- --wrangler-defaults` instead.

  The `init` command will be removed in a future version.


Running `npm create cloudflare\@2.5.0 -y -- --wrangler-defaults`...


using create-cloudflare version 2.21.0

╭ Create an application with Cloudflare Step 1 of 3
│
╰ In which directory do you want to create your application? also used as application name
  ./flat-mouse-c959
│
╰  X  Operation cancelled.
```

I've tried on both windows and WSL to deploy the project, it's just impossible. And the API only allows you to PUT raw script; if you have dependencies you must use wrangler to bundle it.

### Expected behavior
Go into your folder... run a command and deploy it. No extra questions, no bonanza. Simple and straightforward.

### Steps to reproduce
Please provide the following:
- I cannot provide the code since it's confidential
- My `wrangler.toml` is literally empty, it just has the project name and `compatibility_date`
- Not using local dev commands, the project is ready to be deployed
- N/A

I will not provide a git repo for you to clone and test, it's not possible. To "reproduce" it is enough to:

- Copy an existing project
- Try to deploy it with cloudflare account id and api token like I did above

Thanks

**Comment by penalosa** [comment]
Unfortunately there will be a limited amount of debugging we can do without a minimal reproduction—would you be able to put one together that doesn't include confidential code and that reproduces this bug?

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to comment with more details and we can investigate further.
