### ISSUE TITLE
🐛 BUG:  Please use  "pages_build_output_dir" to specify the directory of static files to upload

### ISSUE THREAD

**Issue by kurdin** [cloudflare/workers-sdk#5711]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.52.0 wrangler

### What version of Node are you using?

20.x

### What operating system and version are you using?

Mac Latest

### Observed behavior
When I run 
`$ wrangler pages deploy pages/`
I see the message

```
[WARNING] Pages now has wrangler.toml support.
  We detected a configuration file at
   wrangler.toml but it is missing the
  "pages_build_output_dir" field, required by Pages.
  If you would like to use this configuration file to deploy your project, please use
  "pages_build_output_dir" to specify the directory of static files to upload.
  Ignoring configuration file for now, and proceeding with project deploy.
  ```
  in result all configuration in `wrangler.toml` is ignored on deployment
  but I did specify `pages/` directory using cli 

### Expected behavior
Wrangler should not complain about missing `pages_build_output_dir` if that output directory provided with cli command `wrangler pages deploy pages/` , or at least it should not ignore all other configuration settings from `wrangler.toml` file on deployment.

If I added `pages_build_output_dir` to `wrangler.toml` this message will go away but I could not use cli command `wrangler pages dev --proxy=5173 -- vite --port=5173 --strictPort` in local development env

### Please provide a link to a minimal reproduction

https://github.com/kurdin/wrangler-pages-deploy-output-dir

**Comment by penalosa** [comment]
This is expected behaviour: `pages_build_output_dir` is required to use `wrangler.toml` for deploying your Pages project. It sounds like you're having an issue with `pages dev` with that field included though, which could be a bug. Could you link a reproduction for the behaviour you're seeing, and clarify what behaviour you expected?

**Comment by kurdin** [comment]
@penalosa  Thank you for quick response. 
here is the repo you can try https://github.com/kurdin/wrangler-pages-deploy-output-dir

When I run 
`wrangler pages deploy pages`  I specified  `pages_build_output_dir` using cli `.. deploy pages` I should not have an message `We detected a configuration file at ... the "pages_build_output_dir" field, required by Pages.`
even if this is a warning why would wrangler saying? `Ignoring configuration file for now, and proceeding with project deploy.`  I have some other settings in configuration file that I need to deploy for functions, db bindings, etc. 
It does not make sense. 

Ok, let say I remove deployment dir from cli command :
`wrangler pages deploy`

Now I see this message 

```
▲ [WARNING] Pages now has wrangler.toml support.

  We detected a configuration file at wrangler.toml but it is missing
  the "pages_build_output_dir" field, required by Pages.
  If you would like to use this configuration file to deploy your project, please use
  "pages_build_output_dir" to specify the directory of static files to upload.
  Ignoring configuration file for now, and proceeding with project deploy.
```
and error
```
✘ [ERROR] Must specify a directory of assets to deploy. Please specify the [<directory>] argument in the `pages deploy` command, or configure `pages_build_output_dir` in your `wrangler.toml` configuration file.
```

I think this message is saying it correctly
Please specify the [<directory>] argument in the `pages deploy` command, **__or___** configure `pages_build_output_dir` in your `wrangler.toml` configuration file.

Correct behavior should be that you can set `pages_build_output_dir` from `wrangler.toml`  OR  specify it with in wrangler cli.

**Comment by penalosa** [comment]
Thanks for the followup and clarification. `pages_build_output_dir` is required to use wrangler.toml for deploying your Pages project, and just specifying the directory as a command line argument won't work. This was intentional, to make sure that users were explicitly opting in to the new `wrangler.toml` behaviour.

**Comment by jaypatrick** [comment]
Ran into this same issue today, caused a cascading set of failures that has taken us a couple of hours to clean up (our CI process treats warnings as errors, as it should.)
