### ISSUE TITLE
🐛 BUG: Invalid define value (must be an entity name or valid JSON syntax)

### ISSUE THREAD

**Issue by flexchar** [cloudflare/workers-sdk#5720]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.52.0

### What version of Node are you using?

21

### What operating system and version are you using?

Mac

### Describe the Bug

I've reviewed the following actions and can not figure out why my input keeps getting rejected.

- https://github.com/cloudflare/workers-sdk/pull/1297
- https://github.com/cloudflare/cloudflare-docs/issues/6022
- https://developers.cloudflare.com/workers/wrangler/commands#deploy

### Observed behavior
Work. This is going to be huge in getting Sentry work seamlessly with source map upload.

### Expected behavior
```bash
 ⛅️ wrangler 3.52.0
-------------------

✘ [ERROR] Invalid define value (must be an entity name or valid JSON syntax): abc123


✘ [ERROR] Build failed with 1 error:

  error: Invalid define value (must be an entity name or valid JSON syntax): abc123


🪵  Logs were written to ...
```

### Steps to reproduce
Neither of these work:

```bash
export SENTRY_RELEASE=$(git rev-parse --short HEAD)
npx wrangler deploy src/routes.ts --define SENTRY_RELEASE:$SENTRY_RELEASE --outdir dist --dry-run
npx wrangler deploy src/routes.ts --define SENTRY_RELEASE:"$SENTRY_RELEASE" --outdir dist --dry-run

npx wrangler deploy src/routes.ts --define SENTRY_RELEASE:'$(git rev-parse HEAD)' --outdir dist --dry-run
npx wrangler deploy src/routes.ts --define SENTRY_RELEASE:$(git rev-parse HEAD) --outdir dist --dry-run
```

This is exactly what documentation says thou.

**Comment by KianNH** [comment]
You want `--define SENTRY_RELEASE:'"$SENTRY_RELEASE"'`

**Comment by flexchar** [comment]
Damn, that was neatly hidden. :) How about evaluating the shell as written in the docs? It seems that if I double wrap, I get the exact shell output. 

As in, how to get this working?
`npx wrangler deploy src/routes.ts --define SENTRY_RELEASE:'"$(git rev-parse HEAD)"' --outdir dist --dry-run`

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to provide a reproduction repo that demonstrates the issue?

Running `npx wrangler deploy src/routes.ts --define SENTRY_RELEASE:$(git rev-parse HEAD) --outdir dist --dry-run` seems to work for me.

**Comment by flexchar** [comment]
Of course, @penalosa, I am very curious why it is working for you but not for me. 

Here is the reproducible with the fresh init:
https://github.com/flexchar/workers-issue-5720 


hope that helps!

**Comment by flexchar** [comment]
I know you guys are very busy, @penalosa and @KianNH, and I respect that. Nevertheless I wanted to give a little bump up here hoping you would find a chance for this in your near future sprints. 

This would save the users of Workers Platform a lot of time enabling the source maps to be published for tools like Sentry. Currently debugging deployed (and minified) workers is like debugging a black box.

**Comment by penalosa** [comment]
@flexchar It looks like this only works without quotes when the commit hash starts with an alphabetic character (if it starts with a number esbuild gets confused). I think this is why it was working for me initially.

Could you try the following script? That should ensure that the variable is treated as a string.

```json
"scripts": {
    "test": "wrangler deploy src/index.ts --define \"SENTRY_RELEASE:'$(git rev-parse HEAD)'\" --outdir dist --dry-run"
  }
```

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to comment with more details and we can investigate further.
