### ISSUE TITLE
Code debugging using breakpoints

### ISSUE THREAD

**Issue by gilm123** [cloudflare/workers-sdk#573]
### 💡 Feature request
A way to locally debug the code

#### Overview and problem statement
In every reference to the word "debug" in the documentation, i can only see ways to debug with logs.
i find myself adding a log after a log, while i just need a breakpoint.

we are developing using wrangler dev with a result of a typescript build with webpack.

**Comment by ayrtonvwf** [comment]
Hello. Now that wrangler using workerd locally, is that easier to implement?

**Comment by ayrtonvwf** [comment]
With this PR merged it seems to be possible:

https://github.com/cloudflare/workerd/pull/17

**Comment by penalosa** [comment]
Unfortunately this isn't ready yet (that PR doesn't fully support what we'd need). It's on our roadmap though, and it's definitely something we're looking to fix in the future.

**Comment by penalosa** [comment]
Closing this in favour of https://github.com/cloudflare/workerd/issues/371, which tracks the work needed here for breakpoint debugging support in local mode.

**Comment by swyxio** [comment]
saving people some time from reading thru a bunch of the above - the vscode + wrangler instructions you need are here. https://blog.cloudflare.com/debugging-cloudflare-workers#breakpoints
