### ISSUE TITLE
🐛 BUG: `@cloudflare/vitest-pool-workers@0.2.4` is missing `dist/` folder

### ISSUE THREAD

**Issue by nvie** [cloudflare/workers-sdk#5736]
### Which Cloudflare product(s) does this pertain to?

Other

### What version(s) of the tool(s) are you using?

@cloudflare/vitest-pool-workers@0.2.4

### What operating system and version are you using?

Mac Sonoma 14.4.2

### Observed behavior
The latest version on NPM is missing a `dist/` folder: https://www.npmjs.com/package/@cloudflare/vitest-pool-workers?activeTab=code

### Expected behavior
It has a `dist/` folder.

### Steps to reproduce
`npm i @cloudflare/vitest-pool-workers@0.2.4`

**Comment by penalosa** [comment]
Thanks for flagging this! This was fixed in https://www.npmjs.com/package/@cloudflare/vitest-pool-workers/v/0.2.5
