### ISSUE TITLE
🐛 BUG:wrangler d1 execute dev --file=db/schema.sql使用时报错但已经有数据库 路径也没错 X [ERROR] Couldn't find a D1 DB with the name or binding 'dev' in wrangler.toml.

### ISSUE THREAD

**Issue by admin191** [cloudflare/workers-sdk#5751]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

wrangler

### What version of Node are you using?

3.53.1

### What operating system and version are you using?

Windows11

### Describe the Bug

wrangler d1 execute dev --file=db/schema.sql write in sql file in My D1 .I'm got D1 name is dev But Error 
![image](https://github.com/cloudflare/workers-sdk/assets/111217383/29e74185-1100-4630-80c1-b2b9be93bcba)

### Please provide any relevant error logs

Log:
--- 2024-05-03T03:26:27.541Z debug
🪵  Writing logs to "C:\Users\admin123\AppData\Roaming\xdg.config\.wrangler\logs\wrangler-2024-05-03_03-26-27_363.log"
---

ERROR:⛅️ wrangler 3.53.1
-------------------
🌀 Mapping SQL input into an array of statements

X [ERROR] Couldn't find a D1 DB with the name or binding 'dev' in wrangler.toml.

🪵  Logs were written to "C:\Users\admin123\AppData\Roaming\xdg.config\.wrangler\logs\wrangler-2024-05-03_03-26-27_363.log"

**Comment by euijinkk** [comment]
same issue only for `--local`, not `--remote`

**Comment by FraBle** [comment]
I encountered the same issue as well. Upgrading wrangler to `3.55.0` did not resolve it.

**Comment by FraBle** [comment]
I found my mistake: `database_id=""`. This needs to have a value otherwise [this expression](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/d1/utils.ts#L14) is false.

```toml
[[d1_databases]]
...
database_id = ""
...
```

**Comment by penalosa** [comment]
@admin191 This is because D1 defaults to acting on local databases, while your `dev` database is defined remotely. Adding the `--remote` flag should allow you to run SQL against the remote database
