### ISSUE TITLE
🐛 BUG: D1_ERROR: Wrong number of parameter bindings for SQL query

### ISSUE THREAD

**Issue by chengfengfengwang** [cloudflare/workers-sdk#5765]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3.53.1[wrangler]

### What version of Node are you using?

v20.12.2

### What operating system and version are you using?

Mac OS 13.4.1 (c) (22F770820d)

### Describe the Bug

```
 const param: { id: string; remark: string } = await c.req.json();
  console.log(param); // { id: '1', remark: 'aaa' }

  const { success } = await c.env.DB.prepare(
    `update test set remark=? where id=?1`
  )
    .bind(param.remark, param.id)
    .run();
```
get Error
```
✘ [ERROR] Error: D1_ERROR: Wrong number of parameter bindings for SQL query.
```

**Comment by osaton** [comment]
I don't think you can mix anonymous and ordered parameters. Try:

```ts
const { success } = await c.env.DB.prepare(
    `update test set remark=?1 where id=?2`
  )
    .bind(param.remark, param.id)
    .run();
```

or

```ts
const { success } = await c.env.DB.prepare(
    `update test set remark=? where id=?`
  )
    .bind(param.remark, param.id)
    .run();
```

**Comment by chengfengfengwang** [comment]
> I don't think you can mix anonymous and ordered parameters. Try:
> 
> ```ts
> const { success } = await c.env.DB.prepare(
>     `update test set remark=?1 where id=?2`
>   )
>     .bind(param.remark, param.id)
>     .run();
> ```
> 
> or
> 
> ```ts
> const { success } = await c.env.DB.prepare(
>     `update test set remark=? where id=?`
>   )
>     .bind(param.remark, param.id)
>     .run();
> ```

sorry... It's my fault
