### ISSUE TITLE
🚀 Feature Request: Override `http://placeholder` url in miniflare fetch proxy

### ISSUE THREAD

**Issue by bruceharrison1984** [cloudflare/workers-sdk#5772]
### Describe the solution

I'm not exactly sure how this could be done, but when trying to utilize something like Hono OpenAPI from Miniflare, the context object results in a host-relative incorrect URL:

```ts
apiV1.doc('/doc', (ctx) => ({
  openapi: '3.1.0',
  info: {
    version: '1.0.0',
    title: 'Torch',
  },
  servers: [{ url: `${new URL(ctx.req.url).origin}/api/v1` }],
}));
```

![image](https://github.com/cloudflare/workers-sdk/assets/17836372/7900258f-ca23-49c0-93bd-61615997eca7)

This isn't an issue in Production because the correct URL is present in the request. In the case of local development, we don't have access to the true hostname from the context, so there isn't any way to fixup this URL because we don't know what the original hostname was supposed to be.

**Comment by penalosa** [comment]
Does this happen with Wrangler, or when running Miniflare directly?

**Comment by bruceharrison1984** [comment]
This is when running Miniflare directly via `unstable_dev` for use in a Vite plugin.

**Comment by penalosa** [comment]
`unstable_dev` only add on `http://placeholder` if the URL passed to the `fetch()` function is not absolute. Passing in an absolute URL (including a host) should make this work as expected.

If that doesn't work, would you be able to put together a minimal reproduction with just `unstable_dev` (omitting Vite) and we can investigate further?

**Comment by bruceharrison1984** [comment]
@penalosa 

I ended up fixing my issue by doing what you had suggested. I'm not sure if there is any other way to make it work!
