### ISSUE TITLE
🐛 BUG: `fetchMock` does not intercept `fetch` in a service binding worker

### ISSUE THREAD

**Issue by thiskevinwang** [cloudflare/workers-sdk#5789]
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

3.53.1 [wrangler], 0.2.6 [@cloudflare/vitest-pool-workers], 1.3.0 [vitest]

### What version of Node are you using?

20.11.0

### What operating system and version are you using?

Mac Ventura 13.5

### Observed behavior

`fetchMock` does not appear to intercept `fetch` calls that are internal to _another_ worker that is built and bound as a service binding.

### Expected behavior

I'd expect `fetchMock` to intercept `fetch` calls in a service binding worker.

### Steps to reproduce

1. Create worker A
2. Create worker B with entrypoint "Foo"
3. In worker B, call `fetch(SOMETHING)`
4. Create a test for worker A
5. Build worker B and set as service binding on worker A
6. From test for worker A, call `fetchMock` and intercept the previous SOMETHING
7. `activate()`, `disableNetConnect()`. Assert no pending mocks
8. Call code to test Worker A-to-B integration
9. Observe 1 outstanding interceptor
10. Observe a "Network connection lost" error from the `fetch` call.

See: https://github.com/thiskevinwang/workers-sdk-5789

### Please provide a link to a minimal reproduction

https://github.com/thiskevinwang/workers-sdk-5789

**Comment by thiskevinwang** [comment]
It looks like `outboundService` is one means to mock this class of fetches, but you're slightly bound to a static implementation, so it's not flexible.
- https://github.com/cloudflare/workers-sdk/blob/9b4af8a59bc75ed494dd752c0a7007dbacf75e51/fixtures/vitest-pool-workers-examples/multiple-workers/vitest.config.ts#L87

I also see a mutually exclusive `fetchMock` option, but it's unclear how you satisfy this field (assuming a `vitest.config.ts` file)
- https://github.com/cloudflare/workers-sdk/tree/main/packages/miniflare#interface-workeroptions

**Comment by thiskevinwang** [comment]
Update: added repro-repo https://github.com/thiskevinwang/workers-sdk-5789

**Comment by penalosa** [comment]
This is expected: `fetchMock()` only applies to the current Worker:

> Declarative interface for mocking outbound fetch() requests. Deactivated by default and reset before running each test file. Refer to [undici’s MockAgent documentation](https://undici.nodejs.org/#/docs/api/MockAgent)
for more information. Note this only mocks fetch() requests for the current test runner Worker. Auxiliary Workers should mock fetch()es using the Miniflare fetchMock/outboundService options. Refer to [Configuration](https://developers.cloudflare.com/workers/testing/vitest-integration/configuration/#workerspooloptions) for more information.

You should be able to use Miniflare's `fetchMock` for more extensive mocking, using the `poolOptions.workers.miniflare.fetchMock` config option in `vitest.config.ts`, which is documented at https://miniflare.dev/core/standards#mocking-outbound-fetch-requests

**Comment by thiskevinwang** [comment]
Coming back here to report that I've found a pretty convenient workaround! 
AFAICT from my testing, this allows `fetchMock` to intercept bound workers' `fetch` calls. This is great since it I can continue to use `fetchMock`'s pleasant API, colocate those mocks/interceptors with the rest of my test code, and effectively avoid the less-easy-to-discover-and-configure miniflare configs.

```ts
import { env, fetchMock, SELF } from 'cloudflare:test';
import { afterEach, beforeAll, describe, expect, it, vi } from 'vitest';

//...

    beforeAll(() => {
      vi.spyOn(env.MY_WORKER_BINDING, 'fetch').mockImplementation(global.fetch);
      fetchMock.activate();
      fetchMock.disableNetConnect();
    });

```
