### ISSUE TITLE
🚀 Feature Request: Provide `--latest-version` flag to allow `wrangler versions deploy` to deploy latest worker version

### ISSUE THREAD

**Issue by deasydoesit** [cloudflare/workers-sdk#5799]
### Describe the solution

I'm using wrangler `3.55.0` in the context of a CI/CD pipeline in Github Actions.

When a new git tag gets created, I'm trying to perform the following:

(1) Create new Worker version via `wrangler versions upload` for the git tag
(2) Deploy the newly created Worker version via `wrangler versions  deploy`

However, I'm finding it clunky to do so. 

From my understanding, `wrangler versions deploy` doesn't offer a flag for deploying a "latest" version, so you need to parse the output of `wrangler versions upload` which is in a generic text format as there's no current option for structured output via JSON.

**Comment by RamIdeas** [comment]
Hi @deasydoesit 

There is also a `wrangler versions list` command which has a `--json` option

For your use-case, you can try:
```sh
$ wrangler versions upload --x-versions
$ LATEST_VERSION_ID="${wrangler versions list --json --x-versions | jq '.[0].id'}"
$ wrangler versions deploy --x-versions "$LATEST_VERSION_ID@100%" -y
```

which should deploy your latest version to 100%

It should also be simple to adapt the above to deploy more than one version with split traffic levels (which we expect to be the more common scenario)

**Comment by petebacondarwin** [comment]
Closing as this is supported by using the commands given above.
