### ISSUE TITLE
🐛 BUG: Durable Object API response data is in console visible

### ISSUE THREAD

**Issue by rameardo** [cloudflare/workers-sdk#5802]
### Which Cloudflare product(s) does this pertain to?

Other

### What version(s) of the tool(s) are you using?

3.55.0 [Wrangler]

### What version of Node are you using?

20.10.0

### What operating system and version are you using?

Window 10

### Observed behavior
I wanted to express my appreciation for Cloudflare Workers—it's been incredibly helpful for our online work and business, offering speed and efficiency. However, I noticed a minor detail during deployment that I thought I should bring to your attention.

When deploying a Worker containing a Durable Object, I've observed that information about these objects is displayed in the console. While I understand this might be useful for debugging purposes, it seems unintentional and could potentially be a privacy concern.

I wanted to report this observation as a contribution to the community. Perhaps it was an oversight that this information is not hidden during deployment.

Thank you for your attention to this matter, and keep up the great work with Cloudflare Workers!

### Expected behavior
Hide Durable Object API Information/response from console

Cloudflare Team, You are Amazing <3

### Please provide any relevant error logs

> wrangler deploy -c wrangler.toml --env production

 ⛅️ wrangler 3.55.0
-------------------
Your worker has access to the following bindings:
- Durable Objects:
  - ************
  - ************
- KV Namespaces:
  - ************
  - ************
  -************
  -************
  - ************
- Queues:
  - ************
  -************
- R2 Buckets:
  - ************
  - ************
  - ************
- Services:
  - ************- production
  - S************ - production
  - ************ - production
- Vars:
  - ************
Total Upload: 1338.91 KiB / gzip: 161.10 KiB
Uploaded app (8.10 sec)
{
  **** (the info of my durable object, i think fetched from cf api)
}
{
  **** (the info of my durable object, i think fetched from cf api)
}
{
  **** (the info of my durable object, i think fetched from cf api)
}
Published app (9.24 sec)
  https://****.workers.dev
  Producer for *********
  Producer for ***********
  Consumer for *********
  Consumer for ***********
  Consumer for ****************
Current Deployment ID: ******************
Current Version ID: ******************

Note: Deployment ID has been renamed to Version ID. Deployment ID is present to maintain compatibility with the previous behavior of this command. This output will change in a future version of Wrangler. To learn more visit: https://developers.cloudflare.com/workers/configuration/versions-and-deployments

**Comment by RamIdeas** [comment]
I'm not sure this was an oversight that this information is not hidden during deployment. Can you explain further what specific information you think shouldn't be visible?

**Comment by rameardo** [comment]
i don't see it any more. this was in version 3.55.0. but thanks for your reply i will close this ticket.
