### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by BrandonStudio** [cloudflare/workers-sdk#5817]
### Which Cloudflare product(s) does this pertain to?

Other

### What version(s) of the tool(s) are you using?

AI Gateway (Azure OpenAI)

### What operating system and version are you using?

Windows

### Describe the Bug

AI Gateway for Azure OpenAI does not provide Access-Control-Allow-Headers header for perflight, resulting in following error:
```
... has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response
```

**Comment by penalosa** [comment]
Closing for now, since this is unrelated to workers-sdk and is being tracked internally by the AI Gateway team ([internal ref](https://cflare.co/ai-gateway-azure)). cc @G4brym
