### ISSUE TITLE
🐛 BUG:  [ERROR] workerd/jsg/_virtual_includes/jsg/workerd/jsg/modules.h:443: warning: NOSENTRY Worker using multiple modules in a single bundle.

### ISSUE THREAD

**Issue by thanhlq** [cloudflare/workers-sdk#5879]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

3.57.0 [Wrangler]

### What version of Node are you using?

20.11.0

### What operating system and version are you using?

Ubuntu 22.04

### Observed behavior

When update wrangler to v3.57.0, when preview or deploy nextjs site, I got this error:

⎔ Reloading local server...
Parsed 1 valid header rule.
✘ [ERROR] workerd/jsg/_virtual_includes/jsg/workerd/jsg/modules.h:443: warning: NOSENTRY Worker using multiple modules in a single bundle.

-> and the when access the page I got: 500 internal server error

### Expected behavior
No error like v3.55.0

**Comment by jikyu** [comment]
Running into same error when running tests with `vitest-pool-worker`

**Comment by Solomonic** [comment]
same here. Error occurred for me after upgrading to wrangler `3.57.1`
```
 workerd/jsg/_virtual_includes/jsg/workerd/jsg/modules.h:443: warning: NOSENTRY Worker using multiple modules in a single bundle.
```

**Workaround for now**: Downgrade wrangler to `3.55.0` (version `3.56.0` also breaks for me, so the issue was introduced there)

**Comment by nihaopaul** [comment]
same error, @Solomonic  - i downgraded but functions dont run, are you able to run them?

**Comment by Solomonic** [comment]
> same error, @Solomonic - i downgraded but functions dont run, are you able to run them?

@nihaopaul For me it works as before the wrangler upgrade. To which functions are you referring? I may test that.

**Comment by nihaopaul** [comment]
@Solomonic  - running any function put into the /functions/ folder. i'm using astro, seems the documentation is misleading (read: user error)

**Comment by EskelCz** [comment]
Downgrade doesn't help, for Astro anyway.

> @Solomonic - running any function put into the /functions/ folder. i'm using astro, seems the documentation is misleading (read: user error)
What do you mean? Did you manage to solve it?

**Comment by penalosa** [comment]
This was resolved in https://github.com/cloudflare/workerd/pull/2126, and will be released in Wrangler within the next week or so.

However, it's worth noting that this was just erroneous logging, and shouldn't have caused any behavioural errors.
