### ISSUE TITLE
🐛 BUG: Regression with waitUntil in wrangler@3.50.0

### ISSUE THREAD

**Issue by ericmatthys** [cloudflare/workers-sdk#5897]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.50.0 Wrangler

### What version of Node are you using?

18.16.0

### What operating system and version are you using?

Mac Sonoma 14.5

### Observed behavior

Within a Pages Function, I am using `context.waitUntil` and passing in a promise from a function that makes several requests in a loop.

```tsx
context.waitUntil(fetchAhead(context, url));
```

```tsx
async function fetchAhead(context, initialUrl) {
  let nextUrl = initialUrl;

  while (nextUrl) {
    try {
      const response = await fetch(nextUrl);

      if (response.ok) {
        const data = await response.json();
        nextUrl = data.nextUrl;
      } else {
        nextUrl = undefined;
      }
    } catch (error) {
      nextUrl = undefined;
    }
  }
}

```

Starting with wrangler@3.50.0 and still with 3.57.1, when running the server with `wrangler pages dev`, the while loop is interrupted after its first fetch and it does not continue to fetch ahead in the background.

### Expected behavior

In wrangler@3.49.0, the while loop is not interrupted and all urls are appropriately fetched in the background after a response is returned.

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suit on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to provide a minimal reproduction?

**Comment by ericmatthys** [comment]
I'm having difficulties reproducing it outside of the larger app. I'll have to spend more time with it next week to try to narrow in on any differences.
