### ISSUE TITLE
bug;Can't set compatibility date in the future: 2024-06-05 (Code: 10021)

### ISSUE THREAD

**Issue by Yzz2023** [cloudflare/workers-sdk#5966]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms, Constellation, Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

web

### What version of Node are you using?

不知道

### What operating system and version are you using?

win11

### Observed behavior
Please describe.

### Expected behavior
Please describe.

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suit on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

### Please provide any relevant error logs

Can't set compatibility date in the future: 2024-06-05 (Code: 10021)
![图片1](https://github.com/cloudflare/workers-sdk/assets/133849175/05f86676-3cf4-4693-b7d7-b48e1a255284)

**Comment by penalosa** [comment]
@1000hz could you have a look at this? I suspect this is a regression somewhere to use local time rather than UTC time for the initial compatibility date

**Comment by 1000hz** [comment]
This issue has been fixed.

**Comment by WulfricBeorhtsige** [comment]
Hello,

I'm a rookie running the learning path - workers. I just encountered this error, though it features as fixed.
I'm following the guide and I haven't altered anything in the default prompts.
When I hit deploy, I get the error.
![draft-worker-1](https://github.com/user-attachments/assets/e26d6487-6e35-41d2-98c8-97be57ef6c56)
