### ISSUE TITLE
🚀 Feature Request: Load dev https certificate and key from environment variables

### ISSUE THREAD

**Issue by kansson** [cloudflare/workers-sdk#5997]
### Describe the solution

I use Tailscale for https during development and have a common certificate and key for all projects. It would be convenient to load these using environment variables like `WRANGLER_HTTPS_{CERT|_KEY}_PATH`.

**Comment by petebacondarwin** [comment]
We discussed this in https://github.com/cloudflare/workers-sdk/pull/4475#issuecomment-1835987149.
It was decided, at that time, that it was more flexible to use a command line argument.
But we could consider ENV vars too??

**Comment by kansson** [comment]
> But we could consider ENV vars too?? Would the CLI args approach be enough for you?

Command line arguments works fine but environment variables would be far more convenient. Also with the latter you don't need to add args to the `package.json` script and potentiality break for other users who don't have the certificate and key.

**Comment by kansson** [comment]
Hi @anthonyringoet any progress on this? 😀

**Comment by kansson** [comment]
Hey @petebacondarwin was this feature mentioned in the docs?
