### ISSUE TITLE
🐛 BUG: D1 Export Fails Due to Wrangler Missing the Last Character, a Zero, in the DB ID

### ISSUE THREAD

**Issue by TimPeterNL** [cloudflare/workers-sdk#6019]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3.60.2 [Wrangler], latest [D1]

### What version of Node are you using?

18.18.2

### What operating system and version are you using?

Windows 11

### Describe the Bug

**D1 Bug Report - Export Fails Due to Wrangler Missing the Last Character (a Zero) in the DB ID**
For one of our D1 databases, when performing an export, we receive a message indicating that it failed to decode the ID. Upon checking, it appears that the last character of the database UUID is missing. The last character for this specific DB should be a zero. The CLI command:
```npx wrangler d1 export db-dev-dynam --remote --output=./test.sql```
returns the error message: `The request is malformed: failed to decode ID [code: 7400]`

**Complete CLI Output**
Note that it uses the ID `********-****-****-****-aea160885d6` for `db-dev-dynam` instead of the correct ID `********-****-****-****-aea160885d60` found in the list. **The difference is only the last zero**.
```
PS C:\**********> npx wrangler d1 export db-dev-dynam --remote --output=./test.sql 

 ⛅️ wrangler 3.60.2
-------------------

🌀 Executing on remote database db-dev-dynam (********-****-****-****-aea160885d6):
🌀 Creating export...

X [ERROR] A request to the Cloudflare API (/accounts/********************************/d1/database/********-****-****-****-aea160885d6/export) failed.

  The request is malformed: failed to decode ID [code: 7400]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose


PS C:\**********> npx wrangler d1 list    

 ⛅️ wrangler 3.60.2
-------------------

┌──────────────────────────────────────┬───────────────┬────────────┬──────────────────────────┐
│ uuid                                 │ name          │ version    │ created_at               │
├──────────────────────────────────────┼───────────────┼────────────┼──────────────────────────┤
│ ********-****-****-****-aea160885d60 │ db-dev-dynam  │ production │ 2024-05-10T09:55:51.134Z │
├──────────────────────────────────────┼───────────────┼────────────┼──────────────────────────┤
│ ********-****-****-****-c9c88e0783be │ test          │ production │ 2024-03-09T11:20:59.537Z │
├──────────────────────────────────────┼───────────────┼────────────┼──────────────────────────┤

```

**Comment by TimPeterNL** [comment]
Any update?

**Comment by andyjessop** [comment]
Could you check the database id in your `wrangler.toml`? We think you might have left off the zero there, which would cause this error.

**Comment by TimPeterNL** [comment]
Ohw... you ar absolutely right! Export is now working. Apologies for the work caused. Ticket can be closed.
