### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by mcnielviray** [cloudflare/workers-sdk#6026]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms, Workers Runtime

### What version(s) of the tool(s) are you using?

 2.20.0 

### What version of Node are you using?

18.16.0

### What operating system and version are you using?

Windows 11

### Observed behavior
Please describe.
Unable to deploy my created worker.

X [ERROR] A request to the Cloudflare API (/accounts/78bcd056079cc293ccb55ad04a79bccb/workers/scripts/ai-management-exp) failed.

### Expected behavior
Please describe.

when I am running the "wrangler deploy src/index.ts --env exp". I am receiving an error 

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suit on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

### Please provide any relevant error logs

<img width="637" alt="worker error" src="https://github.com/cloudflare/workers-sdk/assets/133665946/8c28b90d-0423-4bb2-a996-d124182f2e0b">

**Comment by petebacondarwin** [comment]
The screenshot suggests that you are not authorized to deploy this Worker.
Can you try `wrangler whoami` to confirm how you are authenticated?
Perhaps you are using a CLOUDFLARE_API_TOKEN environment variable that is not valid for this Worker?
Also I see you are on an old version of Wrangler, can you try updating to the latest?

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to comment with more details and we can investigate further.
