### ISSUE TITLE
🐛 BUG: update Miniflare's bundling to use new esbuild watch API

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/workers-sdk#6042]
### Which Cloudflare product(s) does this pertain to?

Miniflare

### What version(s) of the tool(s) are you using?

3.2.x

### What operating system and version are you using?

All

### Describe the Bug

We are bumping the esbuild version for Miniflare but this has a different watching API.
See https://github.com/cloudflare/workers-sdk/pull/6029/files#diff-9f96a6362cf0d9b300410bf0fe90a486661f2837acf0aebe24cc4e50a201e797

**Comment by threepointone** [comment]
I'll do this early next week
