### ISSUE TITLE
🐛 BUG: npm create cloudflare with checking version endless loop

### ISSUE THREAD

**Issue by yunnysunny** [cloudflare/workers-sdk#6061]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

2.21.6

### What version of Node are you using?

18.20.3

### What operating system and version are you using?

windows 10

### Observed behavior
When run  npm create cloudflare, it show `Checking if a newer version is available` again and again, with no error.

![image](https://github.com/cloudflare/workers-sdk/assets/734818/5c74c571-4218-4ad4-9c29-06232f23965c)

**Comment by threepointone** [comment]
Odd, I can't reproduce that here. Can you try `npm create cloudflare@latest`?

**Comment by yunnysunny** [comment]
npm create cloudflare@latest has the samp problem:
![image](https://github.com/cloudflare/workers-sdk/assets/734818/398aeb6b-bcf5-4f13-ab7a-cb15f1632176)

**Comment by Momoka7** [comment]
I have the same problem.
`Checking if a newer version is available` for many times,then the error 
`'create-cloudflare' is not recognized as an internal or external command,
operable program or batch file.`
occurred.
![image](https://github.com/cloudflare/workers-sdk/assets/59860461/99fceb43-5cb5-4075-95e4-fc0e0b2087a7)

**Comment by Momoka7** [comment]
> I have the same problem. `Checking if a newer version is available` for many times,then the error `'create-cloudflare' is not recognized as an internal or external command, operable program or batch file.` occurred. ![image](https://private-user-images.githubusercontent.com/59860461/340062751-99fceb43-5cb5-4075-95e4-fc0e0b2087a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MzkxMDgsIm5iZiI6MTcxODUzODgwOCwicGF0aCI6Ii81OTg2MDQ2MS8zNDAwNjI3NTEtOTlmY2ViNDMtNWNiNS00MDc1LTk1ZTQtZmMwZTBiMjA4N2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDExNTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNTc0ZjgyNjZiMDI5NmQyMzdlODQxYjNiOWZmOGFhYzU3MWMzMGYzYWQzMzUzYjVlNzE3MmY0NGRiNmFiNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pT0SoziYBBeQbY2aQVs7ysl0MFKr1buhmh49PUwx0vs)

Consider change your npm registry, some third party registry may absent the latest version of `create-cloudflare`.

**Comment by yunnysunny** [comment]
I use registry `https://registry.npmmirror.com` , and it lacked latest version.
I synced it manual
![image](https://github.com/cloudflare/workers-sdk/assets/734818/41930632-7dc3-42dd-bd49-806bd670cf2f)
it works ok now.
