### ISSUE TITLE
🐛 BUG: `experimental:nodejs_compat_v2`Not Working Local or Deployment

### ISSUE THREAD

**Issue by jjjrmy** [cloudflare/workers-sdk#6095]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.61.0 [Wrangler]

### What version of Node are you using?

18.18

### What operating system and version are you using?

Mac Sonoma 14.5

### Describe the Bug

I am able to deploy my Hono project onto Cloudflare Workers with `node_compat = true`.
The same project won't work on Pages, I was told to use `nodejs_compat_v2`

Deployment ID: `3080aa6b-e5e7-43cf-a946-25209966bcd7`

### Observed behavior
The project will not upload the function, saying either experimental prefix is required or the flag doesn't exist at all. It's impossible to use. 

When developing locally:
```
The `nodejs_compat_v2` compatibility flag is experimental and must be prefixed with `experimental:`. Use `experimental:nodejs_compat_v2` flag instead.
```
When deploying on Cloudflare:
```
Error: Failed to publish your Function. Got error: No such compatibility flag: experimental:nodejs_compat_v2
```

### Expected behavior
It would be nice if my application would build and work same as Workers.

### Steps to reproduce
Test locally or Deploy on pages using the flag `experimental:nodejs_compat_v2`

### Please provide a link to a minimal reproduction

https://github.com/jjjrmy/hono-sutando-cf-worker-pages

**Comment by schettn** [comment]
Do you have the latest wrangler version?

You: `compatibility_date = "2024-06-14"`
Me (works): `compatibility_date = "2024-08-02"`

**Comment by schettn** [comment]
I could kinda reproduce this: https://github.com/cloudflare/workers-sdk/issues/4489#issuecomment-2265550075

**Comment by jjjrmy** [comment]
@andyjessop 

```
10:12:55.602 | Found _worker.js in output directory. Uploading.
-- | --
10:12:56.650 | ▲ [WARNING] Enabling experimental Node.js compatibility mode v2. This feature is still in development and not ready for production use.
10:12:56.650 |  
10:12:56.650 |  
10:12:56.876 | ▲ [WARNING] 1 warning(s) when compiling Worker.
10:12:56.876 |  
10:12:56.877 |  
10:12:56.917 | Validating asset output directory
10:12:58.585 | Deploying your site to Cloudflare's global network...
10:13:01.645 | Uploading... (0/0)
10:13:01.646 | ✨ Success! Uploaded 0 files (0.17 sec)
10:13:01.646 |  
10:13:01.888 | ✨ Upload complete!
10:13:04.122 | Success: Assets published!
10:13:10.178 | Error: Failed to publish your Function. Got error: No such compatibility flag: experimental:nodejs_compat_v2
```

**Comment by irvinebroque** [comment]
try latest wrangler version

**Comment by jjjrmy** [comment]
@irvinebroque that log was from trying to deploy on Cloudflare Pages. is it not on the latest version of wrangler?
I have my compatibility date set to `compatibility_date = "2024-08-29"`

**Comment by irvinebroque** [comment]
You can reproduce this locally when deploying to Pages, running `npx wrangler@latest pages deploy`?

refs https://github.com/cloudflare/workers-sdk/pull/6511

**Comment by jjjrmy** [comment]
@irvinebroque 
```
✘ [ERROR] Deployment failed!
  Failed to publish your Function. Got error: Uncaught Error: Dynamic require of "events" is not
  supported
```

**Comment by jjjrmy** [comment]
bump, still having these issues even after release @jasnell

**Comment by JudahMantell** [comment]
Still having this issue even after setting my Compatability date to always use latest.
