### ISSUE TITLE
🚀 Feature Request: kv-asset-handler granular caching

### ISSUE THREAD

**Issue by threepointone** [cloudflare/workers-sdk#6104]
### Describe the solution

We should be able to add specific caching rules for specific patterns.

**Comment by petebacondarwin** [comment]
This should become obsolete once Assets for Workers lands later this quarter, no?

**Comment by petebacondarwin** [comment]
kv-asset-handler (and so Workers Sites) is not the recommended way to host assets. Either we should use Pages or wait for the new Workers + Assets to land. Closing this as we won't have capacity or desire to add this to kv-asset-handler.
