### ISSUE TITLE
🐛 BUG: issues with async operations in Worker using Turborepo task execution

### ISSUE THREAD

**Issue by lorenzodejong** [cloudflare/workers-sdk#6125]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.60.3 [Wrangler]

### What version of Node are you using?

20.12.2

### What operating system and version are you using?

MacOS Sonoma 14.5

### Observed behavior
When initialising a Cloudflare Worker inside of a Turborepo and executing the wrangler development server using `turbo dev`, the Worker is facing issues with async operations.

### Expected behavior
The Worker executes async operations correctly in Turborepo's task execution.

### Steps to reproduce

Example repository: https://github.com/lorenzodejong/worker-fetch-test

- `pnpm create turbo@latest`
- `cd apps && pnpm create cloudflare@latest`
- Initialise a "Hello world worker", choose an app name (`worker-test` for example)

Modify the worker `src/index.ts` to include an async fetch call:
```typescript
export default {
	async fetch(request, env, ctx): Promise<Response> {
		const res = await fetch('https://api.sampleapis.com/coffee/hot');
		const movies = await res.json();
		console.log(movies);

		return new Response('Hello World!');
	},
} satisfies ExportedHandler<Env>;
```

Execute the worker from the **root of the monorepo** using `pnpm turbo dev`. Invoke the worker.

Observed result:

```
 [wrangler:err] Error: internal error
│     at async Object.fetch (file:///Users/x/Projects/personal/worker-fetch-test/apps/worker
│ -test/src/index.ts:16:15)
│     at async jsonError (file:///Users/x/Projects/personal/worker-fetch-test/node_modules/.
│ pnpm/wrangler@3.61.0_@cloudflare+workers-types@4.20240620.0/node_modules/wrangler/templates/middleware
│ /middleware-miniflare3-json-error.ts:22:10)
│     at async drainBody (file:///Users/x/Projects/personal/worker-fetch-test/node_modules/.
│ pnpm/wrangler@3.61.0_@cloudflare+workers-types@4.20240620.0/node_modules/wrangler/templates/middleware
│ /middleware-ensure-req-body-drained.ts:5:10)
```

### Please provide a link to a minimal reproduction

https://github.com/lorenzodejong/worker-fetch-test

**Comment by threepointone** [comment]
I was able to reproduce this. I assume you're using something like cloudflare warp or a proxy. Turbo v2 expects you to whitelist all environment variables (so called "strict mode"). Here are a couple of workarounds: 
- use loose mode, this will allow all environment variables through. While I recommend this one, turbo might remove this feature in the future. 
```diff
- "dev": "turbo dev",
+ "dev": "turbo dev --env-mode=loose",
```
- modify your `turbo.json` to whitelist usage of extra https certs. While this is turbo's recommended way, you'll have to constantly keep this up to date. 
```diff
@@ -11,7 +11,8 @@
     },
     "dev": {
       "cache": false,
-      "persistent": true
+      "persistent": true,
+      "env": ["NODE_EXTRA_CA_CERTS"]
     }
   }
 }
```

Let me know if this fixes your problem

**Comment by lorenzodejong** [comment]
Hey @threepointone! Thanks for the quick response, you're actually right about the fact that i'm on proxy. I tried out the fix and it works 👍.

And hats off for the amazing work you've done with Partykit around the Cloudflare ecosystem, keep on going!
