### ISSUE TITLE
🚀 Feature Request: Enable dashboard enviroment variables overwriting  in wrangler.toml for Pages

### ISSUE THREAD

**Issue by yunnysunny** [cloudflare/workers-sdk#6183]
### Describe the solution

I need to create a wrangler.toml to tell Pages to use NodeJS compatible code. But If do that, the  environment variables configured in dashboard will been removed, and I can only set them in wrangler.toml now.
I do not want to use wrangler.toml to store my  environment variables , because I will use the code for several Pages project. So I want to set variables in dashboard dynamically, and use  wrangler.toml only to tell Functions I need NodeJS api to run my code.

I use `keep_vars` to skip reading variables in wrangler.toml, but got the error:
```
19:55:28.735 | ✘ [ERROR] Running configuration file validation for Pages:

19:55:28.735 |  
19:55:28.736 | - Configuration file for Pages projects does not support "keep_vars"
```

**Comment by CarmenPopoviciu** [comment]
hi @yunnysunny 

Thank you for the feature request!

Pages does indeed **not** support `keep_vars`, and there are no immediate plans to support it, if we plan to support it at all.

> to tell Pages to use NodeJS compatible code

How are you doing that. Is it via `compatibility_flags = ["nodejs_compat"]`. If yes, and if the only reason to use `wrangler.toml` is to set that compatibility flag, you can also do that via the Dashboard as well, in Settings -> Functions -> Compatibility flags.

Another option is to use `wrangler pages download config [project-name]`, which allows you to download your Pages project config as a `wrangler.toml` file, if the issue is porting you Dash environment variables to your config file.

Does any of this help your use case?

**Comment by petebacondarwin** [comment]
Closing since workarounds have been provided and there has been no response for 2 weeks.

**Comment by yunnysunny** [comment]
> hi @yunnysunny
> 
> Thank you for the feature request!
> 
> Pages does indeed **not** support `keep_vars`, and there are no immediate plans to support it, if we plan to support it at all.
> 
> > to tell Pages to use NodeJS compatible code
> 
> How are you doing that. Is it via `compatibility_flags = ["nodejs_compat"]`. If yes, and if the only reason to use `wrangler.toml` is to set that compatibility flag, you can also do that via the Dashboard as well, in Settings -> Functions -> Compatibility flags.
> 
> Another option is to use `wrangler pages download config [project-name]`, which allows you to download your Pages project config as a `wrangler.toml` file, if the issue is porting you Dash environment variables to your config file.
> 
> Does any of this help your use case?

I wanna the the person who forked my project would use it directly without nothing configruation on cloudflare dashborad, so I supply the `wrangler.toml`.
It will be convenient for setting optional enviroment variables in dashboard for people who want to use advantage features for the project.
But now , we have to do  a straight choice between the two. Make the project deploy with none configuration, you have to use `wrangler.toml` ; while If you want to do custom envrionment variable, you need to move all wrangler.toml configurations  to dashboard or  to modify the content of wrangler.toml.
Why not give user a choice to set environment variables on dashboard to overwrite them in wrangler.toml.  Environment variable is special , writing some envrionment variables in code is dangerous in some conditions. So I desire that make environment variables separate from another configuration items.
