### ISSUE TITLE
🐛 BUG: wrangler deploy is not working

### ISSUE THREAD

**Issue by bitwisebro** [cloudflare/workers-sdk#6191]
### Which Cloudflare product(s) does this pertain to?

KV, Workers Runtime

### What version(s) of the tool(s) are you using?

3.60.3 wrangler

### What version of Node are you using?

v20.11.1

### What operating system and version are you using?

Windows 10

### Observed behavior
npm run deploy errors out with: 
```
node_modules\wrangler\wrangler-dist\cli.js:29747
            throw a;
            ^

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
```

### Expected behavior
The build should deploy correctly

### Steps to reproduce
1. run: npm create cloudflare@latest wrangler-test
2. setup with hello world worker
3. try to run the hello world worker locally: npm run dev
4. run: npm run deploy
5. open the OAuth url in browser and grant permission to wrangler
6. Notice above mentioned error in console

I didn't modified code at all. Just tried to deploy the out of box hello world worker, even then it is throwing error

### Please provide any relevant error logs

node_modules\wrangler\wrangler-dist\cli.js:29747
            throw a;
            ^

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
..
..
..
..

**Comment by penalosa** [comment]
Duplicate of #3672, which we've just released a fix for. Could you try deploying again?

**Comment by bitwisebro** [comment]
@penalosa Thanks for the fix! Tried this fix for a few times and it is working well! I'll close this issue!
