### ISSUE TITLE
🐛 Update vitest-pool-workers to support vitest >= 2.x

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#6215]
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### Describe the Bug

`vitest-pool-workers` currently only supports up to Vitest 1.5.x.

This prevents the use of new features in [v1.6.0](https://github.com/vitest-dev/vitest/releases/tag/v1.6.0) such as comparing benchmark results, as well as a bunch of bug fixes and performance improvements.

[v2.0.0](https://github.com/vitest-dev/vitest/releases/tag/v2.0.0-beta.13) is also currently in beta, so it would good to see a quick update here to support that version too when it lands.

**Comment by fspoettel** [comment]
related: #6071

**Comment by petebacondarwin** [comment]
Unfortunately vitest 1.6 will never be compatible with workerd so we cannot upgrade to that.
We believe that we can make 2.x work but it will require some non-trivial changes to the vitest-pool-workers code, which will make it incompatible with 1.3.x-1.5.x.

The plan is to do this work and then support 2.x going forward. There is a draft PR here https://github.com/cloudflare/workers-sdk/pull/6232.

I'll update the title of this issue accordingly.
