### ISSUE TITLE
🐛 BUG: wrangler cannot find deployments past the first 25 records

### ISSUE THREAD

**Issue by richburdon** [cloudflare/workers-sdk#6234]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.62.0

### What version of Node are you using?

18.19.0

### What operating system and version are you using?

Mac sonoma

### Observed behavior
`wrangler pages deployment list --project-name=composer` returns a list of deployments BUT only the first 25. If the latest production deployment isn't in the first page then `wrangler pages deployment tail --project-name=composer` fails. 

Tail works if I grab the deployment from the dashboard URL.

### Expected behavior
Either:
- wrangler should support filtering to specify the environment; or
- wrangler should page until it finds the appropriate production deployment

Ideally wrangler should output JSON to enable `jq` queries.

**Comment by tanushree-sharma** [comment]
Internal ticket tracking fix WC-2369.
