### ISSUE TITLE
🐛 BUG: Miniflare service bindings don't work correctly with RPC

### ISSUE THREAD

**Issue by katis** [cloudflare/workers-sdk#6235]
### Which Cloudflare product(s) does this pertain to?

Miniflare

### What version(s) of the tool(s) are you using?

3.20240701.0 [Miniflare]

### What version of Node are you using?

22.4.1

### What operating system and version are you using?

Mac Sonoma 14.3

### Observed behavior

Returning an object from an RPC call in Miniflare throws an error `DevalueError: Cannot stringify POJOs with symbolic keys`.

Returning an RpcTarget subclass from a getter doesn't work correctly, but does with a method.

### Expected behavior

Returning an object through RPC works in Miniflare service bindings

Returning an RpcTarget subclass from a getter works in Miniflare service bindings

### Please provide a link to a minimal reproduction

https://github.com/katis/miniflare-pojo-bug-demo

**Comment by seegeoff** [comment]
#6285 is related

**Comment by dario-piotrowicz** [comment]
Thanks so much for the issue @katis and for the very nice minimal reproduction 🙂 

> Returning an object from an RPC call in Miniflare throws an error DevalueError: Cannot stringify POJOs with symbolic keys.

This should be getting fixed in #6301 please give the [PR's prerelease](https://github.com/cloudflare/workers-sdk/pull/6301#issuecomment-2241185724) a go if you want 🙂 

> Returning an RpcTarget subclass from a getter doesn't work correctly, but does with a method.

I'll look into this in the next few days 🙂 
(PS: unfortunately #6301 is regressing the "but does with a method" 😓)

**Comment by dario-piotrowicz** [comment]
The solution in #6301 has been refactored and there is no regression at all anymore 🙂 

![Screenshot 2024-07-28 at 13 44 06](https://github.com/user-attachments/assets/4c4b7798-8f64-4651-8df7-c95534775d8d)

(so this leaves only the getter issue to address)

(@katis thanks a lot again for the valuable repro and tests!)
