### ISSUE TITLE
🐛 BUG:workers.api.error.unauthorized

### ISSUE THREAD

**Issue by mcnielviray** [cloudflare/workers-sdk#6240]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms, Wrangler

### What version(s) of the tool(s) are you using?

3.29.0

### What version of Node are you using?

18.16.0

### What operating system and version are you using?

Windows 11

### Observed behavior
Please describe.
Unable to deploy the Cloudflare worker, which initially I am able to do it.

### Expected behavior
Please describe.

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suite on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

### Please provide any relevant error logs

X [ERROR] A request to the Cloudflare API (/accounts/78bcd056079cc293ccb55ad04a79bccb/workers/scripts/vimeo-devhono) failed.

  workers.api.error.unauthorized [code: 10023]

**Comment by petebacondarwin** [comment]
Hi thanks for the issue report. The `unauthorized` error suggests that the user you are logged into (with Wrangler, possibly via an API token) does not have access to the `vimeo-devhono` Worker in that account.
Please can you provide more information about your current logged in user by running `wrangler whoami` and also checking whether you have `CLOUDFLARE_API_TOKEN` set in your environment.

**Comment by petebacondarwin** [comment]
Closing due to lack of response.
