### ISSUE TITLE
🐛 BUG: `Write EOF` error when running `wrangler dev` for local dev , but deploy is successful.

### ISSUE THREAD

**Issue by Mahi-Teja** [cloudflare/workers-sdk#6262]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.64.0

### What version of Node are you using?

22.4.1

### What operating system and version are you using?

windows 10

### Observed behavior
throwing EOF write error where it should have.

### Expected behavior
 host the server locally

### Steps to reproduce
Please provide the following:
Just created a basic cloudflare app
- `npm create cloudflare --app`
- after successful setup `cd app`
- then `npm run dev ` or `npm start`
- and the error is thrown

![image](https://github.com/user-attachments/assets/72ff30bb-eeac-4f70-8c81-b7699d13de4c)

### Please provide any relevant error logs

```
C:\Users\projects\new-app\node_modules\wrangler\wrangler-dist\cli.js:29765
            throw a;
            ^

Error: write EOF
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)      
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -4095,
  code: 'EOF',
  syscall: 'write'
}

Node.js v22.4.1```

**Comment by Mahi-Teja** [comment]
### Strangely, the `npm run deploy` successfully deployed the server on cloudflare, but throwing error when trying to run locally.
![image](https://github.com/user-attachments/assets/2c634944-0bad-4dcb-b53a-a4c58c548152)

**Comment by petebacondarwin** [comment]
Can you try with node v18 just to check whether this is a problem with Wrangler running on newer node versions.

**Comment by Mahi-Teja** [comment]
![image](https://github.com/user-attachments/assets/5c4df55c-b804-4625-8609-c544e90a48c3)

still getting the error (am using windows 10). 
I tried this on WSL with node 18,20,22 it works fine.

**Comment by oriolmart** [comment]
I have the same issue on Windows 11 and node 20.16.0, i did not find a solution

**Comment by penalosa** [comment]
Could someone who's running into this provide the exact version of Windows 10/Windows 11 that they're running to help us track this down?

**Comment by cuongthom** [comment]
I'm also having the same problem and hope you can help

**Comment by lrapoport-cf** [comment]
hi @Mahi-Teja and all :) we're going to close this issue for now as we don't have enough information to reproduce at this time. for anyone still running into this issue, please open a new issue referencing this one and be sure to include the exact version of windows 10/windows 11, as well as any additional details or context, and we will revisit and investigate. thank you!
