### ISSUE TITLE
🐛 BUG: No error handling for failed deploy due to binding with the name 'assets'.

### ISSUE THREAD

**Issue by db-cloudflare** [cloudflare/workers-sdk#6266]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

Wrangler 3.64.0

### What version of Node are you using?

20.10.0

### What operating system and version are you using?

Windows 11

### Observed behavior
When deploying a Hono application in Wrangler, if a binding uses the name 'ASSETS' the application will fail to deploy.

### Expected behavior
The application failing to deploy is expected as assets is a reserved keyword, however no error message is provided to explain that this is the cause of the failed deployment. An error message that explains that a binding with the name assets exists and that the name needs to be changed is the expected behavior.

### Steps to reproduce
Please provide the following:
- Create a Hono application
- Add a binding with the name 'ASSETS'
- Attempt deploying the application

**Comment by threepointone** [comment]
I think this is a problem specifically with pages, is that right @dbenCF?

**Comment by petebacondarwin** [comment]
Oh right. Hono created via C3 is for Workers. But yes, I expect that ASSETS is blocked in Cloudflare Pages.
Let me try to recreate it...

**Comment by petebacondarwin** [comment]
OK I managed to recreate this, I think. I don't think this has anything to do with Hono or R2. I think that any Pages project that is configured with a wrangler.toml that has an `ASSETS` binding (of any kind) will error with an output that looks like:

```
pnpm wrangler pages deploy 
🌍  Uploading... (1/1)

✨ Success! Uploaded 0 files (1 already uploaded) (0.16 sec)

✨ Compiled Worker successfully
✨ Uploading Worker bundle
🌎 Deploying...

✘ [ERROR] Deployment failed!

  Failed to publish your Function. Got error: Unknown internal error occurred.
  ```

**Comment by petebacondarwin** [comment]
Indeed I can recreate this with the following files:

_worker.js
```js
export default {
  fetch(_req, env) {
    return new Response(env.ASSETS);
  },
};
```

package.json
```json
{
  "name": "test"
}
```

wrangler.toml
```toml
name = "test"
pages_build_output_dir = "."
[vars]
ASSETS = "test"
```

Then running 

```
pnpx wrangler pages deploy 
✔ Select an account › Pete Bacon Darwin Account
🌏  Uploading... (2/2)

✨ Success! Uploaded 1 files (1 already uploaded) (1.22 sec)

✨ Compiled Worker successfully
✨ Uploading Worker bundle
🌎 Deploying...

✘ [ERROR] Deployment failed!

  Failed to publish your Function. Got error: Unknown internal error occurred.
```

**Comment by petebacondarwin** [comment]
Really we should be getting a better error back from the API when this fails, but we could perhaps put an additional validation check into Wrangler.
