### ISSUE TITLE
🐛 BUG: After using npm create cloudflare most examples do not work with TypeScript types

### ISSUE THREAD

**Issue by davidbarratt** [cloudflare/workers-sdk#6328]
### Which Cloudflare product(s) does this pertain to?

C3 (npm create cloudflare)

### What version(s) of the tool(s) are you using?

2.22.2 [C3]

### What version of Node are you using?

20.15.1

### What operating system and version are you using?

Ubuntu through WSL

### Observed behavior
Please describe.

### Expected behavior
Please describe.

### Steps to reproduce
1) Run `npm cloudflare create` with the `"Hello World" Worker` and with TypeScript
2) From the `fetch` handler, return the response from the global `fetch()`
    ```ts
    return fetch(request);
    ```
3) You should now get a type error

I tried an alternative syntax and it also fails with a different error:
```ts
const response = await fetch(request);
return new Response(response.body, response);
```

### Please provide a link to a minimal reproduction

https://github.com/davidbarratt/worker-types/blob/b75bd22eab7d8ab9bfb65362360d5015ad351aa4/src/index.ts#L15-L17

You can see the error if you go to the `src/index.ts` file here (and wait for TypeScript to load):
https://stackblitz.com/~/github.com/davidbarratt/worker-types

### Please provide any relevant error logs
```
Type 'Response' is missing the following properties from type 'Response': webSocket, cf, bytests(2739)
```
or with the alternative format (creating a new `Response`):
```
Argument of type 'ReadableStream<any> | null' is not assignable to parameter of type 'BodyInit | null | undefined'.
  Type 'ReadableStream<any>' is not assignable to type 'BodyInit | null | undefined'.
    Type 'ReadableStream<any>' is not assignable to type 'ReadableStream<Uint8Array>'.
      The types returned by 'getReader(...)' are incompatible between these types.
        Property 'readAtLeast' is missing in type 'ReadableStreamDefaultReader<any>' but required in type 'ReadableStreamBYOBReader'.ts(2345)
```

**Comment by Cherry** [comment]
This looks very much like https://github.com/cloudflare/workerd/issues/1298 to me.

And if I throw the following as described in that issue, into your `package.json` and reinstall, the errors do sure enough disappear:
```json
   "overrides": {
        "@types/node": "20.8.3"
    }
```

If it's happening with a fresh `npm create cloudflare` project now though, that's concerning.
