### ISSUE TITLE
🐛 BUG: Serving forms on static pages through `wrangler pages dev` overrides all POST forms as GET requests 

### ISSUE THREAD

**Issue by nathanchere** [cloudflare/workers-sdk#6338]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.67.0

### What version of Node are you using?

22.5.1

### What operating system and version are you using?

Linux Arch

### Observed behavior
Serving forms on static pages through `wrangler pages dev` overrides all POST forms as GET requests

### Expected behavior
POST forms should submit POST requests

### Steps to reproduce
I created a function in `./functions/api/[[path]].js` to test with the following content:

```
export async function onRequestGet(context) {
  const url = new URL(context.request.url);
  const res = new Response(`GET request to ${url.pathname}`);
  res.headers.set("Content-Type", "text/plain");
  return res;
}

export async function onRequestPost(context) {
  const url = new URL(context.request.url);
  const res = new Response(`POST request to ${url.pathname}`);
  res.headers.set("Content-Type", "text/plain");
  return res;
}

```

Using wranger.toml:

```
name = "functionstest"
pages_build_output_dir = "./dist"
compatibility_date = "2024-06-03"
```

I'm using Astro in this instance but it shouldn't matter as long as the rendered HTML in ./dist points to the same base URL and port that wrangler is serving on. An example of the content of a html page in ./dist used for testing:

```
<form name="contactx" method="POST" action="http://localhost:8788/api/contact">
    <input name="name" value="testing 1 post request"> 
    <input name="email" value="somthing@some.com"> <input type="submit"> 
</form>
<form name="contactx2" method="GET" action="http://localhost:8788/api/contact">
    <input name="name" value="testing 1 get request"> 
    <input name="email" value="somthingelse@some.com"> <input type="submit"> 
</form>
```

Serving the contents of ./dist with `wrangler pages dev` looks fine but all the forms submit as GET requests regardless of how the HTML form is configured. Running the page from the Astro server does a POST as expected. Opening the rendered HTML page in the browser from the ./dist folder via local file system with no additional web server, the behaviour is a POST as expected.

**Comment by petebacondarwin** [comment]
I created this project and it works correctly sending a POST request as expected: https://github.com/petebacondarwin/issue-6338

I suspect that the problem is related to your use of Astro. Perhaps Astro is intercepting the form submissions and redirecting them in some way?

I note that above you are using what appears to be Pages Functions. That is not how Astro does Worker handlers.
See https://github.com/petebacondarwin/issue-6338-astro for an example of how it can work.
