### ISSUE TITLE
🐛 BUG: `fetchMock` returns an empty url

### ISSUE THREAD

**Issue by davidbarratt** [cloudflare/workers-sdk#6350]
### Which Cloudflare product(s) does this pertain to?

Wrangler, Workers Vitest Integration

### What version(s) of the tool(s) are you using?

0.4.14

### What version of Node are you using?

20.15.1

### What operating system and version are you using?

Ubuntu 22.04.4 via WSL2

### Observed behavior
My worker relies on [Response.url](https://developer.mozilla.org/en-US/docs/Web/API/Response/url) property, but the mock returns an empty string.

### Expected behavior
Whatever URL was executed should be added to the `url` property.

### Steps to reproduce
https://github.com/davidbarratt/cache-tag/blob/9e725fab60e565ce6b863367ab27fac527a0a5d5/test/index.spec.ts

### Please provide a link to a minimal reproduction

https://github.com/davidbarratt/cache-tag/blob/9e725fab60e565ce6b863367ab27fac527a0a5d5/test/index.spec.ts

**Comment by petebacondarwin** [comment]
I can reproduce this. Working on a fix.

**Comment by petebacondarwin** [comment]
Related discussion here: https://stackoverflow.com/questions/56654119/how-do-you-set-the-url-when-creating-a-new-response
