### ISSUE TITLE
🐛 BUG: getMigrationsToUpload is not aware of dispatch namespaces

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-sdk#6354]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

Wrangler

### What operating system and version are you using?

macOS

### Describe the Bug

`deploy.ts` will change the URL if `dispatch_namespace` is present, but if a Durable Object is being uploaded with a script to a dispatch namespace, it won't be able to query for the current migration tag

**Comment by petebacondarwin** [comment]
Any chance you could provide a simple reproduction @GregBrimble to help out the developer who might fix this?

**Comment by lrapoport-cf** [comment]
hey @GregBrimble :) we haven't heard from you in a while so we're going to close this issue for now. if this is still an issue for you, please feel free to reopen and please include a reproduction. thanks!
