### ISSUE TITLE
🐛 BUG: missing .gitignore in C3 (npm create cloudflare) "hello world" project 

### ISSUE THREAD

**Issue by jldec** [cloudflare/workers-sdk#6368]
### Which Cloudflare product(s) does this pertain to?

C3 (npm create cloudflare)

### What version(s) of the tool(s) are you using?

C3 v2.22.3 (pnpm create cloudflare@latest) 

### What version of Node are you using?

v20.11.1

### What operating system and version are you using?

macOS Sonoma 14.5

### Observed behavior
It appears that using C3 to create the "Hello World" project with git for version control no longer includes a `.gitignore` file.
This results in the `node_modules` directory being committed in the initial commit. 😮 

I believe this is a recent regression. Earlier hello world projects e.g. created with `create-cloudflare@2.21.9` did not have this problem.

![Screenshot 2024-07-29 at 20 48 37](https://github.com/user-attachments/assets/959aeaac-61c3-4794-afa7-ab1b5e9c13eb)

The problem also does not appear with the "Website or web app" templates. (I tried Next and Hono) 

### Expected behavior
A similar .gitignore file as other template projects

### Steps to reproduce
- `pnpm  create cloudflare@latest`
- select type "Hello World" Worker
- select yes for "Do you want to use git for version control?"

Unless you have `node_modules` globally ignored, it will be committed to the repo.

**Comment by jldec** [comment]
Please feel free to close this issue - I can no longer reproduce it on the latest C3. (v2.23.0)  
To repro this issue, please run `pnpm create cloudflare@2.22.3 --no-auto-update`  
(or use npm)
tx.

**Comment by dario-piotrowicz** [comment]
thanks for the issue @jldec 🙂

Since as you said this doesn't seem a problem present in the latest C3 release I think it's quite safe for us to close the issue 🙂 

But please feel free to reopen it or open a new one should the issue reappear 🙏
