### ISSUE TITLE
🚀 Feature Request: Allow passing a custom fetch function to AI `run` calls

### ISSUE THREAD

**Issue by brettimus** [cloudflare/workers-sdk#6393]
### Describe the solution

Currently, any call of `AI.run(...)` shells out to that class's `fetcher` property, which is a readonly property of an `AI` instance. 

In wrangler, the `fetcher` on your AI binding will call `performApiFetch`, an internal method that ultimately uses undici `fetch` under the hood, after applying some special sauce to authenticate against cloudflare (see: https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/cfetch/internal.ts#L18C23-L18C38)

API Clients for OpenAI and Anthropic allow you to "bring your own fetch", when you instantiate your client. This can make it easy to do simple monitoring of calls to their services locally (inspecting payloads, and quickly getting insights into how long inference tasks took, especially in a longer chain).

Seeing as (I don't think?) we have an easy way in wrangler to hook into the creation of the AI bindings, I thought it could be nice to optionally accept a custom fetch function whenever you call `AI.run`.

This would require a few modifications. The `AiOptions` type would be extended to accept a `fetch` parameter, whose type signature simply matches the web standard fetch:

```ts
type AiOptions = {
  gateway?: GatewayOptions;
  prefix?: string;
  extraHeaders?: object;
  fetch?: typeof fetch;
};
```

Then, you could run

```ts
env.AI.run("@cf/baai/bge-small-en-v1.5", { /* ... */ }, {
  fetch: myCustomFetchFn
})
```

A cursory look through the worker code makes me think this would require a few changes to the `Ai` class and it's Fetcher property, and then I'd assume the API would have to be implemented on `workerd` as well.

It's a little tricky, since the whole point of this change would be to still preserve all the magic that's happening in `performApiRequest` to attach proper auth, etc, to the request, but ultimately the internal cf `performApiRequest` method would use `myCustomFetchFn` instead of undici's fetch.

I realize that's not really a trivial undertaking, but I'd be happy to discuss it further and pick it up :) as I do think this would provide some monitoring flexibility, especially in situations where one is using a modified fetch function to, e.g., automatically produce spans for fetch calls.

**Comment by penalosa** [comment]
It's worth noting that the implementation in Wrangler (passing through to `performApiFetch()`) will only run when using `wrangler dev` locally. For deployed workers in production a different codepath is used, and so it wouldn't be possible to override the fetch method used there. I think AI Gateway is probably a good fit for the monitoring use cases you mention: https://developers.cloudflare.com/ai-gateway/providers/workersai/#worker, have you given that a try?

**Comment by celso** [comment]
@brettimus While providers like OpenAI just "fetch" their public endpoints, ai.run's fetch is very specific to our implementation and hard to expose like you're suggesting. Implementation aside, what is the problem that you're trying to solve?

**Comment by G4brym** [comment]
Hey @brettimus , this is no pretty, but you should be able to mutate the fetch directly on `env.AI` like this:

```ts
const binding = env.AI;
binding.fetcher = {
    fetch: async (input: RequestInfo | URL, init?: RequestInit) => {
      return fetch("http://localhost:8787", init);
    },
};
```

Then calling `binding.run(...)` will use your custom fetcher, some typescript errors might pop up, but you can ignore them

**Comment by brettimus** [comment]
yeah so this was a few weeks ago and i didn't take notes on what i tried, but i remember overriding the fetcher ultimately broke auth against cloudflare's services, so it was a nonstarter. but good shout!

> Hey @brettimus , this is no pretty, but you should be able to mutate the fetch directly on `env.AI` like this:
> 
> ```ts
> const binding = env.AI;
> binding.fetcher = {
>     fetch: async (input: RequestInfo | URL, init?: RequestInit) => {
>       return fetch("http://localhost:8787", init);
>     },
> };
> ```
> 
> Then calling `binding.run(...)` will use your custom fetcher, some typescript errors might pop up, but you can ignore them

**Comment by brettimus** [comment]
@celso @G4brym — thanks for chiming in! i'm a library author, looking for ways to auto-instrument any network calls in Hono apps with opentelemetry traces. so that's my use case. 

api gateway would solve this, indeed, but requires additional configuration / wiring things together, which is what i want to solve. (i'm trying for "out of the box traces with spans")

i can give the api gateway a scan to see how i'd work with opentelemetry. thanks again for the responses

**Comment by G4brym** [comment]
wouldn't a simple proxy on the .run method work for you?

```ts
const originalRun = env.AI.run

const binding = env.AI;
binding.run = async (...args) => {
  // code before run
  const result = await originalRun(...args)
  // code after run

  return result
}
```

**Comment by brettimus** [comment]
> wouldn't a simple proxy on the .run method work for you?
> 
> ```ts
> const originalRun = env.AI.run
> 
> const binding = env.AI;
> binding.run = async (...args) => {
>   // code before run
>   const result = await originalRun(...args)
>   // code after run
> 
>   return result
> }
> ```
> 
> Or even a standard js proxy: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

yes so current approach we're using is proxying `app.fetch` for incoming/outgoing requests, to create a parent span.

then we create child spans for each network request that happens, by patching `globalThis.fetch`. that allows us to add semantic labels for the request/response. since the calls via the cf ai binding are ultimately http requests, it'd be nice to treat them as such. then we get a lot of our attribute serialization for free.

proxying the AI binding itself is certainly a good option, though, and probably the route we'll take at this point!

**Comment by brettimus** [comment]
i'll close this issue as it doesn't seem like a good use of time, and there are clearly workarounds!
