### ISSUE TITLE
🐛 BUG: C3 init from git differs from `generate` behaviour

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#6459]
### Which Cloudflare product(s) does this pertain to?

C3 (npm create cloudflare), Wrangler

### What version(s) of the tool(s) are you using?

C3 2.23.0, wrangler 3.70.0

### What version of Node are you using?

20.16.0

### What operating system and version are you using?

Windows 11

### Describe the Bug

With https://github.com/cloudflare/workers-sdk/pull/6415 landing soon, if `generate` args are simply going to be passed to `c3`, the behaviour must match that 1:1 of `generate` if this is to remain a `minor` bump.

In this issue, I'll lay out all of the differences in behaviour I've found thus far. Perhaps it would be good to run all of the `generate` tests against `c3` if #6415 is to land.

## tsconfig

If a template ships its own tsconfig.json with a `workers-types` entry in the `types` array, c3 shouldn't try and add another one. For example:

- npm create cloudflare@latest
- Template from a Github repo
- https://github.com/Cherry/wrangler-template-example
- Observe `tsconfig.json` now has multiple `workers-types` entries

## Non-github templates

For example: https://gitlab.com/CherryJimbo/wrangler-template-example

C3 errors:
```
├ template failed
│
╰  ERROR  Failed to clone remote template: https://gitlab.com/CherryJimbo/wrangler-template-example
npm error code 1
npm error path E:\c3-testing
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c create-cloudflare
npm error A complete log of this run can be found in: C:\Users\james\AppData\Local\npm-cache\_logs\2024-08-09T13_59_14_414Z-debug-0.log
```

But `npx wrangler generate test https://gitlab.com/CherryJimbo/wrangler-template-example` works fine.

## Missing wrangler.toml

`generate` handles generating from a repo that doesn't yet container a `wrangler.toml`.

- Use `https://github.com/Cherry/wrangler-template-example/src` for testing (not real world, but an example without wrangler.toml)
- `npx wrangler generate test https://github.com/Cherry/wrangler-template-example/src` works fine
- c3 errors: `╰  ERROR  create-cloudflare templates must contain a "wrangler.toml" file.`

## Cloning to existing directory

- `mkdir test`
- `npm create cloudflare@latest -- test --template https://github.com/Cherry/wrangler-template-example` - errors with ` ERROR  Directory `test` already exists and contains files that might conflict. Please choose a new name.`
- vs `npx wrangler generate test https://github.com/Cherry/wrangler-template-example` succeeds, and just creates a `test-1` directory

## Non-interactive mode

`npm create cloudflare@latest -- test2 --template https://github.com/Cherry/wrangler-template-example`

This still prompts afterwards for "git" and "deploying". Is there a way to skip these prompts entirely so the command is non-interactive? You can pass `-y`, but that then attempts to deploy, which isn't what I want. If I pass `--no-accept-defaults`, I still get interactive prompts.

## Error handling

The errors reported from c3 aren't as useful as those from generate. For example, with `https://github.com/Cherry/wrangler-template-private` as the URL:

c3:
```
├ Cloning template from: https://github.com/Cherry/wrangler-template-private
│
├ template failed
│
╰  ERROR  Failed to clone remote template: https://github.com/Cherry/wrangler-template-private
npm error code 1
npm error path E:\c3-testing
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c create-cloudflare
npm error A complete log of this run can be found in: C:\Users\james\AppData\Local\npm-cache\_logs\2024-08-09T13_54_59_429Z-debug-0.log
```

`npx wrangler generate test https://github.com/Cherry/wrangler-template-private`:

```
✘ [ERROR] Command failed with exit code 128: git clone --depth 1 https://github.com/Cherry/wrangler-template-private.git C:\Users\james\AppData\Local\Temp\wrangler-generate-repo-KIMtN3

  Cloning into 'C:\Users\james\AppData\Local\Temp\wrangler-generate-repo-KIMtN3'...
  remote: Repository not found.
  fatal: repository 'https://github.com/Cherry/wrangler-template-private.git/' not found
```
This prints back exactly what it tried to clone, and the response code it got, giving me much more insight to try and debug why.

**Comment by andyjessop** [comment]
This has been addressed in #6415, which was modified so that `generate` with a URL parameter did not delegate to C3.
