### ISSUE TITLE
🐛 BUG: Wrangler leaves orphaned processes after failing to bind to port

### ISSUE THREAD

**Issue by KevSlashNull** [cloudflare/workers-sdk#6510]
### Which Cloudflare product(s) does this pertain to?

Wrangler, Miniflare

### What version(s) of the tool(s) are you using?

10.5.0 [Wrangler], 2024-08-06 [Workerd], 3.20240806.1 [Miniflare]

### What version of Node are you using?

20.12.2

### What operating system and version are you using?

Mac Sonoma 14.6

### Overview

We’ve seen our engineers and community members run into issues with lingering/orphaned `workerd` processes. It seems to be exacerbated by our SDK automatically restarting the `wrangler` when it crashes. Particularly during project updates where `wrangler.toml` is automatically updated by our tooling, wrangler crashes and is immediately restarted by our tooling.

As initial corrective action we’ll disable the service that uses wrangler during project updates. Maybe this’ll help others too.

For context:

- Our tracking issue: https://gitlab.com/gitlab-org/gitlab-development-kit/-/issues/2159
- My comment in the `workerd` project: https://github.com/cloudflare/workers-sdk/issues/4637#issuecomment-2293108196

### Observed behavior

If `wrangler dev` crashes due to a port allocation issue, it leaves behind an orphaned `workerd` process.

Note that it might be also be a mishandling by Miniflare instead of wrangler (see the error below).

### Expected behavior

If `wrangler dev` crashes, it should still clean up resources that it opened.

### Steps to reproduce

1. Run `pgrep workerd | wc -l` and note the number of `workerd` processes
2. Run `git clone https://github.com/KevSlashNull/wrangler-lingering-bug-demo`
3. Run `cd wrangler-lingering-bug-demo`
4. Run `npm install`
5. Run `npx wrangler dev`
6. See an error like `MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.`
7. Run `pgrep workerd | wc -l` again and see that the number of processes increased by one!

### Please provide a link to a minimal reproduction

https://github.com/KevSlashNull/wrangler-lingering-bug-demo

### Please provide any relevant error logs

```
/private/tmp/wrangler-lingering-bug-demo/node_modules/wrangler/wrangler-dist/cli.js:29768
            throw a;
            ^

MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/private/tmp/wrangler-lingering-bug-demo/node_modules/miniflare/dist/src/index.js:9281:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Mutex.runWith (/private/tmp/wrangler-lingering-bug-demo/node_modules/miniflare/dist/src/index.js:3522:16) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}

Node.js v20.15.1
```

**Comment by RamIdeas** [comment]
Hi @KevSlashNull! Thanks for the repro! I've run it myself and confirm your observations – a workerd process is orphaned and left running after wrangler exits.

Coincidentally I have looking into this myself this week, although the orphaned processes I've been finding aren't as easily reproducible. Thanks again for this repro – I'll dig into a specific fix for this issue. _But also_ I have an been thinking of getting workerd to terminate itself when it's parent exits (maybe opt in by a flag wrangler can set) to settle this issue once and for all.

**Comment by RamIdeas** [comment]
I have an existing PR which seems to address this issue https://github.com/cloudflare/workers-sdk/pull/6427

**Comment by penalosa** [comment]
This should be addressed by https://github.com/cloudflare/workers-sdk/pull/7169
