### ISSUE TITLE
🚀 Feature Request: Wrangler type generator `RateLimit` type

### ISSUE THREAD

**Issue by Pedr0Rocha** [cloudflare/workers-sdk#6529]
### Describe the solution

Hello,

Now that [this PR](https://github.com/cloudflare/workerd/pull/2170) adding the type definition for the beta `RateLimit` binding is merged, is it worth adding it in the wrangler type generator? I would like to use it, but it gets overwritten by `any` when I generate the types.

Since it's still an unsafe binding, I assume the checks would still have to me made [here](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/type-generation/index.ts#L347) for now and later on removed to become its own env field binding. Is there anywhere else it needs to be added?

If this is okay to add, I can open a PR with the type + tests.

**Comment by penalosa** [comment]
@Pedr0Rocha we'd be happy to accept a PR that adds this!
