### ISSUE TITLE
How to test with `nodejs_compat` workers?

### ISSUE THREAD

**Issue by AbhiPrasad** [cloudflare/workers-sdk#6544]
Let's say you had a worker that looks like so:

```ts
import { init, wrapper } from 'third-party-lib';

init();

/**
 * @type {import('@cloudflare/workers-types').ExportedHandler}
 */
export default {
  async fetch(_request, _env, _ctx) {
    return wrapper(() => {
      return new Response('Hello World!');
    });
  },
};
```

where `third-party-lib` uses Node API's under the hood (so `nodejs_compat: true` - specifically it uses `AsyncLocalStorage`, so using `nodejs_als` would be more accurate but that doesn't seem to work at all with `NodeJsCompatModule`).

How do you set up Miniflare to test this? Everything is also ESM.

I get the following error:

```
stderr | test/index.test.ts > index > simple test
workerd/util/symbolizer.c++:96: warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set. To symbolize stack traces, set $LLVM_SYMBOLIZER to the location of the llvm-symbolizer binary. When running tests under bazel, use `--test_env=LLVM_SYMBOLIZER=<path>`.
*** Fatal uncaught kj::Exception: kj/async-io-unix.c++:945: failed: ::bind(sockfd, &addr.generic, addrlen): Address already in use; toString() = 127.0.0.1:8787
stack: 1054ac4b7 1054ac24f 102e82813 102e8302f 102e837ef 102e83ea7 102e2ccdb 102e2c8f7 1054d73ef 1054d78ab 1054d6027 1054d5dbf 102e1c1b7 1985420df
```

when using a single module that has type: `NodeJsCompatModule` and a path to the ESM worker script

**Comment by lrapoport-cf** [comment]
hi @AbhiPrasad  :) we haven't heard from you in a while, so we’re going to close this issue for now. if this is still a problem, please feel free to open a new issue referencing this one with an updated summary, repro, and any additional context and we will revisit and investigate further. thanks!
