### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by omonukko** [cloudflare/workers-sdk#6552]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

4.20240806.0

### What version of Node are you using?

20.15.0

### What operating system and version are you using?

Windows11

### Describe the Bug

When I try to use Wrangler Deploy, an error occurs and I cannot deploy.
The error is as shown in the image
![スクリーンショット 2024-08-22 120200](https://github.com/user-attachments/assets/d527740d-9b74-436c-a654-3308910e9b5f)

**Comment by bllchmbrs** [comment]
I am on mac and get this issue as well:

```

  workers.api.error.unknown [code: 10013]
```

Happens upon worker deploy.

**Comment by AbdullahDaGoat** [comment]
similar error i do npm run deploy (wrangler deploy ./dist/index.js) and it produces this same error im also using a KV and esbuild.config.js

**Comment by irvinebroque** [comment]
https://www.cloudflarestatus.com/incidents/x54t30777c2q
