### ISSUE TITLE
🐛 BUG: Local mode stopped working; workerd failures / zombie processes

### ISSUE THREAD

**Issue by bllchmbrs** [cloudflare/workers-sdk#6579]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler

### What version(s) of the tool(s) are you using?

3.7.2 (wrangler)

### What operating system and version are you using?

Sonoma 14.6.1 

### Observed behavior
I have the following `index.ts`
```

console.log("Starting up...");
export default {

	async fetch(request, env, ctx): Promise<Response> {
		console.log("Getting Request", request);
		return new Response("SOME TEXT");
	},
} satisfies ExportedHandler<Env>;

```

The following toml
```
#:schema node_modules/wrangler/config-schema.json
name = "some-name"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]
```

### Expected behavior
When I open the browser **nothing happens**. The page just acts like I am waiting for a request.

If I hit `l` to `turn off local mode`. It loads instantly.

I turn it off, it ceases to work again.

I just updated wrangler today.

### Steps to reproduce
See above, it's trivial.

How can I debug the local mode? There are no logs to try to resolve it.

**Comment by bllchmbrs** [comment]
OK, I got it working but I had to **manually** kill any a workerd process. Is there an easier way to debug?

**Comment by irvinebroque** [comment]
https://github.com/cloudflare/workers-sdk/issues/6510 this ssue?

**Comment by bllchmbrs** [comment]
I've been investigating, I'm not sure it's the same.

Do you know of what around `WorkerEntrypoint` - I think that crashes when I try to run it on my local machine (in a variety of ways) and may have led to the above.

**Comment by penalosa** [comment]
Could you try killing all running `workerd` instances (with `pkill -9 workerd`), and then try running wrangler with the experimental dev registry that should be more stable (`wrangler dev --x-registry`)?

**Comment by bllchmbrs** [comment]
1. killing processes didn't actually work, there's some residual state. I had to do a full machine restart, move to a new directory, it was a huge pain.
2. The `--x-registry` works well in testing so far. Not experiencing any of the issues that I experienced before (thus far).

Will close those out, but hopefully the new registry makes it to prod soon!
