### ISSUE TITLE
🚀 Feature Request: Option to set secret with secret file `npx wrangler secret put <SECRET_FILE> `

### ISSUE THREAD

**Issue by 0x00000000000000000000000** [cloudflare/workers-sdk#6596]
### Describe the solution

Currently, we have to set secrets one by one? By using `npx wrangler secret put SECRET_KEY`, wait for the prompt, and then insert the secret value. Is there a more elegant way to do this?

**Comment by penalosa** [comment]
You should be able to use the bulk secret commands for this use case: https://developers.cloudflare.com/workers/wrangler/commands/#secretbulk

**Comment by 0x00000000000000000000000** [comment]
Thanks! @penalosa
