### ISSUE TITLE
🐛 BUG: Can't use nodejs_compat_v2 with vitest-pool-workers

### ISSUE THREAD

**Issue by cloudkite** [cloudflare/workers-sdk#6610]
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

3.73.0 Wrangler

### What version of Node are you using?

21.5.0

### What operating system and version are you using?

Mac

### Describe the Bug

Setting in wrangler.toml:
compatibility_flags = ["nodejs_compat_v2"]

Error when running tests:
Error: In project packages/embed-worker/vitest.config.ts's configuration file packages/embed-worker/wrangler.toml, `compatibility_flags` must contain "nodejs_compat".
This flag is required to use `@cloudflare/vitest-pool-workers`.

**Comment by koogunmo** [comment]
did you find a workaround? I have this issue as well.

**Comment by cloudkite** [comment]
@koogunmo no I tried patching `vitest-pool-workers` to remove the check, but it gave me a different error in miniflare instead so I gave up and went back to using `nodejs_compat`

**Comment by koogunmo** [comment]
[bastiankistner](https://github.com/bastiankistner) Thanks for the suggestion, but unfortunately, that approach doesn’t work for me. One of the libraries I rely on requires specific functions available in `nodejs_compat_v2` that aren’t present in `nodejs_compat`, which results in an error when I try to run it.

**Comment by cloudkite** [comment]
works now if you set

```
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
```

**Comment by koogunmo** [comment]
@cloudkite I updated my cloudflare pacakages to 'latest" in npm and it isn't working for me. I get this error now: 

```
[mf:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2024-08-21",
but you've requested "2024-09-23". Falling back to "2024-08-21"...

```

Has the change been released yet?
