### ISSUE TITLE
🐛 BUG: Cloudflare Worker Queue Consumer Not Executing in Production

### ISSUE THREAD

**Issue by DevAwais92** [cloudflare/workers-sdk#6619]
### Which Cloudflare product(s) does this pertain to?

Queues

### What version(s) of the tool(s) are you using?

Wrangler: 3.73.0, Queues Beta

### What version of Node are you using?

20.11.0

### What operating system and version are you using?

Windows 11

### Describe the Bug

I have created a Cloudflare Worker to handle queues with the following configuration. The worker successfully processes queue messages in development mode locally. However, when deployed to production, the consumer queue does not execute as expected. The only log output I receive is from the console.log('queue request received', env); in the fetch event, and the consumer queue is not triggered. in queues dashboard messages are being queued. and lastly in production env contains this data to when logging.

(log) queue request received {
  OFFLINE_SALES_QUEUE: {},
}

 index.js File for Queue Handling

```
export default {
  async fetch(request, env, ctx) {
    console.log('queue request received', env);
    const message = 'Hello World! from Cloudflare Workers.';
    await env.OFFLINE_SALES_QUEUE.send({ message });
    return new Response('Message queued successfully.', { status: 200 });
  },
  async queue(batch, env) {
    console.log('initializingDB connection');

    await initializeDB(env);

    console.log('Received batch');
    console.log(`consumed from our queue: ${batch.messages}`);

    const Sale = DB(DBConstants.collections.sales);

    const doc = await Sale.insertOne({
      message: 'Testing Queues',
    });

    console.log('sale doc:', doc.insertedId);
  },
};
```

wrangler.toml File for Queue Configuration

queues.producers = [
  { queue = "offline-sales-queue", binding = "OFFLINE_SALES_QUEUE" }
]

queues.consumers = [
  { queue = "offline-sales-queue", retry_delay = 60, type = "http_pull", max_retries = 3, max_batch_size = 10, max_batch_timeout = 3 }
]

[env.production]

env.production.queues.producers = [
  { queue = "offline-sales-queue", binding = "OFFLINE_SALES_QUEUE" }
]

env.production.queues.consumers = [
  { queue = "offline-sales-queue", retry_delay = 60, type = "http_pull", max_retries = 3, max_batch_size = 10, max_batch_timeout = 3 }
]

**Comment by emily-shen** [comment]
Can you provide a link to a github repo with a minimal reproduction that shows the bug so we can test it? Thanks!

**Comment by DevAwais92** [comment]
Thank you very much, issue finally resolved by a senior dev.

**Comment by gregory** [comment]
@DevAwais92 I've had the same issue but in local - turns out setting max_batch_timeout was preventing the consumer to work in local.

**Comment by fred26s** [comment]
> 非常感谢，这个问题最终由一位资深开发人员解决了。



> Thank you very much, issue finally resolved by a senior dev.

what's happend? how to fix

**Comment by DevAwais92** [comment]
> > 非常感谢，这个问题最终由一位资深开发人员解决了。
> 
> > Thank you very much, issue finally resolved by a senior dev.
> 
> what's happend? how to fix

in our case, enviroments were declared in a wrong a way in wrangler.toml file due to which queues were causing issue in production
