### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by 9M6** [cloudflare/workers-sdk#6644]
### Which Cloudflare product(s) does this pertain to?

Queues

### What version(s) of the tool(s) are you using?

3.75.0

### What version of Node are you using?

v20.10.0

### What operating system and version are you using?

MacOS Sonoma

### Observed behavior
Queue can not be deleted since its attached to worker; worker is non-existent or was deleted before. 

### Expected behavior
Should delete the queue successfully.

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suite on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

**Comment by lrapoport-cf** [comment]
hi @9M6  :) we haven't heard from you in a while, so we’re going to close this issue for now. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include a repro and we will revisit and investigate further. thanks!
