### ISSUE TITLE
🚀 Feature Request: Add missing Node.js APIs (Parent Issue)

### ISSUE THREAD

**Issue by mikenomitch** [cloudflare/workers-sdk#6667]
### Describe the solution

This is a parent issue to drop requests for additional Node.js APIs that are not currently supported.

There are many potential APIs to support next, so this issue is meant to capture links to requests for specific missing methods so that we can better prioritize which to implement.

These missing APIs should only be missing when nodejs_compat_v2 is turned on (or nodejs_compat after Sept 23). This will likely (but not always) mean that you are seeing an unenv error like `[unenv] <method name> is not implemented yet!`. Make sure you're reporting issues when the latest compat is on.

For Cloudflare employees: Edit this issue and add references to any missing APIs that somebody is requesting. IE: Discord, forum, GH, Twitter links asking for a specific API.

For external developers: Feel free to comment if you have hit an unsupported Node.js API. Please make sure that you are using the latest nodejs_compat layer ("nodejs_compat_v2") prior to reporting.

API asks:

- `fs` general requests:
  - https://x.com/eashish93/status/1833217270450987400
- ADD OTHER REQUESTS

**Comment by demosjarco** [comment]
From `node:crypto`:
- `createECDH`
- `createCipher`
- `createCipheriv`
- `createDecipher`
- `createDecipheriv`
- `createHash`
- `createHmac`

These are missing upstream from `uncrypto` (inside `unenv`)

I'm looking to do ECIES with the [`standard-ecies`](https://www.npmjs.com/package/standard-ecies) package and it uses these crypto calls under the hood.

**Comment by mikenomitch** [comment]
We actually decided that a better way of tracking this was via Discussions. If you want to report or upvote a missing API go here: https://github.com/cloudflare/workerd/discussions/categories/node-js-apis

Closing this out in favor of alternative method of tracking!
