### ISSUE TITLE
🚀 Feature Request: Inject custom Esbuild plugins into build process (pages/workers)

### ISSUE THREAD

**Issue by yunusbayraktaroglu** [cloudflare/workers-sdk#6672]
### Describe the solution

In the workers/pages build bundle, I need to remove some lines of code that were added during development. I can achieve this with an esbuild plugin, but including a custom esbuild plugin would require canceling the entire default build process and writing my own.

**Comment by CarmenPopoviciu** [comment]
Thanks for reporting this! We're unlikely to expose Wrangler's esbuild options in the near future, but you can use Wrangler's --no-bundle flag if you'd like to skip Wrangler's esbuild step. https://developers.cloudflare.com/workers/wrangler/custom-builds/
