### ISSUE TITLE
🐛 BUG: `mongodb` can be imported but not successfully used with `nodejs_compat_v2`

### ISSUE THREAD

**Issue by alexbevi** [cloudflare/workers-sdk#6684]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler

### What version(s) of the tool(s) are you using?

3.76.0 [Wrangler]

### What version of Node are you using?

22.8.0

### What operating system and version are you using?

Mac Sonoma 14.6.1

### Observed behavior
The `mongodb` package was described as working in the [blog post from 09/09](https://blog.cloudflare.com/more-npm-packages-on-cloudflare-workers-combining-polyfills-and-native-code/), however it cannot actually be used to connect to a MongoDB cluster.

### Expected behavior

If the `mongodb` package can be imported the expectation would be that it's useable. Given that this package relies on `net.Socket` and `tls.TLSSocket` it's understandable that it doesn't work, however it would be worth clarifying this if the package is listed in the announcement as an example of a package that can be used successfully.

### Steps to reproduce

Basic steps were outlined in this [blog post](https://alexbevi.com/blog/2024/09/11/why-cloudflare-workers-dont-work-with-mongodb/)

**Comment by irvinebroque** [comment]
Hey Alex this is our bad and confusing, we will update and clarify

**Comment by irvinebroque** [comment]
Blog post is now updated to clarify

**Comment by ricky11** [comment]
Indeed, it confused me, i did see monodb as supported, and went down a rabbit hole to get it working, and 2 weeks later, found this.. apart from updating the docs, anychange of adding net.Socket or tls.TLSocket support in workers runtime?

**Comment by vicb** [comment]
See [the discussion on the workerd repo](https://github.com/cloudflare/workerd/discussions/2721) for further information

**Comment by vicb** [comment]
This should work now! (see the thread linked in my previous message)
