### ISSUE TITLE
🐛 BUG: local RPC between cloudflare workers giving error 

### ISSUE THREAD

**Issue by nitbu** [cloudflare/workers-sdk#6695]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.76.0

### What operating system and version are you using?

mac sonoma 14.1.1

### Describe the Bug

main.toml

name = "main"
main = "src/main.js"
compatibility_date = "2024-09-03"
compatibility_flags = ["nodejs_compat"]

[[services]]
  binding = "worker2"
  service = "worker2"

worker2.toml

name = "worker2"
main = "src/worker2.js"
compatibility_date = "2024-09-03"
compatibility_flags = ["nodejs_compat"]

main.js

export default {
	async fetch(request, env, ctx) {
		const worker2result = await env.worker2.none()
		console.log(`worker2result`, worker2result)
                return new Response('END')
	},
}

worker2.js

import { WorkerEntrypoint } from "cloudflare:workers";

export class worker2 extends WorkerEntrypoint {
  async none() { return "this is a returned string" }
}

Error:
Uncaught Error: Dynamic require of "cloudflare:workers" is not supported

I'm just trying to get main worker to call a function (none()) from worker2. This is being run locally and I am running npx wrangler dev -c main.toml for one worker and -c worker2.toml for the other worker.

So I am trying to find the most basic code that will allow local RPC between two workers where the second worker is only being accessed by the first main worker over rpc but I am getting an error. This is all being done locally.

**Comment by geelen** [comment]
Ah ok I was able to reproduce. Add `export default {}` to `worker2.js` and you should be able to start the dev server, then you'll get `TypeError: The RPC receiver does not implement the method "none"`. Then add `entrypoint = "worker2"` to your `[[services]]` section and it should work.

Or, change the code in `worker2.js` to `export default class worker2 extends WorkerEntrypoint` and leave your `[[services]]` section as-is.

If this fixes your problem, would you mind closing the issue?

Looks like we have a problem with workers without default exports in dev (and likely in production too). I wonder if we want to try to support that, or should just give a more descriptive error.

**Comment by nitbu** [comment]
thank you.

to be clear:

worker2.js

import { WorkerEntrypoint } from "cloudflare:workers"

export default class worker2 extends WorkerEntrypoint {
  async none() { return "this is a returned string" }
}

with everything else left the same worked correctly.
