### ISSUE TITLE
🐛 BUG:Broken Link to Templates

### ISSUE THREAD

**Issue by akdombrowski** [cloudflare/workers-sdk#6711]
### Which Cloudflare product(s) does this pertain to?

C3 (npm create cloudflare)

### What version(s) of the tool(s) are you using?

Docs/README

### What operating system and version are you using?

WSL

### Observed behavior
Link to [templates](https://github.com/cloudflare/workers-sdk/tree/main/templates) in the README in this repo and on the [docs site](https://developers.cloudflare.com/workers/get-started/quickstarts/#:~:text=Cloudflare%20templates%20repository,repository%20%E2%86%97.) sends you to a GH 404 missing file page.

### Expected behavior
Link sends you to a list of templates or remove the link.

### Steps to reproduce
Please provide the following:
- Go to README
- click on `templates` link under the table in the Directory section
- or go to the docs link provided above and click on the `Cloudflare templates repository ↗` link.

**Comment by penalosa** [comment]
Thanks for raising this! We recently removed templates from the repo, and now recommend starting your project with `npm create cloudflare`.

PRs to remove references: https://github.com/cloudflare/cloudflare-docs/pull/16858 & https://github.com/cloudflare/workers-sdk/pull/6726
