### ISSUE TITLE
🐛 BUG: Uncaught TypeError: WebAssembly.Instance(): Import #3 "env": module is not an object or function

### ISSUE THREAD

**Issue by SnowyThinker** [cloudflare/workers-sdk#6718]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

wrangler 3.78.2

### What version of Node are you using?

v18.16.0

### What operating system and version are you using?

13.3.1 (a) (22E772610a)

### Describe the Bug

npx wrangler deploy

⛅️ wrangler 3.78.2
-------------------

Running custom build: cargo install -q worker-build && worker-build --release
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Finished release [optimized] target(s) in 0.11s
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: found wasm-opt at "/usr/local/bin/wasm-opt"
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: ✨   Done in 1.68s
[INFO]: 📦   Your wasm pkg is ready to publish at /Users/andrew/workbench/souce/rust/rust-saas-worker/build.

  shim.mjs  16.8kb

⚡ Done in 12ms
Total Upload: 629.76 KiB / gzip: 276.16 KiB
Your worker has access to the following bindings:
- Vars:
  - WORKERS_RS_VERSION: "0.0.9"

✘ [ERROR] A request to the Cloudflare API (/accounts/96caf513731edfceef7fbfe4084e9222/workers/scripts/rust-saas-worker/versions) failed.

  Uncaught TypeError: WebAssembly.Instance(): Import #3 "env": module is not an object or function
    at null.<anonymous>
  (file:///Users/andrew/workbench/souce/rust/rust-saas-worker/build/worker/shim.mjs:1:2748)
   [code: 10021]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to provide a reproduction repo that demonstrates the issue?

**Comment by lrapoport-cf** [comment]
hi @SnowyThinker :) we haven't heard from you in a while, so we’re going to close this issue for now. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and repro and we will revisit and investigate further. thanks!
