### ISSUE TITLE
🐛 BUG: Can not delete R2 event notification

### ISSUE THREAD

**Issue by michaelwittig** [cloudflare/workers-sdk#6748]
### Which Cloudflare product(s) does this pertain to?

R2

### What version(s) of the tool(s) are you using?

3.78.4 [Wrangler]

### What version of Node are you using?

20.11.0

### What operating system and version are you using?

macOS 14.6.1

### Observed behavior
```
npx wrangler r2 bucket notification delete bucketav-test --queue bucketav-sophos-cloudflare

 ⛅️ wrangler 3.78.4
-------------------

Disabling event notifications for "bucketav-test" to queue bucketav-sophos-cloudflare...

✘ [ERROR] A request to the Cloudflare API (/accounts/e647a3934e30cbd6e38ccc419c9e7208/event_notifications/r2/bucketav-test/configuration/queues/1fb4dc677de24aa686bd7b89d2434a58) failed.

  workers.api.error.invalid_r2_event_notification_configuration [code: 11014]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

### Expected behavior
No error. Event configuration should be deleted.

### Steps to reproduce
```
npx wrangler r2 bucket create bucketav-test3
npx wrangler queues create bucketav-test3
npx wrangler r2 bucket notification create bucketav-test3 --queue bucketav-test3 --event-type object-create
npx wrangler r2 bucket notification delete bucketav-test3 --queue bucketav-test3     

✘ [ERROR] A request to the Cloudflare API (/accounts/e647a3934e30cbd6e38ccc419c9e7208/event_notifications/r2/bucketav-test3/configuration/queues/35f268e4704e462ca22c4b289708bfbe) failed.
```

**Comment by lrapoport-cf** [comment]
@jonesphillip can your team please take a look at this?

**Comment by bthwaites** [comment]
Hi @michaelwittig 

I'm not able to reproduce the issue on 3.78.4 or on 3.83.0 (latest), and regardless I don't expect us to ever return 11014 on a notification delete request. It's possible that we did return that error in the past and that we already fixed this issue since you created this ticket. Can you please confirm whether the issue is still happening on the latest wrangler version?

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to open a new issue with more details and we can investigate further.
