### ISSUE TITLE
🐛 BUG: wrangler secret put has breaking change with versions

### ISSUE THREAD

**Issue by huv1k** [cloudflare/workers-sdk#6763]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.78.5

### What version of Node are you using?

v20.16.0

### What operating system and version are you using?

macOS 14.6.1 + Ubuntu Jammy (22.04.5 LTS)

### Observed behavior
We have our CI/CD pipeline, where we deploy workers like `wrangler deploy --env production --outdir dist` and later on in different steps we set secrets with current commit sha `git rev-parse HEAD  2>&1 | wrangler secret put COMMIT_SHA --env production` this was working fine. We are not always deploying secrets and workers at the same time. We modify secrets more often than we deploy workers. But we started seeing an error:
```shell
Secret edit failed. You attempted to modify a secret, but the latest version of your Worker isn't currently deployed. Please ensure that the latest version of your Worker is fully deployed (wrangler versions deploy) before modifying secrets. Alternatively, you can use the Cloudflare dashboard to modify secrets and deploy the version.
  
Note: This limitation will be addressed in an upcoming release.
```
This is `breaking` change without any notification and which upcoming release will fix it? There is no information whatsoever. Why is there not used `compatibility_date` inside `wrangler.toml` to handle such a change? 

### Expected behavior
I would expect this behavior would work as before, without changing `compatibility_date`, otherwise it should be properly documented and provide the exact date when the "upcoming" release is going to fix it. Another option is to provide a link to an explanation or provide at least "some" documentation. This is a poorly executed breaking change. 

### Steps to reproduce
Please provide the following:
1. Deploy worker using `wrangler deploy`
2. Update secret using `wrangler secret put`

**Comment by IgorMinar** [comment]
This is a bummer.. sorry about that.

I took a quick look and this seems to have been introduced in https://github.com/cloudflare/workers-sdk/pull/5930 by @WalshyDev and approved by @tanushree-sharma on the PM side.

@tanushree-sharma can you please help address this via a follow up and also help clarify when the "upcoming release" is coming? Thanks a bunch!

**Comment by tanushree-sharma** [comment]
👋🏼 @huv1k. Sorry you're running into this. 

Are you using the [`wrangler versions`](https://developers.cloudflare.com/workers/wrangler/commands/#upload) commands to upload/deploy Workers? It doesn't sound like you are but want to confirm.

**Comment by huv1k** [comment]
No we are using just deploy

**Comment by tanushree-sharma** [comment]
@huv1k We've been digging into this and believe you're seeing this as a result of concurrent operations that come from `wrangler deploy` and `wrangler secret put`. Running these operations close together triggers a race condition. 

We're going to work to make these operations faster to minimize chances of running into this. In the meantime when you update both your Worker and it's secrets try:

- Using the [secret bulk command](https://developers.cloudflare.com/workers/wrangler/commands/#secretbulk) (when updating multiple secrets) commands
- and updating your secret first `wrangler secret put` and then doing a `wrangler deploy`

Using these should minimize when the race condition is triggered.

**Comment by jiri-prokop-pb** [comment]
@tanushree-sharma We tried to follow your suggestion, together with additional instruction we got from the support that is about adding a slight delay of a few seconds but we still see that error.

When I flipped `wrangler secret put` and `wranger deploy` then it works. Do you see any harm doing the two commands in the reversed order (deploy  then secret put) with a delay of several seconds or minutes between them? Or is your suggested order important?

**Comment by tanushree-sharma** [comment]
I don't see harm, as long as you're okay with applying the secret after `wrangler deploy`.

**Comment by alexanderniebuhr** [comment]
I just faced this again, using wrangler action inside a GitHub runner with its native support for ˋwrangler secret bulkˋ. I don’t think it is fixed.

**Comment by alexkli** [comment]
Same here. I reported this again at #10585. Our use case is automatic secret rotation separate from code deployment.
