### ISSUE TITLE
🚀 Feature Request: It isn't clear that R2 buckets bound in wrangler dev are local

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#6811]
### Describe the solution

I'm sure R2 isn't the only product with this issue, but:

Here's the output of wrangler dev with a bucket bound:

```
> wrangler dev ./src/index.ts


 ⛅️ wrangler 3.78.4 (update available 3.78.8)
-------------------------------------------------------

Your worker has access to the following bindings:
- R2 Buckets:
  - BUCKET: asdfasdf
⎔ Starting local server...
[wrangler:inf] Ready on http://localhost:8787
```

When you have a bucket on R2 named asdfasdf, it's really confusing why your Worker is 404ing fetches from that bucket in `wrangler dev`.

**Comment by isaac-mcfadyen** [comment]
Wonder if this should be a part of a bigger UX improvement?
Even a simple `BINDING_NAME: <name> (local mode)` would be much better than the current.
