### ISSUE TITLE
🐛 BUG: Wrangler attempts to login when using --local if previously logged in

### ISSUE THREAD

**Issue by Codex-** [cloudflare/workers-sdk#6842]
### Which Cloudflare product(s) does this pertain to?

KV, Wrangler, Miniflare

### What version(s) of the tool(s) are you using?

3.78.10 [wrangler]

### What version of Node are you using?

20.17.0

### What operating system and version are you using?

Mac Sequoia 15.0 (24A335)

### Observed behaviour

If you have previously performed a `wrangler login` and then attempt to use a command that supports `--local` and your session has expired, `wrangler` opens a browser to re-auth before attempting to execute the command.

```
pnpm exec wrangler kv key put "test-token" "1" --namespace-id wrangler-local-id  --local
```

### Expected behaviour

Usage of `--local` does not invoke a re-auth

### Steps to reproduce

I was able to reproduce this on an older macos system, and on a windows 11 system (with both powershell, and debian wsl).

- Perform a `wrangler login`
- Wait for expiry
- Attempt to use a command that invokes `--local`
  - `pnpm exec wrangler kv key put "test-token" "1" --namespace-id wrangler-local-id  --local`
- Should not attempt a re-auth that

## Workaround

- Perform a `wrangler logout` and ignore the opened browser window
- After this, usage of `--local` works as expected

**Comment by emily-shen** [comment]
Hey! Sorry for the delay responding. Unfortunately I've not been able to reproduce this. It would be good to know how long you've been waiting for expiry? Also, did you find this bug in a clean project? If not, any specifics about your project setup and a repo with a minimal reproduction would be helpful as well. Thanks :) 

(For reference, to test this I've gone into the `.wrangler/default.toml` file (usually somewhere in your home directory) and modified the expiry time and refresh tokens. The command without the --local flag prompts a relogin, but works fine with the local flag.)

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to open a new issue with more details and we can investigate further.
