### ISSUE TITLE
🐛 BUG:A request to the Cloudflare API (/accounts/382e42b780c451838ecdabbb744594bf/workers/scripts/my-project) failed.    Uncaught Error: Dynamic require of "node:stream" is not supported     at null.<anonymous> (worker.js:9:11)     at null.<anonymous>   (file:///C:/Users/nguye/my-project/node_modules/unenv/runtime/node/console/index.mjs:1:26)     at null.<anonymous> (worker.js:988:3)    [code: 10021]

### ISSUE THREAD

**Issue by thuanent** [cloudflare/workers-sdk#6853]
### Which Cloudflare product(s) does this pertain to?

Workers AI

### What version(s) of the tool(s) are you using?

wrangler 3.78.12

### What operating system and version are you using?

Window11

### Describe the Bug

🐛 BUG:A request to the Cloudflare API (/accounts/382e42b780c451838ecdabbb744594bf/workers/scripts/my-project) failed.    Uncaught Error: Dynamic require of "node:stream" is not supported     at null.<anonymous> (worker.js:9:11)     at null.<anonymous>   (file:///C:/Users/nguye/my-project/node_modules/unenv/runtime/node/console/index.mjs:1:26)     at null.<anonymous> (worker.js:988:3)    [code: 10021]

**Comment by emily-shen** [comment]
Hiya, can you try the prelease in this PR here: https://github.com/cloudflare/workers-sdk/pull/6894#issuecomment-2393617974 and see if you get a more helpful error. Can you also check if you've definitely got a default export on your worker script?

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to open a new issue with more details and we can investigate further.
