### ISSUE TITLE
🐛 BUG: Infinite building with --x-dev-env and an app with a build 

### ISSUE THREAD

**Issue by zwily** [cloudflare/workers-sdk#6876]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.79.0 [Wrangler]

### What version of Node are you using?

20

### What operating system and version are you using?

Man Sequoia

### Observed behavior
When I have a build process (remix, in this case), static assets on, and use `wrangler dev --x-dev-env`, wrangler gets into an infinite loop of rebuilding my app.

Clone github.com:zwily/remix-wrangler-much-restarting and run `npm i && npm run dev`. I also tested this with wrangler HEAD, which includes `--x-dev-env` on by default, and it still happens.

If I comment out `build.command` from `wrangler.toml` it doesn't happen. Should I just make sure I always build before deploy and remove that line?

### Please provide a link to a minimal reproduction

https://github.com/zwily/remix-wrangler-much-restarting

**Comment by threepointone** [comment]
@RamIdeas

**Comment by RamIdeas** [comment]
Taking a look now

cc @penalosa

**Comment by RamIdeas** [comment]
Got a fix going here https://github.com/cloudflare/workers-sdk/pull/6881

Notably, you'll also need to set `build.watch_dir = ./app`

**Comment by zwily** [comment]
> Got a fix going here #6881
> 
> Notably, you'll also need to set `build.watch_dir = ./app`

We'll need that even when your PR is merged?

**Comment by RamIdeas** [comment]
> > Got a fix going here #6881
> > Notably, you'll also need to set `build.watch_dir = ./app`
> 
> We'll need that even when your PR is merged?

Yeah fixing the bug made me think I broke something else. But the default `build.watch_dir` is `./src`, so once I prevented the custom build infinite loop, changes to `./app/routes/_index.tsx` didn't run the custom build until I added:

```diff
[build]
command = "npm run build"
+ watch_dir = "./app"
```

**Comment by threepointone** [comment]
@RamIdeas That seems like a bug too, since that file is included in the worker bundle and should trigger a worker reload anyway, even without setting watch_dir. Does this problem exist even without --x-dev-env?

**Comment by threepointone** [comment]
@zwily looking at youre repo, why are you calling `remix build` as a custom build at all? `npm run dev` is running remix in manual mode, and rebuilds the app anway.

**Comment by zwily** [comment]
Honestly, just because that’s the way the remix workers template has always been. The double builds have always bothered me. On Oct 3, 2024, at 2:54 AM, Sunil Pai ***@***.***> wrote:﻿
@zwily looking at youre repo, why are you calling remix build as a custom build at all? npm run dev is running remix in manual mode, and rebuilds the app anway.

**Comment by threepointone** [comment]
@ramideas Does this problem exist even without --x-dev-env?

**Comment by RamIdeas** [comment]
The e2e test runs with the flag disabled and enabled which confirms it does not. The bug was caused by explicitly retriggering the whole flow in –x-dev-env so makes sense it did not appear in the old flow

**Comment by threepointone** [comment]
I should clarify. We shouldn't have to put `./app` as watch_dir, because we're using `remix dev` which generates the file that's fed into `wrangler dev`, and should retrigger a rebuild anyway. That works fine with without --x-dev-env, even with a custom build, and even if we're watching another directory. Can you explain to me what the bug with --x-dev-env was? And whether you need to add `./app` as watch_dir now? (because you dideally shouldn't)

**Comment by RamIdeas** [comment]
I think I know what you mean. If this works in the old flow, can you explain how? From my understanding, the wranger.toml has `main = "./build/index.js"` which wrangler will watch. But what causes that file to be updated, i.e what causes the custom build to run, when files in `./app` change?

**Comment by threepointone** [comment]
`remix dev` generates `./build/index.js` anytime anything in the ./app import chain changes

**Comment by RamIdeas** [comment]
But `remix dev` wasn't mentioned here. If though, `wrangler dev` was running without a custom build and `remix dev` was running in a separate terminal, then it would just work™️

**Comment by threepointone** [comment]
In the repro https://github.com/zwily/remix-wrangler-much-restarting/blob/2490e3c018d357d1be57270018f12926d4990980/package.json#L9 

Here remix is running in manual mode `remix dev --manual -c "wrangler dev"`

**Comment by RamIdeas** [comment]
> My question, setting watch_dir = ./app shouldn't be required in this usecase, so is it so even with --x-dev-env / after your fix?

Yeah good catch. watch_dir is not required if using `remix dev`, only if using `remix build` in a custom build

**Comment by threepointone** [comment]
ok dope, thank you very much for clarifying! 

I think we need to fix the template and remove `npm run build` as the custom build step in the remix template, that's not required either

**Comment by zwily** [comment]
I must be doing something wrong because this is still infinite building with 3.80.0 on this app: github.com:zwily/remix-wrangler-much-restarting

I updated it for wrangler 3.80.0, removed the custom build and watch dir, and now when I `npm run dev` and then save something in `app/` I get this:

```
➜ ~/Source/my-remix-app2 (main|✚3) $ npm run dev

> dev
> remix dev --manual -c "npm start"


 💿  remix dev

 info  building...
 info  built (314ms)

> start
> wrangler dev ./build/index.js


 ⛅️ wrangler 3.80.0
-------------------

[wrangler:inf] Ready on http://localhost:8787
⎔ Starting local server...
[REMIX DEV] 62100d3d ready

[wrangler:inf] GET / 200 OK (13ms)
[wrangler:inf] GET / 200 OK (9ms)
[wrangler:inf] GET / 200 OK (7ms)
 info  rebuilding... (~ app/routes/_index.tsx)
⎔ Reloading local server...
 info  rebuilt (119ms)
[REMIX DEV] 62100d3d ready
 info  app server ready (121ms)
 info  hmr

⎔ Reloading local server...
[REMIX DEV] 62100d3d ready
⎔ Reloading local server...
[REMIX DEV] 62100d3d ready
⎔ Reloading local server...
[REMIX DEV] 62100d3d ready
⎔ Reloading local server...
[REMIX DEV] 62100d3d ready
..........
```

**Comment by zwily** [comment]
Also, I just pushed an update to it that makes it match my proposed update for the official remix template `classic-remix-compiler/cloudflare-workers`. You can add `--no-x-dev-env` to the `start` command in `package.json` and verify that without x-dev-env, it doesn't restart infinitely, and with it it does.

**Comment by zwily** [comment]
I've noticed another issue too, which I suspect is unrelated, but similar. Using the same sample repo (but adding --no-x-dev-env to avoid the infinite reloading), do `npm run dev` and then watch your console while saving `app/routes/_index.tsx`. You'll notice that as you save it more and more times, you see the server reloading more and more. So on the first save I get this output:

```
 info  rebuilding... (~ app/routes/_index.tsx)
⎔ Reloading local server...
⎔ Reloading local server...
[REMIX DEV] e7efd9e1 ready

 info  app server ready (226ms)
 info  hmr
⎔ Reloading local server...
[REMIX DEV] e7efd9e1 ready
[REMIX DEV] e7efd9e1 ready
```

On the 10th save:

```
 info  rebuilding... (~ app/routes/_index.tsx)
⎔ Reloading local server...
⎔ Reloading local server...
⎔ Reloading local server...
⎔ Reloading local server...
⎔ Reloading local server...
⎔ Reloading local server...
⎔ Reloading local server...
[REMIX DEV] e7efd9e1 ready

 info  app server ready (329ms)
 info  hmr
⎔ Reloading local server...
⎔ Reloading local server...
⎔ Reloading local server...
[REMIX DEV] e7efd9e1 ready
[REMIX DEV] e7efd9e1 ready
```

This has been happening for awhile and I've gotten used to just restarting the process periodically, but can you think of what might be causing this? Should I open a new ticket? Possible it's remix's fault? Or maybe this is fixed in the new dev env?

**Comment by threepointone** [comment]
I can confirm that infinite reloads happen with --x-dev-env on, and doesn't without, on a big standard remix app (I'm using https://github.com/threepointone/remix-workers-app)

**Comment by zwily** [comment]
This fix seems to work. And my last comment about the server reloads increasing every time a file is saved also seems to be addressed in `--x-dev-env`. 

Thank you!
