### ISSUE TITLE
🐛 BUG: Plugin "unenv-cloudflare" returned a non-absolute path: buffer (set a namespace if this is not  a file path)

### ISSUE THREAD

**Issue by oyeesam** [cloudflare/workers-sdk#6895]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

wrangler@3.80.0

### What operating system and version are you using?

v20.11.0

### Observed behavior
I am using [iron-session](https://www.npmjs.com/package/iron-session) package, which with `wrangler prevew` command is giving me following error

```

✘ [ERROR] Plugin "unenv-cloudflare" returned a non-absolute path: buffer (set a namespace if this is not
 a file path)

    ../node_modules/.pnpm/iron-webcrypto@0.2.8/node_modules/iron-webcrypto/dist/index.js:3:23:
      3 │ var index_js = require('buffer/index.js');
        ╵                        ~~~~~~~~~~~~~~~~~



✘ [ERROR] Failed to build Functions at ./functions.

```

I am using Remix

### Please provide any relevant error logs

✘ [ERROR] Plugin "unenv-cloudflare" returned a non-absolute path: buffer (set a namespace if this is not
 a file path)

    ../node_modules/.pnpm/iron-webcrypto@0.2.8/node_modules/iron-webcrypto/dist/index.js:3:23:
      3 │ var index_js = require('buffer/index.js');
        ╵                        ~~~~~~~~~~~~~~~~~

✘ [ERROR] Failed to build Functions at ./functions.

**Comment by emily-shen** [comment]
Hiya, this looks like an issue with the `iron-webcrypto` package. It looks like you're using quite an old version there, are you able to update `iron-session` which uses a more recent version of `iron-webcrypto`? Think `iron-webcrypto` needs to be a later than 0.4.0.

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to open a new issue with more details and we can investigate further.
