### ISSUE TITLE
🐛 BUG: Uncaught TypeError: utils.inherits is not a function

### ISSUE THREAD

**Issue by nkuba** [cloudflare/workers-sdk#6896]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler

### What version(s) of the tool(s) are you using?

3.80.0 [Wrangler]

### What version of Node are you using?

20.17.0

### What operating system and version are you using?

Mac Sonoma 14.6.1

### Observed behavior

I have a worker which imports `ethers@5.7.2` library. When I switched to `compatibility_flags = ["nodejs_compat_v2"]` it started throwing:
```
✘ [ERROR] service core:user:error-example: Uncaught TypeError: utils.inherits is not a function

    at null.<anonymous> (index.js:7544:11) in
  node_modules/.pnpm/hash.js@1.1.7/node_modules/hash.js/lib/hash/sha/1.js
    at null.<anonymous> (index.js:12:50) in __require
    at null.<anonymous> (index.js:8295:20) in
  node_modules/.pnpm/hash.js@1.1.7/node_modules/hash.js/lib/hash/sha.js
    at null.<anonymous> (index.js:12:50) in __require
    at null.<anonymous> (index.js:8812:17) in
  node_modules/.pnpm/hash.js@1.1.7/node_modules/hash.js/lib/hash.js
    at null.<anonymous> (index.js:12:50) in __require
    at null.<anonymous> (index.js:15900:28)
```

### Expected behavior

The worker should start.

### Steps to reproduce

1. Clone the https://github.com/nkuba/cf-workers-error-example repository
2. Run `pnpm install`
3. Run `pnpm dev`

### Please provide a link to a minimal reproduction

https://github.com/nkuba/cf-workers-error-example

### Please provide any relevant error logs

```
> wrangler dev

 ⛅️ wrangler 3.80.0
-------------------

[wrangler:inf] Ready on http://localhost:8787
⎔ Starting local server...
✘ [ERROR] service core:user:error-example: Uncaught TypeError: utils.inherits is not a function

    at null.<anonymous> (index.js:7544:11) in
  node_modules/.pnpm/hash.js@1.1.7/node_modules/hash.js/lib/hash/sha/1.js
    at null.<anonymous> (index.js:12:50) in __require
    at null.<anonymous> (index.js:8295:20) in
  node_modules/.pnpm/hash.js@1.1.7/node_modules/hash.js/lib/hash/sha.js
    at null.<anonymous> (index.js:12:50) in __require
    at null.<anonymous> (index.js:8812:17) in
  node_modules/.pnpm/hash.js@1.1.7/node_modules/hash.js/lib/hash.js
    at null.<anonymous> (index.js:12:50) in __require
    at null.<anonymous> (index.js:15900:28)



✘ [ERROR] The Workers runtime failed to start. There is likely additional logging output above.
```

**Comment by ammubhave** [comment]
Same here. libraries like `inngest` are failing to be imported.

**Comment by vicb** [comment]
Root cause is that module is not properly imported:

<img width="446" alt="image" src="https://github.com/user-attachments/assets/0558978d-93d5-400d-bda3-18efa51953c5">

here `inherits2` should be a function while it is a module
