### ISSUE TITLE
🐛 BUG: `minify` changes names of React components (`keepNames: true` fixes)

### ISSUE THREAD

**Issue by mhart** [cloudflare/workers-sdk#6901]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.80.0

### What operating system and version are you using?

Mac Sonoma 14.6.1

### Observed behavior

With `minify = true` in my Next.js app with stream resuming, I see the following errors in my Worker:

```
✘ [ERROR] ⨯ Error: Expected the resume to render <n5> in this slot but instead it rendered <Il>. The tree doesn't match so React will fallback to client rendering.
```

This does not occur if I use `minify = false`.

### Explanation

This is because `esbuild` has mangled the names when building with minification, so the React component names in the Worker JS script used for server-side rendering no longer match the component names used when the static shell was generated at build time that React is trying to render with.

The specifics of this don't matter too much – it's more that esbuild's minification is pretty aggressive and this name mangling would probably affect more use cases than just this one – however, it can be relaxed with the use of [esbuild's `keepNames` option](https://esbuild.github.io/api/#keep-names).

If I manually modify wrangler's `cli.js` to add `keepNames: true` as an option to the `esbuild.build()` call in `bundleWorker()`, but keep `minify = true`, this error goes away.

So my suggestion to fix this issue would be to add `keepNames: true` to the esbuild options – or expose `keepNames` as a wrangler option (though this seems unnecessarily specific) – or expose any esbuild option to wrangler (I would love this, but I know there's coupling arguments against this)

### Example results

Here are some example results to show how much impact this has on minification:

`minify: false`:

```
Total Upload: 3653.57 KiB / gzip: 822.45 KiB
```

`minify: true, keepNames: false` (or unspecified):

```
Total Upload: 1834.57 KiB / gzip: 654.76 KiB
```

`minify: true, keepNames: true`:

```
Total Upload: 1888.91 KiB / gzip: 672.51 KiB
```

So it results in a 2.7% increase in size compared with full minification – but considering the (uncompressed) minified result is half of the unminified result, still well worth it for a reduction in parsing/compilation time at cold start.

My suggestion would just be to add `keepNames: true` regardless – but I'll leave that up to the team to mull over.

**Comment by threepointone** [comment]
awesome, I think `keepNames: true` is worth the cost for this

**Comment by threepointone** [comment]
https://github.com/cloudflare/workers-sdk/pull/6902
