### ISSUE TITLE
🐛 BUG: on by default: –x-dev-env causes issue with multiple accounts

### ISSUE THREAD

**Issue by jdanyow** [cloudflare/workers-sdk#6947]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

0.0.0-3fa846ec2

### What operating system and version are you using?

Mac

### Describe the Bug

When I upgraded from 3.79.0 to 3.80.3 I started seeing the following error when running `wrangler dev --remote`.

```
✘ [ERROR] More than one account available but unable to select one in non-interactive mode.

  Please set the appropriate `account_id` in your `wrangler.toml` file.
  Available accounts are (`<name>`: `<account_id>`):
     ...redacted...
```

This didn't make sense because my wrangler.toml does have an account_id specified.

I went to the [versions page](https://www.npmjs.com/package/wrangler/v/0.0.0-3fa846ec2?activeTab=versions) and tried out each prerelease version after 3.79.0 until I arrived at `0.0.0-3fa846ec2` which triggered the issue.

Looking at [the commit](https://github.com/cloudflare/workers-sdk/commit/3fa846ec2), there's this line, which unblocked me:

> If you experience any issues, you can disable the flag with `--x-dev-env=false`. Please also let us know by opening an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose.

Using `--x-dev-env=false` fixes the issue!

**Comment by emily-shen** [comment]
cc @penalosa and @RamIdeas
