### ISSUE TITLE
🚀 Feature Request: Remove checked-fetch & allow fetches to custom ports in wrangler dev

### ISSUE THREAD

**Issue by penalosa** [cloudflare/workers-sdk#6950]
The limitation around fetching custom ports has been removed when deployed, so we should remove the check locally. See https://developers.cloudflare.com/workers/configuration/compatibility-dates/#allow-specifying-a-custom-port-when-making-a-subrequest-with-the-fetch-api for more context

**Comment by petebacondarwin** [comment]
Fix is here https://github.com/cloudflare/workers-sdk/pull/7038

But not sure if the runtime is actually fixed...
