### ISSUE TITLE
🐛 BUG: workerd installed twice in node_modules

### ISSUE THREAD

**Issue by gkiely** [cloudflare/workers-sdk#6951]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.80.4

### What version of Node are you using?

22.9.0

### What operating system and version are you using?

macOS Monterey 12.7

### Describe the Bug
Installs `workerd` twice
- `node_modules/@cloudflare/workerd-{OS}-{ARCH}/bin/workerd`
- `node_modules/workerd/bin/workerd`

### Expected behavior
Should install `workerd` once

### Steps to reproduce
```sh
npm create vite@latest
npm i wrangler
```
> Check node_modules

### Please provide a link to a minimal reproduction

https://codesandbox.io/p/devbox/6nlj34

### Please provide any relevant error logs

![image](https://github.com/user-attachments/assets/9a267e01-4441-49f9-a4e3-e63cbdbf1e55)

**Comment by emily-shen** [comment]
Hi, this is intentional and doesn't actually install anything twice. The post install step of the workerd package copies the binary from the OS specific package to make starting workerd faster.

**Comment by gkiely** [comment]
@emily-shen can this be a symlink or moved instead of a copied or is it necessary for there to be 2?
