### ISSUE TITLE
🐛 BUG: dyld error on earlier MacOS versions

### ISSUE THREAD

**Issue by bencondon** [cloudflare/workers-sdk#6956]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.80.4 [Wrangler]

### What version of Node are you using?

20.10.0

### What operating system and version are you using?

MacOS Big Sur 11.7.10

### Observed behavior

A `dyld: Symbol not found` error is thrown when running `wrangler` on earlier MacOS versions.

I've observed the error being thrown on the following commands: 

- `wrangler dev`
- `wrangler d1 execute`
- `wrangler r2 object put`

I've observed that the latest version to work as expected is [wrangler 3.78.9](https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.78.9), i.e. the error is thrown from [wrangler 3.78.10](https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.78.10) onwards.

This issue seems to be related to another issue I had previously reported: [🐛 BUG: Minimum required version for local development #3307](https://github.com/cloudflare/workers-sdk/issues/3307).

### Expected behavior

No `dyld: Symbol not found` error is thrown.

### Steps to reproduce

1. Run `npm create cloudflare@latest` to setup a new worker
2. Run `npx wrangler dev` to start a local development server
3. Throws error

```
 ⛅️ wrangler 3.80.4
-------------------

⎔ Starting local server...
✘ [ERROR] dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv

    Referenced from:
  /Users/<User>/Desktop/<Project>/node_modules/@cloudflare/workerd-darwin-64/bin/workerd
  (which was built for Mac OS X 13.5)
    Expected in: /usr/lib/libc++.1.dylib

/Users/<User>/Desktop/<Project>/node_modules/wrangler/wrangler-dist/cli.js:29768
            throw a;
            ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

1. Run `npm create cloudflare@latest` to setup a new worker
2. Run `wrangler r2 object put` to put an object in an r2 bucket
3. Throws error

```
 ⛅️ wrangler 3.80.4
-------------------

Creating object "<Object>" in bucket "<Bucket>".
dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/<User>/Desktop/<Project>/node_modules/@cloudflare/workerd-darwin-64/bin/workerd (which was built for Mac OS X 13.5)
  Expected in: /usr/lib/libc++.1.dylib

Error: write EPIPE
```

1. Run `npm create cloudflare@latest` to setup a new worker
2. Run `wrangler d1 execute` to execute an sql file on a d1 database
3. Throws error

```
 ⛅️ wrangler 3.80.4
-------------------

🌀 Executing on local database <Database> (<UUID>) from .wrangler/state/v3/d1:
🌀 To execute on your remote database, add a --remote flag to your wrangler command.
dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/<User>/Desktop/<Project>/node_modules/@cloudflare/workerd-darwin-64/bin/workerd (which was built for Mac OS X 13.5)
  Expected in: /usr/lib/libc++.1.dylib

Error: write EPIPE
```

**Comment by emily-shen** [comment]
Hey unfortunately we don't support end of life OS versions, in line with [workerd](https://github.com/cloudflare/workerd?tab=readme-ov-file#running-workerd). We were actually just about to add this to the cloudflare wrangler docs literally today, so apologies for the inconvenience 😅

**Comment by AndrewRayCode** [comment]
I'm on a 2014 Macbook, which cannot be upgraded past Big Sur. Seems like I'm SOL for doing local development with wrangler?

**Comment by LukePammant** [comment]
I know this is old (not as old as my laptop!) but I wanted to mention that I've managed to work around this by using a docker dev container. Hope this helps anyone else stuck w/ old hardware :)

**Comment by gavan-x** [comment]
@LukePammant could you elaborate on your tooling setup and dependencies on your docker container? 
What docker image are you running?

wrangler v4.16.1 is the last version that has been compiled to support MacOS 12.7.6 without the node errors.
Cloudflare should support nodejs not base its decisions on an OS.
wrangler is not a MacOS tool but a nodejs one. 

Supporting nodejs on all platforms is a no brainer. 

Give it time these dyld error will pop up everywhere else, they 'll get the memo, I am quite sure that Intel based macs on Monterey makes a ~10% off dev installs of wrangler.

**Comment by LukePammant** [comment]
> [@LukePammant](https://github.com/LukePammant) could you elaborate on your tooling setup and dependencies on your docker container? What docker image are you running?
> 
> wrangler v4.16.1 is the last version that has been compiled to support MacOS 12.7.6 without the node errors. Cloudflare should support nodejs not base its decisions on an OS. wrangler is not a MacOS tool but a nodejs one.
> 
> Supporting nodejs on all platforms is a no brainer.
> 
> Give it time these dyld error will pop up everywhere else, they 'll get the memo, I am quite sure that Intel based macs on Monterey makes a ~10% off dev installs of wrangler.

The problem is that I'm running MacOS Big Sur 11.7.10. It's the max version that my 2014 Macbook Pro supports. I tried again and updated to node v22.16.0 and Wrangler v4.15.2. 

First when running `npm install` I get the following message which just hangs and never completes:

<img width="732" alt="Image" src="https://github.com/user-attachments/assets/d2eb012c-84fe-4850-b867-f8a357b67320" />


So I kill the process I get the following:

<img width="757" alt="Image" src="https://github.com/user-attachments/assets/7f790e65-ccf3-44c0-83f4-b6592c21fed2" />

And the log file has the following text in regards to `dyld`:

> \# This file contains the result of Yarn building a package (workerd@npm:1.20250508.0)
> \# Script name: postinstall
> 
> dyld: malformed mach-o image: dyld chained fixups info underruns __LINKEDIT

Is there anything else that would be helpful that you'd like me to include? Using a dev container has allowed me to get past this issue by just using  

## Workaround in dev containers

In regards to the docker container that allows me to develop locally via dev containers in VS Code - I based the image off of `node:18-slim`. I haven't touched the project for a few months but it did at least run and allow me to use `workderd` from my old laptop.

**Comment by rohanrehman** [comment]
@LukePammant Is that dev container running locally on your  `MacOS Big Sur 11.7.10. It's the max version that my 2014 Macbook Pro`. or is it in a remote server?

I understand that you are developing locally, but I'de like to confirm if that image is running locally or on a remote server?

**Comment by LukePammant** [comment]
@rohanrehman - correct, I am running the docker container locally. To quickly prove it out I ran the following commands directly on my laptop:

```
docker run -it --rm node:22-slim bash
# Now we're in an interactive shell in the docker container
npm install -g wrangler
wrangler -v
# Returns version 4.20.1
```

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/f505bbf1-d177-4e36-bd1b-9d4914e7b694" />

**Comment by taojoe** [comment]
Not supporting a specific version of macOS is not a good decision, but is it possible to provide a way for developers to compile the corresponding class library by themselves, and use environment variables during installation so that developers can also use the new class library to resolve this conflict?
