### ISSUE TITLE
🐛 BUG: d1 export: `Received a malformed response from the API` (502 Bad Gateway)

### ISSUE THREAD

**Issue by robingenz** [cloudflare/workers-sdk#7003]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3.72.1 [Wrangler]

### What version of Node are you using?

20.17.0

### What operating system and version are you using?

Mac Sonoma 14.5

### Observed behavior

Since yesterday, I have been receiving the following error message when exporting a D1 database:

```
npx wrangler d1 export cloud-db --remote --output tmp.sql 

 ⛅️ wrangler 3.72.1 (update available 3.80.5)
-------------------------------------------------------

▲ [WARNING] Processing wrangler.toml configuration:

    - "unsafe" fields are experimental and may change or break at any time.


🌀 Executing on remote database cloud-db (<REDACTED>):

✘ [ERROR] Received a malformed response from the API

  <!DOCTYPE html>
  <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
  <!--[if I... (length = 6446)

  POST
  /accounts/<REDACTED>/d1/database/<REDACTED>/export
  -> 502 Bad Gateway
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

### Expected behavior

The export should be successful.

### Steps to reproduce

No special setup is needed. You simply need to export a d1 database with wrangler. The database may need to contain enough data. In my case, the database has a size of 60 MB.

**Comment by vilhelmjosander** [comment]
**What version(s) of the tool(s) are you using?**
3.80.5 [Wrangler]

**What version of Node are you using?**
20.14.0

Same issue here when trying to use `wrangler deploy --env preprod` to deploy a worker for a Nuxt Application in Bitbucket pipelines. Worked fine yesterday.

![CleanShot 2024-10-17 at 10 34 50@2x](https://github.com/user-attachments/assets/7859d709-5352-43cd-a322-93a5f0a41110)

**Comment by boertel** [comment]
I also had an `ERROR` when running `pnpm wrangler d1 export my-db --remote --output tmp.sql` 
I did not have a "502 Bad Gateway error", just `ERROR`.
Upgrading wrangler to `^3.81.0` fixed it. (I was running `"wrangler": "^3.78.12"` before)

**Comment by robingenz** [comment]
Yes, updating Wrangler to version 3.81.0 fixed this problem for me.

**Comment by robingenz** [comment]
The error occurs again, even with version 3.81.0.

**Comment by robingenz** [comment]
It seems to have been only a temporary error. It works again.
