### ISSUE TITLE
FEEDBACK: red or green dot on DO services

### ISSUE THREAD

**Issue by isaac-mcfadyen** [cloudflare/workers-sdk#7009]
In PR https://github.com/cloudflare/workers-sdk/pull/6893, a red or green dot was added beside each service when deploying a DO with Wrangler.

I'm not too familiar with Wrangler internals, but it looks like the red vs. green is decided based on whether a service is in the registry.

Per some feedback on [Discord](https://canary.discord.com/channels/595317990191398933/779390076219686943/1296367336462225469), this isn't really clear to users, and in fact the random red dot can be kind of concerning given that there is no explanation on what it means or why your services are suddenly red.

I believe it was added in PR https://github.com/cloudflare/workers-sdk/pull/6893:
https://github.com/cloudflare/workers-sdk/blob/ae4bfead3ad9911823ec154476cb1c49ea3a02bf/packages/wrangler/src/config/index.ts#L268

**Comment by AdiRishi** [comment]
Just wanted to clarify something here (I'm the OP on discord).
I didn't encounter this while deploying a `DO` with wrangler, but rather a worker with static assets (Remix website) with 3 bound JSRPC workers (not sure if that's the same as DO underneath)

```
  Total Upload: 3324.79 KiB / gzip: 1022.32 KiB
  Worker Startup Time: 235 ms
  Your worker has access to the following bindings:
  - KV Namespaces:
    - CACHIFIED_CACHE: 191f201005724b038b6facd2ae37e1d9
  - Services:
    - PUBLIC_DATA_SERVICE: 🔴 naamdeo-courses-api#PublicDataService
    - AUTHENTICATED_USER_SERVICE: 🔴 naamdeo-courses-api#AuthenticatedUserService
    - RESTRICTED_SERVICE: 🔴 naamdeo-courses-api#RestrictedService
```

**Comment by isaac-mcfadyen** [comment]
Hey @penalosa,

Thanks for PR #7039 

While that's definitely a fix for non-local dev, I believe in local dev there's still no indication of what the red/green dots actually mean? Users aren't going to know about the registry, just that there's a random indicator beside their services that isn't explained anywhere that I can find.
