### ISSUE TITLE
🐛 BUG: Error: write EOF when running npx wrangler dev

### ISSUE THREAD

**Issue by elldav** [cloudflare/workers-sdk#7013]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

wrangler 3.81.0

### What version of Node are you using?

Node.js v20.18.0

### What operating system and version are you using?

Windows 11, Win32NT 10.0.22621.0 Microsoft Windows NT 10.0.22621.0

### Observed behavior
I'm gong thru the getting started instructions from https://developers.cloudflare.com/workers/get-started/guide/. When I get to the point to run the npx wrangler dev command it gets an error. I see there is another similar issue. The last request on that was the version of the OS. I included that in the field above. Do you need any other information?

### Expected behavior
Not sure. First time trying out Workers.
From the docs it looks like it would run a service that I could connect to via a browser.

### Steps to reproduce
PS C:\Users\WDAGUtilityAccount> nvm install lts
Downloading node.js version 20.18.0 (64-bit)...
Extracting node and npm...
Complete
npm v10.8.2 installed successfully.

Installation complete. If you want to use this version, type

nvm use 20.18.0
PS C:\Users\WDAGUtilityAccount> nvm use lts
Now using node v20.18.0 (64-bit)
PS C:\Users\WDAGUtilityAccount> npm create cloudflare@latest -- my-first-worker
Need to install the following packages:
create-cloudflare@2.30.0
Ok to proceed? (y)

> npx
> create-cloudflare my-first-worker

──────────────────────────────────────────────────────────────────────────────────────────────────────────
👋 Welcome to create-cloudflare v2.30.0!
🧡 Let's get started.
📊 Cloudflare collects telemetry about your usage of Create-Cloudflare.

Learn more at: https://github.com/cloudflare/workers-sdk/blob/main/packages/create-cloudflare/telemetry.md
──────────────────────────────────────────────────────────────────────────────────────────────────────────

╭ Create an application with Cloudflare Step 1 of 3
│
├ In which directory do you want to create your application?
│ dir ./my-first-worker
│
├ What would you like to start with?
│ category Hello World example
│
├ Which template would you like to use?
│ type Hello World Worker
│
├ Which language do you want to use?
│ lang JavaScript
│
├ Copying template files
│ files copied to project directory
│
├ Updating name in `package.json`
│ updated `package.json`
│
├ Installing dependencies
│ installed via `npm install`
│
╰ Application created

╭ Configuring your application for Cloudflare Step 2 of 3
│
├ Retrieving current workerd compatibility date
│ compatibility date 2024-10-11
│
╰ Application configured

╭ Deploy with Cloudflare Step 3 of 3
│
├ Do you want to deploy your application?
│ no deploy via `npm run deploy`
│
╰ Done

────────────────────────────────────────────────────────────
🎉  SUCCESS  Application created successfully!

💻 Continue Developing
Change directories: cd my-first-worker
Start dev server: npm run start
Deploy: npm run deploy

📖 Explore Documentation
https://developers.cloudflare.com/workers

💬 Join our Community
https://discord.cloudflare.com
────────────────────────────────────────────────────────────

npm notice
npm notice New minor version of npm available! 10.8.2 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice To update run: npm install -g npm@10.9.0
npm notice
PS C:\Users\WDAGUtilityAccount> cd my-first-worker
PS C:\Users\WDAGUtilityAccount\my-first-worker> npx wrangler dev

 ⛅️ wrangler 3.81.0
-------------------

╭────────────────────────────────────────────────────────────────────────────────────────⎔ Starting local server...
╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
│  [b] open a browser, [d] open devtools, [l] turn off local mode, [c] clear console, [x] to exit  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
C:\Users\WDAGUtilityAccount\my-first-worker\node_modules\wrangler\wrangler-dist\cli.js:29768
            throw a;
            ^

Error: write EOF
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -4095,
  code: 'EOF',
  syscall: 'write'
}

Node.js v20.18.0
PS C:\Users\WDAGUtilityAccount\my-first-worker>

### Please provide any relevant error logs

C:\Users\WDAGUtilityAccount\my-first-worker\node_modules\wrangler\wrangler-dist\cli.js:29768
            throw a;
            ^

Error: write EOF
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -4095,
  code: 'EOF',
  syscall: 'write'
}

Node.js v20.18.0
PS C:\Users\WDAGUtilityAccount\my-first-worker>

**Comment by sqpp** [comment]
I even have the same issue on WSL.

**Comment by DevBisht12** [comment]
I’m experiencing the same issue on WSL as well.

**Comment by emily-shen** [comment]
hey! can you check if following this comment helps? https://github.com/cloudflare/workers-sdk/issues/3698#issuecomment-2089044668

**Comment by avaer** [comment]
I'm getting this on Windows 11, node v22.11.0. I am using CMD to run `wrangler dev`.
