### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by millsy** [cloudflare/workers-sdk#7021]
### Which Cloudflare product(s) does this pertain to?

KV, Wrangler

### What version(s) of the tool(s) are you using?

3.80.4

### What version of Node are you using?

18.18.0

### What operating system and version are you using?

Mac 13.6.7

### Observed behavior
Bulk upload timeout

` ⛅️ wrangler 3.80.4 (update available 3.81.0)
-------------------------------------------------------

Uploaded 0% (0 out of 56,300)
Uploaded 8% (5,000 out of 56,300)
Uploaded 17% (10,000 out of 56,300)

✘ [ERROR] Received a malformed response from the API

  PUT
  /accounts/XXXXXXXXX/storage/kv/namespaces/XXXXXXXXX/bulk
  -> 524
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose`

### Expected behavior
Should upload the JSON file to the KV

### Steps to reproduce
Please provide the following:

JSON file has 56,300 records in it.

Command executed : `npx wrangler kv bulk put ./otphotos.json --namespace-id XXXXXXXX`

**Comment by penalosa** [comment]
I've pinged the KV team internally about this
