### ISSUE TITLE
🐛 BUG: I am getting the __dirname uncaught refrence error ? 

### ISSUE THREAD

**Issue by Unknownmaster0** [cloudflare/workers-sdk#7027]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.81.0

### What version of Node are you using?

21.7.1

### What operating system and version are you using?

windows 11

### Observed behavior
Please describe.
Uncaught ReferenceError: __dirname is not defined
    at null.<anonymous>
 [code: 10021]

### Expected behavior
Please describe.
backend/node_modules/@prisma/client/runtime/library.js:6:1410)
    at null.<anonymous> (index.js:13:638)
    at null.<anonymous>

### Please provide any relevant error logs

A request to the Cloudflare API (/accounts/6b04d8f8defb2010a12af27200ad7fe1/workers/scripts/medium-like-blog-backend/versions) failed.

  Uncaught ReferenceError: __dirname is not defined
    at null.<anonymous>
  (backend/node_modules/@prisma/client/runtime/library.js:6:1410)
    at null.<anonymous> (index.js:13:638)
    at null.<anonymous>
  (backend/src/controllers/blog.controller.ts:2:45)
   [code: 10021]

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to provide a reproduction repo that demonstrates the issue?

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to open a new issue with more details and we can investigate further.
