### ISSUE TITLE
🚀 Feature Request: svelte 5 cli migration

### ISSUE THREAD

**Issue by azezsan** [cloudflare/workers-sdk#7029]
### Describe the solution

svelte 5 hit stable release, with it came the new cli sv https://github.com/sveltejs/cli/tree/main/packages/cli, create cloudflare should use the new cli instead of the old create svelte so it generates a svelte project with svelte 5 instead, or possibly add cloudflare as a community integration in the sv cli

**Comment by connorads** [comment]
https://github.com/cloudflare/workers-sdk/pull/7031

**Comment by thisjt** [comment]
In the meantime, while waiting for that PR to be merged, you can still use the usual `npm create cloudflare@latest projectfolder --framework=svelte`, then do `npx sv migrate svelte-5` to upgrade to SK5. Use `sv add` to add your needed libraries.

**Comment by azezsan** [comment]
it's merged but using the cli gives me the old version?

**Comment by codenoid** [comment]
@azezsan yes, need to wait for new release https://github.com/cloudflare/workers-sdk/pull/7089
