### ISSUE TITLE
🐛 BUG: Binding D1 of type d1 failed to generate. Please try again later or contact support. [code: 10021]

### ISSUE THREAD

**Issue by dev-xo** [cloudflare/workers-sdk#7059]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3.82.0

### What version of Node are you using?

22.4.0

### What operating system and version are you using?

Mac Sonoma 14.3

### Describe the Bug

No description, since not 100% sure if it's a bug.

### Observed behavior
Trying to deploy worker with `pnpm -F worker deploy:preview` (Monorepo) `wrangler deploy --env preview`, throws the following error:

```
A request to the Cloudflare API (/accounts/xxx/workers/scripts/langapp-worker-preview/versions) failed.

binding D1 of type d1 failed to generate. Please try again later or contact support. [code: 10021]
```

### Expected behavior
The worker should deploy and have no issue related to D1.

This used to work without any issue, and neither have I made changes to the worker itself recently. The D1 database seems to be in place, and I'm successfully able to deploy my Pages and reconcile to it.

As a side note, everything works as expected on local (D1 reconciliation, etc). Also tried on 3.60.0 and 3.82.0 (new version).

- - -

Any idea if this could be related to a bug, or a personal issue on my workspace? Again, had no issues before, and nothing has changed that impacts the worker.

### Please provide any relevant error logs

```
A request to the Cloudflare API (/accounts/xxx/workers/scripts/langapp-worker-preview/versions) failed.

binding D1 of type d1 failed to generate. Please try again later or contact support. [code: 10021]
```

**Comment by dev-xo** [comment]
I was able to deploy it (changed nothing).

Not sure if it was a bug or something in my workspace. Feel free to close the issue in case no further investigation is required.

**Comment by SirRodney** [comment]
Hey @dev-xo,

This was caused by a Cloudflare issue affecting D1 bindings between 20:19 and 22:20 UTC today. I ran into the same problem, but it was resolved once Cloudflare fixed the incident.

https://www.cloudflarestatus.com/incidents/f907j39814l7

Hope that clears it up!
