### ISSUE TITLE
🐛 BUG: fails to deploy if the name of the worker is accounts

### ISSUE THREAD

**Issue by azezsan** [cloudflare/workers-sdk#7063]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.82.0

### What operating system and version are you using?

WSL2 ubuntu

### Observed behavior
fails to deploy

### Expected behavior
deploys

### Steps to reproduce
- create a sveltekit app with create cloudflare and add experimental flag
- name it accounts
- deploy it

if you have wrangler.toml that has name "accounts" it will fail to upload, at least in the new sveltekit experimental
```
#:schema node_modules/wrangler/config-schema.json
name = "accounts"
compatibility_date = "2024-10-22"
main = ".svelte-kit/cloudflare/_worker.js"
assets = { directory = ".svelte-kit/cloudflare", binding = "ASSETS" }
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

```

**Comment by penalosa** [comment]
Could you provide the debug logs for Wrangler? i.e. `WRANGLER_LOG=debug wrangler deploy`?

**Comment by penalosa** [comment]
This has been raised internally

**Comment by azezsan** [comment]
I was gonna do it but I wasn't very sure how safe that is and it was very straightforward to reproduce , it's an 7003 api error

**Comment by penalosa** [comment]
This has been addressed at the API layer, and should be released within the next week or so

**Comment by azezsan** [comment]
this issue hasn't been addressed
