### ISSUE TITLE
🐛 BUG:  Uncaught ReferenceError: chance is not defined when using javascript-obfuscator

### ISSUE THREAD

**Issue by umesh-gsynergy** [cloudflare/workers-sdk#7113]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.83.0

### What version of Node are you using?

18

### What operating system and version are you using?

Mac big sur

### Describe the Bug

<img width="1440" alt="Screenshot 2024-10-28 at 6 49 51 PM" src="https://github.com/user-attachments/assets/386a6d13-be1c-4548-8ba3-5d26cf571c46">

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to provide a reproduction repo that demonstrates the issue?

**Comment by lrapoport-cf** [comment]
hi @umesh-gsynergy :)  we haven't heard from you in a while, so we’re going to close this issue for now. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and repro and we will revisit and investigate further. thanks!
