### ISSUE TITLE
🐛 BUG: spawn UNKNOWN while wrangler login

### ISSUE THREAD

**Issue by Aritra-2000** [cloudflare/workers-sdk#7114]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

wrangler 3.83.0

### What version of Node are you using?

v22.10.0

### What operating system and version are you using?

windows11

### Observed behavior
whenever i tried to login my wrangler through CLI i'm getting spawn error that's why i can't deploy 

Attempting to login via OAuth...
..................................................................................................Link of Cloudflare.................................................................

X [ERROR] spawn UNKNOWN

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to provide a reproduction repo that demonstrates the issue? In particular, it would be useful to see your `wrangler.toml` file.

**Comment by lrapoport-cf** [comment]
hi @Aritra-2000 :) we haven't heard from you in a while, so we’re going to close this issue for now. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include a repro and we will revisit and investigate further. thanks!
