### ISSUE TITLE
🐛 BUG: Fatal uncaught kj::Exception: kj/table.c++:49: failed: inserted row already exists in table while trying to run multiple workflows locally

### ISSUE THREAD

**Issue by AggressivelyMeows** [cloudflare/workers-sdk#7127]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler, Other

### What version(s) of the tool(s) are you using?

3.83.0

### What operating system and version are you using?

Linux

### Observed behavior
Wrangler crashes with a kj::Exception when you have more than one workflow setup in wrangler.toml.

### Expected behavior
Both workflows work

### Steps to reproduce
- Setup a worker with two workflows.
- Add both workflows to wrangler.toml
- exception when running in dev

Works:
```
[[workflows]]
name = "photosIngestWorkflow"
binding = "photosIngestWorkflow"
class_name = "photosIngestWorkflow"
```

Does not work, with crash:
```
[[workflows]]
name = "photosIngestWorkflow"
binding = "photosIngestWorkflow"
class_name = "photosIngestWorkflow"

[[workflows]]
name = "photosLooperWorkflow"
binding = "photosLooperWorkflow"
class_name = "photosLooperWorkflow"
```

### Please provide any relevant error logs

`
Fatal uncaught kj::Exception: kj/table.c++:49: failed: inserted row already exists in table
stack: /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@5b41f0f /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@322a850 /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@322a744 /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2eaf016 /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2eb9126 /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2e898b8 /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2e87295 /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2e75bdf /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@5b3594a /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@5b35d7b /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@5b33cb8 /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@5b339c3 /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2e61af3 /lib/x86_64-linux-gnu/libc.so.6@24082 /home/codespace/.npm/_npx/d77349f55c2be1c0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2e6102d
`

**Comment by flash716** [comment]
I have the same issue. Makes it very hard to develop workflows that call other workflows.

**Comment by masylum** [comment]
hitting the same issue here

**Comment by gmemstr** [comment]
If you experience the same issue, please react to the issue rather than leaving a comment so that those watching the issue and receiving notifications don't get notification fatigue :)

**Comment by pernydev** [comment]
Same error appears on Wrangler 4.46 with 2025-11-09 comp, on Arch with 6.17.4 kernel when just trying to start the dev server of a brand new Hello, World worker made with the CLI.
