### ISSUE TITLE
🐛 BUG: passing an invalid compatibility_date in wrangler.toml causes env variables not to be bound

### ISSUE THREAD

**Issue by adamdehaven** [cloudflare/workers-sdk#7178]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler

### What version(s) of the tool(s) are you using?

3.82.0 [Wrangler]

### What version of Node are you using?

20.18.0

### What operating system and version are you using?

Mac Sonoma

### Observed behavior

Passing an invalid `compatibility_date` in a `wrangler.toml` (e.g. `2024-11-05` as of today) does not throw an error; however, it causes any environment variables and secrets to not be available in the deployed worker.

### Expected behavior

The invalid `compatibility_date` should fallback to the latest valid `compatibility_date`, and environment variables and secrets should be properly available in the worker.

### Steps to reproduce

1. Create a valid `wrangler.toml` with the following setting:
    ```toml
    compatibility_date = "2024-11-05"
    ```
2. Add an environment secret in the Cloudflare Dashboard UI, and deploy the secret
3. Deploy your worker via `wrangler` using the `wrangler.toml` and notice your environment variable is not available.

**Comment by irvinebroque** [comment]
Can't reproduce this with same exact steps, are you certain that is happening?

**Comment by adamdehaven** [comment]
> Make sure this is a secret and not an environment variable.

Yes, it’s a secret defined in our terraform config for the worker

**Comment by penalosa** [comment]
> Is there a recommended way to submit a reproduction?

Could you provide a link to a GitHub repo that demonstrates the issue?

**Comment by lrapoport-cf** [comment]
hi @adamdehaven  :) we haven't heard from you in a while, so we’re going to close this issue for now. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include a link to a repro and we will revisit and investigate further. thanks!

**Comment by adamdehaven** [comment]
A change in Nitro causes `node:http` polyfill to use runtime native `node:stream` which is incompatible with `unenv/fetch` polyfills (which essentially breaks H3 v1 and Nitro v2 as soon as they use it anyhow, via upgrade or wrangler transpiling for `node_compat_v2`).

See the Nitro issue for more info: https://github.com/unjs/unenv/issues/364
