### ISSUE TITLE
Can not install/deploy minimal version of experimental next app

### ISSUE THREAD

**Issue by emircanerkul** [cloudflare/workers-sdk#7184]
### Which Cloudflare product(s) does this pertain to?

Pages, Workers Runtime, Wrangler

### What version(s) of the tool(s) are you using?

3.85.0

### What operating system and version are you using?

Mac

### Describe the Bug

npm create cloudflare@latest my-next-app -- --framework=next --experimental

✘ [ERROR] A request to the Cloudflare API (/accounts/xxx/workers/scripts/my-next-app) failed.

  Your Worker exceeded the size limit of 1 MiB. Refer to the Workers documentation (https://developers.cloudflare.com/workers/observability/errors/#errors-on-worker-upload) for more details. [code: 10027]
  

Followed: https://developers.cloudflare.com/workers/frameworks/framework-guides/nextjs/

Document do not says you need pro version of workers

**Comment by emily-shen** [comment]
hey! we've raised the limit for free tier to 3MB, so this should work now 🎉
https://developers.cloudflare.com/workers/platform/limits/#account-plan-limits
feel free to open an issue if you encounter any other problems :)
