### ISSUE TITLE
🐛 BUG: Running rust example generated via `cargo generate cloudflare/workers-rs` fails `Uncaught LinkError: WebAssembly.Instance()`

### ISSUE THREAD

**Issue by pmalek** [cloudflare/workers-sdk#7208]
### Which Cloudflare product(s) does this pertain to?

Other

### What version(s) of the tool(s) are you using?

3.86.0 [Wrangler]

### What version of Node are you using?

23.1.0

### What operating system and version are you using?

Mac Sequoia 15.0.1 

### Observed behavior

Running rust example generated with `cargo generate cloudflare/workers-rs` fails with the following error message:

```
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: ✨   Done in 0.26s
[INFO]: 📦   Your wasm pkg is ready to publish at /Users/USER/code_/own/cfworker1/asd/build.

The file src changed, restarting build...
Running custom build: cargo install -q worker-build && worker-build --release
[wrangler:inf] Ready on http://localhost:8787
╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
│  [b] open a browser, [d] open devtools, [l] turn off local mode, [c] clear console, [x] to exit  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Finished `release` profile [optimized] target(s) in 0.04s
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: ✨   Done in 0.22s
[INFO]: 📦   Your wasm pkg is ready to publish at /Users/USER/code_/own/cfworker1/asd/build.

⎔ Starting local server...
✘ [ERROR] service core:user:asd: Uncaught LinkError: WebAssembly.Instance(): Import #9 "./index_bg.js" "__wbg_error_53abcd6a461f73d8": function import requires a callable

    at null.<anonymous> (shim.js:41:9)



✘ [ERROR] The Workers runtime failed to start. There is likely additional logging output above.

```

### Expected behavior
Please describe.

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suite on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

**Comment by o-az** [comment]
downgrade to rust 1.81.0 should fix it

**Comment by pmalek** [comment]
I can confirm, downgrading to 1.81 works. Any particular reason this doesn't work with 1.82? Can't this be enforced somehow through dependency requirements?

**Comment by o-az** [comment]
I have no idea and I found out by luck 😁

**Comment by brentschroeter** [comment]
Having the same issue, also fixed by downgrading to 1.81. Searching through GitHub issues for other projects, seems to be that Rust 1.82 enables [new LLVM features by default](https://blog.rust-lang.org/2024/09/24/webassembly-targets-change-in-default-target-features.html), including WASM reference type transformations which are not yet supported by all JS tooling (for example https://github.com/rustwasm/wasm-bindgen/issues/4211).

**Comment by fornwall** [comment]
Issue in `workers-rs`: https://github.com/cloudflare/workers-rs/issues/668

**Comment by penalosa** [comment]
Closing in favour of https://github.com/cloudflare/workers-rs/issues/668
