### ISSUE TITLE
🐛 BUG:1

### ISSUE THREAD

**Issue by vincent1986** [cloudflare/workers-sdk#7209]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

0.0.0[wrangler]

### What version of Node are you using?

0.0.1

### What operating system and version are you using?

mac

### Observed behavior
Please describe.

### Expected behavior
Please describe.

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suite on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

### Please provide a link to a minimal reproduction

https://github.com/adminPhotos

### Please provide any relevant error logs

w

**Comment by andyjessop** [comment]
I'm going to close this one for now, as there is no description or other information.
