### ISSUE TITLE
🐛 BUG:D1_ERROR: Wrong number of parameter bindings for SQL query.

### ISSUE THREAD

**Issue by toritreee** [cloudflare/workers-sdk#7221]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3.60.3[wrangler]

### What operating system and version are you using?

Windows 11

### Observed behavior
Run the following code:
```ts
const { results } = await env.DB.prepare(
    "SELECT * FROM test WHERE name = '?'",
)
    .bind("Bs Beverages")
    .all();
```
The following error is output:
`D1_ERROR: Wrong number of parameter bindings for SQL query.`

### Expected behavior
The value is bound to "?" correctly.

### Steps to reproduce
Run this: https://developers.cloudflare.com/d1/get-started/
Modify the SQL statement: put "?" in quotes.
My worker code:
```ts
export interface Env {
  // If you set another name in wrangler.toml as the value for 'binding',
  // replace "DB" with the variable name you defined.
  DB: D1Database;
}

export default {
  async fetch(request, env): Promise<Response> {
    const { pathname } = new URL(request.url);

    if (pathname === "/api/name") {
      // If you did not use `DB` as your binding name, change it here
      const { results } = await env.DB.prepare(
        "SELECT * FROM test WHERE name = '?'",
      )
        .bind("Bs Beverages")
        .all();
      return Response.json(results);
    }

    return new Response(
      "Call /api/beverages to see everyone who works at Bs Beverages",
    );
  },
} satisfies ExportedHandler<Env>;
```
Visit "/api/name"

**Comment by edmundhung** [comment]
Hi @toritreee,

Apologies for the confusing error message. Removing the single quotes around the `?` should resolve the issue. For more details, please refer to the [parameter binding documentation](https://developers.cloudflare.com/d1/build-with-d1/d1-client-api/#parameter-binding).

If you have any further questions, feel free to ask!
