### ISSUE TITLE
🚀 Feature Request: Write Version Preview URL to artifacts file

### ISSUE THREAD

**Issue by nprogers** [cloudflare/workers-sdk#7240]
### Describe the solution

https://github.com/cloudflare/wrangler-action/issues/302
Wrangler-action users want to be able to access version preview urls. We should write that to the artifacts file.

**Comment by shahsimpson** [comment]
Related to https://github.com/cloudflare/wrangler-action/issues/302

**Comment by penalosa** [comment]
What's the artifacts file?
