### ISSUE TITLE
🐛 BUG: write EOF

### ISSUE THREAD

**Issue by zhaott-eng** [cloudflare/workers-sdk#7264]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.87.0[wrangler]

### What version of Node are you using?

22.11.0

### What operating system and version are you using?

window11

### Observed behavior
Please describe.Cannot run locally

### Expected behavior
Please describe.Run locally on local8787

### Steps to reproduce
Please provide the following:
- npm i
- npm run dev-remote

### Please provide any relevant error logs

▲ [WARNING] You are using `node_compat`, which is a legacy Node.js compatibility option. Instead, use the `nodejs_compat` compatibility flag. This includes the functionality from legacy `node_compat` polyfills and natively implemented Node.js APIs. See https://developers.cloudflare.com/workers/runtime-apis/nodejs for more information.

Using vars defined in .dev.vars
Your worker has access to the following bindings:
- D1 Databases:
  - D1: quotr (bbb4e052-bc08-44b8-ad0c-606116b50278) (local)
- R2 Buckets:
  - R2: quotr-preview (local)
- Vars:
  - API_HOST: "https://api.quotr.io"
  - PINECONE_ENVIRONMENT: "us-east1-gcp"
  - PINECONE_INDEX: "cost-database-index"
  - OPENAI_API_KEY: "(hidden)"
  - PINECONE_API_KEY: "(hidden)"

X [ERROR] write EOF

If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose

**Comment by edmundhung** [comment]
Hi @zhaott-eng! Thanks for reporting this issue. Could you provide more details to help us investigate? Specifically:

- Which `wrangler` command are you running?
- Can you share the logs when running the command with `WRANGLER_LOG=debug`?

Additionally, if you can provide a minimal reproduction or steps to reproduce the issue, that would be super helpful.

**Comment by emily-shen** [comment]
Could also try following this comment, may help https://github.com/cloudflare/workers-sdk/issues/3698#issuecomment-2089044668

**Comment by lrapoport-cf** [comment]
hi @zhaott-eng  :) we haven't heard from you in a while, so we’re going to close this issue for now. if @emily-shen 's suggestion above does not resolve the issue, please feel free to open a new issue referencing this one. please be sure to include an updated summary and any additional details and we will revisit and investigate further. thanks!
