### ISSUE TITLE
🐛 BUG: WSL 2 - tcmalloc Error 

### ISSUE THREAD

**Issue by cf-jas** [cloudflare/workers-sdk#7275]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.87.0 [Wrangler]

### What version of Node are you using?

20.16.0

### What operating system and version are you using?

WSL 2

PS > wsl --version
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.4460

### Observed behavior
On WSL 2, when running "npx wrangler@latest dev" for the "hello world" Python example, the error happens.

### Expected behavior
---

### Steps to reproduce
Please provide the following:
On WSL1:
git clone https://github.com/cloudflare/python-workers-examples
cd python-workers-examples/01-hello
npx wrangler@latest dev

Python info: Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux

### Please provide any relevant error logs

 ⛅️ wrangler 3.87.0
-------------------

▲ [WARNING] The entrypoint src/entry.py defines a Python worker, support for Python workers is currently experimental. Python workers with a requirements.txt file can only be run locally and cannot be deployed.

⎔ Starting local server...

✘ [ERROR] write EPIPE

If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
╭───────────────────────────────────────────────────────────✘ [ERROR] 2664 external/com_google_tcmalloc/tcmalloc/system-alloc.cc:771] MmapAligned() failed - unable to allocate with tag (hint=0xe10c0000000, size=1073741824, alignment=1073741824) - is something limiting address placement?

  2664 external/com_google_tcmalloc/tcmalloc/arena.cc:52] CHECK in Alloc: FATAL ERROR: Out of memory
  trying to allocate internal tcmalloc data (bytes=131072, object-size=640); is something preventing
  mmap from succeeding (sandbox, VSS limitations)?

✘ [ERROR] 2666 external/com_google_tcmalloc/tcmalloc/system-alloc.cc:771] MmapAligned() failed - unable to allocate with tag (hint=0xf7280000000, size=1073741824, alignment=1073741824) - is something limiting address placement?

  2666 external/com_google_tcmalloc/tcmalloc/arena.cc:52] CHECK in Alloc: FATAL ERROR: Out of memory
  trying to allocate internal tcmalloc data (bytes=131072, object-size=640); is something preventing
  mmap from succeeding (sandbox, VSS limitations)?

**Comment by danlapid** [comment]
Seems like your WSL VM doesn't have enough memory.
Try to increase it's allocation please.

**Comment by cf-jas** [comment]
Hi Dan. I believe I should have enough memory allocated to WSL.

Running free in WSL VM
$ free -h --giga
               total        used        free      shared  buff/cache   available
Mem:             32G         11G         21G         17M        223M         21G
Swap:            60G          0B         60G

**Comment by cf-jas** [comment]
Thanks @danlapid and team for the heads up and guidance.

System was on WSL1 and not WSL2. WSL1 is not supported.

upgraded with
PS > wsl --set-version Ubuntu-22.04 2

Kernel on WSL much show "5.15.153.1-microsoft-standard-WSL2" when WSL2 is being used
$ uname -a
Linux DESKTOP-45994 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
