### ISSUE TITLE
🐛 BUG:[ERROR] write EOF

### ISSUE THREAD

**Issue by lokeshsainipilani** [cloudflare/workers-sdk#7296]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.88.0 [wrangler]

### What version of Node are you using?

23.2.0

### What operating system and version are you using?

windows 10

### Describe the Bug
![image](https://github.com/user-attachments/assets/585ba487-468f-476a-8969-848044ca3e87)

### Observed behavior
it is showing write eof error 

### Expected behavior
while i run npm run dev or wrangler dev command then it is showing eof error

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
- A minimal working subset of your `wrangler.toml`
- Commands used to start your local dev server, including custom env and cli args
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)

A git repo we can clone and run a test suite on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

**Comment by emily-shen** [comment]
Hiya, can you follow this comment and see if it helps https://github.com/cloudflare/workers-sdk/issues/3698#issuecomment-2089044668?

**Comment by lrapoport-cf** [comment]
hi @lokeshsainipilani  :)  we haven't heard from you in a while, so we’re going to close this issue for now. if @emily-shen 's suggestion above does not resolve the issue, please feel free to open a new issue referencing this one. please be sure to include an updated summary and any additional details and we will revisit and investigate further. thanks!
