### ISSUE TITLE
🐛 BUG: PDF doesn't render in Browser Rendering API

### ISSUE THREAD

**Issue by andreaselia** [cloudflare/workers-sdk#7301]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.60.3

### What operating system and version are you using?

Mac Sequoia 15.1

### Describe the Bug

Using the Browser Rendering API to create a new page, go to the URL of a PDF, and then return a screenshot doesn't seem to be able to load the PDF itself, any suggestions or is this simply not one of those use cases the Browser Rendering API should be used for?

### Observed behavior
PDF does not render. If it's not the blank screenshot attached, it's a timeout due to exceeding the 30s navigation timeout.

### Expected behavior
PDF is rendered and it doesn't timeout rendering a PDF.

### Steps to reproduce

```ts
const browser = await puppeteer.launch(env.BROWSER);
const page = await browser.newPage();

// This is a PDF I found on GitHub to test with here
await page.goto('https://usbtemp.s3.amazonaws.com/terms.pdf', {
  waitUntil: 'networkidle0',
});

const img = (await page.screenshot()) as Buffer;

// Here I upload to R2/handle, return a response, etc.
```
![image](https://github.com/user-attachments/assets/dfde81a1-8eeb-40ee-a818-1153d16ef713)

**Comment by emily-shen** [comment]
Unfortunately this is an upstream limitation in headless Chromium browsers, so there is not much we can do from our side :/ 

there are related issues like [this](https://github.com/puppeteer/puppeteer/issues/1872) that have workarounds that you could try.
