### ISSUE TITLE
🐛 BUG:Access violation error on Windows with Wrangler

### ISSUE THREAD

**Issue by amandwivedi1357** [cloudflare/workers-sdk#7305]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

"wrangler": "^3.60.3"

### What version of Node are you using?

v18.18.0

### What operating system and version are you using?

windows 10

### Observed behavior
I encountered an access violation error when trying to run wrangler dev on my Windows machine.

### Expected behavior
Please describe.
Wrangler should start the Workers runtime without errors.

### Steps to reproduce
Install Wrangler globally: npm install -g wrangler
Run wrangler dev in my project folder.

below is the error i am getting
X [ERROR] There was an access violation in the runtime.
On Windows, this may be caused by an outdated Microsoft Visual C++ Redistributable library.

System Information:

Node.js version: v18.18.0
Wrangler version: 3.60.3
OS: Windows 10

Additional Information: I have updated the necessary Visual C++ Redistributable libraries, but the error persists. I’ve also tried running as administrator and in local mode (wrangler dev --local), but the issue remains.

A git repo we can clone and run a test suite on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.
https://github.com/amandwivedi1357/serverless-backend

### Please provide any relevant error logs

>> 

 ⛅️ wrangler 3.88.0
-------------------

⎔ Starting local server...
X [ERROR] There was an access violation in the runtime.

  On Windows, this may be caused by an outdated Microsoft Visual C++ Redistributable library.
  See https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist.

  See https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist.

X [ERROR] The Workers runtime failed to start. There is likely additional logging output above.

**Comment by penalosa** [comment]
Could you try updating to the latest version of Wrangler, and provide the exact versions of Wrangler, Node, Windows and the Microsoft Visual C++ Redistributable library?

**Comment by lrapoport-cf** [comment]
hi @amandwivedi1357  :) we haven't heard from you in a while, so we’re going to close this issue for now. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and additional detail in response to @penalosa 's comment above, and we will revisit and investigate further. thanks!
