### ISSUE TITLE
🐛 BUG: Pages never connects to external workers in local development

### ISSUE THREAD

**Issue by samuelmarcos-cpu** [cloudflare/workers-sdk#7322]
### Which Cloudflare product(s) does this pertain to?

C3 (npm create cloudflare), Pages, Wrangler

### What version(s) of the tool(s) are you using?

3.88.0 [Wrangler]

### What version of Node are you using?

22.9.0

### What operating system and version are you using?

Windows 11, Linux Ubuntu WSL

### Observed Behavior

After configuring and starting a connection from an ES module worker to a page, the page, which was run with `npx wrangler pages dev`, never connects to the worker, which is also running in another terminal with `npx wrangler dev`.

### Expected Behavior

It is expected that after running the dev command for the page project and then running the dev command for the worker project, the page project should be able to connect to the worker running locally, as described in the [documentation](https://developers.cloudflare.com/workers/runtime-apis/bindings/service-bindings/#local-development).

### Steps to Reproduce

This scenario can be easily tested by creating each of the projects with the command `npm create cloudflare@latest`.

#### Setup Worker Project

- Run `npm create cloudflare@latest -- worker-a`
- Select the first option _Hello World example_
- Choose the default options for the remaining choices
- Run `npm run dev`

#### Setup Page Project

- Run `npm create cloudflare@latest -- pages-nuxt`
- Select the second option _Framework Starter_
- Choose the NUXT framework (I also tested using another framework like NEXT, but encountered the same issue)
- Choose the default options for the remaining choices
- Run `npx wrangler pages dev --service WORKER_A=worker-a`

After running both projects in development mode, regardless of the order in which they were started, the output in the pages project will be:

```bash
- Services:
  - WORKER_A: worker-a [not connected]
```

Indicating that the page project did not connect to the worker-a.

I reviewed the documentation, repeated this process on Linux, tested switching from NUXT to NEXT, and had no success. Therefore, I am reporting this issue as a bug.

#### Note

This issue might be related to another [request](https://github.com/cloudflare/workers-sdk/issues/5918)

**Comment by mfromoops** [comment]
I'm having the same issue on 3.90.0

**Comment by emily-shen** [comment]
Does running with `--x-registry=false` help?

**Comment by mfromoops** [comment]
Seems to be working on 3.87.0

**Comment by emily-shen** [comment]
Thanks for the reports! #7081 in 3.88.8 might've caused this :/ Can you add `--x-registry=false` to both dev commands and see if that fixes it?

**Comment by bdmackie** [comment]
@emily-shen I have the same issue (with SvelteKit app as the Pages caller). x-registry=false on both caller and callee dev invocations addressed the issue, however strangely it only connects if you start the callee worker after the caller pages app.
