### ISSUE TITLE
🐛 BUG: Logs don't show if assets.directory is set

### ISSUE THREAD

**Issue by vladshcherbin** [cloudflare/workers-sdk#7397]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler

### What version(s) of the tool(s) are you using?

3.91.0 [wrangler]

### What version of Node are you using?

22.10.0

### What operating system and version are you using?

macOS Sequoia 15.1.1

### Observed behavior
If I set `assets.directory` in `wrangler.json`, observability logs stop showing new logs. If I remove the setting, new logs start coming again. Locally with `wrangler dev` logs show every time.

with `assets.directory`:

<img width="1582" alt="Screenshot 2024-12-01 at 14 26 40" src="https://github.com/user-attachments/assets/89592e4d-6146-40e6-ae11-665aa0fcabe8">

without:

<img width="1582" alt="image" src="https://github.com/user-attachments/assets/0f65c1ac-7483-4c4d-a489-44658293f869">

test link - https://wrangler-test.spacehub.workers.dev
test link of public file - https://wrangler-test.spacehub.workers.dev/acorn.svg
full application code - https://github.com/vladshcherbin/wrangler-test

### Expected behavior
Logs should continue showing in `Logs` tab

### Steps to reproduce
full application code - https://github.com/vladshcherbin/wrangler-test

1. deploy
2. open route - see no logs
3. remove `assets.directory` in `wrangler.json`, re-deploy
4. open route - see logs

### Please provide a link to a minimal reproduction

https://github.com/vladshcherbin/wrangler-test

**Comment by emily-shen** [comment]
Thanks for the report, I can reproduce and we're looking into it!

**Comment by emily-shen** [comment]
Just to double check, have you definitely been invoking your worker when you’ve got assets? Requests to assets don’t show up on logs, only worker invocations.

Also does running npx wrangler tail when you have assets deployed give you anything?

**Comment by vladshcherbin** [comment]
@emily-shen I've recorded requests and tail output - https://youtu.be/b5a66QPmiwg

Both worker requests and asset requests are not logged with `assets.directory` and both are logged without it. Please check and let me know if any other information or test might needed 🙌

**Comment by emily-shen** [comment]
Hey @vladshcherbin should be fixed now! Don't think you have to do anything, maybe redeploy? Feel free to follow up though if you have any issues :))
