### ISSUE TITLE
🐛 BUG: npm create cloudflare (C3) fails with astro framework - error adding type declarations to src/env.d.ts

### ISSUE THREAD

**Issue by jldec** [cloudflare/workers-sdk#7416]
### Which Cloudflare product(s) does this pertain to?

C3 (npm create cloudflare)

### What version(s) of the tool(s) are you using?

c3 v2.33.1, create-astro@4.10.0

### What version of Node are you using?

22.11.0

### What operating system and version are you using?

macOS Sequoia v15.1.1

### Observed behavior
c3 exits with a fatal error when it tries to add type declarations in `src/env.d.ts`
This file appear to have been removed (made optional).

![Screenshot 2024-12-03 at 00 06 06](https://github.com/user-attachments/assets/33d15dbb-5af3-41f2-87e8-28bf8dc5a749)

### Expected behavior
c3 should not error out with astro projects.

### Steps to reproduce
- `npm create cloudflare` (with or without `--experimental`, both fail in the same way)
- select "Framework Starter", and then "Astro"
- select "Include sample files" (or "Blog" or "Empty")
- select "Yes" for TypeScript (the default)

### Please provide any relevant error logs

```
Updating configuration in astro.config.mjs
Adding type declarations in src/env.d.ts
ERROR  Error: Error parsing file: src/env.d.ts
```

**Comment by alexanderniebuhr** [comment]
We changed the way types are declared in Astro v5: https://5-0-0-beta--astro-docs-2.netlify.app/en/guides/upgrade-to/v5/#changed-typescript-configuration

**Comment by dario-piotrowicz** [comment]
Thanks for the issue @jldec 🙂 

#7497 should address this 👍
