### ISSUE TITLE
🐛 BUG: Cannot find tsconfig file "tsconfig.node.json"

### ISSUE THREAD

**Issue by gkiely** [cloudflare/workers-sdk#7443]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.92.0

### What version of Node are you using?

22.10.0

### What operating system and version are you using?

macOS Monterey 12.7.6

### Observed behavior
In the latest version I get the error: `Cannot find tsconfig file "tsconfig.node.json"`

### Expected behavior
Server starts as expected.

### Steps to reproduce
Please provide the following:
- Create a tsconfig.node.json file
- Create a wrangler.toml nested in 1 or 2 directories
- In wrangler.toml set : `tsconfig = "../../tsconfig.node.json"`
- `wrangler dev --port 8080 --env development --config server/wrangler.toml server/server.ts`

This issue is not present in `3.91.0`.

### Please provide a link to a minimal reproduction

If you need a git repo, comment and I can set one up.

**Comment by penalosa** [comment]
Could you try again with `wrangler@beta`? This might be related to an issue with projectRoot that's just been reverted

**Comment by gkiely** [comment]
@penalosa yes that works.

**Comment by penalosa** [comment]
Fantastic! That'll go out in the next release #7446
