### ISSUE TITLE
🐛 BUG: wrangler secret list not valid json 3.93.0 - resolved by downgrading to 3.92.0

### ISSUE THREAD

**Issue by jdanyow** [cloudflare/workers-sdk#7487]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.93.0

### What version of Node are you using?

v23.3.0

### What operating system and version are you using?

gh actions ubuntu-latest

### Describe the Bug

I updated to wranger 3.93.0 today. Afterwards, executing wrangler secret lists produces the following output/error:

```
[ { "name": "XYZ", "type": "secret_text" } ]Cloudflare collects anonymous telemetry about your usage of Wrangler. Learn more at htt
```

If I downgrade to 3.92.0, wrangler secrets list works as expected

This is an issue for our deployments because the [secrets JSON is parsed by jq as part of an assertion that all expected secrets are configured](https://github.com/cloudflare/workers-sdk/issues/2101#issuecomment-1813043234). I'd love to be able to assert secrets in my wrangler.toml. Any chance #2101 can be re-opened?

**Comment by penalosa** [comment]
Thanks for opening an issue! Would it be possible to put together a repro of this issue? It would also be really helpful to see Wrangler's debug logs (which can be enabled by setting WRANGLER_LOG=debug) to help us investigate further.

**Comment by SayefReyadh** [comment]
Is there any update on this issue? Some of our pipelines are currently broken because of it. We use the list command to fetch the recent version and retrieve the ID based on our custom tag. However, the new line ⛅️ wrangler 3.93.0 at the top of the output is causing our jq commands to fail with the error: jq: parse error: Invalid numeric literal at line 2, column 8.

**Comment by SayefReyadh** [comment]
> @SayefReyadh is correct - this was an issue with `wrangler secret list`, not deploy. I've updated the title and description to reflect this. Need to remove the "Cloudflare collects anonymous telemetry about your usage of Wrangler" notice.

For a work around we downgraded to 3.92.0 for now.

**Comment by jdanyow** [comment]
I just verified you can add the following to your wranger.toml to remove the telemetry notice:

```
send_metrics = false
```

https://github.com/cloudflare/workers-sdk/blob/669d7ad1e44c07cf74202c4d0fc244a9c50dec81/packages/wrangler/src/metrics/metrics-dispatcher.ts#L190

**Comment by lrapoport-cf** [comment]
we are working on a fix now 👍

**Comment by lrapoport-cf** [comment]
https://github.com/cloudflare/workers-sdk/pull/7493

**Comment by lrapoport-cf** [comment]
this is now fixed in https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.94.0
