### ISSUE TITLE
🐛 BUG: D1 sqlite import fails: Durable Object's isolate exceeded its memory limit and was reset

### ISSUE THREAD

**Issue by datwelk** [cloudflare/workers-sdk#7554]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3.95.0 [Wrangler]

### What version of Node are you using?

22.9.0

### What operating system and version are you using?

Mac Sonoma 14.7

### Observed behavior
I am trying to import a sqlite dump into my D1 database. The upload succeeds, then after processing around 300k queries the process fails with this error:

✘ [ERROR] Durable Object's isolate exceeded its memory limit and was reset.

This error is consistent, every time i retry.

### Expected behavior
It doesn't error and upload succeeds.

### Steps to reproduce
- Create an sql dump of a db thats around 4 GB in size.
- Try to upload it to d1

### Please provide any relevant error logs

```
 ⛅️ wrangler 3.95.0
-------------------

✔ ⚠️ This process may take some time, during which your D1 database will be unavailable to serve queries.
  Ok to proceed? … yes
🌀 Executing on remote database airlinedelays (e61dc8d9-3fc6-4c4e-b4eb-71e79aad4bd4):
🌀 To execute on your local development database, remove the --remote flag from your wrangler command.
Note: if the execution fails to complete, your DB will return to its original state and you can safely retry.
🌀 File already uploaded. Processing.
🌀 Starting import...
🌀 Processed 36213 queries.
🌀 Processed 52452 queries.
🌀 Processed 69008 queries.
🌀 Processed 85617 queries.
🌀 Processed 101990 queries.
🌀 Processed 118607 queries.
🌀 Processed 135103 queries.
🌀 Processed 151403 queries.
🌀 Processed 168062 queries.
🌀 Processed 184991 queries.
🌀 Processed 201756 queries.
🌀 Processed 218587 queries.
🌀 Processed 235727 queries.
🌀 Processed 252693 queries.
🌀 Processed 269614 queries.
🌀 Processed 288195 queries.

✘ [ERROR] Durable Object's isolate exceeded its memory limit and was reset.
```

**Comment by datwelk** [comment]
Workaround seems to split the sql file into smaller chunks of about 300.000 statements each.

**Comment by andyjessop** [comment]
Hey @datwelk - thanks very much for reporting this. There are moves to improve the import API internally, but for now the only solution is the one that you provided.

**Comment by HananoshikaYomaru** [comment]
this error is not documented here: https://developers.cloudflare.com/durable-objects/observability/troubleshooting. can anyone give more insights? is it caused by D1 handle too much statements at a time or is it caused by D1 handling too much size at a time? I am having this issue with durable object.

**Comment by HananoshikaYomaru** [comment]
I think what the error message means is that it exceed 128 MB of worker memory limit? If I am wrong correct me.

**Comment by kirby-jack** [comment]
same issue here - i believe its from too many statements. mine crashed ~150,000 queries for a 2.57GB `.sql` file.
