### ISSUE TITLE
🐛 BUG: Wrangler pages fails to deploy

### ISSUE THREAD

**Issue by michaelpayne02** [cloudflare/workers-sdk#7577]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler

### What version(s) of the tool(s) are you using?

3.97.0 [Wrangler]

### What version of Node are you using?

Deno 2.1.4

### What operating system and version are you using?

Mac Sequoia 15.2

### Observed behavior
When deploying to pages via `npx wrangler pages deploy dist --project-name=project`, wrangler fails at some point when configuring unenv. Not sure why it's trying to load the package.json from the dist subdirectory when it's actually in the parent folder.

### Expected behavior
Wrangler should upload pages projects.

### Steps to reproduce
Please provide the following:
- Try to upload any pages project with wrangler deploy

### Please provide any relevant error logs

✘ [ERROR] ENOTDIR: not a directory, open '.../node_modules/unenv-nightly/dist/index.cjs/package.json'

**Comment by penalosa** [comment]
Thanks for reporting this! We're investigating—in the meantime downgrading to Wrangler 3.96.0 should be a workaround
