### ISSUE TITLE
Suggest re-logging in when authentication error

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-sdk#761]
Users get an error message when they don't have permission to do something:

```
Received a bad response from the API

Authentication error [code: 10000]

If you think this is a bug, please open an issue at:
https://github.com/cloudflare/wrangler2/issues/new
```

We should suggest re-logging in with `npx wrangler login` and trying again as a first troubleshooting step. This'll be common in particular for the new Pages commands which require a new OAuth grant (given the new additional scopes).

**Comment by threepointone** [comment]
Unfortunately this error comes in a number of situations that aren't related to logging in. We can add the warning, but I hope it doesn't confuse when it doesn't confuse further when it doesn't fix the underlying problem. We should work further on the api side as well giving more specific errors.

**Comment by JacobMGEvans** [comment]
@GregBrimble is this handled by the recent PR that added `requireAuth()` in Pages commands?

**Comment by jspspike** [comment]
Closing this unless a consensus is made to attempt to login, I believe #1197 will help make authentication errors less confusing
