### ISSUE TITLE
🐛 BUG(miniflare): Diacritics in IP geolocation headers causing problems

### ISSUE THREAD

**Issue by Joozty** [cloudflare/workers-sdk#7641]
### Which Cloudflare product(s) does this pertain to?

Miniflare

### What versions are you using?

wrangler 3.99.0

### What operating system and version are you using?

any os

### Describe the Bug

I tried to deploy my Next.js app to Cloudflare Workers, and I followed this [tutorial](https://opennext.js.org/cloudflare). The build completes successfully, but when I try to preview or deploy it, I encounter the following error:

```
Invalid header name or value: "Žilina". Per the Fetch specification, the Headers class may only accept header names and values which contain 8-bit characters. That is, they must not contain any Unicode code points greater than 0xFF. As a quirk, we are encoding this string in UTF-8 in the header, but in a browser this would result in a TypeError exception. Consider encoding this string in ASCII for compatibility with browser implementations of the Fetch specification.
```

Žilina is a city in Slovakia, and I assume that somewhere, a header with this value is being sent. I was able to find the cause, and it throws an error in Miniflare here. I guess the diacritics are causing the problem.

<img width="1422" alt="image" src="https://github.com/user-attachments/assets/0b765d8c-f708-490d-adde-a710131f77b2" />

![image](https://github.com/user-attachments/assets/0b06d435-1513-4b98-9752-566a83f0759c)

**Comment by edmundhung** [comment]
Hi @Joozty,

Could you let us know which version of `@opennextjs/cloudflare` you are using? Also, can you check if upgrading to the latest version resolves the issue?

cc: @vicb

**Comment by Joozty** [comment]
@edmundhung @vicb  I use latest version 0.3.3. I will open the issie in the opennextjs repo. Thx
