### ISSUE TITLE
Investigate using a higher level API for `wrangler dev`

### ISSUE THREAD

**Issue by caass** [cloudflare/workers-sdk#865]
Blocked on #864

`wrangler dev` fails if HTTP/2 is unavailable, rather than falling back to HTTP/1. This causes problems in environments where HTTP/2 is unsupported, such as in StackBlitz.

**Comment by eidam** [comment]
This should not be blocked by #864, as it would work with API token - allowing the full experience, except the login part.

**Comment by penalosa** [comment]
Following up on this, it looks like Stackblitz doesn't currently support the `http2` module, which Wrangler depends on

**Comment by caass** [comment]
Wait, so what's the current status of this? Is the "quick win" to gracefully fallback to http/1.1 when http/2 is unsupported?

**Comment by penalosa** [comment]
This isn't really a quick win—the problem is that we rely on the `http2` module for remote mode. Fixing it would require rewriting most of remote mode

**Comment by penalosa** [comment]
Following up to track status on this: this involves investigating whether we can use `fetch` or similar APIs rather than the `http2` module
